CHANGELOG.md
crates/rome_diagnostics_categories/src/categories.rs
crates/rome_js_analyze/src/analyzers/nursery.rs
crates/rome_js_analyze/src/analyzers/nursery/use_getter_return.rs
crates/rome_js_analyze/tests/specs/nursery/useGetterReturn/invalid.js
crates/rome_js_analyze/tests/specs/nursery/useGetterReturn/invalid.js.snap
crates/rome_js_analyze/tests/specs/nursery/useGetterReturn/valid.js
crates/rome_js_analyze/tests/specs/nursery/useGetterReturn/valid.js.snap
crates/rome_service/src/configuration/linter/rules.rs
crates/rome_service/src/configuration/parse/json/rules.rs
editors/vscode/configuration_schema.json
packages/@biomejs/backend-jsonrpc/src/workspace.ts
packages/@biomejs/biome/configuration_schema.json
website/src/components/generated/NumberOfRules.astro
website/src/pages/lint/rules/index.mdx
website/src/pages/lint/rules/useGetterReturn.md

This implements [getter-return](https://eslint.org/docs/latest/rules/getter-return).
We don't support the option `allowImplicit` (disabled by default).
In contrast to the ESlint rule we do not report the dynamic cases such as:
```js
Object.defineProperty(foo, 'bar', {
get(){}
});
```
_ESlint_ tests included and more complex cases (with exception handlers and loops).

feat(rome_js_analyze): useGetterReturn

---

crates/rome_js_analyze/src/analyzers/style/use_enum_initializers.rs
crates/rome_js_analyze/tests/specs/style/useEnumInitializers/invalid.ts
crates/rome_js_analyze/tests/specs/style/useEnumInitializers/invalid.ts.snap
crates/rome_js_analyze/tests/specs/style/useEnumInitializers/valid.ts
crates/rome_js_analyze/tests/specs/style/useEnumInitializers/valid.ts.snap
crates/rome_js_syntax/src/declaration_ext.rs
crates/rome_js_syntax/src/lib.rs

Fixes #19.
New tests included.

fix(lint/useEnumInitailizers): ignore enum in ambient namespaces

---

crates/rome_js_analyze/src/semantic_analyzers/nursery/no_unsafe_declaration_merging.rs
crates/rome_js_analyze/tests/specs/nursery/noUnsafeDeclarationMerging/valid.ts
crates/rome_js_analyze/tests/specs/nursery/noUnsafeDeclarationMerging/valid.ts.snap
crates/rome_js_syntax/src/declaration_ext.rs

This is related to #19 but concerns noUnsafeDeclarationMerging.
This correctly recognizes ambient classes in ambient context.
Thus, the following code is not reported as unsafe because merging an ambient class and an interface is safe:
```
declare namespace A {
namespace B {
export interface Foo {}
export class Foo {}
}
}
```
Tests included.

fix(lint/noUnsafeDeclarationMerging): recoggnize ambient classes in ambient namespace

---

CHANGELOG.md
crates/rome_diagnostics_categories/src/categories.rs
crates/rome_js_analyze/src/semantic_analyzers/nursery.rs
crates/rome_js_analyze/src/semantic_analyzers/nursery/no_useless_this_alias.rs
crates/rome_js_analyze/tests/specs/nursery/noUselessThisAlias/invalid.js
crates/rome_js_analyze/tests/specs/nursery/noUselessThisAlias/invalid.js.snap
crates/rome_js_analyze/tests/specs/nursery/noUselessThisAlias/valid.js
crates/rome_js_analyze/tests/specs/nursery/noUselessThisAlias/valid.js.snap
crates/rome_service/src/configuration/linter/rules.rs
crates/rome_service/src/configuration/parse/json/rules.rs
editors/vscode/configuration_schema.json
packages/@biomejs/backend-jsonrpc/src/workspace.ts
packages/@biomejs/biome/configuration_schema.json
website/src/components/generated/NumberOfRules.astro
website/src/pages/blog/biome-v1.mdx
website/src/pages/internals/changelog.mdx
website/src/pages/lint/rules/index.mdx
website/src/pages/lint/rules/noUselessThisAlias.md

This closes [rome#4481](https://github.com/rome/tools/issues/4481) by implementing `noUselessThisAlias`.
As discussed in [rome#4481](https://github.com/rome/tools/issues/4481) we diverge from [eslint](https://typescript-eslint.io/rules/no-this-alias/) and unicorn by allowing `this` aliasing where required.
The rule ignores complex cases such as:
```js
function f() {
const [self] = [this];
return () => {
self.g();
}
}
```
The rule could be smarter. However, this code is unlikely to exist.
Tests included.

feat(lint): noUselessThisAlias

---

.github/workflows/release_cli.yml
.github/workflows/release_js_api.yml

I added the `--provenance` flag to publish provenance data alongside the package.
> Starting today, when you build your npm projects on GitHub Actions, you can publish provenance alongside your package by including the --provenance flag. This provenance data gives consumers a verifiable way to link a package back to its source repository and the specific build instructions used to publish it (see example on npmjs.com).
see: [Introducing npm package provenance](https://github.blog/2023-04-19-introducing-npm-package-provenance/)

chore: add --provenance flag to the npm publish command

---

CHANGELOG.md
crates/rome_lsp/src/handlers/analysis.rs
crates/rome_lsp/tests/server.rs
crates/rome_service/src/workspace.rs
website/src/pages/internals/changelog.mdx

This PR avoids applying unsafe fixes when quickfixes are triggered on-save.
Unsafe quickfixes are still available in the IDE via direct invocation. 

fix(lsp): don't apply unsafe quick fixes on-save

---

.github/labeler.yml

Add automatic labeling with label `A-Changelog` when the changelog is edited.
This allows quickly identifying PRs without changelog entry. 
CI

ci(labeler): add A-Changelog label

---

crates/rome_service/src/file_handlers/mod.rs
editors/vscode/package.json
editors/vscode/src/main.ts

Fixes the VSCode extension. It enables and recognises the extension for `jsonc` files.
I tested manually by creating a JSON file

fix(vscode): enable and recognise JSONC files

---

website/src/styles/_blog.scss

Hello everyone,
Congrats on the fork and thank you for the library in the first place.
While surfing the blog posts I've come around this visual bug:
So I fixed it very quickly by changing avatars' z-indexes.
I think I could achieve the same result by bumping up header's z-index as well (or uniquely that), let me know if you'd prefer this way and I'll gladly change it.
Thank you!

fix(website): avatar overlapping with header nav

---

.github/workflows/pull_request.yml
.github/workflows/release_cli.yml
.github/workflows/release_js_api.yml
.github/workflows/release_lsp.yml
.github/workflows/website_deploy_preview.yml
.github/workflows/website_deploy_prod.yml
scripts/print-changelog.sh

This PR updates the release workflows.
GitHub Release notes are now generated from the changelog.
The script extract the first subsection that starts with a digit, e.g. `## 1.1.0`. This allows to skip `## Unreleased`. 
The changelog should be updated before every release.
I also removed useless `fetch-depth` parameter that is [set to `1` by default](https://github.com/actions/checkout).
Next release.

ci: extract changelog for GitHub release notes

---

CHANGELOG.md
crates/rome_js_analyze/src/analyzers/suspicious/no_duplicate_jsx_props.rs
crates/rome_js_analyze/tests/specs/suspicious/noDuplicateJsxProps/invalid.jsx
crates/rome_js_analyze/tests/specs/suspicious/noDuplicateJsxProps/invalid.jsx.snap
crates/rome_js_analyze/tests/specs/suspicious/noDuplicateJsxProps/valid.jsx
crates/rome_js_analyze/tests/specs/suspicious/noDuplicateJsxProps/valid.jsx.snap
website/src/pages/internals/changelog.mdx

fix(lint/noDuplicateJsxProps): make the rule case-sensitive

---

CHANGELOG.md
crates/rome_js_analyze/src/globals/browser.rs
crates/rome_js_analyze/src/globals/node.rs
crates/rome_js_analyze/src/globals/runtime.rs
crates/rome_js_analyze/src/globals/typescript.rs
crates/rome_js_analyze/tests/specs/correctness/noUndeclaredVariables/validTsGlobals.ts
crates/rome_js_analyze/tests/specs/correctness/noUndeclaredVariables/validTsGlobals.ts.snap
website/src/pages/internals/changelog.mdx

Fix #106.
The list of TypeScript globals was sorted in a natural order instead of a byte order.
To avoid this issue I added a test that asserts the order of the list.

fix(lint/noUndeclaredVariables): recognize `Uppercase`

---

website/src/pages/configuration.mdx
website/src/pages/linter/index.mdx

Copy of https://github.com/rome/tools/pull/4782 for Biome. Looks like @ematipico fixed most of the cases in that original PR already, but I found a few stragglers.

docs: fix 'performance reason' typo everywhere left

---

website/src/content/docs/guides/getting-started.mdx

This PR updates/fixes the broken links on the Getting Started page.
* Change working directory to `/website` & run the local dev server:  `pnpm start`
* Navigate to Getting Started screen: `localhost:3000:/getting-started`
* Click previously broken links & ensure they are working:
- under **Installation** section -> *standalone executable*
- under **Configuration** section -> *recommended rules*
- under **Next Steps** section -> *CLI Options* and *configuration options*

docs(website): fix broken links on getting-started

---

crates/rome_js_analyze/src/analyzers/a11y/use_valid_anchor.rs
crates/rome_js_analyze/src/analyzers/complexity/no_useless_constructor.rs
crates/rome_js_analyze/src/analyzers/correctness/no_invalid_constructor_super.rs
crates/rome_js_analyze/src/analyzers/correctness/no_unnecessary_continue.rs
crates/rome_js_analyze/src/analyzers/correctness/no_unsafe_optional_chaining.rs
crates/rome_js_analyze/src/analyzers/nursery/no_nonoctal_decimal_escape.rs
crates/rome_js_analyze/src/analyzers/nursery/use_getter_return.rs
crates/rome_js_analyze/src/analyzers/suspicious/no_async_promise_executor.rs
crates/rome_js_analyze/src/analyzers/suspicious/no_duplicate_case.rs
crates/rome_js_analyze/src/analyzers/suspicious/no_duplicate_class_members.rs
crates/rome_js_analyze/src/analyzers/suspicious/no_self_compare.rs
crates/rome_js_analyze/src/semantic_analyzers/correctness/no_children_prop.rs
crates/rome_js_analyze/src/semantic_analyzers/nursery/no_constant_condition.rs
crates/rome_js_analyze/src/semantic_analyzers/security/no_dangerously_set_inner_html.rs
crates/rome_js_analyze/src/semantic_analyzers/security/no_dangerously_set_inner_html_with_children.rs
crates/rome_js_analyze/src/semantic_analyzers/suspicious/no_array_index_key.rs
crates/rome_js_analyze/src/semantic_analyzers/suspicious/no_catch_assign.rs
crates/rome_js_analyze/src/utils.rs
crates/rome_js_semantic/src/events.rs

- Avoid redundant verifications for `noSelfCompare` and `noDuplicateCase`.
- Avoid some cloning and delay others
- Remove redundant utility `remove_statement`
- Move `ast_utils` under `utils/`
No change.

refactor(analyzer): avoid cloning and redundant checks

---

crates/rome_diagnostics_categories/src/categories.rs

`just new-lintrule` asserts the existence of the `nursery end` comment in `categories.rs`. This pr adds it.
work `just new-lintrule path name`

fix: restore "nursery end" comment in `categories.rs`

---

website/src/styles/playground/_diagnostics.scss

Closes #120
Viewing the code on the Rome site, I noticed that the pre tag contained the overflow property as auto and when I removed it, the scrollbar was the same as on the Biome site.
I decided to assign the property in the diagnostics-console class to select only the pre tag in the playground console, which had a scrolling problem.

fix(website/playground): fix missing scroll

---

crates/rome_cli/src/diagnostics.rs
crates/rome_cli/tests/snapshots/main_cases_config_extends/extends_resolves_when_using_config_path.snap
crates/rome_cli/tests/snapshots/main_commands_check/fs_files_ignore_symlink.snap
crates/rome_cli/tests/snapshots/main_commands_format/custom_config_file_path.snap
crates/rome_cli/tests/snapshots/main_commands_lint/fs_files_ignore_symlink.snap
crates/rome_fs/src/fs.rs
crates/rome_fs/src/lib.rs
crates/rome_service/src/configuration/mod.rs

Closes https://github.com/biomejs/biome/issues/118
I decided not to emit a diagnostic for the presence of a double configuration because it would mean applying the auto-discovery again for a file we wouldn't use, which isn't optimal. 
The change caught a bug, which has been updated.

fix: use `biome.json` instead

---

CHANGELOG.md
crates/rome_js_analyze/src/analyzers/correctness/no_unreachable_super.rs
crates/rome_js_analyze/src/control_flow.rs
crates/rome_js_analyze/tests/specs/correctness/noUnreachableSuper/duplicateSuper.js
crates/rome_js_analyze/tests/specs/correctness/noUnreachableSuper/duplicateSuper.js.snap
crates/rome_js_analyze/tests/specs/correctness/noUnreachableSuper/missingSuper.js
crates/rome_js_analyze/tests/specs/correctness/noUnreachableSuper/missingSuper.js.snap
crates/rome_js_analyze/tests/specs/correctness/noUnreachableSuper/thisBeforeSuper.js
crates/rome_js_analyze/tests/specs/correctness/noUnreachableSuper/thisBeforeSuper.js.snap
crates/rome_js_analyze/tests/specs/correctness/noUnreachableSuper/valid.js
crates/rome_js_analyze/tests/specs/correctness/noUnreachableSuper/valid.js.snap
website/src/content/docs/internals/changelog.mdx
website/src/content/docs/linter/rules/no-unreachable-super.md

Fix [rome#4616](https://github.com/rome/tools/issues/4616).
I take the opportunity to fix an unnoticed bug: the rule assimilated super calls such as `super.method()` to a super call `super()`.
I think that the new implementation is simpler and more robust.
i discovered some cases statically undecidable. For instance the following example:
```js
class A {
constructor(a) {
if (a) { throw new Error(); }
}
}
class B extends A {
constructor() {
try {
super(true);
f();
} catch { super(false); }
}
}
```
As a workaround, I decided to assume that the `try` block has both a `super()` call and no `super()` call when an exception is caught. Thus, the rule reports duplicate `super()` in the previous example.
We could also ignore `catch` blocks. Any thought?
EDIT: [TypeScript uses the same …

fix(lint/noUnreachableSuper): handle complex CFG

---

CHANGELOG.md
crates/rome_js_analyze/src/analyzers/style/no_comma_operator.rs
crates/rome_js_analyze/tests/specs/style/noCommaOperator/valid.jsonc
crates/rome_js_analyze/tests/specs/style/noCommaOperator/valid.jsonc.snap
website/src/content/docs/internals/changelog.mdx

fix(lint/noCommaOperator): ignore update part of for loops

---

packages/@biomejs/biome/bin/biome

Deno cannot directly run Biome via `deno run -A npm:@biomejs/biome check`.
```ts
import child_process from 'node:child_process';
import process from 'node:process';
child_process.spawn(process.execPath, ['bar.js'], {
stdio: [process.stdin, process.stdout, process.stderr]
});
```
deno can not run when env  have a `null` or `undefined` value
May be it is the bug of deno.  https://github.com/denoland/deno/issues/20373
But it can fix this error.
It run correctly when I changed it.

fix: support deno

---

CHANGELOG.md
crates/rome_analyze/src/lib.rs
crates/rome_analyze/src/rule.rs
crates/rome_cli/tests/snapshots/main_commands_check/deprecated_suppression_comment.snap
crates/rome_cli/tests/snapshots/main_commands_lint/deprecated_suppression_comment.snap
crates/rome_diagnostics_categories/src/categories.rs
crates/rome_js_analyze/src/lib.rs
crates/rome_js_analyze/tests/specs/correctness/noUnreachable/SuppressionComments.js.snap
crates/rome_js_analyze/tests/suppression/a11y/useKeyWithClickEvents/invalid.jsx.snap
crates/rome_js_analyze/tests/suppression/correctness/noUndeclaredVariables/noUndeclaredVariables.ts.snap
crates/rome_js_analyze/tests/suppression/correctness/noUnusedVariables/simple.js.snap
crates/rome_js_analyze/tests/suppression/suspicious/noArrayIndexKey/noArrayIndexKey.jsx.snap
crates/rome_js_analyze/tests/suppression/suspicious/noDoubleEquals/noDoubleEquals.js.snap
crates/rome_js_analyze/tests/suppression/suspicious/noDoubleEquals/noDoubleEquals.jsx.snap
crates/rome_js_syntax/src/suppression.rs
crates/rome_lsp/tests/server.rs
packages/@biomejs/backend-jsonrpc/src/workspace.ts
website/src/content/docs/internals/changelog.mdx
website/src/playground/PlaygroundLoader.tsx
website/src/playground/components/Tabs.tsx
website/src/playground/tabs/ControlFlowTab.tsx
website/src/playground/tabs/DiagnosticsConsoleTab.tsx
website/src/playground/tabs/DiagnosticsListTab.tsx
website/src/playground/tabs/SettingsTab.tsx

Closes https://github.com/biomejs/biome/issues/55
Closes https://github.com/biomejs/biome/issues/156
I decided not to emit a code action for updating the comment for now. 
I updated all the tests that involve suppression comments. I updated tests to track the new suppression diagnostic.

feat: `biome-ignore` as suppression comment

---

.github/workflows/main.yml
.github/workflows/pull_request.yml
CHANGELOG.md
Cargo.toml
crates/rome_analyze/src/lib.rs
crates/rome_cli/Cargo.toml
crates/rome_cli/src/commands/daemon.rs
crates/rome_cli/tests/snapshots/main_commands_check/deprecated_suppression_comment.snap
crates/rome_cli/tests/snapshots/main_commands_lint/deprecated_suppression_comment.snap
crates/rome_console/Cargo.toml
crates/rome_js_analyze/Cargo.toml
crates/rome_js_semantic/Cargo.toml
crates/rome_js_transform/Cargo.toml
crates/rome_json_analyze/Cargo.toml
editors/vscode/package.json
packages/@biomejs/biome/package.json
website/src/content/docs/internals/changelog.mdx

Emitting a diagnostic warning for `// rome-ignore` was a bad idea. Context: https://discord.com/channels/1132231889290285117/1149249347276517386
This PR downgrades the diagnostic to information severity. We lose the code action, but this fix won't block user's CI.
`just ready`
Manually tested the LSP:

release: 1.1.1

---

CHANGELOG.md
crates/rome_service/src/file_handlers/json.rs
editors/vscode/package.json
packages/@biomejs/biome/package.json
website/src/content/docs/internals/changelog.mdx

Fixes an urgent bug, where the extension would crash when opening an empty JSON file.
Tested manually https://discord.com/channels/1132231889290285117/1149398718345396276/1149404400746512517

release: 1.1.2

---

CHANGELOG.md
crates/rome_control_flow/src/builder.rs
crates/rome_control_flow/src/lib.rs
crates/rome_js_analyze/src/analyzers/correctness/no_unreachable.rs
crates/rome_js_analyze/src/analyzers/correctness/no_unreachable_super.rs
crates/rome_js_analyze/src/analyzers/nursery/no_fallthrough_switch_clause.rs
crates/rome_js_analyze/src/analyzers/nursery/use_getter_return.rs
crates/rome_js_analyze/tests/specs/nursery/noFallthroughSwitchClause/invalid.js
crates/rome_js_analyze/tests/specs/nursery/noFallthroughSwitchClause/invalid.js.snap
crates/rome_js_analyze/tests/specs/nursery/noFallthroughSwitchClause/valid.js
crates/rome_js_analyze/tests/specs/nursery/noFallthroughSwitchClause/valid.js.snap
website/src/content/docs/internals/changelog.mdx
website/src/content/docs/linter/rules/no-fallthrough-switch-clause.md

This PR improves `noFallthroughSwitchClause` using the control flow graph query.
Many new tests.

refactor(lint/noFallthroughSwitchClause): use CFG

---

crates/biome_cli/src/commands/init.rs
crates/biome_cli/tests/snapshots/main_commands_init/creates_config_file.snap
crates/biome_cli/tests/snapshots/main_commands_init/creates_config_file_when_rome_installed_via_package_manager.snap

This PR updates broken links displayed on `biome init` 
Fixes: https://github.com/biomejs/biome/issues/202
Run `biome init`

chore: update links displayed in `biome init`, the previous were broken

---

crates/rome_js_analyze/src/semantic_analyzers/correctness/use_is_nan.rs
crates/rome_js_analyze/tests/specs/correctness/useIsNan/invalid.js.snap
website/src/content/docs/linter/rules/use-is-nan.md

Closes #96 
Provide code fix for useIsNaN rule:
```diff
- 123 == NaN
+ Number.isNaN(123)
```
```diff
- 123 === NaN
+ Number.isNaN(123)
```
```diff
- 123 !== NaN
+ !Number.isNaN(123)
```
```diff
- 123 != NaN
+ !Number.isNaN(123)
```
Should this rule support other operators like > < >= <=?

feat(lint/useIsNan): add code fix action

---

crates/biome_js_semantic/src/events.rs
crates/biome_js_semantic/src/semantic_model/builder.rs
crates/biome_js_semantic/src/semantic_model/model.rs
crates/biome_js_semantic/src/semantic_model/reference.rs
crates/biome_js_semantic/src/semantic_model/scope.rs
crates/rome_js_analyze/src/analyzers/nursery/no_confusing_void_type.rs
website/src/content/docs/linter/rules/no-confusing-void-type.md

fix(lint/noConfusingVoidType): separate invalid examples

---

editors/vscode/package-lock.json
editors/vscode/package.json

As discussed in https://github.com/biomejs/biome/discussions/230.
This PR lowers the minimal engine version for the VS Code extension to `1.80.0`.

feat(vscode): lower minimum engine version to `1.80.0`

---

CHANGELOG.md
crates/rome_js_analyze/src/react/hooks.rs
crates/rome_js_analyze/tests/specs/nursery/useExhaustiveDependencies/newline.js
crates/rome_js_analyze/tests/specs/nursery/useExhaustiveDependencies/newline.js.snap
website/src/content/docs/internals/changelog.mdx

Fix #168
`cargo test -p rome_js_analyze`

fix(analyzer): useExhaustiveDependencies error when useState is on a new line #168

---

.gitignore
.vscode/extensions.json
.vscode/launch.json
.vscode/tasks.json
CONTRIBUTING.md

This PR introduces a VS Code configuration that aims to improve the development experience of the Biome extension.
https://github.com/biomejs/biome/assets/649677/302c8639-291c-49c8-a372-57ca4ef4a5ff

chore: improve vscode extension debug dx

---

CHANGELOG.md
crates/biome_js_semantic/src/events.rs
crates/biome_rowan/src/ast/batch.rs
crates/rome_js_analyze/tests/specs/suspicious/noRedeclare/valid-modules.ts
crates/rome_js_analyze/tests/specs/suspicious/noRedeclare/valid-modules.ts.snap
website/src/content/docs/internals/changelog.mdx

Fix https://github.com/biomejs/biome/issues/137
`cargo test -p rome_js_analyze`

fix(analyzer): noRedeclare breaks *.d.ts files

---

CHANGELOG.md
crates/rome_js_analyze/src/analyzers/nursery/use_collapsed_else_if.rs
crates/rome_js_analyze/tests/specs/nursery/useCollapsedElseIf/invalid.js.snap
website/src/content/docs/internals/changelog.mdx
website/src/content/docs/linter/rules/use-collapsed-else-if.md

Remove unsafe code fixes. The rule now only provides safe code fixes.
Updated tests.

refactor(lint/useCollapsedElseIf): remove unsafe code fixes

---

crates/biome_lsp/src/handlers/analysis.rs
crates/biome_lsp/tests/server.rs

This PR resolves an issue that was blocking #185 
As biome_lsp only need to avoid unsafe fixes when the code action is on-save quick-fixes, I changed the logic a little, to check if the value is 'quickfix.biome' instead of 'quickfix'
Now Intellij can pull all actions of kind 'quickfix' and vscode will not apply unsafe fixes on-save

fix(biome-lsp): only filter quickactions when action category is 'quickfix.biome'

---

editors/vscode/package.json

Related to #249 
I forgot to add the `--no-dependencies` flag to the build script in the CI.
To fix this globally, I've set the setting in the `vsce` key of the extension's `package.json`
I ran the [pipeline](https://github.com/nhedger/biome/actions/runs/6159195934) on my fork

ci(release_lsp): fix extension packaging

---

.github/release.yml
CHANGELOG.md
CONTRIBUTING.md
crates/biome_js_analyze/src/analyzers/nursery/no_confusing_void_type.rs
crates/biome_js_analyze/src/analyzers/nursery/use_collapsed_else_if.rs
justfile
scripts/print-changelog.sh
website/src/content/docs/internals/changelog.mdx
website/src/content/docs/linter/rules/no-confusing-void-type.md
website/src/content/docs/linter/rules/use-collapsed-else-if.md

This PR should improve the generation of release notes.
As before, we extract the changelog part of a release and append the generated GitHub notes. However, we now exclude all PRs labelled by `A-Changelog` ~or `S-Needs-changelog-update`~. The idea is to avoid including changelog entry already present in what we extracted.
To keep the computed Contributors section up-to-date, I propose adding who contributed to a change directly in the CHANGELOG. I updated some entries to give an example. If we decide to use this convention, I will update the rest of the CHANGELOG.
I updated the _changelog_ section of the CONTRIBUTING guide.   
I improved the script that extracts a changelog entry by always extracting the first section instead of looking for `Unreleased`. This should make the script more …

chore: improve changelog generation

---

.github/workflows/bench_analyzer.yml
.github/workflows/bench_cli.yml
.github/workflows/bench_formatter.yml
.github/workflows/bench_parser.yml
.github/workflows/main.yml
.github/workflows/parser_conformance.yml
.github/workflows/pull_request.yml
.github/workflows/pull_request_js.yml
.github/workflows/release_cli.yml
.github/workflows/release_js_api.yml
.github/workflows/release_lsp.yml
.github/workflows/runtime.yml
.github/workflows/website_deploy_preview.yml
.github/workflows/website_deploy_prod.yml

- Upgrade action versions
- remove settings set to their default
- cancel current jobs when a PR is updated (hopefully freeing some runners)
- deploy website only when the `website` folder is changed
CI

ci: update workflow deps and cancel jobs on PR update

---

.github/workflows/pull_request_cleanup_cache.yml

This forces the deletion of a PR cache when a PR is closed (or merged).
The code comes from [GitHub docs](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#force-deleting-cache-entries).
CI.

ci: cleanup cache when a PR is closed

---

CHANGELOG.md
crates/biome_cli/tests/commands/check.rs
crates/biome_cli/tests/snapshots/main_commands_check/use_literal_keys_should_emit_correct_ast_issue_266.snap
crates/biome_js_analyze/src/analyzers/complexity/use_literal_keys.rs
crates/biome_js_analyze/src/lib.rs
website/src/content/docs/internals/changelog.mdx

Closes https://github.com/biomejs/biome/issues/266
Added a CLI test, because that's where it happens.

fix(lint/useLiteralKeys): emit correct AST for assignment expressions

---

editors/vscode/package.json
editors/vscode/src/main.ts

This PR fixes an issue where the VS Code extension cannot resolve the path to the biome CLI when using certain package managers, notably pnpm.
The new strategy is to point to the `node_modules/.bin/biome` path, which is consistent for all package managers.
---
I'd like some help to test under Windows, I don't have a machine handy.

fix(vscode): server bin path resolution

---

packages/@biomejs/backend-jsonrpc/src/command.ts
packages/@biomejs/biome/scripts/postinstall.js

Postinstall script fails to find the right executable 
```
The Biome CLI postinstall script failed to resolve the binary file "@biomejs/cli-linux-x64/rome". Running Biome from the npm package will probably not work correctly.
```

fix(cli): set the right name for binary executable

---

CHANGELOG.md
website/src/content/docs/internals/changelog.mdx

GitHub Release Notes doesn't recognize contributor mentions if they are inside a link.

chore: update CHANGELOG mentions

---

crates/biome_js_formatter/src/generated.rs
crates/biome_json_formatter/src/generated.rs
xtask/codegen/src/formatter.rs

Closes #240 by suppressing clippy lint `default_constructed_unit_structs`.
Added `#![allow(clippy::default_constructed_unit_structs)]`
`cargo codegen formatter` then `just l` works

fix(formatter): suppress `default_constructed_unit_structs` on formatter generated code

---

CHANGELOG.md
crates/biome_js_analyze/src/analyzers/nursery/no_confusing_void_type.rs
crates/biome_js_analyze/tests/specs/nursery/noConfusingVoidType/valid.ts
crates/biome_js_analyze/tests/specs/nursery/noConfusingVoidType/valid.ts.snap
website/src/content/docs/internals/changelog.mdx

Solves issue with raising error on function type.
Fix #294
Added a new test case in `valid.ts` to verify the functionality is working fine.

fix: void error on type of a function declaration

---

pnpm-lock.yaml
website/astro.config.ts
website/package.json
website/src/content/docs/guides/big-projects.mdx
website/src/content/docs/guides/getting-started.mdx
website/src/content/docs/guides/manual-installation.mdx
website/src/env.d.ts
website/src/playground/PlaygroundLoader.tsx
website/src/playground/tabs/FormatterCodeTab.tsx
website/src/playground/tabs/ImportSortingTab.tsx
website/src/playground/tabs/SettingsTab.tsx
website/src/playground/utils.ts
website/src/playground/workers/biomeWorker.ts
website/src/playground/workers/prettierWorker.ts

This PR creates a guide that explain how use the tool inside big projects. It explains:
- how Biome resolves the configuration files;
- how someone can leverage `extends` to break down the configuration files;
Proof read and merge

 docs: new guide on how to use biome in big projects 

---

.github/workflows/parser_conformance.yml
CHANGELOG.md
crates/biome_js_formatter/src/ts/types/infer_type.rs
crates/biome_js_parser/src/syntax/class.rs
crates/biome_js_parser/src/syntax/function.rs
crates/biome_js_parser/src/syntax/jsx/mod.rs
crates/biome_js_parser/src/syntax/object.rs
crates/biome_js_parser/src/syntax/stmt.rs
crates/biome_js_parser/src/syntax/typescript.rs
crates/biome_js_parser/src/syntax/typescript/statement.rs
crates/biome_js_parser/src/syntax/typescript/ts_parse_error.rs
crates/biome_js_parser/src/syntax/typescript/types.rs
crates/biome_js_parser/src/tests.rs
crates/biome_js_parser/test_data/inline/err/ts_infer_type_not_allowed.rast
crates/biome_js_parser/test_data/inline/err/ts_infer_type_not_allowed.ts
crates/biome_js_parser/test_data/inline/ok/ts_conditional_type.rast
crates/biome_js_parser/test_data/inline/ok/ts_conditional_type.ts
crates/biome_js_parser/test_data/inline/ok/ts_infer_type_allowed.rast
crates/biome_js_parser/test_data/inline/ok/ts_infer_type_allowed.ts
crates/biome_js_parser/test_data/inline/ok/ts_inferred_type.rast
crates/biome_js_parser/test_data/inline/ok/ts_inferred_type.ts
website/src/content/docs/internals/changelog.mdx

The 'infer' keyword can only be utilized within the 'extends' clause of a conditional type. Using it outside of this context will result in an error. Ensure that any type declarations using 'infer' are correctly placed within the conditional type structure to avoid parsing issues.
Added an error message from the typescript for such cases:
`'infer' declarations are only permitted in the 'extends' clause of a conditional type.`
Took test cases from the ts repo:
https://github.com/microsoft/TypeScript/blob/9cbcf010ce0701a25f01a2a074000db34f80cc17/tests/baselines/reference/inferTypes1.errors.txt#L124
https://github.com/microsoft/TypeScript/blob/9cbcf010ce0701a25f01a2a074000db34f80cc17/tests/baselines/reference/templateLiteralTypes1.errors.txt#L5
`cargo test`

feat(js_parser): better diagnostic for infer type #243

---

website/src/content/docs/reference/cli.mdx

Removes `biome formatter` options from `biome lint` help from website.

fix(website): remove formatter options from biome lint

---

CONTRIBUTING.md
GOVERNANCE.md

A first draft of the governance. All @biomejs/core-contributors must approve this PR before being merged.
Review it and approve it

chore: add governance

---

CHANGELOG.md
crates/biome_formatter/src/format_extensions.rs
website/src/content/docs/internals/changelog.mdx

Use OnceCell for the Memoized memory because that's what the RefCell<Option> implemented.
Thank to @MichaReiser 
`cargo test`

refactor(formatter): Use OnceCell in Memoized

---

GOVERNANCE.md

This PR fixes two minor typos in the GOVERNANCE document.

docs(governance): fix typos

---

Cargo.lock
Cargo.toml
crates/biome_console/Cargo.toml
crates/biome_console/src/lib.rs
crates/biome_js_parser/src/lexer/highlight.rs
xtask/coverage/Cargo.toml
xtask/coverage/src/reporters.rs

`atty` has become essentially obsolete because now Rust std has a built-in method: https://doc.rust-lang.org/std/io/trait.IsTerminal.html#tymethod.is_terminal
This PR removes it from the project
CI should pass

chore: remove `atty`

---

.github/workflows/release_lsp.yml

Publish step need to know the build file to avoid create new zip

fix(workflow/release_lsp): added distributionFile parameter

---

CHANGELOG.md
crates/biome_js_analyze/src/analyzers/complexity/no_useless_label.rs
crates/biome_js_analyze/tests/specs/complexity/noUselessLabel/invalid.jsonc.snap
website/src/content/docs/internals/changelog.mdx
website/src/content/docs/linter/rules/no-useless-label.md

The code fix of [noUselessLabel](https://biomejs.dev/linter/rules/no-useless-label) is now safe.
No bug was reported and this does not affect the behavior of the program.
Updated tests.

refactor(lint/noUselessLabel): make code fix safe

---

CHANGELOG.md
crates/biome_js_analyze/tests/specs/correctness/noUndeclaredVariables/infer.ts
crates/biome_js_analyze/tests/specs/correctness/noUndeclaredVariables/infer.ts.snap
crates/biome_js_analyze/tests/specs/correctness/noUndeclaredVariables/infer_incorrect.ts
crates/biome_js_analyze/tests/specs/correctness/noUndeclaredVariables/infer_incorrect.ts.snap
crates/biome_js_semantic/src/events.rs
crates/biome_js_semantic/src/semantic_model/scope.rs
crates/biome_js_semantic/src/tests/infer.rs
crates/biome_js_semantic/src/tests/mod.rs
crates/biome_js_semantic/src/tests/scopes.rs
crates/biome_js_syntax/src/type_ext.rs
pnpm-lock.yaml
website/src/content/docs/internals/changelog.mdx

Fix https://github.com/biomejs/biome/issues/243
We don't need to check the correct position of infer types in semantics because our parser raises an error if they are in an invalid position. #308
Thank to @strager for the explanation.
`cargo test`

fix(analyzer): False positive in rule noUndeclaredVariables #243

---

crates/biome_js_analyze/src/aria_analyzers/a11y/no_redundant_roles.rs
crates/biome_js_analyze/tests/specs/a11y/noRedundantRoles/invalid.jsx.snap
website/src/content/docs/linter/rules/no-redundant-roles.md

Closes #361 
This PR adds a quick explanation to the diagnostic message for `noRedundantRole` on why it is actually redundant.

chore: improve diagnostic message for `noRedundantRoles`

---

.github/workflows/release_lsp.yml

Added missing prerelease output to avoid create gh releases for nightly versions

fix(workflow/release_lsp): added prerelease output

---

CHANGELOG.md
crates/biome_js_analyze/src/analyzers/complexity/no_multiple_spaces_in_regular_expression_literals.rs
crates/biome_js_analyze/tests/specs/complexity/noMultipleSpacesInRegularExpressionLiterals/invalid.jsonc
crates/biome_js_analyze/tests/specs/complexity/noMultipleSpacesInRegularExpressionLiterals/invalid.jsonc.snap
crates/biome_service/src/configuration/linter/rules.rs
editors/vscode/configuration_schema.json
packages/@biomejs/backend-jsonrpc/src/workspace.ts
packages/@biomejs/biome/configuration_schema.json
website/src/content/docs/internals/changelog.mdx
website/src/content/docs/linter/rules/index.mdx
website/src/content/docs/linter/rules/no-multiple-spaces-in-regular-expression-literals.md

Fixes #383.
Also:
- Improve diagnostics
- Use standard `Range`
The ESLint rule ignores consecutive spaces followed by a quantifier.
I think it is more in line with the rule of updating the quantifier in order to avoid consecutive spaces.
I added more tests, including malformed regexes.

fix(lint/noMultipleSpacesInRegularExpressionLiterals): correctly handle spaces followed by a quantifier

---

CHANGELOG.md
crates/biome_js_analyze/src/analyzers/style/use_enum_initializers.rs
crates/biome_js_analyze/tests/specs/style/useEnumInitializers/invalid.ts
crates/biome_js_analyze/tests/specs/style/useEnumInitializers/invalid.ts.snap
website/src/content/docs/internals/changelog.mdx
website/src/content/docs/linter/rules/use-enum-initializers.md

No bugs were reported for [useEnumInitializers](https://biomejs.dev/linter/rules/use-enum-initializers).
Moreover, its code fix doesn't change the program behavior.
I updated the snapshots and added more tests.

refactor(lint/useEnumInitializers): make code fix safe

---

CHANGELOG.md
crates/biome_cli/tests/snapshots/main_commands_ci/ci_runs_linter_not_formatter_issue_3495.snap
crates/biome_js_analyze/src/semantic_analyzers/style/no_var.rs
crates/biome_js_analyze/src/semantic_analyzers/style/use_const.rs
crates/biome_js_analyze/tests/specs/style/useConst/invalid.jsonc.snap
crates/biome_js_semantic/src/events.rs
crates/biome_js_syntax/src/stmt_ext.rs
website/src/content/docs/internals/changelog.mdx
website/src/content/docs/linter/rules/use-const.md

The code fix of [useConst](https://biomejs.dev/linter/rules/use-const) seems pretty stable. No bug was reported since several versions. The code fix of the equivalent ESLint rule is safe. Thus, I think it is time to make the code fix of `useCOnst` safe.
I also take the opportunity to reduplicate some code, and improving the diagnostic using `Emphasis`.
Updated tests.

refactor(lint/useConst): make code fix safe

---

.cargo/config.toml
crates/biome_css_parser/src/lexer/mod.rs
crates/biome_diagnostics/src/display.rs
crates/biome_js_parser/src/lexer/mod.rs
crates/biome_markup/src/lib.rs

This enables the 3 following clippy rules:
- [large_types_passed_by_value](https://rust-lang.github.io/rust-clippy/master/#/large_types_passed_by_value?levels=allow,deny,none&groups=pedantic) reports large copyable types passed by value (we had no instance of this)
- [unnecessary_box_returns](https://rust-lang.github.io/rust-clippy/master/#/unnecessary_box_returns?levels=allow,deny,none&groups=pedantic) reports useless boxing (we had no instance of this)
- [unreadable_literal](https://rust-lang.github.io/rust-clippy/master/#/unreadable_literal) that ensures grouping of digit for better readability.
`cargo test`, `just lint`, `cargo build`, `just codegen`.

refactor: enable more Clippy rules

---

crates/biome_js_analyze/src/analyzers/complexity/no_multiple_spaces_in_regular_expression_literals.rs
crates/biome_js_analyze/tests/specs/complexity/noMultipleSpacesInRegularExpressionLiterals/invalid.jsonc
crates/biome_js_analyze/tests/specs/complexity/noMultipleSpacesInRegularExpressionLiterals/invalid.jsonc.snap

I had a wrong assumption about invalid range. In fact they are ignored and considered as regular characters.
This PR handle now its cases.
Updated tests.

fix(lint/noMultipleSpacesInRegularExpressionLiterals): handle invalid range as regular chars

---

CHANGELOG.md
crates/biome_js_analyze/src/analyzers/complexity/no_useless_label.rs
crates/biome_js_analyze/src/analyzers/correctness/no_unused_labels.rs
crates/biome_js_analyze/tests/specs/correctness/noUnusedLabels/invalid.js
crates/biome_js_analyze/tests/specs/correctness/noUnusedLabels/invalid.js.snap
crates/biome_js_analyze/tests/specs/correctness/noUnusedLabels/valid.js
crates/biome_js_analyze/tests/specs/correctness/noUnusedLabels/valid.js.snap
website/src/content/docs/internals/changelog.mdx
website/src/content/docs/linter/rules/no-unused-labels.md

Make code fix of [noUnusedLabels](https://biomejs.dev/linter/rules/no-unused-labels).
I also improved the implementation by reducing the memory usage of the visitor.
The mutation also uses safer API.
By the way, I wonder if we should reduce the scope of the rule.
For now the rule applies to all labeled statements. However, there are some labeled statement that always unused by nature.
For example:
```js
function sqrt(n) {
DEV: assert(n >= 0);
}
```
We could only report breakable statements (basically statement that can contain other statements)?
Non-breakable statements (and some breakable statements) are already covered by [noConfusingLabels](https://biomejs.dev/linter/rules/no-confusing-labels).
Any though?
Tests updated.

refactor(lint/noUnusedLabels): make code fix safe

---

website/src/content/docs/reference/cli.mdx

In #400, it says that the npm package is `@biomejs/biome`, not `biome`.

docs: `npx biome` -> `npx @biomejs/biome`

---

CHANGELOG.md
crates/biome_js_analyze/src/analyzers/nursery/no_empty_character_class_in_regex.rs
crates/biome_js_analyze/src/analyzers/suspicious/no_control_characters_in_regex.rs
crates/biome_js_formatter/src/utils/assignment_like.rs
crates/biome_js_syntax/src/expr_ext.rs
website/src/content/docs/internals/changelog.mdx

fix(lint): handle malformed reegxes

---

website/astro.config.ts
website/src/content/docs/recipes/continuous-integration.mdx

This PR adds documentation for `setup-biome` and closes #380.

docs: add documentation for `setup-biome`

---

CHANGELOG.md
crates/biome_js_analyze/src/semantic_analyzers/correctness/no_unused_variables.rs
crates/biome_js_analyze/src/semantic_analyzers/nursery/use_exhaustive_dependencies.rs
crates/biome_js_analyze/src/semantic_analyzers/style/use_naming_convention.rs
crates/biome_js_analyze/tests/specs/correctness/noUnusedVariables/invalidTypeParam.ts
crates/biome_js_analyze/tests/specs/correctness/noUnusedVariables/invalidTypeParam.ts.snap
crates/biome_js_analyze/tests/specs/correctness/noUnusedVariables/validTypeParam.ts
crates/biome_js_analyze/tests/specs/correctness/noUnusedVariables/validTypeParam.ts.snap
crates/biome_js_semantic/src/events.rs
crates/biome_js_syntax/src/binding_ext.rs
website/src/content/docs/internals/changelog.mdx
website/src/content/docs/linter/rules/no-unused-variables.md

This PR enhances [noUnusedVariables](https://biomejs.dev/linter/rules/no-unused-variables) by handling unused type parameters.
New tests added.

refactor(lint/noUnusedVariables): report unused type params

---

CHANGELOG.md
crates/biome_js_analyze/src/analyzers/suspicious/no_redundant_use_strict.rs
crates/biome_js_analyze/src/semantic_analyzers/nursery/no_unused_imports.rs
crates/biome_js_analyze/src/utils/batch.rs
crates/biome_js_analyze/tests/specs/suspicious/noRedundantUseStrict/invalid.cjs.snap
crates/biome_js_analyze/tests/specs/suspicious/noRedundantUseStrict/invalid.js
crates/biome_js_analyze/tests/specs/suspicious/noRedundantUseStrict/invalid.js.snap
crates/biome_js_analyze/tests/specs/suspicious/noRedundantUseStrict/invalid.ts.snap
crates/biome_js_analyze/tests/specs/suspicious/noRedundantUseStrict/invalidClass.cjs.snap
crates/biome_js_analyze/tests/specs/suspicious/noRedundantUseStrict/invalidFunction.cjs.snap
crates/biome_js_analyze/tests/specs/suspicious/noRedundantUseStrict/invalidFunction.js.snap
website/src/content/docs/internals/changelog.mdx
website/src/content/docs/linter/rules/no-redundant-use-strict.md

fix(lint/noRedundantUseStrict): keep leading comments

---

website/src/playground/workers/biomeWorker.ts

I was testing the formatter and realized that the indent width was not being applied
https://github.com/biomejs/biome/assets/78874691/7e657ad2-98ba-4ce6-be59-d3791aab62c9
Manually tested the playground

fix(playground): indent width is not being applied

---

editors/vscode/src/main.ts

Related with [#429 ] issue. I just found that `function getSocket` at `main.ts` creating process with command of path into Biome binary file. However, the command would fail when user has space at their username/directory (in my case, windows path). So I'm just add double quotations mark in the command.
before
```
async function getSocket(
outputChannel: OutputChannel,
command: string,
): Promise<string> {
const process = spawn(command, ["__print_socket"], {
stdio: [null, "pipe", "pipe"],
shell: true,
});
```
after
```
async function getSocket(
outputChannel: OutputChannel,
command: string,
): Promise<string> {
const process = spawn(`"${command}"`, ["__print_socket"], {
stdio: [null, "pipe", "pipe"],
shell: true,
});
```
And the extension just work as it should be,

fix(vscode): unknown command when running biome with space separated username or directories

---

CHANGELOG.md
crates/biome_cli/src/commands/mod.rs
crates/biome_cli/src/commands/rage.rs
crates/biome_cli/src/lib.rs
crates/biome_cli/src/main.rs
crates/biome_cli/tests/commands/rage.rs
crates/biome_cli/tests/snapshots/main_commands_rage/rage_help.snap
crates/biome_cli/tests/snapshots/main_commands_rage/with_server_logs.snap
crates/biome_lsp/src/server.rs
website/src/content/docs/internals/changelog.mdx
xtask/codegen/src/main.rs

This PR adds option `--daemon-logs` to `biome rage`.
The `--daemon-logs` option is required to view Biome daemon server logs.
And the diff contains some tiny typo fixes.
Closes #296 
`just test-crate biome_cli`

feat(cli): add `biome rage --daemon-logs` option

---

editors/vscode/src/main.ts

This PR attempts to fix recently reported issues regarding the Biome VS Code extension.
Instead of relying on the `node_modules/.bin` folder and a shell to run the biome CLI, this PR leverages Node's `createRequire` function to create a module resolver scoped to the `@biomejs/biome` npm package. This allows us to resolve `@biomejs/cli-*-*` packages reliably across package managers.
I'm hoping this will fix:
1. Spawn issues
2. Resolution when using pnpm
Related issues: https://github.com/biomejs/biome/issues/332, https://github.com/biomejs/biome/issues/293

fix(vscode): biome resolution

---

.github/workflows/release_lsp.yml

The `test-ui-intellij` job does not exist and makes the workflow fail because it appears in the `needs` of the `build-intellij` job.

ci(release_lsp): remove unknown job dependency

---

crates/biome_js_analyze/src/assists/correctness/organize_imports.rs
crates/biome_js_analyze/src/react.rs
crates/biome_js_syntax/src/import_ext.rs

Improve the code of the organize import action.
The PR de-duplicates code by moving it in `biome_js_syntax` and replaces `source_is` by `source_text`.
No change.

refactor(organize_import): code cleanup

---

CHANGELOG.md
crates/biome_js_analyze/src/assists/correctness/organize_imports.rs
crates/biome_js_analyze/tests/specs/correctness/organizeImports/groups.js
crates/biome_js_analyze/tests/specs/correctness/organizeImports/groups.js.snap
website/src/content/docs/analyzer/index.mdx
website/src/content/docs/internals/changelog.mdx

Fix #449.
I added the following categories:
- `bun:`. Bunjs has recently gained a lot of traction. I think it could be great to handle `bun:` imports.
I placed `bun:` imports just before `node:`. In this way we have a lexicographic order between `bun`, `node`, and `npm`.
- Absolute imports such as `/path`.
I placed it just before the URLs.
- [Node's subpath import](https://nodejs.org/api/packages.html#subpath-imports) `#import`
They are placed just after the libraries and just before the relative imports because they generally redirect to a relative path or a library.
I updated the related website page.
I noticed that we recognize implicitly exported node built-in modules as node modules. This contradicts what the documentation says: `built-in Node.js modules that are explicitly imported …

feat(organize_imports): support `bun:`, `#`, absolute imports

---

crates/biome_aria/src/roles.rs
crates/biome_formatter/src/buffer.rs
crates/biome_formatter/src/comments/builder.rs
crates/biome_js_analyze/src/analyzers/style/use_block_statements.rs
crates/biome_js_formatter/src/ts/declarations/interface_declaration.rs
rust-toolchain.toml
xtask/codegen/src/kinds_src.rs
xtask/coverage/src/compare.rs
xtask/lintdoc/src/main.rs

According to the title.
The current CI should pass.

chore: upgrade Rust to 1.73.0

---

crates/biome_cli/src/commands/mod.rs

As per title
The website will be updated once we will make a release

docs: better documentation for `stdin-file-path`

---

CHANGELOG.md
crates/biome_cli/src/configuration.rs
crates/biome_cli/tests/cases/config_extends.rs
crates/biome_cli/tests/snapshots/main_cases_config_extends/applies_extended_values_in_current_config.snap
crates/biome_cli/tests/snapshots/main_commands_check/check_help.snap
crates/biome_cli/tests/snapshots/main_commands_format/format_help.snap
crates/biome_cli/tests/snapshots/main_commands_lint/lint_help.snap
crates/biome_js_analyze/src/analyzers/nursery/no_excessive_complexity.rs
crates/biome_js_analyze/src/options.rs
crates/biome_js_analyze/src/semantic_analyzers/nursery/use_exhaustive_dependencies.rs
crates/biome_js_analyze/src/semantic_analyzers/style/no_restricted_globals.rs
crates/biome_service/src/configuration/formatter.rs
crates/biome_service/src/configuration/javascript/formatter.rs
crates/biome_service/src/configuration/javascript/mod.rs
crates/biome_service/src/configuration/json.rs
crates/biome_service/src/configuration/linter/mod.rs
crates/biome_service/src/configuration/linter/rules.rs
crates/biome_service/src/configuration/merge.rs
crates/biome_service/src/configuration/mod.rs
crates/biome_service/src/configuration/organize_imports.rs
crates/biome_service/src/configuration/vcs.rs
website/src/content/docs/internals/changelog.mdx
xtask/codegen/src/generate_configuration.rs

Closes https://github.com/biomejs/biome/issues/343
When I implemented the feature, I implemented it with an incorrect assumption, where `extends` would override the current configuration.
Instead, `extends` should be computed first, and then on top of the result, we should apply the options of `biome.json` file. 
To achieve this, I had to create a new method called `merge_if_not_default`. This was needed to avoid default values overriding what was computed from the `extends`.
I added a new test case, similar to the one of the issue that is closed. The snapshot shows that Biome format the code that correct options.

fix(project): change how `extends` should be applied

---

crates/biome_js_analyze/src/analyzers/nursery/no_useless_lone_block_statements.rs
website/src/content/docs/linter/rules/index.mdx

Add missing fix kind metadata.
CI.

refactor(lint/noUselessLoneBlockStatements): add fix kind metadata

---

crates/biome_js_semantic/src/semantic_model/builder.rs
crates/biome_js_semantic/src/semantic_model/model.rs

Until now, bindings are identified by their text range. Binding text ranges don't overlap.
Thus, bindings can also be identified by the start of their text range.
This PR uses the range start instead of the range as binding identifier.
Tests should pass.

Conaclos(js semantic): use range start as binding identifier

---

CHANGELOG.md
crates/biome_js_analyze/src/analyzers/correctness/no_self_assign.rs
crates/biome_js_analyze/tests/specs/correctness/noSelfAssign/issue548.js
crates/biome_js_analyze/tests/specs/correctness/noSelfAssign/issue548.js.snap
website/src/content/docs/internals/changelog.mdx

Fix #548
regerssion test added.

fix(lint/noSelfAssign): don't panic

---

CHANGELOG.md
crates/biome_cli/src/commands/rage.rs
website/src/content/docs/internals/changelog.mdx

The `rage` command was still printing info around server info
Tested locally, it works as expected now.

fix(cli): `rage` command should not print any logs around servers

---

CHANGELOG.md
crates/biome_cli/tests/commands/lint.rs
crates/biome_cli/tests/snapshots/main_commands_lint/ignore_configured_globals.snap
crates/biome_service/src/file_handlers/javascript.rs
crates/biome_service/src/settings.rs
website/src/content/docs/internals/changelog.mdx

Closes https://github.com/biomejs/biome/issues/555
Updated an existing test with the correct configuration

fix(project): correctly map `globals`

---

editors/intellij/src/main/kotlin/com/github/biomejs/intellijbiome/BiomeUtils.kt

fixes  #552 
On `mac` the node_modules/.bin/biome resolves to a node script
```javascript
#!/usr/bin/env node
const { platform, arch, env, version, release } = process;
const PLATFORMS = {
...
```
On windows it's shell script
```
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
case `uname` in
*CYGWIN*|*MINGW*|*MSYS*) basedir=`cygpath -w "$basedir"`;;
esac
if [ -x "$basedir/node" ]; then
exec "$basedir/node"  "$basedir/../@biomejs/biome/bin/biome" "$@"
else 
exec node  "$basedir/../@biomejs/biome/bin/biome" "$@"
fi
```
Point direct to `@biomejs/biome/bin/biome` node script path
Tested on a Windows VM

fix(intellij): binary resolution on windows

---

CHANGELOG.md
crates/biome_js_analyze/tests/specs/correctness/noUnusedVariables/invalidtypeof.ts
crates/biome_js_analyze/tests/specs/correctness/noUnusedVariables/invalidtypeof.ts.snap
crates/biome_js_analyze/tests/specs/nursery/noUnusedImports/issue557.ts
crates/biome_js_analyze/tests/specs/nursery/noUnusedImports/issue557.ts.snap
crates/biome_js_semantic/src/events.rs
website/src/content/docs/internals/changelog.mdx

Fix #557 
As indicated in the issue, `typeof` can be applied to both a value and an **imported type**.
```ts
import { type A, B } from "";
class C {};
interfcae D {}
typeof A; // valid `A` is an imported type
typeof B;
typeof C;
typeof D; // Invalid `D` is a type but is not imported.
```
New tests added.

fix(lint/noUnusedImports): handle typeof of an imported type

---

.github/workflows/release_cli.yml

Solves #568 
This PR extends the `release_cli` workflow to automatically create a version bump PR on homebrew when we publish a new stable version of the CLI.
@biomejs/core-contributors Because the GitHub Action creates a fork (in the biomejs org) and a pull request, we will need to use a personal access token with the following permissions: `public_repo` and `workflow`. Can any of you guys create such PAT and add it as a secret on this repository with the name `HOMEBREW_BUMP_PR_TOKEN`?

ci(release_cli): add homebrew formula bumper

---

CHANGELOG.md
website/src/content/docs/internals/changelog.mdx

Fix location of some changelog entries.

docs(changelog): fix changelog entry location

---

CHANGELOG.md
crates/biome_js_analyze/src/analyzers/correctness/no_self_assign.rs
crates/biome_js_analyze/src/lib.rs
crates/biome_js_analyze/tests/specs/correctness/noSelfAssign/valid.js
crates/biome_js_analyze/tests/specs/correctness/noSelfAssign/valid.js.snap
website/src/content/docs/internals/changelog.mdx

Closes https://github.com/biomejs/biome/issues/576
Added a stest

fix(noSelfAssign): remove erroneous logic

---

crates/biome_js_analyze/src/semantic_analyzers/style/use_naming_convention.rs
website/src/content/docs/linter/rules/use-naming-convention.md

Fix an error in documentation.
No change.

docs(lint/useNamingConvention): type prop and method names in camelCase

---

crates/biome_js_analyze/src/semantic_analyzers/correctness/use_exhaustive_dependencies.rs
crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/checkHooksImportedFromReact.js.snap
crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/customHook.js.snap
crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/extraDependenciesInvalid.js.snap
crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/missingDependenciesInvalid.js.snap
website/src/content/docs/linter/rules/use-exhaustive-dependencies.md

I noticed while working on a project that there was a slight grammar error in one of the newer rules. This PR fixes that and closes #579
Run linter over the following code, see new message:
```
import {useEffect} from "react";
const Comp = () => {
const test = 0;
useEffect(() => {console.log(test)}, []);
return null;
}
```

chore: fix hook linting message grammar

---

CHANGELOG.md
crates/biome_js_analyze/tests/specs/suspicious/noRedeclare/validMethodTypeParam.ts
crates/biome_js_analyze/tests/specs/suspicious/noRedeclare/validMethodTypeParam.ts.snap
crates/biome_js_semantic/src/events.rs
website/src/content/docs/internals/changelog.mdx

Fix #591.
The PR now create dedicated scope for method signatures. This is already done for function signatures and regular methods.
Regression tests added.

fix(lint/noRedeclare): don't report type params of method signatures

---

crates/biome_service/src/configuration/overrides.rs
crates/biome_service/src/configuration/parse/json/overrides.rs
editors/vscode/configuration_schema.json
packages/@biomejs/backend-jsonrpc/src/workspace.ts
packages/@biomejs/biome/configuration_schema.json

On Discord it was pointed out that the schema of the overrides needed to be corrected.
This PR fixes it by flattening the `Overrides` data structure.
I locally tested it, and it's now correct.

fix(project): changed structure to correctly emit schema for overrides

---

editors/intellij/src/main/kotlin/com/github/biomejs/intellijbiome/BiomeUtils.kt

Fixes https://github.com/biomejs/biome/issues/592
A previous fix modified the packager check to check for a specific package manager which caused crashes in some setup (for example, with Yarn PnP). The packager check is not needed however, when an executable path is manually specified in the plugin settings. 
The logic of the code is the same, I just moved the early return of the executable path to before we do the check for the package using a package manager, which avoids using a package manager at all to find the executable, thereby avoiding the crash.

fix(intellij): binary resolution execution sequence

---

crates/biome_js_analyze/src/analyzers/complexity/no_excessive_cognitive_complexity.rs
crates/biome_js_analyze/src/options.rs
crates/biome_js_analyze/src/semantic_analyzers/correctness/use_exhaustive_dependencies.rs
crates/biome_service/src/configuration/parse/json/linter.rs
crates/biome_service/src/configuration/parse/json/rules.rs
editors/vscode/configuration_schema.json
packages/@biomejs/backend-jsonrpc/src/workspace.ts
packages/@biomejs/biome/configuration_schema.json
xtask/codegen/src/generate_configuration.rs

This PR removes dead code and deduplicate code for linter configuration.
Several visitors were never called and thus outdated. This was the case of `Hooks::visit_array_member` and `Hooks::visit_map`.
There is room for improvement:
- I am not sure why we use visitors here while we create the config.
We create a default config, and so we visit the config to initialize it.
This looks like an abuse of the visitor pattern?
- Methods such `map_to_*` don't use `self`.
We should remove `self` from their parameters, this could simplify mutation of self fields (because we cannot both call `map_to_*` and mutate a field of `self` by passing it as visitor to `map_to_*`).
- Instead of relying on `visit_member_name` to validate field names, we could directly validate them in `visit_map`.
We have to …

refactor(linter-config): remove dead code and deduplicate code

---

CHANGELOG.md
crates/biome_js_analyze/src/analyzers/suspicious/no_confusing_void_type.rs
crates/biome_js_analyze/tests/specs/suspicious/noConfusingVoidType/invalid.ts
crates/biome_js_analyze/tests/specs/suspicious/noConfusingVoidType/invalid.ts.snap
crates/biome_js_analyze/tests/specs/suspicious/noConfusingVoidType/valid.ts
crates/biome_js_analyze/tests/specs/suspicious/noConfusingVoidType/valid.ts.snap
website/src/content/docs/internals/changelog.mdx
website/src/content/docs/linter/rules/no-confusing-void-type.md

Closes #604
Fix `noConfusingVoidType` 
- to accept generic types in a union type: #604 
- to report void used in generic function type argument: to pass test
`cargo test -p biome_js_analyze no_confusing_void_type`
~~Existing test plans should pass, and add a test case that filed on #604~~
Update test cases by referencing typescript-eslint no-invalid-void-type test cases.

fix(lint): fix `noConfusingVoidType` to accept generic types in a union type

---

CHANGELOG.md
crates/biome_js_formatter/src/js/expressions/arrow_function_expression.rs
crates/biome_js_formatter/tests/specs/js/module/arrow/params.js
crates/biome_js_formatter/tests/specs/js/module/arrow/params.js.snap
crates/biome_js_formatter/tests/specs/prettier/js/arrows/issue-1389-curry.js.snap
website/src/content/docs/internals/changelog.mdx

This PR fixes #303
When arrow functions returns another arrow function, we need to apply same break logic.
- Validate snapshot 😄
- Added test case from issue

fix(formatter): arrow function chain doesn't break

---

crates/biome_cli/tests/snapshots/main_configuration/incorrect_rule_name.snap
crates/biome_deserialize/src/json.rs
crates/biome_deserialize/src/visitor.rs
crates/biome_js_analyze/src/analyzers/complexity/no_excessive_cognitive_complexity.rs
crates/biome_js_analyze/src/semantic_analyzers/correctness/use_exhaustive_dependencies.rs
crates/biome_js_analyze/src/semantic_analyzers/style/no_restricted_globals.rs
crates/biome_js_analyze/src/semantic_analyzers/style/use_naming_convention.rs
crates/biome_js_formatter/src/context.rs
crates/biome_js_formatter/src/context/trailing_comma.rs
crates/biome_service/src/configuration/formatter.rs
crates/biome_service/src/configuration/javascript/formatter.rs
crates/biome_service/src/configuration/javascript/mod.rs
crates/biome_service/src/configuration/json.rs
crates/biome_service/src/configuration/linter/mod.rs
crates/biome_service/src/configuration/mod.rs
crates/biome_service/src/configuration/overrides.rs
crates/biome_service/src/configuration/parse/json/configuration.rs
crates/biome_service/src/configuration/parse/json/files.rs
crates/biome_service/src/configuration/parse/json/formatter.rs
crates/biome_service/src/configuration/parse/json/javascript/formatter.rs
crates/biome_service/src/configuration/parse/json/javascript/mod.rs
crates/biome_service/src/configuration/parse/json/json_impl/mod.rs
crates/biome_service/src/configuration/parse/json/linter.rs
crates/biome_service/src/configuration/parse/json/organize_imports.rs
crates/biome_service/src/configuration/parse/json/overrides.rs
crates/biome_service/src/configuration/parse/json/rules.rs
crates/biome_service/src/configuration/parse/json/vcs.rs
crates/biome_service/src/configuration/vcs.rs
xtask/codegen/src/generate_configuration.rs

- rename `visit_member_value` to `visit_value`
- remove `visit_member_name`
The removal of `visit_member_name` allowed the removal of `has_only_known_keys`.
This utility function is now replaced by `report_unknown_map_key`.
It is called in `visit_map` when an unknown key is detected.
I also replaced `has_only_known_variants` with `report_unknown_variant`.
It is called in `visit_value` when an unknown variant is found.
Ci should pass.
A CLI snapshot was updated because it now correctly report an unknown rule name.

refactor(json_deserailize): remove `visit_member_name`

---

crates/biome_js_analyze/src/semantic_analyzers/correctness/use_exhaustive_dependencies.rs
crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/valid.js
crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/valid.js.snap
website/src/content/docs/linter/rules/use-exhaustive-dependencies.md

fix #609
I tried to solve this problem by looking at the source code for the eslint-plugin-reacts-hooks plugin, Seems to really don't need to check useContext/useSyncExternalStore/useId : 
https://github.com/facebook/react/blob/main/packages/eslint-plugin-react-hooks/src/ExhaustiveDeps.js

fix: bug with useContext/useSyncExternalStore (#609)

---

CHANGELOG.md
crates/biome_aria/src/roles.rs
website/src/content/docs/internals/changelog.mdx

Part of #553
Some a11y roles were missing in biome_aria, so they were added. And, I fixed that the `get_role` method return all roles except abstract roles. 
passing all current tests would be enough.

fix(biome_aria): add more a11y roles and fix get_role method

---

crates/biome_js_parser/src/lexer/mod.rs
crates/biome_js_parser/src/syntax/expr.rs
crates/biome_js_parser/test_data/inline/err/regex.js
crates/biome_js_parser/test_data/inline/err/regex.rast

This is a follow up PR of #619 
Based on https://github.com/biomejs/biome/pull/619#issuecomment-1784409026, I modified the parser to report an error when the u and v flags are used at the same time.
This PR is a follow up PR, so I don't update changelog.
I added some parser tests.

fix(biome_js_parser): report error when using u and v flag at the same time

---

crates/biome_css_parser/src/syntax/parse_error.rs
crates/biome_js_parser/src/syntax/assignment.rs
crates/biome_js_parser/src/syntax/binding.rs
crates/biome_js_parser/src/syntax/js_parse_error.rs
crates/biome_js_parser/src/syntax/jsx/jsx_parse_errors.rs
crates/biome_js_parser/src/syntax/module.rs
crates/biome_js_parser/src/syntax/typescript/ts_parse_error.rs
crates/biome_json_parser/src/syntax.rs
crates/biome_parser/src/diagnostic.rs
crates/biome_service/src/configuration/linter/rules.rs

I removed some indirection and deleted a struct that we don't need anymore. Now we use `ParseDiagnostic` directly to emit messages from the parsing phase.
Current snapshots should stay the same and tests should pass.

refactor(diagnostics): use `ParseDiagnostic`  instead

---

.github/workflows/release_cli.yml

This PR moves the strategy for bumping the Homebrew formula to its own workflow job.

ci(release_cli): move homebrew bump to own job

---

crates/biome_js_analyze/src/analyzers/complexity/no_excessive_cognitive_complexity.rs

Fixes #643.
So apparently there's a confusing behavior where the `SyntaxNode` of a `JsonNumberValue` may contain a trailing space. If it does, calling `.to_string()` on the syntax node will include the space, causing `u8::from_str()` to fail. Calling `.text()` directly on the value doesn't have this issue.
To be honest, it feels like this may be a workaround to a deeper issue, so I'm not entirely sure this is the right fix. Because of this, I also have not yet created a test for it. Is the possibility for trailing spaces in syntax nodes an expected behavior?
I think an extra unit test should be created for this, since it's quite surprising behavior. But right now I'm more concerned about how similar issues could be prevented from (re)occurring. But the right action here depends on whether …

Fix parsing `maxAllowedComplexity`

---

Cargo.lock
crates/biome_cli/Cargo.toml
crates/biome_cli/src/main.rs

I have always been on the fence with this one, but I decided to let it go! 
So far, we have been running `bpaf` using its API `run_inner`. This API is usually meant for testing, not for production. The reason why I was using this internal API is because I wanted to catch the error and decorate it with our diagnostics:
With this PR, we get the current changes:
Another reason why I want to try to apply this change is because I want to implement [auto completion](https://github.com/pacak/bpaf#dynamic-shell-completion), and that requires more control by `bpaf`.
@biomejs/core-contributors @biomejs/maintainers what do you think?

feat(cli): help with colours

---

packages/@biomejs/biome/README.md

This PR refactors a bit the `README.md` of the npm package:
- it adds installation and usage examples
- it moves the documentation paragraph up
- it moves the traits of Biome after the documentation:
- I removed the part about other tools
- I added a trait about not needing Node.js to function
[Proof read](https://github.com/biomejs/biome/blob/refactor/readme/packages/@biomejs/biome/README.md)

chore: refactor readme

---

crates/biome_cli/tests/cases/biome_json_support.rs
crates/biome_cli/tests/cases/included_files.rs
crates/biome_cli/tests/commands/check.rs
crates/biome_cli/tests/commands/ci.rs
crates/biome_cli/tests/commands/format.rs
crates/biome_cli/tests/commands/init.rs
crates/biome_cli/tests/commands/lint.rs
crates/biome_cli/tests/commands/migrate.rs
crates/biome_cli/tests/main.rs

small refactor for #669 
I divided it into two commits. The first one is a more confident replacement, and the second one I found that some tests were not written in full compliance with the rules, so I need help to check🧐

refactor: small test infrastructure

---

CHANGELOG.md
crates/biome_js_analyze/src/analyzers/a11y/no_blank_target.rs
website/src/content/docs/internals/changelog.mdx

Closes #676 
We were emitting an incorrect node with incorrect nodes; hence during the lining phase the rule could never find `"noreferrer"`.
Existing tests should pass. I tested manually using the CLI, because that's where the issue occurs.

fix(lint): use correct node for code action

---

website/src/content/docs/formatter/index.mdx

In the formatter docs section, an example configuration is shown.
The property `indentSize` is used.
When I tried this option in my config, biome shows me an alert telling me that this property is deprecated, and I should use `indentWidth` instead.
Change an example configuration on the docs to one that is not deprecated.
Try this with the latest version of biome and the warning message disappear.

docs: replace deprecated `indentSize` with `indentWidth`

---

CHANGELOG.md
crates/biome_cli/src/commands/daemon.rs
crates/biome_cli/src/commands/mod.rs
crates/biome_cli/src/lib.rs
crates/biome_cli/src/main.rs
crates/biome_cli/src/service/unix.rs
crates/biome_cli/src/service/windows.rs
crates/biome_cli/tests/main.rs
crates/biome_cli/tests/snapshots/main_commands_lsp_proxy/lsp_proxy_help.snap
crates/biome_lsp/src/server.rs
crates/biome_lsp/src/session.rs
crates/biome_lsp/tests/server.rs
website/src/content/docs/internals/changelog.mdx

Before, it *seemed* that we supported `--config-path`, but it's a mistake of the help command.
Although this is a feature that users require, so I added it.
This is a tricky one. So I plan to merge it, create a nightly release and ask users to test it.

feat(cli): add `--config-path` to `lsp-proxy` and `start` commands

---

CHANGELOG.md
crates/biome_cli/src/cli_options.rs
crates/biome_cli/src/execute/traverse.rs
crates/biome_cli/tests/cases/diagnostics.rs
crates/biome_cli/tests/cases/mod.rs
crates/biome_cli/tests/snapshots/main_cases_diagnostics/logs_the_appropriate_messages_according_to_set_diagonstics_level.snap
crates/biome_cli/tests/snapshots/main_commands_check/check_help.snap
crates/biome_cli/tests/snapshots/main_commands_ci/ci_help.snap
crates/biome_cli/tests/snapshots/main_commands_format/format_help.snap
crates/biome_cli/tests/snapshots/main_commands_lint/lint_help.snap
crates/biome_cli/tests/snapshots/main_commands_lsp_proxy/lsp_proxy_help.snap
crates/biome_cli/tests/snapshots/main_commands_migrate/migrate_help.snap
crates/biome_cli/tests/snapshots/main_commands_rage/rage_help.snap
crates/biome_diagnostics/src/diagnostic.rs
website/src/content/docs/internals/changelog.mdx

Adds the `--diagnostic-level` option to the CLI as described in issue #671.
A question regarding the implementation is what should be the default diagnostic level that should be used if it's not explicitly specified in the CLI options. For now I made [`Information` as the default](https://github.com/simonxabris/biome/blob/9649022b6a77597fe7ae040a787f7021e91da69f/crates/biome_diagnostics/src/diagnostic.rs#L121-L133). 
Now this is where I have some question as I don't have much experience with rust testing and the output was quite hard to decipher.
I guess some of the snapshots have to be updated, as for example the `--help` commands output now displays the `--diagnostic-level` option, but there are other snapshots that fail and I can't actually determine why,  so I'll need some help with …

feat(cli): add --diagnostic-level option

---

crates/biome_js_parser/src/syntax/class.rs
crates/biome_js_parser/test_data/inline/ok/class_member_modifiers_no_asi.js
crates/biome_js_parser/test_data/inline/ok/class_member_modifiers_no_asi.rast

Playground: https://biomejs.dev/playground?indentWidth=4&code=YwBsAGEAcwBzACAAWAAgAHsACgAgACAAcwB0AGEAdABpAGMACgAgACAAYgBhAHIAKAApACAAewB9AAoAfQA%3D
```JavaScript
class X {
static
bar() {}
}
```
There is no ASI after the `static`. 
The newline is allowed between the `static` and the class member name.
new inline test case added.

feat(biome_js_parser): allow newline between the `static` and the class member name

---

editors/intellij/src/main/kotlin/com/github/biomejs/intellijbiome/BiomeUtils.kt
editors/intellij/src/main/kotlin/com/github/biomejs/intellijbiome/formatter/BiomeFormatterProvider.kt
editors/intellij/src/main/kotlin/com/github/biomejs/intellijbiome/lsp/BiomeLspServerSupportProvider.kt
editors/intellij/src/main/kotlin/com/github/biomejs/intellijbiome/settings/BiomeSettings.kt
editors/intellij/src/main/kotlin/com/github/biomejs/intellijbiome/settings/BiomeSettingsConfigurable.kt
editors/intellij/src/main/kotlin/com/github/biomejs/intellijbiome/settings/BiomeSettingsState.kt
editors/intellij/src/main/resources/messages/BiomeBundle.properties

I wanted to be able to specify my biome.json that gets executed, so I added an option for it in the UI 
If it isn't set, it uses the existing functionality to find the config file, and otherwise uses what was set here.
I installed it on my IDE and specified a config directory in a different location and it used that config instead.

feat(intellij): Manual config path specifying

---

crates/biome_js_analyze/src/analyzers/correctness/no_unnecessary_continue.rs
crates/biome_js_analyze/tests/specs/correctness/noUnnecessaryContinue/valid.js
crates/biome_js_analyze/tests/specs/correctness/noUnnecessaryContinue/valid.js.snap

Closes #69
If a continue is in switch block, we have to avoid report this lint error.
Existing tests should pass and I've updated a existing snapshot test for this change.

fix(lint): fix a false positive in `lint/correctness/noUnnecessaryContinue`

---

CHANGELOG.md
crates/biome_diagnostics_categories/src/categories.rs
crates/biome_js_analyze/src/analyzers/nursery.rs
crates/biome_js_analyze/src/analyzers/nursery/no_default_export.rs
crates/biome_js_analyze/tests/specs/nursery/noDefaultExport/invalid.json
crates/biome_js_analyze/tests/specs/nursery/noDefaultExport/invalid.json.snap
crates/biome_js_analyze/tests/specs/nursery/noDefaultExport/valid.cjs
crates/biome_js_analyze/tests/specs/nursery/noDefaultExport/valid.cjs.snap
crates/biome_js_analyze/tests/specs/nursery/noDefaultExport/valid.js
crates/biome_js_analyze/tests/specs/nursery/noDefaultExport/valid.js.snap
crates/biome_js_syntax/src/identifier_ext.rs
crates/biome_service/src/configuration/linter/rules.rs
crates/biome_service/src/configuration/parse/json/rules.rs
crates/biome_service/tests/invalid/hooks_incorrect_options.json.snap
crates/biome_service/tests/invalid/hooks_missing_name.json.snap
editors/vscode/configuration_schema.json
packages/@biomejs/backend-jsonrpc/src/workspace.ts
packages/@biomejs/biome/configuration_schema.json
website/src/components/generated/NumberOfRules.astro
website/src/content/docs/internals/changelog.mdx
website/src/content/docs/linter/rules/index.mdx
website/src/content/docs/linter/rules/no-default-export.md

Implement [no-default-export](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-default-export.md).
This is a rule often recommended in code styles. For example the Google's TypeScript code style [discourages the use of default exports](https://google.github.io/styleguide/tsguide.html#exports).
Unit tests and doc tests should pass.

feat(lint/noDefaultExport): add rule

---

crates/biome_diagnostics_categories/src/categories.rs
crates/biome_js_analyze/src/analyzers/nursery.rs
crates/biome_js_analyze/src/analyzers/nursery/no_implicit_any_let.rs
crates/biome_js_analyze/tests/specs/nursery/noImplicitAnyLet/invalid.ts
crates/biome_js_analyze/tests/specs/nursery/noImplicitAnyLet/invalid.ts.snap
crates/biome_js_analyze/tests/specs/nursery/noImplicitAnyLet/valid.ts
crates/biome_js_analyze/tests/specs/nursery/noImplicitAnyLet/valid.ts.snap
crates/biome_service/src/configuration/linter/rules.rs
crates/biome_service/src/configuration/parse/json/rules.rs
crates/biome_service/tests/invalid/hooks_incorrect_options.json.snap
crates/biome_service/tests/invalid/hooks_missing_name.json.snap
editors/vscode/configuration_schema.json
packages/@biomejs/backend-jsonrpc/src/workspace.ts
packages/@biomejs/biome/configuration_schema.json
website/src/components/generated/NumberOfRules.astro
website/src/content/docs/linter/rules/index.mdx
website/src/content/docs/linter/rules/no-implicit-any-let.md
website/src/frontend-scripts/index.ts
website/src/frontend-scripts/toc.ts
website/src/playground/tabs/FormatterCodeTab.tsx

closes #389
closes #395
This implements a new rule to restrict the usage of variables without any type or initialisation in TS.
ref: https://www.typescriptlang.org/tsconfig#noImplicitAny
I have taken over #395. Thank you for the work @b4s36t4.
All existing tests should pass. #395 has added some test cases for valid and invalid situation and I've improved them. 
In addition, I have corrected all the issues pointed out in #395 for now.

feat(lint): Implement `noImplicitAnyLet`

---

Cargo.lock
crates/biome_js_formatter/Cargo.toml
crates/biome_js_formatter/src/ts/lists/type_parameter_modifier_list.rs
crates/biome_js_formatter/tests/specs/prettier/typescript/typeparams/const.ts.snap
crates/biome_js_syntax/src/modifier_ext.rs

Fix #717
This PR adds a predictable order for Type parameter modifiers (`const`, `in`, `out`).
Prettier also format a bogus node (`const` is not allowed for type parameter of interfaces):
```ts
interface L<in const T> {}
```
Thus, Biome doesn't turn `in const` into `const in`.
Updated prettier diff.

challenge(formatter): predictable order of type parameter modifiers

---

CHANGELOG.md
crates/biome_js_analyze/src/analyzers/style/no_inferrable_types.rs
crates/biome_js_analyze/tests/specs/style/noInferrableTypes/invalid.ts
crates/biome_js_analyze/tests/specs/style/noInferrableTypes/invalid.ts.snap
crates/biome_js_analyze/tests/specs/style/noInferrableTypes/valid.ts
crates/biome_js_analyze/tests/specs/style/noInferrableTypes/valid.ts.snap
website/src/content/docs/internals/changelog.mdx

ffix(lint/noInferrableTypes): assume TypeScript unsafe null mode

---

.gitignore
crates/biome_formatter_test/src/diff_report.rs
crates/biome_js_formatter/report_incompatible.md
crates/biome_js_formatter/tests/specs/prettier/README.md

This pr adds a test option `INCOMPATIBLE_ONLY` to report prettier compatibility for formatter.
When we pass a option `INCOMPATIBLE_ONLY=1` to `cargo test -p biome_js_formatter --test prettier_tests`, the report will show only incompatible test cases (similarity not equals 100.00 %).
1. execute `REPORT_PRETTIER=1 INCOMPATIBLE_ONLY=1 cargo test -p biome_js_formatter --test prettier_tests`
2. generate `incompatible_report.md` that does not include a test file section has similarity 100.00%
And the json case `REPORT_TYPE="json"` also works.

feat(formatter_test): add test option  to report incompatible formatter test cases only

---

crates/biome_formatter_test/src/diff_report.rs

Embedded languages in template literals and unstable syntaxes are not part of the challenge.

challenge(formatter): ignore embdedded languages and unstable syntaxes

---

crates/biome_formatter_test/src/diff_report.rs

Ignore throw expression for the challenge (unstable syntax).

challenge(formatter): ignore throw expression

---

crates/biome_css_parser/src/lexer/mod.rs
crates/biome_css_parser/src/lexer/tests.rs
crates/biome_css_parser/src/parser.rs
crates/biome_css_parser/src/token_source.rs
crates/biome_css_parser/tests/spec_test.rs
xtask/bench/src/language.rs

Current implementation is incorrect. Because now it makes incorrect the following comments:
`./*12321*/div {}` 
We need to rename the css config option to `allow wrong line comments for css` and check only `.div {}//comment` syntax.
`cargo test -p biome_css_parser`

feat(css_parser): CSS Parser pseudo element selector #268

---

crates/biome_js_formatter/src/utils/test_call.rs
crates/biome_js_formatter/tests/specs/prettier/js/test-declarations/test_declarations.js.snap

I've added a implementation for checking if the third member of test call expression is appropriate. I will fix the other Prettier differences in [js/test-declarations/test_declarations.js](https://github.com/biomejs/biome/blob/main/crates/biome_js_formatter/report_incompatible.md#jstest-declarationstest_declarationsjs) in a separated pull request because I think this fix will be a bit large.
`cargo test -p biome_js_formatter --test prettier_tests`

challenge(formatter): check if the third member of test call expression is appropriate

---

CHANGELOG.md
crates/biome_js_analyze/src/analyzers/a11y/no_svg_without_title.rs
crates/biome_js_analyze/tests/specs/a11y/noSvgWithoutTitle/invalid.jsx
crates/biome_js_analyze/tests/specs/a11y/noSvgWithoutTitle/invalid.jsx.snap
crates/biome_js_analyze/tests/specs/a11y/noSvgWithoutTitle/valid.jsx
crates/biome_js_analyze/tests/specs/a11y/noSvgWithoutTitle/valid.jsx.snap
website/src/content/docs/internals/changelog.mdx
website/src/content/docs/linter/rules/no-svg-without-title.md

Closes #784 
This PR does
- fix false-positives for `aria-label`. It does not require that title children having `id`.
- reports when `<svg>`'s `role` attribute is implicit (empty)
- e.g. `<svg role="">` is invalid if there is no `<title>` in child.
Added some test cases
- to accept `aria-label` without inner element's `id` consistency
- to report the case if svg's `role` attribute is implicit

fix(lint): fix false-positives for `aria-label` and report cases where the `role` is implicit in `noSvgWithoutTitle`

---

crates/biome_formatter_test/src/diff_report.rs
crates/biome_js_formatter/report.md
crates/biome_js_formatter/report_incompatible.md

These files [report.md](https://github.com/biomejs/biome/blob/main/crates/biome_js_formatter/report.md) and [report_incompatible.md](https://github.com/biomejs/biome/blob/main/crates/biome_js_formatter/report_incompatible.md) contain invalid markdown at the beginning.
I've fixed invalid markdown caused by wrong indent in report.md and report_incompatible.md and updated them.

chore(challenge): fix invalid markdown in `report.md` and `report_incompatible.md`

---

crates/biome_formatter/src/token/string.rs
crates/biome_js_formatter/src/utils/string_utils.rs
crates/biome_js_formatter/tests/specs/jsx/attribute_escape.jsx
crates/biome_js_formatter/tests/specs/jsx/attribute_escape.jsx.snap
crates/biome_json_formatter/src/format_string.rs

fix #826
`cargo test -p biome_js_formatter`
Check [this Prettier playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBDTBeTACgEp8A+TYAHSkypkigx3zpCvrgypAG4a6DdFgBGrHhw7xufAfUbMw49pKlcYPfrXnDMAE2WrV0jbKhyYAJzgwArpdqEL9ADxlnGmC4CWUAA62WFDYALZweDx+vjyYMACefuE88AAepph+2DDwDhEqesAALAA0hQC+MdYAjrbe1gYA9O7anq6+AUGhSSocUeYgsQndqemZ2XC5ElQFJeWVcDV1cI3NgvRt-oGYwWF5RlR9MfGJeSMxYzlQe9NFpRUD1bX1mE0eGx3bXdf7hwPHw3A0ucspdrjM7vNFs9Xi1XDDBMQtJgyrwQMUQBA-DBvOhkKBsJZLBAAO4ABQJCDQyBA2AANsTsHEqeiRJZsGAANY2ADKXQAMr44MgAGZ0tBwFlszk8zJgXwAc2QVlsEpA4pC3iVlhV6MBiUs3jCsDpABUJsEDVwRWLVWgFbS4ABFWwQeDW2ni9EAKzQKW59qdLrdSFFHtVNVdcFJRL8VJQ2DQAFooHBlss0SArNhvLSFQBhCAhELYal02kZu1QeUOgCC2QNIkCUYmApT7s9IAAFjAQrSAOqd7zSWVwbmUofeABuQ7i1LAaGZIEnKoAklA9AgYNywAasTX19z4g726q-ETxX22X5qWeuBNJ0L0b5xZYYNHsPLiyf0ZlLC-qS …

fix: avoid escape for jsx

---

crates/biome_js_formatter/src/ts/lists/tuple_type_element_list.rs
crates/biome_js_formatter/src/ts/lists/type_parameter_list.rs
crates/biome_js_formatter/tests/specs/ts/class/trailing_comma/class_trailing_comma.ts.snap
crates/biome_js_formatter/tests/specs/ts/function/trailing_comma/function_trailing_comma.ts.snap
crates/biome_js_formatter/tests/specs/ts/object/object_trailing_comma.ts.snap
crates/biome_js_formatter/tests/specs/ts/type/trailing-comma/type_trailing_comma.ts.snap

Follow the [change introduced by Prettier 3.0](https://prettier.io/blog/2023/07/05/3.0.0#print-trailing-comma-in-type-parameters-and-tuple-types-when---trailing-commaes5-14086httpsgithubcomprettierprettierpull14086-14085httpsgithubcomprettierprettierpull14085-by-fiskerhttpsgithubcomfisker) by adding trailing comma in ES5 mode. Note that this is listed under `Flow` breaking change, however, this also affect TypeScript.

feat(js_formatter): es5 trailing comma revision

---

pnpm-lock.yaml
website/package.json

This PR will upgrade prettier to v3.1.0.
Checked the operation of the changes in v3.1 on local playground.
https://prettier.io/blog/2023/11/13/3.1.0#add-indentation-back-to-nested-ternaries-9559httpsgithubcomprettierprettierpull9559-by-rattrayalexhttpsgithubcomrattrayalex
Closes #852

chore: upgrade prettier to v3.1.0

---

crates/biome_js_formatter/src/js/statements/empty_statement.rs
crates/biome_js_formatter/tests/specs/js/module/comments.js
crates/biome_js_formatter/tests/specs/js/module/comments.js.snap

closes #810
I have added a test case. All existing tests should pass.

fix(formatter): fix wrong Indentation for leading comments in empty statement

---

crates/biome_service/src/matcher/mod.rs

closes #856
When specific file or directory names are specified, it's necessary to check if they are included in the source path by traversing back through the path's ancestors. In my implementation, I use `ends_with`. This `ends_with` accurately recognizes paths, and in cases like the following, it will return `false` as expected:
```rust
let path = Path::new("src");
assert!(!path.ends_with("rc"));
```
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=33143b2b647a15d2424b2187a6411fbc
The documentation of `Path::ends_with`: https://doc.rust-lang.org/std/path/struct.Path.html#method.ends_with
I've added a test case for single file or directory name listed in `.gitignore`. All tests should pass.

fix(matcher): fix wrongly ignored paths

---

CHANGELOG.md
crates/biome_js_parser/src/syntax/function.rs
crates/biome_js_parser/test_data/inline/ok/jsx_type_arguments.jsx
crates/biome_js_parser/test_data/inline/ok/jsx_type_arguments.rast
crates/biome_js_parser/test_data/inline/ok/tsx_type_arguments.rast
crates/biome_js_parser/test_data/inline/ok/tsx_type_arguments.tsx
website/src/content/docs/internals/changelog.mdx

Fix #846.
This fixes a parsing error that rejected the following valid code when TypeScript and JSX are both enabled:
```ts
<const T,>() => {};
```
See these two comments for some context:
- https://github.com/biomejs/biome/issues/739#issuecomment-1823476061
- https://github.com/biomejs/biome/issues/739#issuecomment-1823747500
I added tests and updated snapshots.

fix(js_parser): desambigaute JSX and const type param of arrow function

---

website/src/content/docs/analyzer/index.mdx

`organizeImports` is opt-out, not opt-in. This PR clarifies it.

docs: clarify `organizeImports` is opt-out

---

crates/biome_aria/src/macros.rs
crates/biome_formatter/src/printed_tokens.rs
rust-toolchain.toml
xtask/codegen/src/parser_tests.rs

SSIA #878 
The current CI should pass

chore: upgrade Rust to 1.74.0 

---

crates/biome_js_formatter/src/lib.rs

In the documentation of [biome_js_formatter](https://docs.rs/biome_js_formatter/latest/biome_js_formatter/#best-practices), the link of `playground instructions` which is linked to [biomejs/src/website/playground/README.md](https://github.com/biomejs/biome/blob/main/website/playground/README.md) gives 404 error and doesn't exists, even in the oldest [commit](https://github.com/biomejs/biome/tree/cdaded93a386dc07a8d11c705ebe24de8d045cb3/website/src/playground).
Probably [biomejs/src/website/playground/README.md](https://github.com/biomejs/biome/blob/main/website/README.md) is a correct link which gives the instruction below
> If you want to work on the playground, additional artifacts are required and the following command must be used instead:

docs: fix link to playground instrunctions

---

crates/biome_analyze/CONTRIBUTING.md

There is a link to `Biome’s technical principals` in the documentation for[ biome_analyze](https://docs.rs/biome_analyze/latest/biome_analyze/#create-and-implement-the-rule), but I thought the link was set incorrectly, so I changed it. [new link](https://biomejs.dev/internals/philosophy/#technical)

docs: fix link to technical principals

---

crates/biome_js_analyze/src/analyzers/complexity/no_useless_type_constraint.rs
crates/biome_js_analyze/tests/specs/complexity/noUselessTypeConstraint/invalid.ts
crates/biome_js_analyze/tests/specs/complexity/noUselessTypeConstraint/invalid.ts.snap
crates/biome_js_analyze/tests/specs/complexity/noUselessTypeConstraint/invalid.tsx
crates/biome_js_analyze/tests/specs/complexity/noUselessTypeConstraint/invalid.tsx.snap

This Pr updates the code action by adding a mandatory trailing comma in type parameter lists of arrow functions in some specific cases.
I added tests.

refactor(lint/noUselessTypeCOnstraint): add required trailing comma in arrow functions

---

crates/biome_js_formatter/src/ts/lists/type_parameter_list.rs
crates/biome_js_formatter/tests/specs/tsx/type_param.tsx
crates/biome_js_formatter/tests/specs/tsx/type_param.tsx.snap

This is a follow-up of #872.
This PR make us slightly diverges from Prettier by keeping the original intent of Prettier: disambiguating type parameter list of arrow function from JSX.
Prettier seems to forget that the presence of a default type is enough to disambiguate an arrow function from a JSX element.
Thus, in this specific case the trailing comma is not mandatory.
```tsx
<T = unknown>() => {};
```
```diff
// -- Prettier
// ++ Biome
- <T = unknown,>() => {};
+ <T = unknown>() => {}; 
```
I added a test case.

refactor(js_formatter): adjust mandatory trailing comma in arrow functions

---

crates/biome_js_analyze/src/analyzers/suspicious/no_explicit_any.rs
crates/biome_js_analyze/tests/specs/suspicious/noExplicitAny/validTypeConstraints.ts
crates/biome_js_analyze/tests/specs/suspicious/noExplicitAny/validTypeConstraints.ts.snap
website/src/content/docs/linter/rules/no-explicit-any.md

The following code trigger both `noUslessTypeConstraint` and `noExplicitAny`:
```ts
function f<T extends any>(x: T): void {}
```
Extending `any` is not dangerous. Thus, this PR ignores this use of `any`.
This improves user experience by reporting this code a single time.
Test added.

refactor(lint/noExplicitAny): ignore type constraint clauses

---

website/src/content/docs/ja/internals/language-support.mdx

Partial work of https://github.com/biomejs/biome/issues/880
- Check if language-support (ja/internals/language-support#javascript-support) is translated into Japanese

doc(ja): translate `language-support` into Japanese

---

crates/biome_formatter_test/src/diff_report.rs
crates/biome_js_formatter/report.md
crates/biome_js_formatter/report_incompatible.md

Update reports by excluding a prettier snapshot about CSS formatting inside a template literal.

challenge: update reports

---

website/src/components/PostsList.astro

This solves the blog posts list not showing all the posts there are, by also globbing `.md` files alongside `.mdx` ones. I've also updated the filtering logic to properly filter out the `index.md` page without throwing errors.

fix: fix blog list not showing all posts

---

website/src/content/docs/ja/guides/how-biome-works.mdx

doc(ja): translate `How Biome works` into Japanese

---

website/src/content/docs/ja/internals/credits.mdx

I've translated the credits page. 
Related to: #880

doc(ja): translate `credits` into Japanese

---

website/src/pages/schemas/1.4.0/schema.json.js

fix(website): json schema for 1.4.0

---

crates/biome_js_formatter/src/js/expressions/arrow_function_expression.rs
crates/biome_js_formatter/tests/quick_test.rs

[Playground Example](https://biomejs.dev/playground?code=ZgBvAG8AKAAgAC8AKgBoAGkAKgAvACAAKABwAGEAcgBhAG0AZQB0AGUAcgAxACAAKQAgAD0APgAgAHsAYwBvAG4AcwB0ACAAYQAgAD0AIAAnAGgAZQBsAGwAbwAnADsAfQApAAoAZgBvAG8AKAAgAC8AKgBoAGkAKgAvACgAYQApACAAPQA%2BACAAKABiACkAIAA9AD4AIAB7AH0AKQAKAAoAZgBvAG8AKAAgAC8AKgBoAGkAKgAvACgAcABhAHIAYQBtAGUAdABlAHIAMQApACAAPQA%2BACAAKABwAGEAcgBhAG0AZQB0AGUAcgAyACkAIAA9AD4AIAAoAHAAYQByAGEAbQBlAHQAZQByADMAKQAgAD0APgAgACgAcABhAHIAYQBtAGUAdABlAHIANAApACAAPQA%2BACAAKABwAGEAcgBhAG0AZQB0AGUAcgA1ACkAIAA9AD4AIAB7AGMAbwBuAHMAdAAgAGEAIAA9ACAAJwBoAGUAbABsAG8AJwA7AH0AKQA%3D).
`ArrowChain` is a special case of `FormatJsArrowFunctionExpression` that handles formatting all of the nested arrow functions inside of it as a single node point. The top formatting node handles formatting comments, …

fix(js_formatter): Avoid double-printing the first leading comments in arrow chains

---

CHANGELOG.md
packages/@biomejs/biome/package.json
website/src/content/docs/internals/changelog.mdx

Release 1.4.1 with some bug fix
Proof read the changelog

release: 1.4.1

---

.github/workflows/release_cli.yml

This PR removes the job that autobumps the homebrew formula.
Homebrew now automatically bumps the biome formula via their `autobump` [workflow](https://github.com/Homebrew/homebrew-core/blob/c70d765179895fb101f57645fa2b7aa075f4931a/.github/workflows/autobump.yml#L161), so we no longer have to handle it ourselves.

ci(release_cli): remove homebrew bump

---

website/src/pages/schemas/1.4.1/schema.json.js

This PR adds the missing schema for 1.4.1
Generated with the following command:
```
BIOME_VERSION=1.4.1 cargo codegen-website
```

fix(website): add missing schema for 1.4.1

---

website/src/content/docs/ja/index.mdx

I have fixed a broken href in the Japanese version of the documentation.
It seems to be broken since #945.
The href is same as below.
https://github.com/biomejs/biome/blob/60956c87972a208d130e2a14ce818d382b366169/website/src/content/docs/index.mdx#L56

Fixed sponsor link in Japanese version

---

xtask/lintdoc/src/main.rs

This PR adds supports for autolink `<https://example.com>` and references `[foo][bar]` in rule documentation.

refactor(lintdoc): add support for autolink and references

---

crates/biome_formatter_test/src/diff_report.rs
crates/biome_js_formatter/report.md
crates/biome_js_formatter/report_incompatible.md

Ignore JavaScript experimental syntaxes inside JSX to generate Prettier compatibility reports.

chore(formatter): ignore experimental syntaxes in JSX for reports

---

CHANGELOG.md
crates/biome_analyze/CONTRIBUTING.md
crates/biome_diagnostics_categories/src/categories.rs
crates/biome_js_analyze/src/semantic_analyzers/nursery.rs
crates/biome_js_analyze/src/semantic_analyzers/nursery/use_for_of.rs
crates/biome_js_analyze/tests/specs/nursery/useForOf/invalid.js
crates/biome_js_analyze/tests/specs/nursery/useForOf/invalid.js.snap
crates/biome_js_analyze/tests/specs/nursery/useForOf/valid.js
crates/biome_js_analyze/tests/specs/nursery/useForOf/valid.js.snap
crates/biome_service/src/configuration/linter/rules.rs
crates/biome_service/src/configuration/parse/json/rules.rs
crates/biome_service/tests/invalid/hooks_incorrect_options.json.snap
crates/biome_service/tests/invalid/hooks_missing_name.json.snap
editors/vscode/configuration_schema.json
packages/@biomejs/backend-jsonrpc/src/workspace.ts
packages/@biomejs/biome/configuration_schema.json
website/src/components/generated/NumberOfRules.astro
website/src/content/docs/internals/changelog.mdx
website/src/content/docs/linter/rules/index.mdx
website/src/content/docs/linter/rules/use-for-of.md

This PR implements `useForOf` lint rule and closes #49
| Configuration  |  |
| ------------- | ------------- |
| Recommended  | ❌  |
| Fixable  |  ❌  |
This rule recommends a for-of loop when the loop index is only used to read from an array that is being iterated.
- Validate snapshot 😄
- Run default tests
I've removed one original test from eslint-typescript  valid scenario because it's seems not valid code at all:
If you think we still need it, please lets discuss it
```js
for (let i = 0; i < arr.length; i++) {
({ foo: arr[i] }) = { foo: 0 };
} 
```

feat(lint/useForOf): add rule

---

website/src/content/docs/ja/guides/manual-installation.mdx

Part of #880
Translate [Manual insallation](https://biomejs.dev/guides/manual-installation/) page in japanese.
```shell
cd website
pnpm install
pnpm start
```
and checked the page(including link behavior)

translate `Manual installation` in japanese

---

crates/biome_js_formatter/src/ts/expressions/as_expression.rs
crates/biome_js_formatter/tests/quick_test.rs

Fixes #914. This is the last case of that issue (the middle one).
Default-exported cast expressions for functions require parentheses to disambiguate between a cast expression for the function and a default function _declaration_ export. As an example:
```typescript
export default function foo() {} as typeof console.log;
// is actually
export default function foo() {};
as;
typeof console.log;
// because the declaration statement ends, and then `as` is considered a new statement
```
In this case parentheses force the statement to be interpreted as a default export of a cast, rather than a declaration:
```typescript
export default (function foo() {} as typeof console.log);
```
But (seemingly) all other kinds of default export expressions are able to be written without parentheses, as …

fix(js_formatter): Only parenthesize default-export function cast expressions

---

justfile

For whatever reason in my VSCode setup, for quick_tests specifically, I can't just hit the "Run Tests" button in the editor and have it run. It targets the wrong thing.
This adds an alias in the Justfile to run the quick test for a single package to avoid having to write it all out on the command line:
```
cargo test -p {package} --test quick_test -- quick_test --nocapture
```
vs
```
just qt {package}
```
Running `just qt ..` runs the appropriate test for all packages.

chore: add `qt` alias for running quicktests

---

crates/biome_js_analyze/src/react/hooks.rs
crates/biome_js_analyze/src/semantic_analyzers/correctness/use_exhaustive_dependencies.rs
crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/missingDependenciesInvalid.js
crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/missingDependenciesInvalid.js.snap
crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/valid.js
crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/valid.js.snap
website/src/content/docs/linter/rules/use-exhaustive-dependencies.md

Previously, the stableness check of the `correctness/useExhaustiveDependencies` rule was implemented by checking only the names of hooks, resulting in false behaviors in these cases:
- Namespaced imports (`import React from "react"`) (#578)
- Aliased imports (`import { useRef as u } from "react"`)
- Imports from other libraries (`import { useRef } from "preact/hooks"`)
- Local overrides (`const useRef = ...`)
This PR resolves all of the issues above by utilizing the `is_react_call_api()` utility function to check if the hook is actually coming from React.
Closes #578
Added an additional test case. Could add more for other edge cases if that's worth enough.

fix(lint/useExhaustiveDeps): handle hook source (#578)

---

crates/biome_cli/src/commands/ci.rs
crates/biome_cli/src/execute/mod.rs
crates/biome_cli/src/execute/process_file.rs
crates/biome_cli/src/execute/traverse.rs
crates/biome_cli/tests/snap_test.rs
crates/biome_diagnostics/src/display.rs
crates/biome_diagnostics/src/display/frame.rs
crates/biome_diagnostics/src/display_github.rs
crates/biome_diagnostics/src/lib.rs

See discussion in #441
Open questions / TODO:

feat(cli): Support GitHub Workflow Commands

---

website/astro.config.ts
website/src/layouts/StarlightSplashLayout.astro

This PR adds a CSS line to remove the language select to docs and changes the link configuration in the sidebar for both blog and playground to remove the language part (if it exists), so a user would never naturally reach `https://biomejs.dev/ja/blog` for example.
I've tested going to both the `/ja` and `/zh-cn` versions of the docs and clicking the "Blog" and "Playground" links. None ended up sending me to a 404 page.

feat(website): remove language select outside docs

---

website/astro.config.ts
website/src/content/docs/formatter/option-philosophy.md

As Biome grows in popularity, and particularly as people look at potentially migrating from Prettier now that we've won the challenge and promote that compatibility, we're going to get a lot of the same requests for adding options to the formatter.
Even before the challenge, Biome intended to be a strongly-opinionated formatter, much like Prettier, and had the chance to start fresh with a blank set of options and no historical baggage. After the challenge, we've had to implement all of the options that Prettier already has, but we don't want to keep adding more. This page on the website acts as something we can point to when requests come up, explaining that the ideal world for Biome is _no_ options, and the existing ones only exist for compatibility.
It also leaves the door open for …

docs(website): add Formatter Option Philosophy page

---

crates/biome_js_parser/src/state.rs
crates/biome_js_parser/src/syntax/module.rs
crates/biome_js_parser/test_data/inline/ok/decorator_export_default_class_and_interface.rast
crates/biome_js_parser/test_data/inline/ok/decorator_export_default_class_and_interface.ts
crates/biome_js_parser/test_data/inline/ok/decorator_export_default_function_and_function_overload.rast
crates/biome_js_parser/test_data/inline/ok/decorator_export_default_function_and_function_overload.ts
crates/biome_js_parser/test_data/inline/ok/decorator_export_default_function_and_interface.rast
crates/biome_js_parser/test_data/inline/ok/decorator_export_default_function_and_interface.ts

fix #1037 
```
const fn can_merge(a: &ExportDefaultItemKind, b: &ExportDefaultItemKind) -> bool {
match (a, b) {
// export default function a():void;
// export default function a(){
// }
(
ExportDefaultItemKind::FunctionOverload,
ExportDefaultItemKind::FunctionDeclaration,
) => true,
// export default function a(){};
// export default interface A{};
(ExportDefaultItemKind::FunctionDeclaration, ExportDefaultItemKind::Interface) => true,
// export default interface A{};
// export default class A{};
(ExportDefaultItemKind::Interface, ExportDefaultItemKind::ClassDeclaration) => true,
(_, _) => false,
}
}
```
add can merge function
merge interface and class...
update snapshot

fix(js_parser): Illegal duplicate default export declarations

---

CHANGELOG.md
crates/biome_js_analyze/src/analyzers/suspicious/no_empty_interface.rs
crates/biome_js_analyze/src/control_flow/visitor.rs
crates/biome_js_analyze/src/semantic_analyzers/style/use_naming_convention.rs
crates/biome_js_analyze/tests/specs/suspicious/noEmptyInterface/invalid.ts
crates/biome_js_analyze/tests/specs/suspicious/noEmptyInterface/invalid.ts.snap
crates/biome_js_analyze/tests/specs/suspicious/noEmptyInterface/valid.ts
crates/biome_js_analyze/tests/specs/suspicious/noEmptyInterface/valid.ts.snap
website/src/content/docs/internals/changelog.mdx
website/src/content/docs/linter/rules/no-empty-interface.md

fix(lint/noEmptyInterface): allow empty interfaces in external module

---

CHANGELOG.md
crates/biome_js_analyze/tests/specs/suspicious/noRedeclare/valid-declaration-merging.ts
crates/biome_js_analyze/tests/specs/suspicious/noRedeclare/valid-declaration-merging.ts.snap
crates/biome_js_syntax/src/binding_ext.rs
website/src/content/docs/internals/changelog.mdx

Fix #1061
Anti-regression tests added.

fix(lint/noRedeclare): allow  overloads

---

crates/biome_js_formatter/src/js/expressions/call_arguments.rs
crates/biome_js_formatter/src/utils/member_chain/simple_argument.rs
crates/biome_js_formatter/tests/specs/js/module/call/simple_arguments.js
crates/biome_js_formatter/tests/specs/js/module/call/simple_arguments.js.snap
crates/biome_js_formatter/tests/specs/js/module/call/simple_arguments.js.snap.new

When I implemented some previous fixes for call argument grouping in #777, I made it use `SimpleArgument`, since that's the same thing Prettier does. I also expanded some of the things that it matched in #757, but there were still a few more things that were being decided on incorrectly:
- Computed member expressions, like `array[0]`, were not considered simple, because it only checked static member expressions.
- _All_ calls with a single argument were considered simple, even if the argument _to_ that call was not simple, like `Math.floor(1 + 2)`.
- Calls with any number of arguments could be considered simple, rather than limiting to the current `depth`.
This PR addresses all of those errors and matches Prettier much more consistently in all of the cases I've checked.
Added a bunch of …

fix(js_formatter): fix SimpleArgument checks for call and member expressions

---

.github/CODEOWNERS
website/src/content/docs/ja/analyzer/index.mdx

I updated CODEOWNERS about ja translation and fixed some broken links

docs(website): update CODEOWNERS and broken links

---

pnpm-lock.yaml
website/astro.config.ts
website/package.json
website/src/styles/_markdown.scss
website/src/styles/index.scss

This PR adds back the autolink headings that were lost in the Rome -> Biome migration. 
Credits to Astro Docs where I respectfully stole this code from 😛 
When you hover over a heading, you will now see a new icon that will link to the current heading. This works both in desktop and mobile since the icon will be moved to the most appropriate place according to the viewport.
Notes:
- I added two new small dev dependencies to accomplish this: `hastscript` & `html-escaper`.
- This will also apply to blog post entries, where we don't have a table of contents, so that's an extra nicety.
- I've removed some (supposedly) unused code from the `astro.config.mjs` file - If necessary I can add it back.
Example:
Mobile viewport
Medium-sized viewport (+ hover style example)
Large viewport

feat(website): add autolink headings back

---

CHANGELOG.md
crates/biome_js_analyze/src/semantic_analyzers/correctness/use_exhaustive_dependencies.rs
crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/extraDependenciesInvalid.js
crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/extraDependenciesInvalid.js.snap
crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/valid.js
crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/valid.js.snap
website/src/content/docs/internals/changelog.mdx
website/src/content/docs/linter/rules/use-exhaustive-dependencies.md

No longer report out of scope captures that are declared out of function scope.
I also updated the diagnostic message when we detect an identifier in the dependency array that are declare outside the function. This is something eslint is doing as well: https://stackblitz.com/edit/node-8wwnzi?file=src%2Findex.js
Closes: #651 
Test are updated

fix(lint/useExhaustiveDependencies): ignore missing deps declared out of component function scope

---

CHANGELOG.md
crates/biome_js_analyze/src/analyzers/style/use_single_var_declarator.rs
crates/biome_js_analyze/tests/specs/style/useSingleVarDeclarator/invalid.js
crates/biome_js_analyze/tests/specs/style/useSingleVarDeclarator/invalid.js.snap
crates/biome_js_analyze/tests/specs/style/useSingleVarDeclarator/valid.js
crates/biome_js_analyze/tests/specs/style/useSingleVarDeclarator/valid.js.snap
website/src/content/docs/internals/changelog.mdx
website/src/content/docs/linter/rules/use-single-var-declarator.md

Fix #728.
I also take the opportunity of adding more details in the rule description.
I added an anti-regression test and other tests.

fix(lint/useSingleVarDeclarator): output valid code when declarators are on multilines

---

website/src/content/docs/reference/configuration.mdx

The config option for `json.formatter.indentWidth` is missing.
Similar to #1073 but for json
closes #1084

docs(website): add missing indentWidth for json

---

CHANGELOG.md
crates/biome_lsp/src/capabilities.rs
website/src/content/docs/internals/changelog.mdx

Closes https://github.com/biomejs/biome/issues/1042
I tested locally with dynamic capabilities turn off, and it works.

feat(lsp): enable formatting on registering

---

editors/intellij/gradle.properties

Fixes #1091
This PR removes the fixed build range that limit new Jetbrains IDE versions to be compatible with the plugin.
- Test the plugin on WebStorm 2023.3, Intellij 2023.3  and PyCharm 2023.3 using ./gradlew runIde

fix(editors/intellij): remove build range

---

crates/biome_formatter/src/format_element/document.rs

[Playground Link](https://biomejs.dev/playground/?indentStyle=space&code=aQBtAHAAbwByAHQAKAAnAEAAcwBvAG0AZQBsAG8AbgBnAHAAYQB0AGgALwBlAG4AbwB1AGcAaAB0AG8ALwBiAHIAZQBhAGsAdABoAGUAcABhAHIAZQBuAHQAJwApAC4AdABoAGUAbgAoAAoAIAAgACAAIAAgACAAKAB7AHMAbwBtAGUATABvAG4AZwBGAHUAbgBjAHQAaQBvAG4ATgBhAG0AZQB9ACkAIAA9AD4ACgAgACAAIAAgACAAIAAgACAAcwBvAG0AZQBMAG8AbgBnAEYAdQBuAGMAdABpAG8AbgBOAGEAbQBlACgAewAKACAAIAAgACAAIAAgACAAIAAgACAAYgByAG8AawBlAG4ATwBiAGoAZQBjAHQACgAgACAAIAAgACAAIAAgACAAfQApACwACgAgACAAIAAgACkAOwA%3D)
This one was fun! The problem:
```typescript
// Biome
import("@somelongpath/enoughto/breaktheparent").then(
({ someLongFunctionName }) => someLongFunctionName({
brokenObject,
}),
);
// Prettier
import("@somelongpath/enoughto/breaktheparent").then(
({ someLongFunctionName }) => …
```

fix(js_formatter): fix `propagate_expand` for interned elements with `best_fitting`

---

website/src/content/docs/formatter/differences-with-prettier.md

Adding docs about how Biome's output might not match Prettier when it was parsed with `typescript` rather than `babel-ts`. This accounted for almost a dozen diffs when run on our monorepo, and the bugs have been reported to Prettier as inconsistencies.
Biome matches the output of `babel-ts` and `babel`, which feels like the correct target for consistent output across JS and TS combined.
N/A

docs(formatter): Explain divergence for typescript vs babel from Prettier

---

crates/biome_js_formatter/src/js/auxiliary/case_clause.rs
crates/biome_js_formatter/src/js/auxiliary/default_clause.rs
crates/biome_js_formatter/tests/specs/js/module/statement/switch.js
crates/biome_js_formatter/tests/specs/js/module/statement/switch.js.snap

In #1035 I fixed some issues with `case` clauses with multi-statement bodies, but those didn't carry over to `default` clauses because they are handled separately. This copies the updated logic so that they match.
Added some cases to the existing spec test for `switch` to cover default clauses as well.

fix(js_formatter): match default clause block handling with case clauses

---

crates/biome_js_formatter/src/js/expressions/call_arguments.rs
crates/biome_js_formatter/tests/quick_test.rs
crates/biome_js_formatter/tests/specs/js/module/call/simple_arguments.js
crates/biome_js_formatter/tests/specs/js/module/call/simple_arguments.js.snap

When I added `is_relatively_short_argument` in #777, I added `JsBinaryExpression` as a match arm, but didn't realize that wouldn't encompass expressions like `a ?? b`, which are actually `JsLogicalExpression`. This PR just adds a similar arm to that function for handling logicals exactly like binaries, which matches Prettier's `isBinaryish` function used in the same place.
This PR also implements the missing half of Prettier's `isSimpleTsType`, introspecting arrays and generic types to extract the core type before checking for simplicity.
Added to the spec test for simple_arguments and grouping to cover logical expressions.

fix(js_formatter): fix binaryish and ts type handling for grouping call arguments

---

website/src/content/docs/pt-br/internals/versioning.mdx

Partial work of https://github.com/biomejs/biome/issues/1065 which translates the following files:
- `internals/versioning`
Check if there is no missing translation in the translated files.
Check if the translations are correct and if they adhere to the grammatical rules of Portuguese.

docs(website): translate versioning to portuguese

---

crates/biome_js_formatter/src/js/expressions/arrow_function_expression.rs
crates/biome_js_formatter/tests/specs/js/module/arrow/curried_indents.js
crates/biome_js_formatter/tests/specs/js/module/arrow/curried_indents.js.snap

[Playground Link with all the affected cases](https://biomejs.dev/playground/?indentStyle=space&code=CgAvAC8AIABQAGEAcgBhAG0AZQB0AGUAcgBzACAAdABoAGEAdAAgAGIAcgBlAGEAawAgAG8AdgBlAHIAIABtAHUAbAB0AGkAcABsAGUAIABsAGkAbgBlAHMAIABzAGgAbwB1AGwAZAAgAG0AYQB0AGMAaAAgAGkAbgBkAGUAbgB0AGkAbwBuAAoALwAvACAAdwBpAHQAaAAgAHQAaABlACAAbwBwAGUAbgBpAG4AZwAgAHAAYQByAGUAbgB0AGgAZQBzAGkAcwAuAAoALwAvACAAVABoAGUAIABzAGUAYwBvAG4AZAAgAHMAaQBnAG4AYQB0AHUAcgBlACAAYQBuAGQAIABvAG4AdwBhAHIAZAAgAGEAcgBlACAAaQBuAGQAZQBuAHQAZQBkACAAYQAgAHMAZQBjAG8AbgBkACAAbABlAHYAZQBsAC4ACgBhAC4AYgAoAAoAIAAgACgAYQApACAAPQA%2BAAoAIAAgACAAIAAoAGIAKQAgAD0APgAKACAAIAAgACAAKAAKACAAIAAgACAAIAAgAGMAIAA9ACAAIgBhAGIAYwBkAGUAZgBnAGgAaQBqAGsAbABtAG4AbwBwAHEAcgBzAHQAdQB2AHcAeAB5AHoAYQBiAGMAZABlAGYAZwBoAGkAagBrAGwAbQBuAG8AcABxAHIAcwB0AHUAdgB3AHgAeQB6AGEAY …

fix(js_formatter): refactor indention for arrow chains

---

CHANGELOG.md
crates/biome_aria/src/properties.rs
crates/biome_js_analyze/tests/specs/a11y/useValidAriaProps/valid.jsx
crates/biome_js_analyze/tests/specs/a11y/useValidAriaProps/valid.jsx.snap
website/src/content/docs/internals/changelog.mdx

Closes #1167 
Added a snapshot to accept `aria-atomic` as valid case.

fix(lint/useValidAriaProps): fix to not report `aria-atomic` as invalid

---

website/src/content/docs/analyzer/index.mdx
website/src/content/docs/ja/analyzer/index.mdx
website/src/content/docs/pt-br/analyzer/index.mdx
website/src/content/docs/zh-cn/analyzer/index.mdx

This PR updates the file name in the "Import sorting via VSCode extension" examples to accurately reflect the vscode settings file.

docs: fix incorrect file name

---

website/src/content/docs/internals/credits.mdx

There are 2 broken links located in the `credits.mdx`.
- Codespan for `biome_console`
- ignore for `biome_service`
I updated both to still link to the `src` of both packages, but maybe they should be removed if the other packages aren't used anymore

chore: broken links in `credits.mdx`

---

crates/biome_js_formatter/src/js/expressions/call_arguments.rs
crates/biome_js_formatter/tests/specs/ts/simple_arguments.ts
crates/biome_js_formatter/tests/specs/ts/simple_arguments.ts.snap

Fixes #1208 
`is_simple_ts_type` was recently changed to support extracting types from nested arrays and generics, but in the case that an extracted array type was _not_ a generic _and_ was not a primitive type, it was falling back to the _original_ type that was passed in. That meant it would fail the simplicity check that happened afterward and cause functions to expand pre-emptively.
```
// This should collapse, because `MyCustomType` is simple, and only within one array type
foo(() => {
foo
},
bar as MyCustomType[],
);
```
I also fixed a mistyped match against `TsObjectLiteralType`, which was meant to represent the `object` keyword, but that's actually `TsNonPrimitiveLiteralType`.
Added a whole set of tests around simple arguments for TS expressions to cover both of these changes, as …

fix(js_formatter): fix handling ts references from array types in argument grouping

---

CHANGELOG.md
crates/biome_js_analyze/src/analyzers/style/no_useless_else.rs
crates/biome_js_analyze/tests/specs/style/noUselessElse/invalid.js
crates/biome_js_analyze/tests/specs/style/noUselessElse/invalid.js.snap
website/src/content/docs/internals/changelog.mdx
website/src/content/docs/linter/rules/no-useless-else.md

Fix #1191.
I removed the note from the diagnostic because this was misleading. The rule now checks that every preceding branch break early, not only the previous branch.
New test added with a comment on the `else` clause.

refactor(lint/noUselessElse): keep else clause comments

---

CHANGELOG.md

Adding all the changelog entries for the formatter fixes made since 1.4.0...didn't realize it was quite so many nor that it had been so long lol

chore: add formatter changelog entries since 1.4.0 release

---

crates/biome_cli/src/execute/traverse.rs

I was getting `stack overflow` errors when trying to run a command like
```
cargo run --bin biome format ./crates/biome_js_formatter/tests/specs/js/module/comments.js
```
from a clean main branch. After a bit of bisecting and debugging with lots of print statements, I found that I was using a relative path (starting with `.`), and the path resolution done to set up the traversal was inadvertently turning that full path into _just_ the working directory. In other words, given a path like `./path/to/file`, it was trying to resolve that to an absolute path like `/home/user/path/to/file`, but would actually just return `/home/user`...
That in itself wasn't actually the problem, but isn't correct, either. So, this PR fixes that issue and properly returns the complete absolute path with the …

fix(cli): fix traversal of relative paths as inputs

---

CHANGELOG.md
crates/biome_js_analyze/src/analyzers/suspicious/no_empty_interface.rs
crates/biome_js_analyze/src/control_flow/visitor.rs
crates/biome_js_analyze/tests/specs/suspicious/noEmptyInterface/valid.d.ts
crates/biome_js_analyze/tests/specs/suspicious/noEmptyInterface/valid.d.ts.snap
crates/biome_js_analyze/tests/specs/suspicious/noEmptyInterface/valid.ts
crates/biome_js_analyze/tests/specs/suspicious/noEmptyInterface/valid.ts.snap
website/src/content/docs/internals/changelog.mdx

Fix the issue [reported in a comment](https://github.com/biomejs/biome/issues/1157#issuecomment-1859292783). This is a follow-up of #1059.
New tests added.

fix(lint/noEmptyInterface): ignore interfaces extending types in global declarations

---

crates/biome_diagnostics_categories/src/categories.rs
crates/biome_js_analyze/src/syntax.rs
crates/biome_js_analyze/src/syntax/nursery.rs
crates/biome_js_analyze/src/syntax/nursery/no_type_only_import_attributes.rs
crates/biome_js_analyze/tests/specs/nursery/noTypeOnlyImportAttributes/invalid.ts
crates/biome_js_analyze/tests/specs/nursery/noTypeOnlyImportAttributes/invalid.ts.snap
crates/biome_js_analyze/tests/specs/nursery/noTypeOnlyImportAttributes/valid.js
crates/biome_js_analyze/tests/specs/nursery/noTypeOnlyImportAttributes/valid.js.snap
crates/biome_js_analyze/tests/specs/nursery/noTypeOnlyImportAttributes/valid.ts
crates/biome_js_analyze/tests/specs/nursery/noTypeOnlyImportAttributes/valid.ts.snap
crates/biome_js_syntax/src/import_ext.rs
packages/@biomejs/backend-jsonrpc/src/workspace.ts

Implement a syntax rule that ensures that type-only imports and exports are not combined with import attributes.
Instead of implementing a syntax rule, we could check this directly in the parser.
Tests added.

feat(parse/noTypeOnlyImportAttributes): report type-only imports/exports with attributes

---

CHANGELOG.md
crates/biome_diagnostics_categories/src/categories.rs
crates/biome_js_analyze/src/semantic_analyzers/nursery.rs
crates/biome_js_analyze/src/semantic_analyzers/nursery/no_invalid_use_before_declaration.rs
crates/biome_js_analyze/tests/specs/nursery/noInvalidUseBeforeDeclaration/invalid.js
crates/biome_js_analyze/tests/specs/nursery/noInvalidUseBeforeDeclaration/invalid.js.snap
crates/biome_js_analyze/tests/specs/nursery/noInvalidUseBeforeDeclaration/invalid.ts
crates/biome_js_analyze/tests/specs/nursery/noInvalidUseBeforeDeclaration/invalid.ts.snap
crates/biome_js_analyze/tests/specs/nursery/noInvalidUseBeforeDeclaration/valid.js
crates/biome_js_analyze/tests/specs/nursery/noInvalidUseBeforeDeclaration/valid.js.snap
crates/biome_js_analyze/tests/specs/nursery/noInvalidUseBeforeDeclaration/valid.ts
crates/biome_js_analyze/tests/specs/nursery/noInvalidUseBeforeDeclaration/valid.ts.snap
crates/biome_service/src/configuration/linter/rules.rs
crates/biome_service/src/configuration/parse/json/rules.rs
crates/biome_service/tests/invalid/hooks_incorrect_options.json.snap
crates/biome_service/tests/invalid/hooks_missing_name.json.snap
packages/@biomejs/backend-jsonrpc/src/workspace.ts
packages/@biomejs/biome/configuration_schema.json
website/src/components/generated/NumberOfRules.astro
website/src/content/docs/internals/changelog.mdx
website/src/content/docs/linter/rules/index.mdx
website/src/content/docs/linter/rules/no-invalid-use-before-declaration.md

Rule requested in [a comment](https://github.com/biomejs/biome/discussions/3#discussioncomment-7900845).
In JavaScript, referencing a block-scoped variable or a function parameter before its declaration is an error.
The rule reports some of these errors. It cannot report cases where a function that uses a variable is called before the declaration of the variable.
For example:
```js
f();
const CONSTANT = 0;
functionf () { console.log(CONSTANT); }
```
Note that we correctly allow using a variable before its declaration if it is used in an `export` or in a distinct control flow root. For instance:
```js
export { CONSTANT };
const CONSTANT = 0;
```
```js
functionf () { console.log(CONSTANT); }
const CONSTANT = 0;
```
Although it is not invalid in JavaScript, we also report use before …

feat(lint/noInvalidUseBeforeDeclaration): add rule

---

Cargo.lock
crates/biome_analyze/CONTRIBUTING.md
crates/biome_js_analyze/Cargo.toml
crates/biome_js_analyze/src/analyzers/complexity/no_excessive_cognitive_complexity.rs
crates/biome_js_analyze/src/aria_analyzers/nursery/use_valid_aria_role.rs
crates/biome_js_analyze/src/options.rs
crates/biome_js_analyze/src/semantic_analyzers/correctness/use_exhaustive_dependencies.rs
crates/biome_js_analyze/src/semantic_analyzers/style/no_restricted_globals.rs
crates/biome_js_analyze/src/semantic_analyzers/style/use_naming_convention.rs
crates/biome_service/src/configuration/linter/mod.rs

This PR allows removing `Bpaf` dependency of `biome_js_analyze` crate.
This also allows simplifying a rule's configuration implementation since we no longer need to implement Bpaf's `Parser` trait and `FromStr` trait (required by Bpaf).
To do that, I use a pure parser for `PossibleOptions` enum.
We could go beyond and use a pure parser for the entire linter configuration.
CI and manually testd.

refcator(linter): don't require rule config to implement Bpaf's Parser trait

---

crates/biome_css_formatter/src/css/auxiliary/attribute_matcher.rs
crates/biome_css_formatter/src/css/auxiliary/attribute_matcher_value.rs
crates/biome_css_formatter/src/css/auxiliary/attribute_name.rs
crates/biome_css_formatter/src/css/lists/rule_list.rs
crates/biome_css_formatter/src/css/selectors/attribute_selector.rs
crates/biome_css_formatter/tests/specs/css/selectors/attribute_selector.css
crates/biome_css_formatter/tests/specs/css/selectors/attribute_selector.css.snap

#1285. This implements attribute selectors and all of the sub-nodes for it.
Two notes:
- The parser doesn't seem to currently understand `$=` attribute matchers, like `[href$='.com']`. This gets parsed as `href$` being an identifier, then the rest becomes bogus. All of the other operators work as expected, though.
- Values should also eventually be formatted consistently with quotes. This will also be subject to the `quoteStyle` option once that gets added later on.
Added a bunch of spec tests to roughly match prettier, sans the `$=` matcher

feat(css_formatter): support for attribute selectors [#1285]

---

crates/biome_css_formatter/src/css/auxiliary/any_function.rs
crates/biome_css_formatter/src/css/auxiliary/parameter.rs
crates/biome_css_formatter/src/css/auxiliary/simple_function.rs
crates/biome_css_formatter/src/css/lists/component_value_list.rs
crates/biome_css_formatter/src/css/lists/declaration_list.rs
crates/biome_css_formatter/src/css/lists/parameter_list.rs
crates/biome_css_formatter/src/css/lists/selector_list.rs
crates/biome_css_formatter/src/prelude.rs
crates/biome_css_formatter/tests/quick_test.rs
crates/biome_css_formatter/tests/specs/css/functions.css
crates/biome_css_formatter/tests/specs/css/functions.css.snap
crates/biome_css_formatter/tests/specs/css/units.css.snap
crates/biome_css_formatter/tests/specs/css/value_fill.css
crates/biome_css_formatter/tests/specs/css/value_fill.css.snap

#1285. This implements formatting for "component values" - basically everything on the right side of the `:` in a declaration. Nothing too complex for now, but it sets up the `component_value_list` to be able to support `Fill` and `OnePerLine` modes separately (just like `array_element_list` in JS), which will be needed once the parser supports comma-separated lists. Then there will also need to be more logic to decide which layout gets used as well.
Added tests for value fills in general and covering the different structures that functions can have (single/multi parameters, simple/complex values).

feat(css_formatter): formatting for functions and parameters

---

crates/biome_service/src/configuration/linter/mod.rs
crates/biome_service/src/configuration/linter/rules.rs
crates/biome_service/src/configuration/overrides.rs
crates/biome_service/src/configuration/parse/json/linter.rs
xtask/codegen/src/generate_configuration.rs

Part of #1263.
This PR reduces by 53% (from 8440 bytes to 3976 bytes) the memory usage of `biome.json`.
Most of the memory usage comes from the `RuleConfiguration` type (40 bytes) that is present for every rule. `RuleConfiguration` is an enum with two variants, thus it takes the size of its biggest variant: `RuleWithOptions`. Most of the rules have no options, so this is just a waste of memory. This PR replace `RuleWithOptions` with `Box<RuleWithOptions>`. This allows reducing `RuleConfiguration` from 40 bytes to 16 bytes. It is not an ideal fix because `Box` incurs a heap allocation. However, this only happen when configuring a rule with options (we only have a few one at the moment).
Alternatively, we could add lifetime annotations on every config struct/enums and use a reference …

refactor(config): reduce size by 53%

---

CHANGELOG.md
crates/biome_cli/tests/cases/overrides_formatter.rs
crates/biome_cli/tests/cases/overrides_linter.rs
crates/biome_cli/tests/snap_test.rs
crates/biome_cli/tests/snapshots/main_cases_overrides_formatter/does_not_change_formatting_language_settings.snap
crates/biome_cli/tests/snapshots/main_cases_overrides_formatter/does_not_change_formatting_settings.snap
crates/biome_cli/tests/snapshots/main_cases_overrides_linter/does_not_change_linting_settings.snap
crates/biome_service/src/configuration/overrides.rs
crates/biome_service/src/settings.rs
website/src/content/docs/internals/changelog.mdx

Closes https://github.com/biomejs/biome/issues/691 https://github.com/biomejs/biome/issues/1190 
The issue was that when we were computing the overrides of the formatter and the linter, we were silently applying Biome's defaults.
This PR fixes the issue by using the parent configuration before applying the default.
I added new test cases

fix(project): keep parent configuration when computing overrides

---

crates/biome_css_formatter/src/css/auxiliary/keyframes_block.rs
crates/biome_css_formatter/src/css/auxiliary/keyframes_item.rs
crates/biome_css_formatter/src/css/lists/keyframes_item_list.rs
crates/biome_css_formatter/src/css/lists/keyframes_selector_list.rs
crates/biome_css_formatter/src/css/selectors/keyframes_ident_selector.rs
crates/biome_css_formatter/src/css/selectors/keyframes_percentage_selector.rs
crates/biome_css_formatter/src/css/statements/at_rule.rs
crates/biome_css_formatter/src/css/statements/charset_at_rule.rs
crates/biome_css_formatter/src/css/statements/color_profile_at_rule.rs
crates/biome_css_formatter/src/css/statements/counter_style_at_rule.rs
crates/biome_css_formatter/src/css/statements/font_face_at_rule.rs
crates/biome_css_formatter/src/css/statements/font_palette_values_at_rule.rs
crates/biome_css_formatter/src/css/statements/keyframes_at_rule.rs
crates/biome_css_formatter/tests/quick_test.rs
crates/biome_css_formatter/tests/specs/css/atrule/charset.css
crates/biome_css_formatter/tests/specs/css/atrule/charset.css.snap
crates/biome_css_formatter/tests/specs/css/atrule/color_profile.css
crates/biome_css_formatter/tests/specs/css/atrule/color_profile.css.snap
crates/biome_css_formatter/tests/specs/css/atrule/counter_style.css
crates/biome_css_formatter/tests/specs/css/atrule/counter_style.css.snap
crates/biome_css_formatter/tests/specs/css/atrule/font_face.css
crates/biome_css_formatter/tests/specs/css/atrule/font_face.css.snap
crates/biome_css_formatter/tests/specs/css/atrule/font_face.css.snap.new
crates/biome_css_formatter/tests/specs/css/atrule/keyframes.css
crates/biome_css_formatter/tests/specs/css/atrule/keyframes.css.snap

#1285. This implements all of the remaining at-rules that the parser currently understands:
- `font-face`
- `keyframes`
- `font-palette-values`
- `charset`
- `color-profile`
- `counter-style`
Of note, the `@font-face` spec test is currently a verbatim snapshot, because it includes comma-separated values in the declarations, which the parser doesn't handle yet. Once it does, the snapshot _should_ just update and be correct.

feat(css_formatter): all the remaining at-rules

---

crates/biome_css_formatter/src/css/auxiliary/custom_property.rs
crates/biome_css_formatter/src/css/auxiliary/simple_function.rs
crates/biome_css_formatter/src/css/auxiliary/var_function.rs
crates/biome_css_formatter/src/css/auxiliary/var_function_value.rs
crates/biome_css_formatter/tests/quick_test.rs
crates/biome_css_formatter/tests/specs/css/variables.css
crates/biome_css_formatter/tests/specs/css/variables.css.snap

#1285. This implements support for formatting custom properties with the `var` function.
The parser doesn't actually interpret these yet, but the nodes exist, and the formatting is relatively straightforward, so i'm just adding the support in now. Once the parser starts emitting these nodes, the formatting should just work!
Added a snapshot test and accepted it even though the formatting is incorrect.

feat(css_formatter): support for var functions

---

crates/biome_css_formatter/src/css/pseudo/pseudo_class_function_compound_selector_list.rs
crates/biome_css_formatter/src/css/pseudo/pseudo_class_function_relative_selector_list.rs
crates/biome_css_formatter/src/css/pseudo/pseudo_class_function_selector_list.rs
crates/biome_css_formatter/src/css/pseudo/pseudo_class_function_value_list.rs
crates/biome_css_formatter/src/css/selectors/pseudo_class_of_nth_selector.rs
crates/biome_css_formatter/src/css/statements/media_at_rule.rs

In the big chain of merges for the formatter, a few of them had drifted behind the current syntax of the parser, leading to errors on compilation. This fixes all of the things that were renamed.
Compilation succeeds and all of the tests are passing again.

fix(css_formatter): syntax errors after parser refactoring

---

crates/biome_css_formatter/README.md
crates/biome_css_parser/README.md
crates/biome_formatter/README.md
crates/biome_js_formatter/README.md
crates/biome_js_parser/README.md
crates/biome_json_formatter/README.md
crates/biome_json_parser/README.md
packages/@biomejs/biome/README.md

This PR updates the various `README.md` to use the new logo.
The one that we use for npm/github, uses the new way for dark/light theme. We fallback to the light theme because npmjs.org doesn't support dark/light themes (sadly).
The `README.md` of Rust crates use the light theme transparent. crates.io doesn't support dark/light themes.
Check if that's what we want :)

chore: use new logo in readme

---

crates/biome_css_formatter/src/css/auxiliary/attribute_matcher_value.rs
crates/biome_css_formatter/src/lib.rs
crates/biome_css_formatter/tests/specs/css/selectors/attribute_selector.css.snap

#1285. This PR ensures that all values for an attribute selector are quoted. For example:
```css
[type=text][type="checkbox"] {}
/* becomes */
[type="text"][type="checkbox"] {
}
```
The quotes are not _necessary_ syntactically, but ensure consistency across the board (and this matches Prettier's output).
Once quote styles are supported, this will also select the appropriate quote character to use, but that is a future situation.
The attribute matching spec test is updated with quoted values.

feat(css_formatter): Always quote attribute matcher values

---

crates/biome_json_formatter/src/comments.rs
crates/biome_json_formatter/src/json/value/array_value.rs
crates/biome_json_formatter/src/json/value/object_value.rs
crates/biome_json_formatter/tests/specs/json/comments/empty_with_comments.json
crates/biome_json_formatter/tests/specs/json/comments/empty_with_comments.json.snap

Fixes #1322. Comments within empty object and array values are now placed as dangling comments, which those nodes then handle formatting for directly to place them within the braces for the value. For example:
```jsonc
{
"object-block": { /* here's a block comment */},
"object-line": { // here's a line comment
},
"object-ownline": {
/* here's a block comment */
// and a line comment
}
}
// Now becomes
{
"object-block": {
/* here's a block comment */
},
"object-line": {
// here's a line comment
},
"object-ownline": {
/* here's a block comment */
// and a line comment
}
}
```
Added a snapshot test to cover various permutations of comments in empties.

fix(json_formatter): handle comments in empty arrays/objects

---

CHANGELOG.md
crates/biome_js_analyze/src/analyzers/style/use_exponentiation_operator.rs
crates/biome_js_analyze/tests/specs/style/useExponentiationOperator/invalidWithComments.js
crates/biome_js_analyze/tests/specs/style/useExponentiationOperator/invalidWithComments.js.snap
website/src/content/docs/internals/changelog.mdx

Before making the code fix of `useExponentiationOperator` safe, we should improve comment preservation.
This PR improves it by transferring comment following the optional trailing comma of `Math.pow` call.
New test added.

refactor(lint/useExponentiationOperator): preserve more comments in code fix

---

crates/biome_css_formatter/src/css/auxiliary/declaration_or_at_rule_block.rs
crates/biome_css_formatter/src/css/auxiliary/declaration_with_semicolon.rs
crates/biome_css_formatter/src/css/auxiliary/page_at_rule_block.rs
crates/biome_css_formatter/src/css/auxiliary/page_selector_pseudo.rs
crates/biome_css_formatter/src/css/lists/declaration_list.rs
crates/biome_css_formatter/src/css/lists/declaration_or_at_rule_list.rs
crates/biome_css_formatter/src/css/lists/page_at_rule_item_list.rs
crates/biome_css_formatter/src/css/lists/page_selector_list.rs
crates/biome_css_formatter/src/css/selectors/page_selector.rs
crates/biome_css_formatter/src/css/statements/margin_at_rule.rs
crates/biome_css_formatter/src/css/statements/page_at_rule.rs
crates/biome_css_formatter/tests/specs/css/atrule/page.css
crates/biome_css_formatter/tests/specs/css/atrule/page.css.snap
crates/biome_css_formatter/tests/specs/css/atrule/page_complex.css
crates/biome_css_formatter/tests/specs/css/atrule/page_complex.css.snap

New at-rules added in #1319! In a follow-up PR, I think I'm going to start abstracting out some of the list formatting since there are a lot of nodes that use similar structures (either a separated list that gets printed compactly, or a non-separated list that preserves empty lines).
Added two spec tests to cover cases similar to the parser spec tests. The snapshots appear formatted correctly.

feat(css_formatter): support @page and margin at-rules

---

crates/biome_css_formatter/src/css/auxiliary/layer_declaration.rs
crates/biome_css_formatter/src/css/auxiliary/layer_reference.rs
crates/biome_css_formatter/src/css/auxiliary/scope_edge.rs
crates/biome_css_formatter/src/css/auxiliary/scope_range_end.rs
crates/biome_css_formatter/src/css/auxiliary/scope_range_interval.rs
crates/biome_css_formatter/src/css/auxiliary/scope_range_start.rs
crates/biome_css_formatter/src/css/lists/layer_name_list.rs
crates/biome_css_formatter/src/css/lists/layer_reference_list.rs
crates/biome_css_formatter/src/css/statements/layer_at_rule.rs
crates/biome_css_formatter/src/css/statements/scope_at_rule.rs
crates/biome_css_formatter/tests/quick_test.rs
crates/biome_css_formatter/tests/specs/css/atrule/layer.css
crates/biome_css_formatter/tests/specs/css/atrule/layer.css.snap
crates/biome_css_formatter/tests/specs/css/atrule/scope.css
crates/biome_css_formatter/tests/specs/css/atrule/scope.css.snap

#1285. This adds formatting support for `@scope` and `@layer` at-rules. One thing that became apparent from the tests here is that we'll need a way to force lowercase for all of the keyword tokens. We don't want to lowercase _all_ tokens, because names and such will still use uppercase, but anything that's a keyword should get lowercased. I added a function for lowercasing tokens in another PR, but I wonder if there's a more root-level place to do it that automatically covers all keywords but leaves identifiers alone, without having to have each callsite use another `Format` element.
Added spec tests based on the parser tests with various whitespace changes.

feat(css_formatter): format scope and layer at-rules

---

crates/biome_css_formatter/src/css/auxiliary/supports_and_condition.rs
crates/biome_css_formatter/src/css/auxiliary/supports_condition_in_parens.rs
crates/biome_css_formatter/src/css/auxiliary/supports_feature_declaration.rs
crates/biome_css_formatter/src/css/auxiliary/supports_not_condition.rs
crates/biome_css_formatter/src/css/auxiliary/supports_or_condition.rs
crates/biome_css_formatter/src/css/selectors/supports_feature_selector.rs
crates/biome_css_formatter/src/css/statements/supports_at_rule.rs
crates/biome_css_formatter/tests/specs/css/atrule/supports.css
crates/biome_css_formatter/tests/specs/css/atrule/supports.css.snap
crates/biome_css_formatter/tests/specs/css/atrule/supports_complex.css
crates/biome_css_formatter/tests/specs/css/atrule/supports_complex.css.snap

#1285. Support for `@supports`! These rules are also very similar to media query and container query lists. I'm not sure if there's a great way to genericize the formatting for them, since they all need independent nodes for the syntax tree, but the formatting structure is very similar (group, soft block indent, and/not/or conditions, etc.).
Copied over the parser spec tests with whitespace changes to cover all of the various permutations. This test suite again shows the need for a mechanism to lowercase keywords.

feat(css_formatter): formatting support for supports at-rules

---

crates/biome_css_formatter/src/css/auxiliary/attribute_matcher_value.rs
crates/biome_css_formatter/src/css/auxiliary/identifier.rs
crates/biome_css_formatter/src/lib.rs
crates/biome_css_formatter/tests/specs/css/atrule/container.css.snap
crates/biome_css_formatter/tests/specs/css/atrule/layer.css.snap
crates/biome_css_formatter/tests/specs/css/atrule/page.css.snap
crates/biome_css_formatter/tests/specs/css/atrule/scope.css.snap
crates/biome_css_formatter/tests/specs/css/atrule/supports.css.snap
crates/biome_css_formatter/tests/specs/css/casing.css
crates/biome_css_formatter/tests/specs/css/casing.css.snap
crates/biome_json_formatter/src/lib.rs

Dependent on #1353. This PR starts automatically writing all keywords and regular identifiers in lowercase. By definition in the spec, this should be a safe transformation, but only because we now distinguish between regular and custom/dashed identifiers (the latter are case _sensitive_). The one apparent exception that I've found, `@page` rule names, is also parsed using a `CssCustomIdentifier`, ensuring that it preserves casing, even though the spec uses a regular `<ident>` and just states "this one's case sensitive".
This behavior is _similar_ to what Prettier does, but actually a lot more consistent. Prettier does _not_ downcase type selectors, attribute selectors, value definitions, and other things, even though they are explicitly defined as case-insensitive. Biome's behavior after …

feat(css_formatter): automatically downcase all keywords and regular identifiers

---

crates/biome_css_formatter/src/lib.rs
crates/biome_css_formatter/tests/specs/css/range/between_rules.css
crates/biome_css_formatter/tests/specs/css/range/between_rules.css.snap
crates/biome_css_formatter/tests/specs/css/range/keyframes.css
crates/biome_css_formatter/tests/specs/css/range/keyframes.css.snap
crates/biome_css_formatter/tests/specs/css/range/mid_value.css
crates/biome_css_formatter/tests/specs/css/range/mid_value.css.snap
crates/biome_css_formatter/tests/specs/css/range/selector_list.css
crates/biome_css_formatter/tests/specs/css/range/selector_list.css.snap
crates/biome_css_formatter/tests/specs/css/range/single_declaration.css
crates/biome_css_formatter/tests/specs/css/range/single_declaration.css.snap
crates/biome_css_formatter/tests/specs/css/range/single_rule.css
crates/biome_css_formatter/tests/specs/css/range/single_rule.css.snap
crates/biome_css_formatter/tests/specs/css/range/single_value.css
crates/biome_css_formatter/tests/specs/css/range/single_value.css.snap

#1285. This PR adds some better heuristics for handling `format_range` for CSS. In general, the logic expands the range until it hits the boundary of:
- a declaration
- a rule
- an individual value
- a complete component value list
- a selector list
- or any block-like structure
This also adds a number of tests to check that those range boundaries are being respected.

feat(css_formatter): support meaningful boundaries for range formatting

---

crates/biome_cli/src/execute/traverse.rs
crates/biome_cli/tests/commands/ci.rs
crates/biome_cli/tests/snapshots/main_commands_ci/correctly_handles_ignored_and_not_ignored_files.snap

Closes https://github.com/biomejs/biome/issues/1360
The issue is already fixed in `main`.
Added new test case.
I checked that `linter-ignored` has diagnostics that belong to only `format` category.
I checked that `formatter-ignored` has diagnostics that belong only to `lint` category.

chore: add test case for issue

---

CHANGELOG.md
crates/biome_lsp/tests/server.rs
crates/biome_service/src/file_handlers/javascript.rs
crates/biome_service/src/file_handlers/json.rs
crates/biome_service/src/file_handlers/mod.rs
crates/biome_service/src/workspace/server.rs
justfile
website/src/content/docs/internals/changelog.mdx

Closes https://github.com/biomejs/biome/issues/1394
Newly created files weren't correctly processed when calling the analyzer from the LSP. The reason why this wasn't working anymore is because:
- Some time ago we changed the JavaScript analyzer to accept the `JsFileSource`, which tells what kind of JavaScript file we are processing (JS, JSX, TS, etc.). The analyser changed to default to zero diagnostics in case we couldn't compute the `JsFileSource` from the file path. This broke the LSP when the LSP analyzed untitled files.
- We didn't have a test to check these cases
Untitled files are saved and updated by using the actions `textDocument/didOpen` and `textDocument/didChange`, that's where we keep track of their language.
Now when pulling diagnostics and computing `JsFileSource`, we:
- …

fix(lsp): correctly infer file source from un-named files

---

crates/biome_css_parser/src/lib.rs
crates/biome_css_parser/src/parser.rs
crates/biome_css_parser/src/state.rs
crates/biome_css_parser/src/syntax/mod.rs
crates/biome_css_parser/src/token_source.rs
crates/biome_js_parser/src/lib.rs
crates/biome_js_parser/src/parser.rs
crates/biome_js_parser/src/parser/rewrite_parser.rs
crates/biome_js_parser/src/state.rs
crates/biome_js_parser/src/token_source.rs
crates/biome_parser/src/token_source.rs

From https://github.com/biomejs/biome/issues/268#issuecomment-1874820626, this implements checkpoint rewinding for the CSS parser to set up for attempting to parse property values and then falling back to generics if the parse fails for any reason.
I think there's another possibility of using `rewrite_events` the way that the `JsParser` does to avoid the need for rewinding, but I think it's actually okay to just rewind since there's little cost to it, and we aren't enforcing a particular structure on the re-parsed content (it could be either `GenericComponentValueList` or `Bogus`, we don't actually know at the point of rewinding).
Added a test around `try_parse` to ensure it rewinds as expected on error and preserves the position on success. Future PRs will start actually using it in the …

feat(parser,css_parser): implement checkpoint rewinding

---

CHANGELOG.md
crates/biome_js_analyze/src/analyzers/nursery/use_filenaming_convention.rs
crates/biome_js_analyze/tests/specs/nursery/useFilenamingConvention/ValidPascalCase.js.snap
crates/biome_js_analyze/tests/specs/nursery/useFilenamingConvention/ValidPascalCase.options.json
packages/@biomejs/backend-jsonrpc/src/workspace.ts
packages/@biomejs/biome/configuration_schema.json
website/src/content/docs/internals/changelog.mdx
website/src/content/docs/linter/rules/use-filenaming-convention.md

Address #1409
We now allows `pascalCase` as variant for `filenameCases` configuration.
By default, this variant is not included.
New test added

feat(lint/useFilenamingConvention): allow PascalCase in config

---

CHANGELOG.md
crates/biome_cli/src/commands/daemon.rs
crates/biome_cli/src/commands/explain.rs
crates/biome_cli/src/commands/mod.rs
crates/biome_cli/src/lib.rs
crates/biome_cli/tests/commands/explain.rs
crates/biome_cli/tests/snap_test.rs
crates/biome_cli/tests/snapshots/main_commands_explain/explain_help.snap
crates/biome_cli/tests/snapshots/main_commands_explain/explain_logs.snap
crates/biome_cli/tests/snapshots/main_commands_explain/explain_logs.snap.new
crates/biome_service/src/documentation/mod.rs
website/src/content/docs/guides/integrate-in-editor.mdx
website/src/content/docs/internals/changelog.mdx

This PR removes `__print-cache-dir`.
Instead, I added `daemon-logs` to the `biome explain` command.
Added a new snapshot test

feat(cli): document daemon logs directory

---

justfile

- Fix a typo
- Format on `just gen-lint`
- Remove double formatting when running `just ready`
Locally tested

chore(justfile): fix typo and minor improvements

---

crates/biome_js_analyze/tests/specs/nursery/noGlobalEval/valid.js
crates/biome_js_analyze/tests/specs/nursery/noGlobalEval/valid.js.snap
crates/biome_js_analyze/tests/specs/nursery/noGlobalEval/validtest.cjs
crates/biome_js_analyze/tests/specs/nursery/noGlobalEval/validtest.cjs.snap

Address TODO.
The `eval` identifier is not allowed in strict mode.
Thus, I created a new test file with `cjs` extension to test in non-strict mode.

test(lint/noGlobalEval): address TODO

---

CHANGELOG.md
crates/biome_cli/src/execute/mod.rs
crates/biome_diagnostics/src/lib.rs
website/src/content/docs/internals/changelog.mdx

This PR removed the internal hard-coded limit we had when printing the diagnostics.
Many users were frustrated by this.
I locally ran `cargo biome-cli-dev format --max-diagnostics=10000` inside our repository and ensured that ALL diagnostics were printed. Usually, you have the message "Diagnostics not shown". It wasn't there during my test!

feat(cli): remove the hardcoded limit of 200 printable diagnostics

---

CHANGELOG.md
crates/biome_js_analyze/src/analyzers/suspicious/no_confusing_void_type.rs
crates/biome_js_analyze/tests/specs/suspicious/noConfusingVoidType/invalid.ts
crates/biome_js_analyze/tests/specs/suspicious/noConfusingVoidType/invalid.ts.snap
crates/biome_js_analyze/tests/specs/suspicious/noConfusingVoidType/valid.ts
crates/biome_js_analyze/tests/specs/suspicious/noConfusingVoidType/valid.ts.snap
website/src/content/docs/internals/changelog.mdx

fix(lint/noConfusingVoidType): accept `void` in type param lists

---

website/src/content/docs/linter/rules/index.mdx
xtask/lintdoc/src/main.rs

Table header of [rule listing](https://biomejs.dev/linter/rules/) is badly ordered. This PR fixes the issue.

fix(website): fix order of table header for rules

---

crates/biome_js_analyze/src/semantic_analyzers/correctness/use_exhaustive_dependencies.rs
website/src/content/docs/linter/rules/use-exhaustive-dependencies.md

- Add the missing word 'can' in paragraph
- Ensure the sentence now reads correctly

Fix missing word in use-exhaustive-dependencies.md

---

CHANGELOG.md
crates/biome_js_formatter/src/js/expressions/arrow_function_expression.rs
crates/biome_js_formatter/tests/specs/js/module/arrow/assignment_binding_line_break.js
crates/biome_js_formatter/tests/specs/js/module/arrow/assignment_binding_line_break.js.snap
crates/biome_js_formatter/tests/specs/ts/arrow/parameter_default_binding_line_break.ts
crates/biome_js_formatter/tests/specs/ts/arrow/parameter_default_binding_line_break.ts.snap
website/src/content/docs/internals/changelog.mdx

Fixes #1106. Fixes #1428.
Added two spec tests to cover the cases given in the issue reports.

fix(js_formatter): fix invalid formatting of expanded bindings for AsNeeded arrow parens

---

crates/biome_js_analyze/tests/specs/style/useNumericLiterals/invalid.js.snap
crates/biome_js_syntax/src/expr_ext.rs

`JsNumberLiteralExpression::as_number` wasn't ignoring trivia of the interal token, so it was almost always returning `None`.
Added a doctest, it failed without the change and now it passes.

fix: JsNumberLiteralExpression::as_number ignore trivia

---

crates/biome_js_analyze/src/semantic_analyzers/correctness/use_hook_at_top_level.rs
crates/biome_js_analyze/tests/specs/correctness/useHookAtTopLevel/invalid.js
crates/biome_js_analyze/tests/specs/correctness/useHookAtTopLevel/invalid.js.snap
crates/biome_js_analyze/tests/specs/correctness/useHookAtTopLevel/valid.js
crates/biome_js_analyze/tests/specs/correctness/useHookAtTopLevel/valid.js.snap

Given there was a small regression in #610, I added a test case for it and tried to come up with some more test cases that might be giving false positives still. 
Fixing the one specific regression was easy, but as I added more test cases, I realized our current approach of whitelisting safe nodes wasn't the best way forward. There are many more types of nodes that needed whitelisting than node types that actually introduce conditional branches. But the one that really tipped the scales was this test case:
```js
const otherValue = useValue() || defaultValue;
```
Intuitively this code should be valid since we call `useValue()` from the top-level of the component. Technically there is also no reason to disallow it, since it is being called unconditionally and doesn't violate the rules of …

fix(lint/useHookAtTopLevel): stricter checking for conditional hook calls

---

xtask/codegen/src/formatter.rs

As we start to implement exact parsing for all of the properties, we're going to start having formatter files for each one (multiple actually. an `any`, a `property`, and at least one `property_value` file to cover each added node.
Each of the overall Property nodes will have _exactly_ the same structure and get formatted exactly the same way:
```rust
use crate::prelude::*;
use biome_css_syntax::{CssBorderProperty, CssBorderPropertyFields};
use biome_formatter::write;
#[derive(Debug, Clone, Default)]
pub(crate) struct FormatCssBorderProperty;
impl FormatNodeRule<CssBorderProperty> for FormatCssBorderProperty {
fn fmt_fields(&self, node: &CssBorderProperty, f: &mut CssFormatter) -> FormatResult<()> {
let CssBorderPropertyFields {
name,
colon_token,
value,
} = node.as_fields();
write!(
f, …
```

feat(codegen,css_formatter): autogenerate property formattting boilerplate

---

CHANGELOG.md
crates/biome_js_analyze/src/analyzers/complexity/use_arrow_function.rs
crates/biome_js_analyze/tests/specs/complexity/useArrowFunction/invalid.ts
crates/biome_js_analyze/tests/specs/complexity/useArrowFunction/invalid.ts.snap
crates/biome_js_analyze/tests/specs/complexity/useArrowFunction/valid.ts
crates/biome_js_analyze/tests/specs/complexity/useArrowFunction/valid.ts.snap
website/src/content/docs/internals/changelog.mdx

Fix #1436 and ignore function expressions using [`new.target`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target).
Additionally, we no longer check every function parameters for detecting the `this` parameter. 
New tests included.

fix(lint/useArrowFunction): handle fixes that needs parens

---

crates/biome_js_analyze/src/semantic_analyzers/nursery/no_invalid_use_before_declaration.rs
crates/biome_js_analyze/tests/specs/nursery/noInvalidUseBeforeDeclaration/valid.js
crates/biome_js_analyze/tests/specs/nursery/noInvalidUseBeforeDeclaration/valid.js.snap
crates/biome_js_analyze/tests/specs/nursery/noInvalidUseBeforeDeclaration/valid.ts
crates/biome_js_analyze/tests/specs/nursery/noInvalidUseBeforeDeclaration/valid.ts.snap

Allow use-before declarations when the variable is used as a type.
This removes many false positives.
New test included.

refcator(lint/noInvalidUseBeforeDeclaration): allow use before as a type

---

crates/biome_deserialize/src/json.rs
crates/biome_deserialize/src/lib.rs
crates/biome_project/src/node_js_project/package_json.rs
crates/biome_service/src/configuration/diagnostics.rs
crates/biome_service/src/configuration/mod.rs
crates/biome_service/src/file_handlers/json.rs
crates/biome_service/tests/spec_tests.rs
crates/biome_test_utils/src/lib.rs

Allow naming the root deserialized value.
This addresses some requests of #1250.

refactor(deserialize): allow setting name for root deserialized value

---

editors/helix/manual.md

The info on Helix was out of date, version `23.10` has been out for 5 weeks+: https://helix-editor.com/news/release-23-10-highlights/. It now has the multiple language servers feature built in. You can see it is widely adopted here: https://github.com/helix-editor/helix#installation, and anyone can download the binary https://github.com/helix-editor/helix/releases/tag/23.10, so it is readily available for all users.
Another point of concern is the redundancy of keys in the current configuration. Many of the keys are unnecessary duplicates, as they are already inherited from the default configuration found at https://github.com/helix-editor/helix/blob/master/languages.toml. Users should only need to specify overrides or add new keys in their personal configuration files. I have not altered …

docs: update language server setup info for Helix

---

crates/biome_cli/tests/snapshots/main_cases_protected_files/not_process_file_from_cli_verbose.snap
crates/biome_cli/tests/snapshots/main_cases_protected_files/not_process_file_from_stdin_verbose_format.snap
crates/biome_cli/tests/snapshots/main_cases_protected_files/not_process_file_from_stdin_verbose_lint.snap
crates/biome_service/src/diagnostics.rs

Currently, Biome tells users to use `--diagnostic-level=warning` instead of `--diagnostic-level=warn`. This change corrects it to the proper value.
Fixes #1467

fix: Use the correct diagnostic level in advice

---

website/astro.config.ts

This PR add `<link rel="alternate" type="application/rss+xml" href="https://biomejs.dev/feed.xml">` to website `<head>`.
It helps user find RSS feed.
- [HTML attribute: rel - HTML: HyperText Markup Language | MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel)
For example, Feedly and Inoreader can discover the URL of an RSS feed by looking at this tag.
Check response of website.
```shell
curl -s "http://localhost:4321/" | grep "application/rss+xml"
<!DOCTYPE html><html lang="en" dir="ltr" data-has-hero class="astro-oli6443q"> <head><meta charset="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1"/><title>Biome, toolchain of the web</title><link rel="canonical" href="https://biomejs.dev/"/><link rel="alternate" hreflang="en" …
```

docs(website): add `<link rel=alternate>` to RSS feeds

---

CHANGELOG.md
crates/biome_js_analyze/src/analyzers/style/use_consistent_array_type.rs
crates/biome_js_analyze/src/options.rs
crates/biome_js_analyze/tests/specs/style/useConsistentArrayType/invalidShorthand.options.json
crates/biome_js_analyze/tests/specs/style/useConsistentArrayType/invalidShorthand.ts
crates/biome_js_analyze/tests/specs/style/useConsistentArrayType/invalidShorthand.ts.snap
crates/biome_js_analyze/tests/specs/style/useConsistentArrayType/validGeneric.options.json
crates/biome_js_analyze/tests/specs/style/useConsistentArrayType/validGeneric.ts
crates/biome_js_analyze/tests/specs/style/useConsistentArrayType/validGeneric.ts.snap
packages/@biomejs/backend-jsonrpc/src/workspace.ts
packages/@biomejs/biome/configuration_schema.json
website/src/content/docs/internals/changelog.mdx

fix(lint/useConsistentArrayType): correctly handle rule's option

---

crates/biome_cli/src/commands/mod.rs

Fix a forgotten debug print.
I tested locally.

fix(cli): don't print loaded config on error

---

crates/biome_cli/src/cli_options.rs
crates/biome_cli/src/commands/check.rs
crates/biome_cli/src/commands/ci.rs
crates/biome_cli/src/commands/format.rs
crates/biome_cli/src/commands/lint.rs
crates/biome_cli/src/commands/mod.rs
crates/biome_cli/src/execute/mod.rs
crates/biome_wasm/Cargo.toml

Small refactor/clean-up in the CLI
Current CI should pass

refactor(cli): some cleanup

---

CHANGELOG.md
crates/biome_js_analyze/src/analyzers/complexity/use_arrow_function.rs
crates/biome_js_analyze/tests/specs/complexity/useArrowFunction/invalid.ts
crates/biome_js_analyze/tests/specs/complexity/useArrowFunction/invalid.ts.snap
crates/biome_js_analyze/tests/specs/complexity/useArrowFunction/valid.ts
crates/biome_js_analyze/tests/specs/complexity/useArrowFunction/valid.ts.snap
website/src/content/docs/internals/changelog.mdx

fix(lint/useArrowFunction): enclose with parens when needed

---

website/src/content/docs/zh-cn/guides/getting-started.mdx
website/src/content/docs/zh-cn/guides/how-biome-works.mdx
website/src/content/docs/zh-cn/guides/integrate-in-vcs.mdx
website/src/content/docs/zh-cn/guides/manual-installation.mdx
website/src/content/docs/zh-cn/internals/changelog.mdx

Upgrade Chinese translation doc, content and format.
N/A

doc(website): upgrade doc for cn

---

CHANGELOG.md
crates/biome_js_formatter/src/comments.rs
crates/biome_js_formatter/tests/specs/js/module/decorators/class_members_call_decorator.js.snap
crates/biome_js_formatter/tests/specs/js/module/decorators/class_members_mixed.js.snap
crates/biome_js_formatter/tests/specs/js/module/decorators/class_members_simple.js.snap
crates/biome_js_formatter/tests/specs/prettier/typescript/decorators/decorators-comments.ts.snap
website/src/content/docs/internals/changelog.mdx

Ensure the comments in front of the`*` token are placed in front of `*` for generators. If the following token of the comment is the `*` token then attach the comment to the preceding node.
```js
class Foo {
@decorator()
/* comment */ *method(){}
}
// before fix
class Foo {
@decorator()
*/* comment */ method() {}
}
// after fix
class Foo {
@decorator()
/* comment */
*method() {}
}
// prettier
class Foo {
@decorator()
/* comment */
*method() {}
}
```

fix(js_formatter): ensure comments before `*` are placed before `*` in generators

---

CHANGELOG.md
crates/biome_js_analyze/src/analyzers/a11y/no_blank_target.rs
crates/biome_js_analyze/src/analyzers/complexity/no_excessive_cognitive_complexity.rs
website/src/content/blog/biome-v1.mdx
website/src/content/blog/biome-wins-prettier-challenge.md
website/src/content/docs/guides/integrate-in-editor.mdx
website/src/content/docs/internals/changelog.mdx
website/src/content/docs/ja/guides/integrate-in-editor.mdx
website/src/content/docs/linter/rules/no-blank-target.md
website/src/content/docs/linter/rules/no-excessive-cognitive-complexity.md
website/src/content/docs/pt-br/guides/integrate-in-editor.mdx
website/src/content/docs/zh-cn/internals/changelog.mdx

I used https://www.drlinkcheck.com to detect dead links and http links.
This PR fixes these dead links and replace `http` with `https` protocol.

fix(website): fix dead links

---

website/src/content/docs/guides/getting-started.mdx
website/src/content/docs/ja/guides/getting-started.mdx
website/src/content/docs/pt-br/guides/getting-started.mdx
website/src/content/docs/reference/configuration.mdx
website/src/content/docs/zh-cn/guides/getting-started.mdx
website/src/content/docs/zh-cn/reference/configuration.mdx

Update outdated `$schema` url.
Fix #1534

fix(docs): update $schema url

---

CHANGELOG.md
crates/biome_formatter/src/buffer.rs
crates/biome_js_formatter/tests/specs/ts/issue1511.ts
crates/biome_js_formatter/tests/specs/ts/issue1511.ts.snap
website/src/content/docs/internals/changelog.mdx
website/src/content/docs/zh-cn/internals/changelog.mdx

fix(js_formatter): fix #1511

---

crates/biome_cli/Cargo.toml
crates/biome_cli/src/commands/migrate.rs
crates/biome_cli/src/commands/mod.rs
crates/biome_cli/src/execute/migrate.rs
crates/biome_cli/src/execute/migrate/prettier.rs
crates/biome_cli/src/execute/mod.rs
crates/biome_cli/src/lib.rs
crates/biome_deserialize/README.md
crates/biome_js_formatter/src/context.rs

This PR sets the foundation for the future command `biome migrate --prettier`.
This PR creates the data structure that mimics the prettier configuration and its deserialisation, and it converts it to the Biome configuration.
Added a couple of tests. CI should pass

feat: foudations for migration from prettier

---

CHANGELOG.md
crates/biome_cli/tests/cases/protected_files.rs
crates/biome_cli/tests/snapshots/main_cases_protected_files/not_process_file_linter_disabled_from_cli_verbose.snap
crates/biome_cli/tests/snapshots/main_cases_protected_files/not_process_ignored_file_from_cli_verbose.snap
crates/biome_service/src/workspace.rs
crates/biome_service/src/workspace/server.rs
website/src/content/docs/internals/changelog.mdx

This PR improves file handling.
- Protected files that are ignored in the configuration (or with the feature disabled) no longer emits verbose warnings.
- I removed `.gitignore` from the protected list because the file language is not supported by Biome
Thus, it should emit an unsuported file warning.

refactor(cli): do not emit warnings for protected ignored files

---

CONTRIBUTING.md

This PR moves myself from the `Maintainers team` section to the `Core Contributors team` section.

chore: move `nhedger` to core contributors

---

CHANGELOG.md
crates/biome_cli/tests/cases/included_files.rs
crates/biome_cli/tests/commands/format.rs
crates/biome_cli/tests/snapshots/main_commands_format/include_ignore_cascade.snap
crates/biome_cli/tests/snapshots/main_commands_format/include_vcs_ignore_cascade.snap
crates/biome_cli/tests/snapshots/main_commands_format/override_don_t_affect_ignored_files.snap
crates/biome_cli/tests/snapshots/main_commands_format/vcs_absolute_path.snap
crates/biome_service/src/configuration/formatter.rs
crates/biome_service/src/configuration/linter/mod.rs
crates/biome_service/src/configuration/organize_imports.rs
crates/biome_service/src/configuration/overrides.rs
crates/biome_service/src/matcher/mod.rs
crates/biome_service/src/settings.rs
crates/biome_service/src/workspace/server.rs
website/src/content/docs/internals/changelog.mdx

- `overrides` no longer affect which files got ignored
- Reverse application order of `include`/`ignore`.
First apply global `include`/`ignore`, then tools' `include`/`ignore`

fix(config): apply global include/ignore before tools' include/ignore

---

CHANGELOG.md
packages/@biomejs/biome/package.json
website/src/content/docs/guides/getting-started.mdx
website/src/content/docs/internals/changelog.mdx
website/src/content/docs/ja/guides/getting-started.mdx
website/src/content/docs/pt-br/guides/getting-started.mdx
website/src/content/docs/reference/configuration.mdx
website/src/content/docs/zh-cn/guides/getting-started.mdx
website/src/content/docs/zh-cn/reference/configuration.mdx
website/src/pages/schemas/1.5.2/schema.json.js

Patch release that includes multiple fixes around `include` and `ignore` handling.
This patch version should also remove the last regressions introduced in 1.5.0:
- Ignored protected files are no longer reported.
- Protected file diagnostics are no longer counted to determine if the number of diagnostics to be printed has reached the maximum allowed.

release: 1.5.2

---

CHANGELOG.md
crates/biome_css_factory/src/generated/syntax_factory.rs
crates/biome_js_analyze/src/semantic_analyzers/correctness/use_exhaustive_dependencies.rs
crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/checkHooksImportedFromReact.js.snap
crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/customHook.js.snap
crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/extraDependenciesInvalid.js.snap
crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/missingDependenciesInvalid.js.snap
justfile
website/src/content/docs/internals/changelog.mdx
website/src/content/docs/linter/rules/use-exhaustive-dependencies.md

As written below issue, I want `useExhaustiveDependencies` rule to show dependency variable names even when we look errors on VSCode, so I added dependency variable names on error message.
close https://github.com/biomejs/biome/issues/1391
I have no confidence in my PR, so if my approach isn't good or something wrong, please tell me.
Please look over changed snapshot test files.

feat(linter): show dependency variable name by useExhaustiveDependencies

---

crates/biome_css_formatter/src/css/auxiliary/border.rs
crates/biome_css_formatter/src/css/auxiliary/line_style.rs
crates/biome_css_formatter/src/css/auxiliary/line_width_keyword.rs
crates/biome_css_formatter/src/css/properties/border_property.rs
crates/biome_css_formatter/src/prelude.rs
crates/biome_css_formatter/src/utils/mod.rs
crates/biome_css_formatter/src/utils/properties.rs
crates/biome_css_formatter/tests/quick_test.rs
crates/biome_css_formatter/tests/specs/css/properties/border.css
crates/biome_css_formatter/tests/specs/css/properties/border.css.snap
crates/biome_css_syntax/src/generated/nodes.rs
crates/biome_formatter/src/arguments.rs
crates/biome_js_syntax/src/generated/nodes.rs
crates/biome_json_syntax/src/generated/nodes.rs
crates/biome_rowan/src/ast/mod.rs
xtask/codegen/src/generate_nodes.rs

#1285. Continuing on the demonstration of `border` being the first property to be _parsed_ exactly, this is a demonstration of how the property can be _formatted_` exactly as well.
Turns out it gets a little complicated! The primary addition here is the new `FormatPropertyValueFields` struct, which implements all of the logic. Given a list of fields, and optionally a slot map, it takes care of building up the `Fill` element with all of the values. This is what `write_component_value_list` was already doing for the generic versions, but for the new exact versions it needs to be a bit more involved (the generic ones will still use that function as the fallback).
When there's no `slot_map` given, the new struct just iterates the fields and adds them as entries to the `Fill` element. When …

feat(css_formatter): Formatting for `border` property

---

CHANGELOG.md
crates/biome_js_formatter/src/comments.rs
crates/biome_js_formatter/tests/specs/js/module/comments/nested_comments/nested_comments.js
crates/biome_js_formatter/tests/specs/js/module/comments/nested_comments/nested_comments.js.snap
crates/biome_js_formatter/tests/specs/js/module/comments/nested_comments/options.json
website/src/content/docs/internals/changelog.mdx

Closes https://github.com/biomejs/biome/issues/1571
The potential cause of the incorrect formatting of nested multiline comments may stem from nesting `Align`s. 
```
align(2, [
"{",
group(expand: true, [
indent([
soft_line_break_or_space,
group(expand: propagated, [
"/**",
align(1, [
hard_line_break,
"* blah",
hard_line_break,
"*/"
]),
hard_line_break,
"id: string"
]),
if_group_breaks([";"])
]),
soft_line_break_or_space
]),
"}"
]),
soft_line_break_or_space,
"| ",
align(2, ["boolean"])
])
```
Referencing the comment https://github.com/biomejs/biome/blob/1c91b03b2c3d0cf76da40d9b5f36a4d2d38ef7f2/crates/biome_formatter/src/format_element/tag.rs#L19 it provides an explanation of how nesting Align functions. In the reported issue, Transforming `Align(2) Indent Align(1)` to `Indent Indent …

fix(js_formatter): fix invalid formatting of nested multiline comments

---

CHANGELOG.md
crates/biome_cli/tests/commands/format.rs
crates/biome_formatter/src/printer/mod.rs
crates/biome_service/src/file_handlers/javascript.rs
crates/biome_service/src/file_handlers/json.rs
website/src/content/docs/internals/changelog.mdx

Closes https://github.com/biomejs/biome/issues/1178
Added a new test case, no snapshot because it's useless in this case.

fix(formatter): apply line ending option

---

CHANGELOG.md
crates/biome_lsp/src/capabilities.rs
website/src/content/docs/internals/changelog.mdx

This PR changes the way the formatting providers are registered by the LSP to prevent registering a formatter twice.
Some LSP clients do not support dynamic registration for formatting providers, so in PR #1042 , we explicitly enabled static registration of the formatters. Unfortunately, this caused clients that support dynamic registration to show two formatters (the statically registered one, and the dynamically registered one).
This PR adds logic to detect whether the clients supports dynamic registration of formatters, and skips the static registration when they do.
- Ensure only one formatter is registered in VS Code's `Format Document with...` menu.
Fixes #1584

fix(lsp): register formatter dynamically if possible

---

website/src/content/docs/guides/how-biome-works.mdx

We don't support the syntax `{a,b}` for now.
N/A

chore: update documentation

---

crates/biome_formatter/src/comments.rs

Discussed in discord: https://discord.com/channels/1132231889290285117/1132602615570649110/1197890329559445587 but the existing example incorrectly has `b` inside the comment, and claims it is the next token.
N/A

fix(docs): fix `biome_formatter::comments::following_token` example in rustdoc

---

CHANGELOG.md
crates/biome_js_formatter/src/comments.rs
crates/biome_js_formatter/tests/specs/js/module/comments/import_exports.js
crates/biome_js_formatter/tests/specs/js/module/comments/import_exports.js.snap
website/src/content/docs/internals/changelog.mdx

Fixes #1589
Happy to receive feedback on the implementation, not sure if there are obvious edge-cases I'm not considering, but it passes the test suite!
Ive added a snapshot from the issue with import/export, and pass the prettier tests

fix(formatter): correctly handle comments at end of export/import list

---

website/src/content/docs/ja/recipes/git-hooks.mdx
website/src/content/docs/pt-br/recipes/git-hooks.mdx
website/src/content/docs/recipes/git-hooks.mdx
website/src/content/docs/zh-cn/recipes/git-hooks.mdx

- fix only documantation
- rename biomejs/pre-commit version `0.1.0` to `v0.1.0` https://github.com/biomejs/pre-commit/releases/tag/v0.1.0
copy sample `.pre-commit-config.yaml`
```
pre-commit install
```

docs: fix pre-commit sample version v0.1.0

---

CHANGELOG.md
crates/biome_cli/tests/cases/overrides_linter.rs
crates/biome_cli/tests/snapshots/main_cases_overrides_linter/does_merge_all_overrides.snap
crates/biome_cli/tests/snapshots/main_cases_overrides_linter/does_override_groupe_recommended.snap
crates/biome_cli/tests/snapshots/main_cases_overrides_linter/does_override_recommended.snap
crates/biome_cli/tests/snapshots/main_cases_overrides_linter/does_preserve_group_recommended_when_override_global_recommened.snap
crates/biome_cli/tests/snapshots/main_cases_overrides_linter/does_preserve_individually_diabled_rules_in_overrides.snap
crates/biome_service/src/configuration/linter/rules.rs
crates/biome_service/src/settings.rs
crates/biome_service/src/workspace/server.rs
website/src/content/docs/internals/changelog.mdx
xtask/codegen/src/generate_configuration.rs

Fix #1349
The issue was coming from the default value of `recommended` that resulted in adding disabled rules in the rule's filter.
I solved the issue by first merging config with overrides before extracting the enabled rules.
This makes the code simpler and more robust because we reuse the config merge logic.
To reduce the potential cost of cloning the config for every file, I used `Cow`. Thus, the config is only cloned when a file has at least one override.

fix(linter): correctly override linter presets

---

website/src/content/docs/recipes/git-hooks.mdx

Fix scripts of the git hooks page.

fix(website): git hook shell scripts

---

crates/biome_js_parser/src/syntax/typescript/types.rs
crates/biome_js_parser/test_data/inline/ok/ts_call_signature_member.rast
crates/biome_js_parser/test_data/inline/ok/ts_call_signature_member.ts
crates/biome_js_parser/test_data/inline/ok/ts_property_or_method_signature_member.rast
crates/biome_js_parser/test_data/inline/ok/ts_property_or_method_signature_member.ts

- Closes: #1624
snapshots updated.

fix(js_parser): Allow `const` in TsMethodSignatureTypeMember and TsCallSignatureTypeMember

---

website/src/content/docs/linter/index.mdx

- rule sources page -> rules sources page
- /linter/rule -> /linter/rules-sources

fix(website): rules sources page link

---

website/src/content/docs/reference/configuration.mdx
website/src/content/docs/zh-cn/reference/configuration.mdx

`allowTrailingComma` -> `allowTrailingCommas`
----
Also, I have a question. Why use the singular form `trailingComma` in `javascript.formatter`, but plural form `semicolons`?

fix(website): json option key typo

---

crates/biome_js_analyze/src/semantic_analyzers/nursery/use_sorted_classes.rs
crates/biome_js_analyze/src/semantic_analyzers/nursery/use_sorted_classes/class_info.rs
crates/biome_js_analyze/src/semantic_analyzers/nursery/use_sorted_classes/presets.rs
crates/biome_js_analyze/src/semantic_analyzers/nursery/use_sorted_classes/sort_config.rs

Since we don't have a structured way to pass the options, I decided to use `lazy_static` to reduce the allocation of strings. 
CI should pass, hopefully some gain in the analyzer.

chore(linter): reduce string allocations

---

website/src/content/docs/recipes/continuous-integration.mdx

I have created github actions that work with [reviewdog](https://github.com/reviewdog/reviewdog) to utilize the pull request commenting and commit suggestion functionality.
https://github.com/marketplace/actions/run-biome-with-reviewdog
https://github.com/mongolyy/reviewdog-action-biome
I believe this action will improve the usability of the combination of biome and github actions.
Check the [deployment preview](https://deploy-preview-1585--biomejs.netlify.app/recipes/continuous-integration/).

docs(website): add third-party tool in continuous integration section

---

CHANGELOG.md
crates/biome_js_analyze/src/analyzers/style/use_enum_initializers.rs
crates/biome_js_analyze/tests/specs/style/useEnumInitializers/invalid.ts
crates/biome_js_analyze/tests/specs/style/useEnumInitializers/invalid.ts.snap
website/src/content/docs/internals/changelog.mdx

Code action suggested by useEnumInitializers suggests [invalid code](https://biomejs.dev/playground/?code=ZQBuAHUAbQAgAFQAZQBzAHQAIAB7AAoAIAAgAE8AbgBlACAAPQAgADEALAAKACAAIABUAHcAbwAgAC8ALwAgAEMAcgBpAHQAaQBjAGEAbAAgAGUAcgByAG8AcgAsACAAcAByAGUAdgBlAG4AdABzACAAZABlAHYAIABhAG4AZAAgAHAAcgBvAGQAdQBjAHQAaQBvAG4ACgB9AA%3D%3D) if last member has a comment an no comma.
Added new test case

fix(linter): useEnumInitializers action with comment

---

website/src/content/docs/recipes/continuous-integration.mdx

I forgot that the version of github action was up when I created the #1585 pull request.
I will follow this.
Check the deployment preview.

docs(website): update third-party tool version in continuous integration section

---

crates/biome_cli/src/service/windows.rs

Renaming to avoid confusions on output of lsp.

fix(cli): use biome instead of rome on pipe

---

crates/biome_rowan/src/tree_builder.rs

Back port of [rowan#161](https://github.com/rust-analyzer/rowan/pull/161).

refactor(rowan): use niching for Checkpoint

---

website/src/content/docs/guides/how-biome-works.mdx

Remove docs for underused glob patterns.

refactor(website): remove underused glob pattern docs

---

crates/biome_service/src/configuration/formatter.rs
crates/biome_service/src/configuration/linter/mod.rs
crates/biome_service/src/configuration/organize_imports.rs
crates/biome_service/src/configuration/overrides.rs
crates/biome_service/src/matcher/mod.rs
crates/biome_service/src/settings.rs
crates/biome_service/src/workspace/server.rs

Move gitignore state to the files settings.
This avoids paying the cost of gitignore for every matcher.

refactor(biome_service): move gitignore from matcher to files settings

---

CHANGELOG.md
crates/biome_cli/src/execute/traverse.rs
crates/biome_cli/tests/commands/lint.rs
crates/biome_cli/tests/snapshots/main_commands_lint/fs_files_ignore_symlink.snap
crates/biome_fs/src/fs.rs
crates/biome_fs/src/fs/memory.rs
crates/biome_fs/src/fs/os.rs
crates/biome_fs/src/path.rs
website/src/content/docs/internals/changelog.mdx

Check for ignored directories and symlinks.
This fixes the [bug reported by Jarred](https://twitter.com/jarredsumner/status/1750706365516177414).
This also fixes a snapshot where two files under a symlinked and ignored directory were not ignored, because `can_handle` handled wrongly symlinks.

fix(cli): check for ignored dir and symlinks

---

CHANGELOG.md
crates/biome_js_formatter/src/utils/member_chain/chain_member.rs
crates/biome_js_formatter/src/utils/member_chain/groups.rs
crates/biome_js_formatter/src/utils/member_chain/mod.rs
crates/biome_js_formatter/tests/specs/js/module/expression/member-chain/multi_line.js
crates/biome_js_formatter/tests/specs/js/module/expression/member-chain/multi_line.js.snap
website/src/content/docs/internals/changelog.mdx

Closes https://github.com/biomejs/biome/issues/1218
When formatting a member chain, the chain is split into several groups, each containing multiple members. However, there is a distinction in the logic of preserving empty lines. Biome preserves empty lines at the member level regardless of whether they are in the same group, whereas Prettier preserves empty lines at the group level, meaning it only preserves empty lines between groups.
Consider the following case:
```js
foo
.bar()
.baz
.qux()
```
Here, there are three groups: `foo`, `bar()`, and `baz.qux()`. Biome preserves the empty lines between `baz` and `qux`:
```js
foo
.bar()
.baz
.qux();
```
On the other hand, Prettier only preserves empty lines between groups:
```js
foo
.bar()
.baz.qux();
```
To address this specific issue, we can …

fix(js_formatter): fix formatting of multi-line member chain

---

website/src/content/docs/reference/configuration.mdx

I found a setting that is not used in the formatter configuration. So, I removed the unused settings from the document.
You can refer to this code. [Link source code](https://github.com/biomejs/biome/blob/main/packages/%40biomejs/backend-jsonrpc/src/workspace.ts)
According to the types defined here, "bracketSameLine" and "bracketSpacing" are not being used.

docs(website): fix formatter configuration to website page

---

packages/@biomejs/backend-jsonrpc/src/index.ts

'RomePath' type was removed because it was not used in the file.

refactor(backend-jsonrpc): remove unused types

---

CONTRIBUTING.md

I was reading the contributing guide and found a slight inconsistency in the link.
Actually, I planned to make a bigger contribution, but I guess I'll start with this one.

chore: change link to discussions on contributing guide

---

website/src/content/docs/pt-br/guides/big-projects.mdx

Correction of a spelling mistake in the Portuguese documentation
To verify the correction, follow these steps:
1. Visit the [Big Projects guide page](https://biomejs.dev/pt-br/guides/big-projects/).
2. Look for the section related to "Usando múltiplos arquivos de configuração".
3. Check for the corrected spelling in the text.
4. Ensure that the corrected word is now spelled correctly and fits contextually.
5. Confirm that the surrounding content and formatting remain unaffected.
6. If applicable, test any links or code snippets in the vicinity of the correction to ensure they still function as intended.
This test plan helps confirm that the spelling correction has been successfully implemented without introducing new issues.

docs: change 'ecnontrar' to 'encontrar' word in pt-br lang

---

crates/biome_cli/tests/snapshots/main_commands_check/apply_bogus_argument.snap
crates/biome_cli/tests/snapshots/main_commands_check/parse_error.snap
crates/biome_cli/tests/snapshots/main_commands_ci/ci_parse_error.snap
crates/biome_service/src/diagnostics.rs

This pull request addresses the issue outlined in [#1698](https://github.com/biomejs/biome/issues/1698#issue-2105338537), aiming to enhance the diagnostic message returned to the user when attempting to format code that contains parsing errors. 
Previously, the message was not very informative or actionable, potentially leaving users confused about why their code formatting failed and how they could resolve the issue.
Changes Made:
Updated the FormatWithErrorsDisabled diagnostic message in [biome/crates/biome_service/src/diagnostics.rs](https://github.com/biomejs/biome/blob/13ec78dc3bc4bded1bca8072f9a55a6756f32cf8/crates/biome_service/src/diagnostics.rs#L391-L393) to clearly explain why the formatting operation was aborted and provide users with guidance on how to enable formatting in the …

Better diagnostics error when a user tries to format code that has parsing diagnostics.

---

.github/workflows/pull_request.yml
.github/workflows/release_cli.yml
.github/workflows/release_js_api.yml

This PR updates node.js version 20 in CI workflows.

ci: update node-version to 20

---

crates/biome_cli/tests/snapshots/main_commands_format/should_apply_different_formatting.snap
crates/biome_cli/tests/snapshots/main_commands_format/should_apply_different_formatting_with_cli.snap
crates/biome_css_formatter/src/css/auxiliary/declaration_with_semicolon.rs
crates/biome_css_formatter/tests/specs/css/color/functional_colors.css.snap
crates/biome_css_formatter/tests/specs/css/nesting/nesting.css
crates/biome_css_formatter/tests/specs/css/nesting/nesting.css.snap
crates/biome_service/src/file_handlers/mod.rs

CSS nesting rules have been added to nesting.css and nesting.css.snap files. 
Minor changes have been made to the declaration_with_semicolon.rs file to handle the semicolon correctly. 
Moreover, `can_format_css_yet()` function has been used to check CSS formatting capabilities.
new snapshots

feat(css_formatter): CSS nesting

---

CHANGELOG.md
crates/biome_cli/src/commands/mod.rs
crates/biome_cli/src/execute/migrate.rs
crates/biome_cli/src/execute/migrate/prettier.rs
crates/biome_cli/src/lib.rs
crates/biome_cli/tests/commands/migrate.rs
crates/biome_cli/tests/snapshots/main_commands_migrate/migrate_help.snap
crates/biome_cli/tests/snapshots/main_commands_migrate/prettier_migrate_write_with_ignore_file.snap
website/src/content/docs/internals/changelog.mdx

This PR create a new command called `biome migrate prettier`, which essentially runs the migration that I wrote so far :)
Question: should we also do a FS traversal and change `// prettier-ignore` to `// biome-ignore`? While useful, it's **not** that easy to do. Replacing the trivia isn't an easy task.
A user could search and replace very quickly.
Updated the current diagnostics.

feat(cli): add prettier migrate sub command

---

packages/@biomejs/js-api/package.json

Currently js-api depends on @biomejs/wasm-X="^10.0.0". This is incorrect, as the latest released version is 1.5.3.
I believe this doesn't need to be tested.

fix js-api wasm peer dep versions

---

CHANGELOG.md
crates/biome_cli/src/execute/process_file/lint.rs
crates/biome_cli/tests/commands/lint.rs
crates/biome_cli/tests/snapshots/main_commands_lint/lint_syntax_rules.snap
crates/biome_lsp/tests/server.rs
crates/biome_service/src/file_handlers/javascript.rs
crates/biome_service/src/file_handlers/json.rs
crates/biome_service/src/file_handlers/mod.rs
crates/biome_service/src/workspace/server.rs
website/src/content/docs/internals/changelog.mdx

Closes https://github.com/biomejs/biome/issues/1245
I moved the generation of the `AnalysisFilter` inside the language itself. This makes more sense now, because - for example - we don't enable import sorting for a language that doesn't implement it.
I added two new test cases: CLI and LSP

fix(lint): pull syntax rules when pulling diagnostics

---

crates/biome_diagnostics_categories/src/categories.rs
crates/biome_js_analyze/src/semantic_analyzers/nursery.rs
crates/biome_js_analyze/src/semantic_analyzers/nursery/no_re_export_all.rs
crates/biome_js_analyze/tests/specs/nursery/noReExportAll/invalid.js
crates/biome_js_analyze/tests/specs/nursery/noReExportAll/invalid.js.snap
crates/biome_js_analyze/tests/specs/nursery/noReExportAll/valid.js
crates/biome_js_analyze/tests/specs/nursery/noReExportAll/valid.js.snap
crates/biome_service/src/configuration/linter/rules.rs
crates/biome_service/tests/invalid/hooks_missing_name.json.snap
packages/@biomejs/backend-jsonrpc/src/workspace.ts
packages/@biomejs/biome/configuration_schema.json
website/src/components/generated/NumberOfRules.astro
website/src/content/docs/linter/rules/index.mdx
website/src/content/docs/linter/rules/no-re-export-all.md

Avoid re-export all
invalid code for this rule
```
export * from 'foo';
export * as foo from 'foo';
```
Part of #1750 (EDIT: this PR doesn't close the issue)
Add a new test case

feat(biome_js_analyze): noReExportAll

---

CHANGELOG.md
crates/biome_js_analyze/src/analyzers/style/no_non_null_assertion.rs
crates/biome_js_analyze/tests/specs/style/noNonNullAssertion/invalid.ts
crates/biome_js_analyze/tests/specs/style/noNonNullAssertion/invalid.ts.snap
website/src/content/docs/internals/changelog.mdx

Closes https://github.com/biomejs/biome/issues/1748
Now we won't create an unsafe fix for the `NoNonNullAssertion` rule for the following case
```ts
x[y.z!]
```
Add a new test case

fix(lint/noNonNullAssertion): dont create an incorrect unsafe fix for `x[y.z!]`

---

Cargo.lock
crates/biome_cli/src/commands/init.rs
crates/biome_cli/src/commands/mod.rs
crates/biome_cli/src/execute/migrate.rs
crates/biome_cli/src/lib.rs
crates/biome_cli/tests/commands/check.rs
crates/biome_cli/tests/commands/ci.rs
crates/biome_cli/tests/commands/format.rs
crates/biome_cli/tests/commands/init.rs
crates/biome_cli/tests/commands/lint.rs
crates/biome_cli/tests/commands/migrate.rs
crates/biome_cli/tests/configs.rs
crates/biome_cli/tests/snap_test.rs
crates/biome_cli/tests/snapshots/main_commands_check/no_lint_if_linter_is_disabled_when_run_apply_biome_jsonc.snap
crates/biome_cli/tests/snapshots/main_commands_ci/ci_does_not_run_formatter_biome_jsonc.snap
crates/biome_cli/tests/snapshots/main_commands_format/applies_configuration_from_biome_jsonc.snap
crates/biome_cli/tests/snapshots/main_commands_init/creates_config_jsonc_file.snap
crates/biome_cli/tests/snapshots/main_commands_init/init_help.snap
crates/biome_cli/tests/snapshots/main_commands_lint/no_lint_if_linter_is_disabled_when_run_apply_biome_jsonc.snap
crates/biome_cli/tests/snapshots/main_commands_migrate/prettier_migrate_jsonc.snap
crates/biome_cli/tests/snapshots/main_commands_migrate/prettier_migrate_write_biome_jsonc.snap
crates/biome_fs/Cargo.toml
crates/biome_fs/src/fs.rs
crates/biome_fs/src/lib.rs
crates/biome_lsp/src/server.rs
crates/biome_service/src/configuration/mod.rs
crates/biome_service/src/file_handlers/json.rs
crates/biome_service/src/workspace/server.rs
website/src/content/docs/guides/how-biome-works.mdx

This PR adds support for `biome.jsonc` file.
Here's the list of detailed changes and assumptions:
- if `biome.json` and `biome.jsonc` are present in the same folder, we prioritise `biome.json`. I preferred not to emit an error to avoid breaking existing projects. Plus, the auto-search function isn't meant to understand conflicts;
- I updated the `auto_search` function, which now uses two loops. It was fun! I got to use labels to break/continue different loops :)
- the command `init` now accepts a `--jsonc` to emit a `biome.jsonc` file
- the command `migrate` now handles the `biome.jsonc` file
I created new test cases for each command, to make sure that Biome can read and apply the configuration from a `biome.jsonc` file. 
Plus, I added new test cases for the `migrate` command and `init` …

feat(project): support `biome.jsonc`

---

crates/biome_cli/src/diagnostics.rs
crates/biome_diagnostics/tests/macros/location_eq.stderr
crates/biome_formatter/src/printer/line_suffixes.rs
crates/biome_js_formatter/src/utils/member_chain/groups.rs
crates/biome_js_formatter/src/utils/member_chain/mod.rs
crates/biome_rowan/src/arc.rs
crates/biome_rowan/src/cursor/node.rs
crates/biome_rowan/src/syntax/node.rs
crates/biome_rowan/src/syntax_node_text.rs
crates/biome_service/src/configuration/diagnostics.rs
crates/biome_service/src/diagnostics.rs
rust-toolchain.toml

Updates Rust to latest version https://blog.rust-lang.org/2024/02/08/Rust-1.76.0.html

chore: upgrade to rust 1.76.0

---

.github/workflows/release_js_api.yml
website/src/assets/svg/copy-icon.svg
website/src/assets/svg/tick-icon.svg
website/src/components/PackageManagerBiomeCommand.astro
website/src/components/PackageManagerCommand.astro
website/src/frontend-scripts/package-manager-commands.ts
website/src/styles/_pre.scss

I have found my self selecting the commands with the mouse and it will be nice to have a button to copy straight away the command.  
Before: 
After:
https://github.com/biomejs/biome/assets/66533853/242d2fdd-8161-40fa-bd17-9dfeeb466abe

docs(website): Add copy button for commands

---

CHANGELOG.md
crates/biome_js_analyze/src/analyzers/nursery/use_await.rs
crates/biome_js_analyze/tests/specs/nursery/useAwait/invalid.js
crates/biome_js_analyze/tests/specs/nursery/useAwait/invalid.js.snap
crates/biome_js_analyze/tests/specs/nursery/useAwait/valid.js
crates/biome_js_analyze/tests/specs/nursery/useAwait/valid.js.snap
website/src/content/docs/internals/changelog.mdx

Closes #1081 
This PR fixes a false-positive in the `useAwait` lint rule. It should ignore `for await...of` in an async function.
Adds a test case for `for await...of` and execute `just test-lintrule useAwait`

fix(lint): `useAwait` ignores `for await...of`

---

crates/biome_js_analyze/src/semantic_analyzers/correctness/use_exhaustive_dependencies.rs
website/src/content/docs/linter/rules/use-exhaustive-dependencies.md

There is currently an invalid linking for the `options` at the `useExhaustiveDependencies` linter rule page. While the side navigation correctly refers to the hash anchor, the occurrence within the text does not so it leads to a `404` page. The adjustment resolves the issue.
To verify the corrected behavior, follow these steps:
1. Visit the `useExhaustiveDependencies` linter rule page (https://biomejs.dev/linter/rules/use-exhaustive-dependencies)
2. Find the `options` link in the descriptions text (shortly before `Examples`)
3. Click on it and see that it navigates to the section further below at the same page

docs: fix `options` link for `useExhaustiveDependencies` linter rule

---

.github/workflows/pull_request_js.yml
CHANGELOG.md
Cargo.lock
Cargo.toml
biome.json
crates/biome_cli/tests/commands/check.rs
crates/biome_cli/tests/commands/lint.rs
crates/biome_diagnostics/Cargo.toml
crates/biome_diagnostics/src/adapters.rs
crates/biome_fs/Cargo.toml
crates/biome_fs/src/fs.rs
crates/biome_fs/src/fs/memory.rs
crates/biome_fs/src/fs/os.rs
crates/biome_service/Cargo.toml
crates/biome_service/src/configuration/diagnostics.rs
crates/biome_service/src/configuration/mod.rs
crates/biome_service/src/diagnostics.rs
crates/biome_service/src/workspace/server.rs
package.json
pnpm-lock.yaml
shared/biome.json
shared/package.json
website/src/content/docs/guides/how-biome-works.mdx
website/src/content/docs/internals/changelog.mdx
website/src/content/docs/reference/configuration.mdx

This PR allows resolving a configuration file from `node_modules`. To do so, we use `oxc_resolver` to resolve the configuration file.
Unfortunately, I couldn't implement a test case using our memory file system. While `oxc_resolver` allows to implement a `FileSytem` trait to implement any possible logic, unfortunately, the `Resolver` wants ownership of type struct that implements `FileSystem`, e.g.:
```rs
struct MemoryFs {};
impl FileSystem for MemoryFs {};
let resolver = ResolverGeneric::with_file_system(options, MemoryFs);
```
This doesn't work well with our infrastructure, where our memory file system must outlive the entire application. 
I updated the documentation to explain how Biome will resolve the files, please read it and let me know if it's clear enough. Please leave any …

feat(project): resolve extends from `node_modules`

---

website/src/styles/_pre.scss

- Refactored the `_pre.scss` file with pure scss syntax there are lot of pure css repetitive syntax available so I just improved it. 
- Made the copy button sticky to its container so no need to scroll to get to the copy button in mobile view. below's the ref gif:

Refactored `_pre.scss` and made the copy command button sticky within its container.

---

.github/workflows/ja-translation.yaml
.github/workflows/pull_request.yml
.github/workflows/pull_request_js.yml
.github/workflows/release_cli.yml
.github/workflows/release_js_api.yml
.github/workflows/runtime.yml

Some GitHub actions are outdated, and the name that we use to install wasm-pack is dead. I used the following suggestion https://rustwasm.github.io/docs/wasm-bindgen/wasm-bindgen-test/continuous-integration.html#github-actions 
CI should pass

ci: update oudated actions

---

CHANGELOG.md
crates/biome_diagnostics/src/display.rs
website/src/content/docs/internals/changelog.mdx

Another QoL improvement. Now the files printed in a diagnostic are clickable. If biome is run from a terminal that is integrated in the IDE, the IDE will open that file in the specified row:column
The current tests should stay as is. I tested locally and it works like a charm: RustRover and VSCode
Unfortunately VSCode terminal isn't that good at underling the file, but if you hover it with the cursor, it get underlined. 
RustRover instead underlines it regardless.

feat(cli): make file in diagnostic clickable

---

CHANGELOG.md
crates/biome_js_analyze/src/analyzers/suspicious/no_confusing_void_type.rs
crates/biome_js_analyze/tests/specs/suspicious/noConfusingVoidType/valid.ts
crates/biome_js_analyze/tests/specs/suspicious/noConfusingVoidType/valid.ts.snap
website/src/content/docs/internals/changelog.mdx

- Closes https://github.com/biomejs/biome/issues/1812
Added a new test case and other existing tests should pass.

fix(lint/noConfusingVoidType): accept `void` as the extends type in conditional types

---

CHANGELOG.md
crates/biome_analyze/src/rule.rs
crates/biome_diagnostics_categories/src/categories.rs
crates/biome_js_analyze/src/analyzers/nursery.rs
crates/biome_js_analyze/src/analyzers/nursery/no_namespace_import.rs
crates/biome_js_analyze/tests/specs/nursery/noNamespaceImport/invalid.js
crates/biome_js_analyze/tests/specs/nursery/noNamespaceImport/invalid.js.snap
crates/biome_js_analyze/tests/specs/nursery/noNamespaceImport/valid.ts
crates/biome_js_analyze/tests/specs/nursery/noNamespaceImport/valid.ts.snap
crates/biome_service/src/configuration/linter/rules.rs
packages/@biomejs/backend-jsonrpc/src/workspace.ts
packages/@biomejs/biome/configuration_schema.json
website/src/components/generated/NumberOfRules.astro
website/src/content/docs/internals/changelog.mdx
website/src/content/docs/linter/rules/index.mdx
website/src/content/docs/linter/rules/no-namespace-import.md

A part of #1750
This PR adds `noNamespaceImport` lint rule for barrel files.
- Implemented Rule Logic (type only imports are accepted, which are differences from the original)
- Added the [eslint-plugin-barrel-files](https://github.com/thepassle/eslint-plugin-barrel-files) to RuleSource
`just test-lintrule no_namespace_import`

feat(lint/noNamespaceImport): add rule

---

CHANGELOG.md
crates/biome_cli/src/execute/process_file/format.rs
crates/biome_cli/tests/commands/format.rs
crates/biome_cli/tests/snapshots/main_commands_format/format_empty_svelte_js_files_write.snap
crates/biome_cli/tests/snapshots/main_commands_format/format_empty_svelte_ts_files_write.snap
crates/biome_cli/tests/snapshots/main_commands_format/format_svelte_explicit_js_files.snap
crates/biome_cli/tests/snapshots/main_commands_format/format_svelte_explicit_js_files_write.snap
crates/biome_cli/tests/snapshots/main_commands_format/format_svelte_implicit_js_files.snap
crates/biome_cli/tests/snapshots/main_commands_format/format_svelte_implicit_js_files_write.snap
crates/biome_cli/tests/snapshots/main_commands_format/format_svelte_ts_files.snap
crates/biome_cli/tests/snapshots/main_commands_format/format_svelte_ts_files_write.snap
crates/biome_service/src/file_handlers/astro.rs
crates/biome_service/src/file_handlers/javascript.rs
crates/biome_service/src/file_handlers/mod.rs
crates/biome_service/src/file_handlers/svelte.rs
packages/@biomejs/backend-jsonrpc/src/workspace.ts
website/src/content/docs/internals/changelog.mdx

This PR adds formatting for the JS/TS code inside a `.svelte` file
Part of #1719 
Thank you @nhedger, for paving all the work for Vue; all I did was just copying what you did :)
Added new tests.

feat(formatter): partial formatting for `svelte` files

---

crates/biome_js_analyze/src/analyzers/nursery/use_import_restrictions.rs
website/src/content/docs/linter/rules/use-import-restrictions.md

On use-import-restrictions page, a link of eslint-plugin-import-access is not given a display name as below image, so I provided name 'eslint-plugin-import-access'.
before
after
Please see Netlify website preview.

fix(website): show eslint-plugin-import-access link name

---

crates/biome_cli/src/cli_options.rs
crates/biome_cli/tests/snapshots/main_commands_check/check_help.snap
crates/biome_cli/tests/snapshots/main_commands_ci/ci_help.snap
crates/biome_cli/tests/snapshots/main_commands_format/format_help.snap
crates/biome_cli/tests/snapshots/main_commands_lint/lint_help.snap
crates/biome_cli/tests/snapshots/main_commands_migrate/migrate_help.snap
crates/biome_cli/tests/snapshots/main_commands_rage/rage_help.snap

`--config-path` disables the default configuration file resolution, but this is not documented.
I tried to make the explanation of this CLI option short and explanatory.
Refers to #1101 but it doesn't close it until I make the next PR for the corresponding website documentation, after this PR is merged 👍 
All unit tests pass 👍

docs: improve documentation of `--config-path`

---

website/src/content/docs/index.mdx
website/src/content/docs/pt-br/index.mdx
website/src/playground/components/Progress.tsx

This PR improves a progress bar that shows formatter performance on the landing page.
- The progress reaches the right end upon completion
- Change the colors

feat(website): improve formatter performance progress bar

---

crates/biome_deserialize_macros/src/deserializable_derive.rs
crates/biome_deserialize_macros/src/deserializable_derive/enum_variant_attrs.rs
crates/biome_deserialize_macros/src/deserializable_derive/struct_attrs.rs
crates/biome_deserialize_macros/src/deserializable_derive/struct_field_attrs.rs
crates/biome_deserialize_macros/src/lib.rs
crates/biome_deserialize_macros/src/partial_derive.rs
crates/biome_deserialize_macros/src/partial_derive/attrs.rs
crates/biome_deserialize_macros/src/util.rs

While investigating how to implement #1846, I took some time to learn more about derive macro and attribute parsing.
It is hard to find good examples and guides for implementing derive macros. Digging into the internals of the relevant crates, I discovered some types that can help to parse macro attributes (Meta, MetaList, ...).
I refactored the code that parses our derived macro attribute to use these types.
The implementation should be more robust and more helpful in case of an error.
`just test`

refactor(deserializable_macros): idiomatic attribute parsing

---

website/src/styles/playground/_results.scss

In this [playground link](https://biomejs.dev/playground/?code=dAByAHkAIAB7AAoAIAAgAHUAbgBkAGUAZgBpAG4AZQBkADsACgAgACAAdAByAHkAIAB7AAoAIAAgACAAIAB3AGgAaQBsAGUAIAAoAHQAcgB1AGUAKQAgAHsACgAgACAAIAAgACAAIABpAGYAIAAoAEQAYQB0AGUALgBuAG8AdwAoACkAIAA%2BACAAMAApACAAewAKACAAIAAgACAAIAAgACAAIAB1AG4AZABlAGYAaQBuAGUAZAA7AAoAIAAgACAAIAAgACAAIAAgAGIAcgBlAGEAawA7AAoAIAAgACAAIAAgACAAfQAKACAAIAAgACAAfQAKACAAIAB9ACAAZgBpAG4AYQBsAGwAeQAgAHsACgAgACAAIAAgAGkAZgAgACgARABhAHQAZQAuAG4AbwB3ACgAKQAgAD4AIAAwACkAIAB1AG4AZABlAGYAaQBuAGUAZAA7AAoAIAAgAH0ACgAgACAAaQBmACAAKABEAGEAdABlAC4AbgBvAHcAKAApACAAPgAgADAAKQAgAHUAbgBkAGUAZgBpAG4AZQBkADsACgB9ACAAYwBhAHQAYwBoACAAewAKACAAIAB1AG4AZABlAGYAaQBuAGUAZAA7AAoAfQAKAAoA), only a partial control flow graph can be viewed.
After fix: …

fix(website): make playground's control flow graph scrollable

---

crates/biome_js_analyze/src/analyzers/nursery/no_focused_tests.rs
crates/biome_js_analyze/tests/specs/nursery/noFocusedTests/invalid.js.snap
crates/biome_js_analyze/tests/specs/nursery/noFocusedTests/valid.js
crates/biome_js_analyze/tests/specs/nursery/noFocusedTests/valid.js.snap

The rule now reports `fdescribe` and `fit`.
https://github.com/biomejs/biome/blob/c53f6d164f86297f04eaf721a48b71bc3a883320/crates/biome_js_analyze/tests/specs/nursery/noFocusedTests/invalid.js#L4-L5
I updated the existing tests.

refactor(lint/noFocusedTests): report `fdescribe` and `fit`

---

crates/biome_cli/src/execute/process_file.rs
crates/biome_cli/src/execute/process_file/lint.rs
crates/biome_cli/src/execute/traverse.rs
crates/biome_lsp/src/session.rs
crates/biome_service/src/file_handlers/javascript.rs
crates/biome_service/src/file_handlers/json.rs
crates/biome_service/src/file_handlers/mod.rs
crates/biome_service/src/workspace.rs
crates/biome_service/src/workspace/server.rs
packages/@biomejs/js-api/package.json
packages/@biomejs/js-api/tests/__snapshots__/formatContent.test.ts.snap
packages/@biomejs/js-api/tests/__snapshots__/lintContent.test.ts.snap
packages/@biomejs/js-api/tests/__snapshots__/printDiagnostics.test.ts.snap
packages/@biomejs/js-api/tests/formatContent.test.ts
pnpm-lock.yaml

This PR reduces the memory footprint of `DiagnosticPrinter` and the maximum size of the diagnostics that are sent among threads.
This PR reduces the maximum number from `u64` to `u32`. The maximum of `u32` is `4294967295`. I'd say it's safe to say that a project will never reach a higher number in diagnositcs.
CI should pass

perf(cli): reduce memory footprint of diagnostic printer

---

crates/biome_js_analyze/src/analyzers/nursery/no_focused_tests.rs
crates/biome_js_analyze/tests/specs/nursery/noFocusedTests/invalid.js.snap
website/src/content/docs/linter/rules/index.mdx
website/src/content/docs/linter/rules/no-focused-tests.md

Fix all current invalid snapshots.

refactor: `noFocusedTests` code fix

---

website/src/pages/feed.xml.js

The RSS feed stopped working when we updated Astro and its dependencies, now that Endpoints expect a `GET` function instead of the former, `get`. This PR solves this by renaming the function.
You can see currently that https://biomejs.dev/feed.xml will go to a 404 page, locally (or in the deploy preview), if you go to `/feed.xml` you should now see the RSS feed being returned.

fix(website): generate RSS feed again

---

crates/biome_service/src/configuration/overrides.rs
crates/biome_service/src/file_handlers/json.rs
crates/biome_service/src/matcher/mod.rs
crates/biome_service/src/settings.rs

Closes #1795 
There's a small issue here, unfortunately. The analyzer rules can't be cached at the moment because `RuleOptions` are typed using `Any`, which can't be moved among threads.
We will have to come up with a different strategy to cache them.
The current CI should pass

perf: cache computed overrides

---

crates/biome_service/src/file_handlers/astro.rs
crates/biome_service/src/file_handlers/javascript.rs
crates/biome_service/src/file_handlers/svelte.rs
crates/biome_service/src/file_handlers/vue.rs

This PR adds `format_range` and `format_on_type` support for Vue, Astro and Svelte files. I followed the instructions here: https://github.com/biomejs/biome/issues/1719#issuecomment-1959219699

feat(service): implement format_range and format_on_type for vue, astro and svelte files

---

CHANGELOG.md
crates/biome_js_analyze/src/analyzers/nursery/use_filenaming_convention.rs
crates/biome_js_analyze/src/semantic_analyzers/style/use_naming_convention.rs
crates/biome_js_analyze/tests/specs/nursery/useFilenamingConvention/invalid-non-ascii-café.options.json
crates/biome_js_analyze/tests/specs/style/useNamingConvention/invalidNonAscii.options.json
website/src/content/docs/internals/changelog.md
website/src/content/docs/linter/rules/use-filenaming-convention.md
website/src/content/docs/linter/rules/use-naming-convention.md

I recently added a new option to the naming convention rules: `requireAscii`. Enabling it by default is a good thing, but this is a breaking change. According to our [versioning philosophy](https://biomejs.dev/internals/versioning/), we should release a major release. This seems overkill for such a small change.
So I have decided to disable this option by default and postpone the change to a future major release. I will create an issue to track this.
All tests passed.

refactor(lint/namimg-convention): turn off `requireAscii` to avoid breaking changes

---

crates/biome_cli/src/execute/migrate/prettier.rs
crates/biome_cli/tests/snapshots/main_configuration/incorrect_rule_name.snap
crates/biome_deserialize/src/diagnostics.rs
crates/biome_deserialize_macros/src/deserializable_derive.rs
crates/biome_deserialize_macros/src/deserializable_derive/container_attrs.rs
crates/biome_deserialize_macros/src/lib.rs
crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/malformedOptions.js.snap
crates/biome_service/src/configuration/linter/rules.rs
crates/biome_service/tests/invalid/files_extraneous_field.json.snap
crates/biome_service/tests/invalid/formatter_extraneous_field.json.snap
crates/biome_service/tests/invalid/formatter_quote_style.json.snap
crates/biome_service/tests/invalid/hooks_incorrect_options.json.snap
crates/biome_service/tests/invalid/naming_convention_incorrect_options.json.snap
crates/biome_service/tests/invalid/overrides/incorrect_key.json.snap
crates/biome_service/tests/invalid/top_level_extraneous_field.json.snap
packages/@biomejs/biome/configuration_schema.json
xtask/codegen/src/generate_configuration.rs

Fix #1901
Partially fix #1898
This PR adds the `allow_unknown_fields` struct attribute.
I updated the snapshots

feat(deserializable): add `unknown_fields` struct attribute

---

CHANGELOG.md
crates/biome_js_analyze/tests/specs/correctness/organizeImports/issue-1924.js
crates/biome_js_analyze/tests/specs/correctness/organizeImports/issue-1924.js.snap
crates/biome_js_analyze/tests/specs/correctness/organizeImports/namedSpecifiers.js
crates/biome_js_analyze/tests/specs/correctness/organizeImports/namedSpecifiers.js.snap
crates/biome_js_syntax/src/import_ext.rs
website/src/content/docs/internals/changelog.md

- Closes https://github.com/biomejs/biome/issues/1924
For the following case
```js
import { a1 as a3, a2 } from 'a'
```
We used to use `a1` and `a2` for sorting. The reported bug occurs when `a1` is the same as `a2`. Now we use `a3` and `a2` for sorting.
This fix may alter the original behavior. The above code snippet was formatted as `import { a1 as a3, a2 } from 'a'` before, but now it's formatted as `import { a2, a1 as a3 } from 'a'`.
`Eslint` uses `a3` and `a2` for sorting: [link](https://eslint.org/play/#eyJ0ZXh0IjoiLyplc2xpbnQgc29ydC1pbXBvcnRzOiBcImVycm9yXCIqL1xuaW1wb3J0IHttMiwgbTEgYXMgbTN9IGZyb20gJ20nOyIsIm9wdGlvbnMiOnsiZW52Ijp7fSwicnVsZXMiOnt9LCJwYXJzZXJPcHRpb25zIjp7ImVjbWFGZWF0dXJlcyI6e30sImVjbWFWZXJzaW9uIjoibGF0ZXN0Iiwic291cmNlVHlwZSI6Im1vZHVsZSJ9fX0=)
Add new test cases

fix(lint/origanizeImports): use the correct export name to sort in the import clause

---

website/src/content/docs/ja/reference/vscode.mdx
website/src/content/docs/pt-br/reference/vscode.mdx
website/src/content/docs/reference/vscode.mdx
website/src/content/docs/zh-cn/reference/vscode.mdx

This PR removes the outdated requireConfiguration option from the VS Code extension's documentation.
Fix https://github.com/biomejs/biome/issues/1943

docs: remove outdated `requireConfiguration` docs

---

packages/tailwindcss-config-analyzer/src/generate-tailwind-preset.ts

Changes `import.meta.dir` to
```ts
import path from "node:path";
import { fileURLToPath } from "node:url";
path.dirname(fileURLToPath(import.meta.url))
```
In case we want to switch in the future from Bun to something like `tsx` or `ts-node` (which are Node.js based and do not support Bun APIs) to run the internal codegen script for tailwind class sorting.
Run `just gen-tw`.

Address dirname suggestion in internal codegen script

---

website/src/content/docs/guides/big-projects.mdx
website/src/content/docs/ja/guides/big-projects.mdx

Fix indentation in big projects  code example, https://biomejs.dev/guides/big-projects/
View big-projects on website and check `app/backend/biome.json`.

docs: Fix indentation on code example

---

CHANGELOG.md
crates/biome_js_analyze/src/analyzers/complexity/no_useless_constructor.rs
crates/biome_js_analyze/tests/specs/complexity/noUselessConstructor/valid.ts
crates/biome_js_analyze/tests/specs/complexity/noUselessConstructor/valid.ts.snap
website/src/content/docs/internals/changelog.md
website/src/content/docs/linter/rules/no-useless-constructor.md

close #1945 
added test cases and snapshots

fix(analyzer): allow constructor with default parameters in noUselessConstructor

---

CHANGELOG.md
crates/biome_js_formatter/src/js/bindings/formal_parameter.rs
crates/biome_js_formatter/src/js/bindings/parameters.rs
crates/biome_js_formatter/src/utils/object_pattern_like.rs
crates/biome_js_formatter/tests/quick_test.rs
crates/biome_js_formatter/tests/specs/ts/arrow/long_arrow_parentheses_with_line_break.ts
crates/biome_js_formatter/tests/specs/ts/arrow/long_arrow_parentheses_with_line_break.ts.snap
website/src/content/docs/internals/changelog.md

fix(js_formatter): fix invalid formatting of long arrow function for AsNeeded arrow parens

---

packages/@biomejs/biome/README.ja.md
packages/@biomejs/biome/README.md
packages/@biomejs/biome/README.pt-br.md
packages/@biomejs/biome/README.zh-CN.md
website/src/content/docs/index.mdx
website/src/content/docs/ja/index.mdx
website/src/content/docs/pt-br/index.mdx
website/src/content/docs/zh-cn/index.mdx

This PR replaces `TypeScript ESLint` with `typescript-eslint`
https://typescript-eslint.io/maintenance/branding
> Our project name is "typescript-eslint". We sometimes refer to it as "ts-eslint" for short.
> "typescript-eslint" is preferred over "TypeScript ESLint" or "TypeScript-ESLint" because ESLint and TypeScript are written in abbreviated Pascal Case. Combining lowercase with a dash helps differentiate us.

chore: replace TypeScript ESLint with typescript-eslint

---

CHANGELOG.md
crates/biome_js_analyze/src/react/hooks.rs
crates/biome_js_analyze/src/semantic_analyzers/correctness/use_exhaustive_dependencies.rs
crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/issue1931.js
crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/issue1931.js.snap
crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/issue1931.js.snap.new
crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/issue1931.options.json
website/src/content/docs/internals/changelog.md
website/src/content/docs/linter/rules/use-exhaustive-dependencies.md

React hooks are only validated by `useExhaustiveDependencies` if they are being imported from the React library. Sometimes, this is undesirable, for instance when a library re-exports the React hooks. This change allows users to configure built-in hooks as if they were user-provided hooks to get the desired result.
Fixes #1931. 

fix(lint/useExhaustiveDependencies): lint React hooks from other sources

---

.github/workflows/release_cli.yml

Build for linux-arm64 with a page size of 16K, to fix following error:
```
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
memory allocation of 5 bytes failed
```
Related issue:
* #1692 
Run the build binary on an linux-arm64 with 16K page size.

feat(ci): build linux-arm64 with 16K page size

---

crates/biome_js_analyze/src/analyzers/nursery/no_focused_tests.rs

This is a very small fix. 
I was reading the source code of [noFocusedTests](https://github.com/biomejs/biome/blob/main/crates/biome_js_analyze/src/analyzers/nursery/no_focused_tests.rs#L98) and noticed that there seems to be an unnecessary commented out section.

chore: remove unnecessary comment

---

CHANGELOG.md
crates/biome_analyze/src/context.rs
crates/biome_analyze/src/options.rs
crates/biome_analyze/src/registry.rs
crates/biome_analyze/src/signals.rs
crates/biome_formatter/src/lib.rs
crates/biome_js_analyze/src/analyzers/complexity/use_literal_keys.rs
crates/biome_js_analyze/src/analyzers/correctness/no_string_case_mismatch.rs
crates/biome_js_analyze/src/analyzers/style/no_unused_template_literal.rs
crates/biome_js_analyze/src/analyzers/style/use_enum_initializers.rs
crates/biome_js_analyze/src/analyzers/suspicious/use_valid_typeof.rs
crates/biome_js_analyze/src/semantic_analyzers/nursery/use_sorted_classes.rs
crates/biome_js_analyze/tests/specs/style/useEnumInitializers/invalid2.options.json
crates/biome_js_analyze/tests/specs/style/useEnumInitializers/invalid2.ts
crates/biome_js_analyze/tests/specs/style/useEnumInitializers/invalid2.ts.snap
crates/biome_js_factory/src/make.rs
crates/biome_service/src/file_handlers/javascript.rs
crates/biome_service/src/file_handlers/json.rs
crates/biome_test_utils/src/lib.rs
website/src/content/docs/internals/changelog.md

Closes https://github.com/biomejs/biome/issues/1102
Closes https://github.com/biomejs/biome/issues/1903
This PR adds a `preferred_quote` to the analyzer. It is currently used only inside the JavaScript analyzer.
This quote is then computed using the configuration, provide `PreferredQuote::Single` when the formatter is set to use the single quote inside the formatter.
I updated the test suite to compute this new configuration, and added a new test case in one of the rules that use this new logic.

feat(analyzer): infer quote from formatter

---

crates/biome_service/src/workspace/server.rs

To fix the deadlock, I created two functions get/set to manage the `IndexSet<DocumentFileSource>` list. By doing so, we reduce the "window" of when the lock is actually owned by a thread. In the function `get_parse`, we were actually trying to lock the same resource multiple times without releasing them.
By using two small functions, the lock is released when the scope of the function ends, making it safer.
I run our internal `pnpm check` multiple time and now there's not deadlock

fix: concurrency deadlock

---

CHANGELOG.md
crates/biome_js_analyze/src/analyzers/nursery/no_undeclared_dependencies.rs
crates/biome_js_analyze/tests/specs/nursery/noUndeclaredDependencies/valid.js
crates/biome_js_analyze/tests/specs/nursery/noUndeclaredDependencies/valid.js.snap
website/src/content/docs/internals/changelog.md
website/src/content/docs/linter/rules/no-undeclared-dependencies.md

`noUndeclaredDependencies` currently reports runtime dependencies such as `node:assert` or `bun:test`.
With this PR, `noUndeclaredDependencies` ignores all dependencies that use a protocol.

refactor(noUndeclaredDependencies): ignore imports with a protocol

---

CHANGELOG.md
crates/biome_deserialize/src/validator.rs
crates/biome_deserialize_macros/src/deserializable_derive.rs
crates/biome_deserialize_macros/src/lib.rs
crates/biome_js_analyze/src/lib.rs
crates/biome_js_analyze/src/react/hooks.rs
crates/biome_js_analyze/src/semantic_analyzers/correctness/use_exhaustive_dependencies.rs
crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/invalidIndices.js.snap
crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/invalidIndices.options.json
crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/issue1931.js
crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/issue1931.js.snap
crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/stableResult.js
crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/stableResult.js.snap
crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/stableResult.options.json
crates/biome_service/src/configuration/linter/rules.rs
crates/biome_service/src/configuration/vcs.rs
packages/@biomejs/backend-jsonrpc/src/workspace.ts
packages/@biomejs/biome/configuration_schema.json
website/src/content/docs/internals/changelog.md
website/src/content/docs/linter/rules/use-exhaustive-dependencies.md
xtask/codegen/src/generate_configuration.rs

User-provided React hooks can now be configured to return stable results.
Implements #1128.
I went for a slightly different configuration syntax than suggested in #1128 to avoid repetition of hooks that have both stable results and a dependencies array to be validated.
Added and updated test cases.

Implement stable hook configuration

---

CHANGELOG.md
crates/biome_service/src/file_handlers/mod.rs
crates/biome_service/tests/workspace.rs
website/src/content/docs/internals/changelog.md

Closes https://github.com/biomejs/biome/issues/1981
It seems the playground treats typescript definition files as normal typescript files before
Add a new test case

fix(playground): recognize typescript definition files by their file path

---

crates/biome_cli/src/commands/mod.rs
crates/biome_cli/src/lib.rs

This PR introduces a bogus `--stdio` argument for the `lsp-proxy` command.
According to the [Implementation Considerations](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#implementationConsiderations) section of the LSP specification, it is recommended that language servers support the `--stdio` argument if the server communicates over stdio.
The absence of this argument actually makes it harder to spawn Biome's LSP when using `vscode-languageclient`, because it appends an `--stdio` argument to the command, and since the `lsp-proxy` command does not support it, the binary exits with an error.
By introducing this bogus (and hidden) argument, we make it easier to interface with Biome's LSP.
Try spawning Biome's LSP using vscode-languageclient: …

feat(cli): add `--stdio` argument to `lsp-proxy` command

---

crates/biome_js_analyze/src/analyzers/style/use_shorthand_function_type.rs
crates/biome_js_analyze/tests/specs/style/useShorthandFunctionType/invalid.ts
crates/biome_js_analyze/tests/specs/style/useShorthandFunctionType/invalid.ts.snap

Preserve type parameters of generic interfaces when applying fixes.
Fixes #2015.
Add an invalid case where a generic interface has a single call signature, and the fix action preserves the type parameters of the generic interface.

fix(`useShorthandFunctionType`): generic interface type parameters

---

crates/biome_js_analyze/src/analyzers/correctness/no_unreachable.rs
crates/biome_js_formatter/src/js/expressions/call_arguments.rs
crates/biome_js_formatter/src/utils/assignment_like.rs
crates/biome_js_formatter/src/utils/binary_like_expression.rs
crates/biome_parser/src/parse_lists.rs

chore: remove repetitive words

---

crates/biome_js_analyze/src/analyzers/complexity/no_for_each.rs
website/src/content/docs/linter/rules/no-for-each.md

docs: add description of exception for index usage

---

crates/biome_cli/tests/commands/rage.rs
crates/biome_cli/tests/snapshots/main_commands_rage/with_jsonc_configuration.snap
crates/biome_fs/src/fs.rs

I refactored the `auto_search` function in `crates/biome_fs/src/fs.rs` a bit. It was trying to search in parent directories first and then alternatives (`biome.jsonc`). This approach led to an issue where the mutable `file_path` variable was erroneously set to the root path `/` upon searching for the next alternative, thereby causing an incorrect `file_directory_path`.
I switched the loops so it will search alternatives first and then traverse up to parent directories. Additionally, I have made adjustments to error handling to align with this new search logic. However, I am uncertain if this modification aligns with the expected behavior and would greatly appreciate confirmation.
Fixes #2008.
I tested it locally by running `cargo build -p biome_cli` first and tested that binary in another …

fix(auto_search): `biome.jsonc` resolution

---

CHANGELOG.md
crates/biome_js_analyze/src/analyzers/nursery/no_undeclared_dependencies.rs
crates/biome_js_analyze/tests/specs/nursery/noUndeclaredDependencies/valid.js
crates/biome_js_analyze/tests/specs/nursery/noUndeclaredDependencies/valid.js.snap
crates/biome_js_analyze/tests/specs/nursery/noUndeclaredDependencies/valid.package.json
website/src/content/docs/internals/changelog.md

Support imports of subpath exports in lint rule `noUndeclaredDependencies`.
It seems the support of import path aliases in `package.json` (also known as [subpath imports](https://nodejs.org/api/packages.html#subpath-imports)) or `tsconfig.json` needs further discussion so they're not implemented in this PR.
Now that we are using `oxc_resolver` for biome configurations, I think a better approach is to also use it for this rule. It can correctly handle subpath exports, subpath imports and tsconfig path aliases for us.
Related: #2012.
Two valid cases of imports of subpath exports are added to the test snapshot.

fix(noUndeclaredDependencies): support imports of subpath exports

---

Cargo.lock
crates/biome_cli/Cargo.toml
crates/biome_css_analyze/Cargo.toml
crates/biome_deserialize/Cargo.toml
crates/biome_fs/Cargo.toml
crates/biome_js_analyze/Cargo.toml
crates/biome_js_formatter/Cargo.toml
crates/biome_js_parser/Cargo.toml
crates/biome_js_transform/Cargo.toml
crates/biome_lsp/Cargo.toml
crates/biome_test_utils/Cargo.toml
fuzz/Cargo.toml
xtask/bench/Cargo.toml
xtask/codegen/Cargo.toml
xtask/contributors/Cargo.toml
xtask/lintdoc/Cargo.toml

I used [cargo-machette](https://github.com/bnjbvr/cargo-machete) to detect unused dependencies.
Unfortunately we cannot use this on CI because there are false positives.

chore: remove unused deps

---

website/src/styles/playground/_results.scss
website/src/styles/playground/_tabs.scss

This is a follow-up fix of https://github.com/biomejs/biome/pull/1855#issuecomment-1951023066. The result tab panel is no longer chopped off.
Visually confirm the result tab panel can show all of its content.
Code for quick testing:
```js
try {
undefined;
try {
while (true) {
if (Date.now() > 0) {
undefined;
break;
}
}
} finally {
if (Date.now() > 0) undefined;
}
if (Date.now() > 0) undefined;
} catch {
undefined;
}
```

fix(website): result tab panel height

---

website/src/content/docs/ja/guides/getting-started.mdx

Awesome work y'all on getting translations going for this awesome project :)
I noticed that the links in "Getting Started" on the Japanese page were pointing to the English ones.
Maybe other languages can also be updated by others as well.
Verified manually that all links on JA "Getting Started" lead to their JA pages.

docs: Update links in JA Getting Started to refer to JA pages

---

crates/biome_cli/tests/snap_test.rs

Take time in seconds into account. It starts to be annoying so I want to change it. I hope this won't introduce any false positives.
Shouldn't change existing snapshots.

fix(tests_infra): `TIME_REGEX` for snapshot redaction

---

crates/biome_js_analyze/src/semantic_analyzers/nursery/use_jsx_key_in_iterable.rs
crates/biome_js_analyze/tests/specs/nursery/useJsxKeyInIterable/invalid.jsx
crates/biome_js_analyze/tests/specs/nursery/useJsxKeyInIterable/invalid.jsx.snap
crates/biome_js_analyze/tests/specs/nursery/useJsxKeyInIterable/valid.jsx
crates/biome_js_analyze/tests/specs/nursery/useJsxKeyInIterable/valid.jsx.snap

This is a follow-up of #2016 to handle all parenthesized expressions.
See https://github.com/biomejs/biome/issues/2011#issuecomment-1993783800
New test cases are added and should pass.

fix(`useJsxKeyInIterable`): unwrap parenthesized expressions

---

CHANGELOG.md
crates/biome_cli/tests/commands/lint.rs
crates/biome_cli/tests/snapshots/main_commands_lint/top_level_all_down_level_empty.snap
crates/biome_service/src/configuration/linter/rules.rs
website/src/content/docs/internals/changelog.md
xtask/codegen/src/generate_configuration.rs

It turns out the existing function `as_enabled_rules` was calculating the enabled rules in a wrong way. The function is generated by codegen, so I fixed the logic in `xtask/codegen/src/generate_configuration.rs` and regenerated that file. I summarize the correct logic as follows:
- Group-level `all` and group-level `recommend` should take precedence over their top-level alternatives.
- When group-level `all` or group-level `recommend` is not present, it should fallback to check top-level `all` or top-level `recommend`.
- If the whole group-level config is not present, it should check top-level `all` or top-level `recommend`.
- Group-level `all` and group-level `recommend` should take precedence over top-level alternatives. (same as non-nursery groups)
- When group-level `all` or …

fix(configuration): enabled rules calculation

---

packages/@biomejs/biome/package.json

Ever since JSON formatting was introduced, the `JSON` keyword was spaced with tabs instead of spaces for some reason, unlike every other line in `package.json`. The CLI should probably have caught this when formatting, idk why it never did. Should have probably done this in my previous PR ¯\\\_(ツ)\_\/¯

chore: fix `@biomejs/biome` inconsistency in `package.json`

---

website/src/components/PackageManagerBiomeCommand.astro

Both Yarn and PNPM shouldn't use `dlx` to execute Biome, since it bypasses the installed version. Instead, they can directly call the installed binary through a more convenient command.
Note that `npx` (and I assume `bunx`) can also use the binary name instead of the package name *if the package is installed*, but it's somewhat unsafe for them to use the binary name because it gets interpreted as a different package if Biome is not installed.
Addresses #1986.
None needed.

Update usage commands for Yarn and PNPM

---

CHANGELOG.md
crates/biome_js_analyze/src/syntax/correctness/no_super_without_extends.rs
crates/biome_js_analyze/tests/specs/correctness/noSuperWithoutExtends/valid.js
crates/biome_js_analyze/tests/specs/correctness/noSuperWithoutExtends/valid.js.snap
website/src/content/docs/internals/changelog.md

This rule should also check the extends clause of a class expression.
Fixes #2108.
I added a valid test case:
```ts
class A {}
class B {
a = class extends A {
constructor(_) {
super();
}
};
}
```

fix(noSuperWithoutExtends): detect class expressions

---

CHANGELOG.md
crates/biome_cli/tests/cases/cts_files.rs
crates/biome_cli/tests/cases/mod.rs
crates/biome_cli/tests/snapshots/main_cases_cts_files/should_allow_using_export_statements.snap
crates/biome_js_analyze/tests/spec_tests.rs
crates/biome_js_syntax/src/file_source.rs
crates/biome_service/src/file_handlers/mod.rs
website/src/content/docs/internals/changelog.md

Fix discrepancies on file source detection. Allow module syntax in `.cts` files.
Fixes #2114.
Added a test case to show that the following statement can be used in a `.cts` file:
```ts
export default { cjs: true };
```

fix: discrepancies on file source detection

---

GOVERNANCE.md

The previous sentence already mentions a core contributor or lead can reach out, but the next sentence mentions lead only. It looks like an oversight, so I'm tweaking the wording to what I think is appropriate.

Update wording in GOVERNANCE.md

---

.github/renovate.json

This PR adds [renovate](https://docs.renovatebot.com/) to the repository. It adds four groups to monitor:
- github actions
- rust crates
- website
- npm packages
For Rust crates, `syn` and `quote` are ignored for now.
It will open PRs every Monday at 9AM GMT and it will tag the teams @biomejs/core-contributors  and @biomejs/maintainers 
Merge it. It will create a new issue with the label "Dashboard". That issue can't be closed.

ci: add renovate to monitor dependencies

---

CHANGELOG.md
crates/biome_js_analyze/src/analyzers/nursery/no_undeclared_dependencies.rs
crates/biome_js_analyze/src/manifest_services.rs
crates/biome_js_analyze/tests/specs/nursery/noUndeclaredDependencies/valid.d.ts
crates/biome_js_analyze/tests/specs/nursery/noUndeclaredDependencies/valid.d.ts.snap
crates/biome_js_analyze/tests/specs/nursery/noUndeclaredDependencies/valid.js
crates/biome_js_analyze/tests/specs/nursery/noUndeclaredDependencies/valid.js.snap
crates/biome_js_analyze/tests/specs/nursery/noUndeclaredDependencies/valid.package.json
crates/biome_project/src/node_js_project/package_json.rs
website/src/content/docs/internals/changelog.md

This PR fixes some false positives reported by the rule `noUndeclaredDependencies`.
- The rule should validate `peerDependencies` and `optionalDependencies` in `package.json`. Fixes #2122.
- The rule shouldn't report module specifiers in TS external module declaration. Fixes #2123.
New valid test cases are added.

fix(noUndeclaredDependencies): false positives

---

CONTRIBUTING.md

Linking to the crate page isn't smart because we don't release them very often, so they get outdated quickly. This PR changes the link to use the github links instead.
N/A

chore: use github link instead for `CONTRIBUTING.md`

---

CONTRIBUTING.md

This PR fixes broken links on CONTRIBUTING.md. 
- Analyzer: change `biome_analyzer` to `biome_analyze`
- Formatter: currently we don't have CONTRIBUTING.md and it says on Rust doc comments, so use that for now.
Jump to the links from the diff files

docs: fix broken links on CONTRIBUTING.md

---

CHANGELOG.md
crates/biome_json_syntax/src/file_source.rs
crates/biome_service/src/file_handlers/json.rs
crates/biome_service/src/file_handlers/mod.rs
crates/biome_service/tests/workspace.rs
packages/@biomejs/backend-jsonrpc/src/workspace.ts
website/src/content/docs/internals/changelog.md

This PR fixes an issue where the server cannot correctly parse `.jsonc` files.
I still do not fully understand how CLI and LSP work, so I tweaked the code based on my understanding and left some comments. Please correct me if I did something unexpected.
Added a test function in `workspace.rs` to show that it can correctly handle `.jsonc` files now.

fix(biome_service): `.jsonc` file source and parsing

---

crates/biome_js_analyze/src/lint/style/use_filenaming_convention.rs
packages/@biomejs/backend-jsonrpc/src/workspace.ts
packages/@biomejs/biome/configuration_schema.json
website/src/content/docs/linter/rules/use-filenaming-convention.md

Just a small change that corrects the example option in the documentation.

docs(lint/style/useFilenamingConvention): fix example options

---

crates/biome_json_syntax/src/file_source.rs
crates/biome_service/src/diagnostics.rs
crates/biome_service/src/file_handlers/json.rs
crates/biome_service/src/file_handlers/mod.rs
crates/biome_service/src/workspace/server.rs
crates/biome_service/tests/workspace.rs
packages/@biomejs/backend-jsonrpc/src/workspace.ts
website/src/content/docs/guides/how-biome-works.mdx

This PR addresses the TODO lists in #2141 and is a splitted PR from #2146 to not introduce new features. The main reason behind the changes is `JSONC` is not well-defined: some may support trailing commas, some may not:
- I removed the `variant` field in `JsonFileSource` to keep a single source of truth, because it already has fields `allow_trailing_commas` and `allow_comments`.
- I dropped the term `jsonc` because of its ambiguity in favor of using the fluent style API `json().with_comments(true)` and `json().with_comments(true).with_trailing_commas(true)` to properly reflect the main idea.
- Well-known files list is not touched. But I updated the document a bit.
Different kinds of json-like files are tested in `crates/biome_service/tests/workspace.rs`

refactor: json file source

---

Cargo.lock
Cargo.toml
crates/biome_cli/Cargo.toml
crates/biome_css_analyze/Cargo.toml
crates/biome_css_formatter/Cargo.toml
crates/biome_css_parser/Cargo.toml
crates/biome_js_analyze/Cargo.toml
crates/biome_js_formatter/Cargo.toml
crates/biome_js_parser/Cargo.toml
crates/biome_js_semantic/Cargo.toml
crates/biome_js_syntax/Cargo.toml
crates/biome_json_analyze/Cargo.toml
crates/biome_json_formatter/Cargo.toml
crates/biome_migrate/Cargo.toml
crates/biome_rowan/Cargo.toml
crates/biome_wasm/Cargo.toml

Closes: https://github.com/biomejs/biome/issues/2136
ran `cargo shear --fix` and did some fixes (cargo-shear still had some bugs)

Chore: remove unused dependencies

---

.github/workflows/main.yml
.github/workflows/parser_conformance.yml

Use `git config --system core.longpaths true` when we're not inside a git repo.
CI on main should pass.

chore(ci): set git longpaths system-wide

---

.github/workflows/main.yml
.github/workflows/parser_conformance.yml

There're permission issues when running `git config --system core.longpaths true`. I added the checkout steps back.
CI on main should pass.

chore(ci): free disk space, again

---

CHANGELOG.md
crates/biome_fs/src/fs.rs
crates/biome_fs/src/fs/memory.rs
crates/biome_fs/src/fs/os.rs
crates/biome_lsp/src/server.rs
crates/biome_lsp/src/session.rs
crates/biome_service/src/configuration/mod.rs
website/src/content/docs/internals/changelog.md

This PR fixes an issue where the config files in external packages specified in the `extends` option cannot be resolved properly when running in LSP mode (e.g. integrated with an editor).
Fixes #2159.
We didn't implement the method to resolve an external configuration file in a memory os, so I just test this locally with the VSCode extension.

fix(lsp): correctly resolve `extends` configs

---

CHANGELOG.md
crates/biome_cli/src/execute/migrate/prettier.rs
crates/biome_cli/tests/commands/migrate.rs
crates/biome_cli/tests/snapshots/main_commands_migrate/prettier_migrate_end_of_line.snap
website/src/content/docs/internals/changelog.md

I tried to migrate from prettier, and the migration failed because of unsupported option
#2138 
you can migrate a prettierrc like this 
```json
{
"printWidth": 120,
"useTabs": true,
"tabWidth": 2,
"singleQuote": true,
"semi": false,
"trailingComma": "all",
"bracketSameLine": false,
"arrowParens": "avoid",
"endOfLine": "auto"
}
```
I KNOW that auto won't be supported, but i think it's better for the UX to continue the flow with the best option possible instead of stopping in error
feel free to close if you disagree

fix: migrate prettier auto endofline to LF as it's the default

---

crates/biome_grit_parser/src/lexer/mod.rs
crates/biome_js_parser/src/lexer/mod.rs
crates/biome_parser/src/lexer.rs

I noticed a few methods in the JS lexer that are also present in the generic lexer, so I removed them in favor of the generic one.
Also, there was a tiny duplication now in the `current_char_unchecked()` method between the JS and Grit lexers, so I moved it to the generic one.

chore: reduce redundant lexer methods

---

.github/workflows/bench_cli.yml
.github/workflows/benchmark.yml
.github/workflows/main.yml
.github/workflows/parser_conformance.yml
.github/workflows/pull_request.yml
.github/workflows/pull_request_js.yml
.github/workflows/runtime.yml

Our CI is encountering this error: `Failed to save: Cache service responded with 429 during upload chunk.`, which seems that the rate limit is triggered by our frequent cache-updating requests.
To solve this issue, this PR changes the `setup-rust` steps to use the **[warmup strategy](https://github.com/moonrepo/setup-rust?tab=readme-ov-file#warmup-strategy)**. This strategy will relax the granularity of the cache keys, and only save caches when the workflow is running on the main branch.
I also updated the `cache-target` options for some jobs, because they're building in release mode but caching the debug target.
CI should pass and the new cache strategy should work as expected.

chore(ci): update `setup-rust` cache strategy

---

.github/workflows/main.yml

Warmup strategy doesn't work well with rust nightly channels because we will then always save two copies of toolchains in our runner, one is the stable from the warmup branch and the other is the nightly. Therefore it can eat up the space quickly.
So I disabled the cache for nightly channel toolchains. It's **nightly**, so I think it will be fine.
Jobs requiring nightly channel toolchains shouldn't fail.

chore(ci): do not cache nightly channel

---

.github/workflows/pull_request_js.yml

The problematic commit: https://github.com/biomejs/biome/pull/2166/files#diff-16233821c7a54e3f17c4c0e1ddff269adc1dc764c80887e10e242fecbaa1efcd
I was hoping to accelerate the building process but this will trigger a build error. So revert the change.

chore(ci): revert `wasm-pack` dev mode change

---

CHANGELOG.md
crates/biome_cli/src/cli_options.rs
crates/biome_cli/tests/cases/config_path.rs
crates/biome_cli/tests/cases/mod.rs
crates/biome_cli/tests/snapshots/main_cases_config_path/set_config_path.snap
crates/biome_cli/tests/snapshots/main_commands_check/check_help.snap
crates/biome_cli/tests/snapshots/main_commands_ci/ci_help.snap
crates/biome_cli/tests/snapshots/main_commands_format/format_help.snap
crates/biome_cli/tests/snapshots/main_commands_lint/lint_help.snap
crates/biome_cli/tests/snapshots/main_commands_migrate/migrate_help.snap
crates/biome_cli/tests/snapshots/main_commands_rage/rage_help.snap
crates/biome_fs/src/fs.rs
crates/biome_service/src/configuration/mod.rs
website/src/content/docs/internals/changelog.md

I refactored the `auto_search` function that is used to find the configuration file. In the previous version of this function, the searching process would immediately stop if it couldn't find a `biome.json` file in the user provided base path, which isn't an expected behavior because `config-path` accepts a directory path, not a file path. So it should search all the possible alternatives, i.e. `biome.jsonc` file in the user provided path as well, and only returns an error if it cannot find any configuration file in that directory path.
Closes #2164.
I added a test case to ensure that the `biome.jsonc` configuration file can now be correctly resolved in the user provided config path.

fix(biome_fs): configuration resolution

---

website/src/playground/tabs/ControlFlowTab.tsx
website/src/styles/playground/_results.scss

Our control flow graph in the playground doesn't work now. That's because [mermaid v10 changed its `render` function to an async one](https://github.com/mermaid-js/mermaid/blob/master/CHANGELOG.md#mermaidrender-is-async-and-doesnt-accept-callbacks).
The version of `mermaid` was bumped in this commit: 8dac854.
This PR fixes it.
Visual check.

fix(website): control flow

---

crates/biome_css_formatter/src/css/statements/property_at_rule.rs
crates/biome_css_formatter/tests/specs/css/atrule/property.css
crates/biome_css_formatter/tests/specs/css/atrule/property.css.snap

Implement `CssPropertyAtRule` formatting
`cargo test`

feat(css_formatter): CssPropertyAtRule formatting

---

website/src/content/docs/guides/how-biome-works.mdx

In [How Biome works](https://biomejs.dev/guides/how-biome-works/) page, in [`include` and `ignore` explained](https://biomejs.dev/guides/how-biome-works/#include-and-ignore-explained) section there is a dangling phrase:
```text
This I
```
I have removed it
The phrase was removed after running the updated code on my machine via
```sh
pnpm --filter @biomejs/website start
```

docs(guides/how-biome-works): remove dangling phrase

---

CHANGELOG.md
crates/biome_js_formatter/src/js/bindings/object_binding_pattern_property.rs
crates/biome_js_formatter/tests/specs/js/module/binding/object_binding.js
crates/biome_js_formatter/tests/specs/js/module/binding/object_binding.js.snap
website/src/content/docs/internals/changelog.md

Closes https://github.com/biomejs/biome/issues/2172
Align the IR of `JsObjectBindingPatternProperty` with Prettier.
```
group([
group("fairlyLongObjectKeyLongEnoughToBreakCharacterLimit"),
":",
group(indent(line), { id: Symbol.for("assignment") }),
lineSuffixBoundary,
indentIfBreak(
"_fairlyLongValueNameLongEnoughToBreakCharacterLimit",
{ groupId: Symbol.for("assignment") },
),
]),
```
Add a new test case and update the corresponding snapshot

fix(js_formatter): break long destructuring binding pattern  

---

CHANGELOG.md
crates/biome_cli/tests/snapshots/main_commands_check/check_help.snap
crates/biome_cli/tests/snapshots/main_commands_ci/ci_help.snap
crates/biome_cli/tests/snapshots/main_commands_format/format_help.snap
crates/biome_service/src/configuration/formatter.rs
crates/biome_service/src/configuration/javascript/formatter.rs
crates/biome_service/src/configuration/overrides.rs
crates/biome_service/src/settings.rs
packages/@biomejs/backend-jsonrpc/src/workspace.ts
packages/@biomejs/biome/configuration_schema.json
website/src/content/docs/internals/changelog.md
website/src/content/docs/reference/cli.mdx
website/src/content/docs/reference/configuration.mdx

This PR fixes an issue where we cache the final options after we apply overrides to the options, and reuse them in other files in the same workspace. JavaScript/TypeScript files of different variants (`.ts`, `.js`, `.tsx`, `.jsx`) in a single workspace cannot share the same cache because they have different file source params which will affect how they are formatted. This PR uses the `JsFileSource` as the cache key so files of different file sources will have different cached options. Refer to https://github.com/biomejs/biome/issues/2109#issuecomment-2016358037 for more details.
Fixes #2080, fixes #2109.
As a side note/fix, I updated the overrides application functions and configuration doc on our website to take options `lineEnding` and `attributePosition` into account. They were not …

fix(service): cached `JsFormatOptions` with overrides

---

CHANGELOG.md
crates/biome_lsp/src/handlers/analysis.rs
website/src/content/docs/internals/changelog.md

- Quick fix shouldn't pull lint fix actions when the linter is disabled in the config.
- Also fix some errors in the changelog.
Closes #2161.
I didn't figure out a way to add test cases for this fix. I tested it locally with the VSCode Extension and it works as expected.

fix(lsp): quick fix code actions

---

crates/biome_analyze/CONTRIBUTING.md
xtask/codegen/src/generate_new_lintrule.rs

In `generate_new_lintrule.rs`, this PR fixes 
- to use `node.range()` because `reference` isn't defined
- to locate new lint rule in `src/lint/nursery`
Executed `just new-js-lintrule ruleName` without fail

fix(codegen): new lint rule generation

---

CHANGELOG.md
crates/biome_analyze/src/lib.rs
crates/biome_lsp/src/handlers/formatting.rs
website/src/content/docs/internals/changelog.md

Fixes cases where range formatting places code in an incorrect place.
I tested manually

fix(lsp): format range for Astro/Vue/Svelte files

---

crates/biome_cli/src/commands/mod.rs
crates/biome_cli/src/commands/search.rs
crates/biome_cli/src/execute/mod.rs
crates/biome_cli/src/execute/process_file.rs
crates/biome_cli/src/execute/process_file/search.rs
crates/biome_cli/src/execute/traverse.rs
crates/biome_cli/src/lib.rs
crates/biome_cli/src/logging.rs
crates/biome_diagnostics_categories/src/categories.rs
crates/biome_service/src/workspace.rs
crates/biome_service/src/workspace/client.rs
crates/biome_service/src/workspace/server.rs
packages/@biomejs/backend-jsonrpc/src/workspace.ts

This adds the infrastructure for implementing the `biome search` command, but the actual implementation will be left for a future PR. The command remains hidden through the `bpaf` options as long as implementation is not complete.
Everything should remain green.

chore: `search` command infra

---

crates/biome_css_formatter/src/css/auxiliary/import_anonymous_layer.rs
crates/biome_css_formatter/src/css/auxiliary/import_named_layer.rs
crates/biome_css_formatter/src/css/auxiliary/import_supports.rs
crates/biome_css_formatter/src/css/statements/import_at_rule.rs
crates/biome_css_formatter/tests/specs/css/atrule/import.css
crates/biome_css_formatter/tests/specs/css/atrule/import.css.snap
crates/biome_css_formatter/tests/specs/prettier/css/atrule/import.css.snap
crates/biome_css_formatter/tests/specs/prettier/css/comments/at-rules.css.snap
crates/biome_css_formatter/tests/specs/prettier/css/inline-url/inline_url.css.snap
crates/biome_css_formatter/tests/specs/prettier/css/quotes/quotes.css.snap

Implement formatting for `CssImportAtRule`.
`cargo test`

feat(css_formatter): CssImportAtRule formatting

---

crates/biome_cli/src/commands/check.rs
crates/biome_cli/src/commands/ci.rs
crates/biome_cli/src/commands/format.rs
crates/biome_cli/src/commands/lint.rs
crates/biome_cli/src/commands/migrate.rs
crates/biome_cli/src/commands/mod.rs
crates/biome_cli/src/commands/search.rs
crates/biome_cli/src/logging.rs

Deriving `Copy` makes it so that types can be copied without needing to explicitly call `.clone()`. This makes the type a little easier to work with, and also indicates there is no hidden performance cost to copying it. As such, it should only be derived on types that don't require allocations. For enums where the variants have no custom fields, deriving `Copy` is generally safe, as long as no future variants with custom fields are anticipated either.
See also: https://doc.rust-lang.org/std/marker/trait.Copy.html#when-should-my-type-be-copy

chore: derive `Copy` on `LoggingKind` and `LoggingLevel`

---

website/src/content/docs/pt-br/index.mdx

Update pt-br homepage.
Related: https://github.com/biomejs/biome/issues/1958
Run pnpm start locally and check/compare the translated homepage on the dev server with the default one.

docs(pt-br): Update pt-br/index.mdx

---

crates/biome_js_analyze/src/lint/correctness/use_is_nan.rs
crates/biome_js_analyze/src/lint/suspicious/no_global_is_finite.rs
crates/biome_js_analyze/src/lint/suspicious/no_global_is_nan.rs
website/src/content/docs/linter/rules/no-global-is-finite.md
website/src/content/docs/linter/rules/no-global-is-nan.md
website/src/content/docs/linter/rules/use-is-nan.md

This is a small change that fixes the back-to-front wording on the docs for the rules `noGlobalIsFinite`, `noGlobalIsNan` and `useIsNan`.

fix(docs): improve wording of docs for global Number rules

---

CHANGELOG.md
crates/biome_cli/tests/commands/lint.rs
crates/biome_cli/tests/snapshots/main_commands_lint/group_level_disable_recommended_enable_specific.snap
crates/biome_service/src/configuration/linter/rules.rs
website/src/content/docs/internals/changelog.md
xtask/codegen/src/generate_configuration.rs

Correctly calculate enabled rules in lint rule groups.
This is the [Karnaugh map](https://en.wikipedia.org/wiki/Karnaugh_map) of lint group preset logic:
| Self (`A`, `R`) \ Parent (`A`, `R`) | (`N`, `F`) | (`N`, `T`) | (`F`, `F`) | (`F`, `T`) | (`T`, `F`) | (`T`, `T`) |
| :---------------------------------: | :--------: | :--------: | :--------: | :--------: | :--------: | :--------: |
|           **(`N`, `N`)**            |     -      |    `R`     |     -      |    `R`     |    `A`     |    `A`     |
|           **(`N`, `F`)**            |     -      |     -      |     -      |     -      |    `A`     |    `A`     |
|           **(`N`, `T`)**            |    `R`     |    `R`     |    `R`     |    `R`     |    `A`     |    `A`     |
|           **(`F`, `N`)**            |     -      | …

fix(config): group-level lint rules calculation

---

crates/biome_css_formatter/src/css/statements/starting_style_at_rule.rs
crates/biome_css_formatter/tests/specs/css/atrule/starting_style.css
crates/biome_css_formatter/tests/specs/css/atrule/starting_style.css.snap

Adds formatting for `@starting-style` at rule.

feat(formatter): format `@starting-style`

---

CHANGELOG.md
crates/biome_js_analyze/src/lint/correctness/no_children_prop.rs
crates/biome_js_analyze/tests/specs/correctness/noChildrenProp/noChildrenPropInvalid.jsx
crates/biome_js_analyze/tests/specs/correctness/noChildrenProp/noChildrenPropInvalid.jsx.snap
website/src/content/docs/internals/changelog.md

closes: https://github.com/biomejs/biome/issues/2211

fix(lint): rule noChildrenProp not valid under children in a new line

---

website/src/content/docs/analyzer/index.mdx

Fixed a typo in one of the code blocks of the documentation.
There was a typo on the documentation website, specifically [here](https://biomejs.dev/analyzer/)
It's just a typo-fix so no test is needed.

Fixed a typo in the docs

---

website/src/content/docs/analyzer/index.mdx

fix `import sorting` link.
[related link](https://biomejs.dev/analyzer/)
When I clicked `import sorting` link, the page is 404.
I fixed `import-organizer` to `import sorting`.
It's just a typo fix.
Thank you.

chore: fix typo in docs

---

CHANGELOG.md
crates/biome_js_analyze/src/lint/a11y/use_button_type.rs
crates/biome_js_analyze/tests/specs/a11y/useButtonType/inJsx.jsx
crates/biome_js_analyze/tests/specs/a11y/useButtonType/inJsx.jsx.snap
website/src/content/docs/internals/changelog.md

fix(lint/a11y/use_button_type): skip the rule with spread attribute

---

CHANGELOG.md
crates/biome_js_analyze/src/utils.rs
website/src/content/docs/internals/changelog.md

This PR fixes an issue where an operator with no spaces around in a binary expression can break the js analyzer. Specifically when rule `lint/suspicious/noMisrefactoredShorthandAssign` is enabled.
Closes #2243

fix(js_analyzer): binary expression utils

---

crates/biome_html_factory/src/generated/node_factory.rs
crates/biome_html_factory/src/generated/syntax_factory.rs
crates/biome_html_parser/src/lexer/mod.rs
crates/biome_html_parser/src/syntax/mod.rs
crates/biome_html_parser/src/syntax/parse_error.rs
crates/biome_html_parser/src/token_source.rs
crates/biome_html_parser/tests/html_specs/ok/element_list.html
crates/biome_html_parser/tests/html_specs/ok/element_list.html.snap
crates/biome_html_syntax/src/generated/kind.rs
crates/biome_html_syntax/src/generated/macros.rs
crates/biome_html_syntax/src/generated/nodes.rs
crates/biome_html_syntax/src/generated/nodes_mut.rs
crates/biome_html_syntax/src/lib.rs
xtask/codegen/html.ungram
xtask/codegen/src/html_kinds_src.rs

This PR implements the basic parsing of a list of elements. The parsing of this list is inspired to the JSX parsing, where all trivia is parsed as a `HtmlContent`.
The lexer also adds some initial lexing of comments, although I haven't implemented any logic because I encountered some lexing issue that I prefer to solve after this PR lands.
I added new test cases

feat(parser): basic parsing element list with context bump

---

CHANGELOG.md
crates/biome_cli/tests/snapshots/main_commands_migrate/prettier_migrate_yml_file.snap
crates/biome_deserialize/src/json.rs
crates/biome_service/src/configuration/snapshots/deserialization_error.snap
website/src/content/docs/internals/changelog.md

Fix #1627
I updated the changed snapshots.

refactor(biome_deserialize): display parsing error source

---

CHANGELOG.md
crates/biome_js_analyze/src/lint/nursery/no_nodejs_modules.rs
crates/biome_js_analyze/src/lint/nursery/no_restricted_imports.rs
crates/biome_js_analyze/src/lint/nursery/no_undeclared_dependencies.rs
crates/biome_js_analyze/src/lint/nursery/use_node_assert_strict.rs
crates/biome_js_analyze/src/lint/style/use_nodejs_import_protocol.rs
crates/biome_js_analyze/tests/specs/nursery/noNodejsModules/valid.ts
crates/biome_js_analyze/tests/specs/nursery/noNodejsModules/valid.ts.snap
crates/biome_js_analyze/tests/specs/nursery/noRestrictedImports/valid.options.json
crates/biome_js_analyze/tests/specs/nursery/noRestrictedImports/valid.ts
crates/biome_js_analyze/tests/specs/nursery/noRestrictedImports/valid.ts.snap
crates/biome_js_analyze/tests/specs/nursery/useNodeAssertStrict/valid.ts
crates/biome_js_analyze/tests/specs/nursery/useNodeAssertStrict/valid.ts.snap
crates/biome_js_analyze/tests/specs/style/useNodejsImportProtocol/valid.ts
crates/biome_js_analyze/tests/specs/style/useNodejsImportProtocol/valid.ts.snap
crates/biome_js_syntax/src/import_ext.rs
website/src/content/docs/internals/changelog.md

Rules `useNodejsImportProtocol`, `useNodeAssertStrict`, `noRestrictedImports` and `noNodejsModules` shouldn't check `declare module` statements.
```ts
declare module "node:assert" {} // <-- shouldn't check the module specifier at this place
```
I added a helper function `is_in_ts_module_declaration` to `AnyJsImportSpecifierLike`.
Added a doc test for the helper function `is_in_ts_module_declaration`. Added valid cases for these rules.

fix(lint_rules): false positives of several rules

---

crates/biome_css_factory/src/generated/syntax_factory.rs
crates/biome_css_formatter/src/utils/component_value_list.rs
crates/biome_css_formatter/tests/quick_test.rs
crates/biome_css_formatter/tests/specs/css/atrule/font_face.css.snap
crates/biome_css_formatter/tests/specs/css/functions.css.snap
crates/biome_css_formatter/tests/specs/css/properties/all.css
crates/biome_css_formatter/tests/specs/css/properties/all.css.snap
crates/biome_css_formatter/tests/specs/css/url.css.snap
crates/biome_css_formatter/tests/specs/css/value_fill.css.snap
crates/biome_css_formatter/tests/specs/css/variables.css.snap
crates/biome_css_formatter/tests/specs/prettier/css/atrule/font-face.css.snap
crates/biome_css_formatter/tests/specs/prettier/css/comments/declaration.css.snap
crates/biome_css_formatter/tests/specs/prettier/css/composes/composes.css.snap
crates/biome_css_formatter/tests/specs/prettier/css/fill-value/fill.css.snap
crates/biome_css_formatter/tests/specs/prettier/css/grid/grid.css.snap
crates/biome_css_formatter/tests/specs/prettier/css/indent/indent.css.snap
crates/biome_css_formatter/tests/specs/prettier/css/parens/parens.css.snap
crates/biome_css_formatter/tests/specs/prettier/css/trailing-comma/var-func.css.snap
crates/biome_css_formatter/tests/specs/prettier/css/url/url.css.snap
crates/biome_css_parser/tests/css_test_suite/error/at_rule/at_rule_document_error.css.snap
xtask/codegen/css.ungram

This PR updates the `component_value_list` in the CSS formatter to include `ValueListLayout::SingleLine` format. It also refactors the function to determine the layout style according to the list length. This change anticipates further support for one-per-line comma-separated lists
`cargo test`

feat(css_formatter): ValueListLayout::SingleLine

---

website/src/content/docs/reference/vscode.mdx

As requested in this comment: https://github.com/biomejs/biome/issues/1630#issuecomment-2036471511, this PR adds a description of a current limitation of the VSCode extension regarding multi-root workspaces.
- #1573
- #1630
- #2036

Describe multi-root workspace limitation in docs

---

crates/biome_js_analyze/src/lint/nursery/no_duplicate_test_hooks.rs
website/src/content/docs/linter/rules/no-duplicate-test-hooks.md

Fix rule source of `noDuplicateTestHooks`

docs(lint/noDuplicateTestHooks): fix rule source

---

CHANGELOG.md
crates/biome_js_analyze/src/lint/correctness/no_unused_imports.rs
crates/biome_js_analyze/src/react.rs
crates/biome_js_analyze/tests/specs/correctness/noUnusedImports/invalid-unused-react.jsx
crates/biome_js_analyze/tests/specs/correctness/noUnusedImports/invalid-unused-react.jsx.snap
crates/biome_js_analyze/tests/specs/correctness/noUnusedImports/invalid-unused-react.options.json
crates/biome_js_analyze/tests/specs/correctness/noUnusedImports/valid-unused-react.jsx
crates/biome_js_analyze/tests/specs/correctness/noUnusedImports/valid-unused-react.jsx.snap
crates/biome_js_analyze/tests/specs/correctness/noUnusedImports/valid-unused-react.options.json
packages/@biomejs/backend-jsonrpc/src/workspace.ts
packages/@biomejs/biome/configuration_schema.json
website/src/content/docs/internals/changelog.md
website/src/content/docs/linter/rules/no-unused-imports.md

Fix #571
Add a new option to `noUnusedImports` to ignore imports of React.
This was requested by many users.
I added new tests.

feat(lint/noUnusedImports): add ignoreReact option

---

CHANGELOG.md
crates/biome_fs/src/fs/os.rs
website/src/content/docs/internals/changelog.md

When running `lint`, `check` or `format` with the flag `--changed`, ensure that files outside the current directory are filtered out before processing them.
Fixes #1996 .
- Tested it manually at different nested directory levels (including the "root" directory).
- Note that it is difficult to introduce an automated regression test without big changes because the memory filesystem used in tests doesn't allow us to check if the flags we pass to `git` are correct or not.

fix(cli): skip files outside the current directory when using --changed

---

CHANGELOG.md
crates/biome_cli/tests/cases/handle_svelte_files.rs
crates/biome_cli/tests/snapshots/main_cases_handle_svelte_files/format_svelte_ts_context_module_files.snap
crates/biome_cli/tests/snapshots/main_cases_handle_svelte_files/format_svelte_ts_context_module_files_write.snap
crates/biome_cli/tests/snapshots/main_cases_handle_svelte_files/sorts_imports_check.snap
crates/biome_service/src/file_handlers/mod.rs
crates/biome_service/src/file_handlers/svelte.rs
crates/biome_service/src/file_handlers/vue.rs
website/src/content/docs/internals/changelog.md

Use the JSX flavor JavaScript parser to parse the opening tags of the script blocks in Svelte and Vue files so we can parse the language of the script in them more reliably.
Closes #2245.
Test cases are added.

fix(file_handler): svelte & vue script language parsing

---

crates/biome_aria/src/roles.rs
crates/biome_js_analyze/src/lint/a11y/no_svg_without_title.rs
website/src/content/docs/linter/rules/no-svg-without-title.md

Adds the `graphics-symbol` ARIA role which should be replaceable with `img` for valid SVG ARIA roles (and is more descriptive for icons). Updates possible usage from current recommendations from [an article from University at Melbourne](https://www.unimelb.edu.au/accessibility/techniques/accessible-svgs).
`jsx-a11y` had this same problem at one point, but I think that’s been [fixed already](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/issues/756) and that currently supports these roles for SVGs, so this should just bring parity with that (or at least, that’s the intention)
Also adds `graphics-document` and `graphics-object` roles for completeness…but I might have messed something up? Open to feedback if something’s in the wrong place 🙂

fix(js_analyzer): add graphics-symbol role

---

CHANGELOG.md
crates/biome_cli/src/execute/migrate.rs
crates/biome_cli/src/execute/migrate/eslint.rs
crates/biome_cli/src/execute/migrate/ignorefile.rs
crates/biome_cli/src/execute/migrate/prettier.rs
crates/biome_cli/tests/commands/migrate_prettier.rs
crates/biome_cli/tests/snapshots/main_commands_migrate_prettier/prettier_migrate_write_packagejson.snap
crates/biome_cli/tests/snapshots/main_commands_migrate_prettier/prettier_migrate_yml_file.snap
crates/biome_cli/tests/snapshots/main_commands_migrate_prettier/prettierjson_migrate_write.snap
website/src/content/docs/internals/changelog.md

This PR adds support for loading Prettier config files ending with a js-like extension.
I used the sane strategy as #2103: invoking `node` to resolve the file.
It also adds support for embedded Prettier config in `package.json`.
Remaining tasks
I manually tested

feat(migrate-prettier): support js configs

---

.github/workflows/update_contributors.yml
xtask/contributors/src/main.rs

Add a workflow to update contributors regularly. This workflow will create a PR to update the contributors list in `Community.astro` and `Contributors.astro`.
If the list doesn't need to be updated, this workflow will not create a PR.
This workflow can also be executed manually.
Tested on my forked repo.

chore(ci): add update contributors workflow

---

CHANGELOG.md
packages/@biomejs/biome/configuration_schema.json
website/src/content/docs/internals/changelog.md
xtask/codegen/src/generate_schema.rs

Fix #2313 by completely removing `options` form the JSON schema for rules without any option.
I manually tested the schema.

fix(json-schema): remove field `options` for rules without options

---

CHANGELOG.md
crates/biome_cli/src/execute/migrate.rs
crates/biome_cli/src/execute/migrate/prettier.rs
crates/biome_cli/tests/commands/migrate_prettier.rs
crates/biome_cli/tests/snapshots/main_commands_migrate_prettier/prettier_migrate_overrides.snap
crates/biome_configuration/src/css.rs
crates/biome_configuration/src/formatter.rs
crates/biome_configuration/src/javascript/formatter.rs
crates/biome_configuration/src/json.rs
crates/biome_configuration/src/lib.rs
crates/biome_configuration/src/overrides.rs
crates/biome_formatter/src/lib.rs
packages/@biomejs/biome/configuration_schema.json
website/src/content/docs/internals/changelog.md

This PR adds the support for the `overrides` field in Prettier configuration.
While I was testing the feature, I noticed missing serde's `skip_serialization_if = Option::is_none` for some fields of the Biome configuration file. I added them.

feat(migrate-prettier): support `overrides` field

---

crates/biome_js_analyze/src/lint/a11y/no_svg_without_title.rs
website/src/content/docs/linter/rules/no-svg-without-title.md

Address the @Sec-ant 's comment : https://github.com/biomejs/biome/pull/2294#issuecomment-2041512217
Thanks for the report!
The valid case `<svg aria-hidden><rect /></svg>` needs `aria-hidden="true"` because the attribute is default false.
Executed `just gen-lint` and checked that emits no errors.

fix(lint): `noSvgWithoutTitle` valid case to use `aria-hidden` correctly

---

crates/biome_js_analyze/src/react/hooks.rs
crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/stableResultInvalid.js
crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/stableResultInvalid.js.snap
crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/stableResultInvalid.options.json

`stableResult` works for hooks other than the specified name.
For instance, even if you change the name of `useDispatch` to something else, the tests will still pass.
https://github.com/biomejs/biome/blob/f5dd08679c752f3a9ec54fa54c5ee1d12cc13a97/crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/stableResult.options.json#L6-L16
In this PR, added a check to ensure the function names match the stable custom hook names.
However, it does not work when an alias is provided, as shown below:
```js
import { useCallback } from "react";
import { useDispatch as uD } from "react-redux";
function MyComponent25() {
const dispatch = uD();
const doAction = useCallback(() => dispatch(someAction()), []);
}
```
I am not very familiar with this project, so I would appreciate it if you …

fix(lint/useExhaustiveDependencies): unintended application of stable custom hook rules

---

xtask/contributors/src/main.rs

Remove bots from contributors list. Added an ending newline to the generated file `Contributors.astro`.
Tested on my forked repo.

chore(ci): remove bots from contributors

---

CHANGELOG.md
crates/biome_js_analyze/src/lint/style/use_filenaming_convention.rs
crates/biome_js_analyze/tests/specs/style/useFilenamingConvention/+in+valid.js.snap
crates/biome_js_analyze/tests/specs/style/useFilenamingConvention/+val_id.js.snap
website/src/content/docs/internals/changelog.md
website/src/content/docs/linter/rules/use-filenaming-convention.md

Fix #2341.
[style/useFilenamingConvention](https://biomejs.dev/linter/rules/use-filenaming-convention/) now accepts filenames that start with `+`.
I added new tests.

refactor(lint/useFilenamingConvention): allow `+` prefix

---

CHANGELOG.md
crates/biome_css_syntax/src/file_source.rs
crates/biome_html_syntax/src/file_source.rs
crates/biome_js_syntax/src/file_source.rs
crates/biome_json_syntax/src/file_source.rs
crates/biome_rowan/src/file_source.rs
crates/biome_service/src/file_handlers/json.rs
crates/biome_service/src/file_handlers/mod.rs
crates/biome_service/tests/workspace.rs
website/src/content/docs/guides/how-biome-works.mdx
website/src/content/docs/internals/changelog.md
website/src/content/docs/internals/language-support.mdx

- Refactor the file source calculation
I noticed some code redundency and multiple sources of truth in file source calculation and that can be a hidden footgun maintaining-wise. So I tried to refactor the code in a cleaner way. I have very little exprience in tweaking the Rust code in a project level, so please correct me if I did something wrong.
- Complete the well-known json-like file lists
This supersedes #2146.
- Existing tests should pass.
- `WELL_KNOWN...` lists should be sorted for binary search, so a `test_order` function is added to ensure they're sorted.
- Different kinds of json-like files are tested in `crates/biome_service/tests/workspace.rs`

refactor(service): file source

---

crates/biome_js_analyze/src/lint/style/use_number_namespace.rs
website/src/content/docs/linter/rules/use-number-namespace.md

chore(use-number-namespace.md): fix typo

---

crates/biome_graphql_factory/src/generated/node_factory.rs
crates/biome_graphql_factory/src/generated/syntax_factory.rs
crates/biome_graphql_parser/src/lexer/mod.rs
crates/biome_graphql_parser/src/lexer/tests.rs
crates/biome_graphql_parser/src/parser/argument.rs
crates/biome_graphql_parser/src/parser/definitions/operation.rs
crates/biome_graphql_parser/src/parser/directive.rs
crates/biome_graphql_parser/src/parser/mod.rs
crates/biome_graphql_parser/src/parser/parse_error.rs
crates/biome_graphql_parser/src/parser/type.rs
crates/biome_graphql_parser/src/parser/value.rs
crates/biome_graphql_parser/src/parser/variable.rs
crates/biome_graphql_parser/tests/graphql_test_suite/err/operation.graphql
crates/biome_graphql_parser/tests/graphql_test_suite/err/operation.graphql.snap
crates/biome_graphql_parser/tests/graphql_test_suite/ok/directive.graphql
crates/biome_graphql_parser/tests/graphql_test_suite/ok/directive.graphql.snap
crates/biome_graphql_parser/tests/graphql_test_suite/ok/operation.graphql
crates/biome_graphql_parser/tests/graphql_test_suite/ok/operation.graphql.snap
crates/biome_graphql_parser/tests/graphql_test_suite/ok/selection_set.graphql
crates/biome_graphql_parser/tests/graphql_test_suite/ok/selection_set.graphql.snap
crates/biome_graphql_parser/tests/graphql_test_suite/ok/type.graphql
crates/biome_graphql_parser/tests/graphql_test_suite/ok/type.graphql.snap
crates/biome_graphql_parser/tests/graphql_test_suite/ok/value.graphql
crates/biome_graphql_parser/tests/graphql_test_suite/ok/value.graphql.snap
crates/biome_graphql_syntax/src/generated/macros.rs
crates/biome_graphql_syntax/src/generated/nodes.rs
crates/biome_graphql_syntax/src/generated/nodes_mut.rs
crates/biome_graphql_syntax/src/lib.rs
xtask/codegen/graphql.ungram

This PR implement the operation parsing rule, allowing the GraphQL parser to parse [query/mutation operation](https://spec.graphql.org/October2021/#sec-Language.Operations). This PR only parse the happy path with basic recovery strategy, another PR will be raised to handle the error path
All tests for the parser should pass

Add operation parsing rule for GraphQL parser

---

CHANGELOG.md
crates/biome_js_syntax/src/file_source.rs
crates/biome_lsp/tests/server.rs
website/src/content/docs/internals/changelog.md

Allow JSX syntax in files with the `javascript` language id.
This is an ad hoc fix, because [in the React world, `.js` files are allowed to include JSX syntax](https://github.com/facebook/create-react-app/issues/87#issuecomment-234627904), and these files are often associated with the `javascript` language identifier in most of the editors. Plus, [some editor extensions](https://github.com/michaelgmcd/vscode-language-babel/blob/8b3a472748ad07c99dc022b66795c9eb46be4ccb/package.json#L63-L80) will also associate `.jsx` files with the `javascript` language identifier.
And we already allow JSX syntax in `.js` files when running from the CLI. This will make the LSP work more consistently with the CLI.
Relative links: [discussion](https://github.com/biomejs/biome/discussions/838#discussioncomment …

fix(service): allow JSX syntax for `javascript` language id

---

CHANGELOG.md
crates/biome_js_analyze/src/lint/style/use_naming_convention.rs
crates/biome_js_analyze/tests/specs/style/useNamingConvention/invalidFunctionParameter.js
crates/biome_js_analyze/tests/specs/style/useNamingConvention/invalidFunctionParameter.js.snap
crates/biome_js_analyze/tests/specs/style/useNamingConvention/invalidLocalVariable.js
crates/biome_js_analyze/tests/specs/style/useNamingConvention/invalidLocalVariable.js.snap
crates/biome_js_analyze/tests/specs/style/useNamingConvention/invalidTopLevelVariable.ts.snap
crates/biome_js_analyze/tests/specs/style/useNamingConvention/validComponentName.js.snap
crates/biome_js_analyze/tests/specs/style/useNamingConvention/validFunctionParameter.js
crates/biome_js_analyze/tests/specs/style/useNamingConvention/validFunctionParameter.js.snap
crates/biome_js_analyze/tests/specs/style/useNamingConvention/validLocalVariable.js
crates/biome_js_analyze/tests/specs/style/useNamingConvention/validLocalVariable.js.snap
website/src/content/docs/internals/changelog.md
website/src/content/docs/linter/rules/use-naming-convention.md

Close #2367.
I simply decided to accept `PascalCase` for any variable or function parameter. This is a simple and backward-compatible fix.
Requiring a component to be in `PascalCase` would require traversing all references of a variable to check if one of its references is being used as a component. When I designed `useNamingConvention` I wanted to keep things simple and avoid looking at how a binding is used. I would like to preserve that simplicity.

refactor(useNamingConvention): accept `PascalCase` for variable names

---

CHANGELOG.md
crates/biome_cli/tests/cases/handle_astro_files.rs
crates/biome_cli/tests/cases/handle_svelte_files.rs
crates/biome_cli/tests/cases/handle_vue_files.rs
crates/biome_cli/tests/snapshots/main_cases_handle_astro_files/format_astro_carriage_return_line_feed_files.snap
crates/biome_cli/tests/snapshots/main_cases_handle_svelte_files/format_svelte_carriage_return_line_feed_files.snap
crates/biome_cli/tests/snapshots/main_cases_handle_vue_files/format_vue_carriage_return_line_feed_files.snap
crates/biome_service/src/file_handlers/svelte.rs
crates/biome_service/src/file_handlers/vue.rs
website/src/content/docs/internals/changelog.md

Windows users may use `CRLF` as the end-of-line sequence in their files. This PR fixes the regexes we use to detect script blocks in `.svelte` and `.vue` files to take carriage returns into account.

fix(service): script block detection in `.svelte` and `.vue` files with `CRLF`s

---

website/src/content/docs/formatter/index.mdx
website/src/content/docs/guides/getting-started.mdx
website/src/content/docs/ja/formatter/index.mdx
website/src/content/docs/ja/guides/getting-started.mdx
website/src/content/docs/pt-br/formatter/index.mdx
website/src/content/docs/pt-br/guides/getting-started.mdx
website/src/content/docs/zh-cn/formatter/index.mdx
website/src/content/docs/zh-cn/guides/getting-started.mdx

This PR provides some minor improvements to the website docs:
- Getting Started
- Remove some redundancies: we claim several times that Biome is opinionated.
- Remove the jsonc code sample.
It doesn't add so much value.
- `format --write <files>` is more natural to users and simplify its modification when copied on the CLI
- Add a link to our dedicated CI action
- Formatter
- Merge general and language-specific options in a single code sample.
Users reading this section for the first time might stop at the general options and wonder if Biome supports formatting options such as `arrowParentheses`.
It seems better to put all the options in the same place.
This also makes it easier to copy and paste the config.
Ci should pass.

docs(website): Getting Started and Formatter improvements

---

CHANGELOG.md
crates/biome_cli/src/execute/traverse.rs
crates/biome_fs/src/fs.rs
crates/biome_fs/src/fs/memory.rs
crates/biome_fs/src/fs/os.rs
website/src/content/docs/internals/changelog.md

Skip traversing `fifo` or `socket` files. The code now will only handle files, directories or symlinks.
Closes #2311
Tested locally.

fix(cli): skip traversing `fifo` or `socket` files

---

CHANGELOG.md
crates/biome_fs/src/fs.rs
crates/biome_service/src/configuration.rs
crates/biome_service/tests/spec_tests.rs
crates/biome_service/tests/valid/extends_jsonc_m.json
crates/biome_service/tests/valid/extends_jsonc_s.jsonc
website/src/content/docs/internals/changelog.md

We were using the default JSON parser options for extended configuration deserialization. The PR fixes the parser options with a more forgiving settings for none `.json` configuration files.

fix(configuration): `.jsonc` config deserialization in `extends`

---

CHANGELOG.md
crates/biome_analyze/src/context.rs
crates/biome_analyze/src/options.rs
crates/biome_analyze/src/registry.rs
crates/biome_analyze/src/signals.rs
crates/biome_configuration/src/javascript/mod.rs
crates/biome_js_analyze/src/lint/correctness/no_unused_imports.rs
crates/biome_js_analyze/tests/specs/correctness/noUnusedImports/invalid-unused-react.options.json
crates/biome_js_analyze/tests/specs/correctness/noUnusedImports/valid-unused-react.options.json
crates/biome_service/src/file_handlers/css.rs
crates/biome_service/src/file_handlers/javascript.rs
crates/biome_service/src/file_handlers/json.rs
crates/biome_service/src/settings.rs
crates/biome_test_utils/src/lib.rs
packages/@biomejs/backend-jsonrpc/src/workspace.ts
packages/@biomejs/biome/configuration_schema.json
website/src/content/docs/internals/changelog.md
website/src/content/docs/linter/rules/no-unused-imports.md
website/src/content/docs/reference/configuration.mdx

This replaces the `ignoreReact` setting for the `noUnusedImports` hook with a JavaScript-global `jsxRuntime` setting. This will allow it to be reused by the `useImportType` rule.
See discussion: https://github.com/biomejs/biome/issues/2004
Automated tests are updated and still passing.

refactor: replace `ignoreReact` with `jsxRuntime` setting

---

website/src/content/docs/ja/analyzer/index.mdx
website/src/content/docs/pt-br/analyzer/index.mdx
website/src/content/docs/zh-cn/analyzer/index.mdx

The link to the "Import Sorting" page in `docs/{ja,zh-cn,pt-br}/analyzer/index.mdx` is broken.
Ensure that the link is working.

docs: fix the broken link in analyzer/index.mdx

---

CHANGELOG.md
crates/biome_js_analyze/src/react/hooks.rs
packages/@biomejs/backend-jsonrpc/src/workspace.ts
packages/@biomejs/biome/configuration_schema.json
website/src/content/docs/internals/changelog.md

Derived schema wasn't correct for enum, so I made a manual implementation.
Fixes https://github.com/biomejs/biome/issues/2396

fix(project): fix JSON schema for stable hook options

---

CHANGELOG.md
crates/biome_analyze/src/context.rs
crates/biome_js_analyze/src/lint/correctness/no_unused_imports.rs
crates/biome_js_analyze/src/lint/style/use_import_type.rs
crates/biome_js_analyze/tests/specs/style/useImportType/invalid-unused-react-types.options.json
crates/biome_js_analyze/tests/specs/style/useImportType/invalid-unused-react-types.tsx
crates/biome_js_analyze/tests/specs/style/useImportType/invalid-unused-react-types.tsx.snap
crates/biome_js_analyze/tests/specs/style/useImportType/valid-unused-react-types.options.json
crates/biome_js_analyze/tests/specs/style/useImportType/valid-unused-react-types.tsx
crates/biome_js_analyze/tests/specs/style/useImportType/valid-unused-react-types.tsx.snap
crates/biome_js_analyze/tests/specs/style/useImportType/valid-unused-react.options.json
crates/biome_js_analyze/tests/specs/style/useImportType/valid-unused-react.tsx
crates/biome_js_analyze/tests/specs/style/useImportType/valid-unused-react.tsx.snap
website/src/content/docs/internals/changelog.md
website/src/content/docs/linter/rules/use-import-type.md

Don't treat `React` as a type-only import when the `jsxRuntime` is set to `reactClassic`.
Fixes #2004.

fix(lint/useImportType): respect `jsxRuntime`

---

crates/biome_css_formatter/src/utils/component_value_list.rs
crates/biome_css_formatter/tests/specs/css/atrule/font_face.css.snap
crates/biome_css_formatter/tests/specs/css/declaration_list.css
crates/biome_css_formatter/tests/specs/css/declaration_list.css.snap
crates/biome_css_formatter/tests/specs/css/properties/all.css.snap
crates/biome_css_formatter/tests/specs/css/properties/border.css.snap
crates/biome_css_formatter/tests/specs/css/properties/custom.css.snap
crates/biome_css_formatter/tests/specs/css/properties/generic.css.snap
crates/biome_css_formatter/tests/specs/prettier/css/atrule/font-face.css.snap
crates/biome_css_formatter/tests/specs/prettier/css/comments/declaration.css.snap
crates/biome_css_formatter/tests/specs/prettier/css/fill-value/fill.css.snap
crates/biome_css_formatter/tests/specs/prettier/css/indent/indent.css.snap
crates/biome_css_formatter/tests/specs/prettier/css/modules/modules.css.snap
crates/biome_css_formatter/tests/specs/prettier/css/url/url.css.snap

Refactor CSS format handling in component value list
The 'format_with' function in 'component_value_list.rs' has been refactored to improve the handling of commas in CSS formatting. Before, it incorrectly added extra space or newlines before commas which disrupted the desired CSS formatting. The function has now been modified to check if current element is a comma before inserting a space or line break.
`cargo test -p biome_css_formatter`

feat(css_formatter): Incorrect spacing around `CssGenericDelimiter` elements.

---

CHANGELOG.md
crates/biome_js_parser/src/lexer/mod.rs
crates/biome_js_parser/src/lexer/tests.rs
website/src/content/docs/internals/changelog.md

Our parser wrongly assumed all `u32` sequences could be converted to valid Unicode characters, which led to issues as described here: https://github.com/biomejs/biome/issues/2384
This PR makes conversion from `u32` to `char` optional, since in many cases we don't care about the actual value of the escape sequence. And in situations where we do, we can bail as soon as the conversion fails.
Fixes https://github.com/biomejs/biome/issues/2384

fix(parser): fix Unicode surrogate char in escape sequence

---

CHANGELOG.md
crates/biome_cli/src/changed.rs
crates/biome_cli/src/commands/check.rs
crates/biome_cli/src/commands/format.rs
crates/biome_cli/src/commands/lint.rs
crates/biome_cli/src/commands/mod.rs
crates/biome_cli/src/lib.rs
crates/biome_cli/tests/commands/lint.rs
crates/biome_cli/tests/snapshots/main_commands_check/check_help.snap
crates/biome_cli/tests/snapshots/main_commands_format/format_help.snap
crates/biome_cli/tests/snapshots/main_commands_lint/lint_help.snap
crates/biome_cli/tests/snapshots/main_commands_lint/should_error_if_changed_flag_and_staged_flag_are_active_at_the_same_time.snap
crates/biome_cli/tests/snapshots/main_commands_lint/should_not_process_ignored_file_even_if_its_staged.snap
crates/biome_cli/tests/snapshots/main_commands_lint/should_only_process_staged_file_if_its_included.snap
crates/biome_cli/tests/snapshots/main_commands_lint/should_only_processes_staged_files_when_staged_flag_is_set.snap
crates/biome_fs/src/fs.rs
crates/biome_fs/src/fs/memory.rs
crates/biome_fs/src/fs/os.rs
website/src/content/docs/internals/changelog.md

This PR introduces a new `--staged` flag that allows `biome` to select only the files that are staged to be committed.
- Fixes #2296
- Related Discord discussion: https://discord.com/channels/1132231889290285117/1222450681919832134
There is some semblance with `--changed`, but its behaviour is different:
- `--changed` is useful to run certain checks in CI environment, selecting only the files that changed between two git "refs" (they can be explicit or implicit).
- In contrast, `--staged` is useful in local environments, to be used in git hooks such as `pre-commit`.
- I introduced new unit tests covering basic behaviour changes
- I tested the generated binary manually to verify that it works exactly as expected
What follows is for a very small repository.
Performance is slightly better …

feat(cli): add --staged flag

---

crates/biome_js_analyze/src/lint/nursery/no_re_export_all.rs
crates/biome_js_analyze/tests/specs/nursery/noReExportAll/valid.ts
crates/biome_js_analyze/tests/specs/nursery/noReExportAll/valid.ts.snap
website/src/content/docs/linter/rules/no-re-export-all.md

Don't report type re-export such as `export type * from "foo";`.
This aligns the behavior of `noReExportAll` to `noBarrelFile`.

refactor(noReExportAll): don't report type re-export

---

crates/biome_js_analyze/src/lint/style/use_for_of.rs
website/src/content/docs/linter/rules/use-for-of.md

Unintuitively, the documents for useForOf do not include an *actual* forOf. While the actual rule does check for the index accession shown in the documents already, it doesn't respect [the typescript-eslint rule](https://typescript-eslint.io/rules/prefer-for-of/#examples).
: )

docs: update useForOf to include a relevant example

---

crates/biome_cli/src/execute/migrate/eslint_eslint.rs
crates/biome_cli/src/execute/migrate/eslint_typescript.rs
crates/biome_cli/src/execute/migrate/prettier.rs
crates/biome_cli/tests/commands/migrate_eslint.rs
crates/biome_cli/tests/snapshots/main_commands_migrate_eslint/migrate_eslintrcjson_rule_options.snap

This PR adds the support for settings directly a string in `overrides.files`.
Also, I renamed `Shothand` to `ShothandVec` for clarity.
I changed a test to cover this case.

feat(migrate-prettier): support shorthand for overrides.files

---

CHANGELOG.md
crates/biome_js_analyze/src/lint/complexity/use_literal_keys.rs
crates/biome_js_analyze/tests/specs/complexity/useLiteralKeys/invalid.js
crates/biome_js_analyze/tests/specs/complexity/useLiteralKeys/invalid.js.snap
crates/biome_js_analyze/tests/specs/complexity/useLiteralKeys/valid.js
crates/biome_js_analyze/tests/specs/complexity/useLiteralKeys/valid.js.snap
website/src/content/docs/internals/changelog.md

Fix #2430
I took the opportunity of refactoring the implementation to use the utility `as_static_value`.

refactor(useLiteralKeys): ignore __proto__ computed property

---

crates/biome_cli/src/commands/init.rs
crates/biome_cli/tests/snapshots/main_commands_init/creates_config_file.snap
crates/biome_cli/tests/snapshots/main_commands_init/creates_config_file_when_biome_installed_via_package_manager.snap
crates/biome_cli/tests/snapshots/main_commands_init/creates_config_jsonc_file.snap

When `biome init` is executed the following message is printed:
```
❯ ./biome init
Welcome to Biome! Let's get you started...
Files created ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
- biome.json: Your project configuration. Documentation: https://biomejs.dev/reference/configuration
Next Steps ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
1. Setup an editor extension
Get live errors as you type and format when you save. Learn more: https://biomejs.dev/guides/getting-started#editor-setup
2. Try a command
biome check verifies formatting and lint. Run biome --help for a full list of commands and options.
3. Read the documentation
Our website serves as a …
```

docs: suggest biome migrate commands after biome init

---

crates/biome_configuration/src/generated.rs
crates/biome_configuration/src/linter/rules.rs
xtask/codegen/src/generate_configuration.rs

This PR replaces the fixed static arrays by static slice to reduce potential conflicts when rules are concurrently added.
I noticed that the size of the array is often the cause of a conflict.
By using slices, we no longer have this issues.

refactor(codegen): reduce Git conflicts using slices instead of arrays

---

CHANGELOG.md
crates/biome_cli/tests/cases/handle_vue_files.rs
crates/biome_cli/tests/snapshots/main_cases_handle_vue_files/format_vue_generic_component_files.snap
crates/biome_service/src/file_handlers/svelte.rs
crates/biome_service/src/file_handlers/vue.rs
website/src/content/docs/internals/changelog.md

Fix the regexes we use for script block detection in `.vue` and `.svelte` files to support generic components in `.vue` files.
Closes #2456.
Added a test case borrowed from #2456.

fix(analyzer): script block detection in `vue` and `svelte` files

---

crates/biome_cli/src/execute/migrate/eslint_any_rule_to_biome.rs
crates/biome_js_analyze/src/lint/performance/no_barrel_file.rs
website/src/content/docs/linter/rules-sources.mdx
website/src/content/docs/linter/rules/no-barrel-file.md

Fix the rule source of `noBarrelFile`
No change.

fix(lint/noBarrelFile): rule source

---

benchmark/package.json
benchmark/run.js

This PR follows up on https://github.com/biomejs/biome/pull/34 :)
Refactored [run.js](https://github.com/biomejs/biome/blob/main/benchmark/run.js) to utilize `import` statements, improving module handling and more.
Checked `run.js` with `biome` and checked bench with:
```
$ docker build --rm -f Dockerfile.benchmark . --progress plain
```

refactor(bench): update import statement and module handling in run.js

---

website/src/content/docs/guides/getting-started.mdx
website/src/content/docs/ja/guides/getting-started.mdx
website/src/content/docs/pt-br/guides/getting-started.mdx
website/src/content/docs/zh-cn/guides/getting-started.mdx

Fixed a missing "--apply" option in the lint command example in the "Usage" section of the "Getting Started" page.
N/A

fix: missing "--apply" option in the command example

---

Cargo.lock
Cargo.toml
crates/biome_cli/Cargo.toml
crates/biome_deserialize_macros/Cargo.toml
crates/biome_diagnostics_macros/Cargo.toml
crates/biome_formatter_test/Cargo.toml
crates/biome_markup/Cargo.toml
crates/biome_rowan/Cargo.toml
crates/biome_rowan/src/green/node_cache.rs
crates/biome_test_utils/Cargo.toml
crates/biome_text_edit/Cargo.toml
crates/tests_macros/Cargo.toml
fuzz/Cargo.toml
xtask/codegen/Cargo.toml
xtask/contributors/Cargo.toml
xtask/coverage/Cargo.toml

This PR removes a few duplicate crates around the codebase.
Also, it upgrades `hashbrown` to the latest, which has a breaking change. The new method `extract_if` doesn't `Drop` the elements anymore, so now the `drop` is implemented manually. 
The manual `drop` doesn't break a test that was failing on my machine.

chore: tidy up dependencies

---

.github/workflows/repository_dispatch.yml

Add repository dispatch workflow. This workflow is meant to trigger the [Pin submodule and run codegen workflow](https://github.com/biomejs/website/actions/workflows/pin-submodule-and-run-codegen.yaml) in [biomejs/website](https://github.com/biomejs/website) whenever a push event is issued from the main branch.
To trigger the workflow in another repository, this workflow needs a PAT ([Personal Access Token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens)) and stores it as a repository secret. I used the secrete name `BIOME_REPOSITORY_DISPATCH` in this workflow. Further details about the token permissions can be found here: https://github.com/peter-evans/repository-dispatch?tab=readme-ov-file#token
I suggest that we …

chore(ci): add repository dispatch workflow

---

CHANGELOG.md
crates/biome_js_analyze/src/lint/style/use_import_type.rs
crates/biome_js_analyze/tests/specs/style/useImportType/valid-unused-react-combined.options.json
crates/biome_js_analyze/tests/specs/style/useImportType/valid-unused-react-combined.tsx
crates/biome_js_analyze/tests/specs/style/useImportType/valid-unused-react-combined.tsx.snap
website/src/content/docs/internals/changelog.md

Fixes https://github.com/biomejs/biome/issues/2473

fix(lint/useImportType): `jsxRuntime` wasn't respected in combined import statement

---

crates/biome_cli/src/service/mod.rs
crates/biome_console/src/write/termcolor.rs
xtask/README.md
xtask/codegen/src/formatter.rs

chore: fix some typos in comments

---

.changeset/add_crate.md
.github/workflows/prepare_release.yml
Cargo.lock
crates/biome_html_parser/Cargo.toml
justfile
knope.toml
taplo.toml
xtask/codegen/src/generate_crate.rs

This PR does two things:
- it creates a knope workflow to **create a changeset** via the script `just new-changeset`. It present a prompt where users need choose the packages to update
- it creates a knope workflow **meant to be run in CI**. This workflow will create a PR that will prepare the release. If this PR is merged, then the real release will be triggered. 
- It adds a GitHub `prepare_release.yml` workflow that run the knope workflow `prepare-release`
> [!IMPORTANT]
> The release workflow isn't hooked with knope yet, so that PR won't do anything.
I will follow up with another PR to update our current release workflow only after we reach a stable stage where we can hold off on bug fixes.

chore: prepare knope

---

knope.toml

Variables aren't allowed in a multiple package context: https://knope.tech/reference/config-file/variables/#version
Merge it and see if that works

chore: remove variables from workflows

---

.github/renovate.json
Cargo.lock
crates/biome_rowan/Cargo.toml
crates/biome_rowan/src/green/node_cache.rs

This PR reverts `hashbrown`. The latest version is breaking the WASM distribution. 
We will look into this later, maybe by using `features`.
I also added `hashbrown` and `pulldown-cmark` to the ignored deps in renovate, because they contain breaking changes.
CI should pass

fix: reverts hashbrown, which causes issues when compiling to WASM

---

.cargo/config.toml
.github/workflows/pull_request.yml
crates/biome_analyze/src/rule.rs

Closes #2485
I also removed the website code generation check
The website will pick this up automatically

fix(linter): name of typescript-eslint

---

CHANGELOG.md
crates/biome_js_formatter/src/js/statements/return_statement.rs
crates/biome_js_formatter/tests/specs/js/module/statement/return.js
crates/biome_js_formatter/tests/specs/js/module/statement/return.js.snap
crates/biome_js_formatter/tests/specs/prettier/js/comments/return-statement.js
crates/biome_js_formatter/tests/specs/prettier/js/comments/return-statement.js.snap
website/src/content/docs/internals/changelog.md

Fix the following case
```js
// input
function f() {
return (
/*
* multiline comment 
*/ '1'
)
}
// before
function f() {
return /*
* multiline comment
*/ "1";
}
// after
// add parentheses for the return expression that has multiline leading comments
function f5() {
return (
/*
* multiline comment
*/ "1"
);
}
```
Add new test cases and enable the prettier test case that disabled before due to reformatting issue

fix(js_formatter): add parentheses for the return expression that has leading multiline comments.

---

crates/biome_graphql_parser/src/lexer/mod.rs
crates/biome_graphql_parser/src/parser/argument.rs
crates/biome_graphql_parser/src/parser/definitions/mod.rs
crates/biome_graphql_parser/src/parser/definitions/operation.rs
crates/biome_graphql_parser/src/parser/directive.rs
crates/biome_graphql_parser/src/parser/value.rs
crates/biome_graphql_parser/tests/graphql_test_suite/err/directive.graphql
crates/biome_graphql_parser/tests/graphql_test_suite/err/directive.graphql.snap
crates/biome_graphql_parser/tests/graphql_test_suite/err/operation.graphql
crates/biome_graphql_parser/tests/graphql_test_suite/err/operation.graphql.snap
crates/biome_graphql_parser/tests/graphql_test_suite/err/selection_set.graphql
crates/biome_graphql_parser/tests/graphql_test_suite/err/selection_set.graphql.snap
crates/biome_graphql_parser/tests/graphql_test_suite/err/type.graphql
crates/biome_graphql_parser/tests/graphql_test_suite/err/type.graphql.snap
crates/biome_graphql_parser/tests/graphql_test_suite/err/value.graphql
crates/biome_graphql_parser/tests/graphql_test_suite/err/value.graphql.snap
crates/biome_graphql_syntax/src/lib.rs

Handle parsing for operation in GraphQL parser
All the tests should pass

Handle operation parsing error GraphQL

---

.github/workflows/pull_request_title_lint.yaml
CONTRIBUTING.md

This PR adds a workflow for linting pr titles. It uses [amannn/action-semantic-pull-request](https://github.com/amannn/action-semantic-pull-request), used by some repositories ([Electron](https://github.com/electron/electron) · [Vite](https://github.com/vitejs/vite) · [Excalidraw](https://github.com/excalidraw/excalidraw) · [Apache](https://github.com/apache/pulsar) · [Vercel](https://github.com/vercel/ncc) · [Microsoft](https://github.com/microsoft/SynapseML) · [Firebase](https://github.com/firebase/flutterfire) · [AWS](https://github.com/aws-ia/terraform-aws-eks-blueprints)).
This is definition of each part (from [amannn/action-semantic-pull-request](https://github.com/amannn/action-semantic-pull-request)).
```
feat(ui): Add `Button` component
^    ^    ^
|    |    |__ Subject
| …
```

ci: add a workflow for linting pr titles

---

CHANGELOG.md
crates/biome_formatter/src/diagnostics.rs
crates/biome_lsp/src/diagnostics.rs
crates/biome_lsp/src/server.rs

This PR makes sure that all `WorkspaceError` are forwarded to the client, instead passing it to the main LSP handler, which ends up showing a bothering pop-up
Closes https://github.com/biomejs/biome/issues/2403
Manually tested that the pop-up doesn't appear anymore

fix(lsp): forward workspace errors to client console

---

crates/biome_js_analyze/src/lint/nursery/no_react_specific_props.rs

I missed this property cc @marvin-j97

fix(linter): add missing fix kind for solid rule

---

CHANGELOG.md
crates/biome_js_analyze/src/lint/nursery/no_misplaced_assertion.rs
crates/biome_js_analyze/tests/specs/nursery/noMisplacedAssertion/valid.js
crates/biome_js_analyze/tests/specs/nursery/noMisplacedAssertion/valid.js.snap
crates/biome_js_syntax/src/expr_ext.rs

Closes https://github.com/biomejs/biome/issues/2474

feat(linter): allow to call `expect` inside `waitFor`

---

crates/biome_analyze/CONTRIBUTING.md

SSIA
Just updated the  documentation

chore: added how to create new css lint rule

---

CHANGELOG.md
Cargo.toml
crates/biome_json_analyze/Cargo.toml
crates/biome_json_analyze/src/lib.rs
crates/biome_json_analyze/src/lint/nursery/no_duplicate_json_keys.rs
crates/biome_json_analyze/tests/specs/nursery/noDuplicateJsonKeys/invalid.json
crates/biome_json_analyze/tests/specs/nursery/noDuplicateJsonKeys/invalid.json.snap

Closes https://github.com/biomejs/biome/issues/2366
Verified that the new snapshot is correct.

fix(linter): correctly compute duplicate entries

---

crates/biome_css_formatter/src/css/auxiliary/declaration_block.rs
crates/biome_css_formatter/src/css/auxiliary/declaration_or_at_rule_block.rs
crates/biome_css_formatter/src/css/auxiliary/declaration_or_rule_block.rs
crates/biome_css_formatter/src/css/auxiliary/font_feature_values_block.rs
crates/biome_css_formatter/src/css/auxiliary/keyframes_block.rs
crates/biome_css_formatter/src/css/auxiliary/page_at_rule_block.rs
crates/biome_css_formatter/src/css/auxiliary/rule_block.rs
crates/biome_css_formatter/src/utils/block_like.rs

Reuse the same node union from https://github.com/biomejs/biome/pull/2513 to deduplicate the code.
CI

refactor(css_formatter): implement FormatCssBlockLike

---

crates/biome_configuration/src/linter/rules.rs
crates/biome_css_analyze/src/lint/nursery.rs
crates/biome_css_analyze/src/lint/nursery/no_duplicate_selectors_keyframe_block.rs
crates/biome_css_analyze/src/options.rs
crates/biome_css_analyze/tests/specs/nursery/noDuplicateSelectorsKeyframeBlock/invalid.css
crates/biome_css_analyze/tests/specs/nursery/noDuplicateSelectorsKeyframeBlock/invalid.css.snap
crates/biome_css_analyze/tests/specs/nursery/noDuplicateSelectorsKeyframeBlock/valid.css
crates/biome_css_analyze/tests/specs/nursery/noDuplicateSelectorsKeyframeBlock/valid.css.snap
crates/biome_diagnostics_categories/src/categories.rs
packages/@biomejs/backend-jsonrpc/src/workspace.ts
packages/@biomejs/biome/configuration_schema.json

this PR adds lint support to remove duplicate selector in keyframes block #2523
spec test

feat(biome_css_analyze): keyframe-block-no-duplicate-selectors

---

CONTRIBUTING.md
justfile

- actualized contributing guide;
- removed outdated `gen-web` command from `justfile`
Manually checked the changes.

docs: fixed path to crates, updated link to translating doc

---

CHANGELOG.md
crates/biome_js_formatter/src/js/statements/continue_statement.rs
crates/biome_js_formatter/tests/specs/js/module/statement/continue_stmt.js
crates/biome_js_formatter/tests/specs/js/module/statement/continue_stmt.js.snap

```js
// input
for (const f of fs) {
if (condition) continue; //commment
else continue; // comment
}
// before
for (const f of fs) {
if (condition)
continue;
//commment
else continue; // comment
}
// above code will be reformatted as 
for (const f of fs) {
if (condition) continue;
//commment
else continue; // comment
}
// after
for (const f of fs) {
if (condition)
continue; // commment
else continue; // comment
}
```
Add new test cases

fix(js_formatter): correctly format dangling comments of continue statement

---

crates/biome_graphql_parser/src/parser/definitions/fragment.rs
crates/biome_graphql_parser/src/parser/definitions/mod.rs
crates/biome_graphql_parser/src/parser/definitions/operation.rs
crates/biome_graphql_parser/tests/graphql_test_suite/err/definitions/fragment.graphql
crates/biome_graphql_parser/tests/graphql_test_suite/err/definitions/fragment.graphql.snap
crates/biome_graphql_parser/tests/graphql_test_suite/ok/definitions/fragment.graphql
crates/biome_graphql_parser/tests/graphql_test_suite/ok/definitions/fragment.graphql.snap
crates/biome_graphql_parser/tests/spec_tests.rs

Parse GraphQL fragment definition. This is a small case so I parse both the happy path and error path in this PR
All test should pass

feat(biome_graphql_parser): parse fragment definition

---

crates/biome_analyze/CONTRIBUTING.md

There are no `biome_deserializable_macros`.
I think the correct one is `biome_deserialize_macros`.
https://github.com/biomejs/biome/blob/3ef48c5a8ee4b8acdbe0b2eac9a3b89068d3d76c/crates/biome_deserialize_macros/Cargo.toml#L9

docs: fix typo in biome analyze contribution document

---

Cargo.lock
crates/biome_aria_metadata/Cargo.toml
crates/biome_aria_metadata/build.rs
xtask/codegen/Cargo.toml
xtask/codegen/src/generate_new_lintrule.rs
xtask/codegen/src/promote_rule.rs

Use `biome_string_case` instead of `case`.

build(deps): remove 'case' dependency

---

Cargo.lock
xtask/codegen/Cargo.toml
xtask/codegen/src/parser_tests.rs
xtask/codegen/src/promote_rule.rs

- Since Rust `.75, standard functions are available to update file times making `filetime` optional.
- `fs_extra` can easily be replaced with the standard library
I manually tested the codegen.

build(xstask): remove deps `fs_extra` and `filetime`

---

CHANGELOG.md
crates/biome_cli/tests/commands/check.rs
crates/biome_cli/tests/snapshots/main_commands_check/check_stdin_apply_unsafe_only_organize_imports.snap
crates/biome_cli/tests/snapshots/main_commands_check/check_stdin_apply_unsafe_successfully.snap
crates/biome_js_analyze/src/assists/correctness/organize_imports.rs
crates/biome_js_analyze/tests/specs/correctness/organizeImports/side-effect-imports.js
crates/biome_js_analyze/tests/specs/correctness/organizeImports/side-effect-imports.js.snap

Fix #817
Now every side effect import creates its own import group.

fix(organizeImport): ignorer side effect imports

---

packages/@biomejs/biome/configuration_schema.json

- previously MR: #2397 
- Property `jsxRuntime` is not allowed:  ![image](https://github.com/biomejs/biome/assets/28648715/36925872-6475-4b9c-908d-88c72eceb3c0)
- But terminal output told me need to use jsxRuntime ![image](https://github.com/biomejs/biome/assets/28648715/5de0a5fd-ab0a-4779-a384-9f8ef024cff0)
The schema for `jsxRuntime` is not match on the Doc or the prompt on terminal, so I decide to update to the correct definition.🙏

chore: update schema definition

---

crates/biome_configuration/src/javascript/mod.rs
packages/@biomejs/backend-jsonrpc/src/workspace.ts
packages/@biomejs/biome/configuration_schema.json

When I tried to enable the `useImportType` rule in the codebase I maintain at work, I found that `jsxRuntime` still uses `snake_case` in the configuration schema.
just gen-bindings

fix(configuration_schema): rename some fields to camelCase in the `configuration_schema.json`

---

CHANGELOG.md
crates/biome_js_formatter/src/comments.rs
crates/biome_js_formatter/tests/specs/js/module/import/named_import_clause.js
crates/biome_js_formatter/tests/specs/js/module/import/named_import_clause.js.snap

FIx formatting of following case. It's strange that the export declaration doesn't have such an issue.
```js
// input
import {} from /* comment*/ 'foo'
import {} from // comment
'foo'
import {a} from /* comment */'foo'
import {a} from // comment
'foo'
// before
import {} from /* comment*/ "foo";
import {} from "foo"; // comment
import { a } from /* comment */ "foo";
import { a } from "foo";
// after
import {} from /* comment*/ "foo";
import {} from // comment
"foo";
import { a } from /* comment */ "foo";
import {
a, // comment
} from "foo";
```
Add new test cases

fix(js_formatter): correctly handle placement of comments inside named import clause

---

CHANGELOG.md
crates/biome_cli/src/execute/migrate/node.rs

Some plugins and configurations export objects with cyclic references.
This causes `biome migrate eslint` to fail or ignore them.
These edge cases are now handled correctly.
To do that, we detect cyclic references when we serialize the object.
I manually tested using the [ESLint config of the Astro repository](https://github.com/withastro/astro/blob/main/eslint.config.js).
NOTE: We should find a way of writing tests because I am a bit uncomfortable of having so much untested code.

fix(migrate-eslint): handle cyclic references

---

CHANGELOG.md
crates/biome_cli/tests/snapshots/main_commands_ci/ci_runs_linter_not_formatter_issue_3495.snap
crates/biome_cli/tests/snapshots/main_commands_ci/correctly_handles_ignored_and_not_ignored_files.snap
crates/biome_cli/tests/snapshots/main_commands_lint/include_files_in_subdir.snap
crates/biome_cli/tests/snapshots/main_commands_lint/include_files_in_symlinked_subdir.snap
crates/biome_configuration/src/linter/rules.rs
crates/biome_js_analyze/src/lint/style/use_const.rs
crates/biome_js_analyze/tests/specs/style/useConst/invalid.jsonc.snap
crates/biome_js_analyze/tests/specs/style/useConst/valid.jsonc
crates/biome_js_analyze/tests/specs/style/useConst/valid.jsonc.snap
justfile
packages/@biomejs/backend-jsonrpc/src/workspace.ts
packages/@biomejs/biome/configuration_schema.json

Fix #2575
I also took the opportunity of fixing an issue I discovered when reading the code:
The rule should not report an implicitly initialized variable that is read before its assignment.
The following example was previously reported:
```js
let a;
a;
a = 0;
```
I added 3 tests and updated the snapshots.

fix(lint/useConst): handle reads before assignment and improve docs

---

CHANGELOG.md
crates/biome_js_analyze/tests/specs/style/useTemplate/invalidIssue2580.js
crates/biome_js_analyze/tests/specs/style/useTemplate/invalidIssue2580.js.snap
crates/biome_js_factory/src/utils.rs

Fix #2580
I fixed the escape utility and improved its implementation. 

fix(lint/useTemplate): correctly escape characters

---

CHANGELOG.md
crates/biome_js_analyze/src/lint/style/use_shorthand_function_type.rs
crates/biome_js_analyze/tests/specs/style/useShorthandFunctionType/invalid.ts
crates/biome_js_analyze/tests/specs/style/useShorthandFunctionType/invalid.ts.snap

Fix #2595
Previously, the rule didn't add parentheses when they were needed.
It now adds parentheses when the function signature is inside an array, a union, or an intersection.
```diff
- type Union = { (): number } | string;
+ type Union = (() => number) | string;
```
Note: we should move the needs_parens utility from `biome_js_formatter` to `biome_js_syntax`.
It is not the first time we encounter this need.
Another possibility is to format the code fix with the formatter.
However, it is not actually possible?
I added non-regression tests.

fix(lint/useShorthandFunctionType): add parens when needed

---

crates/biome_formatter_test/src/spec.rs
crates/biome_service/tests/workspace.rs
packages/@biomejs/backend-jsonrpc/tests/workspace.test.mjs

Fixes a regression introduced by me in https://github.com/biomejs/biome/pull/2589
Tested locally

fix: regression of latest refactor

---

CHANGELOG.md
crates/biome_js_analyze/src/assists/correctness/organize_imports.rs
crates/biome_js_analyze/tests/specs/correctness/organizeImports/space.ts
crates/biome_js_analyze/tests/specs/correctness/organizeImports/space.ts.snap

Fix #1665
I added a non-regression test

fix(organizeImports): add space where needed

---

crates/biome_js_analyze/src/lint/a11y/no_redundant_alt.rs

fix(lint/noRedundantAlt): rule source

---

CHANGELOG.md
crates/biome_js_analyze/src/lint/suspicious/no_redeclare.rs
crates/biome_js_analyze/tests/specs/suspicious/noRedeclare/invalid.jsonc.snap
crates/biome_js_analyze/tests/specs/suspicious/noRedeclare/invalid.ts
crates/biome_js_analyze/tests/specs/suspicious/noRedeclare/invalid.ts.snap
crates/biome_js_analyze/tests/specs/suspicious/noRedeclare/valid-declaration-merging.ts
crates/biome_js_analyze/tests/specs/suspicious/noRedeclare/valid-declaration-merging.ts.snap
crates/biome_js_semantic/src/events.rs
crates/biome_js_semantic/src/semantic_model/builder.rs
crates/biome_js_syntax/src/binding_ext.rs

Fix #2608
Fix #2394
Fix #2372
I added a non-regression test for each issue.

fix(lint/noRedeclare): handle function and call overloads

---

CHANGELOG.md
crates/biome_js_analyze/tests/specs/correctness/noUnusedVariables/unusedInferBogusConditional.ts
crates/biome_js_analyze/tests/specs/correctness/noUnusedVariables/unusedInferBogusConditional.ts.snap
crates/biome_js_semantic/src/events.rs

Fix #1695
Our semantic model defers the binding of `infer T` once the scope of the true branch of a conditional type is defined.
However, we miss an edge case: when the true branch is absent, `infer T` is never bound.
This leads to the error observed in #1695, where `noUnusedVariables` tries to obtain the undefined binding of `infer T`.
To solve the issue I added a fallback: if the true branch is absent, we bind the `infer` declarations in the scope of the conditional type.
I added a non-regression test.

fix(js_semantic_model): handle bogus conditional type

---

crates/biome_deserialize/src/impls.rs
crates/biome_deserialize/src/merge.rs
crates/biome_deserialize_macros/src/deserializable_derive.rs
crates/biome_deserialize_macros/src/merge_derive.rs
crates/biome_deserialize_macros/src/partial_derive.rs

A few days ago, while working on #1859, I found some possible simplification.
Because, I am no longer sure that #1859 is a good idea, I decided to extract the main simplifications in this PR.
The idea is to implement `Deserializable` for `Option`.
This allows to remove specific handling of `Option` in the `Deserializable` derive macro.
I also simplified the `Merge` derive macro, which was more complex than it needed to be.
I also removed the implementations that allow an instance to be converted to a partial instance.
It is never used and has a conceptual flaw: it assumes that a field is unset with its default value.

refactor(deserialize): don't handle Option specifically

---

crates/biome_analyze/src/matcher.rs
crates/biome_js_analyze/src/ast_utils.rs
crates/biome_js_analyze/src/lint/style/use_consistent_array_type.rs
crates/biome_js_analyze/src/lint/style/use_shorthand_array_type.rs
crates/biome_js_factory/src/make.rs
crates/biome_rowan/src/cursor/trivia.rs

Replace instances of `TriviaPiece::new(TriviaPieceKind::whitespace, 1)` with `TriviaPiece::whitespace(1)`.
Please feel free to close this PR if the changes like these are not warranted.
No functionality changes

refactor: use TriviaPiece factory functions in more places

---

CHANGELOG.md
crates/biome_js_analyze/tests/specs/correctness/noUndeclaredVariables/thisInJsx.jsx
crates/biome_js_analyze/tests/specs/correctness/noUndeclaredVariables/thisInJsx.jsx.snap
crates/biome_js_parser/src/syntax/jsx/mod.rs

I've tried to write a fix for https://github.com/biomejs/biome/issues/2636. I'm not really sure if my code is correct but it seems to pass the tests.
I've added a regression test.

fix: `noUndeclaredVariables` no longer errors on `this` in JSX tags

---

CHANGELOG.md
crates/biome_js_analyze/tests/specs/correctness/noUndeclaredVariables/validExportDefaultInAmbientModule.ts
crates/biome_js_analyze/tests/specs/correctness/noUndeclaredVariables/validExportDefaultInAmbientModule.ts.snap
crates/biome_js_semantic/src/events.rs

Fix #2637
When the semantic model finds an export it issues two references: a value reference and a type reference.
Only one reference get resolved when the referenced entity is only a variable (value) or only a type.
The remaining reference is forwarded to the parent scope and eventually marked as unresolved.
This is an erroneous behavior for two reasons:
1. An `export` cannot export a variable/type declared in a parent scope.
2. An `export` doesn't need to export both a variable and a type.
When we discover an `export` that exports a type or a variable, we no longer forward and mark as unresolved the dual variable/type.

fix(lint/noUndeclaredVariables): don't report variable-only/type-only exports

---

crates/biome_js_analyze/src/lint/nursery/no_useless_undefined_initialization.rs

[A snippet must emit **only ONE** diagnostic.](https://github.com/biomejs/biome/blob/main/crates/biome_analyze/CONTRIBUTING.md#:~:text=A%20snippet%20must%20emit%20only%20ONE%20diagnostic.)
https://github.com/biomejs/biome/blob/8f9c14a275d712c3f8a7de384c00bf507f410acf/crates/biome_analyze/CONTRIBUTING.md?plain=1#L183
-

fix(snippet): should emit only one diagnostic

---

Cargo.lock
Cargo.toml
crates/biome_grit_patterns/Cargo.toml
crates/biome_grit_patterns/src/grit_binding.rs
crates/biome_grit_patterns/src/grit_code_snippet.rs
crates/biome_grit_patterns/src/grit_context.rs
crates/biome_grit_patterns/src/grit_file.rs
crates/biome_grit_patterns/src/grit_language.rs
crates/biome_grit_patterns/src/grit_node.rs
crates/biome_grit_patterns/src/grit_node_patterns.rs
crates/biome_grit_patterns/src/grit_tree.rs
crates/biome_grit_patterns/src/lib.rs
crates/biome_grit_patterns/src/parse.rs
crates/biome_grit_patterns/src/pattern.rs
crates/biome_grit_patterns/src/resolved_pattern.rs
crates/biome_service/Cargo.toml

This PR implements the basic infrastructure on top of which to implement the bindings for the Grit engine. All implementations are merely `todo!()` so far, so this doesn't really do anything, but it gives an idea where the work will happen :)
Lays the foundation for work on https://github.com/biomejs/biome/issues/2582.
Note the Grit crate dependencies still point to my own fork, since the PR hasn't been merged yet. I'll wait with merging this one until the upstream PR is merged first.

chore: add infrastructure for Grit engine

---

crates/biome_rowan/src/ast/batch.rs

Fix typos in biome_rowan batch mutation trait description
None

docs: fix typos in biome_rowan batch mutation

---

CHANGELOG.md
crates/biome_js_analyze/src/lint/nursery/no_misplaced_assertion.rs
crates/biome_js_analyze/tests/specs/nursery/noMisplacedAssertion/valid.js
crates/biome_js_analyze/tests/specs/nursery/noMisplacedAssertion/valid.js.snap

- Close https://github.com/biomejs/biome/issues/2547
> [!NOTE]
> I have some troubles with `cargo format` in `just gen-lint`.
<details>
<summary>Occurred error</summary>
```
biome on  fix-lint-no-misplaced_assertion via  v20.12.1 via 🦀 v1.77.2 
❯ cargo format
[lib (2021)] "/path-to-biome/biome/crates/biome_analyze/src/lib.rs"
[lib (2021)] "/path-to-biome/biome/crates/biome_aria/src/lib.rs"
[custom-build (2021)] "/path-to-biome/biome/crates/biome_aria_metadata/build.rs"
[lib (2021)] "/path-to-biome/biome/crates/biome_aria_metadata/src/lib.rs"
[example (2021)] "/path-to-biome/biome/crates/biome_cli/examples/text_reporter.rs"
[lib (2021)] "/path-to-biome/biome/crates/biome_cli/src/lib.rs"
[bin (2021)] "/path-to-biome/biome/crates/biome_cli/src/main.rs"
[test (2021)] …
```

fix(lint): rule `noMisplacedAssertion`

---

.github/workflows/pull_request_title_lint.yaml
CONTRIBUTING.md

Accept `revert:` as PR type.
CI must pass

ci: accept prefix 'revert:' in PR titles

---

Cargo.lock
Cargo.toml
crates/biome_aria_metadata/Cargo.toml
crates/biome_cli/Cargo.toml
crates/biome_console/Cargo.toml
crates/biome_diagnostics/Cargo.toml
crates/biome_formatter/Cargo.toml
crates/biome_formatter_test/Cargo.toml
crates/biome_fs/Cargo.toml
crates/biome_grit_syntax/Cargo.toml
crates/biome_js_analyze/Cargo.toml
crates/biome_js_formatter/Cargo.toml
crates/biome_js_parser/Cargo.toml
crates/biome_js_semantic/Cargo.toml
crates/biome_lsp/Cargo.toml
crates/biome_rowan/Cargo.toml
crates/biome_rowan/src/arc.rs
crates/biome_test_utils/Cargo.toml
crates/tests_macros/Cargo.toml
xtask/bench/Cargo.toml
xtask/codegen/Cargo.toml
xtask/contributors/Cargo.toml
xtask/coverage/Cargo.toml
xtask/libs_bench/Cargo.toml

Attempt of extracting the deps update from #2641 that don't make Ci fail.
I also removed `memoffset` because `offset_of!` is now stable since Rust 1.77.
And I factorized some deps at workspace level.
CI must pass.

build(deps): update

---

crates/biome_graphql_parser/src/parser/argument.rs
crates/biome_graphql_parser/src/parser/definitions/mod.rs
crates/biome_graphql_parser/src/parser/definitions/operation.rs
crates/biome_graphql_parser/src/parser/definitions/schema.rs
crates/biome_graphql_parser/src/parser/mod.rs
crates/biome_graphql_parser/src/parser/parse_error.rs
crates/biome_graphql_parser/src/parser/value.rs
crates/biome_graphql_parser/src/token_source.rs
crates/biome_graphql_parser/tests/graphql_test_suite/err/definitions/schema.graphql
crates/biome_graphql_parser/tests/graphql_test_suite/err/definitions/schema.graphql.snap
crates/biome_graphql_parser/tests/graphql_test_suite/ok/definitions/schema.graphql
crates/biome_graphql_parser/tests/graphql_test_suite/ok/definitions/schema.graphql.snap

Parse GraphQL schema definition. This is a small case so I parse both the happy path and error path in this PR

feat(biome_graphql_parser): parse schema definition

---

CHANGELOG.md
crates/biome_js_analyze/tests/specs/suspicious/noRedeclare/valid-conditional-type.ts
crates/biome_js_analyze/tests/specs/suspicious/noRedeclare/valid-conditional-type.ts.snap
crates/biome_js_semantic/src/semantic_model/builder.rs

Fix #2394
This is a regression introduced by #2394.
This regression makes `noRedeclare` panics on every conditional types with `infer` bindings.
`noRedeclare` checks the node type of every scope.
Prior to #2615, it was unlikely to retrieve the syntax node of a scope.
The semantic model builder missed many associations. I thought I added all missing associations in #2615.
However, I forgot a case: syntax node of the scope of a conditional true type.
This led to #2394.

fix(lint/noRedeclare): don't panic on conditional types

---

.github/renovate.json

Update the renovate configuration to pin third-party github actions to commit digests corresponding to their semantic versions.
This addresses https://github.com/biomejs/biome/pull/2634#issuecomment-2082536510
N/A

chore(ci): renovate pin GA to semver

---

Cargo.lock
Cargo.toml
crates/biome_deserialize/src/string_set.rs
crates/biome_formatter/src/printed_tokens.rs

Upgrade `indexmap` to 2.x
Only `schemars` (a dev dependency) requires indexmap 1.x.
Thus, we can upgrade to indexmap 2.x
I also enabled the `serde` feature of `indexmap to remove our custom serde implementations.
Unfortunately, we cannot remove `STringSet` because schemars don't provide schemas for indexmap 2.x
It seems that we use `IndexMap` in cases where we could use a `HashSet` or a sorted `Vec`.
A future PR should investigate some possible implications / perf improvements.
CI must pass.

build(deps): upgrade indexmap crate

---

crates/biome_graphql_parser/src/lexer/mod.rs
crates/biome_graphql_parser/src/parser/definitions/operation.rs
crates/biome_graphql_parser/src/parser/definitions/schema.rs
crates/biome_graphql_parser/src/parser/mod.rs
crates/biome_graphql_parser/src/parser/value.rs
crates/biome_graphql_parser/src/token_source.rs

By implementing NthAt for GraphqlLexer, we can utilize more sophisticated checks for Graphql parser
All tests should pass.

feat(biome_graphql_parser): implement NthAt for GraphqlLexer

---

Cargo.toml
crates/biome_analyze/src/options.rs
crates/biome_aria/src/roles.rs
crates/biome_cli/src/execute/diagnostics.rs
crates/biome_cli/src/execute/traverse.rs
crates/biome_css_formatter/tests/prettier_tests.rs
crates/biome_formatter/src/comments/map.rs
crates/biome_formatter/src/printer/call_stack.rs
crates/biome_formatter/src/printer/queue.rs
crates/biome_formatter/src/printer/stack.rs
crates/biome_js_analyze/src/lint/nursery/use_sorted_classes/class_info.rs
crates/biome_js_parser/src/span.rs
crates/biome_js_semantic/src/events.rs
crates/biome_js_semantic/src/tests/assertions.rs
crates/biome_json_formatter/src/lib.rs
crates/biome_json_formatter/tests/prettier_tests.rs
crates/biome_rowan/src/ast/mod.rs
crates/biome_service/src/file_handlers/astro.rs
crates/biome_service/src/file_handlers/css.rs
crates/biome_service/src/file_handlers/javascript.rs
crates/biome_service/src/file_handlers/json.rs
crates/biome_service/src/file_handlers/mod.rs
crates/biome_service/src/file_handlers/svelte.rs
crates/biome_service/src/file_handlers/unknown.rs
crates/biome_service/src/file_handlers/vue.rs
rust-toolchain.toml

The compiler and clippy got better and I had to remove a bunch of unused code. However, there are some false positives (the empty_docs in biome_wasm) and things to review around the `FormatInto` inside the JSON formatter: weirdly, the trait isn't flagged inside other crates.
CI should pass

chore: upgrade to rust 1.78

---

CHANGELOG.md
crates/biome_js_analyze/src/lint/style/use_export_type.rs
crates/biome_js_analyze/tests/specs/style/useExportType/invalid.ts
crates/biome_js_analyze/tests/specs/style/useExportType/invalid.ts.snap

Fix #2685
I took the opportunity of renaming some types to align with `useImportType`.
I added a non regression test.

fix(lint/useExportType): preserve leading comments

---

CHANGELOG.md
crates/biome_js_analyze/src/lint/a11y/no_blank_target.rs
crates/biome_js_analyze/src/lint/complexity/no_useless_fragments.rs
crates/biome_js_analyze/tests/specs/a11y/noBlankTarget/invalid.jsx.snap

Fix #2675
The code fix created a JSX string with a `JSX_IDENT` token.
`inner_string_text` is called to retrieve the content of the attribute.
`inner_string_text` removes quotes only when the token is a `JSX_STRING_LITERAL`.
Thus, on first run, the quotes were well removed, while on the following run, the quotes are not removed.
This led to a never fixed lint rule and thus, an infinite loop. 
I also fixed a similar issue for `noUselessFragments` which was not observed yet.
To avoid this kind of issue we could:
- Add `debug_assert` in node factories (this should be generated by the grammar) to guarantee that every leaf node has the correct token kind.
- Avoid the infinite loop by setting a limit. We can expect to have some conflicting rules in the future.
We should ensure that this doesn't …

fix(lint/noBlankTarget): don't hang when applying the code fix

---

crates/biome_graphql_parser/src/parser/definitions/field.rs
crates/biome_graphql_parser/src/parser/definitions/interface.rs
crates/biome_graphql_parser/src/parser/definitions/mod.rs
crates/biome_graphql_parser/src/parser/definitions/object.rs
crates/biome_graphql_parser/src/parser/definitions/operation.rs
crates/biome_graphql_parser/src/parser/parse_error.rs
crates/biome_graphql_parser/src/parser/value.rs
crates/biome_graphql_parser/tests/graphql_test_suite/err/definitions/object.graphql
crates/biome_graphql_parser/tests/graphql_test_suite/err/definitions/object.graphql.snap
crates/biome_graphql_parser/tests/graphql_test_suite/ok/definitions/object.graphql
crates/biome_graphql_parser/tests/graphql_test_suite/ok/definitions/object.graphql.snap

Parse GraphQL object type definition ([link](https://spec.graphql.org/October2021/#ObjectTypeDefinition)). I parse both the happy path and the error path in this PR.

feat: parse object type definition

---

crates/biome_grit_patterns/src/grit_node.rs

Implements the bindings for basic AST nodes.
Represents a little more progress towards https://github.com/biomejs/biome/issues/2582.
None yet.

chore: implement Grit node bindings

---

crates/biome_js_analyze/src/lint/suspicious/no_fallthrough_switch_clause.rs

Closes https://github.com/biomejs/website/issues/49
Proof read

docs: add small note about `process.exit`

---

crates/biome_js_analyze/src/lint/correctness/use_jsx_key_in_iterable.rs
crates/biome_js_analyze/tests/specs/correctness/useJsxKeyInIterable/invalid.jsx.snap
crates/biome_js_analyze/tests/specs/correctness/useJsxKeyInIterable/valid.jsx
crates/biome_js_analyze/tests/specs/correctness/useJsxKeyInIterable/valid.jsx.snap

This aims to resolve some of the bugs in #2590. It's intentionally small in scope since this is my first PR here, so hopefully it will be easier to review.
It fixes cases where expressions like this would erroneously trigger the `useJsxKeyInIterable` lint:
```jsx
<>{data.reduce((total, next) => total + next, 0)}</>
```
related to: #2590
I added tests.
```bash
cargo test -p biome_js_analyze use_jsx_key_in_iterable
```

fix(lint/useJsxKeyInIterable): don't trigger `useJsxKeyInIterable` when iterating on non-jsx things

---

crates/biome_css_analyze/src/lint/nursery/no_duplicate_at_import_rules.rs
crates/biome_css_analyze/tests/specs/nursery/noDuplicateAtImportRules/invalidQuotes.css
crates/biome_css_analyze/tests/specs/nursery/noDuplicateAtImportRules/invalidQuotes.css.snap

While checking different rules, I noticed that I forgot to check for a specific case when implementing the `noDuplicateAtImportRules` rule.
```css
@import "a.css";
@import 'a.css';
```
This should show an error, but didn't. 
This PR fixes this small bug and also adds a test for this scenario
Added a new test to validate the change.

fix(lint/noDuplicateAtImportRules): correctly handle both single- and double quotes

---

crates/biome_graphql_parser/src/parser/definitions/interface.rs
crates/biome_graphql_parser/src/parser/definitions/mod.rs
crates/biome_graphql_parser/tests/graphql_test_suite/err/definitions/interface.graphql
crates/biome_graphql_parser/tests/graphql_test_suite/err/definitions/interface.graphql.snap
crates/biome_graphql_parser/tests/graphql_test_suite/ok/definitions/interface.graphql
crates/biome_graphql_parser/tests/graphql_test_suite/ok/definitions/interface.graphql.snap

Parse Graphql Interface Type Definition ([link](https://spec.graphql.org/October2021/#InterfaceTypeDefinition)). Interface Type Definition is almost similar to Object Type Definition, with the only difference being the use of the `interface` keyword instead of `type`. As a result, the tests and implementation also share some similarities.

feat(biome_graphql_parser): parse interface type definition

---

crates/biome_configuration/src/linter/rules.rs
crates/biome_css_analyze/src/lint/nursery.rs
crates/biome_css_analyze/src/lint/nursery/no_unmatchable_anb_selector.rs
crates/biome_css_analyze/src/options.rs
crates/biome_css_analyze/tests/specs/nursery/noUnmatchableAnbSelector/invalid.css
crates/biome_css_analyze/tests/specs/nursery/noUnmatchableAnbSelector/invalid.css.snap
crates/biome_css_analyze/tests/specs/nursery/noUnmatchableAnbSelector/valid.css
crates/biome_css_analyze/tests/specs/nursery/noUnmatchableAnbSelector/valid.css.snap
crates/biome_diagnostics_categories/src/categories.rs
packages/@biomejs/backend-jsonrpc/src/workspace.ts
packages/@biomejs/biome/configuration_schema.json

close #2524 
added tests and snapshots

feat(linter): implement `NoUnmatchableAnbSelector`

---

CHANGELOG.md
crates/biome_cli/src/execute/migrate/eslint.rs

Fix #2705
I manually tested the fix.
It is currently not possible to write a test because we rely on node.js

fix(migrate-eslint): correctly resolve shared config @scope/eslint-config

---

CHANGELOG.md
crates/biome_js_analyze/src/lint/correctness/no_unused_labels.rs
crates/biome_js_analyze/src/lint/suspicious/no_confusing_labels.rs
crates/biome_js_analyze/tests/spec_tests.rs
crates/biome_js_analyze/tests/specs/correctness/noUnusedLabels/invalid.js
crates/biome_js_analyze/tests/specs/correctness/noUnusedLabels/invalid.js.snap
crates/biome_js_analyze/tests/specs/correctness/noUnusedLabels/valid.svelte
crates/biome_js_analyze/tests/specs/correctness/noUnusedLabels/valid.svelte.snap
crates/biome_js_analyze/tests/specs/suspicious/noConfusingLabels/invalid.jsonc
crates/biome_js_analyze/tests/specs/suspicious/noConfusingLabels/invalid.jsonc.snap
crates/biome_js_analyze/tests/specs/suspicious/noConfusingLabels/valid.svelte
crates/biome_js_analyze/tests/specs/suspicious/noConfusingLabels/valid.svelte.snap

Fix #2571
We now ignore the use of labels named `$` in Svelte components for the `noUnusedLabels` and `noCOnfusingLabels` rules.
I added tests for each rule.

fix(noUnusedLabels,noConfusingLabels): ignore Svelte reactive statements

---

crates/biome_js_analyze/src/lint/correctness/use_jsx_key_in_iterable.rs
crates/biome_js_analyze/tests/specs/correctness/useJsxKeyInIterable/invalid.jsx.snap
crates/biome_js_analyze/tests/specs/correctness/useJsxKeyInIterable/valid.jsx
crates/biome_js_analyze/tests/specs/correctness/useJsxKeyInIterable/valid.jsx.snap

This is a continuation of #2667, and as such fixes somethings related to #2590.
Specifically, it handles ternaries in expressions like this:
```jsx
<>{data.map(a => a > 4 ? <h1 key={a}>{a}</h1> : <h2 key={a}>{a}</h2>)}</>
```
related to: #2590
fixes #2468
Added tests.
```bash
cargo test -p biome_js_analyze use_jsx_key_in_iterable
```

fix(lint/useJsxKeyInIterable): handle ternaries properly

---

crates/biome_js_analyze/src/lint/nursery/use_explicit_length_check.rs

The doc of this rule is [failing the codegen script in the website repo](https://github.com/biomejs/website/actions/workflows/pin-submodule-and-run-codegen.yaml). This PR fixes it.
Tested locally.

fix(useExplicitLengthCheck): docs

---

CHANGELOG.md
Cargo.lock
crates/biome_configuration/src/lib.rs
crates/biome_lsp/Cargo.toml
crates/biome_lsp/src/handlers/text_document.rs
crates/biome_lsp/src/server.rs
crates/biome_lsp/src/session.rs
crates/biome_lsp/src/utils.rs
crates/biome_lsp/tests/server.rs
crates/biome_service/src/configuration.rs
crates/biome_service/src/settings.rs
crates/biome_service/src/workspace.rs
crates/biome_service/src/workspace/client.rs
crates/biome_service/src/workspace/server.rs

Closes #1573 
This PR adds support for LSP workspaces to Biome LSP. Our internal implementation of `ServerWorkspace` will keep track of the different workspaces registered by the user. 
The Biome LSP now listens to `did_change_workspace_folders`, which is triggered when a user changes (adds and/or removes) workspace folders.
We will need to update our documentation, and explain that providing a `--config-path` will remove the support of that via LSP. Essentially, users can't have both.
I added a new test and tested manually

feat(lsp): workspaces

---

crates/biome_css_parser/src/lexer/mod.rs
crates/biome_css_parser/src/token_source.rs
crates/biome_css_parser/tests/spec_test.rs
crates/biome_css_syntax/src/lib.rs
crates/biome_graphql_parser/src/lexer/mod.rs
crates/biome_graphql_parser/src/token_source.rs
crates/biome_graphql_syntax/src/lib.rs
crates/biome_grit_parser/src/lexer/mod.rs
crates/biome_grit_syntax/src/lib.rs
crates/biome_html_parser/src/lexer/mod.rs
crates/biome_html_parser/src/token_source.rs
crates/biome_html_syntax/src/lib.rs
crates/biome_js_parser/src/lexer/mod.rs
crates/biome_js_parser/src/lexer/tests.rs
crates/biome_js_parser/src/token_source.rs
crates/biome_js_syntax/src/lib.rs
crates/biome_json_syntax/src/lib.rs
crates/biome_parser/CONTRIBUTING.md
crates/biome_parser/src/lexer.rs
crates/biome_parser/src/lib.rs
crates/biome_parser/src/token_source.rs
crates/biome_rowan/src/raw_language.rs
crates/biome_rowan/src/syntax.rs
crates/biome_yaml_syntax/src/lib.rs

We have code duplication around the non-trivia lookahead in our parser. The MR attempts to extract the common parts into the parser crate. Basically, we have a `non_trivia_lookahead` vector for each token source. We can try to move them inside the current lookahead in the buffered lexer, because we are interested only in non-trivia lookahead.
`cargo test`

refactor(parser): implement NthToken for T

---

CHANGELOG.md
crates/biome_js_analyze/src/lint/style/use_single_case_statement.rs
crates/biome_js_analyze/tests/specs/style/useSingleCaseStatement/valid.js
crates/biome_js_analyze/tests/specs/style/useSingleCaseStatement/valid.js.snap

The intent behind the `useSingleCaseStatement` lint is that it's supposed to enforce performing only one action or operation per switch clause. `break` statements don't really fall into this category, and they are commonly used in switch statements to prevent fallthroughs.
fixes #2696
Added snapshot tests
```bash
cargo test -p biome_js_analyze use_single_case_statement
```

fix(lint/useSingleCaseStatement): ignore `break` statements

---

crates/biome_graphql_parser/src/parser/definitions/mod.rs
crates/biome_graphql_parser/src/parser/definitions/union.rs
crates/biome_graphql_parser/tests/graphql_test_suite/err/union.graphql
crates/biome_graphql_parser/tests/graphql_test_suite/err/union.graphql.snap
crates/biome_graphql_parser/tests/graphql_test_suite/ok/definitions/union.graphql
crates/biome_graphql_parser/tests/graphql_test_suite/ok/definitions/union.graphql.snap

Parse Graphql Union Type definition ([link](https://spec.graphql.org/October2021/#UnionTypeDefinition)). This is a small case so I included both the happy path parsing and the error handling.

feat(biome_graphql_parser): parse union type definition

---

crates/biome_graphql_parser/src/parser/definitions/enum.rs
crates/biome_graphql_parser/src/parser/definitions/mod.rs
crates/biome_graphql_parser/src/parser/value.rs
crates/biome_graphql_parser/tests/graphql_test_suite/err/definitions/enum.graphql
crates/biome_graphql_parser/tests/graphql_test_suite/err/definitions/enum.graphql.snap
crates/biome_graphql_parser/tests/graphql_test_suite/ok/definitions/enum.graphql
crates/biome_graphql_parser/tests/graphql_test_suite/ok/definitions/enum.graphql.snap

Parse Graphql Enum type definition ([link](https://spec.graphql.org/October2021/#sec-Enums)). This is a small case so this PR handle both the happy path and the error one.
All test should pass

feat(biome_graphql_parser): parse enum type definition

---

Cargo.lock
xtask/bench/Cargo.toml
xtask/bench/benches/analyzer-libs-css.txt
xtask/bench/benches/css_analyzer.rs
xtask/bench/benches/js_analyzer.rs
xtask/bench/src/language.rs

This PR adds the CSS analyzer to the list of our benchmarks.
It uses the same CSS files we use for formatting and parsing.
CI should pass

feat(bench): add CSS analyzer to the benchmarks

---

.changeset/new_clean_command.md
crates/biome_cli/src/commands/clean.rs
crates/biome_cli/src/commands/mod.rs
crates/biome_cli/src/commands/rage.rs
crates/biome_cli/src/lib.rs

Closes https://github.com/biomejs/biome/issues/1450
I tested it locally

feat(cli): command `clean`

---

crates/biome_graphql_parser/src/parser/definitions/enum.rs
crates/biome_graphql_parser/src/parser/definitions/field.rs
crates/biome_graphql_parser/src/parser/definitions/input_object.rs
crates/biome_graphql_parser/src/parser/definitions/mod.rs
crates/biome_graphql_parser/tests/graphql_test_suite/err/definitions/input_object.graphql
crates/biome_graphql_parser/tests/graphql_test_suite/err/definitions/input_object.graphql.snap
crates/biome_graphql_parser/tests/graphql_test_suite/ok/definitions/input_object.graphql
crates/biome_graphql_parser/tests/graphql_test_suite/ok/definitions/input_object.graphql.snap

Parse GraphQL Input Object definition ([link](https://spec.graphql.org/October2021/#sec-Input-Objects)). This is also a small case, as almost all parsing logic was implemented in a previous PR that focused on parsing Object definition.
Once this is complete, we only have directive definitions left as the last GraphQL definitions. After handling both, we could start parsing GraphQL type extensions.

feat(biome_graphql_parser): parse input object definition

---

GOVERNANCE.md

This is my first attempt at adding a section for Financial Contributions to the GOVERNANCE document. Feedback very much welcome!
Members of the @biomejs/core-contributors need to approve the changes

chore: add Financial Contributions section to GOVERNANCE

---

crates/biome_graphql_parser/src/parser/definitions/directive.rs
crates/biome_graphql_parser/src/parser/definitions/field.rs
crates/biome_graphql_parser/src/parser/definitions/mod.rs
crates/biome_graphql_parser/src/parser/parse_error.rs
crates/biome_graphql_parser/tests/graphql_test_suite/err/definitions/directive_definition.graphql
crates/biome_graphql_parser/tests/graphql_test_suite/err/definitions/directive_definition.graphql.snap
crates/biome_graphql_parser/tests/graphql_test_suite/ok/definitions/directive_definition.graphql
crates/biome_graphql_parser/tests/graphql_test_suite/ok/definitions/directive_definition.graphql.snap

Parse GraphQL directive definition ([link](https://spec.graphql.org/October2021/#sec-Type-System.Directives)). This is a small case so this PR includes both the happy path parsing and error handling
This is the last GraphQL definition. After this, we can start parsing GraphQL type extensions.

feat(biome_graphql_parser): parse directive definition

---

crates/biome_graphql_parser/src/parser/definitions/operation.rs
crates/biome_graphql_parser/src/parser/parse_error.rs
crates/biome_graphql_parser/tests/graphql_test_suite/err/operation.graphql
crates/biome_graphql_parser/tests/graphql_test_suite/err/operation.graphql.snap
crates/biome_graphql_parser/tests/graphql_test_suite/err/type.graphql
crates/biome_graphql_parser/tests/graphql_test_suite/err/type.graphql.snap

The original error handling for operations was minimal, making it difficult for users to understand what needed to be fixed. This PR enhances the error handling and provides clearer indications of where the errors occur.
From
```graphql
operation.graphql:1:7 parse ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
× expected `{` but instead found `$`
> 1 │ query $storyId: ID! {
│       ^
2 │ 	likeStory(storyId: $storyId)
3 │ }
i Remove $
operation.graphql:1:19 parse ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
× Expected a field, a fragment spread, or an inline fragment but instead found '!'.
> 1 │ query $storyId: ID! {
│                   ^
2 │ 	likeStory(storyId: $storyId)
3 │ }
i Expected a field, a fragment spread, or an inline fragment …
```

fix(biome_graphql_parser): improve operation handling

---

Cargo.lock
xtask/bench/Cargo.toml
xtask/bench/benches/analyzer-libs-css.txt
xtask/bench/src/lib.rs

This PR fixes the benchmarking job. I removed the CSS files that were causing parsing errors, and changes the code to print the diagnostics if there are any.
I think this PR should pass

chore: remove libs that panic

---

crates/biome_graphql_parser/src/parser/definitions/interface.rs
crates/biome_graphql_parser/tests/graphql_test_suite/err/definitions/interface.graphql
crates/biome_graphql_parser/tests/graphql_test_suite/err/definitions/interface.graphql.snap
crates/biome_graphql_parser/tests/graphql_test_suite/err/definitions/object.graphql
crates/biome_graphql_parser/tests/graphql_test_suite/err/definitions/object.graphql.snap

Empty interface list in ImplementsInterface clauses are not allowed (see [here](https://spec.graphql.org/October2021/#ImplementsInterfaces))
For instance, the following case should emit a diagnostic:
```graphql
type Person implements &
```

fix(biome_graphql_parser): prevent empty interface list in implement clause

---

crates/biome_graphql_parser/src/parser/argument.rs
crates/biome_graphql_parser/src/parser/definitions/enum.rs
crates/biome_graphql_parser/src/parser/definitions/field.rs
crates/biome_graphql_parser/src/parser/definitions/interface.rs
crates/biome_graphql_parser/src/parser/definitions/operation.rs
crates/biome_graphql_parser/src/parser/definitions/union.rs
crates/biome_graphql_parser/src/parser/mod.rs
crates/biome_graphql_parser/src/parser/type.rs
crates/biome_graphql_parser/src/parser/value.rs
crates/biome_graphql_parser/tests/graphql_test_suite/ok/definitions/object.graphql
crates/biome_graphql_parser/tests/graphql_test_suite/ok/definitions/object.graphql.snap

Some parsing rule pre-conditions was difficult to understand because certain definitions optionally have a description located right before them. This PR refactors those precondition using th NthAt trait, making them easier to comprehend and also fixing a subtle bug where the parser failed to recognize an object attribute preceded by a description.
All tests should pass.

refactor(biome_graphql_parser): use is_nth_at_*

---

CHANGELOG.md
crates/biome_js_analyze/src/lint/correctness/use_jsx_key_in_iterable.rs
crates/biome_js_analyze/tests/specs/correctness/useJsxKeyInIterable/invalid.jsx
crates/biome_js_analyze/tests/specs/correctness/useJsxKeyInIterable/invalid.jsx.snap
crates/biome_js_analyze/tests/specs/correctness/useJsxKeyInIterable/valid.jsx
crates/biome_js_analyze/tests/specs/correctness/useJsxKeyInIterable/valid.jsx.snap

This PR makes the `useJsxKeyInIterable` lint handle more cases related to JSX fragments. It can now handle cases like this:
```jsx
// valid
[].map((item) => {
return <>{item.condition ? <div key={item.id} /> : <div key={item.id}>foo</div>}</>;
});
// invalid
[].map((item) => {
return <>{item.condition ? <div /> : <div>foo</div>}</>;
});
```
related to: #2590
Added snapshot tests
```bash
cargo test -p biome_js_analyze use_jsx_key_in_iterable
```

fix(lint/useJsxKeyInIterable): handle fragments more comprehensively

---

CHANGELOG.md
crates/biome_js_analyze/src/lint/complexity/no_excessive_nested_test_suites.rs
crates/biome_js_analyze/tests/specs/complexity/noExcessiveNestedTestSuites/valid.js
crates/biome_js_analyze/tests/specs/complexity/noExcessiveNestedTestSuites/valid.js.snap

Zod has a `describe` method for describing the fields of a zod schema. Now, this rule will no longer alert when presented with snippets like this:
```js
z.object({})
.describe('')
.describe('')
.describe('')
.describe('')
.describe('')
.describe('');
```
fixes #2599
Added snippet to snapshot tests
```bash
cargo test -p biome_js_analyze no_excessive_nested_test_suites
```

fix(lint/noExcessiveNestedTestSuites): don't alert if describe call is a member of some other object

---

crates/biome_analyze/src/context.rs
crates/biome_analyze/src/options.rs
crates/biome_service/src/file_handlers/javascript.rs
crates/biome_test_utils/src/lib.rs

Close https://github.com/biomejs/biome/issues/2800
- Make jsx_runtime optional inside the analyzer
- It is because `AnalyzerOptions` is a type that is used across languages, and JSON/CSS languages don't need/require this option.
Pass existing tests.

feat(biome_analyze): make jsx_runtime optional inside the analyzer

---

crates/biome_js_analyze/src/lint/correctness/use_jsx_key_in_iterable.rs
crates/biome_js_analyze/tests/specs/correctness/useJsxKeyInIterable/invalid.jsx
crates/biome_js_analyze/tests/specs/correctness/useJsxKeyInIterable/invalid.jsx.snap
crates/biome_js_analyze/tests/specs/correctness/useJsxKeyInIterable/valid.jsx
crates/biome_js_analyze/tests/specs/correctness/useJsxKeyInIterable/valid.jsx.snap

The rule will now catch snippets like below:
```jsx
// invalid
[].map((item) => {
const div = <div>{item}</div>;
return div;
});
```
fully resolves #2590
Added more snapshot tests
```bash
cargo test -p biome_js_analyze use_jsx_key_in_iterable
```

fix(lint/useJsxKeyInIterable): flag jsx in variable declarations

---

crates/biome_analyze/src/rule.rs

This PR implement `Serialize` for `RuleMetadata`. I will use this to transform and create a JSON file out of it that we consume from our website, e.g. `/rules/metadata.json`
CI should pass

feat(analyze): serialize rule metadata

---

Cargo.lock
Cargo.toml
xtask/bench/Cargo.toml
xtask/bench/benches/graphql_parser.rs
xtask/bench/benches/libs-graphql.txt
xtask/bench/src/language.rs

This PR adds benchmarks for the GraphQL parser
CI should pass, and we should see three new benchmarks added

feat(bench): add graphql parser

---

crates/biome_cli/src/execute/std_in.rs
crates/biome_fs/src/path.rs

There's no reason to let this particular function panic. I encountered this behavior when working on #2823.
It compiles, and tests pass.

refactor(biome_fs): make `BiomePath::extension_as_str` not panic

---

CHANGELOG.md
crates/biome_js_analyze/tests/specs/correctness/noUndeclaredVariables/invalidNamesapceReference.ts
crates/biome_js_analyze/tests/specs/correctness/noUndeclaredVariables/invalidNamesapceReference.ts.snap
crates/biome_js_analyze/tests/specs/correctness/noUnusedImports/invalid-import-namespace.ts
crates/biome_js_analyze/tests/specs/correctness/noUnusedImports/invalid-import-namespace.ts.snap
crates/biome_js_analyze/tests/specs/correctness/noUnusedVariables/validNamesapceExportType.ts
crates/biome_js_analyze/tests/specs/correctness/noUnusedVariables/validNamesapceExportType.ts.snap
crates/biome_js_analyze/tests/specs/style/useExportType/valid.ts
crates/biome_js_analyze/tests/specs/style/useExportType/valid.ts.snap
crates/biome_js_analyze/tests/specs/suspicious/noRedeclare/invalid.ts
crates/biome_js_analyze/tests/specs/suspicious/noRedeclare/invalid.ts.snap
crates/biome_js_semantic/src/events.rs

Fix #2796
This PR improves the handling of import namespace in the JavaScript/TypeScript semantic model.
We now handle import namespace as TypeScript namespace: we consider them as values (variables) and allow their reference in an ambient context only inside a qualified name.
Some examples:
```ts
// Unused import
import * as Ns1 from "";
// This doesn't reference the import namespace `Ns1`
type T1 = Ns1; // Undeclared variable `Ns1`
namespace Ns2 {}
type T2 = Ns2; // Undeclared variable `Ns2`
import type * as Ns3 from "";
// `Ns3` references the import namespace because it is a qualified name.
type T3 = Ns3.Inner;
```
Unfortunately it is not enough because import namespace can be imported as a `type`.
In this specific case, we consider them as types.
However, it is always invalid of …

fix(js_semantic): import namespace handling

---

crates/biome_yaml_syntax/src/file_source.rs

feat: yaml file source

---

Cargo.lock

It seems we have a stale `Cargo.lock` file, and `rust-analyzer` wants to update it.
N/A

fix: stale `Cargo.lock`

---

Cargo.lock
crates/biome_deserialize/Cargo.toml
crates/biome_deserialize/src/impls.rs
crates/biome_deserialize/src/json.rs

To facilitate #2757, we need a generic `Value`. We decided on implementing `Deserializable` on `serde_json::Value`. This also implements `PartialOrd` and `Order` on `Text`, so we can collect fields into a `BTreeMap`

feat(biome_deserialize): implement necessary traits for `#[deserializable(rest)]`

---

Cargo.lock
crates/biome_cli/tests/snapshots/main_commands_check/top_level_all_down_level_not_all.snap
crates/biome_cli/tests/snapshots/main_commands_lint/top_level_all_true_group_level_all_false.snap
crates/biome_cli/tests/snapshots/main_configuration/override_globals.snap
crates/biome_js_analyze/src/lint/correctness/no_undeclared_variables.rs
crates/biome_js_analyze/tests/specs/correctness/noUndeclaredVariables/infer_incorrect.ts.snap
crates/biome_js_analyze/tests/specs/correctness/noUndeclaredVariables/invalidNamesapceReference.ts.snap
crates/biome_js_analyze/tests/specs/correctness/noUndeclaredVariables/invalidTsInJs.js.snap
crates/biome_js_analyze/tests/specs/correctness/noUndeclaredVariables/invalidTypeValueWithSameName.ts.snap
crates/biome_js_analyze/tests/specs/correctness/noUndeclaredVariables/noUndeclaredVariables.js.snap
crates/biome_js_analyze/tests/specs/correctness/noUndeclaredVariables/noUndeclaredVariables.ts.snap
crates/biome_js_analyze/tests/suppression/correctness/noUndeclaredVariables/noUndeclaredVariables.ts.snap

This PR improves the diagnostic of `noUndeclaredVariables`.
We now suggest using the `javascript.globals` option when we found an undeclared variable.
CI must pass.

refactor(noUndeclaredVariables): suggest using javascript.globals

---

CHANGELOG.md
crates/biome_js_analyze/tests/specs/correctness/noUndeclaredVariables/validThis.tsx
crates/biome_js_analyze/tests/specs/correctness/noUndeclaredVariables/validThis.tsx.snap
crates/biome_js_semantic/src/events.rs

Fix #2636
@printfn submitted #2656 that fixed the issue by modifying the grammar and the parser.
This PR supersedes #2656. Instead of modifying the grammar and the parser, it adds an exception in the semantic model.
We already used this strategy to ignore `typeof this.foo`.
I credited @printfn in the CHANGELOG for its investigations and the submitted PR :)
I added a non regression test.

fix(js_semantic): ignore `this` in JSX components

---

CHANGELOG.md
crates/biome_configuration/src/linter/rules.rs
crates/biome_diagnostics_categories/src/categories.rs
crates/biome_js_analyze/src/lint/nursery.rs
crates/biome_js_analyze/src/lint/nursery/use_top_level_regex.rs
crates/biome_js_analyze/src/options.rs
crates/biome_js_analyze/tests/specs/nursery/useTopLevelRegex/invalid.js
crates/biome_js_analyze/tests/specs/nursery/useTopLevelRegex/invalid.js.snap
crates/biome_js_analyze/tests/specs/nursery/useTopLevelRegex/valid.js
crates/biome_js_analyze/tests/specs/nursery/useTopLevelRegex/valid.js.snap
packages/@biomejs/backend-jsonrpc/src/workspace.ts
packages/@biomejs/biome/configuration_schema.json

This rule detects regex literals that are defined inside functions. This can result in performance problems if a function like this is called often:
```js
function foo(someString) {
return /[a-Z]*/.test(someString)
}
```
Instead, biome will now encourage users to place regex literals at the top level of a module.
```js
const REGEX = /[a-Z]*/;
function foo(someString) {
return REGEX.test(someString)
}
```
It's a little unclear to me if it would be preferable to implement this using a Visitor instead.
closes #2148
Added snapshot tests
```bash
cargo test -p biome_js_analyze use_top_level_regex
```

feat(lint): add new js lint: `useTopLevelRegex`

---

crates/biome_analyze/src/rule.rs
crates/biome_js_analyze/src/assists/correctness/organize_imports.rs

For #2799, we want to phase out the manual construction of the `RuleAction` struct to make the `applicability` field private.
This is intensionally small to make it easy to review before I do a huge codemod to actually phase out the manual construction.
related to: #2799
It compiles.

refactor(biome_analyze): add `RuleAction::new`

---

crates/biome_js_analyze/src/lint/style/no_implicit_boolean.rs

Closes https://github.com/biomejs/website/issues/341
N/A

fix(docs): noImplicitBoolean is inspired

---

crates/biome_deserialize_macros/src/deserializable_derive.rs
crates/biome_deserialize_macros/src/deserializable_derive/struct_field_attrs.rs
crates/biome_deserialize_macros/src/lib.rs

We want the ability to put any unknown fields into a catch-all field, like [serde's flatten attribute](https://serde.rs/attr-flatten.html#capture-additional-fields). This allows for parsing a package.json file while preserving the unknown fields.
[Discussion here](https://github.com/biomejs/biome/discussions/2698)
This is a first draft, I'd love some guidance on the correct naming/API. Perhaps we could add a new option to the `unknown_fields` container attribute?
Would love some guidance here!

feat(biome_deserialize_derive): adding a rest attribute

---

CHANGELOG.md
crates/biome_js_analyze/src/lint/suspicious/no_exports_in_test.rs
crates/biome_js_analyze/tests/specs/suspicious/noExportsInTest/in-source-testing.js
crates/biome_js_analyze/tests/specs/suspicious/noExportsInTest/in-source-testing.js.snap

- Closes https://github.com/biomejs/biome/issues/2859
Now we treat files containing a top-level test call as test files.

fix(lint/noExportsInTest): avoid mistakenly identifying files with in-source testing as test files

---

Cargo.lock
Cargo.toml
crates/biome_configuration/Cargo.toml
crates/biome_configuration/src/editorconfig.rs
crates/biome_configuration/src/lib.rs
crates/biome_formatter/src/lib.rs

This is the first in a series of PRs to add `.editorconfig` support to biome. I'll be trying to keep these fairly small so they are easy to review.
The goal of this PR is to introduce the necessary helpers to actually parse the settings, and convert them into their biome equivalents.
Related to: #1724
Added some unit tests
```bash
cargo test -p biome_configuration editorconfig
```

feat(biome_configuration): add helpers for parsing .editorconfig files

---

crates/biome_js_analyze/src/lint/style/no_non_null_assertion.rs

Fix typo
Making the docs better. :)

docs: update no_non_null_assertion.rs

---

crates/biome_js_analyze/src/lint/suspicious/no_explicit_any.rs

Follow up of https://github.com/biomejs/biome/pull/2874#discussion_r1603087488

fix(no-explicit-any): doc codeblock test

---

crates/biome_js_analyze/src/lint/style/use_naming_convention.rs

Fix some minor formatting issue with the documentation of the rule
> [!WARNING]
> Be aware that this PR introduce `HardBreak` that is currently not handled by the parser of the website (I have [another PR to add this](https://github.com/biomejs/website/pull/354))
This PR is the first part of a permanent solution for this PR: https://github.com/biomejs/website/pull/307 (which will be close and replace)

docs: fix incorrect bullet char + fix links

---

.github/workflows/main.yml

After searching I believe the current failing CI jobs on Windows is caused by a recent rustup change that breaks nextests. So this PR uses the workaround mentioned by those smart minds that are also affected by and fixed this problem.
Refs:
- https://github.com/rust-lang/rustup/pull/3703
- https://github.com/nextest-rs/nextest/issues/267
Merge to main and check whether the CI on Windows will succeed.

fix(ci): nextest on windows

---

crates/biome_analyze/src/rule.rs
crates/biome_analyze/src/signals.rs
crates/biome_js_analyze/src/assists/correctness/organize_imports.rs
crates/biome_migrate/src/analyzers/nursery_rules.rs

`FixKind` and `Applicability` line up one to one, and need to remain in sync. This adds `RuleMetadata::to_applicability()` and a `impl From<FixKind> for Applicability`.
I'll follow up this PR with another codemod to change all the rules to call this function instead.
Related to: #2799
It compiles.

refactor(biome_analyze): derive `Applicability` from `FixKind`

---

CHANGELOG.md
crates/biome_cli/tests/cases/handle_vue_files.rs
crates/biome_cli/tests/snapshots/main_cases_handle_vue_files/vue_compiler_macros_as_globals.snap
crates/biome_service/src/file_handlers/javascript.rs

Vue has some magic compiler macros that are treated like globals when writing single file components. This makes it unnecessary for users to manually configure biome to treat them as globals.
closes #2771
Added a test.

fix(biome_service): add magic vue compiler macros to globals for vue single file components

---

.github/workflows/pull_request.yml

Follow up of #2887 to fix CI tests on Windows in the `pull_request.yml` workflow.
Merge to main and check rebased or following PRs.

chore(ci): fix nextest on windows

---

crates/biome_fs/src/interner.rs

Use an unordered hash map instead of an ordered hash map for path interning.
CI must pass.

refactor: use an unordered set for interned paths

---

CHANGELOG.md
crates/biome_js_analyze/src/lint/suspicious/no_confusing_void_type.rs
crates/biome_js_analyze/tests/specs/suspicious/noConfusingVoidType/invalid.ts.snap

While I was testing the `--rule` option on a repository, I found the diagnostic of the `noConfusingVoid` rule quite confusing (point intended).
This PR improves the diagnostic and suggests a code fix.
I made the code fix unsafe because in TypeScript `void` is not assignable to `undefined`.
I updated the test snapshots.

refactor(noConfusingVoidType): add code action and improve diagnostics

---

crates/biome_js_analyze/src/lint/style/use_naming_convention.rs

I have noticed some typos in the `useNamingConvention` documentation. Naming of the `custon` option looked very puzzling [on website](https://biomejs.dev/linter/rules/use-naming-convention/#options). I guess it is picked up from here, or?
Not applicable, because there are no code changes.

chore: fix typos in the `useNamingConvention` documentation

---

crates/biome_graphql_parser/src/parser/definitions/directive.rs
crates/biome_graphql_parser/src/parser/definitions/enum.rs
crates/biome_graphql_parser/src/parser/definitions/fragment.rs
crates/biome_graphql_parser/src/parser/definitions/input_object.rs
crates/biome_graphql_parser/src/parser/definitions/interface.rs
crates/biome_graphql_parser/src/parser/definitions/mod.rs
crates/biome_graphql_parser/src/parser/definitions/object.rs
crates/biome_graphql_parser/src/parser/definitions/operation.rs
crates/biome_graphql_parser/src/parser/definitions/scalar.rs
crates/biome_graphql_parser/src/parser/definitions/schema.rs
crates/biome_graphql_parser/src/parser/definitions/union.rs

Following the fix that add support for using keywords as identifiers in GraphQL, the conditions used to verify the absence of definitions have become simpler. This PR simplifies those checks in to a simple match clause, making it clearer under which condition a definition is parsed.
Additionally, this PR servers as a stepping stone toward parsing extensions in GraphQL.
This PR solely refactors the checks for GraphQL definitions, no tests was modified. All tests should still pass.

refactor(biome_graphql_parser): remove is_at_*_definition

---

crates/biome_cli/src/execute/migrate/eslint_to_biome.rs
crates/biome_configuration/src/lib.rs
crates/biome_configuration/src/linter/mod.rs
crates/biome_configuration/src/linter/rules.rs
packages/@biomejs/backend-jsonrpc/src/workspace.ts
packages/@biomejs/biome/configuration_schema.json
xtask/codegen/src/generate_configuration.rs

This PR addresses a concern of @ematipico.
Previously `fix` field was available for any rules, even the ones without code actions. 
To address the issue, I added two new types: `RuleFixConfiguration` and `RuleWithFixOptions` and changed the script that generates `Rules`. Fixable rules use `RuleFixConfiguration`, and unfixable rules use `RuleConfiguration`.
Doing that has also some benefits:
- We reduce the size of the configuration because some rules don't have the `fix` field
- We don't introduce any dynamic check because it is statically generated.
- We get a perfect JSON schema
I am not fond of having dual types `RuleConfiguration`/`RuleFixConfiguration` and `RuleWithOptions`/`RuleWithFixOptions`. However, for this looks like a good tradeoff for now.
CI must pass.

refactor(configuration): disallow `fix` field for unfixable rules

---

CHANGELOG.md
crates/biome_js_parser/src/syntax/typescript/statement.rs
crates/biome_js_parser/test_data/inline/err/ts_declare_using.rast
crates/biome_js_parser/test_data/inline/err/ts_declare_using.ts

The following invalid syntax no longer causes the Biome parser to crash:
```ts
declare using x: null;
declare qwait using x: null;
```
I added two tests.

fix(js_parser): do not crash when encountring `declare using`

---

crates/biome_cli/tests/snapshots/main_commands_check/file_too_large.snap
crates/biome_cli/tests/snapshots/main_commands_check/file_too_large_cli_limit.snap
crates/biome_cli/tests/snapshots/main_commands_check/file_too_large_config_limit.snap
crates/biome_cli/tests/snapshots/main_commands_ci/file_too_large.snap
crates/biome_cli/tests/snapshots/main_commands_ci/file_too_large_cli_limit.snap
crates/biome_cli/tests/snapshots/main_commands_ci/file_too_large_config_limit.snap
crates/biome_cli/tests/snapshots/main_commands_format/file_too_large.snap
crates/biome_cli/tests/snapshots/main_commands_format/file_too_large_cli_limit.snap
crates/biome_cli/tests/snapshots/main_commands_format/file_too_large_config_limit.snap
crates/biome_cli/tests/snapshots/main_commands_lint/file_too_large.snap
crates/biome_cli/tests/snapshots/main_commands_lint/file_too_large_cli_limit.snap
crates/biome_cli/tests/snapshots/main_commands_lint/file_too_large_config_limit.snap
crates/biome_service/src/diagnostics.rs
crates/biome_service/src/snapshots/file_too_large.snap

We now suggest using `files.maxSize` when we hit a file that exceeds this limit.
I updated the existing snapshots.

refactor: improve diagnostic for too large files

---

xtask/bench/benches/json_formatter.rs

We were using the wrong suites to benchmark the json formatter. 🤣
Codspeed will use the correct one to benchmark the json formatter.

fix(bench): json formatter benchmark suites

---

crates/biome_analyze/CONTRIBUTING.md
crates/biome_analyze/src/lib.rs

Adds more information in the contribution guidelines.
I added:
- what's a nursery group
- some tips on how developers should write rules
- explanation of `declare_node_union`
- code tips around the try operator and `let else`
I moved the sections around, in order to create a flow that made sense:
- concepts
- coding
- macros
- semantic model
- etc. 
- testing
- documentation
- codegen
- commit
Before, it didn't make sense.
Proofread.
[Here's the rendered file](https://github.com/biomejs/biome/blob/docs/more-info/crates/biome_analyze/CONTRIBUTING.md), the code diff doesn't help.

docs: improve analyze guide

---

crates/biome_analyze/CONTRIBUTING.md

More goodies around the analyzer.
All these will be updated soon once the analyzer infrastructure is done (there are still few more changes) and it will be ready for more rules.
As for now, I am assuming that the users are writing **lint** rules, however, we already say at the beginning that we have different kind of rules.
I added information regarding:
- `source` and `source_kind`
- a brief explanation of `action`
Also, I removed this `.md` file from the `biome_analyze` crate because... well, it's to long and I think having it GitHub is more than enough. So I removed the `ignore` code block metadata.
Proofread

docs: add more tips around the analyzer

---

Cargo.lock
crates/biome_grit_patterns/Cargo.toml
crates/biome_grit_patterns/src/pattern_compiler/bubble_compiler.rs

Remove unneeded dependency `itertools`.
CI must pass.

build(deps): remove itertools

---

Cargo.lock
crates/biome_cli/src/commands/check.rs
crates/biome_cli/src/commands/format.rs
crates/biome_cli/tests/cases/editorconfig.rs
crates/biome_cli/tests/cases/mod.rs
crates/biome_cli/tests/snapshots/main_cases_editorconfig/should_have_biome_override_editorconfig.snap
crates/biome_cli/tests/snapshots/main_cases_editorconfig/should_use_editorconfig.snap
crates/biome_configuration/src/diagnostics.rs
crates/biome_configuration/src/editorconfig.rs
crates/biome_diagnostics/Cargo.toml
crates/biome_diagnostics/src/adapters.rs
crates/biome_service/src/configuration.rs
crates/biome_service/src/diagnostics.rs

This is part of a series of PRs to add `.editorconfig` support to biome. As with the previous PR, this is intentionally small to help make code reviews easier. The goal is to add functions that look for and load the .editorconfig files, and merge the loaded configurations.
Here's how the configurations are prioritized:
- cli args overrides `biome.json`
- `biome.json` overrides `.editorconfig`
- `.editorconfig` overrides biome defaults
Related to: #1724
I've added one test just to show that it works in this PR, but I have more tests in another branch that I could bring into this PR instead of making another one.
```bash
cargo test -p biome_service
cargo test -p biome_cli
```

feat(biome_service,biome_cli): resolve `.editorconfig` files and merge configuration

---

crates/biome_cli/src/commands/mod.rs
crates/biome_configuration/src/diagnostics.rs
crates/biome_configuration/src/lib.rs
crates/biome_service/src/configuration.rs
crates/biome_service/src/diagnostics.rs
crates/biome_service/src/settings.rs

This is part of a series of PRs for adding `.editorconfig` support to biome. Specifically, this PR follows up on this comment thread: https://github.com/biomejs/biome/pull/2884#discussion_r1605721658
Part of this refactor is also to prefer using `into()`, or the `?` operator's implicit call to `into()` on error types because it's a little bit easier to read, and can make it a little less tedious to do future refactors.
Related to: #1724
It compiles and tests pass.

refactor(diagnostics): change enum hierarchy for configuration diagnostics

---

CHANGELOG.md
crates/biome_js_analyze/src/lib.rs
crates/biome_js_analyze/src/lint/nursery/use_sorted_classes.rs
crates/biome_js_analyze/src/lint/nursery/use_sorted_classes/sort.rs
crates/biome_js_analyze/tests/specs/nursery/useSortedClasses/templateLiteralSpace.jsx
crates/biome_js_analyze/tests/specs/nursery/useSortedClasses/templateLiteralSpace.jsx.snap

Now leading and trailing spaces are kept when applying the code action of `useSortedClasses`
I added two new test cases

fix(useSortedClasses): keep trailing and leading spaces in code action

---

crates/biome_js_analyze/src/lint/security/no_dangerously_set_inner_html.rs
crates/biome_js_analyze/src/lint/security/no_dangerously_set_inner_html_with_children.rs

fix(no-danger): rule source typos

---

CHANGELOG.md
crates/biome_cli/src/commands/ci.rs

Closes https://github.com/biomejs/biome/issues/2819
I didn't test it, but I know it's the correct fix. YOLO strategy

fix: resolve manifest in CI

---

CHANGELOG.md
crates/biome_js_analyze/src/lint/correctness/no_unused_variables.rs
crates/biome_js_analyze/tests/specs/correctness/noUndeclaredVariables/issue_2886.ts
crates/biome_js_analyze/tests/specs/correctness/noUndeclaredVariables/issue_2886.ts.snap

The rule `noUnusedVariables` no longer panics.
Closes https://github.com/biomejs/biome/issues/2886
@biomejs/maintainers @biomejs/core-contributors This is a reminder that we should never use code that panics, e.g. `unwrap`, `unreachable!`, etc. We should never forget that Biome's parser is recoverable, so we can always receive broken that could be weird and mapped to unexpected nodes
Added a regression

fix(noUnusedVariables): no longer panic

---

crates/biome_configuration/src/linter/rules.rs
crates/biome_js_analyze/src/lint/nursery/use_top_level_regex.rs
crates/biome_js_analyze/tests/specs/nursery/useTopLevelRegex/valid.js
crates/biome_js_analyze/tests/specs/nursery/useTopLevelRegex/valid.js.snap
packages/@biomejs/backend-jsonrpc/src/workspace.ts
packages/@biomejs/biome/configuration_schema.json

- Close https://github.com/biomejs/biome/issues/2872

refactor(lint/useTopLevelRegex): ignore regular expressions with the `g` and/or `y` flags

---

.gitattributes
.gitignore

Add more generated files to `.gitattributes` and use `gitignore`/`gitattribute` relative path marker `/` for the `crates` folder.
CI must pass

chore(git): ignore more generated files

---

CHANGELOG.md
crates/biome_service/src/workspace/server.rs

Closes https://github.com/biomejs/biome/issues/2781
The issue was the aggressive caching of `FileFeatureResult`, maybe designed with poor judgement from my side.
Here's the issue explained: when a file is opened, the LSP request diagnostics from a certain file. We pull diagnostics using these feature set:
```rust
let file_features = self.workspace.file_features(SupportsFeatureParams {
features: FeaturesBuilder::new()
.with_linter()
.with_organize_imports()
.build(),
path: biome_path.clone(),
})?;
```
A formatter doesn't have proper diagnostics, so we exclude it from the features. Since the formatter feature isn't requested, the default value is used, which is `Supported` because `ignore` part is checked only on a parameter basis. 
However, this was then cached inside our workspace. 
When …

fix(workspace): remove caching of file features

---

crates/biome_lsp/src/handlers/analysis.rs
crates/biome_lsp/tests/server.rs
crates/biome_service/src/file_handlers/css.rs
crates/biome_service/src/file_handlers/javascript.rs

Adds support for pulling diagnostics from CSS file analysis.
I didn't add the `fix_all` test because we don't have rules that apply a code action yet.
Once we merge this PR, clients will need to update the plugins to enable them for CSS files too.
I already sent a PR for the VSCode extension: https://github.com/biomejs/biome-vscode/pull/222
We should do the same for `biome-intellij` and `biome-zed`. Help would be appreciated!! 

feat(lsp): pull diagnostics for CSS files

---

CHANGELOG.md
crates/biome_cli/src/execute/migrate/eslint.rs

Propagate errors reported by NodeJS when loading ESLint presets.
This helps to identify what is going on.
See #2935
We are not currently able to test this.
I tested the fix locally,

refactor(migrate/eslint): propagate NodeJS error

---

packages/@biomejs/biome/scripts/generate-packages.mjs
packages/@biomejs/biome/scripts/update-nightly-version.mjs

I accidentally broke the script that was used to update the `@biomejs/cli-*` manifests. In fact, the latest nightly didn't work.
Also, I fixed a bug where the nightly script didn't correctly bump the patch.
Merge it and trigger another nightly release

ci: fix nightly version and restore update of manifest

---

Cargo.lock
crates/biome_analyze/src/lib.rs
crates/biome_analyze/src/matcher.rs
crates/biome_analyze/src/registry.rs
crates/biome_analyze/src/rule.rs
crates/biome_analyze/src/signals.rs
crates/biome_analyze/src/suppression_action.rs
crates/biome_analyze/src/syntax.rs
crates/biome_analyze/src/visitor.rs
crates/biome_css_analyze/Cargo.toml
crates/biome_css_analyze/src/lib.rs
crates/biome_css_analyze/src/suppression_action.rs
crates/biome_js_analyze/src/lib.rs
crates/biome_js_analyze/src/suppression_action.rs
crates/biome_js_transform/src/lib.rs
crates/biome_json_analyze/src/lib.rs
crates/biome_json_analyze/src/suppression_action.rs
crates/biome_migrate/src/lib.rs

The suppression action system was tied to the JS language.
This refactors the system by making it generic using a trait called `SuppressionAction` inside `biome_analyze`.
Users will need to implement two functions:
- the function that returns `ApplySuppression`, which contains info on where and how to apply the mutation
- the function that actually adds the suppression comment in the right place
The CSS and JSON languages don't have suppression actions at this time.
The idea is to land a PR that applies suppression to CSS lint rules. @togami2864 I think we need to land at least a basic heuristic to apply suppression comments; otherwise, people won't see the "Quick fix" tooltip in the IDEs/editors.
The current CI should work.

refactor: make suppression action generic via trait

---

crates/biome_cli/tests/cases/overrides_formatter.rs
crates/biome_cli/tests/snapshots/main_cases_overrides_formatter/complex_enable_disable_overrides.snap
crates/biome_service/src/settings.rs

Previously, overrides could erroneously enable the formatter if it was supposed to be disabled, specifically in configurations like this:
```jsonc
{
"formatter": {
"enabled": true,
"lineWidth": 20
},
"javascript": {
"formatter": {
"enabled": false
}
},
"overrides": [
{ "include": ["formatted.js"], "formatter": { "enabled": true } },
{
// this override doesn't have a formatter section, so it would assume the global value, ignoring the language config
"include": ["dirty.js"],
"linter": {
"rules": {
"performance": {
"noBarrelFile": "off"
}
}
}
}
]
}
```
This PR fixes that behavior by not forcing the override settings to have a `Some` value no matter what. I briefly looked into whether or not this affects the linter too, and I _think_ it does, but I think that fix is outside the scope of this …

fix(formatter): don't let overrides erroneously enable formatter if unspecified

---

Cargo.lock
Cargo.toml
crates/biome_deserialize/Cargo.toml
crates/biome_deserialize_macros/Cargo.toml

I've just released `biome_deserialize` and `biome_deserialize_macros`.
This PR set their new version.
CI must pass.

release(crates): biome_deserialize and biome_deserialize_macros

---

CHANGELOG.md
crates/biome_cli/src/execute/migrate/eslint_any_rule_to_biome.rs
crates/biome_js_analyze/src/lint/nursery/no_useless_undefined_initialization.rs
crates/biome_js_analyze/tests/specs/nursery/noUselessUndefinedInitialization/invalid.js
crates/biome_js_analyze/tests/specs/nursery/noUselessUndefinedInitialization/invalid.js.snap

Closes #2879 
The changes are relevant to the code action, but I also had to change the query type in order to place comments after declaration statement.
I changed the `Fix_Kind` of the action to `Safe` since it doesn't remove any user relevant information anymore.
Added comments on test cases to demonstrate the autofix correctness.
I hope I tackled any test case relevant to this action, let me know if you know of any edge case I might have not considered.

feat(noUselessUndefinedInitialization): move comments after the statement on code action

---

CHANGELOG.md
crates/biome_cli/tests/cases/handle_astro_files.rs
crates/biome_cli/tests/snapshots/main_cases_handle_astro_files/astro_global.snap
crates/biome_service/src/file_handlers/javascript.rs

The same idea as https://github.com/biomejs/biome/pull/2823
Add `Astro` object to globals list, so users don't have to.
Added test and snapshot.

fix(biome_service): add Astro object to globals for .astro files

---

crates/biome_js_analyze/src/lint/nursery/use_adjacent_overload_signatures.rs
crates/biome_js_analyze/tests/specs/nursery/useAdjacentOverloadSignatures/invalid.ts.snap

refactor(biome_js_analyze): use rustc_hash::FxHashSet; and reduce allocation

---

crates/biome_service/src/matcher/pattern.rs

This implements the "at least one of these" syntax for glob patterns as discussed in #2986. The intention is to bring our glob pattern parsing closer to what the Editorconfig spec allows for, so that we can have better Editorconfig support.
This is possibly a breaking change since the `{` and `}` characters now have special meaning, and as such it would probably be better to leave this for biome 2.0. It's likely this PR will get stale in that time, but at minimum the test cases in this PR could remain useful to have.
closes #2986
added tests

feat(configuration): add support for `{a,b}` glob patterns, gated behind an internal flag

---

crates/biome_cli/tests/cases/biome_json_support.rs
crates/biome_cli/tests/snapshots/main_cases_biome_json_support/always_disable_trailing_commas_biome_json.snap
crates/biome_service/src/file_handlers/json.rs

This ensures that trailing commas is always disabled when formatting `biome.json` or `biome.jsonc`. Failing to do so could result in biome formatting it's own configuration such that it's no longer valid json, and would not get parsed. The full context is in #2990.
fixes #2990
I added a cli test for this scenario.
```bash
cargo test -p biome_cli always_disable_trailing_commas_biome_json
```

fix(formatter): never format biome.json with trailing commas

---

CHANGELOG.md
crates/biome_cli/tests/commands/lint.rs
crates/biome_cli/tests/configs.rs
crates/biome_cli/tests/snapshots/main_commands_lint/downgrade_severity_info.snap
crates/biome_configuration/src/linter/mod.rs
packages/@biomejs/backend-jsonrpc/src/workspace.ts
packages/@biomejs/biome/configuration_schema.json

Now, rules can be downgraded to `"info"` severity

feat: allow `"info"` severity for analyzer rules

---

biome.json
crates/biome_formatter_test/src/lib.rs
crates/biome_lsp/src/session.rs
crates/biome_service/src/file_handlers/astro.rs
crates/biome_service/src/file_handlers/css.rs
crates/biome_service/src/file_handlers/javascript.rs
crates/biome_service/src/file_handlers/json.rs
crates/biome_service/src/file_handlers/mod.rs
crates/biome_service/src/file_handlers/svelte.rs
crates/biome_service/src/file_handlers/vue.rs
crates/biome_service/src/settings.rs
crates/biome_service/src/workspace/server.rs
package.json
pnpm-lock.yaml
pnpm-workspace.yaml
shared/biome.json

Closes https://github.com/biomejs/biome/issues/2976
This PR is an overhaul of our LSP's user experience. I baked this PR while flying 😛 
The fundamental issue we were having was the assumption that we always have valid **settings** - and when I say settings, I mean the ones that we store inside the `WorkspaceServer`. The settings come from different sources and clients: CLI, biome.json, LSP settings, etc. However, this was an incorrect assumption because sometimes the configuration can contain errors, hence we can't push settings into the `WorkspaceSettings`; we could push the default settings, but this is a mistake because otherwise Biome will format/lint with incorrect settings.
On the other hand, having defaults can come handy in some instances.
In this PR I applied the following …

feat(lsp): improve DX when the configuration has syntax errors

---

crates/biome_analyze/src/lib.rs
crates/biome_cli/src/commands/rage.rs
crates/biome_cli/tests/commands/rage.rs
crates/biome_cli/tests/snapshots/main_commands_rage/with_linter_configuration.snap
crates/biome_configuration/src/css.rs
crates/biome_configuration/src/javascript/formatter.rs
crates/biome_configuration/src/javascript/mod.rs
crates/biome_configuration/src/json.rs
crates/biome_configuration/src/lib.rs

This PR changes the `biome rage` output for the rules:
- it prints if the linter is enabled for the various languages
- it prints the enabled rules. It's a bit long, but at least we don't need to check which rules are recommended on the website.
Updated the snapshot

feat(cli): rage now prints all enabled rules 

---

CHANGELOG.md
crates/biome_formatter/src/token/string.rs
crates/biome_js_formatter/tests/specs/jsx/multiline_jsx_string/multiline_jsx_string.jsx
crates/biome_js_formatter/tests/specs/jsx/multiline_jsx_string/multiline_jsx_string.jsx.snap
crates/biome_js_formatter/tests/specs/jsx/multiline_jsx_string/options.json

Closes https://github.com/biomejs/biome/issues/2877
We manage line terminators in two steps:
1. Normalize line terminators during the IR generation phase by replacing `\r\n` with `\n`.
2. Replace `\n` with different line terminators based on the `line_ending` option.
It appears that the normalizing step is skipped for JSX strings.
Add new test cases

fix(js_formatter): correctly handle line terminators in JSX string

---

CHANGELOG.md
crates/biome_js_analyze/src/lint/correctness/use_exhaustive_dependencies.rs
crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/duplicateDependencies.js
crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/duplicateDependencies.js.snap

Disallow duplicate dependencies in hooks.
close #2956 
```jsx
import { useCallback } from "react";
function Component1({ a }) {
const handle = useCallback(() => {
console.log(a);
}, [a, a]);
}
function Component2() {
const [local,SetLocal] = useState(0);
const handle = useCallback(() => {
console.log(local);
}, [local, local]);
}
```

feat(lint): implement duplicate dependency error

---

CHANGELOG.md
crates/biome_configuration/src/linter/rules.rs
crates/biome_diagnostics_categories/src/categories.rs
crates/biome_js_analyze/src/lint/correctness/no_unused_variables.rs
crates/biome_js_analyze/src/lint/nursery.rs
crates/biome_js_analyze/src/lint/nursery/no_unused_function_parameters.rs
crates/biome_js_analyze/src/options.rs
crates/biome_js_analyze/tests/specs/nursery/noUnusedFunctionParameters/invalid.js
crates/biome_js_analyze/tests/specs/nursery/noUnusedFunctionParameters/invalid.js.snap
crates/biome_js_analyze/tests/specs/nursery/noUnusedFunctionParameters/invalid.ts
crates/biome_js_analyze/tests/specs/nursery/noUnusedFunctionParameters/invalid.ts.snap
crates/biome_js_analyze/tests/specs/nursery/noUnusedFunctionParameters/valid.js
crates/biome_js_analyze/tests/specs/nursery/noUnusedFunctionParameters/valid.js.snap
packages/@biomejs/backend-jsonrpc/src/workspace.ts
packages/@biomejs/biome/configuration_schema.json

This adds a new lint `noUnusedFunctionParameters` that detects unused parameters. Previously these were detected by `noUnusedVariables`.
I added tests for the new lint.

feat(noUnusedFunctionParameters): add lint for unused function parameters, instead of using noUnusedVariables

---

CHANGELOG.md
crates/biome_analyze/src/lib.rs
crates/biome_analyze/src/matcher.rs
crates/biome_analyze/src/registry.rs
crates/biome_analyze/src/rule.rs
crates/biome_js_analyze/src/lib.rs
crates/biome_js_analyze/src/lint/correctness/use_exhaustive_dependencies.rs
crates/biome_js_analyze/tests/quick_test.rs
crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/ignoredDependencies.js
crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/ignoredDependencies.js.snap
crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/valid.js
crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/valid.js.snap
crates/biome_rowan/src/syntax_node_text.rs
crates/biome_suppression/src/lib.rs

Allow suppression comments to suppress individual instances of rules. This is used for the lint rule `useExhaustiveDependencies`, which is now able to suppress specific dependencies.
The syntax for passing instances to suppress is `// biome-ignore lint/correctness/useExhaustiveDependencies(a): <explanation>` as documented in the `useExhaustiveDependencies` rule. The reason I opted for this syntax was pragmatic; our suppression parser already supported it. This does mean I'm kinda reusing a legacy syntax for a new purpose, though I see no clear conflicts in this approach. Let me know if you prefer a different approach though.
Fixes #2509.
Tests added.
I have also added a `quick_test.rs` in `biome_js_analyze` which helps with debugging lint rules a bit more easily.

feat(analyzer): suppress individual dependencies

---

crates/biome_js_analyze/src/lint/correctness/use_jsx_key_in_iterable.rs
crates/biome_js_analyze/tests/specs/correctness/useJsxKeyInIterable/valid.jsx
crates/biome_js_analyze/tests/specs/correctness/useJsxKeyInIterable/valid.jsx.snap

This PR fixes a false positive where the rule would flag variable declaration statements even if the return statement had a component with the `key` prop set.
fixes #3020
Added snapshot test

fix(lint/useJsxKeyInIterable): fix a false positive when key is in the return statement, but not any variable declarations

---

CHANGELOG.md
crates/biome_cli/tests/commands/init.rs
crates/biome_cli/tests/snapshots/main_commands_init/does_not_create_config_file_if_json_exists.snap
crates/biome_cli/tests/snapshots/main_commands_init/does_not_create_config_file_if_jsonc_exists.snap
crates/biome_service/src/configuration.rs

Fix https://github.com/biomejs/biome/issues/3024
Added tests

fix(cli): `biome init` won't generate config file if `biome.jsonc` already exists

---

crates/biome_cli/src/execute/migrate/eslint_any_rule_to_biome.rs
crates/biome_js_analyze/src/lint/style/no_unused_template_literal.rs

Citing `no-useless-template-literals` (now renamed [no-unnecessary-template-expression](https://typescript-eslint.io/rules/no-unnecessary-template-expression)) was an error.
The rules are different.
The ESLint rule reports template literals that only use literals in interpolation. It doesn't report a template literal without interpolation.
Our rule outputs an opposite behavior.
CI must pass.

refactor(noUnusedTemplateLiteral): remove rule sources

---

Cargo.lock
crates/biome_diagnostics/src/display.rs
crates/biome_grit_patterns/Cargo.toml
crates/biome_grit_patterns/src/errors.rs
crates/biome_grit_patterns/src/grit_analysis_ext.rs
crates/biome_grit_patterns/src/grit_context.rs
crates/biome_grit_patterns/src/grit_js_parser.rs
crates/biome_grit_patterns/src/grit_node.rs
crates/biome_grit_patterns/src/grit_node_patterns.rs
crates/biome_grit_patterns/src/grit_query.rs
crates/biome_grit_patterns/src/grit_target_language.rs
crates/biome_grit_patterns/src/grit_target_node.rs
crates/biome_grit_patterns/src/grit_tree.rs
crates/biome_grit_patterns/src/lib.rs
crates/biome_grit_patterns/src/pattern_compiler/literal_compiler.rs
crates/biome_grit_patterns/src/pattern_compiler/snippet_compiler.rs
crates/biome_grit_patterns/src/source_location_ext.rs
crates/biome_grit_patterns/tests/quick_test.rs

Grit patterns can contain [snippet literals](https://docs.grit.io/language/patterns#code-snippets) like such:
```
`console.log("foo");`
```
The part inside the backticks is a structural pattern that matches any function call node where the callee matches `console.log` and which has a single string argument with the content `foo`.
This PR updates the Grit crates and implements the parsing for snippet literals, so that our own Grit bindings invoke the Biome JS parser when a snippet like the above is encountered.
Added a quick test that helps with testing Grit patterns, although it still fails in the execution part. But at least it parses the query with a literal snippet now.

feat(grit): parse Grit literal snippets

---

crates/biome_js_analyze/src/lint/nursery/no_unused_function_parameters.rs

Fixing a typo in the documentation code example
Manually checked that it's correct

fix(noUnusedFunctionParameters): fix typo in documentation code example

---

crates/biome_graphql_factory/src/generated/node_factory.rs
crates/biome_graphql_factory/src/generated/syntax_factory.rs
crates/biome_graphql_parser/src/parser/definitions/enum.rs
crates/biome_graphql_parser/src/parser/definitions/mod.rs
crates/biome_graphql_parser/src/parser/parse_error.rs
crates/biome_graphql_parser/tests/graphql_test_suite/err/definitions/enum_extension.graphql
crates/biome_graphql_parser/tests/graphql_test_suite/err/definitions/enum_extension.graphql.snap
crates/biome_graphql_parser/tests/graphql_test_suite/err/definitions/interface_extension.graphql.snap
crates/biome_graphql_parser/tests/graphql_test_suite/err/definitions/object_extension.graphql.snap
crates/biome_graphql_parser/tests/graphql_test_suite/err/definitions/union_extension.graphql.snap
crates/biome_graphql_parser/tests/graphql_test_suite/ok/definitions/enum_extension.graphql
crates/biome_graphql_parser/tests/graphql_test_suite/ok/definitions/enum_extension.graphql.snap
crates/biome_graphql_syntax/src/generated/macros.rs
crates/biome_graphql_syntax/src/generated/nodes.rs
crates/biome_graphql_syntax/src/generated/nodes_mut.rs
crates/biome_graphql_syntax/src/lib.rs
xtask/codegen/graphql.ungram

Parse GraphQL enum extensions ([link](https://spec.graphql.org/October2021/#sec-Enum-Extensions)). Once this is completed, we will only have input object extensions ([link](https://spec.graphql.org/October2021/#sec-Input-Object-Extensions)) remaining before the GraphQL parser is ready for benchmarking.

feat(graphql_parser): parse enum extension

---

crates/biome_js_analyze/src/lint/style/use_naming_convention.rs

Fix the example of the `conventions` option.
CI must pass.

docs(useNamingConvention): fix conventions example

---

packages/@biomejs/biome/README.ja.md
packages/@biomejs/biome/README.md
packages/@biomejs/biome/README.pt-br.md
packages/@biomejs/biome/README.zh-CN.md

Fix command option for biome check, use `--write` instead of `--apply` in readme.
Should pass

docs(readme):  fix replace `apply` by `write` option

---

CHANGELOG.md
crates/biome_cli/examples/text_reporter.rs
crates/biome_cli/src/commands/check.rs
crates/biome_cli/src/commands/ci.rs
crates/biome_cli/src/commands/format.rs
crates/biome_cli/src/commands/lint.rs
crates/biome_cli/src/execute/mod.rs
crates/biome_cli/src/execute/traverse.rs
crates/biome_cli/src/lib.rs
crates/biome_cli/tests/commands/check.rs
crates/biome_cli/tests/commands/ci.rs
crates/biome_cli/tests/commands/format.rs
crates/biome_cli/tests/commands/lint.rs
crates/biome_cli/tests/snapshots/main_commands_check/should_error_if_unchanged_files_only_with_changed_flag.snap
crates/biome_cli/tests/snapshots/main_commands_check/should_error_if_unstaged_files_only_with_staged_flag.snap
crates/biome_cli/tests/snapshots/main_commands_ci/should_error_if_unchanged_files_only_with_changed_flag.snap
crates/biome_cli/tests/snapshots/main_commands_format/should_error_if_unchanged_files_only_with_changed_flag.snap
crates/biome_cli/tests/snapshots/main_commands_format/should_error_if_unstaged_files_only_with_staged_flag.snap
crates/biome_cli/tests/snapshots/main_commands_lint/should_error_if_unchanged_files_only_with_changed_flag.snap
crates/biome_cli/tests/snapshots/main_commands_lint/should_error_if_unstaged_files_only_with_staged_flag.snap

Closes #3069 
The PR #2726 overwrite the `biome (lint|format|check|ci)` command's target path when the path is empty.
But, when using `--staged` and `--changed` options, the path would be **intentionally** empty. When there is no file in staging (`--staged`) or there is no difference from a certain branch (`--changed`), the file to be executed need not exist.
So, in this PR, make sure that paths are not overwritten when either `--staged` or `--changed` is used.
Added snapshot cases.
And manually tested `--staged` and `--changed` commands.

fix(cli): prevent overwriting paths when using `--staged` or `--changed` options

---

crates/biome_js_analyze/tests/specs/nursery/useAdjacentOverloadSignatures/invalid.ts
crates/biome_js_analyze/tests/specs/nursery/useAdjacentOverloadSignatures/invalid.ts.snap

Fixes https://github.com/biomejs/biome/pull/3059#issue-2334048284
Run `just test-lintrule useAdjacentOverloadSignatures` on my latest code and checked that snapshot was updated correctly.

fix: `use-adjacent-overload-signature` diagnostic

---

.github/workflows/repository_dispatch.yml

So we can have [shorter urls](https://github.com/stackblitz-labs/pkg.pr.new/?tab=readme-ov-file#setup).
Also, GITHUB_TOKEN is no longer needed.
Merge to main.

chore(ci): use compact in pkg-pr-new command

---

packages/@biomejs/biome/configuration_schema.json
xtask/codegen/src/generate_schema.rs

Fix #3098
I really don't like the way we generate the schema for the rules. It is prone to errors. In the future, we should try a different approach: we could try to edit the schema directly in the code, instead of modifying the generated schema by traversing and patching it.
Locally tested.

chore: fix JSON schema for biome config file

---

CHANGELOG.md
crates/biome_formatter/src/builders.rs
crates/biome_js_analyze/src/lint/complexity/use_literal_keys.rs
crates/biome_js_analyze/tests/specs/complexity/useLiteralKeys/invalid.js
crates/biome_js_analyze/tests/specs/complexity/useLiteralKeys/invalid.js.snap
crates/biome_js_analyze/tests/specs/complexity/useLiteralKeys/invalid.ts
crates/biome_js_analyze/tests/specs/complexity/useLiteralKeys/invalid.ts.snap
crates/biome_js_analyze/tests/specs/complexity/useLiteralKeys/valid.js
crates/biome_js_analyze/tests/specs/complexity/useLiteralKeys/valid.js.snap
crates/biome_js_analyze/tests/specs/complexity/useLiteralKeys/valid.ts
crates/biome_js_analyze/tests/specs/complexity/useLiteralKeys/valid.ts.snap

Fix #3085
Note that we still report computed member names that can be simplified. Instead of simplifying to an identifier, we always simplify to a quoted property leaving the removal of the quotes to the formatter.

fix(useLiteralKeys): don't report quoted member names

---

CHANGELOG.md
crates/biome_js_analyze/src/lint/suspicious/no_empty_interface.rs
crates/biome_js_analyze/tests/specs/suspicious/noEmptyInterface/valid.d.ts
crates/biome_js_analyze/tests/specs/suspicious/noEmptyInterface/valid.d.ts.snap
crates/biome_js_analyze/tests/specs/suspicious/noEmptyInterface/valid.ts
crates/biome_js_analyze/tests/specs/suspicious/noEmptyInterface/valid.ts.snap

Fix #3110
We now accept empty interfaces in global declarations `declare global {}` and ambient modules `declare module "mod" {}`.
I added tests.

fix(noEmptyInterface): ignore empty interfaces in ambient modules

---

crates/biome_analyze/src/rule.rs
crates/biome_cli/src/execute/migrate/eslint_any_rule_to_biome.rs
crates/biome_js_analyze/src/lint/correctness/no_unused_imports.rs
crates/biome_js_analyze/src/lint/correctness/no_unused_variables.rs
crates/biome_js_analyze/src/lint/style/use_while.rs

Address https://github.com/biomejs/biome/discussions/3#discussioncomment-9709522
CI must pass.

refactor(lint): add SonarJs and UnusedImports rule sources

---

crates/biome_graphql_parser/src/lexer/mod.rs
crates/biome_graphql_parser/src/lexer/tests.rs

According to the GraphQL documentation, backslash characters can be used unescaped within a block string ([link](https://spec.graphql.org/October2021/#sec-String-Value.Block-Strings)).
All tests should pass.

fix(graphql_parser): allow backlash in block string

---

CHANGELOG.md
crates/biome_css_formatter/src/comments.rs
crates/biome_css_formatter/src/css/auxiliary/function.rs
crates/biome_css_formatter/src/css/lists/layer_name_list.rs
crates/biome_css_formatter/src/css/value/identifier.rs
crates/biome_css_formatter/src/separated.rs
crates/biome_css_formatter/tests/specs/css/atrule/import.css.snap
crates/biome_css_formatter/tests/specs/css/atrule/layer.css
crates/biome_css_formatter/tests/specs/css/atrule/layer.css.snap
crates/biome_css_formatter/tests/specs/css/casing.css.snap
crates/biome_css_formatter/tests/specs/css/properties/all.css
crates/biome_css_formatter/tests/specs/css/properties/all.css.snap
crates/biome_css_formatter/tests/specs/prettier/css/case/case.css.snap
crates/biome_css_formatter/tests/specs/prettier/css/color/color-adjuster.css.snap
crates/biome_css_formatter/tests/specs/prettier/css/loose/loose.css.snap
crates/biome_css_formatter/tests/specs/prettier/css/parens/parens.css.snap
crates/biome_css_parser/src/syntax/property/mod.rs
crates/biome_css_parser/tests/css_test_suite/error/property/property_generic_error.css.snap
crates/biome_css_parser/tests/css_test_suite/ok/at_rule/at_rule_container.css.snap
crates/biome_css_parser/tests/css_test_suite/ok/at_rule/at_rule_container_complex.css.snap
crates/biome_css_parser/tests/css_test_suite/ok/at_rule/at_rule_supports.css.snap
crates/biome_css_parser/tests/css_test_suite/ok/declaration_list.css.snap
crates/biome_css_parser/tests/css_test_suite/ok/function/calc.css.snap
crates/biome_css_parser/tests/css_test_suite/ok/property/property_generic.css.snap
crates/biome_css_parser/tests/css_test_suite/ok/values/url_value.css.snap

Fix https://github.com/biomejs/biome/issues/3068
We have several ways to prevent case changes while formatting:
1. We use custom identifiers during parsing.
2. We pass parameters to the identifier formatter to prevent parsing.
However, using custom identifiers in places where they aren't specified as part of the specification may not be ideal. So I avoid that places and pass a parameter for a formatter.
`cargo test`

fix(css_formatter): fix CSS formatter converts variable declarations and function calls to lowercase #3068

---

.github/workflows/pull_request.yml
Cargo.lock
Cargo.toml
justfile
xtask/rules_check/Cargo.toml
xtask/rules_check/src/lib.rs
xtask/rules_check/src/main.rs

This PR restores a script that checks the validity of the docs of our rules. This code was copied from the website repository and stripped of all the logic regarding generating the docs. 
Plus, it adds this check inside the CI and `gen-lint`
CI should pass

ci: add check for rules docs

---

CHANGELOG.md
crates/biome_js_analyze/src/lint/correctness/no_unused_variables.rs
crates/biome_js_analyze/src/lint/nursery/no_unused_function_parameters.rs
crates/biome_js_analyze/tests/specs/correctness/noUnusedVariables/validType.ts
crates/biome_js_analyze/tests/specs/correctness/noUnusedVariables/validType.ts.snap
crates/biome_js_analyze/tests/specs/nursery/noUnusedFunctionParameters/valid.ts
crates/biome_js_analyze/tests/specs/nursery/noUnusedFunctionParameters/valid.ts.snap
crates/biome_js_syntax/src/binding_ext.rs

Fix #3135
I added non-regression tests.

fix(noUnusedVariables): don't report params in contructor types

---

CHANGELOG.md
crates/biome_aria/src/macros.rs
crates/biome_aria/src/roles.rs
crates/biome_js_analyze/src/lint/nursery/use_semantic_elements.rs
crates/biome_js_analyze/tests/specs/nursery/useSemanticElements/invalid.jsx.snap

Implements [this comment](https://github.com/biomejs/biome/pull/2867#discussion_r1605976026).
Finally, we can get alternative element.
```tsx
! The elements with the following roles can be changed to the following elements:
<input type="checkbox">
1 │ <>
> 2 │     <div role="checkbox" ></div>
│          ^^^^
3 │     <div role="radio" ></div>
4 │     <div role="option" ></div>
```

feat(lint): display correspinding element

---

CHANGELOG.md
crates/biome_css_formatter/src/css/auxiliary/bracketed_value.rs
crates/biome_css_formatter/src/css/properties/composes_property.rs
crates/biome_css_formatter/src/css/properties/value_at_rule_generic_property.rs
crates/biome_css_formatter/src/utils/component_value_list.rs
crates/biome_css_formatter/tests/quick_test.rs
crates/biome_css_formatter/tests/specs/css/properties/grid.css.snap
crates/biome_css_formatter/tests/specs/prettier/css/grid/grid.css.snap

Format the CSS grid property as Prettier does.
https://github.com/prettier/prettier/blob/d8d4732e521f01c73350b8faed5d6473861b8d01/src/language-css/print/comma-separated-value-group.js#L344-L358
`cargo test`

fix(css_formatter): fix CSS formatting for css values

---

CHANGELOG.md
crates/biome_configuration/src/linter/rules.rs
crates/biome_css_analyze/src/lint/nursery/no_unmatchable_anb_selector.rs
crates/biome_css_analyze/tests/specs/nursery/noUnmatchableAnbSelector/invalid.css.snap
packages/@biomejs/backend-jsonrpc/src/workspace.ts
packages/@biomejs/biome/configuration_schema.json
xtask/rules_check/src/lib.rs

- The file name `format!("{group}/{rule}.js")` displayed in the code block diagnostics is misleading, I changed it to `rule-doc-code-block`.
- When diagnostics are unexpected or the number of them is greater than 2, only the diagnostics themselves were printed, but the error messages were not. I printed them before `ControlFlow::Break`.
- For JSON and CSS rules, we didn't check them when diagnostices were expected but none were printed. This fix helps us catch a failure codeblock in `nursery/noUnmatchableAnbSelector`.
- `Fixkind` mismatch can be catched by the compiler, so I removed the check.
CI should pass when the rule `nursery/noUnmatchableAnbSelector` is fixed.

fix(ci): rule check error messages

---

CHANGELOG.md

- Add changelog entry for the new feature introduced in #2958
- Fix typo in link to noUnknownUnit documentation in `CHANGELOG.md`
- The corrected link now points to the correct documentation for Biome

docs: add entry for noShorthandPropertyOverrides to CHANGELOG.md

---

crates/biome_json_parser/src/parser.rs
xtask/rules_check/src/lib.rs

- Discard `BlockType` and use `DocumentFileSource` as the single source of truth.
- Retain the code block tag from the input instead of regenerating it.
- Use `code-block.{js,css,json...}` as the file path displayed in code block diagnostics.
I will apply the same modifications to the codegen task in the website repo after this is merged.

chore(ci): improve rules_check task

---

crates/biome_js_analyze/src/lint/a11y/no_aria_hidden_on_focusable.rs
crates/biome_js_analyze/src/lint/a11y/no_svg_without_title.rs
crates/biome_js_analyze/src/lint/a11y/use_valid_aria_role.rs
crates/biome_js_analyze/src/lint/correctness/no_children_prop.rs
crates/biome_js_analyze/src/lint/correctness/use_jsx_key_in_iterable.rs
crates/biome_js_analyze/src/lint/nursery/no_react_specific_props.rs
crates/biome_js_analyze/src/lint/nursery/use_focusable_interactive.rs
crates/biome_js_analyze/src/lint/style/use_fragment_syntax.rs
crates/biome_js_analyze/src/lint/style/use_self_closing_elements.rs
crates/biome_js_analyze/src/lint/suspicious/no_array_index_key.rs
crates/biome_js_analyze/src/lint/suspicious/no_comment_text.rs
crates/biome_js_analyze/src/lint/suspicious/no_duplicate_jsx_props.rs
crates/biome_js_analyze/src/lint/suspicious/no_suspicious_semicolon_in_jsx.rs

Just want to keep things in order.

chore: change `js` code blocks containing JSX elements to `jsx`

---

CHANGELOG.md
crates/biome_cli/src/commands/rage.rs
crates/biome_cli/tests/snapshots/main_commands_rage/with_formatter_configuration.snap
crates/biome_configuration/src/css.rs
crates/biome_css_formatter/src/context.rs
crates/biome_service/src/file_handlers/css.rs
crates/biome_service/src/settings.rs

Closes https://github.com/biomejs/biome/issues/3103
- add a new test 
- update an existing test and a snapshot

fix(css_formatter): correctly resolve css format options

---

Cargo.lock
crates/biome_grit_patterns/Cargo.toml
crates/biome_grit_patterns/src/errors.rs
crates/biome_grit_patterns/src/grit_binding.rs
crates/biome_grit_patterns/src/grit_code_snippet.rs
crates/biome_grit_patterns/src/grit_context.rs
crates/biome_grit_patterns/src/grit_file.rs
crates/biome_grit_patterns/src/grit_node_patterns.rs
crates/biome_grit_patterns/src/grit_query.rs
crates/biome_grit_patterns/src/grit_resolved_pattern.rs
crates/biome_grit_patterns/src/grit_target_node.rs
crates/biome_grit_patterns/src/lib.rs
crates/biome_grit_patterns/src/pattern_compiler.rs
crates/biome_grit_patterns/src/pattern_compiler/snippet_compiler.rs
crates/biome_grit_patterns/tests/quick_test.rs
crates/biome_rowan/src/syntax/token.rs

This implements the Grit snippet bindings. 
The quick test now passes, but it only tests that it completes. It doesn't test the actual matching yet, so there's still a lot of `todo!()`s left, and then there's probably still plenty of bugs as well :sweat_smile:

chore(grit): implement Grit snippet bindings

---

crates/biome_js_analyze/src/lint/style/use_import_type.rs

This partially address https://github.com/biomejs/website/issues/50
CI must pass.

docs(useImportType): add docs about TypeScript settings

---

crates/biome_js_analyze/src/lint/nursery/no_undeclared_dependencies.rs
crates/biome_js_analyze/src/lint/nursery/use_import_extensions.rs

Address https://github.com/biomejs/website/issues/50#issuecomment-2160679956
CI must pass.

docs(noUndeclaredDependencies,useImportExtensions): add note about LSP configs

---

crates/biome_js_analyze/src/lint/nursery/no_undeclared_dependencies.rs

docs(no_undeclared_dependencies): follow up fix of #3173

---

.github/workflows/repository_dispatch.yml

We fixed the manifest files in #3155, let's try enabling `--compact` again.
Merge to main.

chore(ci): try enable `--compact` flag for `pkg.pr.new`

---

.github/workflows/repository_dispatch.yml

It doesn't work for 2 reasons:
1. We haven't published the fix.
2. The `sideEffect` field fails the zod validation.
I'll report the issue to upstream.

chore(ci): remove `--compact` flag

---

crates/biome_formatter/src/format_element/document.rs

Double quotes in source code when printing formatter IR were previously not escaped, causing poor syntax highlighing on the playground. This PR escapes quotes with a simple string replacement.
fixes #1056
CI should pass, ~~but I'm not sure where to add a test for this.~~ I've added a unit test for this.

fix(formatter): escape double quotes when printing formatter IR

---

crates/biome_js_analyze/src/lint/a11y/use_key_with_click_events.rs

The two examples given only differed on how the div element was closed (self-closing vs non-self-closing), which is not relevant to the rule at hand. To avoid confusing the reader, let's keep only one of the examples.
The non-self-closing case is tested explicitly in the dedicated test cases for useKeyWithClickEvents, so we don't loose any test coverage with this change.
Moved here from https://github.com/biomejs/website/pull/591

fix: remove unnecessary example

---

CHANGELOG.md
crates/biome_cli/tests/cases/overrides_formatter.rs
crates/biome_cli/tests/cases/overrides_linter.rs
crates/biome_cli/tests/snapshots/main_cases_overrides_formatter/does_not_conceal_previous_overrides.snap
crates/biome_cli/tests/snapshots/main_cases_overrides_formatter/takes_last_formatter_enabled_into_account.snap
crates/biome_cli/tests/snapshots/main_cases_overrides_linter/does_merge_all_overrides.snap
crates/biome_cli/tests/snapshots/main_cases_overrides_linter/does_not_conceal_overrides_globals.snap
crates/biome_cli/tests/snapshots/main_cases_overrides_linter/takes_last_linter_enabled_into_account.snap
crates/biome_service/src/file_handlers/javascript.rs
crates/biome_service/src/settings.rs

Fix #3176
When we convert the Biome Configuration to Workspace settings, we use the base settings to set the missing settings in every override. This results in overrides that conceal previous overrides.
For example, the following config:
```json
{
"linter": {
"rules": {
"suspicious": { "noDebugger": "off" }
}
},
"overrides": [
{
"include": ["index.js"],
"linter": {
"rules": {
"suspicious": { "noDebugger": "warn" }
}
}
}, {
"include": ["index.js"]
}
]
}
```
was resolved to:
```json
{
"linter": {
"rules": {
"suspicious": { "noDebugger": "off" }
}
},
"overrides": [
{
"include": ["index.js"],
"linter": {
"rules": {
"suspicious": { "noDebugger": "warn" }
}
}
}, {
"include": ["index.js"],
"linter": {
"rules": {
"suspicious": { "noDebugger": "off" }
}
}
}
]
}
```
The current PR fixes the issue …

fix(config): don't conceal a previous override with the base settings

---

CHANGELOG.md
crates/biome_css_analyze/src/lint/nursery/no_unknown_property.rs
crates/biome_css_analyze/tests/specs/nursery/noUnknownProperty/valid.css
crates/biome_css_analyze/tests/specs/nursery/noUnknownProperty/valid.css.snap

Closes #3092.
Prevent warnings from being thrown for [Custom properties (--*)](https://developer.mozilla.org/en-US/docs/Web/CSS/--*).

fix(noUnknownProperty): prevent warning on CSS custom property

---

CHANGELOG.md
crates/biome_js_analyze/src/lint/correctness/use_jsx_key_in_iterable.rs
crates/biome_js_analyze/tests/specs/correctness/useJsxKeyInIterable/valid.jsx
crates/biome_js_analyze/tests/specs/correctness/useJsxKeyInIterable/valid.jsx.snap

Closes #3084 by fixing the cast when the returned component is parenthesized.
```js
[].map((el) => {
const content = <p>Paragraph</p>
return (<div key={el}>{content}</div>); // will cast successfully
});
```
Added a snapshot case.

fix(lint/useJsxKeyInIterable): fix a false positive when key is in parenthesized return statement

---

CHANGELOG.md
crates/biome_cli/src/commands/migrate.rs
crates/biome_migrate/src/analyzers/nursery_rules.rs
crates/biome_migrate/tests/specs/migrations/nurseryRules/existingGroupWithExistingRule.json
crates/biome_migrate/tests/specs/migrations/nurseryRules/existingGroupWithExistingRule.json.snap
crates/biome_migrate/tests/specs/migrations/nurseryRules/firstToExistingGroup.json
crates/biome_migrate/tests/specs/migrations/nurseryRules/firstToExistingGroup.json.snap
crates/biome_migrate/tests/specs/migrations/nurseryRules/lastToExistingGroup.json
crates/biome_migrate/tests/specs/migrations/nurseryRules/lastToExistingGroup.json.snap
crates/biome_migrate/tests/specs/migrations/nurseryRules/middleToExistingGroup.json
crates/biome_migrate/tests/specs/migrations/nurseryRules/middleToExistingGroup.json.snap
crates/biome_migrate/tests/specs/migrations/nurseryRules/renamedRuleAndNewRule.json.snap
crates/biome_migrate/tests/specs/migrations/nurseryRules/singleToExistingGroup.json
crates/biome_migrate/tests/specs/migrations/nurseryRules/singleToExistingGroup.json.snap

- Fixes #3179. `biome migrate` can now properly handle the comma separators when removing stale nursery rules from the nursery group.
- When the target rule is already present in the target group, but the source rule is also present in the `nursery` group, `biome migrate` now only removes the source rule from the `nursery` group to avoid duplicate keys in the target group.
- Demote `useImportRestrictions`, see https://github.com/biomejs/biome/pull/3207#issuecomment-2167252053
Sorry about the diff. I had to rename most of the variables to understand the code.
Added several test cases where the nursery rule to migrate is present in different positions. I also tested the repo provided in #3179.

fix(migrate): properly handle rule removal and insertion

---

CHANGELOG.md
crates/biome_js_analyze/src/lint/complexity/use_literal_keys.rs
crates/biome_js_analyze/tests/specs/complexity/useLiteralKeys/invalid.js
crates/biome_js_analyze/tests/specs/complexity/useLiteralKeys/invalid.js.snap
crates/biome_js_analyze/tests/specs/complexity/useLiteralKeys/invalid.ts.snap
crates/biome_js_analyze/tests/specs/complexity/useLiteralKeys/valid.js
crates/biome_js_analyze/tests/specs/complexity/useLiteralKeys/valid.js.snap

Fixes #3160. This rule now ignores the following kind of computed member name:
```js
const a = {
[`line1
line2`]: true,
};
```

fix(lint/useLiteralKeys): unescaped newline false positive

---

crates/biome_analyze/src/options.rs
crates/biome_analyze/src/registry.rs
crates/biome_analyze/src/signals.rs
crates/biome_deserialize/src/impls.rs
crates/biome_formatter/src/lib.rs
crates/biome_js_analyze/src/lint/nursery/use_sorted_classes/sort_config.rs
crates/biome_text_size/src/size.rs
rust-toolchain.toml
xtask/codegen/src/js_kinds_src.rs

Flagged some dead code, and simplified some code inside our analyzer
CI should pass

chore: rust 1.79.0

---

CHANGELOG.md
crates/biome_css_analyze/src/lint/nursery/no_unknown_property.rs
crates/biome_css_analyze/tests/specs/nursery/noUnknownProperty/valid.css
crates/biome_css_analyze/tests/specs/nursery/noUnknownProperty/valid.css.snap

fix(lint/noUnknownProperty): ignore `composes` for noUnknownProperty

---

CHANGELOG.md
crates/biome_js_analyze/src/lint/correctness/use_exhaustive_dependencies.rs
crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/exportDefaultClass.js
crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/exportDefaultClass.js.snap
crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/recursiveComponents.js
crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/recursiveComponents.js.snap

Fix false positives of the [useExhaustiveDependencies](https://biomejs.dev/linter/rules/use-exhaustive-dependencies/) rule:
- The component itself is considered stable when it is used recursively inside a hook closure defined inside of it:
```jsx
import { useMemo } from "react";
function MyRecursiveComponent() {
// MyRecursiveComponent is stable, we don't need to add it to the dependencies list.
const children = useMemo(() => <MyRecursiveComponent />, []);
return <div>{children}</div>;
}
```
- Also, `export default function` and `export default class` are considered stable now because they can only appear at the top level of a module.
Closes #3212
Added several valid test cases.

fix(lint/useExhaustiveDependencies): false positives

---

CHANGELOG.md

The docs site uses `-` to separate camel-case tokens, not `_`. The links for `nursery/useErrorMessage` and `nursery/useThrowOnlyError` now resolve.
Click the links :)
I briefly scanned through the changelog for similar typos, but only found these two.

chore: fix changelog links to nursery rules useErrorMessage and useThrowOnlyError

---

CHANGELOG.md
crates/biome_service/src/file_handlers/javascript.rs

Ref: https://vuejs.org/api/sfc-script-setup.html#default-props-values-when-using-type-declaration
Besides that, I also sorted the positions based on [`vue/define-macros-order`](https://eslint.vuejs.org/rules/define-macros-order.html).

fix(javascript/vue): missing withDefaults macro

---

CHANGELOG.md
crates/biome_cli/src/main.rs

Closes https://github.com/biomejs/biome/issues/3232
I tested it locally, and now `--colors=off` doesn't show any colours

fix(cli): correctly compute the color mode in `ci`

---

CHANGELOG.md
packages/@biomejs/biome/package.json
packages/@biomejs/js-api/package.json

Updated the changelog and the packages to publish
CI should pass

release: v1.8.2

---

crates/biome_configuration/src/diagnostics.rs
crates/biome_configuration/src/editorconfig.rs

This makes it so that we can fully support all editorconfig glob patterns. Adding support to the vendored `glob` package is already done, but the functionality is gated behind behind a flag to not cause a breaking change (discussed in #2986).
This should allow us to reenable loading `.editorconfig` files, which is to be done in a subsequent PR.
related to: #1724
related to: #2986
replaces: #3028
Added unit tests
```bash
cargo test -p biome_configuration editorconfig
```

feat(editorconfig): expand unknown globs into known globs

---

crates/biome_service/src/file_handlers/graphql.rs
crates/biome_service/src/file_handlers/mod.rs
crates/biome_service/tests/workspace.rs

This PR implements the `pull_diagnostics` function for the graphql handler. This is harmless, as it only pulls the parsing diagnostics. 
I also enabled the GraphQL support during testing, so we can add internal tests like I did in the PR
CI should pass

chore(core): implement `pull_diagnostics` for graphql

---

CHANGELOG.md
crates/biome_cli/src/execute/migrate/node.rs

Fixes #3104 by setting the `NODE_NO_WARNINGS` env variable

fix(migrate): suppress node warnings

---

crates/biome_cli/tests/cases/overrides_formatter.rs
crates/biome_cli/tests/snapshots/main_cases_overrides_formatter/does_not_override_well_known_special_files_when_config_override_is_present.snap

This one is kinda weird, and this doesn't really feel like the correct fix. I'm unfamiliar with this area of the codebase.
If an override is applied to a json file that is considered "well known" to be parsed with trailing commas and/or comments, then those settings will not be applied because the override is present (not necessarily using the override's value, if the settings are cached).
For example, if we add the following override to this repo's `biome.json`, running `biome check` will fail, even though it should be effectively a no-op.
```json
"overrides": [
{
"include": ["**/*.json"],
"formatter": {
"indentStyle": "space"
}
}
]
```
Note that json files that have different default parsing settings, that also match the override must be checked. The following command does _not_ …

test(parse/json): add test for bug where overrides erroneously override special parsing options

---

crates/biome_analyze/CONTRIBUTING.md

While working on https://github.com/biomejs/biome/pull/3241 I found it difficult to apply diagnostic, for multiple ranges. I found answer on Discord but that was not very obvious, so it should prob be documented.
It is bit rough, but I hope this can be starting point.
not needed

docs(analyzer): improve contributing guide for rules with multiple signals

---

Cargo.lock
Cargo.toml
crates/biome_graphql_analyze/Cargo.toml
crates/biome_graphql_analyze/src/lib.rs
crates/biome_graphql_analyze/src/lint.rs
crates/biome_graphql_analyze/src/lint/nursery.rs
crates/biome_graphql_analyze/src/lint/nursery/use_dummy_rule.rs
crates/biome_graphql_analyze/src/options.rs
crates/biome_graphql_analyze/src/registry.rs
crates/biome_graphql_analyze/src/suppression_action.rs
crates/biome_graphql_analyze/tests/spec_tests.rs
crates/biome_graphql_analyze/tests/specs/nursery/useDummyRule/valid.graphql
crates/biome_graphql_analyze/tests/specs/nursery/useDummyRule/valid.graphql.snap
justfile
knope.toml
xtask/codegen/src/generate_analyzer.rs
xtask/codegen/src/generate_new_analyzer_rule.rs

This PR initialize the `biome_graphql_analyze` crate and its infrastructure.
I added a `just new-graphql-lintrule` script.
CI should pass

chore(lint): initialise `biome_graphql_analyze`

---

crates/biome_js_analyze/src/lint/style/use_naming_convention.rs

Take [feedbacks](https://github.com/biomejs/biome/discussions/3236#discussioncomment-9839657) into account.
CI must pass.

docs(useNamingConvention): add examples and improve explanations

---

CHANGELOG.md
crates/biome_js_analyze/src/lint/style/use_consistent_array_type.rs
crates/biome_js_analyze/src/lint/style/use_shorthand_array_type.rs
crates/biome_js_analyze/tests/specs/style/useConsistentArrayType/valid.ts
crates/biome_js_analyze/tests/specs/style/useConsistentArrayType/valid.ts.snap
crates/biome_js_analyze/tests/specs/style/useShorthandArrayType/valid.ts
crates/biome_js_analyze/tests/specs/style/useShorthandArrayType/valid.ts.snap

fix(useConsistentArrayType): ignore `Array` in `extends`/`implements` clauses

---

CHANGELOG.md
crates/biome_cli/src/cli_options.rs
crates/biome_cli/src/commands/mod.rs
crates/biome_cli/src/main.rs
crates/biome_cli/tests/snapshots/main_commands_check/check_help.snap
crates/biome_cli/tests/snapshots/main_commands_ci/ci_help.snap
crates/biome_cli/tests/snapshots/main_commands_format/format_help.snap
crates/biome_cli/tests/snapshots/main_commands_lint/lint_help.snap
crates/biome_cli/tests/snapshots/main_commands_migrate/migrate_help.snap
crates/biome_cli/tests/snapshots/main_commands_rage/rage_help.snap
packages/tailwindcss-config-analyzer/src/generate-tailwind-preset.ts

Fixes #3148
I ran the command locally: `cargo run --bin biome lint ./test.js --reporter=github`

fix(cli): disable colors when using the github reporter

---

CHANGELOG.md
crates/biome_configuration/src/linter/rules.rs
crates/biome_diagnostics_categories/src/categories.rs
crates/biome_js_analyze/src/lint/correctness/no_nodejs_modules.rs
crates/biome_js_analyze/src/lint/nursery.rs
crates/biome_js_analyze/src/lint/nursery/no_exported_imports.rs
crates/biome_js_analyze/src/lint/nursery/no_restricted_imports.rs
crates/biome_js_analyze/src/lint/nursery/no_undeclared_dependencies.rs
crates/biome_js_analyze/src/lint/nursery/use_import_extensions.rs
crates/biome_js_analyze/src/lint/style/use_node_assert_strict.rs
crates/biome_js_analyze/src/lint/style/use_nodejs_import_protocol.rs
crates/biome_js_analyze/src/lint/suspicious/no_import_assign.rs
crates/biome_js_analyze/src/options.rs
crates/biome_js_analyze/tests/specs/nursery/noExportedImports/invalid.js
crates/biome_js_analyze/tests/specs/nursery/noExportedImports/invalid.js.snap
crates/biome_js_analyze/tests/specs/nursery/noExportedImports/valid.js
crates/biome_js_analyze/tests/specs/nursery/noExportedImports/valid.js.snap
crates/biome_js_syntax/src/import_ext.rs
packages/@biomejs/backend-jsonrpc/src/workspace.ts
packages/@biomejs/biome/configuration_schema.json

Add a new exclusive rule for Biome.
The rule disallows exporting an imported variable and suggests using `export from`.
This is an implementation I had done some time ago. I had intended to add a code fix before submitting a PR.
However, I now think that the rule is ok without a code ix.

feat(noExportedImports): add lint rule

---

crates/biome_json_parser/tests/spec_test.rs
crates/biome_service/src/file_handlers/json.rs
crates/biome_service/src/settings.rs

This changes the JSON parser options to use `Option<bool>` for better semantics when dealing with default values and fallbacks.
as discussed here: https://github.com/biomejs/biome/pull/3260#issuecomment-2185010285
CI should pass

refactor(parse/json): change fields in `JsonParserSettings` to `Option`
