README.md
packages/@biomejs/biome/README.md

- use badgen.net, the successor of shields.io, for badges
- rename the project to Biome
- update various links
- Improve the presentation of the project

docs(README): update to Biome

---

.github/workflows/release_cli.yml
.github/workflows/release_js_api.yml
.github/workflows/release_lsp.yml
editors/vscode/README.md
editors/vscode/package-lock.json
editors/vscode/package.json
website/src/pages/vscode.mdx

- fixes the publisher name
- updates to use the new version of a deprecated action (it was using node 12)
- fixed CI workflow to correctly use the non-deprecated version of `vcse`
Merge it and see if that works

chore: fix publisher and action publishing

---

benchmark/README.md
crates/rome_analyze/CONTRIBUTING.md
crates/rome_analyze/README.md
crates/rome_cli/README.md
crates/rome_css_parser/README.md
crates/rome_diagnostics/CONTRIBUTING.md
crates/rome_diagnostics/README.md
crates/rome_diagnostics_categories/README.md
crates/rome_formatter/README.md
crates/rome_js_factory/README.md
crates/rome_js_formatter/README.md
crates/rome_js_parser/README.md
crates/rome_js_semantic/README.md
crates/rome_js_syntax/README.md
crates/rome_json_formatter/README.md
crates/rome_json_parser/README.md
crates/rome_service/README.md
editors/helix/manual.md
editors/vscode/README.md
fuzz/README.md
packages/@biomejs/js-api/README.md
rfcs/002-runtime-api.md
website/src/pages/vscode.mdx
xtask/codegen/README.md

Rename Rome to Biome in internal docs.
Rename LSP `rome.rome` to `biomejs.biome`.
CI

docs: update internal docs

---

.github/ISSUE_TEMPLATE/01_bug.yml
.github/workflows/pull_request_js.yml
CHANGELOG.md
Cargo.toml
LICENSE
crates/rome_console/LICENSE
crates/rome_css_parser/LICENSE
crates/rome_diagnostics/LICENSE
crates/rome_formatter/LICENSE
crates/rome_js_formatter/LICENSE
crates/rome_js_parser/LICENSE
crates/rome_js_semantic/LICENSE
crates/rome_js_syntax/LICENSE
crates/rome_json_formatter/LICENSE
crates/rome_json_parser/LICENSE
editors/vscode/LICENSE
editors/vscode/README.md
editors/vscode/package.json
justfile
packages/@biomejs/backend-jsonrpc/package.json
packages/@biomejs/biome/scripts/postinstall.js
packages/@biomejs/js-api/package.json
website/src/components/cli-screenshots/init.md
website/src/pages/vscode.mdx
website/src/playground/components/RomeHeader.tsx
website/src/playground/tabs/FormatterCodeTab.tsx

This PR updates the LICENSE files with proper credits to Rome Tools and other projects.
This also add some contexts in the CHANGELOG file and apply more renaming. 
CI.

refactor: more renamings to Biome

---

website/src/pages/credits.mdx

This removes the Alumni section of the credits page.

chore(website): remove Alumni

---

editors/vscode/package.json
packages/@biomejs/biome/bin/biome
packages/@biomejs/biome/package.json

fix: path to correct binary

---

crates/rome_js_analyze/src/analyzers/nursery/use_getter_return.rs
crates/rome_service/src/configuration/linter/rules.rs
editors/vscode/configuration_schema.json
packages/@biomejs/backend-jsonrpc/src/workspace.ts
packages/@biomejs/biome/configuration_schema.json
website/src/pages/lint/rules/index.mdx
website/src/pages/lint/rules/useGetterReturn.md

Fix rule docs and add an example demonstrating control flow capabilities.
No change.

refactor(lint/useGetterReturn): improve rule docs

---

CODE_OF_CONDUCT.md
packages/@biomejs/biome/README.md

We don't have Rust docs for now (will work on that later).
I updated the CoC to 2.1, and updated the email.
N/A

chore: better readme and code of conduct

---

crates/rome_deserialize/src/json.rs
crates/rome_js_analyze/src/analyzers/a11y/no_blank_target.rs
crates/rome_js_analyze/src/analyzers/a11y/use_alt_text.rs
crates/rome_js_analyze/src/analyzers/a11y/use_html_lang.rs
crates/rome_js_analyze/src/analyzers/a11y/use_iframe_title.rs
crates/rome_js_analyze/src/analyzers/a11y/use_key_with_mouse_events.rs
crates/rome_js_analyze/src/analyzers/complexity/no_extra_boolean_cast.rs
crates/rome_js_analyze/src/analyzers/correctness/no_inner_declarations.rs
crates/rome_js_analyze/src/analyzers/correctness/no_switch_declarations.rs
crates/rome_js_analyze/src/analyzers/correctness/no_unreachable_super.rs
crates/rome_js_analyze/src/analyzers/correctness/no_unused_labels.rs
crates/rome_js_analyze/src/analyzers/correctness/use_yield.rs
crates/rome_js_analyze/src/semantic_analyzers/nursery/no_constant_condition.rs
crates/rome_js_analyze/src/semantic_analyzers/nursery/use_exhaustive_dependencies.rs
crates/rome_js_analyze/src/suppression_action.rs
crates/rome_js_formatter/src/js/expressions/logical_expression.rs
crates/rome_js_formatter/src/js/expressions/string_literal_expression.rs
crates/rome_js_formatter/src/utils/string_utils.rs
crates/rome_js_syntax/src/expr_ext.rs
crates/rome_js_syntax/src/jsx_ext.rs

Avoid some cloning.
```
cargo test
```

refactor: avoid some cloning

---

website/src/pages/internals/language_support.mdx

Updates the supported version of JavaScript to ES2023 and the supported version of TypeSCript to 5.2

docs(website): update supported version of JavaScript and TypeScript

---

editors/vscode/README.md
website/src/pages/analyzer/index.mdx
website/src/pages/formatter/index.mdx
website/src/pages/guides/getting-started.mdx
website/src/pages/internals/philosophy.mdx
website/src/pages/vscode.mdx

- Improve formatting (newline for every sentence)
- Remove an erroneous link
- Improve some wording
Manual.

docs(website): improve formatting, remove an erroneous link

---

editors/vscode/package.json
packages/@biomejs/biome/package.json

release: v1.0.0

---

CONTRIBUTING.md

Update Discord invite link in `CONTRIBUTING.md`

docs(CONTRIBUTING): update Discord invite link

---

CHANGELOG.md
website/src/pages/internals/changelog.mdx

- update version
- use labeled links for lint rules

docs(CHANGELOG): update version

---

website/src/pages/blog/annoucing-biome.mdx

Make note of the new features during the _rome to biome_ section
[Discord discussion](https://discord.com/channels/1132231889290285117/1132231889911029825/1146214855829885129)

blog: mention new features in first migration step

---

crates/rome_cli/src/commands/init.rs
crates/rome_cli/tests/snapshots/main_commands_init/creates_config_file.snap
crates/rome_cli/tests/snapshots/main_commands_init/creates_config_file_when_rome_installed_via_package_manager.snap
editors/vscode/configuration_schema.json
packages/@biomejs/backend-jsonrpc/src/workspace.ts
packages/@biomejs/biome/configuration_schema.json
packages/@biomejs/js-api/README.md
website/src/pages/guides/getting-started.mdx
website/src/pages/internals/philosophy.mdx

This PR should update the last expired discord links.

fix: update remaining discord links

---

CONTRIBUTING.md

Use `Unreleased` instead of `[Unreleased]`.

docs(CONTRIBUTING): update changelog guidelines

---

crates/rome_js_analyze/tests/specs/correctness/organizeImports/groups.js
crates/rome_js_analyze/tests/specs/correctness/organizeImports/groups.js.snap
website/src/pages/analyzer/index.mdx

Was going through the docs and noticed this typo.

small typo fix

---

.github/workflows/bench_analyzer.yml
.github/workflows/bench_cli.yml
.github/workflows/bench_formatter.yml
.github/workflows/bench_parser.yml
.github/workflows/parser_conformance.yml
CHANGELOG.md
crates/rome_cli/src/configuration.rs
crates/rome_cli/src/diagnostics.rs
crates/rome_cli/src/service/unix.rs
crates/rome_cli/tests/snapshots/main_commands_check/fs_files_ignore_symlink.snap
crates/rome_cli/tests/snapshots/main_commands_format/custom_config_file_path.snap
crates/rome_cli/tests/snapshots/main_commands_lint/fs_files_ignore_symlink.snap
justfile
website/astro.config.ts
website/src/content/docs/internals/changelog.mdx

As per title
Closes https://github.com/biomejs/biome/issues/108
Updated existing tests

feat(cli): emit warning when `rome.json` file is found

---

website/src/content/docs/blog/biome-v1.mdx

I was going through the documentation and noticed a typo `jsxQuotStyle` -> `jsxQuoteStyle`

fix: docs typo

---

website/src/content/docs/blog/biome-v1.mdx

I encountered them while reading it and decided to might as well fix them.

fix(website): broken rule links on `biome-v1` blog page

---

CHANGELOG.md
crates/rome_js_analyze/src/semantic_analyzers/correctness/no_undeclared_variables.rs
website/src/content/docs/formatter/index.mdx
website/src/content/docs/guides/getting-started.mdx
website/src/content/docs/internals/changelog.mdx
website/src/content/docs/linter/rules/no-undeclared-variables.md

fix(docs): a bunch of broken links, not all of them

---

CHANGELOG.md
crates/rome_cli/src/commands/migrate.rs
crates/rome_cli/src/execute/migrate.rs
crates/rome_cli/src/execute/mod.rs
crates/rome_cli/tests/commands/migrate.rs
crates/rome_cli/tests/snapshots/main_commands_migrate/emit_diagnostic_for_rome_json.snap
crates/rome_cli/tests/snapshots/main_commands_migrate/should_create_biome_json_file.snap
website/src/content/docs/internals/changelog.mdx

Closes https://github.com/biomejs/biome/issues/119
Closes https://github.com/biomejs/biome/issues/54
Added new test cases

feat: migrate `rome.json` to `biome.json`

---

CONTRIBUTING.md

I fixed the broken links in CONTRIBUTING.md

docs: fix broken links in CONTRIBUTING.md

---

packages/@biomejs/biome/README.md

docs: Update README.md

---

packages/@biomejs/biome/bin/biome

#151 
I made a small mistake. I reversed the condition.

fix: support deno

---

.github/workflows/website_deploy_preview.yml
.github/workflows/website_deploy_prod.yml

Limit website deploys only for PRs that come from own branches
Merge and see if third party PRs don't trigger these workflows

ci: run action only from own branches

---

CHANGELOG.md
crates/rome_analyze/src/lib.rs
crates/rome_cli/tests/snapshots/main_commands_check/deprecated_suppression_comment.snap
crates/rome_cli/tests/snapshots/main_commands_lint/deprecated_suppression_comment.snap
crates/rome_js_analyze/tests/specs/correctness/noUnreachable/SuppressionComments.js.snap
website/src/content/docs/internals/changelog.mdx

This PR adds a code action to replace `// rome-ignore` with `// biome-ignore`
Updated test cases.

feat: create action for replacing outdated suppression comments

---

CHANGELOG.md
editors/vscode/package.json
packages/@biomejs/biome/package.json
website/src/content/docs/internals/changelog.mdx
website/src/pages/schemas/1.1.0/schema.json.js

release: 1.1.0

---

crates/rome_diagnostics/CONTRIBUTING.md

docs: fix typo in CONTRIBUTING.md

---

website/src/content/docs/formatter/index.mdx
website/src/content/docs/guides/manual-installation.mdx

fix: fix website links

---

CHANGELOG.md
website/src/content/docs/internals/changelog.mdx

Changes a few `rome` -> `biome` references.
Markdown looks correct i suppose

docs: update 1.1.0 changelog entries

---

.github/workflows/main.yml

This should fix CI issue in `main`
Merge it and see if it works

ci: install taplo binary

---

xtask/lintdoc/src/main.rs

Updated the linter rules link

---

.github/workflows/parser_conformance.yml
crates/biome_js_semantic/src/events.rs

Fix a regression - https://github.com/biomejs/biome/pull/228#issuecomment-1713395777
`cargo test`

fix(analyzer): add external module declaration

---

CHANGELOG.md
crates/biome_cli/src/execute/traverse.rs
crates/biome_cli/tests/commands/ci.rs
crates/biome_cli/tests/snapshots/main_commands_ci/does_error_with_only_warnings.snap
website/src/content/docs/internals/changelog.mdx

Closes https://github.com/biomejs/biome/issues/239

fix(cli): `--errors-on-warnings` should work with `ci` command

---

crates/biome_diagnostics_categories/src/categories.rs
website/src/content/docs/linter/rules/use-valid-aria-values.md

fix(useValidAriaValues): rule link

---

CHANGELOG.md
crates/biome_cli/tests/commands/format.rs
crates/biome_cli/tests/snapshots/main_commands_format/should_apply_different_indent_style.snap
crates/biome_service/src/configuration/javascript/formatter.rs
crates/biome_service/src/configuration/json.rs
crates/biome_service/src/file_handlers/javascript.rs
crates/biome_service/src/file_handlers/json.rs
editors/vscode/configuration_schema.json
editors/vscode/package.json
packages/@biomejs/backend-jsonrpc/src/workspace.ts
packages/@biomejs/biome/configuration_schema.json
packages/@biomejs/biome/package.json
website/src/content/docs/internals/changelog.mdx
website/src/pages/schemas/1.2.1/schema.json.js

This PR should fix the minor regressions we found after the release
I created a new test case and looked for `indent_size` in the schema, and none were found, which is good.

fix: schema and formatter language application

---

website/src/content/docs/reference/configuration.mdx

I am terrible at documentation 😓 
I forgot to add some lines for the new fields we added in the documentation. 
Proof read

docs: documentation for new configuration fields

---

crates/biome_cli/tests/snapshots/main_commands_check/should_organize_imports_diff_on_check.snap

Fix https://github.com/biomejs/biome/actions/runs/6213855173/job/16865255889
`cargo test`

fix(cli): fix ci tests

---

.github/workflows/bench_analyzer.yml
.github/workflows/bench_formatter.yml
.github/workflows/bench_parser.yml

I managed to change the permissions of the token, the workflows should be able to write the comment know
Merge it and test it

ci: remove checks in bench workflows

---

website/astro.config.ts
website/src/content/docs/guides/big-projects.mdx

Newly added this [big-projects page](https://biomejs.dev/guides/big-projects/) should be described Biome.

fix: rome to biome on big-projects page

---

website/src/content/docs/guides/manual-installation.mdx

This PR adds installation instructions for Biome's homebrew formula.
Related to https://github.com/biomejs/biome/issues/209

docs: add homebrew installation instructions

---

.github/workflows/release_lsp.yml

Fix Intellij plugin nightly release workflow

fix(workflows): Update plugin version must export version

---

.github/workflows/release_lsp.yml

Fix Intellij plugin workflow - update artifact name

fix(workflow): updated artifect name

---

.github/workflows/release_lsp.yml

Updated workflow to use correct envs

fix(intellij): updated release-lsp env variables

---

CONTRIBUTING.md

This PR adds myself to the list of maintainers.

docs(CONTRIBUTING): add `nhedger` to maintainers

---

CONTRIBUTING.md

This pr adds me to core contributors section.

chore: add unvalley to core contributors team

---

.github/ISSUE_TEMPLATE/01_bug.yml
CONTRIBUTING.md

Closes https://github.com/biomejs/biome/issues/165
https://codesandbox.io/p/sandbox/biome-starter-cbs-rky6zq
Open it and check it out

chore: add CBS reference to docs and bug template

---

CONTRIBUTING.md

chore: add nissy-dev to core contributor

---

crates/biome_js_analyze/tests/specs/correctness/noSelfAssign/invalid.js.snap

test(lint): update snapshots

---

crates/biome_js_analyze/src/semantic_analyzers/nursery/no_invalid_new_builtin.rs
website/src/content/docs/linter/rules/no-invalid-new-builtin.md

Separate code examples to avoid warnings when running `cargo test`.
Updated tests.

refactor(lint/noInvalidNewBuiltin): separate examples

---

CONTRIBUTING.md

chore: add denbezrukov to core contributor

---

CHANGELOG.md
crates/biome_cli/tests/snapshots/main_commands_check/lint_error.snap
crates/biome_cli/tests/snapshots/main_commands_check/maximum_diagnostics.snap
crates/biome_cli/tests/snapshots/main_commands_check/print_verbose.snap
crates/biome_cli/tests/snapshots/main_commands_ci/ci_lint_error.snap
crates/biome_cli/tests/snapshots/main_commands_ci/print_verbose.snap
crates/biome_cli/tests/snapshots/main_commands_lint/lint_error.snap
crates/biome_cli/tests/snapshots/main_commands_lint/maximum_diagnostics.snap
crates/biome_cli/tests/snapshots/main_commands_lint/print_verbose.snap
crates/biome_js_analyze/src/analyzers/style/use_while.rs
crates/biome_js_analyze/tests/specs/style/useWhile/invalid.js
crates/biome_js_analyze/tests/specs/style/useWhile/invalid.js.snap
crates/biome_js_analyze/tests/specs/style/useWhile/valid.js
crates/biome_js_analyze/tests/specs/style/useWhile/valid.js.snap
crates/biome_service/src/configuration/linter/rules.rs
editors/vscode/configuration_schema.json
packages/@biomejs/backend-jsonrpc/src/workspace.ts
packages/@biomejs/biome/configuration_schema.json
website/src/content/docs/internals/changelog.mdx
website/src/content/docs/linter/rules/index.mdx
website/src/content/docs/linter/rules/use-while.md

Make teh code fix of [useWhile](https://biomejs.dev/linter/rules/use-while) safe.
I take the opportunity to improve the rule docs, diagnostics, and code fix (better trivia handling).
Updated and added tests.

refactor(lint/useWhile): make code fix safe

---

CHANGELOG.md
crates/biome_cli/src/commands/mod.rs
crates/biome_cli/tests/snapshots/main_commands_check/check_help.snap
crates/biome_cli/tests/snapshots/main_commands_format/format_help.snap
crates/biome_cli/tests/snapshots/main_commands_lint/lint_help.snap
packages/@biomejs/biome/bin/biome
website/src/content/docs/internals/changelog.mdx
website/src/content/docs/reference/cli.mdx

This PR:
- improves the documentation of `--stdin-file-path`
- adds support for `BIOME_BINARY` environment variable
- deprecates `ROME_BINARY`
Updated snapshot tests

feat(cli): use `BIOME_BINARY`, improve documentation

---

website/src/content/docs/analyzer/index.mdx

Adds more documentation to how import sorting works and how to solve common issues.
N/A

docs: add explanation how to break down import groups

---

crates/biome_cli/src/commands/mod.rs
crates/biome_cli/tests/snapshots/main_commands_check/check_help.snap
crates/biome_cli/tests/snapshots/main_commands_ci/ci_help.snap
website/src/content/docs/formatter/index.mdx
website/src/content/docs/linter/index.mdx

Improves the documentation of `check` and `ci` commands
Rendered website, proof read

docs: improve documentation for `check` and `ci` commands

---

CONTRIBUTING.md

This PR adds myself to the list of maintainers 👋

docs(CONTRIBUTING): add victor-teles to maintainers

---

crates/biome_js_analyze/src/analyzers/correctness/use_valid_for_direction.rs

Remove rule's state of `useValidForDirection`.
No change.

refactor(lint/useValidForDirection): remove rule's state

---

CHANGELOG.md
crates/biome_cli/src/vcs.rs
crates/biome_cli/tests/commands/check.rs
crates/biome_cli/tests/commands/ci.rs
crates/biome_cli/tests/commands/format.rs
crates/biome_cli/tests/commands/lint.rs
crates/biome_cli/tests/snapshots/main_commands_check/ignore_vcs_ignored_file.snap
crates/biome_cli/tests/snapshots/main_commands_check/ignore_vcs_os_independent_parse.snap
crates/biome_cli/tests/snapshots/main_commands_ci/ignore_vcs_ignored_file.snap
crates/biome_cli/tests/snapshots/main_commands_format/ignore_vcs_ignored_file.snap
crates/biome_cli/tests/snapshots/main_commands_lint/ignore_vcs_ignored_file.snap
crates/biome_cli/tests/snapshots/main_commands_lint/ignore_vcs_os_independent_parse.snap
website/src/content/docs/internals/changelog.mdx

Per discussion https://github.com/biomejs/biome/discussions/391
We don't need `.git` folder for retrieving the `.gitignore` file. 
Current tests should pass

feat(cli): lift the check of `.git` folder

---

.github/FUNDING.yml

Add `FUNDING.yml` to introduce the `sponsor` button.

chore(FUNDING): add sponsor button

---

.github/workflows/release_crates.yml

Fixed the problem that release jobs are executed every time a push is made.

chore: change the running condition of crate release job

---

website/src/content/docs/reference/configuration.mdx

This pr fixes the schema version on the website configuration page.

docs: fix biome schema version on configuration page

---

website/astro.config.ts

This PR adds a link to the official mastodon account of the project
Manually verified that the `rel="me"` metadata is created, so we will get automatically verified.

feat(website): add mastodon official account

---

crates/biome_analyze/CONTRIBUTING.md

This PR lists all the rules someone has to follow when writing the documentation of a lint rule.
Proof read

docs: better guidelines for documentation rules

---

crates/biome_service/src/workspace.rs
crates/biome_service/src/workspace/server.rs

This PR adds an internal `DashMap` to save the `FileFeaturesResult` associated with each path. This change should save some operations when recomputing the same information for the same file.
Current CI should pass

feat(core): cache file features, to avoid re-computation

---

website/src/styles/_footer.scss
website/src/styles/playground/_results.scss
website/src/styles/playground/_tabs.scss

https://github.com/biomejs/biome/assets/85363195/90052af5-f960-4747-ae4a-6da9ae06417d
https://github.com/biomejs/biome/assets/85363195/e996521d-78fb-4b70-926a-a6e5a42535d5

fix(playground): fix playground styles

---

crates/biome_js_analyze/src/semantic_analyzers/style/no_restricted_globals.rs
crates/biome_js_semantic/src/events.rs
crates/biome_js_semantic/src/tests/references.rs

This extracts the two first commits of #482.
They are minor changes that improve readability and code safety.
CI.

refactor(js_semantic): minor changes

---

Cargo.lock
xtask/bench/Cargo.toml
xtask/bench/src/language.rs
xtask/bench/src/lib.rs
xtask/bench/src/libs-css.txt

feat(css_parser): Add css bench parser

---

editors/vscode/package.json

This PR adds [sponsorship to vscode plugin](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#extension-sponsor).

chore(vscode): add extension sponsorship

---

xtask/bench/src/lib.rs
xtask/bench/src/libs-css.txt

I couldn't write skip logic for unimplemented syntax =(
I believe it'll be easier when we have all selectors.

fix(css_parser): remove bench

---

website/src/pages/schemas/1.2.2/schema.json.js
xtask/codegen/Cargo.toml
xtask/codegen/src/generate_website.rs

The schema 1.2.2 isn't correct, it contains fields that aren't published yet.
I fixed the script by copying the schema inside the folder of the `schema.json.js` file.
It was tested locally. Once we merge, it should be deployed.

fix(website): fix 1.2.2 schema

---

website/src/components/PackageManagerBiomeCommand.astro

There were some inconsistencies in the "exec" part of the commands. Now, it should be fixed.
N/A

docs(website): fix dlx command

---

website/src/pages/schemas/1.2.2/schema.json.js
xtask/codegen/src/generate_website.rs

This time should be fixed for good
Closes https://github.com/biomejs/biome/issues/512
Tried locally

docs(website): fix schema (again)

---

crates/biome_diagnostics_categories/src/categories.rs
crates/biome_js_analyze/src/analyzers/nursery.rs
crates/biome_js_analyze/src/analyzers/nursery/no_useless_lone_block_statements.rs
crates/biome_js_analyze/tests/specs/nursery/noUselessLoneBlockStatements/invalid.cjs
crates/biome_js_analyze/tests/specs/nursery/noUselessLoneBlockStatements/invalid.cjs.snap
crates/biome_js_analyze/tests/specs/nursery/noUselessLoneBlockStatements/invalidModule.js
crates/biome_js_analyze/tests/specs/nursery/noUselessLoneBlockStatements/invalidModule.js.snap
crates/biome_js_analyze/tests/specs/nursery/noUselessLoneBlockStatements/valid.cjs
crates/biome_js_analyze/tests/specs/nursery/noUselessLoneBlockStatements/valid.cjs.snap
crates/biome_js_analyze/tests/specs/nursery/noUselessLoneBlockStatements/validModule.js
crates/biome_js_analyze/tests/specs/nursery/noUselessLoneBlockStatements/validModule.js.snap
crates/biome_service/src/configuration/linter/rules.rs
crates/biome_service/src/configuration/parse/json/rules.rs
editors/vscode/configuration_schema.json
packages/@biomejs/backend-jsonrpc/src/workspace.ts
packages/@biomejs/biome/configuration_schema.json
website/src/components/generated/NumberOfRules.astro
website/src/content/docs/linter/rules/index.mdx
website/src/content/docs/linter/rules/no-useless-lone-block-statements.md

Fix #42
Adds a new rule `noUselessBlockStatements`.

feat(lint/noUselessBlockStatements): add rule

---

CONTRIBUTING.md

adds myself to the list of maintainers 🎉

docs(CONTRIBUTING): add `SuperchupuDev` to maintainers

---

CHANGELOG.md
website/src/content/docs/internals/changelog.mdx

chore(CHANGELOG): log missing contributions

---

CHANGELOG.md
crates/biome_cli/src/execute/std_in.rs
crates/biome_cli/tests/commands/check.rs
crates/biome_cli/tests/snapshots/main_commands_check/check_stdin_returns_text_if_content_is_not_changed.snap
website/src/content/docs/internals/changelog.mdx

Resolves a bug discussed here https://github.com/biomejs/biome/discussions/522

fix(cli): return the original content to `stdout` if it didn't change

---

website/src/content/docs/guides/big-projects.mdx

`app.json` should be `biome.json` according to the context
> We start by creating a new configuration file at app/biome.json, and put there the...
The config file name in the documentation is `app/biome.json`

fix(docs): config file name

---

CHANGELOG.md
website/src/content/docs/internals/changelog.mdx

Uses the correct dates for releases 1.3.0 and 1.3.1 👀

chore: fix changelog release dates

---

crates/biome_js_analyze/src/analyzers/correctness/use_yield.rs
website/src/content/docs/linter/rules/use-yield.md

This PR fixes `useYield` rule ESLint source reference.

docs(website): fix `useYield` source reference

---

crates/biome_deserialize/src/json.rs
crates/biome_js_analyze/src/semantic_analyzers/correctness/use_exhaustive_dependencies.rs
crates/biome_js_analyze/src/semantic_analyzers/style/use_naming_convention.rs
crates/biome_service/src/configuration/parse/json/configuration.rs
crates/biome_service/src/configuration/parse/json/formatter.rs
crates/biome_service/src/configuration/parse/json/javascript/formatter.rs
crates/biome_service/src/configuration/parse/json/javascript/mod.rs
crates/biome_service/src/configuration/parse/json/json_impl/mod.rs
crates/biome_service/src/configuration/parse/json/linter.rs
crates/biome_service/src/configuration/parse/json/overrides.rs
crates/biome_service/src/configuration/parse/json/rules.rs
crates/biome_service/src/configuration/parse/json/vcs.rs
xtask/codegen/src/generate_configuration.rs

The PR improves the API by using `self` as the visitor in `map_to_*` functions.

refactor(json_deserialize): improve `map_to_*` API

---

CHANGELOG.md
crates/biome_js_parser/src/lexer/mod.rs
crates/biome_js_parser/src/syntax/expr.rs
crates/biome_js_parser/test_data/inline/ok/literals.js
crates/biome_js_parser/test_data/inline/ok/literals.rast
website/src/content/docs/internals/changelog.mdx

Fix #613
I add parser test for v flag

feat(biome_js_parser): support RegExp v flag

---

CHANGELOG.md
crates/biome_cli/src/logging.rs
website/src/content/docs/internals/changelog.mdx

Closes https://github.com/biomejs/biome/issues/562
I tested locally, now the panic isn't emitted anymore

fix(cli): start logger only when needed

---

CHANGELOG.md
crates/biome_cli/tests/cases/overrides_formatter.rs
crates/biome_cli/tests/cases/overrides_linter.rs
crates/biome_cli/tests/snap_test.rs
crates/biome_cli/tests/snapshots/main_cases_overrides_formatter/does_include_file_with_different_formatting_and_all_of_them.snap
crates/biome_cli/tests/snapshots/main_cases_overrides_linter/does_include_file_with_different_linting_and_applies_all_of_them.snap
crates/biome_js_formatter/src/context.rs
crates/biome_json_formatter/src/context.rs
crates/biome_service/src/configuration/javascript/formatter.rs
crates/biome_service/src/configuration/linter/rules.rs
crates/biome_service/src/configuration/mod.rs
crates/biome_service/src/file_handlers/javascript.rs
crates/biome_service/src/file_handlers/json.rs
crates/biome_service/src/settings.rs
crates/biome_service/src/workspace/server.rs
website/src/content/docs/internals/changelog.mdx
xtask/codegen/src/generate_configuration.rs

This PR fixes the behaviour of the `overrides`. The previous behaviour wasn't correct, coming from the other tools.
I plan to update the documentation before the release.
Reviewed the test cases and altered some of the existing ones.

fix(core): overrides behaviour

---

CHANGELOG.md
editors/intellij/gradle.properties
editors/vscode/package.json
packages/@biomejs/biome/package.json
website/src/content/docs/internals/changelog.mdx
website/src/pages/schemas/1.3.2/schema.json.js

release: 1.3.2

---

CHANGELOG.md
packages/@biomejs/biome/package.json
website/src/content/docs/internals/changelog.mdx
website/src/pages/schemas/1.3.3/schema.json.js

release: 1.3.3

---

CHANGELOG.md
CONTRIBUTING.md
crates/biome_cli/src/execute/mod.rs
crates/biome_cli/src/execute/traverse.rs
crates/biome_cli/tests/commands/format.rs
crates/biome_cli/tests/snapshots/main_commands_format/format_json_when_allow_trailing_commas.snap
crates/biome_cli/tests/snapshots/main_commands_format/format_jsonc_files.snap
crates/biome_cli/tests/snapshots/main_commands_format/formatter_lint_warning.snap
crates/biome_cli/tests/snapshots/main_commands_format/formatter_print.snap
crates/biome_cli/tests/snapshots/main_commands_format/ignore_comments_error_when_allow_comments.snap
crates/biome_cli/tests/snapshots/main_commands_format/ignores_unknown_file.snap
crates/biome_cli/tests/snapshots/main_commands_format/max_diagnostics.snap
crates/biome_cli/tests/snapshots/main_commands_format/max_diagnostics_default.snap
crates/biome_cli/tests/snapshots/main_commands_format/print_verbose.snap
crates/biome_cli/tests/snapshots/main_commands_format/treat_known_json_files_as_jsonc_files.snap
justfile
website/src/content/docs/internals/changelog.mdx

This PR fixes the `format` command. When we `biome format ./test.ts` and there are pending diffs, now the CLI exits with an error code.
Updated the existing tests

fix(cli): error code for `format` command

---

website/astro.config.ts
website/package.json
website/src/content/docs/guides/integrate-in-editor.mdx
website/src/content/docs/guides/integration-with-editors.mdx

This PR adds a new guide to the website that explains how to integrate Biome inside an editor.
Proof read

docs(website): new guide for editors

---

CHANGELOG.md
crates/biome_js_analyze/src/semantic_analyzers/correctness/no_unused_variables.rs
crates/biome_js_analyze/tests/specs/correctness/noUnusedVariables/invalidTypeParam.ts
crates/biome_js_analyze/tests/specs/correctness/noUnusedVariables/invalidTypeParam.ts.snap
crates/biome_js_analyze/tests/specs/correctness/noUnusedVariables/validTypeParam.ts
crates/biome_js_analyze/tests/specs/correctness/noUnusedVariables/validTypeParam.ts.snap
website/src/content/docs/internals/changelog.mdx

Fix #639
Regression tests added

fix: allow unused mapped key

---

CHANGELOG.md
crates/biome_js_analyze/src/semantic_analyzers/correctness/no_unused_variables.rs
crates/biome_js_analyze/tests/specs/correctness/noUnusedVariables/invalidTypeParam.ts
crates/biome_js_analyze/tests/specs/correctness/noUnusedVariables/invalidTypeParam.ts.snap
crates/biome_js_analyze/tests/specs/correctness/noUnusedVariables/validTypeParam.ts
crates/biome_js_analyze/tests/specs/correctness/noUnusedVariables/validTypeParam.ts.snap
website/src/content/docs/internals/changelog.mdx

Fix #565
Regression tests included.

fix: handle infer in unions

---

website/src/content/docs/guides/getting-started.mdx
website/src/content/docs/guides/integrate-in-editor.mdx

After some feedback and suggestions, I reworked the editors page and added "First-party" plugins and "Third-party" plugins. 
What do you think? 
Proof read
https://biome-website-h1i3bnd6p-ematipico.vercel.app/guides/integrate-in-editor/

docs(website): reworked the editor plugins section

---

.github/workflows/pull_request.yml

This PR is an attempt at fixing an issue where there is no space left on the device when using ubuntu.

ci(pull_request): free disk space on ubuntu-latest

---

CHANGELOG.md
CONTRIBUTING.md
crates/biome_analyze/CONTRIBUTING.md
crates/biome_cli/src/commands/mod.rs
crates/biome_cli/src/lib.rs
crates/biome_cli/tests/snapshots/main_commands_lsp_proxy/lsp_proxy_help.snap
justfile
website/astro.config.ts
website/src/content/docs/internals/changelog.mdx

What the PR says. Closes https://github.com/biomejs/biome/issues/675 
I will make a follow-up PR  to add the feature requested 
Snapshot updated

fix(cli): remove CLI options from the `lsp-proxy` command

---

website/src/content/docs/guides/integrate-in-editor.mdx

chore(website): add coc-biome

---

CONTRIBUTING.md

This pr proposes add resources section to CONTRIBUTING.md .
I think the resources will help new contributors to understand projects and codebases.

docs(CONTRIBUTING): add resources section

---

CHANGELOG.md
website/src/content/docs/internals/changelog.mdx

I just found a typo and fixed it.

chore: fix typo in CHANGELOG.md

---

crates/biome_js_formatter/report.md

Compatibility report in the repo.
This makes update of the report easier for the time of the challenge.
Once done, we could remove the report.
The report was generated using #731.
No change. CI should pass.

chore: add prettier compat report

---

crates/biome_js_formatter/report.md
crates/biome_js_formatter/report_incompatible.md

Update prettier compatibility reports.

chore(formatter): update compatibility reports

---

.github/workflows/pull_request.yml
.github/workflows/pull_request_intellij.yml
.github/workflows/release_cli.yml
.github/workflows/release_js_api.yml
.github/workflows/release_lsp.yml
.github/workflows/website_deploy_preview.yml
.github/workflows/website_deploy_prod.yml

`actions/checkout@v3` and `actions/setup-node@v3` use Node v16 which is EOL since [11 Sep 2023](https://endoflife.date/nodejs), so bumped these to v4 that use Node v20.
- Check if all CI tests pass

ci: update GitHub action

---

crates/biome_js_formatter/report.md
crates/biome_js_formatter/report_incompatible.md

chore: update challenge reports

---

crates/biome_js_formatter/report.md
crates/biome_js_formatter/report_incompatible.md

chore(challenge): update reports

---

crates/biome_formatter_test/src/diff_report.rs
crates/biome_js_formatter/report.md
crates/biome_js_formatter/report_incompatible.md

Exclude more experimental syntaxes and embedded language from the report.

chore(challenge): refine reports

---

crates/biome_formatter/src/comments.rs
crates/biome_formatter/src/source_map.rs
crates/biome_formatter_test/src/test_prettier_snapshot.rs
crates/biome_js_formatter/src/utils/jsx.rs

Update some ignore comment to use `biome-ignore` instead of `rome-ignore`
Ci should pass.

refactor: rename some rome-ignore to biome-ignore

---

crates/biome_js_formatter/report.md

chore: update `report.md`

---

crates/biome_js_analyze/src/analyzers/nursery/no_useless_lone_block_statements.rs
crates/biome_js_analyze/tests/specs/nursery/noUselessLoneBlockStatements/valid.cjs
crates/biome_js_analyze/tests/specs/nursery/noUselessLoneBlockStatements/valid.cjs.snap

closes #783
All existing tests should pass and I've added two test cases for try/catch and try/catch/finally.

fix(linter): avoid causing noUselessLoneBlockStatements for try/catch

---

packages/@biomejs/biome/README.md

This pr generates sections to sponsor on README page.
Thank you for becoming gold sponsor [@shiguredo](https://github.com/shiguredo)! 
And, thank you becoming bronze sponsor [@KANAME](https://github.com/kanamekey)!
We are truly fortunate to have you as our sponsors and look forward to achieving great things together🔥

chore: add sponsors to readme

---

website/src/content/docs/reference/configuration.mdx

This PR replaces `exlude` instances with `ignore`.

docs(website): replace `exclude` with `ignore`

---

crates/biome_formatter_test/src/diff_report.rs
crates/biome_js_formatter/report-challenge.md
crates/biome_js_formatter/report-es2015.md
crates/biome_js_formatter/report-es2024+.md
crates/biome_js_formatter/report.md
crates/biome_js_formatter/report_incompatible.md

Add the reports for submission

chore(challenge): add submission reports

---

CONTRIBUTING.md

chore: Add TaKO8Ki to Maintainers team

---

crates/biome_js_formatter/report.md
crates/biome_js_formatter/report_incompatible.md

challenge: update reports

---

packages/@biomejs/biome/scripts/update-nightly-version.mjs

Fixes #860.
Bump `version` of nightly in the script.

fix(tooling): update the script to bump the nightly version

---

CONTRIBUTING.md

Thanks for having me on the team :)
I sure hope markdown works 👀

chore: Add myself as a maintainer in CONTRIBUTING.md

---

.github/CODEOWNERS

I've added japanese-translation-reviewers to CODEOWNERS. 
> It might be a good idea to create a team, such as 'japanese-translation-reviewers', so that reviewers are automatically assigned when files under website/src/content/docs/ja/ are edited or new files are added.
ref: https://github.com/biomejs/biome/issues/880#issuecomment-1827219855

chore(doc): Add japanese-translation-reviewers to CODEOWNERS

---

.github/workflows/release_cli.yml

This PR (hopefully) fixes the homebrew job

ci(release_cli): fix homebrew job

---

CHANGELOG.md
crates/biome_js_analyze/src/analyzers/style/no_useless_else.rs
crates/biome_js_analyze/src/utils/batch.rs
crates/biome_js_analyze/tests/specs/style/noUselessElse/valid.js
crates/biome_js_analyze/tests/specs/style/noUselessElse/valid.js.snap
crates/biome_js_semantic/src/semantic_model/tests.rs
website/src/content/docs/internals/changelog.mdx
website/src/content/docs/linter/rules/no-useless-else.md

Fix #924
Fix #920
I added a test and updated the documentation.

refactor(lint/noUselessElse): ignore else clauses of if that doesn't break

---

website/src/content/docs/ja/recipes/continuous-integration.mdx

Partial work of https://github.com/biomejs/biome/issues/880.  `recipes/continuous-integration.mdx `
- Check if all links works as expecetd
- Check if all translations make sense

doc(ja): translate continuous-integration into Japanese

---

CHANGELOG.md
crates/biome_js_analyze/tests/specs/suspicious/noRedeclare/valid-mapped-types.ts
crates/biome_js_analyze/tests/specs/suspicious/noRedeclare/valid-mapped-types.ts.snap
crates/biome_js_semantic/src/events.rs
website/src/content/docs/internals/changelog.mdx

fix(js_semantic): add semantic scope to mapped types

---

CHANGELOG.md

Adding changelog entries for the 1.4.1 release.
Markdown :)

chore: add formatting changelog entries for 1.4.1

---

crates/biome_cli/src/commands/mod.rs
crates/biome_cli/tests/snapshots/main_commands_check/check_help.snap
crates/biome_cli/tests/snapshots/main_commands_lint/lint_help.snap
website/src/content/docs/analyzer/index.mdx
website/src/content/docs/ja/analyzer/index.mdx

- mention that -apply is now "safe to apply".
- Edit `--apply-unsafe` to `--apply` at https://biomejs.dev/analyzer#import-sorting-via-cli
relevance: https://github.com/biomejs/biome/issues/961
- help reflects the modifications made.
- Documentation has been modified.

docs(website): update import sorting doc

---

crates/biome_js_analyze/src/semantic_analyzers/complexity/no_banned_types.rs
website/src/content/docs/linter/rules/no-banned-types.md

docs: fix typo and improve readability in complexity/noBannedTypes rule

---

crates/biome_js_formatter/report.md
crates/biome_js_formatter/report_incompatible.md

Update Prettier compatibility reports.

chore(formatter): update Prettier compat reports

---

website/src/content/docs/guides/integrate-in-editor.mdx

Add link to the Sublime Text Biome integration called [LSP-biome](https://github.com/sublimelsp/LSP-biome).

docs(website): add sublime text integration

---

website/src/content/docs/formatter/index.mdx

Improve Prettier divergence section. Invalid syntax formtatting are now grouped on a single section.

refactor(website): improve divergence notes

---

website/src/content/docs/ja/index.mdx

Fixed routing bug.
https://github.com/biomejs/biome/assets/34010665/c9a42fb4-00a5-48e8-9824-ab28c5ae1587
- Change language to Japanese
- Click `はじめる`  button to route to the getting-started page
- Check if the page is written in Japanese and the url is correct `/ja/guides/getting-started`

fix: routing bug fix

---

crates/biome_js_analyze/src/semantic_analyzers/correctness/use_exhaustive_dependencies.rs
crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/valid.ts
crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/valid.ts.snap

Fixes https://github.com/biomejs/biome/issues/811

fix(lint/exhaustiveDeps): ignore TS typeof (#811)

---

website/astro.config.ts

Changed Twitter icon to X's.
Ran the website locally and confirmed the following:
- The icon updated properly
- Clicking on it navigates to https://twitter.com/biomejs

Update Twitter icon

---

website/src/content/blog/biome-wins-prettier-challenge.md

While reading [this blog post](https://biomejs.dev/blog/biome-wins-prettier-challenge/), I noticed that the bracketSameLine comments were incorrect and the bracketSpacing true & false examples were the same, so I fixed them.
Also note that the docs links don't work, because these config options seem to not be documented at all.
I tested formatting these code samples with the Biome CLI.

Fix code examples in prettier challenge blog post

---

README.zh-CN.md
packages/@biomejs/biome/README.md
packages/@biomejs/biome/README.zh-CN.md

Translate readme file to Chinese.

Translate readme cn

---

website/src/content/blog/annoucing-biome.mdx
website/src/content/blog/biome-v1.mdx
website/src/content/blog/biome-wins-prettier-challenge.md

Add Chinese translation links of blogs.

add blog chinese translation links

---

packages/@biomejs/biome/README.md

fix broken readme link

---

website/astro.config.ts
website/src/content/docs/formatter/differences-with-prettier.md
website/src/content/docs/formatter/index.mdx

This PR breaks down the formatter section in three pages:
- introduction
- divergences
- option philosophy 
I added a new chapter in the formatting docs, where we list the default options of the javascript files.
Check the rendered website

docs(website): break down formatter in three pages

---

website/astro.config.ts

Partial work from #1065 that translates the documentation sidebar.
- Check if the translation matches the correct translation of the terms
- Check if there's missing any translation of the terms

docs(pt-br): translated sidebar

---

packages/@biomejs/biome/README.md

chore: add nanabit to the list of bronze sponsors

---

crates/biome_js_analyze/tests/specs/nursery/useShorthandFunctionType/invalid.ts
crates/biome_js_analyze/tests/specs/nursery/useShorthandFunctionType/invalid.ts.snap
crates/biome_js_analyze/tests/specs/nursery/useShorthandFunctionType/valid.ts
crates/biome_js_analyze/tests/specs/nursery/useShorthandFunctionType/valid.ts.snap

Close #1045 
I ran `just test-crate biome_js_analyze` and everything as green as my garden

test(useShorthandFunctionType): add more test cases

---

packages/@biomejs/biome/README.md
packages/@biomejs/biome/README.zh-CN.md

Follow-up of:
- https://github.com/biomejs/biome/pull/1174#issuecomment-1855336082
_always, reading docs with smile_

docs(README.md): update translations in README.md

---

website/src/components/formatter/input.md
website/src/components/formatter/output.md
website/src/content/docs/index.mdx
website/src/content/docs/pt-br/index.mdx
website/src/content/docs/zh-cn/index.mdx
website/src/playground/components/Progress.tsx
website/src/styles/_overrides.scss
website/src/styles/_performance.scss
website/src/styles/_progress.scss

feat: Hero `Performance` component

---

CHANGELOG.md
crates/biome_cli/src/execute/migrate.rs
crates/biome_migrate/src/analyzers.rs
crates/biome_migrate/src/analyzers/schema.rs
crates/biome_migrate/src/lib.rs
crates/biome_migrate/src/version_services.rs
crates/biome_migrate/tests/spec_tests.rs
crates/biome_migrate/tests/specs/migrations/schema/invalid.json
crates/biome_migrate/tests/specs/migrations/schema/invalid.json.snap
crates/biome_migrate/tests/specs/migrations/schema/valid.json
crates/biome_migrate/tests/specs/migrations/schema/valid.json.snap
website/src/content/docs/internals/changelog.mdx

The command `biome migrate` now updates the `$schema` field :)
Tests added

feat(migrate): add migration for the schema field

---

GOVERNANCE.md
website/src/content/docs/internals/philosophy.mdx

Please @biomejs/core-contributors approve the PR. What do you think about the newly added paragraph in the philosophy?

chore: governance and philosophy

---

website/src/components/Netlify.astro
website/src/components/starlight/Sidebar.astro
website/src/content/docs/index.mdx

Unfortunately, the Netlify badge isn't in all pages: blog, blog pages and playground don't have it.
Because of that, we moved it to the home.
This should give us access to the open source program of Netlify.

website: move netlify badge to home

---

CONTRIBUTING.md
justfile

Few updates in the resources and the just commands

chore: update justfile and resources

---

crates/biome_js_formatter/report.md
crates/biome_js_formatter/report_incompatible.md
packages/@biomejs/biome/README.ja.md
packages/@biomejs/biome/README.md
packages/@biomejs/biome/README.pt-br.md
packages/@biomejs/biome/README.zh-CN.md

Biome scores 97% compatibility with Prettier!

chore: update Prettier compatibility

---

packages/@biomejs/biome/README.ja.md
packages/@biomejs/biome/README.md
packages/@biomejs/biome/README.pt-br.md
packages/@biomejs/biome/README.zh-CN.md

This PR moves the links of our translations of top (again). Better this way.

chore: move translation links on top

---

packages/@biomejs/biome/README.md

Fix minor capitalisation in "Typescript".

[Minor Doc Fix] Capitalisation in Readme

---

packages/@biomejs/biome/README.zh-CN.md

Optimize some expressions, typesetting format in Chinese and English.
I've checked the format.

readme(zh-CN): Optimize some expressions, typesetting format in Chinese and English.

---

CONTRIBUTING.md

chore: add myself as a core contributor

---

website/src/content/docs/formatter/differences-with-prettier.md

There was a formatting issue, see screenshot:
and https://biomejs.dev/formatter/differences-with-prettier 
none, just a simple markdown fix

docs: fix formatting issue

---

crates/biome_cli/src/execute/process_file.rs
crates/biome_cli/src/execute/traverse.rs
crates/biome_cli/tests/cases/diagnostics.rs
crates/biome_cli/tests/snapshots/main_cases_diagnostics/logs_the_appropriate_messages_according_to_set_diagnostics_level.snap

This is a follow-up of https://github.com/biomejs/biome/pull/1248
I wanted to push directly to the PR, but I wasn't allowed.
If a user specifies `--diagnostic-error=error`, they are not interested in diagnostics that have a severity lower than that, which means that we shouldn't bother processing those diagnostics at all.
In the previous PR there was a regression, which I fixed

fix(cli): diagnostic level

---

website/src/content/docs/linter/rules/no-for-each.md

Proposed docs changes in #1205.
Do not affect CI.

docs: add caveat to `lint/complexity/noForEach`

---

CHANGELOG.md
website/src/content/docs/internals/changelog.mdx

Improve last changelog entries and add some missing changelog entries.

docs(CHANGELOG): improve and update

---

crates/biome_js_analyze/src/analyzers/complexity/no_for_each.rs
website/src/content/docs/linter/rules/no-for-each.md

Follow-up of #1305
The docs were wrongly placed.

docs(lint/noForEach): add caveat in the source file

---

packages/@biomejs/biome/README.ja.md
packages/@biomejs/biome/README.pt-br.md
packages/@biomejs/biome/README.zh-CN.md

Translated READMEs are still use previous logo, so this PR updates them.

chore: use logo v2 in translated README

---

website/src/content/docs/ja/recipes/continuous-integration.mdx
website/src/content/docs/pt-br/recipes/continuous-integration.mdx
website/src/content/docs/recipes/continuous-integration.mdx
website/src/content/docs/zh-cn/recipes/continuous-integration.mdx

Current continuous-integration document uses biome v1.2.2, that's old, so this PR updates it `latest`. This change reduces our task to update it.

docs(website): use biome latest in ci example doc

---

crates/biome_js_analyze/src/analyzers/suspicious/use_getter_return.rs
crates/biome_js_analyze/tests/specs/suspicious/useGetterReturn/invalid.js.snap
website/src/content/docs/linter/rules/use-getter-return.md

Fix diagnostic of `useGetterReturn`.
Updated test snapshots.

fix(lint/useGetterReturn): fix diagnostic

---

crates/biome_cli/src/execute/mod.rs
crates/biome_cli/src/execute/process_file.rs
crates/biome_cli/src/execute/std_in.rs
crates/biome_cli/src/execute/traverse.rs
crates/biome_cli/tests/cases/mod.rs
crates/biome_cli/tests/cases/protected_files.rs
crates/biome_cli/tests/snapshots/main_cases_protected_files/not_process_file_from_cli.snap
crates/biome_cli/tests/snapshots/main_cases_protected_files/not_process_file_from_cli_verbose.snap
crates/biome_cli/tests/snapshots/main_cases_protected_files/not_process_file_from_stdin_format.snap
crates/biome_cli/tests/snapshots/main_cases_protected_files/not_process_file_from_stdin_lint.snap
crates/biome_cli/tests/snapshots/main_cases_protected_files/not_process_file_from_stdin_verbose_format.snap
crates/biome_cli/tests/snapshots/main_cases_protected_files/not_process_file_from_stdin_verbose_lint.snap
crates/biome_fs/src/fs/os.rs
crates/biome_service/src/diagnostics.rs
crates/biome_service/src/snapshots/source_file_not_supported.snap
crates/biome_service/src/workspace.rs
crates/biome_service/src/workspace/server.rs
package.json
packages/@biomejs/backend-jsonrpc/src/workspace.ts
website/src/content/docs/guides/how-biome-works.mdx

Closes https://github.com/biomejs/biome/issues/1355
This PR adds the concept of protected files, files that Biome won't process because they are handled by other tools.
I took the chance to add some verbose diagnostic that should provide more information on how to hide of fix the diagnostics.
Added new snapshot tests

feat(project): show message when a file is protected

---

crates/biome_cli/tests/commands/check.rs
crates/biome_cli/tests/commands/format.rs
crates/biome_cli/tests/commands/lint.rs
crates/biome_css_parser/src/prelude.rs
crates/biome_js_formatter/src/parentheses.rs
crates/biome_js_parser/src/tests.rs
crates/biome_js_semantic/src/semantic_model.rs
crates/biome_js_semantic/src/semantic_model/model.rs
crates/biome_js_syntax/src/lib.rs
crates/biome_js_syntax/src/stmt_ext.rs
rust-toolchain.toml
xtask/coverage/src/main.rs
xtask/coverage/src/runner.rs

Upgrade to Rust 1.75.0
CI should pass

chore: upgrade to rust 1.75.0

---

.github/workflows/bench_analyzer.yml
xtask/bench/Cargo.toml
xtask/bench/benches/analyzer-libs-js.txt
xtask/bench/benches/analyzer-libs-ts.txt
xtask/bench/benches/analyzer.rs
xtask/bench/src/lib.rs

This PR refactors the benchmarks of the Analyzer. It makes it simpler and it uses only `criterion`. The plan is to merge this PR and use https://codspeed.io
To merge this PR and then open a new one to check if it works

ci: benchmark analyzer with codspeed

---

.github/workflows/bench_analyzer.yml
.github/workflows/bench_js_parser.yml
xtask/bench/Cargo.toml
xtask/bench/benches/js_parser.rs
xtask/bench/benches/libs-css.txt
xtask/bench/benches/libs-js.txt
xtask/bench/benches/libs-json.txt
xtask/bench/benches/libs-ts.txt

This PR adds JS parser benchmark
I will use this PR to test the analyzer and fix it in case there are bugs

ci: benchmark js parser with codspeed

---

.github/workflows/bench_analyzer.yml
.github/workflows/bench_js_formatter.yml
.github/workflows/bench_js_parser.yml
xtask/bench/Cargo.toml
xtask/bench/benches/js_formatter.rs
xtask/bench/src/lib.rs

ci: bench js formatter with codspeed

---

crates/biome_analyze/CONTRIBUTING.md

I was working on analyzer issue and found that the link of the `snapshot test` in the `CONTRIBUTION.md` is wrong.
I believe that updating the link to correct document is useful for a contributors.

docs(analyzer): update the link of snaphot testing

---

crates/biome_js_analyze/src/analyzers/nursery/use_shorthand_function_type.rs
crates/biome_js_analyze/tests/specs/nursery/useShorthandFunctionType/valid.ts
crates/biome_js_analyze/tests/specs/nursery/useShorthandFunctionType/valid.ts.snap

close #354
Does not report and fix if node has inner comments https://github.com/biomejs/biome/pull/670#pullrequestreview-1727244683
Add snaps for valid cases

chore(lint/useShorthandFunctionType): ignore if node has inner comments

---

xtask/bench/benches/analyzer.rs
xtask/bench/benches/css_formatter.rs
xtask/bench/benches/css_parser.rs
xtask/bench/benches/js_formatter.rs
xtask/bench/benches/js_parser.rs
xtask/bench/benches/json_formatter.rs
xtask/bench/benches/json_parser.rs
xtask/bench/src/lib.rs

This PR makes the code for bench marking more generic and shared among benches.
Hopefully, this should make codspeed happy, because it seems it's not recording properly the data.
This is doesn't work as I expect, in the following weeks I will open an issue in their repository to understand why.
Merge it and trigger a workflow

refactor: benchmark code generic

---

crates/biome_aria/src/roles.rs
crates/biome_js_analyze/tests/specs/a11y/noInteractiveElementToNoninteractiveRole/valid.jsx
crates/biome_js_analyze/tests/specs/a11y/noInteractiveElementToNoninteractiveRole/valid.jsx.snap

Fixes #1095 
Added testcase for the issue.

fix: add `svg` as non-interactive html element

---

.cargo/config.toml
.github/workflows/bench_analyzer.yml
.github/workflows/bench_css_formatter.yml
.github/workflows/bench_css_parser.yml
.github/workflows/bench_js_formatter.yml
.github/workflows/bench_js_parser.yml
.github/workflows/bench_json_formatter.yml
.github/workflows/bench_json_parser.yml
Cargo.lock
xtask/bench/Cargo.toml
xtask/bench/benches/analyzer.rs
xtask/bench/benches/css_formatter.rs
xtask/bench/benches/css_parser.rs
xtask/bench/benches/js_formatter.rs
xtask/bench/benches/js_parser.rs
xtask/bench/benches/json_formatter.rs
xtask/bench/benches/json_parser.rs
xtask/bench/src/lib.rs

It's possible that the issue with codspeed is due to the fact that we didn't use their [compact library](https://docs.codspeed.io/benchmarks/rust#plugging-codspeed).
This PR adds a feature to the benchmarks called `codspeed`, and it uses the compact library in CI.
Merge, trigger the CI and check the results

ci: use codspeed criterion 

---

website/src/components/Sponsors.astro
website/src/content/docs/index.mdx
website/src/content/docs/ja/index.mdx
website/src/content/docs/pt-br/index.mdx
website/src/content/docs/zh-cn/index.mdx

We had reports saying the image of the sponsor wasn't showing up. This PR fixes the issue.
I checked locally and it shows up now

fix(website): fix the sponsor image

---

.github/workflows/main.yml
.github/workflows/pull_request.yml
Cargo.lock
crates/biome_lsp/Cargo.toml
xtask/bench/Cargo.toml
xtask/libs_bench/Cargo.toml

Cleaning up some the messes I have been doing lol
CI must pass this time

ci: format and use `--all-targets` to detect used deps

---

crates/biome_cli/tests/cases/overrides_formatter.rs
crates/biome_cli/tests/snapshots/main_cases_overrides_formatter/does_not_change_formatting_language_settings_2.snap
crates/biome_service/src/configuration/overrides.rs

This PR fixes a bug in the computation of the overrides, languages settings.

fix(project): correctly compute language settings for overrides

---

website/src/content/docs/guides/integrate-in-editor.mdx

doc(editors): how to use biome in `lsp-mode` for Emacs

---

website/src/content/docs/reference/configuration.mdx

docs: fixed indentation on code example

---

website/astro.config.ts
website/src/content/docs/recipes/git-hooks.mdx

feat(website): add Git Hooks recipe

---

packages/@biomejs/js-api/README.md

docs(@biomejs/js-api): remove unnecessary `await` in readme

---

website/src/content/docs/linter/rules/no-global-eval.md
website/src/content/docs/linter/rules/no-invalid-use-before-declaration.md
website/src/content/docs/linter/rules/no-misleading-character-class.md
website/src/content/docs/linter/rules/no-nodejs-modules.md
website/src/content/docs/linter/rules/no-then-property.md
website/src/content/docs/linter/rules/no-useless-ternary.md
website/src/content/docs/linter/rules/use-consistent-array-type.md
website/src/content/docs/linter/rules/use-export-type.md
website/src/content/docs/linter/rules/use-filenaming-convention.md
website/src/content/docs/linter/rules/use-for-of.md
website/src/content/docs/linter/rules/use-nodejs-import-protocol.md
website/src/content/docs/linter/rules/use-number-namespace.md
website/src/content/docs/linter/rules/use-shorthand-function-type.md
xtask/lintdoc/src/main.rs

This PR adds some danger messages to notify users when a rule hasn't been released yet.

docs(website): mark not released rules

---

packages/@biomejs/biome/README.md
packages/@biomejs/biome/README.pt-br.md
packages/@biomejs/biome/README.zh-CN.md

Update rule count in the READMEs.

docs(README): update rule count

---

website/src/content/docs/reference/configuration.mdx

The explanation of `extends` was outdated. This PR fixes it
Proof read

fix(docs): the documentation was outdated

---

CHANGELOG.md
crates/biome_js_analyze/src/analyzers/complexity/no_for_each.rs
crates/biome_js_analyze/tests/specs/complexity/noForEach/invalid.js
crates/biome_js_analyze/tests/specs/complexity/noForEach/invalid.js.snap
crates/biome_js_analyze/tests/specs/complexity/noForEach/valid.js
crates/biome_js_analyze/tests/specs/complexity/noForEach/valid.js.snap
website/src/content/docs/internals/changelog.mdx
website/src/content/docs/linter/rules/no-for-each.md

refactor(lint/noForEach): don't report forEach callback with 2+ parameters

---

website/src/content/blog/roadmap-2024.md

Just fixing the typo in Roadmap 2024
N/A

Fix typo in roadmap-2024.md

---

CHANGELOG.md
crates/biome_js_analyze/src/analyzers/complexity/use_arrow_function.rs
crates/biome_js_analyze/tests/specs/complexity/useArrowFunction/invalid.ts
crates/biome_js_analyze/tests/specs/complexity/useArrowFunction/invalid.ts.snap
website/src/content/docs/internals/changelog.mdx

Fix #1502
I added a regression test.

fix(lint/useArrowFunction): handle comma sequence in return position

---

CHANGELOG.md
packages/@biomejs/biome/package.json
website/src/content/docs/internals/changelog.mdx
website/src/content/docs/reference/cli.mdx
website/src/pages/schemas/1.5.1/schema.json.js

release: 1.5.1

---

CHANGELOG.md
website/src/content/docs/internals/changelog.mdx

fix(chaneglog): correctly place the last changelog entry

---

website/src/content/docs/ja/recipes/continuous-integration.mdx
website/src/content/docs/pt-br/recipes/continuous-integration.mdx
website/src/content/docs/recipes/continuous-integration.mdx
website/src/content/docs/zh-cn/recipes/continuous-integration.mdx

[Setup Biome GitHub Actions](https://github.com/biomejs/setup-biome) was updated to v2.
To match this, update the all language documents in repo.
N/A

docs(website): update `biomejs/setup-biome@v2`

---

CHANGELOG.md
crates/biome_cli/src/execute/traverse.rs
crates/biome_cli/tests/cases/diagnostics.rs
crates/biome_cli/tests/snapshots/main_cases_diagnostics/max_diagnostics.snap
crates/biome_cli/tests/snapshots/main_cases_diagnostics/max_diagnostics_no_verbose.snap
crates/biome_cli/tests/snapshots/main_cases_diagnostics/max_diagnostics_verbose.snap
website/src/content/docs/internals/changelog.mdx

Fixes https://github.com/biomejs/biome/issues/1512
Added two new test cases

fix(cli): don't count verbose diagnostics

---

CHANGELOG.md
crates/biome_cli/tests/cases/overrides_formatter.rs
crates/biome_cli/tests/commands/format.rs
crates/biome_cli/tests/snapshots/main_commands_format/should_apply_different_formatting.snap
crates/biome_cli/tests/snapshots/main_commands_format/should_apply_different_formatting_with_cli.snap
crates/biome_service/src/file_handlers/mod.rs
website/src/content/docs/internals/changelog.mdx

We forgot to disable the handling of CSS file from the CLI
cc @faultyserver 
I tested it on a real-world project, and ignored - for now - the tests we have in the CLI

fix(cli): don't handle CSS files

---

CHANGELOG.md
crates/biome_cli/tests/cases/biome_json_support.rs
crates/biome_cli/tests/snapshots/main_cases_biome_json_support/biome_json_is_not_ignored.snap
crates/biome_service/src/workspace/server.rs
website/src/content/docs/internals/changelog.mdx

The file `biome.json` can't be ignored anymore. 
Closes https://github.com/biomejs/biome/issues/1469

fix: the file `biome.json` can't be ignored

---

CHANGELOG.md
crates/biome_cli/src/execute/std_in.rs
crates/biome_cli/tests/cases/protected_files.rs
crates/biome_cli/tests/snapshots/main_cases_protected_files/not_process_file_from_stdin_format.snap
crates/biome_cli/tests/snapshots/main_cases_protected_files/not_process_file_from_stdin_lint.snap
crates/biome_cli/tests/snapshots/main_cases_protected_files/not_process_file_from_stdin_verbose_format.snap
crates/biome_cli/tests/snapshots/main_cases_protected_files/not_process_file_from_stdin_verbose_lint.snap
crates/biome_cli/tests/snapshots/main_cases_protected_files/should_return_the_content_of_protected_files_via_stdin.snap
website/src/content/docs/internals/changelog.mdx

fix(cli): return the original content when a protected file is encountered

---

CHANGELOG.md
crates/biome_cli/tests/commands/format.rs
crates/biome_cli/tests/snapshots/main_commands_format/does_not_format_ignored_file_in_included_directory.snap
crates/biome_cli/tests/snapshots/main_commands_format/does_not_format_non_included_and_ignored_files.snap
crates/biome_service/src/settings.rs
crates/biome_service/src/workspace/server.rs
website/src/content/docs/guides/how-biome-works.mdx
website/src/content/docs/internals/changelog.mdx

fix(config): don't ignore 'include' when 'ignore' is set

---

CHANGELOG.md
website/src/content/docs/internals/changelog.mdx

- Add `Unreleased` section
- Fix some typo

chore(CHANGELOG): add Unreleased section and fix typo

---

crates/biome_cli/fixtures/input.json
crates/biome_cli/src/execute/migrate.rs
crates/biome_cli/src/execute/migrate/prettier.rs
crates/biome_cli/src/execute/process_file.rs
crates/biome_cli/tests/commands/migrate.rs
crates/biome_cli/tests/snapshots/main_commands_migrate/emit_diagnostic_for_rome_json.snap
crates/biome_cli/tests/snapshots/main_commands_migrate/prettier_migrate.snap
crates/biome_cli/tests/snapshots/main_commands_migrate/prettier_migrate_no_file.snap
crates/biome_cli/tests/snapshots/main_commands_migrate/prettier_migrate_write.snap
crates/biome_cli/tests/snapshots/main_commands_migrate/prettier_migrate_yml_file.snap

When we migrate the configuration from Prettier, I decided to **not** run the other migrations. What do you think? Should we run them at the end?
This PR adds the required operations for the migration from prettier:
- file system operations
- workspace operations
- merging strategy to the main configuration
I added new tests cases, errors too

feat(cli): file system prettier migration 

---

website/src/content/docs/recipes/git-hooks.mdx

fix wrong variable name `pushed_files` to `push_files`

docs(website): fix lefthook pre-push recipe

---

CHANGELOG.md
crates/biome_js_analyze/src/semantic_analyzers/correctness/use_exhaustive_dependencies.rs
crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/issue1194.ts
crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/issue1194.ts.snap
website/src/content/docs/internals/changelog.mdx

Fix #1194 
I added a non-regression test.

fix(lint/useExhaustiveDependencies): do not panic on TS import equal

---

CHANGELOG.md
crates/biome_cli/tests/commands/format.rs
crates/biome_cli/tests/snapshots/main_commands_format/don_t_format_ignored_known_jsonc_files.snap
crates/biome_service/src/diagnostics.rs
crates/biome_service/src/file_handlers/json.rs
crates/biome_service/src/file_handlers/mod.rs
crates/biome_service/src/workspace/server.rs
website/src/content/docs/internals/changelog.mdx

fix(config): don't include ignored files known to be jsonc files when ignoreUnknown is true

---

website/src/content/docs/recipes/git-hooks.mdx

fix(website): fix lint-staged glob pattern

---

CHANGELOG.md
packages/@biomejs/biome/package.json
website/src/content/docs/guides/getting-started.mdx
website/src/content/docs/internals/changelog.mdx
website/src/content/docs/ja/guides/getting-started.mdx
website/src/content/docs/pt-br/guides/getting-started.mdx
website/src/content/docs/reference/configuration.mdx
website/src/content/docs/zh-cn/guides/getting-started.mdx
website/src/content/docs/zh-cn/reference/configuration.mdx
website/src/pages/schemas/1.5.3/schema.json.js

This patch version includes important bug fixes for the LSP and the `overrides` config property.

release: 1.5.3

---

CHANGELOG.md
crates/biome_cli/src/execute/diagnostics.rs
crates/biome_cli/src/execute/process_file.rs
crates/biome_fs/src/fs/os.rs
website/src/content/docs/internals/changelog.mdx

Closes https://github.com/biomejs/biome/issues/1508
I tested locally using our repository with a testing branch

fix(cli): don't processed deleted files with `--changed`

---

crates/biome_js_analyze/src/semantic_analyzers/correctness/use_exhaustive_dependencies.rs
crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/valid.js
crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/valid.js.snap

Handles dynamic computed property access correctly.
It should not break on dynamic properties but instead skip over because it's iterating in reverse order.
Fixes #1636
Fixes #1637
Added a reproduction test case

fix(lint/useExhaustiveDependencies): handle dynamic computed property access correctly

---

CHANGELOG.md
crates/biome_lsp/src/handlers/formatting.rs
crates/biome_lsp/src/server.rs
crates/biome_lsp/src/session.rs
crates/biome_lsp/tests/server.rs
crates/biome_service/src/workspace/server.rs
website/src/content/docs/internals/changelog.mdx

Closes https://github.com/biomejs/biome/issues/1654
I also changed the logging level of some instrumentation because logs  can get quite lengthy 
I had to change the server factory a bit to accept an external file system, so we can inject the configuration file.

fix(lsp): don't format ignored files

---

CHANGELOG.md
website/src/content/docs/internals/changelog.mdx

docs(changelog): fix incorrect rule name (`noSortedClasses` => `useSortedClasses`)

---

crates/biome_lsp/src/documents.rs
crates/biome_service/src/workspace.rs
crates/biome_service/src/workspace/server.rs

Minor cleanup. Remove unused parameter from `get_parse`.

refactor(biome_service): cleanup get_parse

---

CHANGELOG.md
crates/biome_cli/tests/main.rs
crates/biome_cli/tests/snapshots/main_configuration/override_globals.snap
crates/biome_service/src/configuration/overrides.rs
crates/biome_service/src/file_handlers/javascript.rs
crates/biome_service/src/matcher/mod.rs
crates/biome_service/src/settings.rs
website/src/content/docs/internals/changelog.mdx

This fixes an issue where `globals` inside `overrides` didn't get picked up.

Fix overriding of globals

---

crates/biome_cli/tests/cases/diagnostics.rs
crates/biome_cli/tests/cases/protected_files.rs
crates/biome_cli/tests/snapshots/main_cases_diagnostics/max_diagnostics_verbose.snap
crates/biome_cli/tests/snapshots/main_cases_protected_files/not_process_file_from_cli.snap
crates/biome_cli/tests/snapshots/main_cases_protected_files/not_process_file_from_cli_verbose.snap
crates/biome_cli/tests/snapshots/main_cases_protected_files/not_process_file_from_stdin_verbose_format.snap
crates/biome_cli/tests/snapshots/main_cases_protected_files/not_process_file_from_stdin_verbose_lint.snap
crates/biome_service/src/workspace.rs

Allows formatting package.json files.
Resolves: https://github.com/biomejs/biome/issues/1668

feat(formatter): Format package.json #1668

---

packages/@biomejs/js-api/src/index.ts

To maintain code consistency, just like the existing relationship between `FormatContentOptions` and `FormatContentDebugOptions`, `FormatDebugResult` inherits from `FormatResult`.
I have defined a wrapper for the first try-catch block that was used twice. This part of the code is considered less important when reading, so I have changed it to a declarative style that focuses on 'what' is happening rather than 'how.' This approach also enhances readability.
All test cases pass.

refactor(js-api): improve readability and reusability

---

crates/biome_js_analyze/src/globals/typescript.rs

Add the `NoInfer` utility type which was introduced in typescript@5.4 in `TYPESCRIPT_BUILTIN` list
Reference https://devblogs.microsoft.com/typescript/announcing-typescript-5-4-beta/#the-noinfer-utility-type
CI

feat(js_analyzer): recognize the `NoInfer` utility type

---

crates/biome_js_analyze/src/analyzers/suspicious/no_implicit_any_let.rs
website/src/content/blog/biome-wins-prettier-challenge.md
website/src/content/docs/linter/rules/no-implicit-any-let.md

This is a more natural phrasing
~There's a snapshot test that I need to figure out how to update~
Updated the snapshots, thanks @Conaclos for the help!

Swap order of words in "has implicitly" -> "implicitly has"

---

website/src/content/docs/analyzer/index.mdx

fix(website): fix typo on analyzer page

---

CHANGELOG.md
crates/biome_js_analyze/src/suppression_action.rs
crates/biome_js_analyze/tests/spec_tests.rs
crates/biome_js_analyze/tests/suppression/correctness/noUndeclaredVariables/noUndeclaredVariables.ts.snap
crates/biome_js_analyze/tests/suppression/correctness/noUnusedVariables/ts-module-export.ts.snap
crates/biome_js_analyze/tests/suppression/suspicious/noArrayIndexKey/noArrayIndexKey.jsx.snap
crates/biome_js_analyze/tests/suppression/suspicious/noAssignInExpressions/noAssignInExpressions.ts
crates/biome_js_analyze/tests/suppression/suspicious/noAssignInExpressions/noAssignInExpressions.ts.snap
crates/biome_js_analyze/tests/suppression/suspicious/noDoubleEquals/noDoubleEquals.jsx.snap
website/src/content/docs/internals/changelog.mdx

close #1697 
added a test case

fix(analyzer/suppression): insert the existing leading whitespaces in action

---

CONTRIBUTING.md
crates/biome_js_formatter/src/comments.rs
website/README.md
xtask/codegen/html.ungram

chore: fix typo

---

.github/FUNDING.yml
packages/@biomejs/biome/README.md

This PR adds a new heading called `## Funding` to the readme, as a way to prompt to the users **how** we seek funding.
Proof read. [Rendered heading](https://github.com/biomejs/biome/blob/chore/funding-update/packages/@biomejs/biome/README.md#funding)

chore: add funding section to README.md

---

crates/biome_js_analyze/src/analyzers/suspicious/no_implicit_any_let.rs
website/src/content/docs/linter/rules/no-implicit-any-let.md

This PR does not do anything except reword two sentences in the diagnostic.
It rewords two sentences to make them grammatically correct English.
Unit tests still pass (I hope)

chore(lint/noImplicitAnyLet): reword diagnostic

---

.github/workflows/ja-translation.yaml
.github/workflows/pull_request.yml
.github/workflows/pull_request_js.yml
.github/workflows/release_js_api.yml
.github/workflows/runtime.yml

GitHub is [planning to upgrade to Node 20](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/). Versions prior to actions/cache v3 use an outdated version of node, so we will upgrade to actions/cache v4, where [Node 20 is the default](https://github.com/actions/cache/releases/tag/v4.0.0).

chore: Bump actions/cache

---

website/src/content/docs/ja/reference/vscode.mdx
website/src/content/docs/pt-br/reference/vscode.mdx
website/src/content/docs/reference/vscode.mdx
website/src/content/docs/zh-cn/reference/vscode.mdx

Fix #1631 
Update all languages

docs(reference/vscode): fix setting value

---

CONTRIBUTING.md

chore: add @anonrig to maintainers

---

crates/biome_diagnostics_categories/src/categories.rs
crates/biome_js_analyze/src/semantic_analyzers/nursery.rs
crates/biome_js_analyze/src/semantic_analyzers/nursery/no_console.rs
crates/biome_js_analyze/tests/specs/nursery/noConsole/invalid.js
crates/biome_js_analyze/tests/specs/nursery/noConsole/invalid.js.snap
crates/biome_js_analyze/tests/specs/nursery/noConsole/valid.js
crates/biome_js_analyze/tests/specs/nursery/noConsole/valid.js.snap
crates/biome_service/src/configuration/linter/rules.rs
packages/@biomejs/backend-jsonrpc/src/workspace.ts
packages/@biomejs/biome/configuration_schema.json
website/src/components/generated/NumberOfRules.astro
website/src/content/docs/linter/rules/index.mdx
website/src/content/docs/linter/rules/no-console.md

This PR adds `noConsole`
PS: We already have `noConsoleLog` rule.

feat(lint/noConsole): add rule

---

CONTRIBUTING.md

Add myself to CONTRIBUTING.md as maintainer

---

Cargo.lock
Cargo.toml
crates/biome_cli/Cargo.toml
crates/biome_fs/Cargo.toml
xtask/codegen/Cargo.toml
xtask/coverage/Cargo.toml

There are some security advisories that this PR attempts to fix

chore: update some deps

---

crates/biome_js_analyze/src/analyzers/nursery/no_nodejs_modules.rs
crates/biome_js_analyze/src/analyzers/nursery/no_restricted_imports.rs
crates/biome_js_analyze/src/analyzers/nursery/no_undeclared_dependencies.rs
crates/biome_js_analyze/src/analyzers/nursery/use_nodejs_import_protocol.rs
crates/biome_js_analyze/tests/specs/nursery/noUndeclaredDependencies/invalid.js
crates/biome_js_analyze/tests/specs/nursery/noUndeclaredDependencies/invalid.js.snap
crates/biome_js_analyze/tests/specs/nursery/noUndeclaredDependencies/valid.js
crates/biome_js_analyze/tests/specs/nursery/noUndeclaredDependencies/valid.js.snap
crates/biome_js_syntax/src/import_ext.rs
crates/biome_js_syntax/src/lib.rs

This PR adds more cases for `noUndeclaredDependencies`
I also took the opportunity to refactor some of the repeated code.
New test cases added

chore(lint): cover more cases for noUndeclaredDependencies

---

crates/biome_cli/src/commands/ci.rs
crates/biome_cli/src/commands/mod.rs

Some linter workaround wasn't applied to the `ci` command. This PR applies the appropriate changes
CI should pass

fix(cli): apply linter logic to CI command

---

crates/biome_js_analyze/src/semantic_analyzers/nursery/use_sorted_classes.rs
crates/biome_js_analyze/src/semantic_analyzers/nursery/use_sorted_classes/any_class_string_like.rs
crates/biome_js_analyze/tests/specs/nursery/useSortedClasses/codeOptionsUnsorted.jsx.snap
crates/biome_js_analyze/tests/specs/nursery/useSortedClasses/unsorted.jsx
crates/biome_js_analyze/tests/specs/nursery/useSortedClasses/unsorted.jsx.snap

This PR adds support for partial templates for the rule `useSortedClasses`.
The snapshots should be correctly updated

feat(lint): partial support for tagged templates

---

website/src/content/docs/analyzer/index.mdx
website/src/content/docs/ja/analyzer/index.mdx
website/src/content/docs/ja/reference/vscode.mdx
website/src/content/docs/pt-br/analyzer/index.mdx
website/src/content/docs/pt-br/reference/vscode.mdx
website/src/content/docs/reference/vscode.mdx
website/src/content/docs/zh-cn/analyzer/index.mdx
website/src/content/docs/zh-cn/reference/vscode.mdx

Updates docs for the VSCode LSP plugin settings.
VSCode is deprecating the boolean type for the `editor.codeActionsOnSave` settings. It will automatically prompt the user to update these settings but this change will help new users who might be confused on which format is correct.

docs: update vscode setting docs

---

CHANGELOG.md
crates/biome_js_analyze/src/analyzers/complexity/no_static_only_class.rs
website/src/content/docs/internals/changelog.mdx
website/src/content/docs/linter/rules/no-static-only-class.md

Presumably a link was meant to be included to this article here
Also fixed a couple of headings in the changelog

fix(documentation): add link to external article

---

crates/biome_analyze/src/rule.rs
crates/biome_js_analyze/src/analyzers/nursery/use_import_restrictions.rs
website/src/content/docs/linter/rules/use-import-restrictions.md

This PR fixes the rule source of the useImportRestrictions lint rule.

docs(lint/useImportRestrictions): fix the rule source

---

website/src/content/docs/guides/how-biome-works.mdx
website/src/content/docs/reference/cli.mdx

After updating the cli options in #1844, this is the PR for updating the website.
Closes #1101 
Tests pass 👍

docs: Update website for --config-path disabling default resolution method

---

CONTRIBUTING.md

chore: add `togami2864` to maintainers team

---

crates/biome_js_analyze/src/semantic_analyzers/nursery/no_console.rs
crates/biome_js_analyze/src/semantic_analyzers/suspicious/no_console_log.rs
crates/biome_js_analyze/tests/specs/nursery/noConsole/invalid.js
crates/biome_js_analyze/tests/specs/nursery/noConsole/invalid.js.snap
crates/biome_js_analyze/tests/specs/suspicious/noConsoleLog/invalid.js
crates/biome_js_analyze/tests/specs/suspicious/noConsoleLog/invalid.js.snap

Change to remove the semicolon from the autofix of the noConsoleLog/noConsole rule.
added tests

fix: remove remaining semicolon from the autofix of noConsole/noConsoleLog

---

website/src/components/PackageManagerBiomeCommand.astro
website/src/components/PackageManagerCommand.astro
website/src/frontend-scripts/package-manager-commands.ts
website/src/styles/_overrides.scss
website/src/styles/_pre.scss

Replacing the old copy button and using the code component from starlight to have a more asymmetric style.

Copy button with code component from starlight

---

crates/biome_js_analyze/src/analyzers/a11y/use_valid_anchor.rs
crates/biome_js_analyze/src/lib.rs
crates/biome_js_analyze/tests/specs/a11y/useValidAnchor/invalid.jsx
crates/biome_js_analyze/tests/specs/a11y/useValidAnchor/invalid.jsx.snap
crates/biome_js_analyze/tests/specs/a11y/useValidAnchor/valid.jsx
crates/biome_js_analyze/tests/specs/a11y/useValidAnchor/valid.jsx.snap
website/src/content/docs/linter/rules/use-valid-anchor.md

Closes https://github.com/biomejs/biome/issues/1835
New tests added.
Now anchor with onClick property should not throw an error when there is a valid href value
```js
<a href="http://www.deque.com" onclick="window.open(this.href); return false;"> Annual Reports </a>
```

fix(lint/useValidAnchor):  fix progressively enhanced anchors are flagged

---

CHANGELOG.md
crates/biome_js_analyze/src/assists/correctness/organize_imports.rs
crates/biome_js_analyze/tests/specs/correctness/organizeImports/groups.js.snap
website/src/content/config.ts
website/src/content/docs/analyzer/index.mdx
website/src/content/docs/internals/changelog.mdx
website/src/pages/feed.xml.js
website/src/pages/og/[...path].ts

This PR fixes an issue in the import sorting.
Modules with protocols are now moved after `npm:`. 
Updated the current test cases and the documentation.

fix(analyzer): virtual modules should come first

---

website/src/content/docs/ja/recipes/git-hooks.mdx

Fixes an inconsistency in the git hooks doc, which is my mistake on #1892.
I mistakenly fixed the Lefthook section instead of the husky section in the Japanese docs.
I apologize for not recognizing the mistake. I'm so sorry to bother you.

docs(recipes/git-hooks): fix inconsistency between translations

---

website/src/content/docs/recipes/git-hooks.mdx

* Correct grammar and typos in a couple of sections
* The changes aim to improve the clarity and correctness of the contributing guide.
* Manually reviewed each section for grammar and typos.
* Although minor, ensured and verified that the changes remain consistent with the existing structure and conventions.

docs: Fix minor typos in Git Hooks guide

---

CHANGELOG.md
website/src/content/docs/internals/changelog.md

- Update CHANGELOG.md
- Related to [lint/noSemicolonInJsx](https://github.com/biomejs/biome/pull/1881)

docs: update CHANGELOG

---

website/_redirects

This PR adds a redirct from `biomejs.com` to `biomejs.dev`
Merge it, deploy it to Netlify and see if that works.

chore(website): add redirect

---

CHANGELOG.md
crates/biome_js_analyze/src/semantic_analyzers/correctness/no_unused_variables.rs
crates/biome_js_analyze/tests/specs/correctness/noUnusedVariables/validObjectDestructuring.js
crates/biome_js_analyze/tests/specs/correctness/noUnusedVariables/validObjectDestructuring.js.snap
website/src/content/docs/internals/changelog.md

- Closes https://github.com/biomejs/biome/issues/1910
Add a new test case

feat(lint/noUnusedVariables): ignore unused rest spread siblings

---

crates/biome_diagnostics_categories/src/categories.rs
crates/biome_js_analyze/src/analyzers/nursery.rs
crates/biome_js_analyze/src/analyzers/nursery/no_duplicate_test_hooks.rs
crates/biome_js_analyze/src/analyzers/nursery/no_excessive_nested_test_suites.rs
crates/biome_js_analyze/src/analyzers/nursery/no_focused_tests.rs
crates/biome_js_analyze/src/analyzers/nursery/no_skipped_tests.rs
crates/biome_js_analyze/src/options.rs
crates/biome_js_analyze/tests/specs/nursery/noExcessiveNestedTestSuites/invalid.js
crates/biome_js_analyze/tests/specs/nursery/noExcessiveNestedTestSuites/invalid.js.snap
crates/biome_js_analyze/tests/specs/nursery/noExcessiveNestedTestSuites/valid.js
crates/biome_js_analyze/tests/specs/nursery/noExcessiveNestedTestSuites/valid.js.snap
crates/biome_js_syntax/src/expr_ext.rs
crates/biome_service/src/configuration/linter/rules.rs
packages/@biomejs/backend-jsonrpc/src/workspace.ts
packages/@biomejs/biome/configuration_schema.json
website/src/components/generated/NumberOfRules.astro
website/src/content/docs/linter/rules/index.mdx
website/src/content/docs/linter/rules/no-excessive-nested-test-suites.md

Part of https://github.com/biomejs/biome/issues/1848
Implements the rule without option.
Snapshots test added

feat(lint/noNestTestSuites): add rule

---

website/src/content/docs/linter/rules/use-filenaming-convention.md

just fixed a typo that I've found in an older PR
not needed, this is just docs

fix: typo and more descriptive info

---

crates/biome_diagnostics_categories/src/categories.rs
website/src/content/docs/linter/rules/use-consistent-array-type.md

Just a simple find-and-replace.
Fixes #1939.

fix: `use-consistent-array-type` lint rule url

---

website/src/content/docs/zh-cn/index.mdx

Update Simplified Chinese homepage.
Related: #1958
Run `pnpm start` locally and check/compare the translated homepage on the dev server with the default one.

docs(zh-cn): update homepage

---

crates/biome_js_analyze/src/analyzers/a11y/use_valid_anchor.rs
website/src/content/docs/linter/rules/use-valid-anchor.md

Just improved `useValidAnchor` documentation. Related: #1873 
CI should pass

chore: improve useValidAnchor doc

---

website/src/content/docs/ja/index.mdx

Update Japanese homepage.
Related: https://github.com/biomejs/biome/issues/1958
I referred to this pull request. https://github.com/biomejs/biome/pull/1959
Run homepage locally and check it.

docs(ja): update homepage

---

website/src/content/docs/ja/index.mdx

- Update `ja/index.mdx` (continuing from #1960).
- Translate sections that are still in English.
- Revise translations that sound unnatural.
- Remove unnecessary spaces.
Additional comments in Japanese are left below for the Japanese reviewers.
Visually checked the Japanese homepage and verified that it is functioning without any problems.

docs(ja): Update `ja/index.mdx`

---

website/src/content/docs/ja/guides/manual-installation.mdx

The translation of "the Biome version you want to install" was incorrect, so I have corrected it.
Visually checked the updated page locally and verified that it is functioning without any problems.

docs(ja): fix incorrect translation in manual-installation.mdx

---

website/astro.config.ts

The page "Integrate Biome with your VCS" has already been translated into Chinese, but I noticed that the sidebar content was still in English, so I've corrected it. Also, I believe that "大型项目使用 Biome" should actually be "大型项目中使用 Biome" for accuracy, so I've made that change as well (I have some understanding of Chinese, but I'm not a native speaker, so please let me know if this is incorrect).
Visually checked the updated sidebar locally and verified that it is functioning without any problems.

docs(zh-cn): Update sidebar items

---

Cargo.lock
Cargo.toml
xtask/libs_bench/Cargo.toml

Cause: https://github.com/biomejs/biome/actions/runs/8164847182/job/22320938708
Hopefully the CI should pass and we should be able to flash out a nightly

chore: update deps due to security advisories

---

CHANGELOG.md
packages/@biomejs/biome/package.json
packages/@biomejs/js-api/package.json
website/src/content/docs/internals/changelog.md

I reverted `package.json` here https://github.com/biomejs/biome/commit/efe55dac2cb3b790b74794785cdd5304ae6fd82b
Let's see if this time the CI triggers the release
Merge and check if the actions is triggered

chore: trigger CI

---

packages/@biomejs/js-api/tests/__snapshots__/lintContent.test.ts.snap

follow-up #2006 
I executed `pnpm --prefix packages/@biomejs/js-api test:ci --update`
update snapshot in js-api

chore: update js-api snapshot

---

CHANGELOG.md
website/src/content/docs/internals/changelog.md

Update correct release date.
N/A

fix: typo v1.6.0 release month

---

CHANGELOG.md
website/src/content/docs/internals/changelog.md

Add a few changelog entries for previous PRs.

docs(changelog): add a few changelog entries

---

CHANGELOG.md
crates/biome_diagnostics_categories/src/categories.rs
crates/biome_js_analyze/src/analyzers/nursery.rs
crates/biome_js_analyze/src/analyzers/nursery/no_done_callback.rs
crates/biome_js_analyze/src/options.rs
crates/biome_js_analyze/tests/specs/nursery/noDoneCallback/invalid.js
crates/biome_js_analyze/tests/specs/nursery/noDoneCallback/invalid.js.snap
crates/biome_js_analyze/tests/specs/nursery/noDoneCallback/valid.js
crates/biome_js_analyze/tests/specs/nursery/noDoneCallback/valid.js.snap
crates/biome_js_syntax/src/expr_ext.rs
crates/biome_service/src/configuration/linter/rules.rs
packages/@biomejs/backend-jsonrpc/src/workspace.ts
packages/@biomejs/biome/configuration_schema.json
website/src/components/generated/NumberOfRules.astro
website/src/content/docs/internals/changelog.md
website/src/content/docs/linter/rules/index.mdx
website/src/content/docs/linter/rules/no-done-callback.md

Part of https://github.com/biomejs/biome/issues/1848
Implement rule without code fix.
Added snapshot tests

feat(lint/noDoneCallback): add rule

---

CHANGELOG.md
crates/biome_cli/src/execute/process_file/lint.rs
packages/@biomejs/biome/package.json
website/src/content/docs/guides/getting-started.mdx
website/src/content/docs/guides/how-biome-works.mdx
website/src/content/docs/internals/changelog.md
website/src/content/docs/ja/guides/getting-started.mdx
website/src/content/docs/pt-br/guides/getting-started.mdx
website/src/content/docs/reference/configuration.mdx
website/src/content/docs/zh-cn/guides/getting-started.mdx
website/src/content/docs/zh-cn/reference/configuration.mdx
website/src/pages/schemas/1.6.1/schema.json.js

Maybe we can include some other fix and then release it

release: 1.6.1

---

Cargo.lock
Cargo.toml
crates/biome_string_case/Cargo.toml
scripts/publish-crates.sh

Make `biome_string_case` publishable by setting a version, removing `publish = false` and adding it in `scripts/publish-crates.sh`. 

refactor: make biome_string_case publishable

---

crates/biome_deserialize/README.md

This adds the docs removed in #1564
No change.

doc: add docs removed in #1564

---

crates/biome_cli/tests/snap_test.rs

Sorry, my brain wasn't functioning...
Existing snapshots shouldn't change.

fix(tests_infra): `TIME_REGEX` for snapshot redaction

---

.github/workflows/main.yml
.github/workflows/pull_request.yml

I added the action to `main.yml` too
Check if this CI passes. Then merge it and monitor the main CI.

ci: use action to free-up space in main

---

.github/workflows/main.yml
.github/workflows/pull_request.yml

ci: use action to free-up space in main v2

---

.github/ISSUE_TEMPLATE/config.yml

I've seen multiple reports in the main repository around VScode and IntelliJ while they were supposed to be filed in the relative repositories.
I added two new links to the issue choice; hopefully, this will help.
N/A

chore: add two more options for guidance

---

.github/workflows/pull_request.yml

CI are failing due to disk size... not sure why :/
This PR adds the step that reduced the disk size to all steps
Merge it and rebase another PR to see if it works

ci: attempt to reduce disk size

---

.github/actions/free-disk-space/action.yaml
.github/workflows/main.yml
.github/workflows/pull_request.yml

This PR refactors the disk freeing instructions into an action, and adds it to some steps where it seemed necessary

ci: refactor disk freeing to action

---

.github/workflows/runtime.yml

The disk freeing action was missing in the `runtime.yml` workflow making it fail

ci: use disk freeing action for `runtime.yml`

---

website/src/content/docs/index.mdx
website/src/styles/_overrides.scss

That theme color stopped being used after Discord's 2021 rebrand, the new one is listed at https://discord.com/branding

chore(website): use new discord theme color

---

crates/biome_cli/Cargo.toml
crates/biome_css_formatter/Cargo.toml
crates/biome_css_formatter/src/lib.rs
crates/biome_service/Cargo.toml
crates/biome_service/src/file_handlers/css.rs
crates/biome_wasm/Cargo.toml
pnpm-lock.yaml
website/package.json
website/src/playground/Playground.tsx
website/src/playground/utils.ts
website/src/playground/workers/biomeWorker.ts
website/src/playground/workers/prettierWorker.ts

Add css formatting for the playground using the feature flag because our css formatting is unstable.
CI

feat(css_formatting): add css formatting for the playground

---

justfile

fix regression of #2065 
ran`just new-lint-rule crates/biome_js_analyze/src/semantic_analyzers/nursery myRuleName` and `just promote-rule noConsoleLog style` on my local machine, and it worked well.

fix: modify justfile related to lint rules

---

crates/biome_css_formatter/src/css/auxiliary/font_feature_values_item.rs
crates/biome_css_formatter/src/css/lists/font_feature_values_item_list.rs
crates/biome_css_formatter/src/css/statements/font_feature_values_at_rule.rs
crates/biome_css_formatter/tests/specs/css/atrule/font_feature_values.css
crates/biome_css_formatter/tests/specs/css/atrule/font_feature_values.css.snap
crates/biome_css_formatter/tests/specs/prettier/css/atrule/font-feature-values.css.snap
crates/biome_css_formatter/tests/specs/prettier/css/comments/at-rules.css.snap
crates/biome_parser/CONTRIBUTING.md
website/src/playground/workers/biomeWorker.ts

- Implement CssFontFeatureValuesAtRule formatting
- Pass a quote style option for a biome worker
cargo test

feat(css_formatter): CssFontFeatureValuesAtRule formatting

---

crates/biome_css_formatter/src/css/auxiliary/document_custom_matcher.rs
crates/biome_css_formatter/src/css/lists/document_matcher_list.rs
crates/biome_css_formatter/src/css/statements/document_at_rule.rs
crates/biome_css_formatter/src/utils/block_like.rs
crates/biome_css_formatter/tests/specs/css/atrule/document.css
crates/biome_css_formatter/tests/specs/css/atrule/document.css.snap

Implement CssDocumentAtRule formatting
cargo test

feat(css_formatter): CssDocumentAtRule formatting

---

.github/renovate.json

It is blocking the CI in [#2485](https://github.com/biomejs/biome/actions/runs/8332835551/job/22802919140#step:6:572) and [#2486](https://github.com/biomejs/biome/actions/runs/8336585908/job/22813969432#step:6:571)

ci: format `renovate.json`

---

website/src/content/docs/internals/language-support.mdx
website/src/content/docs/ja/internals/language-support.mdx
website/src/content/docs/pt-br/internals/language-support.mdx
website/src/content/docs/zh-cn/internals/language-support.mdx

The CSS linter started moving forward 🔥🔥
CI should be passed

chore(doc): set the CSS linter status to 'In Progress'

---

CONTRIBUTING.md

Add @Sec-ant to the maintainers team.

chore: update maintainers

---

.github/workflows/main.yml
.github/workflows/parser_conformance.yml

Add free-disk-space step to two more jobs and remove one redundant checkout step.
CI and CI on main should pass.

chore(ci): free disk space

---

CHANGELOG.md
crates/biome_js_analyze/src/lib.rs
crates/biome_js_analyze/src/lint/nursery/use_sorted_classes.rs
crates/biome_js_analyze/src/lint/nursery/use_sorted_classes/any_class_string_like.rs
crates/biome_js_analyze/tests/specs/nursery/useSortedClasses/codeOptionsSorted.jsx
crates/biome_js_analyze/tests/specs/nursery/useSortedClasses/codeOptionsSorted.jsx.snap
crates/biome_js_analyze/tests/specs/nursery/useSortedClasses/codeOptionsUnsorted.jsx
crates/biome_js_analyze/tests/specs/nursery/useSortedClasses/codeOptionsUnsorted.jsx.snap
crates/biome_js_analyze/tests/specs/nursery/useSortedClasses/sorted.jsx
crates/biome_js_analyze/tests/specs/nursery/useSortedClasses/sorted.jsx.snap
crates/biome_js_analyze/tests/specs/nursery/useSortedClasses/unsorted.jsx
crates/biome_js_analyze/tests/specs/nursery/useSortedClasses/unsorted.jsx.snap
website/src/content/docs/internals/changelog.md

Part of #1274 
It adds support for object member properties. 
Updated the current snapshots

feat(lint): support literal names for `useSortedClasses`

---

GOVERNANCE.md

This PR update the governance document, to address the following:
- it clarifies the voting rules and dynamic by adding `**private**` to the word "thread"
- reduce the voting period from seven days to three. I have been noticing that seven days is a very long period, and the majority of voting sessions we've had finish even before three days
- it adds many clarifications around the expense policy and how leads can submit expenses. When I wrote this section, I took some knowledge for granted, which was a mistake on my end. 
The majority of @biomejs/core-contributors must read and approve the PR

chore: update governance document

---

CHANGELOG.md
crates/biome_js_analyze/src/lint/style/use_naming_convention.rs
crates/biome_js_analyze/src/utils/rename.rs
crates/biome_js_analyze/tests/specs/style/useNamingConvention/validComponentName.js
crates/biome_js_analyze/tests/specs/style/useNamingConvention/validComponentName.js.snap
crates/biome_js_formatter/src/syntax_rewriter.rs
website/src/content/docs/internals/changelog.md

fix(lint): useNamingConvention should't ignore jsx component name binding

---

CONTRIBUTING.md

chore: add myself as a maintainer

---

CHANGELOG.md
packages/@biomejs/biome/package.json
website/src/content/docs/guides/getting-started.mdx
website/src/content/docs/guides/how-biome-works.mdx
website/src/content/docs/internals/changelog.md
website/src/content/docs/ja/guides/getting-started.mdx
website/src/content/docs/pt-br/guides/getting-started.mdx
website/src/content/docs/reference/configuration.mdx
website/src/content/docs/zh-cn/guides/getting-started.mdx
website/src/content/docs/zh-cn/reference/configuration.mdx
website/src/pages/schemas/1.6.4/schema.json.js

Patch release for tomorrow :)
N/A

release: 1.6.4

---

.github/workflows/release_cli.yml

We recently upgraded the CI jobs, but missed that there few breaking changes. This PR applies the migration guide 
https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md#multiple-uploads-to-the-same-named-artifact
Merge and trigger a nightly release

ci: fix release regression

---

packages/@biomejs/biome/package.json

chore: re-try release 1.6.4

---

website/src/content/docs/guides/big-projects.mdx
website/src/content/docs/guides/how-biome-works.mdx

This PR addresses few concerns about monorepos.

docs: add warning around nested config

---

CHANGELOG.md
website/src/content/docs/internals/changelog.md

I accidentally dropped something from the changelog: https://github.com/biomejs/biome/pull/2105/files#r1553651900

Revert incorrectly merged changelog

---

crates/biome_cli/src/execute/migrate/eslint_to_biome.rs

Improve migration of ESLint flat configurations when the configuration array contains a single object.
In this specific case, we directly use this object as the global Biome configuration.
Previously, we created an override object.
I added two tests.

refactor(migrate-eslint): improve flat config migration

---

CHANGELOG.md
crates/biome_js_analyze/src/lint/correctness/use_exhaustive_dependencies.rs
crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/valid.js
crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/valid.js.snap
website/src/content/docs/internals/changelog.md

Fixes https://github.com/biomejs/biome/issues/2361.

fix(lint/useExhaustiveDependencies): don't report recursive calls as missing dependencies

---

CHANGELOG.md
crates/biome_js_analyze/src/lint/nursery/no_done_callback.rs
crates/biome_js_analyze/src/lint/nursery/no_duplicate_else_if.rs
crates/biome_js_analyze/src/lint/nursery/no_evolving_any.rs
crates/biome_js_analyze/src/lint/nursery/no_misplaced_assertion.rs
crates/biome_js_analyze/src/lint/nursery/no_suspicious_semicolon_in_jsx.rs
website/src/content/docs/internals/changelog.md
website/src/content/docs/linter/rules/no-done-callback.md
website/src/content/docs/linter/rules/no-duplicate-else-if.md
website/src/content/docs/linter/rules/no-evolving-any.md
website/src/content/docs/linter/rules/no-misplaced-assertion.md
website/src/content/docs/linter/rules/no-suspicious-semicolon-in-jsx.md

Add missing changelog entries and update rule versions.

chore: update rule version

---

CHANGELOG.md
crates/biome_js_analyze/src/lint/correctness/use_exhaustive_dependencies.rs
crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/missingDependenciesInvalid.js
crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/missingDependenciesInvalid.js.snap
crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/valid.js
crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/valid.js.snap
website/src/content/docs/internals/changelog.md

Fixes https://github.com/biomejs/biome/issues/2362.

fix(lint/useExhaustiveDependencies): fix missing dependency from function declaration

---

CHANGELOG.md
crates/biome_cli/src/cli_options.rs
crates/biome_cli/src/execute/mod.rs
crates/biome_cli/tests/commands/check.rs
crates/biome_cli/tests/commands/format.rs
crates/biome_cli/tests/snapshots/main_commands_check/check_help.snap
crates/biome_cli/tests/snapshots/main_commands_ci/ci_help.snap
crates/biome_cli/tests/snapshots/main_commands_format/format_help.snap
crates/biome_cli/tests/snapshots/main_commands_lint/lint_help.snap
crates/biome_cli/tests/snapshots/main_commands_migrate/migrate_help.snap
crates/biome_cli/tests/snapshots/main_commands_rage/rage_help.snap
website/src/content/docs/internals/changelog.md

Follow up of https://github.com/biomejs/biome/pull/2364#issuecomment-2051403303
cc @Conaclos 
Updated the tests

chore: use `--reporter` option

---

crates/biome_cli/src/execute/mod.rs
crates/biome_configuration/src/javascript/mod.rs
crates/biome_configuration/src/linter/rules.rs
crates/biome_css_analyze/src/lint/nursery/no_color_invalid_hex.rs
crates/biome_js_analyze/src/globals/javascript/language.rs
crates/biome_js_analyze/src/globals/javascript/node.rs
crates/biome_js_analyze/src/globals/javascript/web.rs
crates/biome_js_analyze/src/globals/module/node.rs
crates/biome_js_analyze/src/globals/typescript/language.rs
crates/biome_js_analyze/src/globals/typescript/node.rs
crates/biome_js_analyze/src/globals/typescript/web.rs
crates/biome_js_analyze/src/lint/correctness/no_void_elements_with_children.rs
crates/biome_js_parser/src/lib.rs
crates/biome_js_semantic/src/events.rs
crates/biome_js_semantic/src/semantic_model/builder.rs
crates/biome_js_semantic/src/semantic_model/model.rs
crates/biome_js_syntax/src/expr_ext.rs
crates/biome_js_syntax/src/function_ext.rs
crates/biome_js_syntax/src/lib.rs
crates/biome_parser/CONTRIBUTING.md
crates/biome_parser/src/lib.rs
crates/biome_service/src/settings.rs
crates/biome_service/src/workspace.rs
justfile
packages/@biomejs/backend-jsonrpc/src/workspace.ts
packages/@biomejs/biome/configuration_schema.json
website/src/content/docs/linter/rules/index.mdx
website/src/content/docs/linter/rules/no-color-invalid-hex.md
xtask/codegen/src/generate_configuration.rs

I was annoyed by all these warnings of `lintdoc`.
This PR resolves these warnings.
Any idea how to make them hard errors to avoid regression?

refactor: resolve lintdoc warnings

---

CHANGELOG.md
crates/biome_analyze/src/rule.rs
crates/biome_js_analyze/src/lint/correctness/no_unused_variables.rs
crates/biome_js_analyze/src/lint/style/no_namespace.rs
crates/biome_js_analyze/tests/specs/style/noNamespace/invalid.ts.snap
website/src/components/generated/Sources.md
website/src/content/blog/biome-v1-6.mdx
website/src/content/docs/internals/changelog.md
website/src/content/docs/linter/rules-sources.mdx
website/src/content/docs/linter/rules/no-constant-math-min-max-clamp.md
website/src/content/docs/linter/rules/no-namespace.md
website/src/content/docs/zh-cn/internals/changelog.mdx

Fix a few typos and rewrite the history 😜 
Proofread.

fix: a few typos

---

website/src/content/blog/biome-v1-7.md

Noticed these two while reading the announcement blog post :)
N/A

docs: fix missing punctuation and typo

---

CHANGELOG.md
website/src/content/docs/internals/changelog.md

chore(changelog); add Unreleased section

---

.changeset/this_is_a_test.md

I added a changeset to test the prepare release workflow. I will delete this file later on
Merge it and see if the workflow is triggered and works as expected.

ci: trigger prepare release

---

CHANGELOG.md
crates/biome_js_analyze/src/lib.rs
crates/biome_js_analyze/src/lint/complexity/no_useless_fragments.rs
crates/biome_js_analyze/tests/specs/complexity/noUselessFragments/issue_2460.jsx
crates/biome_js_analyze/tests/specs/complexity/noUselessFragments/issue_2460.jsx.snap

fix(linter): fix edge case in `noUselessFragments`

---

crates/biome_css_analyze/src/lint/nursery/no_duplicate_font_names.rs
crates/biome_css_analyze/src/lint/nursery/no_duplicate_selectors_keyframe_block.rs
crates/biome_css_analyze/tests/specs/nursery/noDuplicateFontNames/invalid.css.snap
crates/biome_css_analyze/tests/specs/nursery/noDuplicateSelectorsKeyframeBlock/invalid.css.snap

follow-up #2534.
Updated lint messages of `noDuplicateFontNames` & `noDuplicateSelectorsKeyframeBlock`
updated snapshots

fix(biome_css_analyzer): update lint error messages

---

packages/@biomejs/biome/README.md

chore: add a new bronze sponsor

---

CHANGELOG.md
packages/@biomejs/biome/package.json

chore: release 1.7.1

---

crates/biome_configuration/src/javascript/mod.rs
packages/@biomejs/backend-jsonrpc/src/workspace.ts

See https://github.com/biomejs/biome/pull/2568#issuecomment-2071840710
just gen-bindings

fix: rename some fileds to camelCase in the `configuration_schema`

---

crates/biome_cli/src/execute/migrate/node.rs

Address the concern I expressed in [this comment](https://github.com/biomejs/biome/pull/2583#issuecomment-2074979928).
I added a JS function that removes cycles of an object.
It doesn't remove non-cyclic multiple references to a same object.
I manually tested using the [ESLint config of the Astro repository](https://github.com/withastro/astro/blob/main/eslint.config.js) and a non-cyclic config.

fix(migrate-eslint): remove cyclic references of configs

---

.gitattributes
.github/CODEOWNERS
.github/labeler.yml
.github/renovate.json
netlify.toml

removes some website configurations unused in this repo

chore: remove some website leftovers

---

crates/biome_js_analyze/src/lint/suspicious/no_redundant_use_strict.rs

Closes https://github.com/biomejs/website/issues/52
Proof reading

docs: better explanation of the directive `"use strict"`

---

crates/biome_js_analyze/src/lint/nursery/use_explicit_length_check.rs

Avoid clone and allocations where possible.
CI must pass.

refactor(lint/useExplicitLengthCheck): avoid some allocations and clone

---

packages/@biomejs/js-api/package.json

There are some breaking changes in the WASM bundle, and the JS APIs needs an update.
Closes https://github.com/biomejs/biome/issues/2744
N/A

release: js-api

---

.github/workflows/release_knope.yml

The workflow didn't have a check version
Merge it and see if github likes it

ci: fix knope release workflow

---

CONTRIBUTING.md
GOVERNANCE.md

chore: move `@nissy-dev` to past maintainer

---

CHANGELOG.md
crates/biome_service/src/file_handlers/mod.rs

It's possible to use tsx inside of vue single file components. I'm not sure _why_ you would, but you can.
closes #2765
Added an additional test case.
```
cargo test -p biome_service
```

feat: support `lang="tsx"` for vue sfc

---

crates/biome_css_analyze/src/lint/nursery/no_unknown_media_feature_name.rs

This is blocking the CI inside the website

fix: missing codeblock

---

packages/@biomejs/biome/README.md

Add our new silver sponsor L2beat ❤️

refactor(readme): add l2beat silver sponsor

---

crates/biome_js_analyze/src/lint/style/use_filenaming_convention.rs

Address https://github.com/biomejs/biome/issues/2754#issuecomment-2100075190

docs(useFilenamingConvention): how to ignore files

---

.github/workflows/prepare_release.yml
knope.toml

The workflow was running a script that shouldn't have
Merge it, trigger it and see if it works

ci: fix workflow preapre relase

---

.changeset/new_clean_command.md

The new configuration of knope uses `cli` instead of `@biomejs/biome` to integrate all packages required to be published when releasing the CLI.
Merging this PR should update the automated release PR

ci: the CLI has now a different package name

---

xtask/bench/Cargo.toml

I forgot to add the group to `Cargo.toml`
The benchmark job should finish and show new entries

chore: add graphql_parser bench to `Cargo.toml`

---

crates/biome_js_analyze/src/lint/style/use_filenaming_convention.rs

Fix the [fail on the website CI](https://github.com/biomejs/website/actions/runs/9077370117/job/24942110226).

dcos(useFilenamingConvention): fix JSON

---

CHANGELOG.md
crates/biome_js_parser/src/syntax/typescript/types.rs
crates/biome_js_parser/test_data/inline/ok/ts_construct_signature_member.rast
crates/biome_js_parser/test_data/inline/ok/ts_construct_signature_member.ts

Fix #2825
I added a non regression test.

fix(js_parser): accept `const` type param on `new` signatures

---

crates/biome_cli/src/commands/mod.rs
crates/biome_cli/src/execute/mod.rs
crates/biome_cli/tests/snapshots/main_commands_lint/lint_help.snap

Address https://github.com/biomejs/biome/pull/2860#issuecomment-2114798270

docs(cli): add details about the `--rule` option

---

crates/biome_migrate/src/analyzers/nursery_rules.rs

This was missed before #2885 was merged.
Tests pass now.
```bash
cargo nextest run -p biome_migrate
```

fix(biome_migrate): add `FixKind` to `NurseryRules` migration

---

CHANGELOG.md

Added Changelogs
CI should pass

chore: added CHANGELOG about css lint rules

---

Cargo.lock

ci: update `time`, as it's causing some fails in CI

---

crates/biome_js_analyze/src/lint/suspicious/no_prototype_builtins.rs

Closes https://github.com/biomejs/website/pull/416
N/A

fix(no_prototyp_builtins): typo

---

CHANGELOG.md
crates/biome_lsp/tests/server.rs
crates/biome_service/src/file_handlers/javascript.rs

We were computing the code actions without using the overrides. I updated the code to use the correct function.
Closes https://github.com/biomejs/biome/issues/2782
Added a new test case in the LSP test suite

fix(workspace): pull code actions from overrides

---

CHANGELOG.md
crates/biome_js_analyze/src/lint/style/use_naming_convention.rs

As said in the title :)
CI must pass

docs(useNamingConvention): add a note about the availability of `conventions` option

---

CHANGELOG.md

Forgot to add a changelog entry for #2957

chore(changelog): add entry for pr #2957

---

crates/biome_js_analyze/src/lint/complexity/no_useless_constructor.rs

The link in this rule's docs was pointing to an old version of the typescript docs.

docs(noUselessConstructor): update outdated link to external docs

---

xtask/bench/README.md

I ran the benchmark on my local environment to check the performance of the CSS analyzer and added instruction for Analyzer and added some comments.
Run each command and checked that all benchmark works fine.

docs(bench): update docs of benchmark

---

crates/biome_cli/src/execute/migrate/eslint_any_rule_to_biome.rs
crates/biome_js_analyze/src/lint/nursery/use_throw_only_error.rs

Fix one of the source of `useThrowOnlyError`.
CI must pass.

refactor(useThrowOnlyError): fix sources

---

.github/workflows/repository_dispatch.yml

Cache the target folder to speed up `wasm-pack`
Merge to main

chore(ci): cache the target folder to speed up `wasm-pack`

---

.github/workflows/repository_dispatch.yml

Move the cache step around.
Merge to main.

chore(ci): tweak

---

.github/workflows/repository_dispatch.yml

chore(ci): install pnpm :(

---

crates/biome_cli/src/reporter/summary.rs
crates/biome_diagnostics/examples/lint.rs

Update CLI advices.
CI must pass.

refactor: use --write instead of --apply in CLI advices

---

.github/workflows/repository_dispatch.yml

This PR fixes the wasm pack cache restore and save steps. It also add a command to update the version of the wasm package to the commit hash.
Merge to main.

chore(ci): improve repository dispatch workflow

---

.github/workflows/repository_dispatch.yml

chore(ci): bump `actions/cache` version

---

.github/workflows/repository_dispatch.yml

https://github.com/biomejs/biome/actions/runs/9409935986/job/25920749638#step:11:14
Merge to main.

chore(ci): compact doesn't work, revert

---

.github/workflows/repository_dispatch.yml

I want to use this commit to test whether repository dispatch works.
Merge to main.

chore(ci): change semver `pr` to `rev`

---

justfile
xtask/rules_check/src/lib.rs

I addresses https://github.com/biomejs/biome/pull/3150#discussion_r1632842582
CI should pass

ci: add check for rules docs

---

CHANGELOG.md
crates/biome_js_analyze/src/lint/nursery/use_date_now.rs
crates/biome_js_analyze/tests/specs/nursery/useDateNow/valid.js
crates/biome_js_analyze/tests/specs/nursery/useDateNow/valid.js.snap

Fixes https://github.com/biomejs/biome/issues/3133
Added failing cases

fix(linter): fix useDateNow false positive when new Date has arguments

---

CONTRIBUTING.md

The core contributors agreed to assign them the title of Past maintainers due to long-lasting inactivity. 
N/A

chore: move maintainers to past maintainers

---

CONTRIBUTING.md

chore: move Sec-ant to core contributor

---

CONTRIBUTING.md

Add myself to the maintainers list. Thanks for having me. ❤️
TBD.

chore: add minht11 to the maintainers team

---

CHANGELOG.md
crates/biome_cli/src/execute/std_in.rs
crates/biome_cli/tests/commands/lint.rs
crates/biome_cli/tests/snapshots/main_cases_handle_astro_files/check_stdin_successfully.snap
crates/biome_cli/tests/snapshots/main_cases_handle_astro_files/check_stdin_write_successfully.snap
crates/biome_cli/tests/snapshots/main_cases_handle_astro_files/lint_stdin_successfully.snap
crates/biome_cli/tests/snapshots/main_cases_handle_svelte_files/check_stdin_successfully.snap
crates/biome_cli/tests/snapshots/main_cases_handle_svelte_files/check_stdin_write_successfully.snap
crates/biome_cli/tests/snapshots/main_cases_handle_svelte_files/lint_stdin_successfully.snap
crates/biome_cli/tests/snapshots/main_cases_handle_svelte_files/lint_stdin_write_successfully.snap
crates/biome_cli/tests/snapshots/main_cases_handle_vue_files/check_stdin_successfully.snap
crates/biome_cli/tests/snapshots/main_cases_handle_vue_files/check_stdin_write_successfully.snap
crates/biome_cli/tests/snapshots/main_cases_handle_vue_files/lint_stdin_successfully.snap
crates/biome_cli/tests/snapshots/main_cases_handle_vue_files/lint_stdin_write_successfully.snap
crates/biome_cli/tests/snapshots/main_commands_lint/check_stdin_shows_parse_diagnostics.snap

Closes https://github.com/biomejs/biome/issues/3201
Look how many snapshots we fixed!! :D 
We didn't inject the source code inside the diagnostics, that's why they were incorrect
Updated the current snapshots and added a new test case, taken from the bug report

fix(cli): inject source code in diagnostics printed in `stdin`

---

crates/biome_js_analyze/src/lint/complexity/use_literal_keys.rs

chore: fix typo in comments

---

CHANGELOG.md
crates/biome_service/src/file_handlers/css.rs

Fix CSS modules settings mapping

fix(css_parser): fix CSS modules settings mapping

---

CHANGELOG.md
crates/biome_css_parser/src/syntax/mod.rs
crates/biome_css_parser/src/syntax/property/color.rs
crates/biome_css_parser/src/syntax/property/mod.rs
crates/biome_css_parser/tests/css_test_suite/error/property/color_error.css
crates/biome_css_parser/tests/css_test_suite/error/property/color_error.css.snap
crates/biome_css_parser/tests/css_test_suite/error/property/color_error.css.snap.new
crates/biome_css_parser/tests/spec_test.rs

fix(css_parser): fix constant crashes when editing css files #3256

---

CHANGELOG.md
packages/@biomejs/biome/package.json
packages/@biomejs/js-api/package.json
packages/tailwindcss-config-analyzer/src/generate-tailwind-preset.ts

release: v1.8.3

---

crates/biome_js_analyze/src/lint/nursery/no_exported_imports.rs
crates/biome_js_analyze/tests/specs/nursery/noExportedImports/invalid.js.snap

I fixed a small typo in `no_exported_imports.rs`
Screenshot of playground:

chore: fix typo in diagnostic comment

---

crates/biome_analyze/src/context.rs

This PR adds a `get_service` method that allows the retrieval of a service without using queries such as `Aria`, `Manifest`, etc.
Of course, queries are still preferred because they allow the creation of better methods.
CI should pass

feat(analyzer): expose a method to retrieve a service on demand

---

packages/@biomejs/biome/README.hi.md
packages/@biomejs/biome/README.ja.md
packages/@biomejs/biome/README.md
packages/@biomejs/biome/README.pt-BR.md
packages/@biomejs/biome/README.zh-CN.md

I completely missed the change. We don't like lists, even though they are easier to edit, we prefer this layout, consider that it won't change often.

chore: revert some change in the READMEs

---

CHANGELOG.md

This PR closes #1724, as I think editorconfig support is complete.
closes #1724
CI should pass

chore: add editorconfig support to changelog

---

crates/biome_cli/tests/cases/graphql.rs
crates/biome_cli/tests/snapshots/main_cases_graphql/lint_single_rule.snap

Update a snapshot changed by %3350
CI must pass.

ci: update GraphQL cli snapshot

---

xtask/codegen/src/generate_nodes.rs

Just a minor change to call the function for this instead of having the `match` inlined
CI passes

refactor(codegen): call kind src function instead

---

crates/biome_js_semantic/src/semantic_model/builder.rs

Remove dead code
CI must pass.

refactor(js_semantic): remove dead code

---

.github/workflows/release_cli.yml
.github/workflows/release_knope.yml

`macos-11` is deprecated 
Merge it and trigger a release

ci: update macos image

---

xtask/codegen/src/lib.rs

Another minor change to make adding new languages a little less tedious.

fix(codegen): create output directory if it doesn't exist

---

crates/biome_diagnostics_categories/src/categories.rs

Fixed a mistake in the noEvolvingTypes url

fix: fix typo in URL for noEvolvingTypes rule in diagnostics categories

---

crates/biome_js_semantic/src/events.rs
crates/biome_js_semantic/src/semantic_model/builder.rs
crates/biome_js_semantic/src/semantic_model/model.rs

Update outdated comments and docs.

docs(js_semantic): update docs and comments

---

CHANGELOG.md

Update `CHANGELOG.md` with `noIrregularWhitespace` rule.

chore(changelog): add changelog entry about noIrregularWhitespace rule

---

crates/biome_css_parser/src/syntax/at_rule/media.rs
crates/biome_css_parser/tests/css_test_suite/error/at_rule/at_rule_media_error.css
crates/biome_css_parser/tests/css_test_suite/error/at_rule/at_rule_media_error.css.snap

Fix https://github.com/biomejs/biome/issues/3284 https://github.com/biomejs/biome/issues/3432
I'm not sure if it's a good idea to have '$' as part of an identifier, but the fix doesn't get the parser stuck.
`cargo test`

fix(css_parser): fix Parser is no longer progressing #3284

---

packages/@biomejs/biome/README.md

chore: add new bronze sponsor

---

CHANGELOG.md
crates/biome_js_analyze/src/lint/suspicious/no_extra_non_null_assertion.rs
crates/biome_js_analyze/tests/specs/suspicious/noExtraNonNullAssertion/valid.ts
crates/biome_js_analyze/tests/specs/suspicious/noExtraNonNullAssertion/valid.ts.snap

fix(noExtraNonNullAssertion): don't report non-null assertion enclosed in parens

---

.npmrc
package.json

pnpm/pnpm#6300 got fixed in pnpm 9.5.0, no need to use the `.npmrc` workaround anymore
it should...install deps correctly i guess?

chore: update pnpm and remove workaround

---

CHANGELOG.md

docs(changelog): document fix for `lint --write --only`

---

packages/@biomejs/biome/README.md

This PR adds our new Silver Sponsor

chore: add silver sponsor

---

crates/biome_grit_patterns/src/grit_code_snippet.rs

Tiny PR to resolve a few left-over `todo!()`s in `grit_code_snippet.rs`
Not covered yet.

fix(grit): add code snippet bindings

---

crates/biome_grit_patterns/src/grit_resolved_pattern.rs

Small PR to resolve the remaining `todo!()s` that were left in `grit_resolved_pattern.rs`.
Some are simply replaced with `bail!()`, while `fn text()` has ported implementations from Grit.
Not covered yet.

fix(grit): resolve `todo!`()s in `grit_resolved_pattern.rs`

---

crates/biome_analyze/CONTRIBUTING.md

I found the empty bullet on [biome_analyze/CONTRIBUTING.md](https://github.com/biomejs/biome/blob/main/crates/biome_analyze/CONTRIBUTING.md) duriing the review and removed it.
Checked the [Makrdown preview](https://code.visualstudio.com/docs/languages/markdown#_markdown-preview) on VSCode.

docs: remove the emtpty bullet on `biome_analyze/CONTRIBUTING.md`

---

crates/biome_css_semantic/src/events.rs
crates/biome_css_semantic/src/semantic_model/mod.rs

- Added comments
- Changed to create rule context for @\media and nested selectors
CI should pass

feat(css_semantic): handle @media and nested selectors correctly

---

xtask/codegen/src/generate_new_analyzer_rule.rs

chore: fix the rule template

---

crates/biome_analyze/src/registry.rs

I found a minor typo in a message in crates/biome_analyze/src/registry.rs and fixed it.

chore: fix typo in registry

---

crates/biome_js_analyze/src/lint/nursery/no_irregular_whitespace.rs

The rule was emitting a parsing diagnostic, which is incorrect.
I will verify this in the website repository

docs: correct diagnostic for rule

---

crates/biome_analyze/CONTRIBUTING.md
packages/@biomejs/biome/README.md

Info about the options section was missing in this contribution guide to explain how to document a rule.
Also fixed a dead link on readme. (thx [lychee](https://github.com/lycheeverse/lychee))
No change

chore: document options section in analyze contributions guide

---

.github/ISSUE_TEMPLATE/01_formatter_bug.yml
.github/ISSUE_TEMPLATE/02_lint_bug.yml
.github/ISSUE_TEMPLATE/03_bug.yml

chore: update issue templates with reproduction

---

crates/biome_js_analyze/src/lint/complexity/no_useless_catch.rs
crates/biome_js_analyze/src/services/control_flow/nodes/try_catch.rs
crates/biome_js_analyze/tests/specs/complexity/noUselessCatch/invalid.js
crates/biome_js_analyze/tests/specs/complexity/noUselessCatch/invalid.js.snap
crates/biome_js_syntax/src/stmt_ext.rs

Fix the bug found in the Ecosystem CI workflow run: https://github.com/biomejs/ecosystem-ci/actions/runs/10456856050/job/28955515973
I took the opportunity of improving the implementation.
We no longer query `JsModule`.
Note> Please don't merge this PR.
I would like to trigger the Ecosystem CI using a comment. This requires to merge https://github.com/biomejs/ecosystem-ci/pull/3.

fix(noUselessCatch): fix code action panics

---

crates/biome_console/src/write/html.rs

Follow up for https://github.com/biomejs/biome/pull/3701
The PR introduced some regressions, which are fixed here.

fix(console): regression for #3701

---

crates/biome_console/src/write/html.rs

fix: escape backslash when printing HTML in mdx

---

crates/biome_grit_patterns/src/grit_binding.rs
crates/biome_grit_patterns/src/grit_node.rs
crates/biome_grit_patterns/src/pattern_compiler.rs
crates/biome_grit_patterns/src/pattern_compiler/as_compiler.rs
crates/biome_grit_patterns/tests/specs/ts/functionToArrow.grit
crates/biome_grit_patterns/tests/specs/ts/functionToArrow.snap
crates/biome_grit_patterns/tests/specs/ts/functionToArrow.ts

Adds support for the `as` keyword in GritQL.
Test added.

feat(grit): support `as` keyword

---

CHANGELOG.md
crates/biome_js_analyze/src/lint/nursery/no_undeclared_dependencies.rs
crates/biome_js_analyze/src/services/manifest.rs
crates/biome_js_analyze/tests/specs/nursery/noUndeclaredDependencies/valid.js
crates/biome_js_analyze/tests/specs/nursery/noUndeclaredDependencies/valid.js.snap
crates/biome_js_analyze/tests/specs/nursery/noUndeclaredDependencies/valid.package.json

Support [self package imports](https://nodejs.org/api/packages.html#self-referencing-a-package-using-its-name).

refactor(noUndeclaredDependencies): support self package imports

---

crates/biome_js_analyze/src/lint/suspicious/no_double_equals.rs

This PR fixes a minor typo in this [file](https://github.com/biomejs/biome/blob/main/crates/biome_js_analyze/src/lint/suspicious/no_double_equals.rs).

fix(docs): typo in `no_double_equals.rs`

---

CHANGELOG.md
crates/biome_service/src/file_handlers/json.rs

Closes https://github.com/biomejs/biome/issues/3696
I tested it using the user's reproduction, locally

fix(core): enforce parsing options for `biome.jsonc`

---

CHANGELOG.md
crates/biome_cli/tests/cases/overrides_formatter.rs
crates/biome_cli/tests/commands/format.rs
crates/biome_cli/tests/snapshots/main_cases_handle_css_files/should_not_format_files_by_default.snap
crates/biome_cli/tests/snapshots/main_cases_handle_css_files/should_not_lint_files_by_default.snap
crates/biome_cli/tests/snapshots/main_cases_overrides_formatter/does_include_file_with_different_languages.snap
crates/biome_cli/tests/snapshots/main_commands_format/should_apply_different_formatting.snap
crates/biome_cli/tests/snapshots/main_commands_rage/with_formatter_configuration.snap
crates/biome_cli/tests/snapshots/main_commands_rage/with_linter_configuration.snap
crates/biome_configuration/src/css.rs
crates/biome_service/src/file_handlers/css.rs
crates/biome_service/src/settings.rs

This PR enables CSS formatting and linting by default.
I updated the snapshots and added a changelog line

feat(core): enable CSS linting and formatting by default

---

crates/biome_lsp/src/handlers/text_document.rs
crates/biome_lsp/src/session.rs

Closes https://github.com/biomejs/biome/issues/3169
I tested locally using the info provided in the issue. The LSP server doesn't hang anymore

fix(lsp): update diagnostics only for supported files

---

crates/biome_js_parser/src/syntax/expr.rs

Part of https://github.com/biomejs/biome/issues/3157
Adds `enumflags2` to `biome_js_parser` `ExpressionContextFlag`

refactor(biome_js_parser/syntax): use enumflags2 for `ExpressionContextFlag`

---

crates/biome_cli/src/cli_options.rs
crates/biome_cli/tests/snapshots/main_commands_check/check_help.snap
crates/biome_cli/tests/snapshots/main_commands_ci/ci_help.snap
crates/biome_cli/tests/snapshots/main_commands_format/format_help.snap
crates/biome_cli/tests/snapshots/main_commands_lint/lint_help.snap
crates/biome_cli/tests/snapshots/main_commands_migrate/migrate_help.snap
crates/biome_cli/tests/snapshots/main_commands_rage/rage_help.snap

docs(cli): update `--verbose` doc

---

xtask/codegen/src/generate_configuration.rs
xtask/codegen/src/generate_license.rs

Run `cargo clippy --all-targets --all-features -- -D warning` on main branch and fixed errors.

fix: clippy error with `cargo clippy --all-targets --all-features -- -D warning` command

---

crates/biome_deserialize/README.md

After https://github.com/biomejs/biome/pull/2310 code changed a bit, this PR updates readme example.

docs(biome_deserialize): update example `is_type()` with `visitable_type()`

---

crates/biome_html_parser/tests/html_specs/ok/attributes.html.snap
crates/biome_html_parser/tests/html_specs/ok/comment.html
crates/biome_html_parser/tests/html_specs/ok/comment.html.snap
crates/biome_html_parser/tests/html_specs/ok/element.html.snap
crates/biome_html_parser/tests/html_specs/ok/element_list.html.snap
crates/biome_html_parser/tests/html_specs/ok/ok.html.snap
crates/biome_html_parser/tests/html_specs/ok/ok2.html.snap
crates/biome_html_parser/tests/spec_test.rs
crates/biome_html_parser/tests/spec_tests.rs

This is a small PR that adds a test and fixes the test snapshots for the html parser marking the input as `css` blocks and not `html` blocks.
CI passes.

test(parser/html): add a test for parsing a comment and fix parser snapshots marked with wrong language

---

crates/biome_css_analyze/src/lint/nursery/no_invalid_grid_areas.rs
crates/biome_css_analyze/tests/specs/nursery/noInvalidGridAreas/valid.css
crates/biome_css_analyze/tests/specs/nursery/noInvalidGridAreas/valid.css.snap

fix #3827 
added tests and CI should pass

fix(linter): only emit diagnostics for grid area properties

---

crates/biome_aria/src/roles.rs
crates/biome_js_analyze/src/lint/a11y/no_interactive_element_to_noninteractive_role.rs
crates/biome_js_analyze/src/lint/nursery/use_semantic_elements.rs
crates/biome_js_analyze/tests/specs/nursery/useSemanticElements/valid.jsx
crates/biome_js_analyze/tests/specs/nursery/useSemanticElements/valid.jsx.snap

fix(linter): allow SVG elements with role="img"

---

crates/biome_cli/src/execute/process_file.rs
crates/biome_cli/src/execute/process_file/search.rs
crates/biome_cli/src/execute/traverse.rs
crates/biome_cli/src/reporter/terminal.rs

Small fix to show the number of results instead of number of files with results.
Tested manually.

fix(search): fix num results

---

crates/biome_analyze/CONTRIBUTING.md

I've noticed this feedback on a few new rules recently, and I figured it would good to start documenting them.

docs(analyze): add section for common mistakes

---

crates/biome_css_formatter/src/utils/component_value_list.rs
crates/biome_css_formatter/tests/specs/css/value_one_per_line.css
crates/biome_css_formatter/tests/specs/css/value_one_per_line.css.snap
crates/biome_css_formatter/tests/specs/prettier/css/url/url.css.snap

fix(format/css): preserve expanded comma separated values

---

CHANGELOG.md
crates/biome_css_analyze/src/lint/nursery/no_unknown_pseudo_class.rs
crates/biome_js_analyze/src/lint/nursery/no_substr.rs
crates/biome_js_analyze/src/lint/nursery/use_consistent_curly_braces.rs

- Add some missing Changelog entries
- Order existing entries
- Fix version field of some rules that are already released.
CI must pass.

refactor(changelog): add missing entries, order existing ones

---

CONTRIBUTING.md

chore: add vohoanglong0107 as maintainer

---

crates/biome_service/src/file_handlers/mod.rs

In #3839, there isn't enough information in the logs to triage the bug, if its on our side. I think these additional logs should be enough to fix that.
See: #3839

chore: add additional debug logs for #3839

---

.github/labeler.yml

This updates the auto labeler config to be more comprehensive when labeling things with `A-Linter`, `A-Formatter`, and `A-Parser`.
Tested the globs with this tool: http://pthrasher.github.io/minimatch-test/

chore(ci): update pr labeler globs to require less maintainance

---

crates/biome_service/src/file_handlers/mod.rs
crates/biome_service/src/workspace/server.rs

chore: add more logs for #3839

---

crates/biome_js_analyze/src/lint/style/use_filenaming_convention.rs

Fix the snippet code on how to ignore the file on `useFilenamingConvention` rule

docs: update snippet ignore file on `useFilenamingConvention` rule

---

.github/workflows/bench_cli.yml
.github/workflows/benchmark.yml
.github/workflows/main.yml
.github/workflows/parser_conformance.yml
.github/workflows/pull_request.yml
.github/workflows/release_knope.yml

Installing the toolchain can take a long time in macOS because of this issue : https://github.com/moonrepo/setup-rust/issues/22
ex workflows where this happens: 
https://github.com/biomejs/biome/actions/runs/10872714495/job/30168050791
Should work.

chore(ci): add gh token for setup-rust

---

CHANGELOG.md
crates/biome_cli/src/execute/process_file/format.rs
crates/biome_cli/src/execute/traverse.rs
crates/biome_cli/src/reporter/terminal.rs
crates/biome_cli/tests/commands/check.rs
crates/biome_cli/tests/snapshots/main_commands_check/print_verbose_write.snap

Closes https://github.com/biomejs/biome/issues/3917

fix(cli): use correct list of evaluated paths

---

crates/biome_html_formatter/src/html/auxiliary/directive.rs

This PR fixes doctype directive formatting so that it matches prettier.
> [!NOTE]
> This PR probably doesn't work without:
> - #3962 
Added tests.

fix(format/html): fix doctype formatting

---

CHANGELOG.md

Added new GritQL changes to the CHANGELOG.
N/A

chore: add Grit updates to CHANGELOG

---

CHANGELOG.md
packages/@biomejs/biome/package.json

Plan to release this patch for tomorrow
CI should pass

release: v1.9.2

---

packages/@biomejs/biome/README.md

- Uses Polar shield badge, because the backlog doesn't reflect the current available bounties
- Changes some badges from green to the colour of the Biome logo
[Rendered](https://github.com/biomejs/biome/blob/docs/readme-badge/packages/@biomejs/biome/README.md)

chore(readme): use polar shield

---

Cargo.lock
crates/biome_yaml_syntax/Cargo.toml

chore: fix udeps failure

---

crates/biome_service/src/file_handlers/html.rs

This implements the debug functions for HTML so they show up in the playground.
Tested manually via local playground.

feat(html): implement debug features for html

---

.github/labeler.yml

Updates the auto labeler job to apply `L-Grit` to PRs that change those crates. I've already created the label.

chore(ci): update labeler to include grit tag

---

crates/biome_js_analyze/src/lint/complexity/no_useless_fragments.rs
crates/biome_js_analyze/tests/specs/complexity/noUselessFragments/issue_3926.jsx
crates/biome_js_analyze/tests/specs/complexity/noUselessFragments/issue_3926.jsx.snap

fix(linter): noUselessFragments fix creates invalid CST

---

CHANGELOG.md
crates/biome_js_analyze/src/lint/correctness/no_unused_function_parameters.rs
crates/biome_js_analyze/tests/specs/correctness/noUnusedFunctionParameters/invalid.js
crates/biome_js_analyze/tests/specs/correctness/noUnusedFunctionParameters/invalid.js.snap
crates/biome_js_analyze/tests/specs/correctness/noUnusedFunctionParameters/valid.js
crates/biome_js_analyze/tests/specs/correctness/noUnusedFunctionParameters/valid.js.snap

fix(noUnusedFunctionParameters): ignore params in obj pattern with a rest param

---

crates/biome_js_analyze/src/lint/a11y/use_semantic_elements.rs

I forgot to update the examples in #4078

fix(useSemanticElements): examples

---

CHANGELOG.md
crates/biome_cli/src/execute/migrate/eslint_any_rule_to_biome.rs
crates/biome_configuration/src/analyzer/linter/rules.rs
crates/biome_diagnostics_categories/src/categories.rs
crates/biome_js_analyze/src/lint/nursery.rs
crates/biome_js_analyze/src/lint/nursery/no_template_curly_in_string.rs
crates/biome_js_analyze/src/options.rs
crates/biome_js_analyze/tests/specs/nursery/noTemplateCurlyInString/invalid.js
crates/biome_js_analyze/tests/specs/nursery/noTemplateCurlyInString/invalid.js.snap
crates/biome_js_analyze/tests/specs/nursery/noTemplateCurlyInString/valid.js
crates/biome_js_analyze/tests/specs/nursery/noTemplateCurlyInString/valid.js.snap
packages/@biomejs/backend-jsonrpc/src/workspace.ts
packages/@biomejs/biome/configuration_schema.json

feat(linter): implement noTemplateCurlyInString

---

CHANGELOG.md
crates/biome_js_parser/src/syntax/class.rs
crates/biome_js_parser/src/syntax/typescript.rs
crates/biome_js_parser/src/syntax/typescript/statement.rs
crates/biome_js_parser/src/syntax/typescript/types.rs
crates/biome_js_parser/test_data/inline/err/interface_cannot_be_reserved_world.rast
crates/biome_js_parser/test_data/inline/err/interface_cannot_be_reserved_world.ts
crates/biome_js_parser/test_data/inline/err/ts_class_name_reserved_as_type.rast
crates/biome_js_parser/test_data/inline/err/ts_class_name_reserved_as_type.ts
crates/biome_js_parser/test_data/inline/err/ts_type_alias_cannot_be_reserved_word.rast
crates/biome_js_parser/test_data/inline/err/ts_type_alias_cannot_be_reserved_word.ts

feat(biome_js_parser): forbid undefined as type name

---

CHANGELOG.md
crates/biome_cli/src/commands/rage.rs
crates/biome_configuration/src/graphql.rs
crates/biome_configuration/src/json.rs
crates/biome_service/src/file_handlers/css.rs
crates/biome_service/src/settings.rs
crates/biome_service/src/workspace.rs

This was a though one to find, but I eventually fixed it.
I manually tested the fix on VS Code and Zed

fix(lsp): correctly enable CSS on LSP

---

CHANGELOG.md
crates/biome_cli/src/execute/mod.rs
crates/biome_cli/src/execute/std_in.rs
crates/biome_cli/tests/commands/check.rs
crates/biome_cli/tests/commands/lint.rs
crates/biome_cli/tests/snapshots/main_commands_check/check_stdin_returns_text_if_content_is_not_changed.snap
crates/biome_cli/tests/snapshots/main_commands_lint/check_stdin_shows_parse_diagnostics.snap

Closes https://github.com/biomejs/biome/issues/4102
Some snapshots were incorrect, they are now updated

fix(cli): don't error in stdin, with `--write`

---

CHANGELOG.md
packages/@biomejs/js-api/src/index.ts
packages/@biomejs/wasm-nodejs/package.json
packages/aria-data/generate-aria-data.js

Closes https://github.com/biomejs/biome/issues/3881
CI should pass

fix(js-api): update code

---

.github/workflows/benchmark.yml

Updates the codspeed action
CI should pass

ci: update codspeed action

---

.github/workflows/release_js_api.yml
pnpm-lock.yaml
pnpm-workspace.yaml

The `@biomejs/*` packages weren't inside the pnpm workspace anymore, so the CI was failing.
I put them back, and they should work now.
CI should pass

ci: fix js API release workflow

---

packages/@biomejs/js-api/package.json
packages/@biomejs/js-api/src/index.ts

This PR should fix some other JS API issues, and trigger a new release
CI should pass

fix(js-api): pass correct information

---

packages/@biomejs/backend-jsonrpc/tests/workspace.test.mjs

A test is updated to use the most up to date change of the workspace
CI should pass

test: update workspace test

---

packages/@biomejs/js-api/tests/__snapshots__/printDiagnostics.test.ts.snap

Update of snapshots 
CI should pass

test: update snapshots for js-api

---

.changeset/remove_biome_log_dir.md
crates/biome_cli/src/commands/daemon.rs
crates/biome_cli/src/lib.rs
crates/biome_cli/tests/commands/rage.rs

Closes https://github.com/biomejs/biome/issues/4288
The CI should pass

feat: remove environment variable `BIOME_LOG_DIR`

---

CHANGELOG.md
crates/biome_css_analyze/src/lint/nursery/no_duplicate_custom_properties.rs
crates/biome_css_analyze/tests/specs/nursery/noDuplicateCustomProperties/invalid.css.snap
crates/biome_css_analyze/tests/specs/nursery/noDuplicateCustomProperties/valid.css
crates/biome_css_analyze/tests/specs/nursery/noDuplicateCustomProperties/valid.css.snap

- Ignore non-custom properties
- Improve the error message
- Add more test cases
CI should pass

fix(linter): fix false-positve and improve the error of noDuplicateCustomProperties

---

crates/biome_configuration/src/javascript/mod.rs

refactor: remove dead code

---

CHANGELOG.md

chore: remove useless conflict on CHANGELOG

---

crates/biome_diagnostics/src/serde.rs
packages/@biomejs/js-api/tests/__snapshots__/formatContent.test.ts.snap

Fixes some failures in the CI for `next
I tested it locally

chore: update code and diagnostics

---

Cargo.lock
crates/biome_aria_metadata/Cargo.toml
crates/biome_console/Cargo.toml
crates/biome_diagnostics/Cargo.toml
crates/biome_lsp/Cargo.toml
crates/biome_wasm/Cargo.toml
xtask/codegen/Cargo.toml
xtask/rules_check/Cargo.toml

Extract patch updates from #4406
CI must pass.

chore(deps): patch updates

---

crates/biome_deserialize/src/json.rs
crates/biome_js_parser/tests/js_test_suite/error/import_assertion_err.js.snap
crates/biome_js_parser/tests/js_test_suite/error/import_attribute_err.js.snap
crates/biome_js_parser/tests/js_test_suite/ok/export_from_clause.js.snap
crates/biome_js_parser/tests/js_test_suite/ok/export_named_from_clause.js.snap
crates/biome_lsp/src/capabilities.rs

Rebasing `next` on `main` leads to errors.
This PR fixes them.
CI must pass.

ci: fix errors and update snapshots

---

packages/@biomejs/biome/README.hi.md
packages/@biomejs/biome/README.ja.md
packages/@biomejs/biome/README.kr.md
packages/@biomejs/biome/README.md
packages/@biomejs/biome/README.pt-BR.md
packages/@biomejs/biome/README.zh-CN.md
packages/@biomejs/biome/README.zh-TW.md

- Fix an inaccurate translation.
- Use more natural translation wording.
- Fix broken links.
- Remove the removed content from `README.md`.
- Fixe Markdown syntax that was not rendering correctly.

docs: update `README.kr.md`

---

CHANGELOG.md
crates/biome_js_analyze/src/lint/complexity/use_arrow_function.rs
crates/biome_js_analyze/tests/specs/complexity/useArrowFunction/invalid.ts
crates/biome_js_analyze/tests/specs/complexity/useArrowFunction/invalid.ts.snap

Fix https://github.com/biomejs/biome/issues/4530

fix(useArrowFunction): preserve directives in the code fix

---

packages/@biomejs/biome/README.ru.md

I forgot to add the link, my apologies

fix: added a missing link to the English README in the Russian translation

---

packages/@biomejs/biome/README.hi.md
packages/@biomejs/biome/README.ja.md
packages/@biomejs/biome/README.kr.md
packages/@biomejs/biome/README.zh-CN.md

fix: fix translation links

---

crates/biome_js_analyze/src/utils/restricted_glob.rs

Add `matches_directory_with_exceptions` for matching a path against a list of globs with exceptions.
This will allow us to implement a file crawler.
The current implementation has the same limitations as Git: only directly in exception are doesn't match.
Encapsulating this in a method, will allow us to improve its implementation if one day we switch to another glob library that supports prefix matching.
I added doc tests.
CI must pass.

refactor(retsricted_glob): add `matches_directory_with_exceptions`

---

CONTRIBUTING.md

Add myself to biome maintainers team, thank you~

chore: add zoomdong to member list

---

crates/biome_glob/src/lib.rs

We now reject cases where `**` is not enclosed by `/` or the start/end of the glob.
`globset` accept these cases and assume it is a single `*`.
Also, multiple succeeding globstars are rejected because there are useless, e.g. `**/**` is now invalid.
I added tests and improved test coverage.

refactor(glob): stricter validation

---

CHANGELOG.md
crates/biome_js_analyze/src/lint/a11y/no_label_without_control.rs
crates/biome_js_analyze/tests/specs/a11y/noLabelWithoutControl/valid.jsx
crates/biome_js_analyze/tests/specs/a11y/noLabelWithoutControl/valid.jsx.snap

Closes #4511 
Add snapshot tests

fix(noLabelWithoutControl): add button tags in default input components

---

crates/biome_css_formatter/src/css/lists/selector_list.rs
crates/biome_css_formatter/src/css/selectors/complex_selector.rs

follow the comments https://github.com/biomejs/biome/pull/4614#pullrequestreview-2470945783 here.
Add some comments for the code.
Don't need test

chore: add some comments for selector list formatted

---

CHANGELOG.md
crates/biome_js_analyze/src/lint/nursery/use_sorted_classes/sort.rs
crates/biome_js_analyze/tests/specs/nursery/useSortedClasses/issue_3394.jsx
crates/biome_js_analyze/tests/specs/nursery/useSortedClasses/issue_3394.jsx.snap

Supplementary test case，and fixed
```tsx
<>
<div class={`${variable}-bar ${variable}`}></div>
<div class={`${variable}-bar    ${variable}`}></div>
</>
```
Expected behavior
```tsx
<>
<div class={`${variable}-bar ${variable}`}></div>
<div class={`${variable}-bar ${variable}`}></div>
</>
```
What happens
```tsx
<>
<div class={`${variable}-bar${variable}`}></div>
<div class={`${variable}-bar${variable}`}></div>
</>
```

fix(linter): useSortedClasses false positive #3394

---

.changeset/add_the_new_rule_nounwantedpolyfillio.md
CHANGELOG.md
crates/biome_cli/src/execute/migrate/eslint_any_rule_to_biome.rs
crates/biome_configuration/src/analyzer/linter/rules.rs
crates/biome_diagnostics_categories/src/categories.rs
crates/biome_js_analyze/src/lib.rs
crates/biome_js_analyze/src/lint/nursery.rs
crates/biome_js_analyze/src/lint/nursery/no_unwanted_polyfillio.rs
crates/biome_js_analyze/src/nextjs.rs
crates/biome_js_analyze/src/options.rs
crates/biome_js_analyze/tests/specs/nursery/noUnwantedPolyfillio/invalid-next-script.jsx
crates/biome_js_analyze/tests/specs/nursery/noUnwantedPolyfillio/invalid-next-script.jsx.snap
crates/biome_js_analyze/tests/specs/nursery/noUnwantedPolyfillio/invalid.jsx
crates/biome_js_analyze/tests/specs/nursery/noUnwantedPolyfillio/invalid.jsx.snap
crates/biome_js_analyze/tests/specs/nursery/noUnwantedPolyfillio/valid.jsx
crates/biome_js_analyze/tests/specs/nursery/noUnwantedPolyfillio/valid.jsx.snap
packages/@biomejs/backend-jsonrpc/src/workspace.ts
packages/@biomejs/biome/configuration_schema.json

Implement no-unwanted-polyfillio from eslint-plugin-next.
- rule doc: https://nextjs.org/docs/messages/no-unwanted-polyfillio
- rule source: https://github.com/vercel/next.js/blob/canary/packages/eslint-plugin-next/src/rules/no-unwanted-polyfillio.ts
Add snapshot tests

feat(lint): add `noUnwantedPolyfillio`

---

.changeset/tsconfigjson_files_will_now_be_treated_the_same_as_tsconfigjson_files.md
crates/biome_json_syntax/src/file_source.rs

fix(json): treat `tsconfig.*.json` files as well known, allow comments and trailing comments by default

---

crates/biome_js_analyze/src/lint/nursery/no_restricted_imports.rs

The main branch is not currently passing CI. This repo gets main up to code again.
This branch should be validated by confirming:
- It only contains minor formatting changes.
- Its CI is passing.

ci: fix formatting 

---

crates/biome_js_analyze/src/lint/correctness/no_unused_variables.rs

Closes https://github.com/biomejs/biome/issues/4554

docs: redact incorrect docs

---

crates/biome_html_formatter/src/html/auxiliary/element.rs

Follow up of https://github.com/biomejs/biome/pull/4818/files#r1901914743
cc @dyc3 
CI should pass

refactor(formatter): don't allocate strings, and use try operator early

---

justfile

update task comments in justfile
N/A

chore: improve task comments for creating new lint rules

---

.changeset/fix_fragament_4751.md
crates/biome_js_analyze/src/lint/complexity/no_useless_fragments.rs
crates/biome_js_analyze/tests/quick_test.rs
crates/biome_js_analyze/tests/specs/complexity/noUselessFragments/issue_4751.jsx
crates/biome_js_analyze/tests/specs/complexity/noUselessFragments/issue_4751.jsx.snap

closes: #4751 
The following case:
```jsx
<section>
<>
<div />
<div />
</>
</section>;
showFullName ? <>{fullName}</> : <>{firstName}</>;
```
It will be reported by biome linter.
I add test case at `biome_js_analyzer`.

fix(noUselessFragments): check Fragment when it under JSX Element or Condition Expr

---

.changeset/remove_support_for_max_line_length_from_editorconfig_as_it_isnt_part_of_the_official_spec_anymore_.md
crates/biome_cli/tests/cases/editorconfig.rs
crates/biome_cli/tests/snapshots/main_cases_editorconfig/should_have_biome_override_editorconfig.snap
crates/biome_cli/tests/snapshots/main_cases_editorconfig/should_have_cli_override_editorconfig.snap
crates/biome_cli/tests/snapshots/main_cases_editorconfig/should_use_editorconfig.snap
crates/biome_cli/tests/snapshots/main_cases_editorconfig/should_use_editorconfig_check.snap
crates/biome_cli/tests/snapshots/main_cases_editorconfig/should_use_editorconfig_check_enabled_from_biome_conf.snap
crates/biome_cli/tests/snapshots/main_cases_editorconfig/should_use_editorconfig_ci.snap
crates/biome_cli/tests/snapshots/main_cases_editorconfig/should_use_editorconfig_ci_enabled_from_biome_conf.snap
crates/biome_cli/tests/snapshots/main_cases_editorconfig/should_use_editorconfig_enabled_from_biome_conf.snap
crates/biome_configuration/src/editorconfig.rs
crates/biome_diagnostics/src/display.rs

Closes https://github.com/biomejs/biome/issues/4892
I updated the tests to use new properties from the editorconfig

refactor(editorconfig): remove support for `max_line_length`

---

.github/ISSUE_TEMPLATE/06_commercial_request.yml

Add an issue type for commercial support requests.
See also: https://github.com/biomejs/website/pull/1666
N/A

chore: commercial support request issue template

---

.github/ISSUE_TEMPLATE/01_formatter_bug.yml
.github/ISSUE_TEMPLATE/02_lint_bug.yml
.github/ISSUE_TEMPLATE/04_task.yml
.github/ISSUE_TEMPLATE/05_umbrella.yml
.github/ISSUE_TEMPLATE/06_commercial_request.yml

chore: use issue types in templates

---

crates/biome_cli/src/service/unix.rs
crates/biome_css_analyze/src/suppression_action.rs
crates/biome_css_formatter/src/utils/string_utils.rs
crates/biome_formatter_test/src/check_reformat.rs
crates/biome_graphql_analyze/src/suppression_action.rs
crates/biome_graphql_formatter/tests/quick_test.rs
crates/biome_grit_patterns/src/grit_resolved_pattern.rs
crates/biome_js_analyze/src/assists/source/organize_imports/util.rs
crates/biome_js_analyze/src/lint/nursery/use_at_index.rs
crates/biome_js_analyze/src/lint/nursery/use_trim_start_end.rs
crates/biome_js_formatter/src/utils/string_utils.rs

Closes #4913
This change simplifies some statements to improve code readability and maintainability.
CI

refactor: replace some lines for readability

---

GOVERNANCE.md

This PR adds the following changes to the Governance document:
- adds more perks to each role that weren't listed before 
- a new header that explains how governance changes (like this one) are accepted
- adds a better table of contents at the top of the file
Proof read and wait for the 50% approval from core contributors

chore: add governance changes approval

---

crates/biome_analyze/CONTRIBUTING.md

Updated old link with new one.

chore: update Just install link

---

crates/biome_migrate/src/analyzers/deleted_rules.rs
crates/biome_migrate/src/analyzers/includes.rs
crates/biome_migrate/src/analyzers/no_var.rs
crates/biome_migrate/src/analyzers/organize_imports.rs
crates/biome_migrate/src/analyzers/style_rules.rs

This PR removes from the migrate rules the version check, as it's not needed. It was added due to how tests were running, but that was fixed in the test suite.
CI should pass. I checked locally, and all tests still pass.

chore(migrate): remove version check

---

justfile

update `gen-tw` command description, it can now run without bun.
related commit: dff45a4fb51f574253f3092c7553fc01a2016d9f
N/A

chore: `gen-tw` description

---

xtask/codegen/src/generate_nodes.rs
xtask/codegen/src/generate_syntax_kinds.rs

This fixes the codegen that is currently broken on `next`. It also has a small refactor to make changes to codegen less error prone.
Ran codegen, CI codegen job should pass.

fix(css): fix css codegen

---

crates/biome_configuration/src/analyzer/assist/actions.rs
crates/biome_css_analyze/src/registry.rs
packages/@biomejs/backend-jsonrpc/src/workspace.ts
packages/@biomejs/biome/configuration_schema.json
xtask/codegen/src/generate_analyzer.rs

This fixes the CSS assist tests not running, and ultimately the failing CI.
CI should pass now.

fix(css): fix css lint/assist registry codegen

---

.github/workflows/repository_dispatch.yml

Adds workaround for https://github.com/actions/setup-node/issues/1222
Merge and see if the action works

ci: workaround for dispatch action

---

crates/biome_js_formatter/src/comments.rs
crates/biome_js_formatter/tests/quick_test.rs
crates/biome_js_formatter/tests/specs/js/module/array/holes_comments.js
crates/biome_js_formatter/tests/specs/js/module/array/holes_comments.js.snap

Closes https://github.com/biomejs/biome/issues/4695

fix(formatter): handling of comments in js holes with newlines

---

.changeset/wet-hornets-sparkle.md
crates/biome_configuration/src/editorconfig.rs

fix(editorconfig): fix `insert_final_newline` being unable to parse value `unset`

---

crates/biome_js_formatter/tests/specs/js/module/array/holes_comments.js.snap

I forgot to rebase #5068 before merging it.
i
CI should pass

chore(format/js): fix missing snapshot update

---

crates/biome_cli/src/commands/daemon.rs

chore(lsp): add more logging when running the daemon

---

.changeset/usealttext_dont_check_object_spread.md
.github/workflows/preview.yml

This PR uses `pkg.pr.new` to publish out preview releases 
I will definitely test the workflow once we merge `next` to `main`

ci: use `pkg.pr.new` for preview releases

---

.github/workflows/preview.yml

ci: fix incorrect syntax

---

.github/workflows/benchmark.yml
.github/workflows/main.yml
.github/workflows/pull_request.yml
.github/workflows/pull_request_js.yml
packages/@biomejs/biome/README.md

- Remove `next` from workflows
- Remove the important block from the readme
N/A

chore: update workflows and readme

---

.github/workflows/preview.yml
.github/workflows/release.yml
packages/@biomejs/biome/scripts/update-nightly-version.mjs

Fixes some errors in some workflow I found
After merge, I will trigger the preview workflow again

ci: correctly import composite action

---

.github/workflows/release.yml

ci: install dependencies

---

package.json
pnpm-lock.yaml

ci: install required packages for changesets

---

crates/biome_cli/tests/snapshots/main_commands_check/check_help.snap
crates/biome_cli/tests/snapshots/main_commands_ci/ci_help.snap
crates/biome_configuration/src/html.rs
crates/biome_html_formatter/src/context.rs
packages/@biomejs/backend-jsonrpc/src/workspace.ts
packages/@biomejs/biome/configuration_schema.json

I missed these changes in a previous PR.

docs(html): fix docs for html's whitespace sensitivity option

---

e2e-tests/relative-apth-ignore-file/biome.json
e2e-tests/relative-path/biome.json

In other prs, the `Check JS Files` workflow fails ( https://github.com/biomejs/biome/actions/runs/13347724646/job/37280253082?pr=5129 ) by format diff.
This PR fixes it.

chore: format e2e test files

---

.changeset/real-carrots-ring.md

chore: changeset for `--suppress` flag

---

crates/biome_grit_formatter/src/grit/auxiliary/language_declaration.rs
crates/biome_grit_formatter/src/grit/auxiliary/list_accessor.rs
crates/biome_grit_formatter/src/grit/auxiliary/named_arg.rs
crates/biome_grit_formatter/src/grit/auxiliary/not.rs
crates/biome_grit_formatter/src/grit/auxiliary/root.rs
crates/biome_grit_formatter/src/grit/auxiliary/version.rs
crates/biome_grit_formatter/src/grit/patterns/pattern_definition_body.rs
crates/biome_grit_formatter/tests/specs/grit/bubble.grit.snap
crates/biome_grit_formatter/tests/specs/grit/comments/multifile.grit.snap
crates/biome_grit_formatter/tests/specs/grit/comments/top-comments.grit.snap
crates/biome_grit_formatter/tests/specs/grit/file_node.grit.snap
crates/biome_grit_formatter/tests/specs/grit/function_definition.grit.snap
crates/biome_grit_formatter/tests/specs/grit/list.grit
crates/biome_grit_formatter/tests/specs/grit/list.grit.snap
crates/biome_grit_formatter/tests/specs/grit/marzano/complex.grit.snap
crates/biome_grit_formatter/tests/specs/grit/marzano/engine.grit.snap
crates/biome_grit_formatter/tests/specs/grit/marzano/go_code.grit.snap
crates/biome_grit_formatter/tests/specs/grit/marzano/go_unknown.grit.snap
crates/biome_grit_formatter/tests/specs/grit/marzano/python.grit.snap
crates/biome_grit_formatter/tests/specs/grit/marzano/react_hooks.grit.snap
crates/biome_grit_formatter/tests/specs/grit/marzano/shadow_scope.grit.snap
crates/biome_grit_formatter/tests/specs/grit/multifile.grit.snap
crates/biome_grit_formatter/tests/specs/grit/patterns/create_new_files.grit.snap
crates/biome_grit_formatter/tests/specs/grit/patterns/definition_body.grit.snap
crates/biome_grit_formatter/tests/specs/grit/patterns/file_node.grit.snap
crates/biome_grit_formatter/tests/specs/grit/patterns/like.grit.snap
crates/biome_grit_formatter/tests/specs/grit/patterns/or.grit
crates/biome_grit_formatter/tests/specs/grit/patterns/or.grit.snap
crates/biome_grit_formatter/tests/specs/grit/version.grit.snap

Update the GritQL formatter to format the whole [standard library](https://github.com/getgrit/stdlib/pull/248) effectively by fixing bugs with `not` and list accessors + updating formatting to match existing pattern norms.
Added and updated snapshot tests.

fix: improve GritQL formatter

---

CONTRIBUTING.md

I have received a kind invitation from @arendjr to join the team, and I accepted it.
This pull request adds me to the maintainers list as my first PR as a maintainer of Biome.
N/A

chore: add siketyan to maintainers

---

crates/biome_js_analyze/src/lint/nursery/use_for_component.rs
crates/biome_js_analyze/tests/specs/nursery/useForComponent/invalid.tsx.snap

Follow pr review: https://github.com/biomejs/biome/pull/5203#issuecomment-2687316105
update test case snapshot.

chore: update useForComponent diagnostic note

---

crates/biome_configuration/src/analyzer/linter/rules.rs
crates/biome_css_analyze/src/lint/nursery.rs
crates/biome_css_analyze/src/lint/nursery/no_useless_escape_in_string.rs
crates/biome_css_analyze/src/options.rs
crates/biome_css_analyze/tests/specs/nursery/noUselessEscapeInString/invalid.css
crates/biome_css_analyze/tests/specs/nursery/noUselessEscapeInString/invalid.css.snap
crates/biome_css_analyze/tests/specs/nursery/noUselessEscapeInString/valid.css
crates/biome_css_analyze/tests/specs/nursery/noUselessEscapeInString/valid.css.snap

Follow-up of https://github.com/biomejs/biome/pull/5229
Add the rule for CSS.
I added tests

feat(css/noUselessEscapeInString): add rule

---

CONTRIBUTING.md

Updated guide to use past tense in changesets.
N/A

chore: past tense in changesets

---

crates/biome_js_analyze/src/assist/source/use_sorted_attributes.rs

The documentation was throwing parsing errors because the code block is incorrect.
Once merged, it should correctly update the website

docs: fix documentation

---

.changeset/pretty-boats-fix.md
crates/biome_cli/src/cli_options.rs
crates/biome_cli/src/commands/mod.rs
crates/biome_cli/src/lib.rs
crates/biome_cli/src/main.rs
crates/biome_cli/tests/main.rs
crates/biome_cli/tests/snapshots/main_commands_check/check_help.snap
crates/biome_cli/tests/snapshots/main_commands_ci/ci_help.snap
crates/biome_cli/tests/snapshots/main_commands_format/format_help.snap
crates/biome_cli/tests/snapshots/main_commands_lint/lint_help.snap
crates/biome_cli/tests/snapshots/main_commands_migrate/migrate_help.snap
crates/biome_cli/tests/snapshots/main_commands_rage/rage_help.snap
crates/biome_lsp/src/server.rs
crates/biome_service/src/lib.rs
crates/biome_service/src/workspace.rs
crates/biome_service/src/workspace.tests.rs
crates/biome_service/src/workspace/server.rs
crates/biome_service/src/workspace/server.tests.rs
crates/biome_service/src/workspace/watcher.tests.rs
crates/biome_wasm/src/lib.rs

Closes #5124 
Updated the snapshots. I also tested it locally and I noticed that the CLI takes longer execute the commands

feat(cli): add `--threads` to `ci` command

---

Cargo.lock
crates/biome_markdown_factory/src/generated/node_factory.rs
crates/biome_markdown_factory/src/generated/syntax_factory.rs
crates/biome_markdown_syntax/src/generated/kind.rs
crates/biome_markdown_syntax/src/generated/macros.rs
crates/biome_markdown_syntax/src/generated/nodes.rs
crates/biome_markdown_syntax/src/generated/nodes_mut.rs
crates/biome_suppression/Cargo.toml
xtask/codegen/markdown.ungram
xtask/codegen/src/generate_nodes.rs
xtask/codegen/src/markdown_kinds_src.rs

The current grammar lacked examples and nodes. I know it was kept like this as a placeholder, but it was hard to provide context to new people.
All these nodes are not implemented expection for fews. 
Current CI should pass

chore(markdown): better grammar

---

biome.json
plugins/no-object-assign.grit

It's not very meaningful, but I figured it might be a good idea to have a plugin in our own configuration for dogfooding purposes.

chore: add dogfood plugin

---

biome.json

Fixes the CI.
Green CI is happy CI.

chore: format config

---

.changeset/fair-months-report.md
crates/biome_js_analyze/src/lib.rs
crates/biome_js_analyze/src/lint/nursery/use_explicit_type.rs
crates/biome_js_analyze/tests/specs/nursery/useExplicitType/invalid.ts
crates/biome_js_analyze/tests/specs/nursery/useExplicitType/invalid.ts.snap
crates/biome_js_analyze/tests/specs/nursery/useExplicitType/valid.ts
crates/biome_js_analyze/tests/specs/nursery/useExplicitType/valid.ts.snap
crates/biome_js_formatter/tests/quick_test.rs

Follow up of https://github.com/biomejs/biome/pull/4233

feat: add option to skip arrow function

---

crates/biome_css_analyze/src/assist/source/use_sorted_properties.rs
crates/biome_js_analyze/src/assist/source/organize_imports.rs

I found some issues when rendering some assist on the website.
This PR fixes them
CI should pass

docs: update docs for website

---

crates/biome_migrate/src/analyzers/style_rules.rs
crates/biome_migrate/tests/specs/migrations/styleRules/notRecommended.json
crates/biome_migrate/tests/specs/migrations/styleRules/notRecommended.json.snap

Bug found while testing. If the recommended rules are disabled, the styling rules shouldn't be migrated.
Added a new test. No changeset required.

fix(migrate): don't migrate if recommended rules are disabled

---

rust-toolchain.toml

Upgrades rust to 1.85.1.
This should make our testing suite a bit faster.
CI should stay green

chore: upgrade rust

---

.changeset/rare-results-burn.md
crates/biome_css_analyze/src/keywords.rs
crates/biome_css_analyze/src/lint/correctness/no_unknown_function.rs
crates/biome_css_analyze/tests/specs/correctness/noUnknownFunction/valid.css
crates/biome_css_analyze/tests/specs/correctness/noUnknownFunction/valid.css.snap

This PR fixes a false positive in the Astro org, where the `tech` function wasn't in the known functions.
Also, I optimised the rule while at it. 

fix(linter): false positive for `noUnknownFunction`

---

crates/biome_js_analyze/src/assist/source/organize_imports.rs

Attempt to fix the [codegen error on the website](https://github.com/biomejs/website/actions/runs/14012684324/job/39234425913#step:11:1).
Let's see if this fix the issue.

docs(assist/organizeImports): remove invalid trailing comma in config

---

crates/biome_js_analyze/src/assist/source/organize_imports.rs

Follow-up of https://github.com/biomejs/biome/pull/5413

docs(assist/organizeImports): add missing comma in config

---

crates/biome_js_analyze/src/assist/source/organize_imports.rs

Follow-up of https://github.com/biomejs/biome/pull/5415
Let's remove them for now.

docs(assist/organizeImports): remove expect_diagnostic,use_options

---

crates/biome_js_analyze/src/assist/source/organize_imports.rs

Follow up of https://github.com/biomejs/biome/pull/5416

docs(assist/organizeImports): remove options marker and use ts where required

---

.github/workflows/beta.yml
CONTRIBUTING.md
packages/@biomejs/biome/scripts/generate-packages.mjs
packages/@biomejs/biome/scripts/update-beta-version.mjs
packages/@biomejs/biome/scripts/update-preview-version.mjs

~~Bumped version numbers to the upcoming 2.0 release.~~
Updated workflows.
Expanded the `CONTRIBUTING` section on releases a bit.
Afraid I'll first have to merge before testing the workflow. YOLO!

chore: beta preparation

---

packages/@biomejs/biome/scripts/generate-packages.mjs
packages/@biomejs/biome/scripts/update-beta-version.mjs

Fix dependencies in release process.
YOLO

chore: fix dependency versions

---

crates/biome_cli/tests/snapshots/main_cases_migrate_v2/should_successfully_migrate_knip.snap
crates/biome_migrate/src/analyzers/schema.rs

Fixes #5430
Tested manually on a fresh 1.9.4 config.

fix(migrate): read `BIOME_VERSION` at compile time for schema migration

---

.changeset/few-baboons-stop.md
crates/biome_js_analyze/src/lint/correctness/no_unused_imports.rs
crates/biome_js_analyze/tests/specs/correctness/noUnusedImports/issue_5407_lone_comment.js
crates/biome_js_analyze/tests/specs/correctness/noUnusedImports/issue_5407_lone_comment.js.snap
crates/biome_rowan/src/ast/mod.rs

Closes https://github.com/biomejs/biome/issues/5407
I handled the case where the code has lone imports without siblings. 
Added new test case

fix(lint): keep comments in noUnusedImports

---

crates/biome_js_analyze/src/lint/nursery/no_destructured_props.rs
crates/biome_js_analyze/tests/specs/nursery/noDestructuredProps/issue_5449_valid.tsx
crates/biome_js_analyze/tests/specs/nursery/noDestructuredProps/issue_5449_valid.tsx.snap

Closes https://github.com/biomejs/biome/issues/5449

fix(lint/noDestructuredProps): better check when inside a function

---

crates/biome_lsp/src/capabilities.rs
crates/biome_lsp/src/handlers/analysis.rs
crates/biome_lsp/src/session.rs

Closes https://github.com/biomejs/biome/issues/5488
I can't recall why I removed `source.fixAll.biome` from the code actions that are always available. I tested it locally, and it works. I tested the other code actions, and they work.
Local testing

fix(lsp): restore available code action

---

.changeset/proud-keys-wash.md
crates/biome_cli/tests/snapshots/main_commands_check/suppression_syntax_error.snap
crates/biome_cli/tests/snapshots/main_commands_lint/suppression_syntax_error.snap
crates/biome_suppression/src/lib.rs

Addresses https://github.com/biomejs/biome/issues/5465#issuecomment-2760683688 by adding more information to the diagnostic message.
Tested it locally in the editor

fix(core): enhance error message of incorrect suppressions

---

crates/biome_service/src/workspace/server.rs

Super tiny fix to avoid a compile warning in WASM builds.
CI should be green and have one less warning :)

chore: fix warning in WASM build

---

crates/biome_analyze/CONTRIBUTING.md

Minor typo in contributing guide

docs: minor typo

---

crates/biome_service/src/lib.rs

Added more ignore entries for the scanner, [as suggested](https://github.com/biomejs/biome/pull/5546#discussion_r2024180949).
None.

chore: more ignore entries for the scanner

---

.changeset/gold-donkeys-eat.md
Cargo.lock
crates/biome_configuration/src/analyzer/linter/rules.rs
crates/biome_css_analyze/Cargo.toml
crates/biome_css_analyze/src/lint/nursery.rs
crates/biome_css_analyze/src/lint/nursery/no_important_styles.rs
crates/biome_css_analyze/src/options.rs
crates/biome_css_analyze/tests/specs/nursery/noImportantStyles/invalid.css
crates/biome_css_analyze/tests/specs/nursery/noImportantStyles/invalid.css.snap
crates/biome_diagnostics_categories/src/categories.rs
justfile
packages/@biomejs/backend-jsonrpc/src/workspace.ts
packages/@biomejs/biome/configuration_schema.json

Closes https://github.com/biomejs/biome/issues/5039
Added new test cases. CI should stay green.

feat(css): add rule `noImportantStyles`

---

.changeset/hot-baboons-destroy.md
crates/biome_js_analyze/src/lint/complexity/no_useless_fragments.rs
crates/biome_js_analyze/src/utils/batch.rs
crates/biome_js_analyze/tests/specs/complexity/noUselessFragments/issue_4751.jsx.snap
crates/biome_js_analyze/tests/specs/complexity/noUselessFragments/issue_5484.tsx
crates/biome_js_analyze/tests/specs/complexity/noUselessFragments/issue_5484.tsx.snap

Adds some new utilities for modifying JSX elements, and fixes the linked bug. The original logic was rather confusing.
fixes #5484
Added a test.

fix(lint/noUselessFragments): fix case where code fix would remove more than just the fragment

---

crates/biome_js_analyze/src/assist/source/use_sorted_keys.rs
crates/biome_js_analyze/tests/specs/source/useSortedKeys/unsorted.js
crates/biome_js_analyze/tests/specs/source/useSortedKeys/unsorted.js.snap

Fix https://github.com/biomejs/biome/issues/5581

fix(assist/useSortedKeys): move comments with the associated key

---

crates/biome_configuration/Cargo.toml

Fix a build error when testing Biome
CI must pass.

test(build): fix test build error

---

packages/@biomejs/biome/README.fr.md
packages/@biomejs/biome/README.hi.md
packages/@biomejs/biome/README.ja.md
packages/@biomejs/biome/README.kr.md
packages/@biomejs/biome/README.md
packages/@biomejs/biome/README.pt-BR.md
packages/@biomejs/biome/README.ru.md
packages/@biomejs/biome/README.uk.md
packages/@biomejs/biome/README.zh-CN.md
packages/@biomejs/biome/README.zh-TW.md

chore: remove bronze sponsor

---

crates/biome_css_analyze/src/lint/nursery/no_unknown_pseudo_class.rs
crates/biome_css_analyze/src/lint/nursery/no_unknown_pseudo_element.rs
crates/biome_css_analyze/src/lint/suspicious/no_shorthand_property_overrides.rs

Some linting issues weren't addressed. This PR fixes them.
CI should be green

chore: fix linting issues

---

crates/biome_js_analyze/src/lint/correctness/use_import_extensions.rs
crates/biome_js_analyze/tests/specs/correctness/useImportExtensions/valid.js
crates/biome_js_analyze/tests/specs/correctness/useImportExtensions/valid.js.snap

When making https://github.com/biomejs/biome/pull/5532 I forgot to handle valid cases this PR fix it.
Added snapshots.

fix(linter): useImportExtensions should not error on valid imports with sub extensions

---

.github/workflows/main.yml
.github/workflows/pull_request.yml

This PR changes the PR workflow and the main workflow to use the depot runner. 
CI should pass

ci: use depot runner

---

.github/renovate.json

The crate `rand` can't be updated safely. I added it to the ignore list, so we can safely upgrade the other crates.
CI should pass

ci(renovate): ignore `rand`

---

packages/@biomejs/biome/README.fr.md
packages/@biomejs/biome/README.hi.md
packages/@biomejs/biome/README.ja.md
packages/@biomejs/biome/README.kr.md
packages/@biomejs/biome/README.md
packages/@biomejs/biome/README.pt-BR.md
packages/@biomejs/biome/README.ru.md
packages/@biomejs/biome/README.uk.md
packages/@biomejs/biome/README.zh-CN.md
packages/@biomejs/biome/README.zh-TW.md

chore: add gold sponsor

---

.changeset/no-duplicate-object-keys-5617.md
crates/biome_js_analyze/src/lint/suspicious/no_duplicate_object_keys.rs
crates/biome_js_analyze/tests/specs/suspicious/noDuplicateObjectKeys/invalid.js
crates/biome_js_analyze/tests/specs/suspicious/noDuplicateObjectKeys/invalid.js.snap
crates/biome_js_analyze/tests/specs/suspicious/noDuplicateObjectKeys/invalid.jsonc
crates/biome_js_analyze/tests/specs/suspicious/noDuplicateObjectKeys/invalid.jsonc.snap
crates/biome_js_analyze/tests/specs/suspicious/noDuplicateObjectKeys/valid.jsonc
crates/biome_js_analyze/tests/specs/suspicious/noDuplicateObjectKeys/valid.jsonc.snap
crates/biome_js_syntax/src/expr_ext.rs

Fix https://github.com/biomejs/biome/issues/5617

fix(lint/noDuplicateObjectKeys): transfer comments

---

RELEASES.md

A brief document that explains how Biome does releases. 
One thing that we could add in the future, is to publish a pre-release to GitHub too, with a specific tag (name TBD), and with a small message. This could help users that don't have/want access to di Discord 
Proofread. The core contributors team is already aligned with the proposed workflow.

docs: add RELEASES.md document

---

crates/biome_yaml_factory/src/generated/node_factory.rs
crates/biome_yaml_factory/src/generated/syntax_factory.rs
crates/biome_yaml_syntax/src/generated/kind.rs
crates/biome_yaml_syntax/src/generated/macros.rs
crates/biome_yaml_syntax/src/generated/nodes.rs
crates/biome_yaml_syntax/src/generated/nodes_mut.rs
crates/biome_yaml_syntax/src/lib.rs
crates/biome_yaml_syntax/src/syntax_node.rs
xtask/codegen/src/yaml_kinds_src.rs
xtask/codegen/yaml.ungram

Quick follow up to https://github.com/biomejs/biome/pull/5615 to resolve the issues with some nodes, namely:
- Rename YamlStream to YamlRoot
- Rename YamlIndentedBlock to AnyYamlIndentedBlock

fix(yaml): remaining issues with Yaml grammar

---

crates/biome_cli/src/execute/migrate/eslint_any_rule_to_biome.rs
crates/biome_js_analyze/src/lint/nursery/no_ts_ignore.rs

There's no rule named `ban-ts-comment` in ESLint core.

fix(lint): correct the source of the rule `noTsIgnore`

---

Cargo.lock
crates/biome_yaml_parser/Cargo.toml
crates/biome_yaml_parser/src/lexer/mod.rs
crates/biome_yaml_parser/src/lexer/tests.rs
crates/biome_yaml_parser/src/lib.rs
crates/biome_yaml_parser/src/parser/block.rs
crates/biome_yaml_parser/src/parser/document.rs
crates/biome_yaml_parser/src/parser/mod.rs
crates/biome_yaml_parser/src/token_source.rs

Initialize a minimal YAML parser
CI is still green

feat(yaml): initialize parser

---

package.json

Align the pnpm version with corepack config at `package.json`. 
BTW, nodejs will remove corepack in the future: https://socket.dev/blog/node-js-takes-steps-towards-removing-corepack , so we need more way to restrict the package manager version.

chore(deps): add engines field for pnpm

---

CONTRIBUTING.md

Thankfully I've invited and joined to the Core Contributors team. Moving my name to the team in CONTRIBUTING.md.
N/A. At least I double-checked spelling of my name :)

chore: move @siketyan to the Core Contributors team

---

.changeset/use-naming-convention-4545.md
crates/biome_js_analyze/src/lint/style/use_naming_convention.rs
crates/biome_js_analyze/tests/specs/style/useNamingConvention/validExternalModule.ts
crates/biome_js_analyze/tests/specs/style/useNamingConvention/validExternalModule.ts.snap

Fix https://github.com/biomejs/biome/issues/4545

fix(lint/useNamingConvention): ignore declarations in external modules

---

crates/biome_cli/src/panic.rs

Added a small message to encourage users also to provide a reproduction.
Proof read

chore: update panic error message

---

.changeset/busy-houses-add.md
.changeset/quiet-animals-speak.md
crates/biome_cli/tests/cases/suppressions.rs
crates/biome_cli/tests/snapshots/main_cases_suppressions/should_emit_diagnostics_for_incorrect_reason.snap
crates/biome_cli/tests/snapshots/main_commands_lint/lint_only_rule_ignore_suppression_comments.snap
crates/biome_js_analyze/src/lint/correctness/use_exhaustive_dependencies.rs
crates/biome_js_formatter/tests/specs/js/module/statement/return_verbatim_argument.js
crates/biome_js_formatter/tests/specs/js/module/statement/return_verbatim_argument.js.snap
crates/biome_suppression/src/lib.rs

Implements what @siketyan proposed in https://github.com/biomejs/biome/discussions/2907#discussioncomment-12868094
- An empty reason emits a warning
- A reason `<explanation>` emits a warning
Added new tests

feat(core): suppression reason

---

crates/biome_js_analyze/src/assist/source/organize_imports.rs

This updates the docs of the import/export organizer.
This PR should not be merged until the release of a new version of Biome (i.e. Biome v2 or Biome beta 2).

docs(assist/organizeImports): update docs with last changes

---

crates/biome_js_type_info/src/format_type_info.rs
crates/biome_js_type_info/tests/snapshots/infer_type_of_function_with_destructured_arguments.snap
crates/biome_service/src/file_handlers/astro.rs
crates/biome_service/src/file_handlers/css.rs
crates/biome_service/src/file_handlers/graphql.rs
crates/biome_service/src/file_handlers/grit.rs
crates/biome_service/src/file_handlers/html.rs
crates/biome_service/src/file_handlers/javascript.rs
crates/biome_service/src/file_handlers/json.rs
crates/biome_service/src/file_handlers/mod.rs
crates/biome_service/src/file_handlers/svelte.rs
crates/biome_service/src/file_handlers/vue.rs
crates/biome_service/src/snapshots/biome_service__workspace__tests__debug_type_info.snap
crates/biome_service/src/workspace.rs
crates/biome_service/src/workspace.tests.rs
crates/biome_service/src/workspace/client.rs
crates/biome_service/src/workspace/server.rs

This PR exposes a new debug method from the workspace. 
Next step: use this method in the playground
Added new tests and updated the existing ones

feat(workspace): add `debug_type_info`

---

.changeset/some-bikes-worry.md
crates/biome_cli/src/execute/migrate.rs

closes #5770 
modified the code based on @ematipico's suggestions. https://github.com/biomejs/biome/issues/5770#issuecomment-2830725278 ❤️
1. modified the code using the workspace API
2. build `biome` with new commits
```
cargo build --bin biome
```
3. run `./biome migrate --write` in the issued repro project
```
./biome migrate --write
```
the result showed as expected.

fix(biome_cli): use workspace API to update and format config files

---

.github/workflows/main.yml
.github/workflows/pull_request.yml

ci: use depot runners for windows

---

crates/biome_lsp/src/server.rs
crates/biome_service/src/workspace_types.rs
crates/biome_wasm/src/lib.rs
packages/@biomejs/backend-jsonrpc/src/workspace.ts

I am about to implement a new tab in the playground, and I need to expose the function in the WASM build
CI should stay green

feat(wasm): expose `getTypeInfo`

---

crates/biome_service/src/file_handlers/astro.rs
crates/biome_service/src/file_handlers/css.rs
crates/biome_service/src/file_handlers/graphql.rs
crates/biome_service/src/file_handlers/grit.rs
crates/biome_service/src/file_handlers/html.rs
crates/biome_service/src/file_handlers/javascript.rs
crates/biome_service/src/file_handlers/json.rs
crates/biome_service/src/file_handlers/mod.rs
crates/biome_service/src/file_handlers/svelte.rs
crates/biome_service/src/file_handlers/vue.rs
crates/biome_service/src/snapshots/biome_service__workspace__tests__debug_registered_types.snap
crates/biome_service/src/snapshots/biome_service__workspace__tests__debug_type_info.snap
crates/biome_service/src/workspace.rs
crates/biome_service/src/workspace.tests.rs
crates/biome_service/src/workspace/client.rs
crates/biome_service/src/workspace/server.rs
crates/biome_service/src/workspace_types.rs
crates/biome_wasm/src/lib.rs
packages/@biomejs/backend-jsonrpc/src/workspace.ts

`debug_type_info` was printing some information that was out of place (registered types). 
In this PR we add `debug_registered_types`, so we can pull them separately without tarnish the IR printed by `debug_type_info`
Added a new test. CI should pass

refactor(core): break down type info and registered types

---

crates/biome_package/src/node_js_package/package_json.rs

`node_semver` panics in rare cases, for example `~0.x.0`. Unfortunately in the wild there are very old packages that are still used by modern packages. 
This PR adds a `catch_unwind` so we don't panic during the parsing.
Added a test

fix(package_json): catch panic error when

---

crates/biome_js_analyze/src/assist/source/organize_imports/import_groups.rs
packages/@biomejs/backend-jsonrpc/src/workspace.ts
packages/@biomejs/biome/configuration_schema.json

Address https://github.com/biomejs/biome/discussions/5835
CI is green.

fix(schema): more precise type for organizeImports predfined groups

---

crates/biome_js_analyze/src/assist/source/organize_imports/import_groups.rs

Cherry-pick the fixes of https://github.com/biomejs/biome/pull/5874
CI is green.

fix(organizeImports): fix Display impl

---

crates/biome_yaml_parser/src/token_source.rs

Allow the parser to lex different tokens depending on the context
Everything should still be green

feat(yaml): implement BumpWithContext for YamlTokenSource

---

crates/biome_yaml_parser/src/parser/mod.rs
crates/biome_yaml_parser/src/token_source.rs

Implement rewind and checkpoint functions for the YAML parser.
These functionalities are necessary for the parser to disambiguate between a mapping entry like `[abc, {123: 546}]: def` and a single flow node like `[abc, {123: 546}]`. In such cases, the parser has to parse past the flow node and check for the presence of a `:` indicator to determine whether it's part of a mapping entry.
Since a flow node might not be valid as a mapping key, the parser must be able to rewind to the start of the node and reparse it as a flow node instead.
Everything should remain green.

feat(yaml): implement rewind and checkpoint for yaml parser

---

crates/biome_cli/src/execute/diagnostics.rs
crates/biome_cli/src/execute/traverse.rs

Closes https://github.com/biomejs/biome/issues/5871
I also optimised the code to use `Utf8Path` instead, which shouldn't allocate anything. 
I tested locally

fix(cli): format diagnostic location

---

Cargo.lock
Cargo.toml
crates/biome_module_graph/src/resolver_cache.rs

Let's stay up to date.
Everything should remain green.

chore: upgrade to `oxc-resolver` 8

---

crates/biome_analyze/src/lib.rs
crates/biome_analyze/src/matcher.rs
crates/biome_cli/tests/cases/suppressions.rs
crates/biome_cli/tests/commands/lint.rs
crates/biome_cli/tests/snapshots/main_cases_suppressions/should_emit_diagnostics_for_incorrect_reason.snap
crates/biome_cli/tests/snapshots/main_commands_lint/lint_only_rule_ignore_suppression_comments.snap
crates/biome_suppression/src/lib.rs

Closes https://github.com/biomejs/biome/issues/5846
The `<explanation>` check isn't done during the parsing phase, but after. In order to emit a good diagnostic, now we save the reason and its range inside `Suppression`
Updated the snapsthos based on the correct requirements

fix(analyzer): placeholder shouldn't block signals

---

packages/@biomejs/biome/README.zh-TW.md

Fix the wrong translations of "support".

docs(readme): fix wrong translations

---

crates/biome_js_analyze/tests/quick_test.rs
crates/biome_js_analyze/tests/specs/nursery/noFloatingPromises/invalid.ts
crates/biome_js_analyze/tests/specs/nursery/noFloatingPromises/invalid.ts.snap
crates/biome_module_graph/src/js_module_info/scoped_resolver.rs

Fixes an issue with type inference not following all (relative) imports.
Updated test case.

fix(core): fix resolving of (relative) imports

---

Cargo.lock

PR to fix a small CVE: https://github.com/crossbeam-rs/crossbeam/pull/1187#issue-2980761131
CI should pass

fix(core): update crossbeam channel due to CVE

---

.changeset/afraid-vans-design.md
crates/biome_cli/tests/commands/check.rs
crates/biome_cli/tests/commands/lint.rs
crates/biome_cli/tests/snapshots/main_cases_editorconfig/should_have_cli_override_editorconfig.snap
crates/biome_cli/tests/snapshots/main_cases_editorconfig/should_use_editorconfig_check.snap
crates/biome_cli/tests/snapshots/main_cases_editorconfig/should_use_editorconfig_check_enabled_from_biome_conf.snap
crates/biome_cli/tests/snapshots/main_cases_editorconfig/should_use_editorconfig_ci.snap
crates/biome_cli/tests/snapshots/main_cases_linter_groups_plain/enables_all_rules_when_group_is_error.snap
crates/biome_cli/tests/snapshots/main_cases_linter_groups_plain/enables_all_rules_when_group_is_on_with_default_severity.snap
crates/biome_cli/tests/snapshots/main_cases_rules_via_dependencies/enables_react_rules_via_dependencies.snap
crates/biome_cli/tests/snapshots/main_cases_rules_via_dependencies/enables_rules_via_dependencies_but_disable_rule_from_config.snap
crates/biome_cli/tests/snapshots/main_cases_suppressions/err_when_missing_range_end.snap
crates/biome_cli/tests/snapshots/main_cases_suppressions/syntax_rule_line_suppression.snap
crates/biome_cli/tests/snapshots/main_cases_suppressions/syntax_rule_range_suppression.snap
crates/biome_cli/tests/snapshots/main_cases_suppressions/syntax_rule_top_suppression.snap
crates/biome_cli/tests/snapshots/main_commands_check/apply_unsafe_with_error.snap
crates/biome_cli/tests/snapshots/main_commands_check/fix_unsafe_with_error.snap
crates/biome_cli/tests/snapshots/main_commands_check/write_unsafe_with_error.snap
crates/biome_cli/tests/snapshots/main_commands_lint/apply_unsafe_with_error.snap
crates/biome_cli/tests/snapshots/main_commands_lint/check_stdin_write_unsafe_successfully.snap
crates/biome_cli/tests/snapshots/main_commands_lint/fix_unsafe_with_error.snap
crates/biome_cli/tests/snapshots/main_commands_lint/group_level_recommended_false_enable_specific.snap
crates/biome_js_analyze/src/lint/correctness/no_unused_variables.rs
crates/biome_js_analyze/tests/specs/correctness/noUnusedVariables/invalidFunction.ts.snap
crates/biome_js_analyze/tests/specs/correctness/noUnusedVariables/invalidRecursiveFunctions.js.snap
crates/biome_js_analyze/tests/specs/correctness/noUnusedVariables/invalidTypeValueSameNames.ts.snap

The PR adds fix suggestion for the rule `noUnusedVariables` to `JsFunctionDeclaration` similar to `JsArrowFunctionExpression` because they should be treated the same in regards to this rule.
Closes #5917 
I updated the snapshot tests for invalid functions to reflect the unsafe fixes.

fix(js_analyze): suggest fix for unused `JsFunctionDeclaration`

---

.changeset/icy-beds-build.md
crates/biome_cli/src/cli_options.rs
crates/biome_cli/src/commands/mod.rs
crates/biome_cli/src/execute/traverse.rs
crates/biome_cli/tests/commands/check.rs
crates/biome_cli/tests/commands/lint.rs
crates/biome_cli/tests/snapshots/main_commands_check/fs_error_dereferenced_symlink.snap
crates/biome_cli/tests/snapshots/main_commands_lint/fs_error_dereferenced_symlink.snap
crates/biome_service/src/workspace/server.rs

Closes https://github.com/biomejs/biome/issues/5919
I tested it locally in this repository, and confirmed that Biome still checks the same amount of files

fix(cli): normalise config-path path

---

.changeset/dull-dogs-leave.md
crates/biome_css_analyze/src/lint/correctness/no_unknown_pseudo_element.rs
crates/biome_css_analyze/tests/specs/correctness/noUnknownPseudoElement/valid.css
crates/biome_css_analyze/tests/specs/correctness/noUnknownPseudoElement/valid.css.snap

Closes https://github.com/biomejs/biome/issues/5998

fix(lint): `noUnknownPseudoElement` selector check

---

.changeset/pretty-vans-appear.md
crates/biome_css_analyze/src/lint/suspicious/no_duplicate_properties.rs
crates/biome_css_analyze/tests/specs/suspicious/noDuplicateProperties/valid_6022.css
crates/biome_css_analyze/tests/specs/suspicious/noDuplicateProperties/valid_6022.css.snap
crates/biome_css_semantic/src/events.rs
crates/biome_css_semantic/src/semantic_model/builder.rs
crates/biome_css_semantic/src/semantic_model/model.rs

Closes https://github.com/biomejs/biome/issues/6022
I also took the opportunity to make the semantic model a bit more typed, which was something I already did some PR ago. 
Added a test

fix(noDuplicateProperties): don't track `@keyframes`

---

crates/biome_service/src/settings.rs

This PR skip the log of `self` from `format_options`, which is very noisy
Should compile

chore: remove log

---

crates/biome_js_analyze/src/lint/nursery/use_adjacent_getter_setter.rs

Update version of `useAdjacentGetterSetter` to `2.0.0` as requested here: https://github.com/biomejs/biome/pull/5964#discussion_r2093706904
None needed.

chore: change version of `useAdjacentGetterSetter`

---

crates/biome_cli/tests/cases/linter_domains.rs
crates/biome_cli/tests/snapshots/main_cases_linter_domains/does_enable_test_rules_when_recommended_rules_are_disabled_but_domain_is_enabled.snap

Follow-up of https://github.com/biomejs/biome/pull/6094#discussion_r2097276357
Added only a test case, the snapshot show that the current logic covers the use case.

test: cover domains case

---

.changeset/silent-brooms-chew.md

Wording was a bit confusing still.
N/A

chore: tweak monorepo changelog

---

biome.json
crates/biome_cli/src/commands/mod.rs
crates/biome_cli/src/commands/scan_kind.rs
crates/biome_cli/tests/cases/monorepo.rs
crates/biome_cli/tests/snapshots/main_cases_monorepo/should_extend_from_the_root_config.snap
crates/biome_service/src/settings.rs
crates/biome_service/src/workspace/server.rs

Fixed the behaviour for how the CLI forces the scanner kind for some commands + fixed an issue with nested configs overriding the root config.
Tests updated + manually tested.

fix(core): fix extending nested configs

---

crates/biome_cli/tests/cases/monorepo.rs
crates/biome_cli/tests/snapshots/main_cases_monorepo/should_ignore_files_in_nested_projects.snap
crates/biome_service/src/projects.rs

Closes https://github.com/biomejs/biome/issues/6225
Ignore matches are stored in the root configuration regardless of where they are, so they are semantically detached from the root-nested settings division.
I manually tested it in the repository provided. Test added

fix(core): ignore matches in monorepo

---

crates/biome_cli/tests/commands/check.rs
crates/biome_cli/tests/snapshots/main_commands_check/doesnt_check_file_when_assist_is_disabled.snap
crates/biome_lsp/src/handlers/analysis.rs
crates/biome_service/src/file_handlers/css.rs
crates/biome_service/src/file_handlers/graphql.rs
crates/biome_service/src/file_handlers/javascript.rs
crates/biome_service/src/file_handlers/json.rs
crates/biome_service/src/file_handlers/mod.rs
crates/biome_service/src/workspace.rs
crates/biome_service/src/workspace/server.rs
packages/@biomejs/backend-jsonrpc/src/workspace.ts

Closes https://github.com/biomejs/biome/issues/6247
When fixing files, we didn't use the rule categories passed via params

fix(core): use rule categories when applying fixes

---

crates/biome_cli/tests/snapshots/main_cases_migrate_v2/should_migrate_nested_config.snap
crates/biome_cli/tests/snapshots/main_commands_migrate/should_migrate_nested_files.snap
crates/biome_service/src/settings.rs
crates/biome_service/src/workspace/scanner.rs
crates/biome_service/src/workspace/server.rs

Closes https://github.com/biomejs/biome/issues/6238
The order of the evaluated files was incorrect. 
I tested it against the reproduction provided

fix(core): remove `rev` when iterating over evaluated paths

---

.changeset/pink-sides-sit.md
crates/biome_js_analyze/src/lint/correctness/no_unused_imports.rs
crates/biome_js_analyze/tests/specs/correctness/noUnusedImports/invalid_issue_6229.ts
crates/biome_js_analyze/tests/specs/correctness/noUnusedImports/invalid_issue_6229.ts.snap

Closes https://github.com/biomejs/biome/issues/6229
The fix was simple. Just needed to add the white space to the token.

fix(lint): rule `noUnusedImports` use case

---

crates/biome_js_analyze/src/suppressions.tests.rs
crates/biome_js_analyze/tests/quick_test.rs
crates/biome_module_graph/tests/spec_tests.rs
crates/biome_package/src/node_js_package/package_json.rs
crates/biome_resolver/src/lib.rs

Hopefully, this will reduce some memory usage when deserialising the `package.json`
Green CI. Also, I accidentally pushed https://github.com/biomejs/biome/commit/e39cb3bb4f79f1144252509386ff8da07030a167 and this PR should fix it

perf(package): reduce string usage

---

crates/biome_cli/src/execute/migrate.rs
crates/biome_cli/tests/snapshots/main_cases_migrate_v2/should_migrate_nested_config.snap
crates/biome_cli/tests/snapshots/main_commands_migrate/should_migrate_nested_files.snap

Closes https://github.com/biomejs/biome/issues/6328
Snapshots updated

fix(migrate): double migration

---

GOVERNANCE.md
packages/@biomejs/biome/README.md

This PR slightly updates the `README.md` and remove the issue funding, since we don't use Polar.sh anymore.
This PR updates the `GOVERNANCE.md` document by removing all references to polar.sh, and halting the community-funded bounties. 
Proof read

chore: update readme and governance

---

.github/workflows/release.yml
biome.json
package.json
pnpm-lock.yaml
scripts/update-manifests.mjs
scripts/version-check.ts

Hopefully this works better.
YOLO. Have to try it on `main` for the release.

chore: use own version check script

---

crates/biome_js_analyze/src/lint/nursery/no_shadow.rs
crates/biome_js_analyze/src/lint/suspicious/no_shadow_restricted_names.rs
packages/@biomejs/biome/CHANGELOG.md

docs: correct urls

---

package.json
packages/@biomejs/biome/package.json
pnpm-lock.yaml
pnpm-workspace.yaml

Hopefully, this should fix the release workflow, where we we run `pnpm install` and the lock file is updated due to the optional dependencies.
I'll try the release again 😅

chore: optional dependencies should be ignored

---

packages/@biomejs/backend-jsonrpc/package.json
packages/@biomejs/js-api/package.json
pnpm-lock.yaml

These updates should prevent the lock file changes in the release PR
Merge it and monitor the release PR

chore: update to use workspace protocol

---

.changeset/lemon-experts-sleep.md
.github/workflows/release.yml
packages/@biomejs/biome/scripts/copy-binaries.mjs
packages/@biomejs/cli-darwin-arm64/package.json
packages/@biomejs/cli-darwin-x64/package.json
packages/@biomejs/cli-linux-arm64-musl/package.json
packages/@biomejs/cli-linux-arm64/package.json
packages/@biomejs/cli-linux-x64-musl/package.json
packages/@biomejs/cli-linux-x64/package.json
packages/@biomejs/cli-win32-arm64/package.json
packages/@biomejs/cli-win32-x64/package.json

The 2.0.1 release is out, so I can't make any more changes and test them. I believe these are the last ones to have a fully working action (I hope!)
Also, 2.0.1 misses the binaries because we forgot to copy them. Crated a new script which is largely based on `generate-package.mjs`

ci: add permissions to release actions

---

.changeset/use_readonly_class_properties_definition.md

Updated the changeset for #6297, which was supposed to be a patch release as it's a nursery rule.
N/A

chore: update changeset to patch

---

.github/workflows/release.yml

All previous releases before 2.0.4 followed this format, the new format is breaking the github action as it's trying to fetch the old format

chore: fix release tag name

---

packages/@biomejs/biome/README.fr.md
packages/@biomejs/biome/README.hi.md
packages/@biomejs/biome/README.ja.md
packages/@biomejs/biome/README.kr.md
packages/@biomejs/biome/README.md
packages/@biomejs/biome/README.pt-BR.md
packages/@biomejs/biome/README.ru.md
packages/@biomejs/biome/README.uk.md
packages/@biomejs/biome/README.zh-CN.md
packages/@biomejs/biome/README.zh-TW.md

chore: update vscode badges

---

.github/labeler.yml

Adds `A-Resolver` and `A-Type-Inference` to the labeler.
N/A

chore: add labels for resolver and type inference

---

crates/biome_analyze/src/rule.rs
crates/biome_js_analyze/src/assist/source/use_sorted_keys.rs

Add `sources` to `js/useSortedKeys`

fix(js/useSortedKeys): add sources

---

.changeset/wild-peaches-rescue.md
crates/biome_lsp/src/handlers/analysis.rs

Closes https://github.com/biomejs/biome/issues/6459
We were computing the incorrect file features when calling the `fix_all` function. Now we currently add actions and linting. 
I tested it manually using the reproduction provided

fix(lsp): fix all file features

---

.changeset/nine-turkeys-stare.md
.changeset/polite-monkeys-work.md
crates/biome_js_analyze/src/lint/a11y/use_alt_text.rs
crates/biome_js_analyze/src/lint/a11y/use_semantic_elements.rs
crates/biome_js_analyze/tests/specs/a11y/useAltText/invalid_issue_6384.tsx
crates/biome_js_analyze/tests/specs/a11y/useAltText/invalid_issue_6384.tsx.snap
crates/biome_js_analyze/tests/specs/a11y/useAltText/valid_issue_6384.tsx
crates/biome_js_analyze/tests/specs/a11y/useAltText/valid_issue_6384.tsx.snap
crates/biome_js_analyze/tests/specs/a11y/useSemanticElements/valid_issue_6384.tsx
crates/biome_js_analyze/tests/specs/a11y/useSemanticElements/valid_issue_6384.tsx.snap

Closes https://github.com/biomejs/biome/issues/6384
The range of diagnostic included trivia, which it shouldn't
Added two tests

fix(linter): diagnostic range for `useAtlText`

---

justfile

This PR adjusts indentation and removes extra blank lines in the Justfile.  
These changes improve the readability and maintainability of the build scripts without affecting any functionality. No related issues were found, and this is purely a code style cleanup.
- Run `just install-tools` to ensure the script keeps working.

chore(justfile): adjust indentation and remove extra blank lines in `justfile`

---

CONTRIBUTING.md

This is a PR to add myself to the list of maintainers.

docs: add mdevils to maintainers

---

.changeset/fix_no_focused_tests_diagnostic_message_to_have_correct_fn_name.md

https://github.com/biomejs/biome/pull/6599 follow up to update the changeset

fix(biome-js-analyze): update changes 

---

.changeset/sixty-things-pump.md
crates/biome_css_formatter/src/css/auxiliary/container_style_query_in_parens.rs
crates/biome_css_formatter/tests/specs/css/atrule/container.css.snap
crates/biome_css_parser/src/syntax/at_rule/container/mod.rs
crates/biome_css_parser/tests/css_test_suite/ok/at_rule/at_rule_container.css
crates/biome_css_parser/tests/css_test_suite/ok/at_rule/at_rule_container.css.snap
crates/biome_css_parser/tests/css_test_suite/ok/at_rule/at_rule_container_complex.css.snap

Fix https://github.com/biomejs/biome/issues/6680
new snapshots

fix(css_formatter): correct spacing in container style queries

---

.changeset/spicy-lizards-enjoy.md
crates/biome_js_analyze/src/lint/nursery/no_shadow.rs
crates/biome_js_analyze/tests/specs/nursery/noShadow/valid-func-in-type.ts
crates/biome_js_analyze/tests/specs/nursery/noShadow/valid-func-in-type.ts.snap

fix(noShadow): fix a false positive related to function parameters inside type definitions

---

.changeset/angry-asses-attack.md
.changeset/boolean-bananas-bounce.md
.changeset/conditional-clauses-check.md
.changeset/consequtive_commas_collaborate.md
.changeset/funky-functions-follow.md
.changeset/getters-get-good.md
.changeset/muddy-mules-meander.md
.changeset/no_unused_function_parameters_add_option_ignore_rest_siblings.md
.changeset/ternary-tests-tick.md
CONTRIBUTING.md

We can't have big headers in changesets, otherwise it breaks the correct flow of the headings of the changelog, and it messes up renovate too.
I updated the contribution guide, and I also removed the headers we have in current changesets because it's about *examples*, and it doesn't make much sense to have an header for example, unless there's a more important header before that one.

chore: update contribution and changesets

---

.changeset/five-dodos-promise.md
crates/biome_js_analyze/src/lint/correctness/no_unused_imports.rs
crates/biome_js_analyze/tests/specs/correctness/noUnusedImports/valid-type-augmentation.ts
crates/biome_js_analyze/tests/specs/correctness/noUnusedImports/valid-type-augmentation.ts.snap

fix(noUnusedImports): formally make an exception for type augmentation imports

---

crates/biome_js_analyze/src/lint/nursery/no_implicit_coercion.rs
crates/biome_js_analyze/src/lint/nursery/no_magic_numbers.rs
crates/biome_js_analyze/src/lint/nursery/no_misused_promises.rs
crates/biome_js_analyze/src/lint/nursery/no_unassigned_variables.rs
crates/biome_js_analyze/src/lint/nursery/use_readonly_class_properties.rs
crates/biome_js_analyze/src/lint/nursery/use_unified_type_signature.rs
crates/biome_js_analyze/src/lint/suspicious/no_alert.rs

New rules have their version set.
N/A.

chore: set versions for new rules

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

@arendjr, you were the main promoter of this change, so please have a look at this PR and change it according to what you had in mind

docs: update contribution guide and pull request template

---

CONTRIBUTING.md

Added a note to check the milestone before releasing to our `CONTRIBUTING.md`.
N/A

chore: check milestone before releasing

---

.changeset/lovely-moments-join.md

Fixes the changeset for `noVueReservedProps` rule:
1. Minor -> Patch
2. Header styling

chore: fix `noVueReservedProps` changeset

---

crates/biome_js_analyze/src/lint/nursery/no_import_cycles.rs

I was noticing slowdowns in my projects coming from this rule. Obviously, it would be better to make the rule faster, which I have some ideas for. But given that the source rule has a similar disclaimer, we should probably have it too.

docs(noImportCycles): add note about computation cost

---

crates/biome_analyze/CONTRIBUTING.md

This PR documents how the options of lint rules should be documented.
N/A
N/A

docs: explain how to document options

---

.changeset/modern-ghosts-cough.md
crates/biome_lsp/src/server.rs

Closes https://github.com/biomejs/biome-zed/issues/113
I tested manually in Zed and VSCode and I could see the diagnostics correctly updated.

fix(lsp): update diagnostics on watched files

---

Cargo.lock
Cargo.toml
crates/biome_tailwind_factory/Cargo.toml
crates/biome_tailwind_factory/src/generated.rs
crates/biome_tailwind_factory/src/generated/node_factory.rs
crates/biome_tailwind_factory/src/generated/syntax_factory.rs
crates/biome_tailwind_factory/src/lib.rs
crates/biome_tailwind_factory/src/make.rs
crates/biome_tailwind_syntax/Cargo.toml
crates/biome_tailwind_syntax/src/generated.rs
crates/biome_tailwind_syntax/src/generated/kind.rs
crates/biome_tailwind_syntax/src/generated/macros.rs
crates/biome_tailwind_syntax/src/generated/nodes.rs
crates/biome_tailwind_syntax/src/generated/nodes_mut.rs
crates/biome_tailwind_syntax/src/lib.rs
crates/biome_tailwind_syntax/src/syntax_node.rs
xtask/codegen/src/ast.rs
xtask/codegen/src/formatter.rs
xtask/codegen/src/generate_syntax_kinds.rs
xtask/codegen/src/language_kind.rs
xtask/codegen/src/lib.rs
xtask/codegen/src/tailwind_kinds_src.rs
xtask/codegen/tailwind.ungram

Originally, I was going to make a `biome_tailwind_utils` crate with utility functions to interact with tailwind classes. I realized that I was essentially writing a parser, so I figured that it would be better to be able to use the full power of our parsing infra to do it.

feat(parse): add tailwind grammar

---

.github/workflows/main.yml
.github/workflows/pull_request.yml

This PR tries out the new `depot cargo` command for the PR and main workflows
It should stay green

ci: use depot cargo in the PR workflow

---

.github/workflows/main.yml
.github/workflows/pull_request.yml

Revert "ci: use depot cargo in the PR workflow"

---

.changeset/floppy-dragons-yell.md
crates/biome_js_analyze/src/lint/a11y/use_semantic_elements.rs
crates/biome_js_analyze/tests/specs/a11y/useSemanticElements/invalid.jsx
crates/biome_js_analyze/tests/specs/a11y/useSemanticElements/invalid.jsx.snap
crates/biome_js_analyze/tests/specs/a11y/useSemanticElements/invalid_self_closing.jsx
crates/biome_js_analyze/tests/specs/a11y/useSemanticElements/invalid_self_closing.jsx.snap

Closes https://github.com/biomejs/biome/issues/6622
Added new tests

fix(lint): `useSemanticElements` self-closing elements

---

crates/biome_analyze/CONTRIBUTING.md

docs(analyze): about "Services"

---

.claude/agents/biome-lint-engineer.md
.claude/agents/cst-parser-engineer.md
.claude/agents/ir-formatter-engineer.md
CLAUDE.md

This PR adds a few Claude agents that could be helpful for coding with claude code. 
I created the agents using the recommended steps, so it's possible that they are not very accurate. Plus, it's a new technology, so feel free to send PR or suggestions to improve it.
Proof read

chore: add Claude sub-agents

---

crates/biome_js_analyze/src/lint/nursery/no_vue_reserved_keys.rs
crates/biome_js_analyze/src/lint/nursery/no_vue_reserved_props.rs
crates/biome_js_analyze/src/lint/nursery/use_react_function_components.rs
crates/biome_json_analyze/src/lint/nursery/no_quickfix_biome.rs

Changed the `version` metadata in the rules we have already released in previous versions.
N/A
Will be synced to the website repo automatically.

chore(lint): add version to the released rules

---

.github/workflows/autofix.yml
.github/workflows/pull_request.yml

Uses [Autofix.ci](https://autofix.ci/) to automatically update codegen and fix formatting issues in PRs.
Ideally I would like it to be able to rebase in case of conflicts too, but I'm not sure how to set that up yet. Suggestions welcome!
CI/YOLO

chore: setup autofix.ci workflow

---

.coderabbit.yaml

Few more small CodeRabbit tweaks.
YOLO

chore: tweak CodeRabbit

---

crates/biome_service/src/scanner.rs

Fixed broken WASM build after #6989.
Will be synced to next.biomejs.dev/playground so we can try there
N/A

fix: revive wasm build

---

.changeset/new-shrimps-reply.md
crates/biome_js_analyze/src/lint/a11y/use_semantic_elements.rs
crates/biome_js_analyze/tests/specs/a11y/useSemanticElements/invalid.jsx
crates/biome_js_analyze/tests/specs/a11y/useSemanticElements/invalid.jsx.snap
crates/biome_js_analyze/tests/specs/a11y/useSemanticElements/invalid_self_closing.jsx
crates/biome_js_analyze/tests/specs/a11y/useSemanticElements/invalid_self_closing.jsx.snap
crates/biome_js_analyze/tests/specs/a11y/useSemanticElements/valid.jsx
crates/biome_js_analyze/tests/specs/a11y/useSemanticElements/valid.jsx.snap

Fixes #6951
- Tests updated
Bugfix?

fix: remove option, combobox, listbox from semantic element suggestions

---

crates/biome_js_analyze/src/lint/style/use_consistent_member_accessibility.rs

Closes https://github.com/biomejs/website/issues/2833
The rule doesn't have any fix, so the rule shouldn't mention any "future" fix.
N/A
N/A

docs: remove the mention of a fix

---

.changeset/fluffy-lies-drum.md
crates/biome_cli/tests/cases/monorepo.rs
crates/biome_cli/tests/snapshots/main_cases_monorepo/should_ignore_linter_nested_file.snap
crates/biome_service/src/projects.rs

Closes https://github.com/biomejs/biome/issues/7160
N/A

fix(core): included files in nested configurations

---

packages/@biomejs/biome/README.fr.md
packages/@biomejs/biome/README.hi.md
packages/@biomejs/biome/README.ja.md
packages/@biomejs/biome/README.kr.md
packages/@biomejs/biome/README.md
packages/@biomejs/biome/README.pt-BR.md
packages/@biomejs/biome/README.ru.md
packages/@biomejs/biome/README.uk.md
packages/@biomejs/biome/README.zh-CN.md
packages/@biomejs/biome/README.zh-TW.md

chore: add Vercel to sponsors

---

.github/workflows/release.yml
.github/workflows/release_cli.yml

See https://github.com/biomejs/docker/pull/8

chore: add repository dispatch to kick off docker image build on release

---

packages/@biomejs/biome/CHANGELOG.md

Fixed 2 broken links in the `@biome` package changelog, the root changelog was already correct.
N/A
N/A

fix(changelog): correct dead links in 2.2

---

crates/biome_js_analyze/src/lint/correctness/no_undeclared_dependencies.rs

Addresses https://github.com/biomejs/biome/issues/6733
Users often struggle to understand when to apply the rule. We've had multiple issues. It seems we don't have to explain what this rule is for, and what it doesn't cover.
This PR attempts to clarify that. cc @arendjr 
N/A
This PR

docs(lint): improve noUndeclaredDependencies

---

crates/biome_js_analyze/src/lint/correctness/no_unused_private_class_members.rs

This PR removes some allocations by using iterators.
I also replaced the `FxHashSet` with a `Vec` because it is not possible to collect twice the same node.
Everything should be green.
No behavioral changes/

refactor(noUnusedPrivateClassMembers): avoid some allocations

---

crates/biome_css_parser/src/syntax/at_rule/keyframes.rs
crates/biome_json_formatter/tests/language.rs
rust-toolchain.toml

Upgrade to the latest version of Rust, and apply new clippies.
CI should pass

chore: upgrade to rust 1.90.0

---

crates/biome_js_analyze/src/lint/performance/no_unwanted_polyfillio.rs

I respond to [this Issue](https://github.com/biomejs/website/issues/2305).
Closes https://github.com/biomejs/website/issues/2305
none.
none.

fix: replace domains polyfill.io to Cloudflare
