biomejs/biome

- CHANGELOG.md
- crates/biome_js_analyze/src/lib.rs
- crates/biome_js_analyze/src/lint/style/use_nodejs_import_protocol.rs
- crates/biome_js_analyze/src/services/manifest.rs
- crates/biome_js_analyze/tests/specs/style/useNodejsImportProtocol/invalid.js.snap
- crates/biome_js_analyze/tests/specs/style/useNodejsImportProtocol/validDep.js
- crates/biome_js_analyze/tests/specs/style/useNodejsImportProtocol/validDep.js.snap
- crates/biome_js_analyze/tests/specs/style/useNodejsImportProtocol/validDep.package.json
- crates/biome_project/src/lib.rs
- crates/biome_project/src/node_js_project/mod.rs
- crates/biome_project/src/node_js_project/package_json.rs
Closes https://github.com/biomejs/biome/issues/3066
> fix(linter): `useNodejsImportProtocol` takes in dependencies in consideration

- crates/biome_grit_patterns/src/errors.rs
- crates/biome_grit_patterns/src/grit_binding.rs
- crates/biome_grit_patterns/src/grit_context.rs
- crates/biome_grit_patterns/src/grit_node_patterns.rs
- crates/biome_grit_patterns/src/grit_query.rs
- crates/biome_grit_patterns/src/grit_resolved_pattern.rs
- crates/biome_grit_patterns/src/grit_target_language.rs
- crates/biome_grit_patterns/src/grit_target_language/js_target_language.rs
- crates/biome_grit_patterns/src/grit_target_node.rs
- crates/biome_grit_patterns/src/lib.rs
- crates/biome_grit_patterns/src/pattern_compiler.rs
- crates/biome_grit_patterns/src/pattern_compiler/call_compiler.rs
- crates/biome_grit_patterns/src/pattern_compiler/node_like_compiler.rs
- crates/biome_grit_patterns/src/pattern_compiler/predicate_call_compiler.rs
- crates/biome_grit_patterns/src/pattern_compiler/predicate_compiler.rs
- crates/biome_grit_patterns/tests/quick_test.rs
- crates/biome_service/src/workspace/server.rs
I feel I will have a pretty major announcement coming up soon, since this PR brings the bindings in a state where an actual Grit query can execute and match against an arbitrary JS snippet. The pattern execution appears to return a correct `true` or `false` result indicating whether the query matched or not. Also, if I change the pattern in the quick test to use the rewrite operator (`=>`) I can see the Grit engine produce an `Effect`, which is a data structure describing the rewrite that should take place, so this is really exciting.
What does _not_ work yet, is extracting the ranges where matches are found when I don't use a rewrite operator. I suppose I could also try modifying the query to include an empty rewrite and extract the range from the `Effect`, but  maybe @morgante knows an …
> chore(grit): implement node-like compilers + fixes

- Cargo.lock
- crates/biome_analyze/src/diagnostics.rs
- crates/biome_analyze/src/lib.rs
- crates/biome_js_analyze/src/lib.rs
- crates/biome_service/Cargo.toml
- crates/biome_service/src/diagnostics.rs
- crates/biome_service/src/file_handlers/css.rs
- crates/biome_service/src/file_handlers/graphql.rs
- crates/biome_service/src/file_handlers/javascript.rs
This PR enables linting of Graphql files inside our workspace. This won't change anything to the user, so it's safe to merge this PR.
Once merged, I will update the playground so it can show diagnostics from linting.
Also, I started seeing a lot of repeated code that we could refactor and make generic.
CI should pass
> feat: enable linting for graphql

- crates/biome_css_parser/tests/spec_test.rs
- crates/biome_service/src/file_handlers/css.rs
- crates/biome_service/src/settings.rs
This changes the CSS parser options to use `Option<bool>` for better semantics when dealing with default values and fallbacks.
basically the same change as #3272
Ci should pass
> refactor(parse/css): change fields in `CssParserSettings` to `Option`

- CHANGELOG.md
- crates/biome_js_analyze/src/lint/complexity/use_arrow_function.rs
- crates/biome_js_analyze/tests/specs/complexity/useArrowFunction/invalid.tsx
- crates/biome_js_analyze/tests/specs/complexity/useArrowFunction/invalid.tsx.snap
When JSX is enabled, the code fix should transform this:
```tsx
const f1 = function<T> (x: T): T {
return x;
}
```
into this:
```tsx
const f1 = <T,>(x: T): T => x
```
instead of this:
```tsx
const f1 = <T>(x: T): T => x
```
Otherwise the parser will treat `<T>` as a JSX tag.
Closes #3292
I added test cases.
> fix(lint/use_arrow_function): add a trailing comma to single type parameter when JSX is enabled

- crates/biome_graphql_parser/src/parser/argument.rs
- crates/biome_graphql_parser/tests/graphql_test_suite/err/directive.graphql.snap
- crates/biome_graphql_parser/tests/graphql_test_suite/err/operation.graphql
- crates/biome_graphql_parser/tests/graphql_test_suite/err/operation.graphql.snap
- crates/biome_graphql_parser/tests/graphql_test_suite/err/selection_set.graphql
- crates/biome_graphql_parser/tests/graphql_test_suite/err/selection_set.graphql.snap
- crates/biome_graphql_parser/tests/graphql_test_suite/ok/value.graphql
- crates/biome_graphql_parser/tests/graphql_test_suite/ok/value.graphql.snap
We made assumption that an '{' token must not appear inside an arguments list, but this isn't true since an object value containing an '{' token is an valid argument
> fix(graphql_parser): parse object value in list

- CHANGELOG.md
- crates/biome_json_syntax/src/file_source.rs
- xtask/codegen/src/language_kind.rs
Add turbo.json to well known jsonc files.
Also remove yaml alias from error as aliases of other languages aren't included either
> feat(core): include turbo into well known jsonc

- crates/biome_cli/src/commands/check.rs
- crates/biome_cli/src/commands/format.rs
- crates/biome_cli/src/execute/migrate/prettier.rs
- crates/biome_cli/tests/cases/editorconfig.rs
- crates/biome_cli/tests/cases/overrides_formatter.rs
- crates/biome_cli/tests/snapshots/main_cases_editorconfig/should_use_editorconfig.snap
- crates/biome_cli/tests/snapshots/main_cases_editorconfig/should_use_editorconfig_enabled_from_biome_conf.snap
- crates/biome_cli/tests/snapshots/main_commands_check/check_help.snap
- crates/biome_cli/tests/snapshots/main_commands_ci/ci_help.snap
- crates/biome_cli/tests/snapshots/main_commands_format/format_help.snap
- crates/biome_cli/tests/snapshots/main_commands_migrate_prettier/prettier_migrate.snap
- crates/biome_cli/tests/snapshots/main_commands_migrate_prettier/prettier_migrate_end_of_line.snap
- crates/biome_cli/tests/snapshots/main_commands_migrate_prettier/prettier_migrate_fix.snap
- crates/biome_cli/tests/snapshots/main_commands_migrate_prettier/prettier_migrate_jsonc.snap
- crates/biome_cli/tests/snapshots/main_commands_migrate_prettier/prettier_migrate_overrides.snap
- crates/biome_cli/tests/snapshots/main_commands_migrate_prettier/prettier_migrate_with_ignore.snap
- crates/biome_cli/tests/snapshots/main_commands_migrate_prettier/prettier_migrate_write.snap
- crates/biome_cli/tests/snapshots/main_commands_migrate_prettier/prettier_migrate_write_biome_jsonc.snap
- crates/biome_cli/tests/snapshots/main_commands_migrate_prettier/prettier_migrate_write_packagejson.snap
- crates/biome_cli/tests/snapshots/main_commands_migrate_prettier/prettier_migrate_write_with_ignore_file.snap
- crates/biome_cli/tests/snapshots/main_commands_migrate_prettier/prettierjson_migrate_write.snap
- crates/biome_configuration/src/diagnostics.rs
- crates/biome_configuration/src/editorconfig.rs
- crates/biome_configuration/src/formatter.rs
- crates/biome_service/src/configuration.rs
- crates/biome_service/src/settings.rs
- crates/biome_service/tests/invalid/formatter_extraneous_field.json.snap
- crates/biome_service/tests/invalid/formatter_quote_style.json.snap
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
- packages/@biomejs/biome/configuration_schema.json
This PR reenables editorconfig support, and additionally adds a cli flag, `--use-editorconfig`, to control whether or not it's enabled.
related to: #1724
I've reenabled the unit tests that I wrote for this.
> feat(editorconfig): reenable editorconfig support, add cli flag to disable it

- CHANGELOG.md
- crates/biome_js_analyze/src/lint/a11y/use_alt_text.rs
- crates/biome_js_analyze/tests/specs/a11y/useAltText/area.jsx
- crates/biome_js_analyze/tests/specs/a11y/useAltText/area.jsx.snap
- crates/biome_js_analyze/tests/specs/a11y/useAltText/img.jsx
- crates/biome_js_analyze/tests/specs/a11y/useAltText/img.jsx.snap
- crates/biome_js_analyze/tests/specs/a11y/useAltText/input.jsx
- crates/biome_js_analyze/tests/specs/a11y/useAltText/input.jsx.snap
- crates/biome_js_analyze/tests/specs/a11y/useAltText/object.jsx
- crates/biome_js_analyze/tests/specs/a11y/useAltText/object.jsx.snap
Fixes https://github.com/biomejs/biome/issues/3316
I've added test cases with `aria-hidden` to all useAltText tests.
> fix(lint): don't request alt text for elements hidden from assistive technologies

- CHANGELOG.md
- crates/biome_js_analyze/src/lint/complexity/no_useless_fragments.rs
- crates/biome_js_analyze/tests/specs/complexity/noUselessFragments/issue_3149.jsx
- crates/biome_js_analyze/tests/specs/complexity/noUselessFragments/issue_3149.jsx.snap
Closes #3149 
This PR fixes a crash that occurs when applying the quick fix for the `noUselessFragments` rule in certain JSX contexts.
```jsx
function fn(member) {
fn(<>{member.expression()}</>);
(<>{1}</>).toString();
}
```
The `action` in the `noUselessFragments` rule has been updated to use the `expression` node of a `JsxExpressionChild` directly without any additional wrapping.
The special handling for `JsIdentifierExpression` has also been removed as it is no longer necessary.
Add snapshot test cases, build and execute the binary in [the reprodcution repo](https://github.com/simon-paris/biome-fragment-crash-repro).
> fix(lint): prevent crash when applying `noUselessFragments` unsafe fixes

- crates/biome_cli/tests/cases/editorconfig.rs
- crates/biome_cli/tests/snapshots/main_cases_editorconfig/should_apply_path_overrides.snap
- crates/biome_cli/tests/snapshots/main_cases_editorconfig/should_have_cli_override_editorconfig.snap
- crates/biome_cli/tests/snapshots/main_cases_editorconfig/should_use_editorconfig_check.snap
- crates/biome_cli/tests/snapshots/main_cases_editorconfig/should_use_editorconfig_check_enabled_from_biome_conf.snap
This adds some more unit tests for editorconfig support. The goal for this PR is to add all the tests needed for sufficient coverage of editorconfig support.
A final subsequent PR from me will update the changelog and close the editorconfig issue.
related to: #1724
> test(editorconfig): additional tests for editorconfig support

- CHANGELOG.md
- crates/biome_js_analyze/src/lint/complexity/no_excessive_nested_test_suites.rs
- crates/biome_js_analyze/tests/specs/complexity/noExcessiveNestedTestSuites/valid.js
- crates/biome_js_analyze/tests/specs/complexity/noExcessiveNestedTestSuites/valid.js.snap
This covers an additional edge case that I didn't account for initially in #2793.
related: #2599
added new snapshot tests
> fix(lint/noExcessiveNestedTestSuites): more thoroughly check if describe call is an object member

- crates/biome_cli/src/execute/migrate/eslint.rs
- crates/biome_cli/tests/commands/migrate_eslint.rs
- crates/biome_cli/tests/snapshots/main_commands_migrate_eslint/migrate_eslintrc.snap
- crates/biome_cli/tests/snapshots/main_commands_migrate_eslint/migrate_no_eslint_config_packagejson.snap
I find it not work When I use `biome migrate eslint` with a .eslintrc file
Support .eslintrc and tested locally
Works for me
> feat: support eslint config .eslintrc on migrate

- CHANGELOG.md
- crates/biome_js_analyze/src/lint/style/use_filenaming_convention.rs
- crates/biome_js_analyze/tests/specs/style/useFilenamingConvention/_404.tsx.snap
- crates/biome_js_analyze/tests/specs/style/useFilenamingConvention/안녕하세요.js.snap
Fix #3353
By fixing this issue, we also now accept filenames in [unicase](https://en.wikipedia.org/wiki/Unicase).
This aligns the behavior of `useFilenamingConvention` with the behavior of `useNamingConvention`.
I added two tests.
> refactor(useFilenamingConvention): accept filename in unicase

- CHANGELOG.md
- crates/biome_css_formatter/tests/specs/prettier/css/comments/custom-properties.css.snap
- crates/biome_css_formatter/tests/specs/prettier/css/comments/selectors.css.snap
- crates/biome_css_formatter/tests/specs/prettier/css/postcss-plugins/postcss-nested-props.css.snap
- crates/biome_css_formatter/tests/specs/prettier/css/variables/apply-rule.css.snap
- crates/biome_css_parser/src/parser.rs
- crates/biome_css_parser/src/syntax/block/declaration_or_rule_list_block.rs
- crates/biome_css_parser/src/syntax/block/mod.rs
- crates/biome_css_parser/tests/css_test_suite/ok/nesting/nesting_1.css
- crates/biome_css_parser/tests/css_test_suite/ok/nesting/nesting_1.css.snap
- crates/biome_css_parser/tests/spec_test.rs
Fix https://github.com/biomejs/biome/issues/3287
Details see https://github.com/biomejs/biome/issues/3287
`cargo test`
> fix(css_parser): fix the CSS parser doesn't support nested selectors with pseudo-classes #3287

- CHANGELOG.md
- crates/biome_cli/src/commands/format.rs
- crates/biome_cli/src/commands/lint.rs
- crates/biome_cli/src/commands/mod.rs
- crates/biome_cli/src/commands/rage.rs
- crates/biome_cli/src/lib.rs
- crates/biome_cli/tests/cases/graphql.rs
- crates/biome_cli/tests/cases/mod.rs
- crates/biome_cli/tests/snapshots/main_cases_graphql/format_and_write_graphql_files.snap
- crates/biome_cli/tests/snapshots/main_cases_graphql/format_graphql_files.snap
- crates/biome_cli/tests/snapshots/main_cases_graphql/lint_single_rule.snap
- crates/biome_cli/tests/snapshots/main_commands_check/check_help.snap
- crates/biome_cli/tests/snapshots/main_commands_ci/ci_help.snap
- crates/biome_cli/tests/snapshots/main_commands_rage/with_linter_configuration.snap
- crates/biome_configuration/src/graphql.rs
- crates/biome_configuration/src/lib.rs
- crates/biome_graphql_formatter/tests/spec_test.rs
- crates/biome_service/Cargo.toml
- crates/biome_service/src/file_handlers/graphql.rs
- crates/biome_service/src/file_handlers/mod.rs
- crates/biome_service/src/settings.rs
- crates/biome_wasm/Cargo.toml
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
- packages/@biomejs/biome/configuration_schema.json
This PR enabled GraphQL linting via CLI, it adds the relative configuration to `biome.json` file.
I added tests for formatting and linting
> feat: enable GraphQL linting

- crates/biome_analyze/src/rule.rs
- crates/biome_configuration/src/linter/rules.rs
- crates/biome_diagnostics_categories/src/categories.rs
- crates/biome_graphql_analyze/src/lint/nursery.rs
- crates/biome_graphql_analyze/src/lint/nursery/no_duplicated_fields.rs
- crates/biome_graphql_analyze/src/lint/nursery/use_deprecated_reason.rs
- crates/biome_graphql_analyze/src/options.rs
- crates/biome_graphql_analyze/tests/specs/nursery/noDuplicatedFields/invalid.graphql
- crates/biome_graphql_analyze/tests/specs/nursery/noDuplicatedFields/invalid.graphql.snap
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
- packages/@biomejs/biome/configuration_schema.json
Implement [no-duplicate-fields](https://the-guild.dev/graphql/eslint/rules/no-duplicate-fields) lint rule from `graphql-eslint`
All tests should pass.
> feat(graphql_analyze): noDuplicatedFields

- .github/workflows/repository_dispatch.yml
Fix a regression introduced by  #3350
#3350 removed the crate feature `graphql`. This makes fail the GH action `repository_dispatch`.
The `repository_dispatch` action should not fail.
> ci(repository_dispatch): fix action

- crates/biome_js_analyze/tests/specs/correctness/noInvalidUseBeforeDeclaration/invalid.js.snap
- crates/biome_js_analyze/tests/specs/correctness/noInvalidUseBeforeDeclaration/invalidBindingPattern.js.snap
- crates/biome_js_analyze/tests/specs/suspicious/noGlobalAssign/invalid.js.snap
- crates/biome_js_semantic/src/events.rs
- crates/biome_js_semantic/src/semantic_model/builder.rs
- crates/biome_js_semantic/src/semantic_model/closure.rs
- crates/biome_js_semantic/src/semantic_model/import.rs
- crates/biome_js_semantic/src/semantic_model/model.rs
- crates/biome_js_semantic/src/tests/assertions.rs
We used node ranges to identify scopes and bindings.
Int he past, this created some confusion because devs expected scopes and bindings to be identified by their trimmed ranges.
This PR makes the switch to trimmed ranges.
As a side effect, the diagnostics of some rules and coverage are improved :)
CI must pass.
> refactor(js_semantic): use trimmed range to identify scopes and bindings

- crates/biome_js_semantic/src/semantic_model/binding.rs
- crates/biome_js_semantic/src/semantic_model/builder.rs
- crates/biome_js_semantic/src/semantic_model/closure.rs
- crates/biome_js_semantic/src/semantic_model/globals.rs
- crates/biome_js_semantic/src/semantic_model/model.rs
- crates/biome_js_semantic/src/semantic_model/reference.rs
- crates/biome_js_semantic/src/semantic_model/scope.rs
This PR introduces minor changes for the semantic model.
It separates binding and scope nodes to make easier refactoring around the way we identify a scope and a binding.
I also change all usize to u32.
CI must pass
> refactor(js_semantic): separate binding and scope nodes

- xtask/codegen/src/language_kind.rs
This refactors how most of the functions on `LanguageKind` are defined to be generated from a macro. The purpose is to make it less tedious, and reduce the potential for merge conflicts when implementing new languages. Since we'll likely be implementing a few new languages for HTML-ish language support (#1726), I figured this would be useful. Ideally, simply adding an entry to `enum LanguageKind` should be enough, but doing that requires a proc macro.
Everything compiles, and inlining the macros with rust analyzer produces the same output as before the refactor
> refactor(codegen): generate most functions on `LanguageKind` with a macro

- crates/biome_configuration/src/linter/rules.rs
- crates/biome_diagnostics_categories/src/categories.rs
- crates/biome_js_analyze/src/lint/nursery.rs
- crates/biome_js_analyze/src/lint/nursery/use_strict_mode.rs
- crates/biome_js_analyze/src/options.rs
- crates/biome_js_analyze/tests/spec_tests.rs
- crates/biome_js_analyze/tests/specs/nursery/useStrictMode/invalid.js
- crates/biome_js_analyze/tests/specs/nursery/useStrictMode/invalid.js.snap
- crates/biome_js_analyze/tests/specs/nursery/useStrictMode/invalid.package.json
- crates/biome_js_analyze/tests/specs/nursery/useStrictMode/valid.js
- crates/biome_js_analyze/tests/specs/nursery/useStrictMode/valid.js.snap
- crates/biome_js_syntax/src/file_source.rs
- crates/biome_project/src/lib.rs
- crates/biome_project/src/node_js_project/mod.rs
- crates/biome_project/src/node_js_project/package_json.rs
- crates/biome_service/src/workspace/server.rs
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
- packages/@biomejs/biome/configuration_schema.json
Adds a new rule called `useStrictMode` that enforces the use of `"use strict"` inside script files (CJS). 
This PR updates the logic of the workspace to "guess" the module kind by reading the `type` field inside the manifest.
If the manifest has `"commonjs"`, all `.js` files are marked as scripts.
I know that `commonjs` is the default value, but nowadays, nobody uses it, they use some sort of bundler and transpiler to handle the transformation of the code. I'd be happy to change the default value to commonjs if you think it's the correct approach.
Added tests
> feat(lint): add rule `useStrictMode`

- crates/biome_js_semantic/src/events.rs
- crates/biome_js_semantic/src/semantic_model/builder.rs
- crates/biome_js_semantic/src/tests/assertions.rs
- xtask/coverage/src/symbols/msts.rs
Previous PR switched from range to range start to identify a declaration.
This PR spread the change even further by using range start to identify the declaration in a read, write and export.
CI must pass.
> refactor(js_semantic): use range start to identify the declaration in read/write

- crates/biome_js_analyze/src/lint/style/use_naming_convention.rs
- crates/biome_js_analyze/src/utils/regex.rs
Improve error messages for invalid restricted regexes.
This is not currently testable because JSON serialization doesn't unescape `\\`.
> refactor(js_analyze): improve restricted regex error meesages

- crates/biome_js_semantic/src/semantic_model/binding.rs
- crates/biome_js_semantic/src/semantic_model/builder.rs
- crates/biome_js_semantic/src/semantic_model/closure.rs
- crates/biome_js_semantic/src/semantic_model/model.rs
- crates/biome_js_semantic/src/semantic_model/reference.rs
- crates/biome_js_semantic/src/semantic_model/scope.rs
This is a follow-up of #3408
This PR aims to improve the code readability.
I renamed `BindingIndex` and `ReferenceIndex` into `BindingId` and `ReferenceId` and added the same methods as `ScopeId`.
Note that I kept the internal representation `u32` because we don't need a niche optimization for them.
Also, I removed `SemanticModelScopeReference` that is  a duplicate of `ReferenceId`.
CI must pass.
> refactor(js_semantic): minor changes

- crates/biome_grit_patterns/src/grit_binding.rs
- crates/biome_grit_patterns/tests/specs/ts/identifier.snap
Fixed an issue that caused line and column numbers in ranges to be incorrect.
> fix(grit): correct calculation of line and column numbers

- crates/biome_js_analyze/src/lint/correctness/no_invalid_use_before_declaration.rs
- crates/biome_js_analyze/src/lint/style/no_arguments.rs
- crates/biome_js_analyze/src/lint/style/use_for_of.rs
- crates/biome_js_analyze/src/lint/suspicious/no_global_assign.rs
- crates/biome_js_analyze/src/react/hooks.rs
- crates/biome_js_semantic/src/events.rs
- crates/biome_js_semantic/src/semantic_model/binding.rs
- crates/biome_js_semantic/src/semantic_model/builder.rs
- crates/biome_js_semantic/src/semantic_model/closure.rs
- crates/biome_js_semantic/src/semantic_model/globals.rs
- crates/biome_js_semantic/src/semantic_model/model.rs
- crates/biome_js_semantic/src/semantic_model/reference.rs
- crates/biome_js_semantic/src/semantic_model/scope.rs
- crates/biome_js_semantic/src/tests/assertions.rs
This PR reduces the size of the semantic data models.
Also, I made some cleanup.
CI must pass.
> refactor(js_semantic): reduce semantic data size and make some cleanup

- crates/biome_css_parser/src/syntax/at_rule/value.rs
- crates/biome_css_parser/src/syntax/css_modules.rs
- crates/biome_css_parser/src/syntax/selector/pseudo_class/function_selector.rs
- crates/biome_css_parser/tests/css_test_suite/error/at_rule/at_rule_keyframes/disabled_css_module/at_rule_keyframe_disabled_css_modules.css.snap
- crates/biome_css_parser/tests/css_test_suite/error/at_rule/value/at_rule_value_disabled.css.snap
- crates/biome_css_parser/tests/css_test_suite/error/property/composes/disabled/composes_error_disabled.css.snap
- crates/biome_css_parser/tests/css_test_suite/error/selector/pseudo_class/pseudo_class_function_selector/disabled/pseudo_class_function_selector_disabled.css.snap
> fix(biome-css-parser): incorrect option name in hint when using `:global` in CSS module

- CHANGELOG.md
- crates/biome_js_parser/src/syntax/stmt.rs
- crates/biome_js_parser/test_data/inline/ok/break_stmt.js
- crates/biome_js_parser/test_data/inline/ok/break_stmt.rast
Fixes https://github.com/biomejs/biome/issues/3410
> fix(js_parser): correctly parse break statements containing keywords

- .github/workflows/release_knope.yml
- knope.toml
- packages/@biomejs/backend-jsonrpc/package.json
- packages/@biomejs/biome/package.json
- packages/@biomejs/cli-darwin-arm64/package.json
- packages/@biomejs/cli-darwin-x64/package.json
- packages/@biomejs/cli-linux-arm64-musl/package.json
- packages/@biomejs/cli-linux-arm64/package.json
- packages/@biomejs/cli-linux-x64-musl/package.json
- packages/@biomejs/cli-linux-x64/package.json
- packages/@biomejs/cli-win32-arm64/package.json
- packages/@biomejs/cli-win32-x64/package.json
- packages/@biomejs/wasm-bundler/package.json
- packages/@biomejs/wasm-nodejs/package.json
- packages/@biomejs/wasm-web/package.json
- pnpm-lock.yaml
- scripts/update-manifests.mjs
To avoid disruptions to the current build, I crated a new script.
I run the new script locally, and it works as expected. These packages aren't used yet during the release, so the won't affect anything yet
> ci: add script to correctly update packages during the release

- CHANGELOG.md
- crates/biome_js_formatter/src/ts/types/infer_type.rs
- crates/biome_js_formatter/tests/specs/ts/type/injfer_in_intersection.ts
- crates/biome_js_formatter/tests/specs/ts/type/injfer_in_intersection.ts.snap
- crates/biome_js_formatter/tests/specs/ts/type/injfer_in_union.ts
- crates/biome_js_formatter/tests/specs/ts/type/injfer_in_union.ts.snap
Fix #3419
This also handle `infer` in intersections.
I added two tests.
> fix(js_formatter): keep parens around infer in unions/intersections

- crates/biome_js_analyze/src/lint/nursery/use_consistent_curly_braces.rs
This is a small fix.
As part of reviewing the `jsx` code, I discovered the following. I believe it should be specified as `jsx`.
```
/// ### Valid
///
/// ```js // should be jsx?
/// <>
///     <Foo>Hello world</Foo>
///     <Foo foo="bar" />
///     <Foo foo={5} />
///     <Foo foo={<Bar />} />
/// </>
/// ```
```
> fix(lint/useConsistentCurlyBraces): specify correct language type

- crates/biome_analyze/src/lib.rs
- crates/biome_js_analyze/src/lint/nursery/no_irregular_whitespace.rs
- crates/biome_js_analyze/tests/specs/nursery/noIrregularWhitespace/invalid.js.snap
- xtask/rules_check/Cargo.toml
- xtask/rules_check/src/lib.rs
This PR fixes the `rules_check` script to correctly return an error when a snippet emits multiple diagnostics. I updated the `no_irregular_whitespace` docs because it was silently failing.
CI should pass
> chore: fix rules check snippet to emit an error code

- crates/biome_js_analyze/src/utils/rename.rs
- crates/biome_js_analyze/tests/specs/style/useNamingConvention/invalidLocalVariable.js
- crates/biome_js_analyze/tests/specs/style/useNamingConvention/invalidLocalVariable.js.snap
Fix #3050
I also took the opportunity of removing some legacy code and improving the code:
- Trivias are already transferred by `replace_token`: we don't need to do that manually.
- We now have `AnyJsIdentifierUsage` to retrieve the name token.
- I added more comments to make the code more comprehensible
I added a test in the `useNamingConvention` rule.
> fix(js_analyze): handle shorthand property renaming

- CHANGELOG.md
- crates/biome_js_analyze/src/lint/nursery/use_adjacent_overload_signatures.rs
- crates/biome_js_analyze/src/lint/suspicious/no_misleading_instantiator.rs
- crates/biome_js_analyze/src/lint/suspicious/no_then_property.rs
- crates/biome_js_analyze/tests/specs/nursery/useAdjacentOverloadSignatures/valid.ts
- crates/biome_js_analyze/tests/specs/nursery/useAdjacentOverloadSignatures/valid.ts.snap
- crates/biome_js_analyze/tests/specs/suspicious/noMisleadingInstantiator/valid.ts
- crates/biome_js_analyze/tests/specs/suspicious/noMisleadingInstantiator/valid.ts.snap
- crates/biome_js_syntax/src/expr_ext.rs
Fix #3309
I introduced a new enum `ClassMemberName` that is returned by `AnyJsClassMemberName::name`.
This allows to carry the information if the name was #private or public.
I had to refactor the code of `useAdjacentOverloadSignatures` to accommodate with this change.
I also fixed `noMisleadingInstantiator` that previously reported `class C { #new(): C {} }`.
I added tests.
> fix(useAdjacentOverloadSignatures): don't report #private and public members with same name

- crates/biome_js_analyze/src/react/hooks.rs
- crates/biome_js_analyze/tests/specs/correctness/useHookAtTopLevel/valid.js
- crates/biome_js_analyze/tests/specs/correctness/useHookAtTopLevel/valid.js.snap
Jest has some functions that our heuristics flag as a react hook. This PR makes it so biome doesn't flag `jest.useFakeTimers` and `jest.useRealTimers` as react hooks.
fixes #3337
Honestly, I don't exactly have a clean reproduction for the linked issue.
> fix(lint/useHookAtTopLevel): don't flag jest function calls that look like hooks

- CHANGELOG.md
- crates/biome_cli/src/cli_options.rs
- crates/biome_cli/src/execute/mod.rs
- crates/biome_cli/src/execute/process_file/format.rs
- crates/biome_cli/src/execute/process_file/lint.rs
- crates/biome_cli/src/execute/traverse.rs
- crates/biome_cli/tests/cases/diagnostics.rs
- crates/biome_cli/tests/snapshots/main_commands_check/check_help.snap
- crates/biome_cli/tests/snapshots/main_commands_ci/ci_help.snap
- crates/biome_cli/tests/snapshots/main_commands_format/format_help.snap
- crates/biome_cli/tests/snapshots/main_commands_lint/lint_help.snap
- crates/biome_cli/tests/snapshots/main_commands_migrate/migrate_help.snap
- crates/biome_cli/tests/snapshots/main_commands_rage/rage_help.snap
Closes https://github.com/biomejs/biome/issues/3450
Following https://github.com/biomejs/biome/discussions/3060, I added a new `none` value that can be passed to `--max-diagnostics`, which sets the limit to `u32::MAX`. I believe this limit is unreachable in most of the projects.
Also, when a reporter that isn't the default is passed, we ignore `--max-diagnostics` and set the its default to the max value. 
> feat(cli): lift limit of max diagnostics

- CHANGELOG.md
- crates/biome_js_analyze/src/lint/style/use_naming_convention.rs
- crates/biome_js_analyze/tests/specs/style/useNamingConvention/validCustomStyleAbstractClass.options.json
- crates/biome_js_analyze/tests/specs/style/useNamingConvention/validCustomStyleAbstractClass.ts
- crates/biome_js_analyze/tests/specs/style/useNamingConvention/validCustomStyleAbstractClass.ts.snap
- crates/biome_js_syntax/src/modifier_ext.rs
Fix https://github.com/biomejs/biome/discussions/1725#discussioncomment-10090033
This PR fixes two bugs:
- We erroneously rejected a valid configuration
- We didn't set the abstract modifier flag for abstract classes
I added a non-regression test.
> fix(useNamingConvention): handle custom conventions on abstract classes

- crates/biome_service/src/file_handlers/css.rs
- crates/biome_service/src/file_handlers/graphql.rs
- crates/biome_service/src/file_handlers/javascript.rs
- crates/biome_service/src/file_handlers/json.rs
- crates/biome_service/src/file_handlers/mod.rs
A simple refactor to add Syntax rules to the `lint` function of each language automatically. Syntax rules are configuration free, so they can be added without a particular business logic.
Current tests should pass
> refactor(core): register syntax rules via visitor

- Cargo.lock
- Cargo.toml
- crates/biome_graphql_semantic/Cargo.toml
- crates/biome_graphql_semantic/src/events.rs
- crates/biome_graphql_semantic/src/lib.rs
- crates/biome_graphql_semantic/src/semantic_model/binding.rs
- crates/biome_graphql_semantic/src/semantic_model/builder.rs
- crates/biome_graphql_semantic/src/semantic_model/mod.rs
- crates/biome_graphql_semantic/src/semantic_model/model.rs
- crates/biome_graphql_semantic/src/semantic_model/reference.rs
- crates/biome_graphql_semantic/src/tests/directive.rs
- crates/biome_graphql_semantic/src/tests/enum.rs
- crates/biome_graphql_semantic/src/tests/fragment.rs
- crates/biome_graphql_semantic/src/tests/interface.rs
- crates/biome_graphql_semantic/src/tests/mod.rs
- crates/biome_graphql_semantic/src/tests/object.rs
- crates/biome_graphql_semantic/src/tests/operation.rs
- crates/biome_graphql_semantic/src/tests/scalar.rs
- crates/biome_graphql_semantic/src/tests/union.rs
- knope.toml
Depends on https://github.com/biomejs/biome/pull/3427
Build a Semantic model for GraphQL from AST.
Unlike in JS, in GraphQL, a variable can be referenced in a fragment, which in turn can be referenced by multiple operations, and then defined in those operations. This results in a variable being potentially defined in multiple locations.
```rust
fragment HeroDetails on Character {
name(startWith: $start)
}
query HeroWithH($start: String = "H") {
...HeroDetails
}
query HeroWithO($start: String = "O") {
...HeroDetails
}
```
In this case, the $start variable is defined in both the `HeroWithH` and `HeroWithO` variable definitions, and referenced at `(startWith: $start)` in `HeroDetails` fragment.
To address this, each operation and fragment will be associated with a scope. The scope will keep …
> feat(graphql_semantic): build semantic model from AST

- crates/biome_cli/src/execute/process_file/lint.rs
- crates/biome_cli/src/execute/std_in.rs
- crates/biome_cli/tests/commands/lint.rs
- crates/biome_cli/tests/snapshots/main_commands_lint/lint_only_write.snap
- crates/biome_cli/tests/snapshots/main_commands_lint/lint_skip_write.snap
- crates/biome_lsp/src/handlers/analysis.rs
- crates/biome_service/src/file_handlers/css.rs
- crates/biome_service/src/file_handlers/graphql.rs
- crates/biome_service/src/file_handlers/javascript.rs
- crates/biome_service/src/file_handlers/mod.rs
- crates/biome_service/src/workspace.rs
- crates/biome_service/src/workspace/server.rs
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
> fix(lint): allow only/skip filter when --write is passed

- crates/biome_analyze/src/lib.rs
- crates/biome_configuration/src/linter/mod.rs
- crates/biome_service/src/file_handlers/css.rs
- crates/biome_service/src/file_handlers/graphql.rs
- crates/biome_service/src/file_handlers/javascript.rs
- crates/biome_service/src/file_handlers/json.rs
- crates/biome_service/src/file_handlers/mod.rs
This PR is just a refactor to make the linting code more DRY. It uses the `RegistryVisitor` pattern, it accepts the `LintParams` type and emits the enabled/disabled rules based on the configuration.
I will attempt to make the code more DRY with other PRs.
The current tests should pass
> refactor(core): register rules using visitor pattern

- crates/biome_js_formatter/report.md
- crates/biome_js_formatter/report_incompatible.md
Update compatibility reports between Biome and Prettier.
> chore(js_formatter): update prettier compat reports

- crates/biome_js_analyze/src/lint/suspicious/no_exports_in_test.rs
- crates/biome_json_analyze/src/utils.rs
- crates/biome_rowan/src/ast/mod.rs
Follow-up of #3520
The PR removes `try_cast_node` (only used once) and replace some `try_cast` with `cast` when it makes sense.
CI must pass.
> refactor: remove try_cast_node

- crates/biome_analyze/CONTRIBUTING.md
By going through the contribution guidelines, I've noticed that changes from #2336 and #1519 were not reflected there:
* allowing multiple sources
* `Source` and `SourceKind` renaming to `RuleSource` and `RuleSourceKind`
* `SourceKind::Same` renaming to `SourceKind::SameLogic`
* default `source_kind` value
> docs: update contributing guidelines according to previous changes

- crates/biome_js_formatter/src/jsx/tag/opening_element.rs
- crates/biome_js_formatter/tests/specs/jsx/bracket_same_line/bracket_same_line.jsx
- crates/biome_js_formatter/tests/specs/jsx/bracket_same_line/bracket_same_line.jsx.snap
```ts
// before format
<div
sx={{
position: 'absolute'
}}
// comment
>
test
</div>
<div
sx={{
position: 'absolute'
}} // comment
>
test
</div>
```
```ts
// after format
```ts
<div
sx={{
position: 'absolute'
}} 
>
// comment
test
</div>
```
There was a bug where when the `bracket same line` option was true and there was a comment after an attribute, that comment would be formatted as the value of the element.
When the comment is //, putting the bracket on the same line would also comment out the closing `>`, so I thought that even if bracket same line is true, we shouldn't break the line when there's a comment after an attribute.
I created a function called `has_last_attribute_comments` in `crates/biome_js_formatter/src/jsx/tag/opening_element.rs` that returns a boolean indicating whether …
```
> fix(formatter): prevent line break when comment follows end of attributes, irrespective of bracketSameLine value

- CHANGELOG.md
- crates/biome_js_analyze/src/lint/style/use_export_type.rs
- crates/biome_js_analyze/tests/specs/style/useExportType/invalid.ts
- crates/biome_js_analyze/tests/specs/style/useExportType/invalid.ts.snap
- crates/biome_js_analyze/tests/specs/style/useExportType/valid.ts
- crates/biome_js_analyze/tests/specs/style/useExportType/valid.ts.snap
Close #3535
An empty `export {}` allows you to force TypeScript to consider a file with no imports and exports as an EcmaScript module.
While `export type {}` is valid, it is more common to use `export {}`.
Users may find it confusing that the linter asks them to convert it to `export type {}`.
Also, a bundler should be able to remove `export {}` as well as `export type {}`.
So it is not so useful to report `export {}`.
> refactor(useExportType): don't report `export {}`

- crates/biome_formatter_test/src/diff_report.rs
- crates/biome_js_formatter/report.md
- crates/biome_js_formatter/report_incompatible.md
Ignore Prettier incompatibility from files that contain only bogus nodes.
I updated the reports.
CI must pass
> chore(js_formatter): ignore files with only bogus nodes for generating prettier compat reports

- .gitattributes
currently the file doesn't have syntax highlighting in github. Marking it in .gitattributes manually tells github to add Dockerfile syntax highlighting to it
> chore: config Dockerfile.benchmark in gitattributes

- crates/biome_css_formatter/src/utils/string_utils.rs
- crates/biome_formatter/src/lib.rs
- crates/biome_formatter/src/token/string.rs
- crates/biome_js_formatter/src/utils/string_utils.rs
While I was working on #3558, I noted a room for improving string utilities.
This PR improves the implementation of the string utilities:
- Reduce an unnecessary lookup (counting the number of characters) when we check the number of quotes inside a string
- Avoid a string allocation when string contents are normalized
- Avoid a string allocation when quotes are normalized
The PR has also the aim of improving performance of string normalization by avoiding `peekable()` and iterating over bytes instead of chars.
The PR also normalizes strings before evaluating if quotes are needed for import attribute keys.
This is a follow-up of #3558.
There is more room for improvements for example to avoid code duplication.
The change are already large in this PR, I prefer to defer them in a follow-up …
> refactor(formatter): improve string normalization

- CHANGELOG.md
- crates/biome_js_analyze/src/lint/style/use_naming_convention.rs
- crates/biome_js_analyze/tests/specs/style/useNamingConvention/invalidStrictPascalCase.ts
- crates/biome_js_analyze/tests/specs/style/useNamingConvention/invalidStrictPascalCase.ts.snap
Fix #3561
I added a non-regression test.
> fix(useNamingConvention): don't suggest empty fixes

- CHANGELOG.md
- crates/biome_js_analyze/src/lint/correctness/no_unused_variables.rs
- crates/biome_js_analyze/src/lint/style/use_naming_convention.rs
- crates/biome_js_analyze/src/lint/suspicious/no_implicit_any_let.rs
- crates/biome_js_analyze/tests/specs/correctness/noUnusedVariables/invalid.d.ts
- crates/biome_js_analyze/tests/specs/correctness/noUnusedVariables/invalid.d.ts.snap
- crates/biome_js_analyze/tests/specs/style/useNamingConvention/invalidGlobal.d.ts
- crates/biome_js_analyze/tests/specs/style/useNamingConvention/invalidGlobal.d.ts.snap
- crates/biome_js_semantic/src/semantic_model/model.rs
This PR makes two changes:
- `useNamingConvention` no longer suggests renaming in declaration files without exports
- `noUnusedVariables` now report unused types in declaration files with at least one export
I added tests.
> fix(useNamingConvention): don't suggest renaming in global declaration files

- crates/biome_cli/src/execute/process_file/lint.rs
- crates/biome_cli/tests/snapshots/main_cases_handle_astro_files/lint_astro_files.snap
- crates/biome_cli/tests/snapshots/main_cases_handle_vue_files/lint_vue_js_files.snap
- crates/biome_cli/tests/snapshots/main_cases_handle_vue_files/lint_vue_ts_files.snap
- crates/biome_cli/tests/snapshots/main_cases_handle_vue_files/vue_compiler_macros_as_globals.snap
- crates/biome_diagnostics/src/serde.rs
When we print diagnostics, previously the spans would be relative to the start of the js code, not to the start of the file. This was causing diagnostics to point to the wrong line for vue, svelte, and astro files.
fixes #3366
Tested manually on some of my own vue/svelte projects. Updated the snapshots.
> fix(cli): apply offsets for htmlish js file sources

- crates/biome_js_analyze/src/lint/style/use_number_namespace.rs
- crates/biome_js_analyze/tests/specs/style/useNumberNamespace/invalid.js.snap
Closes #3578
Updated number namespace rule to show correct `Number.POSITIVE_INFINITY` or `Number.NEGATIVE_INFINITY` type instead of showing invalid `Number.Infinity`
I ran `cargo test use_number_namespace` and then did `cargo insta review` to accept the new snapshot changes.
> fix(lint/useNumberNamespace): show correct message for `Infinity` type

- crates/biome_css_parser/tests/css_test_suite/ok/grit_metavariable/metavar.css
- crates/biome_css_parser/tests/css_test_suite/ok/grit_metavariable/metavar.css.snap
- crates/biome_css_parser/tests/spec_test.rs
- crates/biome_grit_patterns/src/grit_binding.rs
- crates/biome_grit_patterns/src/grit_target_language.rs
- crates/biome_grit_patterns/src/pattern_compiler/snippet_compiler.rs
- crates/biome_grit_patterns/tests/quick_test.rs
- crates/biome_grit_patterns/tests/specs/ts/duplicateVariable.snap
- crates/biome_grit_patterns/tests/specs/ts/duplicateVariable.ts
- crates/biome_js_formatter/src/js/any/name.rs
- crates/biome_js_parser/src/syntax/expr.rs
- crates/biome_js_parser/test_data/inline/ok/metavar.rast
- crates/biome_js_parser/test_data/inline/ok/metavar.ts
- crates/biome_js_syntax/src/generated/nodes.rs
- crates/biome_js_syntax/src/identifier_ext.rs
- crates/biome_parser/src/lexer.rs
- xtask/codegen/js.ungram
Improves the Grit bindings to fix another edge case. Previously, `$fn && fn()` would match `foo && foo()`, but not `foo.bar && foo.bar()`. This fixes the parser so we don't "overfit" towards identifiers.
While debugging I ran into a fun issue, which is that there are two Unicode "mu" characters, uppercase µ (Unicode 181) and lowercase μ (Unicode 956). They're hardly distinguishable (and some monospace fonts don't seem to make _any_ distinction), but 181 (upper case) is the correct one we should use. cc @ah-yu 
With these fixes out of the way, I ran into another `todo!()` regarding equivalence tests, which have now been ported from Grit as well. And lo and behold, `foo.bar && foo.bar()` now matches too :)
Test added.
> fix(grit): equivalence tests + minor fixes

- CHANGELOG.md
- crates/biome_cli/src/commands/mod.rs
- crates/biome_lsp/src/diagnostics.rs
- crates/biome_lsp/src/handlers/analysis.rs
- crates/biome_lsp/src/handlers/rename.rs
- crates/biome_lsp/src/server.rs
- crates/biome_lsp/src/session.rs
- crates/biome_service/src/settings.rs
- crates/biome_service/src/workspace.rs
- crates/biome_service/src/workspace/client.rs
- crates/biome_service/src/workspace/server.rs
- crates/biome_service/src/workspace_types.rs
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
Closes https://github.com/biomejs/biome/issues/3577
The bug: a new project was always created when a configuration was updated.
The fix
- we check if the project we registering is new or not. If not, we return the current key
- we don't throw an error if the manifest isn't found
I took the opportunity to do some minor refactors:
- more trace logging
- print the error in there's a failure inside the LSP
I tested it manually, as I was able to reproduce it locally. Now bug is gone and the Biome LSP doesn't crush anymore
> fix(core): don't create a new project when the configuration changes

- crates/biome_cli/src/reporter/gitlab.rs
This pull request addresses the inconsistency in naming conventions related to GitLab within the codebase. The primary motivation for this change is to improve code readability and maintainability by ensuring that all references to GitLab are consistently capitalized and follow a standardized naming pattern.
This change solves the existing problem where different parts of the code used varying capitalizations for GitLab, which could lead to confusion and reduced clarity for developers working on the project.
There are no specific issues linked to this change, but it aligns with our ongoing effort to improve code quality.
This change involves only renaming, so no functional tests are required. However, the implementation's correctness can be verified by checking that all instances of …
> chore: ensure consistent naming for GitLab-related structs and types

- crates/biome_js_analyze/src/lint/nursery/no_useless_escape_in_regex.rs
- crates/biome_js_analyze/tests/specs/nursery/noUselessEscapeInRegex/invalid.js
- crates/biome_js_analyze/tests/specs/nursery/noUselessEscapeInRegex/invalid.js.snap
- crates/biome_js_analyze/tests/specs/nursery/noUselessEscapeInRegex/valid.js
- crates/biome_js_analyze/tests/specs/nursery/noUselessEscapeInRegex/valid.js.snap
Fix the failing build on the website. See https://github.com/biomejs/website/actions/runs/10282489937/job/28454302319
Actually this caught a bug, because the range should be inclusive.
I added a test to avoid a regression. I also added a test for Unicode characters.
> fix(noUselessEscapeInRegex): handle \9 backreference

- .github/workflows/pull_request.yml
- Cargo.lock
- Cargo.toml
- crates/biome_css_semantic/Cargo.toml
- crates/biome_css_semantic/src/events.rs
- crates/biome_css_semantic/src/lib.rs
- crates/biome_css_semantic/src/semantic_model/builder.rs
- crates/biome_css_semantic/src/semantic_model/mod.rs
- crates/biome_css_semantic/src/semantic_model/model.rs
- knope.toml
This PR introduces the semantic model for css. The first usecase might be these linter rules.
- https://github.com/biomejs/biome/issues/2514
- https://github.com/biomejs/biome/issues/2806
- https://github.com/biomejs/biome/issues/2784
I'll try to supprt more cases and integrate the analyzer in another PR later.
[Playground](https://biomejs.dev/playground/?files.main.css=LgBwAGEAcgBlAG4AdAAgAHsACgAgACAAYwBvAGwAbwByADoAIABiAGwAdQBlADsACgAKACAAIAAuAGMAaABpAGwAZAAgAHsACgAgACAAIAAgAGMAbwBsAG8AcgA6ACAAcgBlAGQAOwAKACAAIAB9AAoAfQA%3D)
```sample.css
.parent {
color: blue;
.child {
color: red;
}
}
```
```
// output
SemanticModel {
data: SemanticModelData {
root: CssRoot {...},
node_by_range: {...},
rules: [
Rule {
selectors: [
Selector {
name: ".parent",
range: 0..7,
specificity: Specificity(
0,
0, …
```
> feat(css_semantic): build semantic model for css

- CHANGELOG.md
- Cargo.lock
- crates/biome_css_analyze/Cargo.toml
- crates/biome_css_analyze/src/lib.rs
- crates/biome_css_analyze/src/services/mod.rs
- crates/biome_css_analyze/src/services/semantic.rs
- crates/biome_css_semantic/src/semantic_model/mod.rs
Add `Semantic<N>` and `SemanticServices` to enable the lint rules to use a semantic model for CSS.
Created the test lint rule and ran the test using `Semantic<>` and `SemanticServices`.
> feat(linter): integrate css semantic model into the analyzer

- crates/biome_cli/src/execute/migrate/prettier.rs
- crates/biome_configuration/src/css.rs
- crates/biome_configuration/src/editorconfig.rs
- crates/biome_configuration/src/formatter.rs
- crates/biome_configuration/src/graphql.rs
- crates/biome_configuration/src/javascript/formatter.rs
- crates/biome_configuration/src/json.rs
- crates/biome_configuration/src/lib.rs
- crates/biome_configuration/src/overrides.rs
- crates/biome_formatter/src/lib.rs
- crates/biome_service/src/settings.rs
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
- packages/@biomejs/biome/configuration_schema.json
This is a minor change that removes `biome_configuration::PlainIndentStyle` and use `biome_formatter::IndentStyle` instead. I am not sure why we had this duplication in the first place. This is certainly for legacy reasons.
Note that removing `Tabs` and `Spaces` from the `FromStr` impl for `biome_formatter::IndentStyle` doesn't break anything because the implementation was not used.
CI must pass.
> refactor: remove PlainIdentStyle

- CHANGELOG.md
- crates/biome_js_analyze/src/lint/suspicious/no_control_characters_in_regex.rs
- crates/biome_js_analyze/src/utils.rs
- crates/biome_js_analyze/tests/specs/suspicious/noControlCharactersInRegex/invalid.js
- crates/biome_js_analyze/tests/specs/suspicious/noControlCharactersInRegex/invalid.js.snap
This PR fixes `noControlCharactersInRegex` by supporting `\uhhhh` in Unicode-aware regexes and by recognizing regexes with the `v` flag as Unicode-aware.
I took the opportunity of improving the code.
There are more room for improvement in a follow-up PR.
> fix(noControlCharactersInRegex): handle \u correctly in Unicode-aware regexes

- CHANGELOG.md
- Cargo.lock
- crates/biome_cli/Cargo.toml
- crates/biome_cli/src/commands/clean.rs
- crates/biome_cli/src/commands/daemon.rs
- crates/biome_cli/src/commands/explain.rs
- crates/biome_cli/src/commands/mod.rs
- crates/biome_cli/src/commands/rage.rs
- crates/biome_cli/src/lib.rs
- crates/biome_cli/src/service/unix.rs
- crates/biome_cli/src/service/windows.rs
- crates/biome_cli/tests/commands/rage.rs
- crates/biome_cli/tests/snapshots/main_commands_lsp_proxy/lsp_proxy_help.snap
- crates/biome_cli/tests/snapshots/main_commands_rage/rage_help.snap
- crates/biome_cli/tests/snapshots/main_commands_rage/rage_ok.snap
- crates/biome_cli/tests/snapshots/main_commands_rage/with_configuration.snap
- crates/biome_cli/tests/snapshots/main_commands_rage/with_formatter_configuration.snap
- crates/biome_cli/tests/snapshots/main_commands_rage/with_jsonc_configuration.snap
- crates/biome_cli/tests/snapshots/main_commands_rage/with_linter_configuration.snap
- crates/biome_cli/tests/snapshots/main_commands_rage/with_malformed_configuration.snap
- crates/biome_cli/tests/snapshots/main_commands_rage/with_server_logs.snap
- crates/biome_console/src/lib.rs
- crates/biome_console/src/utils.rs
- crates/biome_flags/Cargo.toml
- crates/biome_flags/src/lib.rs
Until now, we've had some environment variables, but they were not very well documented, and some were not used at all. 
This PR exposes a new function called `biome_env` inside the `biome_flags` crate, and it exposes three environment variables:
- `BIOME_CONFIG_PATH`: already documented and used.
- `BIOME_LOG_PATH`: where to store the logs. It defaults to a directory that depends on the OS.
- `BIOME_LOG_PREFIX_NAME`: the prefix of the logs, it defaults to `server.log`
New options are added to the `lsp-proxy` an `starts` commands:
- `--log-path`
- `--log-prefix-name`
`BIOME_LOG_DIR` is deprecated because it isn't in line with the naming convention we've been using. We use "path" instead of "dir". 
These variables are added to `lsp-proxy` and `start` CLI commands, too.
These new variables …
> feat(cli): better environment variables

- .github/workflows/main.yml
- .github/workflows/pull_request.yml
- CONTRIBUTING.md
- justfile
`cargo test` seems to be faster than `nextest`, and it's one less tool to install
CI should pass
> ci: use `cargo t` instead of `nextest`

- xtask/codegen/src/generate_new_analyzer_rule.rs
Currently GraphQL new lint rule template is using the old `declare_rule` macro. Additionally, the example included in the template is somewhat misleading (also causes `just new-graphql-lintrule` to fail).
This PR updates the template to use the new macros and provides a better example.
Generate a new lint rule with `just new-graphql-lintrule abc` and confirm that the generated lint rule compiles fine.
> fix(graphql_analyzer): use the correct macro to declare rule

- crates/biome_cli/src/execute/migrate/eslint_any_rule_to_biome.rs
- crates/biome_css_analyze/src/lint/nursery/no_empty_block.rs
- crates/biome_js_analyze/src/lint/nursery/use_focusable_interactive.rs
- crates/biome_js_analyze/src/lint/nursery/use_throw_only_error.rs
- crates/biome_js_analyze/src/lint/suspicious/no_sparse_array.rs
I've noticed, when looking for dead links in website repo, that some source rules have changed names, resulting in 404 links in the website.
`jsx-a11y/interactive-support-focus` -> `jsx-a11y/interactive-supports-focus` (typo ?)
`no-sparse-array` -> `no-sparse-arrays` (typo ?)
`no-empty-block` -> `block-no-empty` (typo ?)
`interactive-support-focus` -> `interactive-supports-focus` (typo ?)
`typescript/no-throw-literal` -> Its now an option inside `typescript/only-throw-error`
Should pass
> fix(lint/sources): update sources renamed rules

- CHANGELOG.md
- crates/biome_js_analyze/tests/specs/suspicious/noRedeclare/invalid-non-strict-mode.cjs
- crates/biome_js_analyze/tests/specs/suspicious/noRedeclare/invalid-non-strict-mode.cjs.snap
- crates/biome_js_analyze/tests/specs/suspicious/noRedeclare/valid-function-strict-mode.cjs
- crates/biome_js_analyze/tests/specs/suspicious/noRedeclare/valid-function-strict-mode.cjs.snap
- crates/biome_js_analyze/tests/specs/suspicious/noRedeclare/valid-strict-mode.cjs
- crates/biome_js_analyze/tests/specs/suspicious/noRedeclare/valid-strict-mode.cjs.snap
- crates/biome_js_semantic/src/events.rs
- crates/biome_js_semantic/src/tests/functions.rs
Fix #3664
Function declarations are not hoisted in strict mode.
The semantic model now registers if a scope is in strict mode.
We could in a near future, expose this information directly in the semantic model.
This could simplify the implementation of some linter rules.
I added some test
> fix(js_semantic): take strict mode into account to compute declaration scope

- crates/biome_js_analyze/src/lint/complexity/no_static_only_class.rs
- crates/biome_js_analyze/tests/specs/complexity/noStaticOnlyClass/valid.ts
- crates/biome_js_analyze/tests/specs/complexity/noStaticOnlyClass/valid.ts.snap
Closes #3612
Updated `NoStaticOnlyClass` rule to exclude classes that have `extends` clause and added test case.
I'm wondering if i should do the same for `implements` clause?
Ran `cargo test no_static_only_class` and then `cargo insta review` to accept the new snapshot changes.
> fix(lint/noStaticOnlyClass): prevent error on static classes that extend other classes

- CHANGELOG.md
- crates/biome_js_analyze/src/lint/correctness/no_nodejs_modules.rs
- crates/biome_js_analyze/tests/specs/correctness/noNodejsModules/valid.ts
- crates/biome_js_analyze/tests/specs/correctness/noNodejsModules/valid.ts.snap
- crates/biome_js_syntax/src/import_ext.rs
> refactor(noNodejsModules): ignore type-only imports

- CHANGELOG.md
- crates/biome_cli/tests/cases/config_extends.rs
- crates/biome_cli/tests/commands/migrate_eslint.rs
- crates/biome_cli/tests/snapshots/main_cases_config_extends/extends_config_merge_overrides.snap
- crates/biome_cli/tests/snapshots/main_commands_migrate_eslint/migrate_merge_with_overrides.snap
- crates/biome_deserialize/src/merge.rs
- crates/biome_deserialize_macros/src/merge_derive.rs
Fix #3544
We no longer overwrite the `overrides` field. This fixes #3544 and allows inheriting the `overrides` of an extended configuration.
I took the opportunity of adding more implementations of the `Merge` trait. Basically I implemented `Merge` for the same types as `Deserializable` implement.
I added a migration test.
> fix(configuration): merge inherited overrides

- CHANGELOG.md
- crates/biome_js_analyze/src/lint/correctness/no_nodejs_modules.rs
- crates/biome_js_analyze/tests/specs/correctness/noNodejsModules/valid-with-dep.js
- crates/biome_js_analyze/tests/specs/correctness/noNodejsModules/valid-with-dep.js.snap
- crates/biome_js_analyze/tests/specs/correctness/noNodejsModules/valid-with-dep.package.json
Similarly to `useNodejsImportProtocol`, `noNodejsModules` now ignore `package.json` dependencies that have the same name as Node.js modules.
I added a test
> refactor(noNodejsModules): ignore package.json dependencies

- crates/biome_lsp/src/extension_settings.rs
- crates/biome_lsp/src/server.rs
This pull request deprecates the `biome.rename` LSP setting in favor of `biome.experimental.rename` to align with the new name of the setting that will be used in the upcoming version of the VS Code extension.
This is a non-breaking change, and the old setting name will continue to work for now, although the new name will be preferred.
Tested manually that setting either `biome.rename` and `biome.experimental.rename` to `true` resulted in the `biome_rename` capability being registered.
> feat(lsp): deprecate `biome.rename` in favor of `biome.experimental.rename`

- crates/biome_js_analyze/src/lint/complexity/use_optional_chain.rs
While searching for JS-specific lint rules, I initially overlooked this rule due to the ts lang tag.
> chore: update biome_js_analyze/lint/complexity/use_optional_chain to use js tag instead of ts

- crates/biome_js_analyze/src/lint/suspicious/no_comment_text.rs
- crates/biome_js_analyze/tests/specs/suspicious/noCommentText/invalid.tsx
- crates/biome_js_analyze/tests/specs/suspicious/noCommentText/invalid.tsx.snap
- crates/biome_js_analyze/tests/specs/suspicious/noCommentText/valid.tsx
- crates/biome_js_analyze/tests/specs/suspicious/noCommentText/valid.tsx.snap
This fixes a false positive such as:
```jsx
<div>https://domain.com</div>
```
I had to change the implementation because this was hard to check using regexes (Rust regexes don't support assertions).
As a bonus, we now have precise range reporting.
I added tests.
> fix(noCommentText): don't report URIs

- CHANGELOG.md
- crates/biome_js_formatter/src/ts/types/infer_type.rs
- crates/biome_js_syntax/src/parentheses/tstype.rs
Fix a regression introduced in #3451 and detected by the [Ecosystem CI](https://github.com/biomejs/ecosystem-ci/actions/runs/10491208466/job/29060285601)
> fix(js_formatter): remove useless parens around infer type

- crates/biome_console/src/write/html.rs
The HTML emitted by our adapter was causing a parsing error when used inside MDX files.
It turns out that MDX doesn't like `\n\n` inside HTML. I think it's a reasonable parsing error.
This PR fixes the issue by changing `\n` to a `<br />`. While `<br>` should be accepted, MDX doesn't like it, so it's safer to use `<br />` instead.
This PR changes the existing adapter and renames it. Unfortunately, I tried to use a new adapter but that required more work, so I decided to update the existing one.
I added new tests to avoid possible regressions. Once merged, I will send a PR to the website to fix everything.
> fix(console): print `<br />` when having a newline

- CHANGELOG.md
- crates/biome_cli/tests/cases/overrides_formatter.rs
- crates/biome_cli/tests/snapshots/main_cases_overrides_formatter/allow_trailing_commas_on_well_known_files.snap
- crates/biome_cli/tests/snapshots/main_cases_overrides_formatter/disallow_comments_on_well_known_files.snap
- crates/biome_json_syntax/src/file_source.rs
- crates/biome_service/tests/workspace.rs
We now define `.json` files directly under the `.vscode` and the `.zed` directories as JSON files that allow comments.
> refactor(json): allow comments in `.json` files under `.vscode` and `.zed` dirs

- crates/biome_console/src/write/html.rs
- crates/biome_wasm/src/utils.rs
I am rewriting the docs generation of the lint rules, and MDX breaks if there are curly braces that aren't escaped. 
In MDX, curly braces are the beginning of an expression. With this option, we tell the HTML printer to escape curly braces.
Added new tests. I will merge it and use it for the website
> feat: adds an option to `HTML` printer for MDX

- crates/biome_console/src/write/html.rs
> fix: another quick fix to escape some other chars that make MDX go nuts

- CHANGELOG.md
Adds the `ignoreNull` option to the CHANGELOG.
cc @peaBerberian
> chore: add `ignoreNull` option to `CHANGELOG`

- Cargo.lock
- crates/biome_yaml_parser/Cargo.toml
- crates/biome_yaml_parser/src/lexer/mod.rs
- crates/biome_yaml_parser/src/lexer/tests.rs
I figured I'd take a stab at building the lexer based on the grammar in #3400. It's somewhat inspired by the json lexer. I'm posting it early here so people can see it, and avoid duplicated effort.
related to: #2365 
Added some unit tests, and they all pass.
> feat(yaml): lexer that can lex very simple examples

- .github/actions/free-disk-space/action.yaml
`free-disk-space` is useful but quite slow.
A contributor to `rspack` has made a fork which is faster.
I have also tested another version using https://lib.rs/crates/rmz but the installation time makes it slower.
Related PR with the changes : https://github.com/jlumbroso/free-disk-space/pull/26
Tested on a fork + rspack is also already using it.
> perf(ci): speedup free disk space action

- CHANGELOG.md
- crates/biome_cli/src/commands/mod.rs
- crates/biome_cli/src/execute/mod.rs
- crates/biome_cli/tests/snapshots/main_commands_explain/explain_help.snap
- crates/biome_cli/tests/snapshots/main_commands_lsp_proxy/lsp_proxy_help.snap
- crates/biome_cli/tests/snapshots/main_commands_migrate/migrate_help.snap
- crates/biome_cli/tests/snapshots/main_commands_rage/rage_help.snap
- crates/biome_service/src/diagnostics.rs
Marked as EXPERIMENTAL, and added a CHANGELOG entry.
Also made the subcommand descriptions a little bit more consistent.
The GritQL reference is created in this website PR: https://github.com/biomejs/website/pull/991
Tested the `--help` output manually.
> chore: unhide `search` command

- CHANGELOG.md
- crates/biome_js_analyze/src/lint/a11y/no_interactive_element_to_noninteractive_role.rs
- crates/biome_js_analyze/tests/specs/a11y/noInteractiveElementToNoninteractiveRole/valid.jsx
- crates/biome_js_analyze/tests/specs/a11y/noInteractiveElementToNoninteractiveRole/valid.jsx.snap
The `<canvas>` element can be given `role="img"` to indicate that the canvas is not meant to be interactive. This can be seen in [this PR to the corresponding ESLint plugin rule](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/pull/796). I noticed this difference between the ESLint plugin rule and Biome while migrating in our codebase.
Additional context on `<canvas>` accessibility can be found here: https://pauljadam.com/demos/canvas.html
I've updated the `valid.jsx` for this rule to reflect the intended change.
> fix: edge case in `noInteractiveToNonInteractiveRole` for `<canvas>`.

- CHANGELOG.md
- crates/biome_js_syntax/src/file_source.rs
- crates/biome_service/src/file_handlers/mod.rs
- crates/biome_service/src/file_handlers/svelte.rs
- crates/biome_service/src/file_handlers/vue.rs
Closes https://github.com/biomejs/biome/issues/3464
I would like to add a test, but I couldn't find a file on the web
> fix: enable JSX parsing inside `.vue` files

- CHANGELOG.md
- crates/biome_js_analyze/src/globals/javascript/language.rs
- crates/biome_js_analyze/src/globals/javascript/node.rs
- crates/biome_js_analyze/src/globals/javascript/web.rs
- crates/biome_js_analyze/src/globals/module/node.rs
- crates/biome_js_analyze/src/globals/typescript/language.rs
- crates/biome_js_analyze/src/globals/typescript/node.rs
- crates/biome_js_analyze/src/globals/typescript/web.rs
- crates/biome_js_analyze/tests/spec_tests.rs
- crates/biome_js_analyze/tests/specs/correctness/noUndeclaredVariables/invalid.svelte.ts
- crates/biome_js_analyze/tests/specs/correctness/noUndeclaredVariables/invalid.svelte.ts.snap
- crates/biome_js_analyze/tests/specs/correctness/noUndeclaredVariables/valid.js
- crates/biome_js_analyze/tests/specs/correctness/noUndeclaredVariables/valid.js.snap
- crates/biome_js_analyze/tests/specs/correctness/noUndeclaredVariables/valid.options.json
- crates/biome_service/src/file_handlers/javascript.rs
- crates/biome_test_utils/src/lib.rs
Add support for Svelte 5 runes.
I fixed an issue in our test infra where `globals` was always empty.
I added a test to check that it is now set correctly.
Unfortunately our test infra doesn't call `resolve_analyzer_options` and I don't see an easy way to do it because it is language dependent and our test infra is mostly language independent.
Thus, I was not able to write a test for Svelte runes. 
Also, I took the opportunity of removing the size from the constant slices of globals.
> refactor(noUndeclaredVariables): recognize Svelte 5 runes

- crates/biome_cli/src/execute/migrate/eslint.rs
- crates/biome_cli/src/execute/migrate/prettier.rs
- crates/biome_cli/src/execute/process_file/assists.rs
- crates/biome_cli/src/execute/process_file/format.rs
- crates/biome_cli/src/execute/process_file/lint.rs
- crates/biome_cli/src/execute/process_file/organize_imports.rs
- crates/biome_cli/src/execute/process_file/workspace_file.rs
- crates/biome_cli/src/execute/std_in.rs
- crates/biome_fs/src/fs/os.rs
- crates/biome_fs/src/path.rs
- crates/biome_grit_patterns/src/grit_query.rs
- crates/biome_js_analyze/tests/spec_tests.rs
- crates/biome_lsp/src/handlers/analysis.rs
- crates/biome_lsp/src/handlers/formatting.rs
- crates/biome_lsp/src/session.rs
- crates/biome_project/tests/manifest_spec_tests.rs
- crates/biome_service/src/configuration.rs
- crates/biome_service/src/diagnostics.rs
- crates/biome_service/src/file_handlers/json.rs
- crates/biome_service/src/workspace.rs
- crates/biome_service/src/workspace/server.rs
- crates/biome_service/tests/spec_tests.rs
- crates/tests_macros/src/lib.rs
Minor changes to avoid some UTF-8 validations when we retrieve the extension of a file path.
CI must pass.
> refactor: avoid UTF-8 validation of file extensions

- CHANGELOG.md
- crates/biome_cli/src/execute/migrate/eslint_any_rule_to_biome.rs
- crates/biome_cli/src/execute/migrate/eslint_eslint.rs
- crates/biome_cli/src/execute/migrate/eslint_to_biome.rs
- crates/biome_cli/src/execute/migrate/eslint_typescript.rs
- crates/biome_configuration/src/analyzer/linter/rules.rs
- crates/biome_diagnostics_categories/src/categories.rs
- crates/biome_js_analyze/src/lint/nursery.rs
- crates/biome_js_analyze/src/lint/nursery/use_consistent_member_accessibility.rs
- crates/biome_js_analyze/src/options.rs
- crates/biome_js_analyze/tests/specs/nursery/useConsistentMemberAccessibility/invalidExplicit.options.json
- crates/biome_js_analyze/tests/specs/nursery/useConsistentMemberAccessibility/invalidExplicit.ts
- crates/biome_js_analyze/tests/specs/nursery/useConsistentMemberAccessibility/invalidExplicit.ts.snap
- crates/biome_js_analyze/tests/specs/nursery/useConsistentMemberAccessibility/invalidNoPublic.options.json
- crates/biome_js_analyze/tests/specs/nursery/useConsistentMemberAccessibility/invalidNoPublic.ts
- crates/biome_js_analyze/tests/specs/nursery/useConsistentMemberAccessibility/invalidNoPublic.ts.snap
- crates/biome_js_analyze/tests/specs/nursery/useConsistentMemberAccessibility/invalidNone.options.json
- crates/biome_js_analyze/tests/specs/nursery/useConsistentMemberAccessibility/invalidNone.ts
- crates/biome_js_analyze/tests/specs/nursery/useConsistentMemberAccessibility/invalidNone.ts.snap
- crates/biome_js_analyze/tests/specs/nursery/useConsistentMemberAccessibility/validExplicit.options.json
- crates/biome_js_analyze/tests/specs/nursery/useConsistentMemberAccessibility/validExplicit.ts
- crates/biome_js_analyze/tests/specs/nursery/useConsistentMemberAccessibility/validExplicit.ts.snap
- crates/biome_js_analyze/tests/specs/nursery/useConsistentMemberAccessibility/validNoPublic.options.json
- crates/biome_js_analyze/tests/specs/nursery/useConsistentMemberAccessibility/validNoPublic.ts
- crates/biome_js_analyze/tests/specs/nursery/useConsistentMemberAccessibility/validNoPublic.ts.snap
- crates/biome_js_analyze/tests/specs/nursery/useConsistentMemberAccessibility/validNone.options.json
- crates/biome_js_analyze/tests/specs/nursery/useConsistentMemberAccessibility/validNone.ts
- crates/biome_js_analyze/tests/specs/nursery/useConsistentMemberAccessibility/validNone.ts.snap
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
- packages/@biomejs/biome/configuration_schema.json
close #3271 
implement [useConsistentMemberAccessibility](https://typescript-eslint.io/rules/explicit-member-accessibility/#require-explicit-accessibility-for-a-given-member)
Add snaps for valid/invalid cases
> feat(biome_js_analyzer): implement `useConsistentMemberAccessibility`

- crates/biome_css_semantic/src/events.rs
- crates/biome_css_semantic/src/semantic_model/builder.rs
- crates/biome_css_semantic/src/semantic_model/mod.rs
- crates/biome_css_semantic/src/semantic_model/model.rs
- cleanup codebase
- Improve the definition of global css custom variables and allow an empty at-property declation
CI should pass
> chore(css_semantic): allow an empty at-property declation

- CHANGELOG.md
- crates/biome_json_syntax/src/file_source.rs
Recognize `jest.config.json` files as JSON files allowing comments.
CI must pass.
> refactor(json): allow comments in jest.config.json

- crates/biome_cli/src/reporter/summary.rs
While I was working on the Ecosystem CI, I noted that reported paths in the summary are not always reported in the same order.
This PR fixes that by ordering paths in the summary.
CI must pass.
> refactor(summary-reporter): order reported paths

- CHANGELOG.md
- crates/biome_js_analyze/src/lint/suspicious/no_redeclare.rs
- crates/biome_js_analyze/tests/specs/suspicious/noRedeclare/valid.jsonc
- crates/biome_js_analyze/tests/specs/suspicious/noRedeclare/valid.jsonc.snap
Previously, Biome reported `foof` as redeclared.
```js
const f = function foo() { const foo = 0; }
```
I added a test
> refactor(noRedeclare): ignore var named as function expression name

- crates/biome_css_semantic/src/semantic_model/builder.rs
- crates/biome_css_semantic/src/semantic_model/mod.rs
- crates/biome_css_semantic/src/semantic_model/model.rs
This PR improves the CSS semantic model by implementing a more efficient rule hierarchy tracking system and improving rule lookup.
I added a new public API, `get_rule_by_range` to the model that can be used in lint rules.
```css
.foo{
color: red;
.bar {
color: blue;
font-size: 20px;
.baz {
color: pink
}
}
}
```
```rust
let model = ctx.model();
let range = node.range(); // Consider node as `color: blue` in `.bar`
// Get the rule containing the given range
let rule = model.get_rule_by_range(range);
// See Selectors 
for selector in &rule.selectors {
// Work with selectors
}
// See other declarations in the same scope
for declaration in &rule.declarations {
// Work with declarations
}
// Access parent and child rules
if let Some(parent_id) = rule.parent_id {
let parent_rule = …
```
> feat(css_semantic): implement rule hierarchy tracking and enhance rule lookup

- crates/biome_js_analyze/src/lib.rs
- crates/biome_js_analyze/src/lint/correctness/use_exhaustive_dependencies.rs
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
- packages/@biomejs/biome/configuration_schema.json
> fix(useExhaustiveDependencies): make stableResult optional

- CHANGELOG.md
- crates/biome_aria/src/properties.rs
- crates/biome_js_analyze/src/lint/a11y/use_valid_aria_values.rs
- crates/biome_js_analyze/tests/specs/a11y/useValidAriaValues/invalid.jsx.snap
- crates/biome_js_analyze/tests/specs/a11y/useValidAriaValues/valid.jsx
- crates/biome_js_analyze/tests/specs/a11y/useValidAriaValues/valid.jsx.snap
Fix #3748
This PR fixes several bugs and improves the diagnostics of `useValidAriaValues`.
- Properties that expect a string now accept arbitrary text.
- An identifiers can now be made up of any characters except ASCII whitespace.
- An identifier list can now be separated by any ASCII whitespace.
> fix(useValidAriaValues): correctly check property types

- crates/biome_js_parser/src/syntax/stmt.rs
> fix: don't panic in debug mode when encountring complex variable declaration

- crates/biome_css_parser/src/lexer/mod.rs
- crates/biome_js_parser/src/lexer/mod.rs
- crates/biome_json_parser/src/lexer/mod.rs
- crates/biome_unicode_table/src/bytes.rs
- crates/biome_unicode_table/src/lib.rs
Attempt to improve a hot code path (CSS identifier parsing).
> perf(css_parser): avoid expensive check when parsing an id

- CHANGELOG.md
- crates/biome_js_analyze/src/lint/a11y/use_heading_content.rs
- crates/biome_js_analyze/tests/specs/a11y/useHeadingContent/invalid.jsx
- crates/biome_js_analyze/tests/specs/a11y/useHeadingContent/invalid.jsx.snap
- crates/biome_js_analyze/tests/specs/a11y/useHeadingContent/valid.jsx
- crates/biome_js_analyze/tests/specs/a11y/useHeadingContent/valid.jsx.snap
An `aria-label` can be used to set what a screen reader uses for a heading element, even when the heading element doesn't have content available in its "a11y tree" (e.g. children nodes of the element). There is one exception where a heading tag can have both `aria-label` and `aria-hidden`, which also removes it from the "a11y tree". 
The logic introduced in this PR reflects the above.
I've updated the snapshots to reflect what should be a valid and invaild use of `aria-label`.
> fix: let aria-label be valid for useHeadingContent.

- xtask/bench/benches/analyzer-libs-css.txt
- xtask/bench/benches/analyzer-libs-js.txt
- xtask/bench/benches/analyzer-libs-ts.txt
- xtask/bench/benches/libs-css.txt
- xtask/bench/benches/libs-graphql.txt
- xtask/bench/benches/libs-json.txt
- xtask/bench/benches/libs-ts.txt
Closes https://github.com/biomejs/biome/issues/3196
> chore(bench): pin bench libs

- crates/biome_html_parser/src/lexer/mod.rs
- crates/biome_html_parser/src/lexer/tests.rs
- crates/biome_html_parser/src/syntax/mod.rs
- crates/biome_html_parser/tests/html_specs/ok/ok2.html
- crates/biome_html_parser/tests/html_specs/ok/ok2.html.snap
- xtask/codegen/html.ungram
This fixes incorrect lexing and parsing for HTML in the `doctype` directive node. It doesn't completely resolve everything parsing related to `doctype` -- I've left that to a future PR because the context for `quirk`, `public_id` and `system_id` is not really clear, even from looking at the HTML spec. But this _should_ reasonably cover modern html documents.
Updated the unit tests
> fix(parser/html): fix parsing `html` keyword in doctype

- Cargo.lock
- Cargo.toml
- crates/biome_html_formatter/Cargo.toml
- crates/biome_html_formatter/src/context.rs
- crates/biome_html_formatter/src/lib.rs
- crates/biome_html_formatter/tests/language.rs
- crates/biome_html_formatter/tests/quick_test.rs
- crates/biome_html_parser/src/lib.rs
- crates/biome_service/Cargo.toml
- crates/biome_service/src/file_handlers/html.rs
- crates/biome_service/src/file_handlers/mod.rs
This PR adds `quick_test` to `biome_html_formatter`. This is equivalent to the `quick_test`s in other formatter crates.
CI passes, and running the quick test works.
> feat(format/html): add `quick_test` to formatter crate

- CHANGELOG.md
- crates/biome_cli/src/execute/migrate/eslint_eslint.rs
- crates/biome_cli/src/execute/migrate/eslint_to_biome.rs
- crates/biome_js_analyze/src/lint/nursery/no_console.rs
- crates/biome_js_analyze/tests/specs/nursery/noConsole/allowlist.js
- crates/biome_js_analyze/tests/specs/nursery/noConsole/allowlist.js.snap
- crates/biome_js_analyze/tests/specs/nursery/noConsole/allowlist.options.json
- crates/biome_js_analyze/tests/specs/nursery/noConsole/invalid.js.snap
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
- packages/@biomejs/biome/configuration_schema.json
Add an option to `noConsole` that allows to specify an allowlist of methods.
This is the same option that provided by ESLint.
I also implemented the code for `migrate eslint`.
I improved the diagnostics and the rule description.
> refactor(noConsole): add `allow` option

- Cargo.lock
- crates/biome_js_parser/Cargo.toml
- crates/biome_js_parser/src/lexer/mod.rs
Part of https://github.com/biomejs/biome/issues/3157
Adds `enumflags2` to `biome_js_parser/lexer`.
> refactor(biome_js_parser/lexer): use enumflags2 for `RegexFlag`

- CHANGELOG.md
- crates/biome_js_analyze/tests/specs/suspicious/noFocusedTests/invalid.js
- crates/biome_js_analyze/tests/specs/suspicious/noFocusedTests/invalid.js.snap
- crates/biome_js_syntax/src/expr_ext.rs
closes #3791
Fixed a case where test call expressions are failed to be treated as one of them.
**Previously:**
```js
describe.only("foo", () => {});
describe.only(foo, () => {}); // ❌ failed to report as linter error
```
Only supports test call expressions with string-like expressions.
**Currently:**
```js
describe.only("foo", () => {});
// works with any JavaScript expression
describe.only(foo, () => {});
describe.only(foo.bar, () => {});
```
Every JavaScript expression is supported.
Tests are added.
> fix(linter): fix rule `noFocusedTests` checking test call expressions

- crates/biome_js_parser/src/syntax/class.rs
Part of https://github.com/biomejs/biome/issues/3157
Adds `enumflags2` to `biome_js_parser` `ModifierFlag`
> refactor(biome_js_parser/syntax): use enumflags2 for `ModifierFlag`

- crates/biome_grit_patterns/src/grit_binding.rs
- crates/biome_grit_patterns/src/grit_node_patterns.rs
- crates/biome_grit_patterns/tests/specs/ts/functionToArrow.snap
- crates/biome_grit_patterns/tests/specs/ts/functionToArrow.ts
- crates/biome_js_analyze/src/lint/complexity/no_useless_constructor.rs
- crates/biome_js_analyze/src/lint/correctness/no_unused_private_class_members.rs
- crates/biome_js_analyze/src/lint/style/no_parameter_assign.rs
- crates/biome_js_formatter/src/js/any/formal_parameter.rs
- crates/biome_js_formatter/src/js/bindings/parameters.rs
- crates/biome_js_formatter/src/js/expressions/arrow_function_expression.rs
- crates/biome_js_parser/src/syntax/function.rs
- crates/biome_js_syntax/src/generated/nodes.rs
- crates/biome_js_syntax/src/parameter_ext.rs
- xtask/codegen/js.ungram
We had an issue with matching function arguments in Grit queries, that prevented metavariables from matching multiple arguments. In short, the metavariable was consumed by the `JsFormalParameter` and stored inside one of its slots. This wasn't a problem if you only tried to match a single argument with no other syntax, but if you wanted the metavariable to match anything more, it wouldn't work.
To fix it, I made sure `JsMetavariable` can be accepted in our grammar _next to_ `JsFormalParameter` and updated the JS parser so it's accepted there.
I also extended our list handling in the bindings a bit to be more in line with how Grit's reference implementation does it. The change in `GritBinding::singleton()` seems it's actually necessary, but some of the others may not be. It's probably …
> fix(grit): fix matching multiple args

- crates/biome_js_parser/src/state.rs
Part of https://github.com/biomejs/biome/issues/3157
Adds `enumflags2` to `biome_js_parser` `SignatureFlag ` and `ParsingContextFlag`
> refactor(biome_js_parser/state): use enumflags2 for `SignatureFlag ` and `ParsingContextFlag`

- Cargo.lock
- Cargo.toml
- crates/biome_js_analyze/Cargo.toml
- crates/biome_js_parser/Cargo.toml
- crates/biome_parser/Cargo.toml
- crates/biome_parser/src/lexer.rs
Closes #3157
Adds `enumflags2` to `biome_parser` `TokenFlag ` and removes `bitflags` dependency from all `Cargo.toml` files where it is referenced.
> refactor(biome_parser): use enumflags2 for `TokenFlag ` and remove `bitflags`

- packages/@biomejs/biome/scripts/generate-packages.mjs
Fixes #3804 - see that issue for discussion.
I'm not sure that it's possible to validate conclusively that this fixes #3804 without privileged access to the repository, as it's part of the NPM publish workflow.
> ci: fix broken CLI binary copy step for NPM publish

- crates/biome_grit_patterns/tests/specs/ts/functionToArrow.grit
- crates/biome_grit_patterns/tests/specs/ts/functionToArrow.snap
- crates/biome_grit_patterns/tests/specs/ts/functionToArrow.ts
- crates/biome_js_formatter/src/js/any/statement.rs
- crates/biome_js_parser/src/syntax/function.rs
- crates/biome_js_parser/src/syntax/stmt.rs
- crates/biome_js_parser/test_data/inline/ok/metavar.rast
- crates/biome_js_syntax/src/generated/nodes.rs
- xtask/codegen/js.ungram
We had an issue with matching function bodies in Grit queries that prevented metavariables from matching statements inside a function body. In fact, even the presence of a metavariable inside a snippet's function body would prevent the query from matching at all.
To fix it, I made sure `JsMetavariable` will be accepted in our grammar inside `AnyJsStatement` and updated the JS parser so it's accepted there.
Expanded test cases.
> fix(grit): fix matching function body

- crates/biome_grit_patterns/src/errors.rs
- crates/biome_grit_patterns/src/pattern_compiler/literal_compiler.rs
- crates/biome_grit_patterns/tests/specs/ts/whereClause.grit
- crates/biome_grit_patterns/tests/specs/ts/whereClause.snap
- crates/biome_grit_patterns/tests/specs/ts/whereClause.ts
Adds support for language-specific snippets in Grit queries. We only support one target language thus far, so it's purely a syntax thing for now.
> feat(grit): support language-specific snippets in Grit queries

- crates/biome_grit_patterns/src/errors.rs
- crates/biome_grit_patterns/src/pattern_compiler.rs
- crates/biome_grit_patterns/src/pattern_compiler/regex_compiler.rs
- crates/biome_grit_patterns/tests/specs/ts/regex.grit
- crates/biome_grit_patterns/tests/specs/ts/regex.snap
- crates/biome_grit_patterns/tests/specs/ts/regex.snap.new
- crates/biome_grit_patterns/tests/specs/ts/regex.ts
Another missing feature implemented in Grit queries: regex support.
> feat(grit): add regex support in Grit queries

- crates/biome_grit_patterns/src/errors.rs
- crates/biome_grit_patterns/src/pattern_compiler/literal_compiler.rs
- crates/biome_grit_patterns/tests/specs/ts/rawSnippet.grit
- crates/biome_grit_patterns/tests/specs/ts/rawSnippet.snap
- crates/biome_grit_patterns/tests/specs/ts/rawSnippet.ts
Adds syntax support for raw snippets. It doesn't do much since we don't support rewrites yet anyway, but it was the last item missing in our syntax support, so might as well support it :)
> feat(grit): syntax support for raw snippets in Grit queries

- CHANGELOG.md
- crates/biome_configuration/src/analyzer/linter/rules.rs
- crates/biome_css_analyze/src/lint/nursery.rs
- crates/biome_css_analyze/src/lint/nursery/no_duplicate_custom_properties.rs
- crates/biome_css_analyze/src/options.rs
- crates/biome_css_analyze/tests/specs/nursery/noDuplicateCustomProperties/invalid.css
- crates/biome_css_analyze/tests/specs/nursery/noDuplicateCustomProperties/invalid.css.snap
- crates/biome_css_analyze/tests/specs/nursery/noDuplicateCustomProperties/valid.css
- crates/biome_css_analyze/tests/specs/nursery/noDuplicateCustomProperties/valid.css.snap
- crates/biome_diagnostics_categories/src/categories.rs
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
- packages/@biomejs/biome/configuration_schema.json
> feat(biome_css_analyzer): `noDuplicateCustomProperties`

- crates/biome_html_parser/src/lexer/mod.rs
- crates/biome_html_parser/src/lexer/tests.rs
- crates/biome_html_parser/tests/html_specs/ok/hello-world.html
- crates/biome_html_parser/tests/html_specs/ok/hello-world.html.snap
- crates/biome_html_parser/tests/html_specs/ok/special-chars.html
- crates/biome_html_parser/tests/html_specs/ok/special-chars.html.snap
The intention of the `html` keyword is that it should only appear in the `doctype` declaration. An `<html>` tag should be lexed such that `html` is `HtmlLiteral`.
Added tests
> fix(parser/html): fix incorrect lexing of `<html>` elements

- crates/biome_html_formatter/src/html/auxiliary/closing_element.rs
- crates/biome_html_formatter/src/html/auxiliary/directive.rs
- crates/biome_html_formatter/src/html/auxiliary/element.rs
- crates/biome_html_formatter/src/html/auxiliary/name.rs
- crates/biome_html_formatter/src/html/auxiliary/opening_element.rs
- crates/biome_html_formatter/src/html/auxiliary/root.rs
- crates/biome_html_formatter/src/html/auxiliary/self_closing_element.rs
- crates/biome_html_formatter/src/prelude.rs
This PR refactors the directive and element tag formatters to not use the verbatim formatter. This allows testing and experimentation with formatters for child tokens. Without this, it's not possible to test formatters for attribute and element lists.
It builds.
> feat(format/html): impl non-verbatim formatting for directive and element tags

- crates/biome_js_analyze/src/lint/suspicious/no_duplicate_test_hooks.rs
- crates/biome_js_analyze/tests/specs/suspicious/noDuplicateTestHooks/invalid.js.snap
- crates/biome_js_analyze/tests/specs/suspicious/noDuplicateTestHooks/valid.js
- crates/biome_js_analyze/tests/specs/suspicious/noDuplicateTestHooks/valid.js.snap
Fixes https://github.com/biomejs/biome/issues/3291
Since noDuplicateTestHooks didn't know that `describe.each` has a different syntax from `describe`
Added a new test for `describe.each` hook
> fix(js_analyzer): don't flag duplicate hooks in describe.each for lint/suspicious/noDuplicateTestHooks

- Cargo.lock
- crates/biome_configuration/Cargo.toml
- crates/biome_html_formatter/Cargo.toml
- crates/biome_html_formatter/tests/prettier_tests.rs
- crates/biome_html_formatter/tests/spec_test.rs
- crates/biome_html_formatter/tests/spec_tests.rs
- crates/biome_html_formatter/tests/specs/example.html
- crates/biome_html_formatter/tests/specs/example.html.snap
- crates/biome_html_formatter/tests/specs/prettier/prepare_tests.js
- crates/biome_html_syntax/src/file_source.rs
- crates/biome_service/Cargo.toml
- crates/biome_service/src/file_handlers/html.rs
- crates/biome_service/src/file_handlers/mod.rs
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
- xtask/rules_check/src/lib.rs
This PR sets up everything necessary to start adding snapshot tests for the html formatter.
The example snapshot test works and is evaluated correctly, and importing prettier's html tests also work (I just haven't done that to make reviewing this easier).
> test(format/html): set up test infrastructure

- crates/biome_js_analyze/src/lint/nursery/no_restricted_types.rs
- crates/biome_js_analyze/tests/specs/nursery/noRestrictedTypes/invalidCustom.options.json
- packages/@biomejs/biome/configuration_schema.json
Allows passing string instead of full object `noRestrictedTypes`, make common configuration easier.
```json
{
"types": {
"OldAPI": {
"message": "Use NewAPI instead"
}
}
}
```
->
```json
{
"types": {
"OldAPI": "Use NewAPI instead"
}
}
```
No changelog entry since rule is not released yet.
Existing snapshots should pass.
> feat(linter): make noRestrictedTypes common options simpler

- crates/biome_js_formatter/src/js/bindings/constructor_parameters.rs
- crates/biome_js_formatter/src/js/classes/static_initialization_block_class_member.rs
- crates/biome_js_formatter/src/ts/lists/type_parameter_list.rs
Remove unnecessary symbols and add missing symbols
> chore: fix docs comments

- crates/biome_html_factory/src/generated/node_factory.rs
- crates/biome_html_parser/src/syntax/mod.rs
- crates/biome_html_parser/src/syntax/parse_error.rs
- crates/biome_html_parser/tests/html_specs/error/element/br-with-end.html
- crates/biome_html_parser/tests/html_specs/error/element/br-with-end.html.snap
- crates/biome_html_parser/tests/html_specs/ok/no-end-tags/br-in-span.html
- crates/biome_html_parser/tests/html_specs/ok/no-end-tags/br-in-span.html.snap
- crates/biome_html_parser/tests/html_specs/ok/no-end-tags/br.html
- crates/biome_html_parser/tests/html_specs/ok/no-end-tags/br.html.snap
- crates/biome_html_parser/tests/html_specs/ok/no-end-tags/meta.html
- crates/biome_html_parser/tests/html_specs/ok/no-end-tags/meta.html.snap
- crates/biome_html_parser/tests/html_specs/ok/no-end-tags/wbr.html
- crates/biome_html_parser/tests/html_specs/ok/no-end-tags/wbr.html.snap
- crates/biome_html_syntax/src/generated/nodes.rs
- crates/biome_html_syntax/src/generated/nodes_mut.rs
- crates/biome_html_syntax/src/lib.rs
- xtask/codegen/html.ungram
Void elements are elements whose content model is "nothing", meaning that they should not have an end tag, and therefore, have no children.
In browsers, this requirement is imposed very forgivingly. Given that Biome doesn't aim to write browser-grade parsers, we can afford to be a little more strict.
The parser now checks the tag name to know if it should be self closing. If it encounters a closing tag for a void element, it will emit a diagnostic.
Added snapshot tests.
See the HTML spec: https://html.spec.whatwg.org/#void-elements
> feat(parser/html): correctly parse void elements

- crates/biome_analyze/src/rule.rs
Update a rule source URL of [eslint-plugin-solid](https://github.com/solidjs-community/eslint-plugin-solid).
At [Restructure to turbo monorepo](https://github.com/solidjs-community/eslint-plugin-solid/pull/150), docs was moved.
https://github.com/solidjs-community/eslint-plugin-solid/blob/main/docs/no-react-specific-props.md ❌
https://github.com/solidjs-community/eslint-plugin-solid/blob/main/packages/eslint-plugin-solid/docs/no-react-specific-props.md ✔️
N/A
> fix: update eslint-plugin-solid docs position

- CHANGELOG.md
- crates/biome_aria/src/roles.rs
- crates/biome_js_analyze/tests/specs/a11y/useSemanticElements/invalid.jsx
- crates/biome_js_analyze/tests/specs/a11y/useSemanticElements/invalid.jsx.snap
- crates/biome_js_analyze/tests/specs/a11y/useSemanticElements/valid.jsx
- crates/biome_js_analyze/tests/specs/a11y/useSemanticElements/valid.jsx.snap
Fix #3858
The [alert role](https://www.w3.org/TR/wai-aria-1.2/#alert) and [alertdialog role](https://www.w3.org/TR/wai-aria-1.2/#alert) have no associated concepts according to the spec.
I noticed several errors in the provided metadata (divergence from the spec). Also, this is modeled on the 1.1 spec. We should update it to 1.2.
All these fixes are out of scope for this PR.
> fix(aria): remove concept for alert like roles

- CHANGELOG.md
- crates/biome_cli/src/commands/ci.rs
- crates/biome_cli/tests/cases/editorconfig.rs
- crates/biome_cli/tests/snapshots/main_cases_editorconfig/should_use_editorconfig_ci.snap
- crates/biome_cli/tests/snapshots/main_cases_editorconfig/should_use_editorconfig_ci_enabled_from_biome_conf.snap
This makes biome load `.editorconfig` files when running `biome ci`.
fixes #3864
Added unit tests
> fix(editorconfig): fix editorconfig not being loaded when running `biome ci`

- crates/biome_js_analyze/src/lint/suspicious/no_console.rs
This PR adds `noConsole` options documentation. (The `allow` option was added in #3786.)
N/A
> chore: add `noConsole` options documentation

- crates/biome_js_analyze/src/lint/style/use_consistent_array_type.rs
These are few minor changes in `useConsistentArrayType` rule documentation:
- "Default" was is move into the description of the option
- the heading is now set in lower case (`syntax`) to match the option name
- and I used bullet points (similar to [`useNamingConvention`](https://biomejs.dev/linter/rules/use-naming-convention/) documentation)
N/A
> chore: tweak `useConsistentArrayType` rule documentation

- CHANGELOG.md
- crates/biome_js_analyze/src/lint/correctness/no_undeclared_dependencies.rs
- crates/biome_js_analyze/tests/specs/correctness/noUndeclaredDependencies/valid.package.json
- crates/biome_js_analyze/tests/specs/correctness/noUndeclaredDependencies/valid.ts
- crates/biome_js_analyze/tests/specs/correctness/noUndeclaredDependencies/valid.ts.snap
Fix #3874
Fix #3872
We now ensure that the package name is valid before checking if it is a dependency.
Note that I deliberately accepted some invalid package names (package names starting with an underscore and package name with uppercase character) in order to catch users' typo errors.
We also ignore `bun` imports.
This looks fair because the NPM module named `bun` is from the `bun` runtime.
> fix(noUndeclaredDependencies): ignore invalid package names, bun import, and recognize Definitely Typed

- crates/biome_lsp/src/capabilities.rs
- crates/biome_lsp/tests/server.rs
Reverts biomejs/biome#3731, because it causes code actions and quick fixes to no longer be available in VS Code.
Let's revert this and release a patch version to address the issue. This will give us more time to decide how to fix the regression without impacting users longer than necessary.
Fixes #3879
Fixes #3887
> revert: "feat(lsp): add codeActionKinds"

- packages/@biomejs/biome/README.hi.md
- packages/@biomejs/biome/README.ja.md
- packages/@biomejs/biome/README.kr.md
- packages/@biomejs/biome/README.md
- packages/@biomejs/biome/README.pt-BR.md
- packages/@biomejs/biome/README.zh-CN.md
- packages/@biomejs/biome/README.zh-TW.md
Based on the current README, a Zh-TW translation has been added!
Also updated the count of rules to 270 for other languages for consistency.
N/A.
> docs(readme): add zh-tw readme translation

- crates/biome_html_parser/src/lexer/mod.rs
- crates/biome_html_parser/src/lexer/tests.rs
- crates/biome_html_parser/src/syntax/mod.rs
- crates/biome_html_parser/src/token_source.rs
- crates/biome_html_parser/tests/html_specs/error/element/br-with-end.html.snap
- crates/biome_html_parser/tests/html_specs/error/element/missing-close-tag.html.snap
- crates/biome_html_parser/tests/html_specs/ok/attributes/multiline-attributes.html.snap
- crates/biome_html_parser/tests/html_specs/ok/element_list.html.snap
- crates/biome_html_parser/tests/html_specs/ok/hello-world.html.snap
- crates/biome_html_parser/tests/html_specs/ok/no-end-tags/meta.html.snap
- crates/biome_html_parser/tests/html_specs/ok/no-end-tags/wbr.html.snap
- crates/biome_html_parser/tests/html_specs/ok/special-chars.html.snap
This fixes the HTML lexer treating whitespace trivia as `HTML_LITERAL` when it shouldn't.
We end up creating less syntax nodes by treating all HTML text that would affect what is rendered on the screen as part of the same `HTML_LITERAL`. See the updated snapshots for examples of how this affects lexing and parsing.
This also significantly restructures the HTML lexer, and it should be a bit more straightforward.
Added/updated tests
> fix(parser/html): fix whitespace being lexed as html literal

- CHANGELOG.md
- crates/biome_unicode_table/src/lib.rs
The ranges should be inclusive.
CI must pass.
> fix(css_parser): accept U+FDCF and U+FFFD in identifiers

- crates/biome_cli/tests/cases/editorconfig.rs
- crates/biome_cli/tests/snapshots/main_cases_editorconfig/should_emit_diagnostics.snap
- crates/biome_configuration/src/diagnostics.rs
- crates/biome_configuration/src/editorconfig.rs
In the editorconfig spec, `unset` means "use the default value" and `off` (in the context of `max_line_length`) means "completely turn off the line limit".
This PR aims to implement the behavior for `unset`, and `off`. ~provide a better diagnostic when encountering `off`. We technically can't really handle `off` because biome doesn't have a mechanism to turn off the max line length enforcement.~
fixes #3886
closes #3904
Added some unit tests and a cli snapshot test
> fix(config): handle `unset` and `off` values in editorconfig files

- crates/biome_js_analyze/src/lint/nursery/use_consistent_curly_braces.rs
- crates/biome_js_analyze/tests/specs/nursery/useConsistentCurlyBraces/invalid.jsx
- crates/biome_js_analyze/tests/specs/nursery/useConsistentCurlyBraces/invalid.jsx.snap
PR https://github.com/biomejs/biome/pull/3182 added the `useConsistentCurlyBraces` rule. However, the automatic fix provided by the rule inadvertently removes other child nodes under the parent node. This behavior should be corrected to preserve these nodes.
```
invalid.jsx:14:9 lint/nursery/useConsistentCurlyBraces  FIXABLE  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
! Should not have curly braces around expression.
12 │ <Foo>{/*comment*/'Hello world'/*comment*/}</Foo>
13 │ 
> 14 │ <Foo>{x}{'y'}{z}</Foo>
│         ^^^^^
15 │ </>
16 │ 
i JSX child does not need to be wrapped in curly braces.
i Unsafe fix: Remove curly braces around the expression.
14 │ <Foo>{x}{'y'}{z}</Foo>
│      ----- -----      
```
See test spec.
```
cargo test -p biome_js_analyze use_consistent_curly_braces
```
> fix: preserve other children in `useConsistentCurlyBraces`

- CHANGELOG.md
- Cargo.lock
- crates/biome_cli/src/commands/check.rs
- crates/biome_cli/src/commands/ci.rs
- crates/biome_cli/src/commands/format.rs
- crates/biome_configuration/src/lib.rs
- crates/biome_lsp/Cargo.toml
- crates/biome_lsp/src/server.rs
- crates/biome_lsp/src/session.rs
Closes https://github.com/biomejs/biome/issues/3923
I also did some small refactor the make the code a bit more DRY.
I tested the changes locally
> fix(lsp): apply `.editorconfig` options

- CHANGELOG.md
- crates/biome_js_analyze/src/lint/nursery/use_strict_mode.rs
- crates/biome_js_analyze/tests/specs/nursery/useStrictMode/invalid-with-directive.cjs
- crates/biome_js_analyze/tests/specs/nursery/useStrictMode/invalid-with-directive.cjs.snap
- crates/biome_js_analyze/tests/specs/nursery/useStrictMode/invalid.js.snap
- crates/biome_js_analyze/tests/specs/nursery/useStrictMode/valid-with-directive.cjs
- crates/biome_js_analyze/tests/specs/nursery/useStrictMode/valid-with-directive.cjs.snap
`noStrictMode` didn't report files with some directives that are not `use strict`.
I am unsure if it was intended.
I also improved the code fix that now add a semicolon and keep previous directives.
Also, I removed the file module kind check because we only query `JsScript` nodes that imply Script module kind.
> fix(useStrictMode): check actual directives

- CHANGELOG.md
- crates/biome_aria_metadata/build.rs
- crates/biome_js_analyze/src/lint/style/use_filenaming_convention.rs
- crates/biome_js_analyze/tests/specs/style/useFilenamingConvention/0_start_with_digit.ts.snap
Fix partially #3952.
`useFilenamingConvention` no longer suggests names with a disallowed case.
> fix(useFilenamingConvention): don't suggest names with disallowed case

- CHANGELOG.md
- crates/biome_js_analyze/src/lint/style/use_filenaming_convention.rs
- crates/biome_js_analyze/src/lint/style/use_naming_convention.rs
- crates/biome_js_analyze/tests/specs/style/useFilenamingConvention/[slug_4].js.snap
- crates/biome_string_case/src/lib.rs
Fix #3952
Leading ASCII digits inside a name are now considered as lowercase characters.
`2024-09-17-filename`, `2024_09_17_filename`, `20240917FileName` and `20240917filename` are recognized as `kebab-case`, `snake_case`, `camelCase` and `lowercase` respectively.
`2024FILENAME` and `2024_FILE_NAME` are not recognized as `UPPERCASE` and `CONSTANT_CASE`.
I updated the changed snapshot.
> fix(useFilenamingConvention): allow leading digits in lower-like cases

- crates/biome_html_parser/src/syntax/mod.rs
- crates/biome_html_parser/tests/html_specs/ok/no-end-tags/casing.html
- crates/biome_html_parser/tests/html_specs/ok/no-end-tags/casing.html.snap
The HTML spec says that the casing of html tags is case insensitive.
CI should pass. Added a test.
> fix(parser/html): check void element names case insensitively

- crates/biome_html_formatter/src/html/auxiliary/string.rs
- crates/biome_html_formatter/tests/spec_tests.rs
- crates/biome_html_formatter/tests/specs/attributes-single-quotes.html
- crates/biome_html_formatter/tests/specs/attributes-single-quotes.html.snap
This PR makes it so that we keep single quotes but only when the string contains a `"`.
Added a test.
> fix(format/html): keep single quotes if string contains a double quote

- crates/biome_html_parser/src/lexer/mod.rs
- crates/biome_html_parser/src/lexer/tests.rs
- crates/biome_html_parser/src/syntax/mod.rs
- crates/biome_html_parser/src/token_source.rs
- crates/biome_html_parser/tests/html_specs/error/attributes/invalid-unqouted-value1.html
- crates/biome_html_parser/tests/html_specs/error/attributes/invalid-unqouted-value1.html.snap
- crates/biome_html_parser/tests/html_specs/error/attributes/invalid-unquoted-value2.html
- crates/biome_html_parser/tests/html_specs/error/attributes/invalid-unquoted-value2.html.snap
- crates/biome_html_parser/tests/html_specs/ok/attributes/attributes-unquoted.html
- crates/biome_html_parser/tests/html_specs/ok/attributes/attributes-unquoted.html.snap
This PR lets the HTML parser correctly lex and parse unquoted attribute values.
Added a test. See also: https://html.spec.whatwg.org/#attributes-2
> feat(parser/html): lex and parse unquoted attribute values

- crates/biome_html_parser/src/lexer/mod.rs
- crates/biome_html_parser/src/syntax/mod.rs
- crates/biome_html_parser/src/token_source.rs
- crates/biome_html_parser/tests/html_specs/ok/embedded-languages/script-basic.html
- crates/biome_html_parser/tests/html_specs/ok/embedded-languages/script-basic.html.snap
- crates/biome_html_parser/tests/html_specs/ok/embedded-languages/script-empty.html
- crates/biome_html_parser/tests/html_specs/ok/embedded-languages/script-empty.html.snap
- crates/biome_html_parser/tests/html_specs/ok/embedded-languages/script-in-string.html
- crates/biome_html_parser/tests/html_specs/ok/embedded-languages/script-in-string.html.snap
- crates/biome_html_parser/tests/html_specs/ok/embedded-languages/script-less-than.html
- crates/biome_html_parser/tests/html_specs/ok/embedded-languages/script-less-than.html.snap
This PR aims to handle `<script>` and `<style>` tags as minimally as possible in order to not crash and burn. It intentionally does not attempt to do any embedded language parsing or formatting. This is pretty much just to be able to parse all the prettier tests.
Added tests.
> feat(parser/html): handle script and style tags

- .github/workflows/repository_dispatch.yml
- crates/biome_cli/Cargo.toml
- crates/biome_service/Cargo.toml
- crates/biome_service/src/file_handlers/html.rs
- crates/biome_service/src/file_handlers/mod.rs
- crates/biome_service/src/settings.rs
- crates/biome_wasm/Cargo.toml
This PR reenables the HTML file handler, but only when compiled with the `experimental-html` flag.
Tested it manually on one of my projects. Shouldn't cause problems in ecosystem ci.
> feat(html): add `experimental-html` feature flag to enable html file handler

- crates/biome_grit_patterns/src/errors.rs
- crates/biome_grit_patterns/src/grit_context.rs
- crates/biome_grit_patterns/src/grit_definitions.rs
- crates/biome_grit_patterns/src/grit_query.rs
- crates/biome_grit_patterns/src/lib.rs
- crates/biome_grit_patterns/src/pattern_compiler.rs
- crates/biome_grit_patterns/src/pattern_compiler/and_compiler.rs
- crates/biome_grit_patterns/src/pattern_compiler/call_compiler.rs
- crates/biome_grit_patterns/src/pattern_compiler/compilation_context.rs
- crates/biome_grit_patterns/src/pattern_compiler/function_definition_compiler.rs
- crates/biome_grit_patterns/src/pattern_compiler/pattern_definition_compiler.rs
- crates/biome_grit_patterns/src/pattern_compiler/predicate_definition_compiler.rs
- crates/biome_grit_patterns/tests/specs/ts/patternDefinition.grit
- crates/biome_grit_patterns/tests/specs/ts/patternDefinition.snap
- crates/biome_grit_patterns/tests/specs/ts/patternDefinition.ts
Adds support for Grit definitions:
- Pattern and predicates: https://docs.grit.io/guides/patterns
- Functions: https://docs.grit.io/language/functions#function-definitions
Added a test. I admit test coverage is a bit light still, but I'll expand later as I improve the support for functions, since we currently don't have any built-in functions yet.
> feat(grit): support for Grit pattern, predicate and function definitions

- CHANGELOG.md
- crates/biome_js_analyze/src/lint/a11y/no_label_without_control.rs
- crates/biome_js_analyze/tests/specs/a11y/noLabelWithoutControl/valid.jsx
- crates/biome_js_analyze/tests/specs/a11y/noLabelWithoutControl/valid.jsx.snap
- crates/biome_js_syntax/src/jsx_ext.rs
Fix #3875
I refactored the code to avoid unnecessary string allocations and to avoid visiting too many nodes.
> fix(noLabelWithoutControl): accept expressions as label

- Cargo.lock
- crates/biome_grit_patterns/Cargo.toml
- crates/biome_grit_patterns/src/errors.rs
- crates/biome_grit_patterns/src/grit_built_in_functions.rs
- crates/biome_grit_patterns/src/grit_context.rs
- crates/biome_grit_patterns/src/grit_query.rs
- crates/biome_grit_patterns/src/lib.rs
- crates/biome_grit_patterns/src/pattern_compiler/call_compiler.rs
- crates/biome_grit_patterns/src/pattern_compiler/compilation_context.rs
- crates/biome_grit_patterns/src/pattern_compiler/node_like_compiler.rs
- crates/biome_grit_patterns/src/pattern_compiler/snippet_compiler.rs
- crates/biome_grit_patterns/tests/specs/ts/capitalize.grit
- crates/biome_grit_patterns/tests/specs/ts/capitalize.snap
- crates/biome_grit_patterns/tests/specs/ts/capitalize.ts
This implements all the Grit built-ins: https://docs.grit.io/language/functions#built-in-functions
Only exception for now is the `log()` function, which gets a bit of special treatment in the Grit engine.
Note that support for built-in functions will be important for us, as we will want to have a built-in `diagnostic()` function to allow for the creation of custom linter plugins.
Added test case. Still too low on coverage, but more is coming.
> feat(grit): implement Grit built-ins

- crates/biome_grit_patterns/src/grit_target_node.rs
- crates/biome_grit_patterns/tests/quick_test.rs
- crates/biome_grit_patterns/tests/specs/ts/containsSnippet.grit
- crates/biome_grit_patterns/tests/specs/ts/containsSnippet.snap
- crates/biome_grit_patterns/tests/specs/ts/containsSnippet.ts
Due to a bug in our Grit node cursor, `contains` queries would report false positives when the matched node was contained in a sibling instead of inside the node itself. This is the issue we witnessed when drafting the 1.9 release notes, @Conaclos.
Test added.
> fix(grit): fix node walking

- CHANGELOG.md
Put the GritQL changes under the CLI section instead.
N/A
> chore: move Grit changes in CHANGELOG

- crates/biome_css_analyze/src/lint/nursery/no_missing_var_function.rs
- crates/biome_js_analyze/src/lint/nursery/use_component_export_only_modules.rs
#3974 didn't set the `version` field of new rules.
CI must pass
> refactor(lint): set version field for new rules

- crates/biome_js_analyze/src/lint/correctness/use_exhaustive_dependencies.rs
- crates/biome_js_analyze/src/lint/correctness/use_hook_at_top_level.rs
Closes https://github.com/biomejs/biome/issues/3476
N/A
> docs: improve documentation of rule

- crates/biome_grit_patterns/src/grit_binding.rs
- crates/biome_grit_patterns/src/grit_query.rs
- crates/biome_grit_patterns/src/grit_target_node.rs
- crates/biome_grit_patterns/src/pattern_compiler.rs
- crates/biome_grit_patterns/src/pattern_compiler/call_compiler.rs
- crates/biome_grit_patterns/src/pattern_compiler/log_compiler.rs
- crates/biome_grit_patterns/src/pattern_compiler/predicate_call_compiler.rs
- crates/biome_grit_patterns/src/pattern_compiler/predicate_compiler.rs
- crates/biome_grit_patterns/src/pattern_compiler/snippet_compiler.rs
- crates/biome_grit_patterns/tests/quick_test.rs
- crates/biome_grit_patterns/tests/spec_tests.rs
- crates/biome_grit_patterns/tests/specs/ts/log.grit
- crates/biome_grit_patterns/tests/specs/ts/log.snap
- crates/biome_grit_patterns/tests/specs/ts/log.ts
- crates/biome_service/src/file_handlers/mod.rs
Implements the GritQL `log()` function, and exposes the logs in both the quick test and the spec tests. The `log()` function is a little bit special, since it's implemented as a pattern in the Grit pattern matcher, rather than an ordinary function, so we have to special-case it in our node compilers.
> feat(grit): implement GritQL log() function

- Cargo.lock
- crates/biome_service/Cargo.toml
- crates/biome_service/src/workspace.rs
- crates/biome_service/src/workspace/server.rs
- crates/biome_service/src/workspace_types.rs
- crates/biome_wasm/src/lib.rs
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
In the playground, we currently hard code which languages can do what with naive conditions based on the filename. This aims to make it so we don't need to constantly update the playground as file capabilities change.
This also fixes the de/serialization of the `FeatureName` type.
CI should pass. Unsure how to test this with my local version of the playground.
> feat: add additional `FeatureKind` entries for debug features

- crates/biome_html_formatter/src/html/auxiliary/root.rs
- crates/biome_html_formatter/tests/specs/html/attributes/break.html.snap
- crates/biome_html_formatter/tests/specs/html/attributes/no-break.html.snap
- crates/biome_html_formatter/tests/specs/html/attributes/self-closing.html.snap
- crates/biome_html_formatter/tests/specs/html/attributes/single-quotes.html.snap
- crates/biome_html_formatter/tests/specs/html/long-content.html.snap
- crates/biome_html_formatter/tests/specs/html/many-children.html.snap
- crates/biome_html_formatter/tests/specs/html/self-closing.html.snap
Very simple. Prettier always ends files with an extra newline, and so do we with other files.
> feat(formatter/html): add line break at the end of files

- crates/biome_cli/src/panic.rs
Replace PanicInfo -> PanicHookInfo to make dependencies check happy.
n/a
> chore(cli): replace PanicInfo -> PanicHookInfo

- CHANGELOG.md
- crates/biome_graphql_formatter/src/graphql/value/string_value.rs
- crates/biome_graphql_formatter/tests/specs/prettier/graphql/comments/fields.graphql
- crates/biome_graphql_formatter/tests/specs/prettier/graphql/comments/fields.graphql.prettier-snap
Fixes #3924
Previously the formatter tried to format block comments by removing the indentation in those comments, but it forgot to take empty lines into account when calculating and subtracting the indent level.
Also allows the formatter to format line with only spaces and tabs
Added a new test containing block comment with empty lines and lines with only white spaces
> fix(graphql_formatter): panic in block comments with empty line

- Cargo.lock
- clippy.toml
- crates/biome_css_syntax/Cargo.toml
- crates/biome_css_syntax/src/file_source.rs
- crates/biome_graphql_syntax/Cargo.toml
- crates/biome_graphql_syntax/src/file_source.rs
- crates/biome_html_syntax/Cargo.toml
- crates/biome_html_syntax/src/file_source.rs
- crates/biome_js_syntax/Cargo.toml
- crates/biome_js_syntax/src/file_source.rs
- crates/biome_json_syntax/Cargo.toml
- crates/biome_json_syntax/src/file_source.rs
- crates/biome_string_case/src/lib.rs
- crates/biome_yaml_syntax/Cargo.toml
- crates/biome_yaml_syntax/src/file_source.rs
Basically the same ideas as https://github.com/oxc-project/oxc/issues/5586.
Enforce usage of `biome_string_case::StrExtension::to_ascii_lowercase_cow` with Clippy to minimize memory allocation.
All existing tests should pass.
> chore: enforce usage of to_ascii_lowercase_cow

- crates/biome_html_parser/src/lexer/mod.rs
- crates/biome_html_parser/tests/html_specs/ok/attributes/multiline-attribute-value.html
- crates/biome_html_parser/tests/html_specs/ok/attributes/multiline-attribute-value.html.snap
According to the spec, pretty much every character is allowed inside quotes.
https://html.spec.whatwg.org/#attribute-value-(double-quoted)-state
Added a test
> fix(parser/html): allow multi line attribute values

- crates/biome_js_analyze/src/lint/nursery/use_explicit_function_return_type.rs
- crates/biome_js_analyze/tests/specs/nursery/useExplicitFunctionReturnType/invalid.ts
- crates/biome_js_analyze/tests/specs/nursery/useExplicitFunctionReturnType/invalid.ts.snap
- crates/biome_js_analyze/tests/specs/nursery/useExplicitFunctionReturnType/valid.ts
- crates/biome_js_analyze/tests/specs/nursery/useExplicitFunctionReturnType/valid.ts.snap
Related issue: https://github.com/biomejs/biome/issues/2017
Implemented support for direct const assertions in arrow functions in this rule. (`allowDirectConstAssertionInArrowFunctions` in typescript-eslint/explicit-function-return-type)
> feat(linter): support direct const assertions in useExplicitFunctionReturnType rule

- crates/biome_js_analyze/src/lint/complexity/no_excessive_cognitive_complexity.rs
- crates/biome_js_analyze/tests/specs/complexity/noExcessiveCognitiveComplexity/booleanOperators.js.snap
- crates/biome_js_analyze/tests/specs/complexity/noExcessiveCognitiveComplexity/booleanOperators2.js.snap
- crates/biome_js_analyze/tests/specs/complexity/noExcessiveCognitiveComplexity/complexEventHandler.ts.snap
- crates/biome_js_analyze/tests/specs/complexity/noExcessiveCognitiveComplexity/excessiveNesting.js.snap
- crates/biome_js_analyze/tests/specs/complexity/noExcessiveCognitiveComplexity/functionalChain.js.snap
- crates/biome_js_analyze/tests/specs/complexity/noExcessiveCognitiveComplexity/lambdas.js.snap
- crates/biome_js_analyze/tests/specs/complexity/noExcessiveCognitiveComplexity/nestedControlFlowStructures.js.snap
- crates/biome_js_analyze/tests/specs/complexity/noExcessiveCognitiveComplexity/simpleBranches.js.snap
- crates/biome_js_analyze/tests/specs/complexity/noExcessiveCognitiveComplexity/simpleBranches2.js.snap
- crates/biome_js_analyze/tests/specs/complexity/noExcessiveCognitiveComplexity/sumOfPrimes.js.snap
- When running the biome cli, it reports: `Please refactor this function to reduce its complexity score from 17 to the max allowed complexity 15`.
- In the editor, biome reports: `Excessive complexity detected. (biome: lint/complexity/noExcessiveCognitiveComplexity)`
see: https://github.com/biomejs/biome/discussions/4012
This PR simply inserts the levels in the diagnostic message to fix that.
I haven't touched any rust code before, but the change seems straightforward enough, though.
> feat(lsp): `noExcessiveCognitiveComplexity` diagnostic shows levels

- crates/biome_html_parser/src/syntax/mod.rs
- crates/biome_html_parser/tests/html_specs/ok/no-end-tags/param.html
- crates/biome_html_parser/tests/html_specs/ok/no-end-tags/param.html.snap
`param` is one of the void elements a part of HTML 4 originally (I think?), retained for backwards compatibility in HTML 5.
See: https://www.w3.org/TR/2011/WD-html5-author-20110809/the-param-element.html
Tested manually, and against a prettier test that uses that element. Also added a parser snapshot test.
> fix(parser/html): add `param` to void elements list

- crates/biome_html_formatter/src/context.rs
- crates/biome_html_formatter/tests/prettier_tests.rs
- crates/biome_html_formatter/tests/quick_test.rs
- crates/biome_html_formatter/tests/spec_test.rs
- crates/biome_service/src/file_handlers/html.rs
- crates/biome_service/src/file_handlers/mod.rs
- crates/biome_service/src/settings.rs
This PR implements resolving formatter options for HTML.
Tested manually on a local version of the playground. ~~Planning to add tests.~~ I couldn't find an easy way to add snapshot tests for this.
> feat(html): resolve format options

- crates/biome_js_analyze/src/lint/nursery/use_explicit_function_return_type.rs
- crates/biome_js_analyze/tests/specs/nursery/useExplicitFunctionReturnType/invalid.ts
- crates/biome_js_analyze/tests/specs/nursery/useExplicitFunctionReturnType/invalid.ts.snap
- crates/biome_js_analyze/tests/specs/nursery/useExplicitFunctionReturnType/valid.ts
- crates/biome_js_analyze/tests/specs/nursery/useExplicitFunctionReturnType/valid.ts.snap
Related issue: https://github.com/biomejs/biome/issues/2017
Implemented support for allow expressions in useExplicitFunctionReturnType rule. (`allowExpressions` in typescript-eslint/explicit-function-return-type)
> feat(linter): support allow expressions

- Cargo.lock
- crates/biome_grit_syntax/Cargo.toml
- crates/biome_grit_syntax/src/file_source.rs
Replaces a call to `to_ascii_lowercase`
CI should pass
> perf(grit): use `to_ascii_lowercase_cow`

- crates/biome_css_analyze/src/services/semantic.rs
- crates/biome_css_semantic/src/events.rs
- crates/biome_css_semantic/src/semantic_model/builder.rs
- crates/biome_css_semantic/src/semantic_model/mod.rs
- crates/biome_css_semantic/src/semantic_model/model.rs
- crates/biome_text_size/src/range.rs
According to the [profile](https://codspeed.io/biomejs/biome/branches/togami2864:2784), get_rule_by_range and process_selector significantly affect performance.
I implemented the following improvements to address these issues:
- Replaced `FxHashMap` with `BTreeMap`  to search `range_to_rule` more efficiently.
- Used `Cow` to minimize unnecessary memory allocation in `process_selector`
- Removed unused functions.
CI should pass
> perf(linter): performance improvement for css semantic model

- Cargo.lock
- biome.json
- crates/biome_aria/src/lib.rs
- crates/biome_aria_metadata/CONTRIBUTING.md
- crates/biome_aria_metadata/Cargo.toml
- crates/biome_aria_metadata/aria-data.json
- crates/biome_aria_metadata/build.rs
- crates/biome_aria_metadata/src/lib.rs
- packages/aria-data/README.md
- packages/aria-data/aria-data-1-1.json
- packages/aria-data/aria-data-1-2.json
- packages/aria-data/aria-data-1-3-draft.json
- packages/aria-data/generate-aria-data.js
- packages/aria-data/package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
Our ARIA metadata are currently handwritten and mostly based on ARIA 1.1 (some of them are in ARIA 1.2).
Some of these metadata are erroneous or incomplete.
I first started to update them manually. However, this took too much time and it is error-prone.
The aria-query NPM package provides [a JSON file](https://github.com/A11yance/aria-query/blob/main/scripts/roles.json) with the ARIA metadata.
This seems to be manually updated.
I also noticed several issues and some lack of fidelity with the specification (they mix related and base concepts for example).
Thus, I decided to write a script that extracts ARIA metadata directly from the specification.
The script is written in JavaScript and relies on `happy-dom` NPM package that parse the HTML page of the ARIA specification.
I chose …
> refactor(aria_metadata): generate ARIA metadata from specification

- crates/biome_html_factory/src/generated/node_factory.rs
- crates/biome_html_factory/src/generated/syntax_factory.rs
- crates/biome_html_formatter/src/generated.rs
- crates/biome_html_formatter/src/html/any/element.rs
- crates/biome_html_formatter/src/html/auxiliary/comment.rs
- crates/biome_html_formatter/src/html/auxiliary/mod.rs
- crates/biome_html_parser/src/lexer/mod.rs
- crates/biome_html_parser/src/lexer/tests.rs
- crates/biome_html_parser/src/syntax/mod.rs
- crates/biome_html_parser/src/token_source.rs
- crates/biome_html_parser/tests/html_specs/ok/comment.html.snap
- crates/biome_html_syntax/src/generated/kind.rs
- crates/biome_html_syntax/src/generated/macros.rs
- crates/biome_html_syntax/src/generated/nodes.rs
- crates/biome_html_syntax/src/generated/nodes_mut.rs
- crates/biome_html_syntax/src/lib.rs
- crates/biome_parser/src/parsed_syntax.rs
- xtask/codegen/html.ungram
- xtask/codegen/src/html_kinds_src.rs
- xtask/codegen/src/js_kinds_src.rs
This PR changes how comments are parsed such that they are included in the AST as actual nodes, and not just trivia attached to other nodes.
Fixes #4043 (but not the mismatched formatting)
Snapshots updated, CI should pass.
> refactor(parser/html): refactor comments to be nodes in the tree

- crates/biome_cli/src/execute/migrate/eslint_any_rule_to_biome.rs
- crates/biome_configuration/src/analyzer/linter/rules.rs
- crates/biome_diagnostics_categories/src/categories.rs
- crates/biome_js_analyze/src/lint/nursery.rs
- crates/biome_js_analyze/src/lint/nursery/no_nested_ternary.rs
- crates/biome_js_analyze/src/options.rs
- crates/biome_js_analyze/tests/specs/nursery/noNestedTernary/invalid.js
- crates/biome_js_analyze/tests/specs/nursery/noNestedTernary/invalid.js.snap
- crates/biome_js_analyze/tests/specs/nursery/noNestedTernary/valid.js
- crates/biome_js_analyze/tests/specs/nursery/noNestedTernary/valid.js.snap
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
- packages/@biomejs/biome/configuration_schema.json
related discussion: https://github.com/biomejs/biome/discussions/3#discussioncomment-10721971
rule: https://eslint.org/docs/latest/rules/no-nested-ternary
eslint's code: https://github.com/eslint/eslint/blob/main/lib/rules/no-nested-ternary.js
> feat(linter): implement no-nested-ternary

- CHANGELOG.md
- crates/biome_js_analyze/src/lint/a11y/use_button_type.rs
- crates/biome_js_analyze/src/react.rs
- crates/biome_js_analyze/tests/specs/a11y/useButtonType/inObject.js
- crates/biome_js_analyze/tests/specs/a11y/useButtonType/inObject.js.snap
Fix #4072 
This solves two bugs:
1. The `find_prop_by_name` utility only returned quoted property.
For instance `{ "type": foo }` was reported, while `{ type: foo }` was not reported.
2. The rule was always reporting `"type"` property set with any string value, including valid ones.
I have to admit that I was a bit surprised that our JSX rules handle dynamic code such as `React.createElement`. I wonder if we should restrict our rules to JSX and ignore dynamic creation completely.
I took the opportunity of refactoring a bit the flow to make it more readable.
I added a test
> fix(useButtonType): don't report dynamically created button with valid type

- packages/@biomejs/biome/configuration_schema.json
- xtask/codegen/src/generate_schema.rs
> fix(schema): make optional the `options` JSON schema field

- CHANGELOG.md
- crates/biome_js_analyze/src/lint/correctness/no_undeclared_dependencies.rs
- crates/biome_js_analyze/tests/specs/correctness/noUndeclaredDependencies/valid.ts
- crates/biome_js_analyze/tests/specs/correctness/noUndeclaredDependencies/valid.ts.snap
`noUndeclaredDependencies` now ignores NodeJS modules.
> fix(noUndeclaredDependencies): ignore NodeJS modules

- CHANGELOG.md
- crates/biome_js_analyze/src/lint/suspicious/no_misleading_character_class.rs
- crates/biome_js_analyze/tests/specs/suspicious/noMisleadingCharacterClass/invalid.js
- crates/biome_js_analyze/tests/specs/suspicious/noMisleadingCharacterClass/invalid.js.snap
- crates/biome_js_analyze/tests/specs/suspicious/noMisleadingCharacterClass/valid.js
- crates/biome_js_analyze/tests/specs/suspicious/noMisleadingCharacterClass/valid.js.snap
While I was working on #4081, I noticed that the rule was inspecting the entire regex from the start of the first char class.
This PR fixes the issue by checking only char classes.
I have suspicions about other parts of the implementation, notably escape handling.
I left the investigation for later.
I added test.
> fix(noMisleadingCharacterClass): ignore characters outside of char classes

- crates/biome_js_analyze/src/lint/style/use_number_namespace.rs
The https://biomejs.dev/linter/rules/use-number-namespace/ page says `isNan`, but actually [`isNaN`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isNaN), so I fixed it.
No(only docs).
> docs: fix `isNan` to `isNaN`

- CHANGELOG.md
- crates/biome_css_formatter/src/css/auxiliary/query_feature_range_interval.rs
- crates/biome_css_formatter/tests/specs/css/atrule/container.css.snap
- crates/biome_css_formatter/tests/specs/css/atrule/page_complex.css.snap
- crates/biome_css_formatter/tests/specs/css/nesting/conditional_at_rule.css.snap
Resolving issue #4076 highlighted by @nstepien 
- I was able to pinpoint where the format originated from.
- Added the missing space() which should implement the desired format
> fix: updated query feature range interval format

- CHANGELOG.md
- crates/biome_js_analyze/src/lint/suspicious/no_control_characters_in_regex.rs
- crates/biome_js_analyze/src/lint/suspicious/no_misleading_character_class.rs
- crates/biome_js_analyze/tests/specs/suspicious/noControlCharactersInRegex/valid.js
- crates/biome_js_analyze/tests/specs/suspicious/noControlCharactersInRegex/valid.js.snap
- crates/biome_js_analyze/tests/specs/suspicious/noMisleadingCharacterClass/invalid.js.snap
- crates/biome_js_analyze/tests/specs/suspicious/noMisleadingCharacterClass/valid.js
- crates/biome_js_analyze/tests/specs/suspicious/noMisleadingCharacterClass/valid.js.snap
- crates/biome_text_size/src/range.rs
This PR fixes erroneous handling of escape sequence.
This was a hard fix/refactor because Unicode escape sequence is hard to handle in both regex strings and regex literals. I still think that we should remove support for string regexes in this rule and `noControlCharacterInRegex`. This brings a lot of complexity for a minor improvement in linting.
Also, I fixed `noControlCharacterInRegex`: the rule no longer panics on incomplete Unicode escape sequences.
I also improved the diagnostics message and refactored the code to allow reporting the precise range of the problematic characters.
To do that I had to compute codepoint on demand instead of “evaluating” the string.
This also avoids a string allocation.
I added missing combining characters: Mongolian Free Variation Selector and Variation …
> fix(noMisleadingCharacterClass): properly handle escaping and improve diagnostics

- crates/biome_js_analyze/src/lint/nursery/use_explicit_function_return_type.rs
- crates/biome_js_analyze/tests/specs/nursery/useExplicitFunctionReturnType/invalid.ts
- crates/biome_js_analyze/tests/specs/nursery/useExplicitFunctionReturnType/invalid.ts.snap
- crates/biome_js_analyze/tests/specs/nursery/useExplicitFunctionReturnType/valid.ts
- crates/biome_js_analyze/tests/specs/nursery/useExplicitFunctionReturnType/valid.ts.snap
related: https://github.com/biomejs/biome/issues/2017
This PR introduces the ability to detect higher-order functions in the `useExplicitFunctionReturnType` rule, specifically functions that return other functions.
Nested statement handling is not implemented: The current implementation does not cover cases where functions are returned inside conditional or branching logic (e.g., if statements or switch statements). 
Example of unsupported case:
```
function example() {
if (condition) {
return function() {}; // This return inside the 'if' statement is not detected
}
}
```
Should biome support nested statements like if or switch when checking for higher-order functions? 
This would involve inspecting return statements within those control structures, adding complexity but potentially …
> feat(useExplicitFunctionReturnType): support higher-order function

- Cargo.lock
- xtask/bench/Cargo.toml
- xtask/bench/benches/gritql_search.rs
Adds benchmarks for GritQL query execution. Runs against the same libs as TypeScript benches.
> chore: setup GritQL benchmark

- CHANGELOG.md
- crates/biome_analyze/CONTRIBUTING.md
- crates/biome_js_analyze/src/lint/a11y/no_label_without_control.rs
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
- packages/@biomejs/biome/configuration_schema.json
Closes https://github.com/biomejs/biome/issues/4125
I updated the contribution guide too. I took the opportunity to do some small refactor, and move functions inside the options struct, so we don't pass around the same object.
CI should pass. I checked the code generated files manually.
> fix(lint): options for `noLabelWithoutControl` are optional

- crates/biome_css_analyze/src/lint/suspicious/no_shorthand_property_overrides.rs
- crates/biome_css_analyze/src/utils.rs
Removing unnecessary memory allocations for the performance
CI should pass
> perf(linter): remove unneeded memory allocation for str

- CHANGELOG.md
- crates/biome_css_analyze/src/lint/nursery/no_descending_specificity.rs
- crates/biome_js_analyze/src/lint/nursery/no_nested_ternary.rs
- crates/biome_js_analyze/src/lint/nursery/no_octal_escape.rs
- crates/biome_js_analyze/src/lint/nursery/no_template_curly_in_string.rs
- crates/biome_js_analyze/src/lint/nursery/use_explicit_function_return_type.rs
- packages/@biomejs/biome/package.json
- packages/@biomejs/js-api/package.json
- packages/@biomejs/wasm-nodejs/package.json
We are preparing the release, and we will ship it once we fixed some critical bugs. 
CI should pass
> release: v1.9.3

- crates/biome_js_analyze/src/lint/a11y/use_semantic_elements.rs
Add missing word for the message from useSemanticElements.
> fix: add missing word

- CHANGELOG.md
- crates/biome_js_analyze/src/lint/correctness/use_exhaustive_dependencies.rs
- crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/reportMissingDependenciesArray.js
- crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/reportMissingDependenciesArray.js.snap
- crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/reportMissingDependenciesArray.options.json
- crates/biome_service/tests/invalid/hooks_incorrect_options.json.snap
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
- packages/@biomejs/biome/configuration_schema.json
Continuation of https://github.com/biomejs/biome/issues/630. Makes the behaviour disabled [here](https://github.com/biomejs/biome/issues/608) optional.
Adds an option `reportMissingDependenciesArray` to catch extra re-renders caused by missing dependency arrays.
```
// this config
"useExhaustiveDependencies": {
"reportMissingDependenciesArray": true,
}
// causes this to be an error
function ReportMissingDependenciesArray() {
const [a] = useState("hello");
useEffect(() => {
console.log(a); // <- runs every render
});
return <div/>;
}
```
Also added changelog entry for this and for https://github.com/biomejs/biome/issues/630.
A unit test is added
> feat(useExhaustiveDependencies): add option to useExhaustiveDependencies to enable errors when the dependencies array is missing

- crates/biome_js_analyze/src/lint/a11y/use_valid_aria_role.rs
- crates/biome_js_analyze/src/lint/complexity/no_useless_this_alias.rs
fix typo in examples
nonIgnoreDom -> ignoreNonDom
using schemas 1.9.3
> chore: correct options name (ignoreNonDom) in the examples

- crates/biome_js_analyze/src/lint/nursery/no_template_curly_in_string.rs
The website isn't deploying anymore because of a build issue.
The issue was caused by using a template literal syntax wasn't wrapped in a code block.
Merge it, and the new website should be deployed.
> docs: use code blocks to avoid rendering issue on the website

- CHANGELOG.md
- crates/biome_js_factory/src/utils.rs
Fix #4181
I added some tests to avoid any regression.
> fix(js): don't panic when escaping a string

- crates/biome_cli/src/execute/migrate/eslint_any_rule_to_biome.rs
- crates/biome_configuration/src/analyzer/linter/rules.rs
- crates/biome_diagnostics_categories/src/categories.rs
- crates/biome_js_analyze/src/lint/nursery.rs
- crates/biome_js_analyze/src/lint/nursery/no_img_element.rs
- crates/biome_js_analyze/src/options.rs
- crates/biome_js_analyze/tests/specs/nursery/noImgElement/invalid.jsx
- crates/biome_js_analyze/tests/specs/nursery/noImgElement/invalid.jsx.snap
- crates/biome_js_analyze/tests/specs/nursery/noImgElement/valid.jsx
- crates/biome_js_analyze/tests/specs/nursery/noImgElement/valid.jsx.snap
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
- packages/@biomejs/biome/configuration_schema.json
Implement [no-img-element](https://nextjs.org/docs/messages/no-img-element) from eslint-plugin-next.
Snapshots + CI
> feat(lint): add `noImgElement` rule

- CHANGELOG.md
- crates/biome_css_analyze/src/lint/nursery/no_missing_var_function.rs
- crates/biome_css_analyze/tests/specs/nursery/noMissingVarFunction/valid.css
- crates/biome_css_analyze/tests/specs/nursery/noMissingVarFunction/valid.css.snap
Closes #4190 
We were not using `text_trimmed()` to check the `var` text. Instead, we were using `text`.
____
cc @Conaclos I moved a changelog paragraph. It was incorrectly listed as a linter fix, but it was a parser fix.
> fix(linter): false positive

- crates/biome_cli/src/changed.rs
- crates/biome_cli/src/commands/check.rs
- crates/biome_cli/src/commands/ci.rs
- crates/biome_cli/src/commands/format.rs
- crates/biome_cli/src/commands/lint.rs
- crates/biome_cli/src/commands/mod.rs
- crates/biome_cli/src/lib.rs
The CLI that runs the commands has become very repeated. I had attempted few refactors before, and eventually landed on this one. 
As for now, this refactor only touches the `format` command, to show how it has become. We can discuss the architecture here, and one we merge this PR, I will refactor the rest of the commands.
We now have a `CommandRunner` trait that all the payloads need to implement in order to be run. Eventually, only the `run` command is called, then the rest is just repeated logic that was moved from `format.rs`.
With a trait, now the bulk of the logic lives inside one single function, and it is shared among commands. This should reduce the repeated work, especially when we add new CLI options that affect multiple commands e.g. VCS integration.
When merging the …
> refactor(cli): use command runner to run predictable logic

- crates/biome_analyze/src/rule.rs
- crates/biome_cli/src/commands/check.rs
- crates/biome_cli/src/commands/ci.rs
- crates/biome_cli/src/commands/format.rs
- crates/biome_cli/src/commands/lint.rs
- crates/biome_cli/src/commands/migrate.rs
- crates/biome_cli/src/commands/mod.rs
- crates/biome_cli/src/commands/search.rs
- crates/biome_cli/src/execute/mod.rs
- crates/biome_cli/src/lib.rs
- crates/biome_cli/tests/snapshots/main_commands_check/fs_files_ignore_symlink.snap
- crates/biome_cli/tests/snapshots/main_commands_ci/ci_errors_for_all_disabled_checks.snap
- crates/biome_cli/tests/snapshots/main_commands_migrate/emit_diagnostic_for_rome_json.snap
- crates/biome_cli/tests/snapshots/main_commands_migrate/should_create_biome_json_file.snap
- crates/biome_css_analyze/src/utils.rs
This PR migrates the majority of commands to use the `CommandRunner` trait.
I also created a new trait called `LoadEditorConfig` to share the same logic only for the `format`, `check` and `ci` commands, where we load the `.editorconfig` file.
Current CI should work. Checked that the updated snapshots are correct.
> refactor(cli): command runner

- CHANGELOG.md
- crates/biome_js_analyze/src/lint/nursery/use_sorted_classes.rs
- crates/biome_js_analyze/src/lint/nursery/use_sorted_classes/sort.rs
- crates/biome_js_analyze/tests/quick_test.rs
- crates/biome_js_analyze/tests/specs/nursery/useSortedClasses/issue_4041.jsx
- crates/biome_js_analyze/tests/specs/nursery/useSortedClasses/issue_4041.jsx.snap
Closes https://github.com/biomejs/biome/issues/4041
> fix(linter): `useSortedClasses` false positive

- CHANGELOG.md
- crates/biome_analyze/src/lib.rs
- crates/biome_js_analyze/tests/specs/correctness/noUnreachable/SuppressionComments.js.snap
- crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/ignoredDependencies.js.snap
The previous message says "Suppression comment is unused". This is confusing for some users because you "use" suppression comments to suppress diagnostics (aka the effect), but the message is telling them it's not being "used". The previous message also does not explain how to resolve the issue at all.
> fix(analyze): improve diagnostic message for unused suppression comments

- crates/biome_js_analyze/src/lint/nursery/use_explicit_function_return_type.rs
- crates/biome_js_analyze/tests/specs/nursery/useExplicitFunctionReturnType/invalid.ts
- crates/biome_js_analyze/tests/specs/nursery/useExplicitFunctionReturnType/invalid.ts.snap
- crates/biome_js_analyze/tests/specs/nursery/useExplicitFunctionReturnType/valid.ts
- crates/biome_js_analyze/tests/specs/nursery/useExplicitFunctionReturnType/valid.ts.snap
related: https://github.com/biomejs/biome/issues/2017
This PR introduces the ability to detect typed function expressions in the useExplicitFunctionReturnType rule.
todos:
```
const asTyped = (() => '') as () => string;
const castTyped = <() => string>(() => '');
```
```
type FuncType = () => string;
const arrowFn: FuncType = () => 'test';
```
```
type CallBack = () => void;
const f = (gotcha: CallBack = () => { }): void => { };
```
```
type MethodType = () => void;
class App {
private method: MethodType = () => { };
}
```
```
const x: Foo = { prop: () => {} }
const x = { prop: () => {} } as Foo
const x = <Foo>{ prop: () => {} }
const x: Foo = { bar: { prop: () => {} } }
```
> feat(useExplicitFunctionReturnType): support typed function expressions

- crates/biome_grit_patterns/src/grit_built_in_functions.rs
- crates/biome_grit_patterns/src/grit_resolved_pattern.rs
Appears to give a few percent performance boost.
> chore(grit): don't use `im::Vector` where we don't have to

- CHANGELOG.md
- crates/biome_js_analyze/src/lint/complexity/no_useless_fragments.rs
- crates/biome_js_analyze/src/lint/style/use_export_type.rs
- crates/biome_js_analyze/src/lint/style/use_import_type.rs
- crates/biome_js_analyze/tests/specs/style/useExportType/invalid.ts
- crates/biome_js_analyze/tests/specs/style/useExportType/invalid.ts.snap
- crates/biome_js_analyze/tests/specs/style/useExportType/valid.ts
- crates/biome_js_analyze/tests/specs/style/useExportType/valid.ts.snap
- crates/biome_js_analyze/tests/specs/style/useImportType/invalid-combined.ts.snap
- crates/biome_js_analyze/tests/specs/style/useImportType/invalid-default-imports.ts.snap
- crates/biome_js_analyze/tests/specs/style/useImportType/invalid-named-imports.ts.snap
- crates/biome_js_analyze/tests/specs/style/useImportType/invalid-namesapce-imports.ts.snap
- crates/biome_js_analyze/tests/specs/style/useImportType/invalid-unused-react-types.tsx.snap
- crates/biome_js_analyze/tests/specs/style/useImportType/valid-unused-react-combined.tsx.snap
This is a followup of #4201 that concerns exports.
This suggests the following fixes:
```diff
- export type { type C, D };
+ export type { C, D };
```
This also bring the following suggestion:
```diff
- export { type A, type B } from "";
+ export type { A, B } from "";
```
Also, I took the opportunity of harmonizing diagnostics between `useExportType` and `useImportType`.
> fix(useExportType): remove useless inline type exports

- .github/ISSUE_TEMPLATE/01_formatter_bug.yml
- .github/ISSUE_TEMPLATE/02_lint_bug.yml
- .github/ISSUE_TEMPLATE/03_bug.yml
- .github/workflows/close-issue.yml
- .github/workflows/needs-repro.yml
I took inspiration from the Astro workflow, and I like it.
This PR adds three two workflows: 
- One that writes a comment when we use the label `S-Needs repro`. When this label is added to an issue, an automatic message is sent and asks the user to provide a reproduction.
- One that closes issues that have the `S-Needs repro` label, and they are inactive for three days.
- One that removes the label `S-Needs triage` once the label `S-Bug confirmed` is added
I also update the issue templates with the correct label to assign (which I just created)
Merge and check
> ci: automatic issue closer

- crates/biome_js_analyze/src/lint/style/use_naming_convention.rs
This PR replaces the occurrence of "cas eof" in the [`useNamingConvention` documentation](https://biomejs.dev/linter/rules/use-naming-convention/#ignored-declarations) to "case of".
N/A
> docs(useNamingConvention): fix typo cas eof -> case of

- CHANGELOG.md
- Cargo.lock
- crates/biome_grit_patterns/Cargo.toml
- crates/biome_grit_patterns/src/grit_binding.rs
- crates/biome_grit_patterns/src/grit_built_in_functions.rs
- crates/biome_grit_patterns/src/grit_code_snippet.rs
- crates/biome_grit_patterns/src/grit_context.rs
- crates/biome_grit_patterns/src/grit_file.rs
- crates/biome_grit_patterns/src/grit_node.rs
- crates/biome_grit_patterns/src/grit_node_patterns.rs
- crates/biome_grit_patterns/src/grit_query.rs
- crates/biome_grit_patterns/src/grit_resolved_pattern.rs
- crates/biome_grit_patterns/src/grit_target_node.rs
- crates/biome_grit_patterns/src/pattern_compiler/accumulate_compiler.rs
- crates/biome_grit_patterns/src/pattern_compiler/as_compiler.rs
- crates/biome_grit_patterns/src/pattern_compiler/auto_wrap.rs
- crates/biome_grit_patterns/src/pattern_compiler/bubble_compiler.rs
- crates/biome_grit_patterns/src/pattern_compiler/call_compiler.rs
- crates/biome_grit_patterns/src/pattern_compiler/compilation_context.rs
- crates/biome_grit_patterns/src/pattern_compiler/log_compiler.rs
- crates/biome_grit_patterns/src/pattern_compiler/not_compiler.rs
- crates/biome_grit_patterns/src/pattern_compiler/pattern_definition_compiler.rs
- crates/biome_grit_patterns/src/pattern_compiler/snippet_compiler.rs
- crates/biome_grit_patterns/src/pattern_compiler/step_compiler.rs
- crates/biome_grit_patterns/src/pattern_compiler/variable_compiler.rs
- crates/biome_grit_patterns/src/variables.rs
Upgrades Grit crates to 0.4. Main difference is a change I made to [remove the `im` crate](https://github.com/getgrit/gritql/pull/536) as a dependency entirely. This resulted in a rougly 25-30% performance improvement in our Grit benchmarks, at least locally.
Another nice effect is that our `biome_grit_patterns` crate no longer depends on `anyhow`, though other Biome crates still do.
> perf: upgrade Grit and remove `im` crate

- CHANGELOG.md
- crates/biome_cli/src/execute/migrate/eslint_any_rule_to_biome.rs
- crates/biome_configuration/src/analyzer/linter/rules.rs
- crates/biome_diagnostics_categories/src/categories.rs
- crates/biome_js_analyze/src/lint/nursery.rs
- crates/biome_js_analyze/src/lint/nursery/use_guard_for_in.rs
- crates/biome_js_analyze/src/options.rs
- crates/biome_js_analyze/tests/specs/nursery/useGuardForIn/invalid.js
- crates/biome_js_analyze/tests/specs/nursery/useGuardForIn/invalid.js.snap
- crates/biome_js_analyze/tests/specs/nursery/useGuardForIn/valid.js
- crates/biome_js_analyze/tests/specs/nursery/useGuardForIn/valid.js.snap
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
- packages/@biomejs/biome/configuration_schema.json
> feat(linter): support useGuardForIn

- CHANGELOG.md
- crates/biome_js_analyze/tests/specs/correctness/noUnusedFunctionParameters/issue4227.ts
- crates/biome_js_analyze/tests/specs/correctness/noUnusedFunctionParameters/issue4227.ts.snap
- crates/biome_js_semantic/src/events.rs
- crates/biome_js_semantic/src/semantic_model/builder.rs
> fix(noUnusedFunctionParameters): ignore parameter in constructor types

- crates/biome_grit_formatter/src/grit/predicates/predicate_and.rs
- crates/biome_grit_formatter/src/grit/predicates/predicate_assignment.rs
- crates/biome_grit_formatter/tests/specs/grit/patterns/where_pattern.grit.snap
- crates/biome_grit_formatter/tests/specs/grit/predicates/assignment.grit
- crates/biome_grit_formatter/tests/specs/grit/predicates/assignment.grit.snap
For #2476 
Implements the `GritPredicateAnd` and `GritPredicateAssignment` formatting rules.
Snapshot tests generate the desired formatting for assignments
> feat(format/grit): add formatting for predicate assignment and predicate and

- .github/workflows/benchmark.yml
- .github/workflows/main.yml
- .github/workflows/pull_request.yml
- .github/workflows/pull_request_js.yml
The `next` branch serves as preparation for the 2.0 release, and deserves the same protections as our `main` for now.
> chore: run CI workflows on and against `next` branch

- crates/biome_js_analyze/src/lint/nursery/no_document_cookie.rs
- crates/biome_js_analyze/tests/specs/nursery/noDocumentCookie/invalid.js
- crates/biome_js_analyze/tests/specs/nursery/noDocumentCookie/invalid.js.snap
- crates/biome_js_analyze/tests/specs/nursery/noDocumentCookie/valid.js
- crates/biome_js_analyze/tests/specs/nursery/noDocumentCookie/valid.js.snap
This is followup PR to #4204 .
This PR extends the implementation of `noDocumentCookie` by adding support for tracking assignments to variables.
Now, the following code will be supported.
```js
const doc = document;
doc.cookie = "foo = bar";
```
- Added tests to verify the handling of variable assignments.
> feat(lint): add variable assignment tracking to `noDocumentCookie` rule

- CHANGELOG.md
- Cargo.lock
- crates/biome_js_analyze/src/lint/style/use_filenaming_convention.rs
- crates/biome_js_analyze/tests/specs/style/useFilenamingConvention/Invalid_Renamed_Export.js
- crates/biome_js_analyze/tests/specs/style/useFilenamingConvention/Invalid_Renamed_Export.js.snap
- crates/biome_js_analyze/tests/specs/style/useFilenamingConvention/Valid_Renamed_Export.js
- crates/biome_js_analyze/tests/specs/style/useFilenamingConvention/Valid_Renamed_Export.js.snap
- crates/biome_js_analyze/tests/specs/style/useFilenamingConvention/Valid_Renamed_Export.snap
- crates/biome_js_semantic/Cargo.toml
- crates/biome_js_semantic/src/semantic_model/binding.rs
- crates/biome_js_semantic/src/semantic_model/builder.rs
- crates/biome_js_semantic/src/semantic_model/model.rs
Fix #4254
To fix the issue, I added to the semantic model the capability of retrieving exports of a given binding.
Unfortunately, this adds 24 bytes of overhead to every binding data.
It should be possible to remove this overhead by distinguishing between read and export references.
However, this is a bigger change than the one I introduced here.
I left it for a future PR, unless the perf impact is visible.
Also, I took the opportunity of introducing a small optimization: instead of iterating over all bindings, we now iterate only over bindings that are actually exported.
> fix(useFilenamingConvention): take export renaming into account

- CHANGELOG.md
- crates/biome_cli/src/execute/migrate/eslint_any_rule_to_biome.rs
- crates/biome_configuration/src/analyzer/linter/rules.rs
- crates/biome_diagnostics_categories/src/categories.rs
- crates/biome_js_analyze/src/lint/nursery.rs
- crates/biome_js_analyze/src/lint/nursery/no_document_import_in_page.rs
- crates/biome_js_analyze/src/options.rs
- crates/biome_js_analyze/tests/specs/nursery/noDocumentImportInPage/app/valid.jsx
- crates/biome_js_analyze/tests/specs/nursery/noDocumentImportInPage/app/valid.jsx.snap
- crates/biome_js_analyze/tests/specs/nursery/noDocumentImportInPage/pages/_document.jsx
- crates/biome_js_analyze/tests/specs/nursery/noDocumentImportInPage/pages/_document.jsx.snap
- crates/biome_js_analyze/tests/specs/nursery/noDocumentImportInPage/pages/invalid.jsx
- crates/biome_js_analyze/tests/specs/nursery/noDocumentImportInPage/pages/invalid.jsx.snap
- crates/biome_js_analyze/tests/specs/nursery/noDocumentImportInPage/valid.jsx
- crates/biome_js_analyze/tests/specs/nursery/noDocumentImportInPage/valid.jsx.snap
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
- packages/@biomejs/biome/configuration_schema.json
Implement [no-document-import-in-page](https://nextjs.org/docs/messages/no-document-import-in-page) from eslint-plugin-next.
Snapshots + CI
> feat(lint): add `noDocumentImportInPage` rule

- .changeset/reduced_accepted_values.md
- .changeset/reduced_accepted_values_for_js_options.md
- .changeset/reduced_accepted_values_of_options.md
- crates/biome_formatter/src/lib.rs
- crates/biome_js_formatter/src/context.rs
- crates/biome_js_formatter/src/context/trailing_commas.rs
Closes https://github.com/biomejs/biome/issues/3619
We don't have tests for these cases, however I felt having a changeset was more appropriate.
> fix: reduce accepted values for options

- CHANGELOG.md
- crates/biome_js_analyze/src/lint/style/use_naming_convention.rs
- crates/biome_js_analyze/tests/specs/style/useNamingConvention/invalidIndexParameter.ts
- crates/biome_js_analyze/tests/specs/style/useNamingConvention/invalidIndexParameter.ts.snap
- crates/biome_js_analyze/tests/specs/style/useNamingConvention/validIndexParameter.ts
- crates/biome_js_analyze/tests/specs/style/useNamingConvention/validIndexParameter.ts.snap
- crates/biome_js_syntax/src/modifier_ext.rs
Does not change any defaults, and adds a changelog entry. Closes #4277.
Updated snapshots to include `readonly` index signatures.
> fix(lint): allow readonly modifier on indexParameter in `useNamingConvention`

- CHANGELOG.md
- crates/biome_configuration/src/analyzer/linter/rules.rs
- crates/biome_diagnostics_categories/src/categories.rs
- crates/biome_js_analyze/src/lint/nursery.rs
- crates/biome_js_analyze/src/lint/nursery/no_useless_string_raw.rs
- crates/biome_js_analyze/src/options.rs
- crates/biome_js_analyze/tests/specs/nursery/noUselessStringRaw/invalid.js
- crates/biome_js_analyze/tests/specs/nursery/noUselessStringRaw/invalid.js.snap
- crates/biome_js_analyze/tests/specs/nursery/noUselessStringRaw/valid.js
- crates/biome_js_analyze/tests/specs/nursery/noUselessStringRaw/valid.js.snap
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
- packages/@biomejs/biome/configuration_schema.json
> feat(linter): implement noUselessStringRaw

- CHANGELOG.md
- crates/biome_js_parser/src/syntax/module.rs
- crates/biome_js_parser/test_data/inline/err/import_defer_clause.js
- crates/biome_js_parser/test_data/inline/err/import_defer_clause.rast
follow up the pr: https://github.com/biomejs/biome/pull/4301
> chore: add more test case for defer import parser

- CHANGELOG.md
- crates/biome_js_analyze/src/lint/suspicious/no_suspicious_semicolon_in_jsx.rs
- crates/biome_js_analyze/tests/specs/suspicious/noSuspiciousSemicolonInJsx/invalid.jsx
- crates/biome_js_analyze/tests/specs/suspicious/noSuspiciousSemicolonInJsx/invalid.jsx.snap
Closes https://github.com/biomejs/biome/issues/4226
Catch suspicious semicolon in react fragment.
Test case added,
```jsx
const Component4 = () => {
return (
<>
<div />;
</>
);
}
const Component5 = () => {
return (
<>
<Component>
<div />
</Component>;
</>
);
}
```
> fix(lint/noSuspiciousSemicolonInJsx): catch suspicious semicolon in fragment

- crates/biome_deserialize_macros/src/deserializable_derive.rs
- crates/biome_js_analyze/src/lint/style/use_filenaming_convention.rs
This brings the implementation of `useFilenamingConvention` closer to the implementation of `useNamingConvention`. We now use internally the `Cases` bit flags.
This should marginally improve file case checking performance.
Also, I had to fix some bugs in `biome_deserialize_macros` related to validators.
CI must pass.
> refactor(useFilenamingConvention): use the Cases bit flags for filename cases

- CHANGELOG.md
- crates/biome_cli/src/execute/migrate/eslint_typescript.rs
- crates/biome_cli/src/execute/migrate/eslint_unicorn.rs
- crates/biome_js_analyze/src/lint/style/use_filenaming_convention.rs
- crates/biome_js_analyze/src/lint/style/use_naming_convention.rs
- crates/biome_js_analyze/src/utils.rs
- crates/biome_js_analyze/src/utils/restricted_regex.rs
- crates/biome_js_analyze/tests/specs/style/useFilenamingConvention/%validMatch.options.json
- crates/biome_js_analyze/tests/specs/style/useFilenamingConvention/%validMatch.ts
- crates/biome_js_analyze/tests/specs/style/useFilenamingConvention/%validMatch.ts.snap
- crates/biome_js_analyze/tests/specs/style/useFilenamingConvention/invalidMatch.js
- crates/biome_js_analyze/tests/specs/style/useFilenamingConvention/invalidMatch.js.snap
- crates/biome_js_analyze/tests/specs/style/useFilenamingConvention/invalidMatch.options.json
- crates/biome_js_analyze/tests/specs/style/useFilenamingConvention/invalidMatchExtension.INVALID.js.snap
- crates/biome_js_analyze/tests/specs/style/useFilenamingConvention/invalidMatchExtension.INVALID.options.json
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
- packages/@biomejs/biome/configuration_schema.json
Close #4105
This PR implements a new option named `match` that allows validating a filename thanks to a regular expression.
Similarly to `useNamingConvention`, we rely on the `RestrictedRegex` type that allow to use a common subset of patterns between JS and Rust regexes.
If the regex captures strings then:
- the first capture is considered as the name of the file
- the second captures is considered as the extensions of the file (dot separated).
- Following captures are ignored.
For example, given the regular expression `%?(.+?)\.(.+)` and the filename `%index.d.ts`,
the filename matches the regular expression with two captures: `index` and `d.ts`.
The name `index` and the extensions `d`, `ts` are then checked against the `filenameCases` option.
I added new tests.
> feat(useFilenamingConvention): add the match option

- crates/biome_grit_formatter/src/grit/auxiliary/like.rs
- crates/biome_grit_formatter/src/grit/lists/predicate_list.rs
- crates/biome_grit_formatter/src/grit/predicates/predicate_accumulate.rs
- crates/biome_grit_formatter/src/grit/predicates/predicate_match.rs
- crates/biome_grit_formatter/src/grit/predicates/predicate_rewrite.rs
- crates/biome_grit_formatter/src/lib.rs
- crates/biome_grit_formatter/src/prelude.rs
- crates/biome_grit_formatter/src/separated.rs
- crates/biome_grit_formatter/tests/specs/grit/patterns/create_new_files.grit
- crates/biome_grit_formatter/tests/specs/grit/patterns/create_new_files.grit.snap
Add the ability to handle multi-line patterns that are separated with commas.
Added simple formatting rules for:
- accumulator predicate
- match predicate
- rewrite predicate
Snapshot tests demonstrate correct formatting
> feat(format/grit): add logic for formatting with separators and other predicates

- CHANGELOG.md
- crates/biome_js_analyze/src/lint/style/use_filenaming_convention.rs
- crates/biome_js_analyze/src/lint/style/use_naming_convention.rs
- crates/biome_js_analyze/src/utils/restricted_regex.rs
The [Regular Expression Pattern Modifiers proposal](https://github.com/tc39/proposal-regexp-modifiers) is now at Stage 4.
This PR adds support for `i`, `m` and `s` pattern modifiers in Restricted Regexes.
This allows users to create case-insensitive regexes.
> refactor(restricted-regex): accept non-capturing groups with flags

- Cargo.lock
- Cargo.toml
- crates/biome_analyze/src/rule.rs
- crates/biome_configuration/src/diagnostics.rs
- crates/biome_configuration/src/lib.rs
- crates/biome_configuration/src/plugins.rs
- crates/biome_diagnostics_categories/src/categories.rs
- crates/biome_fs/src/fs.rs
- crates/biome_grit_patterns/Cargo.toml
- crates/biome_js_analyze/src/lint/nursery/use_collapsed_if.rs
- crates/biome_parser/src/lib.rs
- crates/biome_plugin_loader/Cargo.toml
- crates/biome_plugin_loader/src/analyzer_grit_plugin.rs
- crates/biome_plugin_loader/src/analyzer_plugin.rs
- crates/biome_plugin_loader/src/diagnostics.rs
- crates/biome_plugin_loader/src/lib.rs
- crates/biome_plugin_loader/src/plugin_manifest.rs
- crates/biome_plugin_loader/src/snapshots/deserialization_error.snap
- crates/biome_plugin_loader/src/snapshots/load_plugin_with_wrong_rule_extension.snap
- crates/biome_plugin_loader/src/snapshots/load_plugin_with_wrong_version.snap
- crates/biome_plugin_loader/src/snapshots/load_plugin_without_manifest.snap
- crates/biome_service/src/file_handlers/css.rs
- crates/biome_service/src/file_handlers/json.rs
- crates/biome_test_utils/src/lib.rs
- knope.toml
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
- packages/@biomejs/biome/configuration_schema.json
Continuation of https://github.com/biomejs/biome/pull/4071
Note this doesn't integrate the plugins into the analyzer yet, like the previous one did. This just makes sure they load as we want them to.
Tests added. CI should remain green.
> feat: plugin loader

- crates/biome_formatter/src/macros.rs
- crates/biome_js_analyze/src/lint/correctness/no_flat_map_identity.rs
- crates/biome_suppression/src/lib.rs
- rust-toolchain.toml
Upgrade to stable Rust 1.82.0 while suppressing clippy errors.
> build: upgrade to rust 1.82.0

- crates/biome_plugin_loader/src/lib.rs
Should fix the snapshot tests on the Windows runner.
> chore: normalize Windows paths in plugin tests

- crates/biome_js_analyze/src/lint/nursery/use_at_index.rs
I looked through the changelog and checked the new rules to determine if they might be relevant to my project. In the documentation for the new `useAtIndex` rule (https://biomejs.dev/linter/rules/use-at-index) I noticed a typo at first glance, so I thought it might be a good idea to fix it right away. The typo was introduced in https://github.com/biomejs/biome/pull/4120#discussion_r1790270327
N/A
> docs(useAtIndex): fix typo chatAt -> charAt

- CHANGELOG.md
- crates/biome_js_analyze/src/syntax/correctness/no_initializer_with_definite.rs
- crates/biome_js_analyze/src/syntax/correctness/no_type_only_import_attributes.rs
- crates/biome_js_analyze/tests/spec_tests.rs
- crates/biome_js_analyze/tests/specs/correctness/noTypeOnlyImportAttributes/valid.cts
- crates/biome_js_analyze/tests/specs/correctness/noTypeOnlyImportAttributes/valid.cts.snap
- crates/biome_js_analyze/tests/specs/correctness/noTypeOnlyImportAttributes/valid_cjs.package.json
- crates/biome_js_syntax/src/file_source.rs
Fix https://github.com/biomejs/biome/issues/4361
`noTypeOnlyImportAttributes` reports `import type` with `import attributes` because this is a syntax error in TypeScript.
However, since TypeScript 5.3, [this is allowed in CommonJS files](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-3.html#stable-support-resolution-mode-in-import-types).
This PR makes `noTypeOnlyImportAttributes` to ignore files ending the `.cts` extension.
I notes that the test snapshot outputted the wrong  Markdown language (`ts` instead of `cts`). Thus, I changed how we output the Markdown language in tests in order to output `cts` for `cts` files. As a side effect this also translates `mts` to `cts`. However, we have no test using this extension and this should not create any issue.
I added a …
> fix(noTypeOnlyImportAttributes): ignore .cts files

- crates/biome_js_analyze/src/utils/restricted_glob.rs
In the [import revamping RFC](https://github.com/biomejs/biome/discussions/3015), I proposed that each group be represented by a special identifier or a glob.
For example in the following list we have two groups:
```json5
{
groups: [
"@myCompany/**"
"@*/**"
]
}
```
This will place all imports starting with `@myCompany/` before all other scoped imports.
Unfortunately, as noted by a [comment in the RFC](https://github.com/biomejs/biome/discussions/3015#discussioncomment-9586004), this doesn't allow doing the reverse, i.e. placing first all coped imports (except the ones starting with `@myCompany/`).
At the time, I thought about a [recursive approach](https://github.com/biomejs/biome/discussions/3015#discussioncomment-9639600) to solve this limitation.
However, this looks complicated and …
> feat(restricted_glob): negated globs

- .changeset/use_new_workspace_apis.md
- crates/biome_analyze/src/categories.rs
- crates/biome_css_syntax/src/file_source.rs
- crates/biome_diagnostics/src/suggestion.rs
- crates/biome_formatter/src/lib.rs
- crates/biome_fs/src/path.rs
- crates/biome_graphql_syntax/src/file_source.rs
- crates/biome_js_syntax/src/file_source.rs
- crates/biome_json_syntax/src/file_source.rs
- crates/biome_plugin_loader/src/plugin_manifest.rs
- crates/biome_service/src/workspace.rs
- knope.toml
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
- packages/@biomejs/backend-jsonrpc/tests/workspace.test.mjs
- packages/@biomejs/js-api/src/index.ts
- packages/@biomejs/js-api/tests/lintContent.test.ts
- packages/@biomejs/js-api/tests/printDiagnostics.test.ts
- packages/@biomejs/wasm-nodejs/package.json
Closes https://github.com/biomejs/biome/issues/4366
All fields are now camel case. 
This will break the playground, which means that we need to update it once `next` is merged to `main`
I updated the JS APIs, CI should pass.
> feat(workspace): make types camel case

- crates/biome_js_analyze/src/utils/restricted_glob.rs
Reviewing #4376, I noticed that `RetsrictedGLob` was not implementing `Eq`, `PartialEq` and `Hash`.
This PR fixes it.
CI must pass.
> refactor(restricted_glob): add Eq impls

- crates/biome_cli/src/execute/migrate/eslint_any_rule_to_biome.rs
- crates/biome_configuration/src/analyzer/linter/rules.rs
- crates/biome_diagnostics_categories/src/categories.rs
- crates/biome_js_analyze/src/lint/nursery.rs
- crates/biome_js_analyze/src/lint/nursery/use_google_font_preconnect.rs
- crates/biome_js_analyze/src/options.rs
- crates/biome_js_analyze/tests/specs/nursery/useGoogleFontPreconnect/invalid.jsx
- crates/biome_js_analyze/tests/specs/nursery/useGoogleFontPreconnect/invalid.jsx.snap
- crates/biome_js_analyze/tests/specs/nursery/useGoogleFontPreconnect/valid.jsx
- crates/biome_js_analyze/tests/specs/nursery/useGoogleFontPreconnect/valid.jsx.snap
- crates/biome_js_syntax/src/jsx_ext.rs
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
- packages/@biomejs/biome/configuration_schema.json
Implement [google-font-preconnect](https://nextjs.org/docs/messages/google-font-preconnect) from eslint-plugin-next.
Snapshots + CI
> feat(lint): add `useGoogleFontPreconnect` rule

- CHANGELOG.md
- crates/biome_aria/src/roles.rs
- crates/biome_js_analyze/tests/specs/a11y/useSemanticElements/invalid.jsx.snap
Fixes #4323. TL;DR role="search" != role="searchbox"
- This fixes a simple typo without changing any behavior
- Tests updated; tests should pass
> fix(lint): don’t recommend role="searchbox" suggestions for role="search"

- Cargo.lock
- crates/biome_configuration/src/analyzer/linter/rules.rs
- crates/biome_diagnostics_categories/src/categories.rs
- crates/biome_graphql_analyze/Cargo.toml
- crates/biome_graphql_analyze/src/lib.rs
- crates/biome_graphql_analyze/src/lint/nursery.rs
- crates/biome_graphql_analyze/src/lint/nursery/use_named_operation.rs
- crates/biome_graphql_analyze/src/options.rs
- crates/biome_graphql_analyze/tests/specs/nursery/useNamedOperation/invalid.graphql
- crates/biome_graphql_analyze/tests/specs/nursery/useNamedOperation/invalid.graphql.snap
- crates/biome_graphql_analyze/tests/specs/nursery/useNamedOperation/valid.graphql
- crates/biome_graphql_analyze/tests/specs/nursery/useNamedOperation/valid.graphql.snap
- crates/biome_graphql_factory/src/lib.rs
- crates/biome_graphql_factory/src/make.rs
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
- packages/@biomejs/biome/configuration_schema.json
Disallow operations without name, since GraphQL clients usually use operations' name to cache.
Added new tests to verify this rule's behavior
> feat(graphql_analyze): useNamedOperation

- crates/biome_lsp/src/handlers/formatting.rs
Closes https://github.com/biomejs/biome/issues/4393
The changes are minimal, and we already have some logic that creates text exits out of a diff.
The current tests pass. I tested locally and nothing breaks.
> fix(lsp): emit text edits when formatting

- Cargo.lock
- Cargo.toml
- crates/biome_lsp/Cargo.toml
- crates/biome_lsp/src/capabilities.rs
- crates/biome_lsp/src/documents.rs
- crates/biome_lsp/src/handlers/analysis.rs
- crates/biome_lsp/src/handlers/formatting.rs
- crates/biome_lsp/src/handlers/rename.rs
- crates/biome_lsp/src/lib.rs
- crates/biome_lsp/src/session.rs
- crates/biome_lsp/src/utils.rs
- crates/biome_lsp_converters/Cargo.toml
- crates/biome_lsp_converters/README.md
- crates/biome_lsp_converters/src/from_proto.rs
- crates/biome_lsp_converters/src/lib.rs
- crates/biome_lsp_converters/src/line_index.rs
- crates/biome_lsp_converters/src/to_proto.rs
- knope.toml
`biome_lsp` has a lot of nifty converters and tools for working with `biome_rowan`'s structs and converting them to LSP formats. Unfortunately, `biome_lsp` is a private crate, so none of those tools were exported.
This PR moves those utilities into a separate `biome_lsp_converters` crate that is public, so that people (just me, maybe) can use them.
Moved the tests as well, so the same testing strategy still applies.
> feat: move biome_lsp/converters to a separate crate

- Cargo.lock
- xtask/coverage/Cargo.toml
- xtask/coverage/src/js/test262.rs
Remove the remaining instance of `once_cell::Lazy`.
CI must pass.
> chore(deps): remove once_cell crate

- Cargo.lock
- crates/biome_cli/Cargo.toml
- crates/biome_wasm/Cargo.toml
Extract all updates of #4406, except **grit**-related deps and **hashbrown** that remove APIs that we are using.
CI must pass.
> chore(deps): update

- CHANGELOG.md
- crates/biome_js_analyze/src/lint/style/use_export_type.rs
- crates/biome_js_analyze/src/lint/style/use_import_type.rs
Fix https://github.com/biomejs/biome/issues/4417
Unfortunately we cannot test declaration files yet.
I didn't manage to extend our test infra to support it.
> refactor(useImportType,useExportType): ignore dts

- CHANGELOG.md
- crates/biome_css_formatter/src/css/auxiliary/attribute_matcher_value.rs
- crates/biome_css_formatter/src/css/value/string.rs
- crates/biome_css_formatter/src/utils/string_utils.rs
- crates/biome_css_formatter/tests/quick_test.rs
- crates/biome_css_formatter/tests/specs/css/quote_style/normalize_quotes.css
- crates/biome_css_formatter/tests/specs/css/quote_style/normalize_quotes.css.snap
closes: #4384 
`@charset` must always have double quotes: https://www.w3.org/TR/css-syntax-3/#determine-the-fallback-encoding
I add a param `StringLiteralParentKind` for `impl FormatLiteralStringToken` to judge if the `CSS String`'s parent is a `CSS_CHARSET_AT_RULE` which represents the syntax like:`@charset`, i refer the same util at `biome_js_formatter`.
if the string is `StringLiteralParentKind::CharsetAtRule`, i will use the double quote for the string in any case, or we will execute the normal logic of `biome_css_formatter`.
Test case as follows: 
```css
@charset·"UTF-8";
@charset "iso-8859-15";
@charset "any-string-is-okay";
```
> fix(css_formatter): keep @charset double quote in single quote config

- crates/biome_analyze/src/lib.rs
- crates/biome_cli/src/commands/rage.rs
- crates/biome_cli/tests/snapshots/main_commands_rage/with_linter_configuration.snap
Order lint rules reported by `biome rage`.
This makes finding if a rule is enabled easier and avoids changes when we use a different hash function. 
I updated the snapshots.
> refactor: order lint rules in rage output

- crates/biome_js_analyze/src/lint/style/use_filenaming_convention.rs
`useFilenamingConvention` now orders suggested filenames.
This avoids depending on the order induced by a hash function,
No change in snapshots.
> refactor(useFilenamingConvention): order suggested filenames

- crates/biome_configuration/src/analyzer/assists/actions.rs
- crates/biome_service/src/file_handlers/mod.rs
- xtask/codegen/src/generate_configuration.rs
- Use `HashSet` instead of `Vec` to avoid duplicated filters.
- Remove `get_disabled_rules` for assist actions.
In contrast to lint rules, `as_enabled_rules` doesn't need `get_disabled_rules` to compute enabled rules,
because the system is simpler (no `all` and `recommended` flags)
CI must pass.
> refactor(lint,actions): avoid duplicated filters

- CHANGELOG.md
- crates/biome_cli/src/execute/migrate/eslint.rs
Fix https://github.com/biomejs/biome/issues/3079#issuecomment-2440862660
I added unit tests.
> fix(migrate-eslint): corretcly handle scoped package with paths

- .cargo/config.toml
- .github/workflows/release_cli.yml
- .github/workflows/release_knope.yml
Biome recently reached 5M downloads! However, with the current npm binary size of 29MB (v1.9.4), this translates to 100TB+ of cumulative download data. This PR aims to optimize the binary size to reduce bandwidth usage.
Binary size optimization results (tested on commit 3401663efea3a3c45a7d9240d72b92c981285fb2):
- Before: 32.9MB (only lto)
- After: 30.45MB (codegen-units=1)
All options are explained here : https://doc.rust-lang.org/cargo/reference/profiles.html
- Set `codegen-units = 1`: Can reduces binary size and improves runtime performance
Tested on Sentry repo like ecosystem-ci (6164 files)
> build: reduce binary size

- CHANGELOG.md
- crates/biome_css_formatter/src/css/lists/relative_selector_list.rs
- crates/biome_css_formatter/tests/specs/css/declaration_list.css
- crates/biome_css_formatter/tests/specs/css/declaration_list.css.snap
closes: #4326 
I add special judge for that case:
```css
.a {
/* hi */
a,
/* me */
div {
color: red;
}
}
```
If i get a `CSS_Type_Selector` like: `/* hi */\n  a,\n  div`(you can refer this from above case), i will not add an ident for this to avoid this case, the previous logic at `biome_css_formatter` will add an ident for this case by default.
add test case like:
```css
.with-comments {
/* hello */
a,
/* world */
button {
color: blue;
}
}
.without-comments {
a,
button {
color: blue;
}
}
```
my fix as follows:
```diff
.with-comments {
/* hello */
a,
/* world */
-    button {
+  button{
color: blue;
}
}
```
> fix(css_formatter): don't indent CSS selector when leading comments before

- crates/biome_css_analyze/src/lint/correctness/no_invalid_direction_in_linear_gradient.rs
- crates/biome_css_analyze/src/lint/correctness/no_invalid_grid_areas.rs
- crates/biome_css_analyze/src/lint/nursery/no_irregular_whitespace.rs
- crates/biome_js_analyze/src/lint/complexity/no_useless_lone_block_statements.rs
- crates/biome_js_analyze/src/lint/suspicious/no_misleading_character_class.rs
- crates/biome_js_analyze/src/lint/suspicious/no_then_property.rs
just cleanup to keep things consistent and remove unnecessary code
Merge after passing CI
> chore(linter): clean up lint rules and update correct version numbers

- Cargo.lock
- crates/biome_grit_patterns/Cargo.toml
- crates/biome_grit_patterns/src/grit_context.rs
- crates/biome_grit_patterns/src/grit_css_parser.rs
- crates/biome_grit_patterns/src/grit_target_language.rs
- crates/biome_grit_patterns/src/grit_target_language/css_target_language.rs
- crates/biome_grit_patterns/src/grit_target_language/css_target_language/constants.rs
- crates/biome_grit_patterns/src/grit_target_node.rs
- crates/biome_grit_patterns/src/lib.rs
- crates/biome_grit_patterns/tests/spec_tests.rs
- crates/biome_grit_patterns/tests/specs/css/colors.css
- crates/biome_grit_patterns/tests/specs/css/colors.grit
- crates/biome_grit_patterns/tests/specs/css/colors.snap
- xtask/bench/benches/gritql_search.rs
- xtask/codegen/src/generate_target_language_constants.rs
- xtask/codegen/src/language_kind.rs
Adds CSS support to our Grit bindings.
Note this doesn't yet fix the assumptions in our search command and the plugin loader, so a few places still need to be updated before CSS support in plugins/search is fully complete. 
Test added.
> feat(grit): support Grit queries targeting CSS

- crates/biome_js_analyze/src/lint/complexity/use_arrow_function.rs
A minor change that avoids useless checks.
CI must pass.
> perf(useArrowFunction): avoid useless checks

- crates/biome_cli/src/execute/migrate/eslint_any_rule_to_biome.rs
- crates/biome_js_analyze/src/lint/correctness/use_array_literals.rs
Just adding this rule source: https://typescript-eslint.io/rules/no-array-constructor/
Noticed it while doing some migrating.
👀
> docs: add typescript-eslint rule source for `useArrayLiterals`

- crates/biome_service/src/file_handlers/grit.rs
- crates/biome_service/src/file_handlers/mod.rs
Grit was failing in the playground because we don't expose the `lint` method, which is charge of pulling diagnostics, even from the parser.
I locally tested by compiling the WASM module. It works now
> fix(grit): linting inside workspace

- CHANGELOG.md
- crates/biome_js_analyze/src/lint/correctness/no_unused_imports.rs
- crates/biome_js_analyze/src/lint/style/use_import_type.rs
- crates/biome_js_analyze/tests/specs/correctness/noUnusedImports/invalid-import-namespace.ts.snap
- crates/biome_js_analyze/tests/specs/correctness/noUnusedImports/invalid-unused-react.jsx.snap
- crates/biome_js_analyze/tests/specs/correctness/noUnusedImports/invalid.js
- crates/biome_js_analyze/tests/specs/correctness/noUnusedImports/invalid.js.snap
- crates/biome_js_analyze/tests/specs/correctness/noUnusedImports/invalid.jsx.snap
- crates/biome_js_analyze/tests/specs/correctness/noUnusedImports/invalid.ts.snap
Fix https://github.com/biomejs/biome/issues/3574 and https://github.com/biomejs/biome/issues/4240
I added a test and updated the snapshots.
> refactor(noUnusedImports): report empty named imports

- CHANGELOG.md
- crates/biome_js_analyze/src/lint/correctness/no_undeclared_variables.rs
- crates/biome_js_analyze/tests/specs/correctness/noUndeclaredVariables/ignore-types.options.json
- crates/biome_js_analyze/tests/specs/correctness/noUndeclaredVariables/ignore-types.ts
- crates/biome_js_analyze/tests/specs/correctness/noUndeclaredVariables/ignore-types.ts.snap
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
- packages/@biomejs/biome/configuration_schema.json
See [this thread](https://github.com/biomejs/biome/issues/3998#issuecomment-2361821503) for some context.
Add a new `checkTypes` option for `noUndeclaredVariables`.
The option is turned on by default. I plan to turn it off in Biome 2.0.
This will bring `noUndeclaredVariables` closer to `no-undef` (So we will set the rule as a source instead of an inspiration).
This also eliminates many false positives.
TypeScript is better suited to perform this kind of check.
We could consider in Biome 2.0 to turn on the rule by default because `checkTypes` set to false will reduce significantly the number of false positives.
I chose to name the option `checkTypes` instead of `ignoreTypes` because I plan to make it false by default.
> feat(noUndeclaredVariables): add checkTypes option

- CHANGELOG.md
- crates/biome_js_analyze/src/lint/correctness/no_unused_imports.rs
- crates/biome_js_analyze/tests/specs/correctness/noUnusedImports/invalid-import-namespace.ts.snap
- crates/biome_js_analyze/tests/specs/correctness/noUnusedImports/invalid-unused-react.jsx.snap
- crates/biome_js_analyze/tests/specs/correctness/noUnusedImports/invalid.js.snap
- crates/biome_js_analyze/tests/specs/correctness/noUnusedImports/invalid.jsx.snap
- crates/biome_js_analyze/tests/specs/correctness/noUnusedImports/invalid.ts
- crates/biome_js_analyze/tests/specs/correctness/noUnusedImports/invalid.ts.snap
Fix https://github.com/biomejs/biome/issues/3401
The rule now keeps all trivia (notably comments) separated from the `import` by a blank line (aka orphan comments).
> refactor(noUnusedImports): keep orphan comments

- crates/biome_js_analyze/src/lint/a11y/no_autofocus.rs
- crates/biome_js_analyze/tests/quick_test.rs
- crates/biome_js_analyze/tests/specs/a11y/noAutofocus/invalid.jsx
- crates/biome_js_analyze/tests/specs/a11y/noAutofocus/invalid.jsx.snap
- crates/biome_js_analyze/tests/specs/a11y/noAutofocus/valid.jsx
- crates/biome_js_analyze/tests/specs/a11y/noAutofocus/valid.jsx.snap
Closes #4339 
Use a custom visitor to detect that an element with the `autofocus` attribute is a child element of `dialog` element  or `popover` attribute.
Updated the snapshot tests
> fix(js_analyze): skip `noAutofocus` check if eligible

- crates/biome_js_analyze/src/lint/correctness/no_constructor_return.rs
- crates/biome_js_analyze/tests/specs/correctness/noConstructorReturn/invalid.js.snap
See: https://github.com/biomejs/biome/issues/4453
Snapshots updated.
> fix(linter): improve diagnostic for `noConstructorReturn`

- crates/biome_js_analyze/src/lint/correctness/no_constructor_return.rs
As [suggested](https://github.com/biomejs/biome/issues/4453#issuecomment-2466454739) by @Conaclos, I'm adding a link to my blog post for advice on how to use the singleton pattern with the `noConstructorReturn` rule.
> docs(linter): include advice on the singleton pattern with `noConstructorReturn`

- crates/biome_js_analyze/src/lint/a11y/no_access_key.rs
- crates/biome_js_analyze/src/lint/a11y/no_autofocus.rs
- crates/biome_js_analyze/src/lint/a11y/no_blank_target.rs
- crates/biome_js_analyze/src/lint/a11y/no_distracting_elements.rs
- crates/biome_js_analyze/src/lint/a11y/no_header_scope.rs
- crates/biome_js_analyze/src/lint/a11y/no_label_without_control.rs
- crates/biome_js_analyze/src/lint/a11y/no_redundant_alt.rs
- crates/biome_js_analyze/src/lint/a11y/no_svg_without_title.rs
- crates/biome_js_analyze/src/lint/a11y/use_alt_text.rs
- crates/biome_js_analyze/src/lint/a11y/use_anchor_content.rs
- crates/biome_js_analyze/src/lint/a11y/use_button_type.rs
- crates/biome_js_analyze/src/lint/a11y/use_heading_content.rs
- crates/biome_js_analyze/src/lint/a11y/use_html_lang.rs
- crates/biome_js_analyze/src/lint/a11y/use_iframe_title.rs
- crates/biome_js_analyze/src/lint/a11y/use_key_with_click_events.rs
- crates/biome_js_analyze/src/lint/a11y/use_media_caption.rs
- crates/biome_js_analyze/src/lint/a11y/use_semantic_elements.rs
- crates/biome_js_analyze/src/lint/a11y/use_valid_anchor.rs
- crates/biome_js_analyze/src/lint/correctness/no_void_elements_with_children.rs
- crates/biome_js_analyze/src/lint/nursery/no_head_element.rs
- crates/biome_js_analyze/src/lint/nursery/no_img_element.rs
- crates/biome_js_analyze/src/lint/nursery/use_google_font_display.rs
- crates/biome_js_analyze/src/lint/nursery/use_google_font_preconnect.rs
- crates/biome_js_analyze/src/lint/nursery/use_valid_autocomplete.rs
- crates/biome_js_analyze/src/lint/security/no_dangerously_set_inner_html_with_children.rs
- crates/biome_js_analyze/src/services/aria.rs
- crates/biome_js_syntax/src/jsx_ext.rs
- crates/biome_service/src/file_handlers/mod.rs
- Improve consistency of the documentation
- Use `SyntaxResult` instead of `Option` where possible.
- Remove unnecessary wrapping: use `Option<X>` instead of `SyntaxResult<Option<X>>`
- Use `split_ascii_whitespace` instead of `split_whitespace` for splitting HTML attribute values.
- Avoid some cloning and use `TokenString` instead of `String` for `get_attribute_inner_string_text`.
CI must pass.
> refactor(js_syntax): minor clean up

- crates/biome_js_analyze/src/lint/nursery/use_valid_autocomplete.rs
Refactor `useValidAUtocomplete` to use the `Ast` query instead of the `Aria` query.
I also simplified the implementation by using `JsxAttributeList::find_by_name` and `AnyJsxElement` instead of a custom type.
CI must pass.
> refactor(useValidAutocomplete): use Ast query instead of Aria

- crates/biome_aria/src/roles.rs
- crates/biome_aria_metadata/src/lib.rs
- crates/biome_js_analyze/src/lint/a11y/no_interactive_element_to_noninteractive_role.rs
- crates/biome_js_analyze/src/lint/a11y/no_noninteractive_element_to_interactive_role.rs
- crates/biome_js_analyze/src/lint/a11y/no_noninteractive_tabindex.rs
- crates/biome_js_analyze/src/lint/a11y/no_redundant_roles.rs
- crates/biome_js_analyze/src/lint/a11y/use_aria_props_for_role.rs
- crates/biome_js_analyze/src/lint/a11y/use_focusable_interactive.rs
- crates/biome_js_analyze/src/lint/a11y/use_semantic_elements.rs
- crates/biome_js_analyze/src/lint/a11y/use_valid_aria_role.rs
- crates/biome_js_analyze/src/lint/nursery/use_aria_props_supported_by_role.rs
Aria allows setting fallbacks in the role attribute. Only the first valid role is taken into account.
This PR introduces `AriaRole::from_roles` that parses a space-separated list of roles and return the first valid one.
CI must pass
> refactor(aria): add AriaRole::from_roles

- crates/biome_grit_formatter/src/lib.rs
- crates/biome_service/src/file_handlers/grit.rs
This PR adds range formatting and format on type for grit 
Existing CI should pass
> feat(grit): add range formatting

- CHANGELOG.md
- crates/biome_css_formatter/src/comments.rs
- crates/biome_css_formatter/tests/quick_test.rs
- crates/biome_css_formatter/tests/specs/css/issue_3229.css
- crates/biome_css_formatter/tests/specs/css/issue_3229.css.snap
- crates/biome_css_formatter/tests/specs/prettier/css/atrule/supports.css.snap
- crates/biome_css_formatter/tests/specs/prettier/css/bom/bom.css.snap
- crates/biome_css_formatter/tests/specs/prettier/css/comments/custom-properties.css.snap
- crates/biome_css_formatter/tests/specs/prettier/css/comments/selectors.css.snap
- crates/biome_css_formatter/tests/specs/prettier/css/front-matter/custom-parser.css.snap
- crates/biome_css_formatter/tests/specs/prettier/css/front-matter/empty.css.snap
- crates/biome_css_formatter/tests/specs/prettier/css/yaml/comment_after.css.snap
- crates/biome_formatter_test/src/check_reformat.rs
Closes https://github.com/biomejs/biome/issues/3229
The issue was caused by comments that belonged to `left` and `combinator` of a `CssCompoundSelector`. 
To make the reformatting happy, I decided to place the comments of the node to be a trailing comment of `right`.
The end result is way better than Prettier. Prettier [isn't able to remove the empty lines inside comments](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAdK7NQPQCoAEAllAA4CuM+u2WWAZhBFvvnvgIb6QC23Cl1WhmHoWAOnYAlMgBs4+YKJZcIMiACck+dXAAmSgL5CsbYuQE0oDJhhhtOPPrCqXMMCdLkK3kNZu16ANzoBiAANCAQJDCE0ADOyKDs6uoQAO4ACskICSjsMmnsAJ4JEQBG6uxgANZwMADK7HwAMsRwyHT5cXDllTV19SRVxADmyDDqZD0g3dyE45PTcAAeJHDqhE4w+QAq61DJhHC5nTLdEXGjcgCKZBDwHV3TAFZxy-VXcLf37Uin5yAAI53eAZVIkXIgdhxAC0UDgej04RAE3YhBkowAwhBeOxkFCZDJkZcoCM5ABBGATQhlChwDLrVrwx5naYAC …
> fix(css): reformat issue in comments between compound selectors

- crates/biome_json_parser/src/parser.rs
- crates/biome_json_syntax/src/file_source.rs
Fixes incorrect use of `with_*` methods in `JsonParserOptions::from(&JsonFileSource)`. Adds unit tests and `#[must_use]` to prevent this error in the future.
I accidentally stumbled upon this while trying to fix some tests that were breaking due to an unrelated change. Took a bit of time to figure out that `JsonParserOptions::from` simply discarded the `allow_comments` and `allow_trailing_commas` flags...
Unit tests for `JsonParserOptions::from(&JsonFileSource)` were added.
> fix(json_parser): fix broken `JsonParserOptions::from(&JsonFileSource)` implementation

- CHANGELOG.md
- crates/biome_cli/src/execute/migrate/eslint.rs
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
- packages/@biomejs/biome/configuration_schema.json
Fix https://github.com/biomejs/biome/issues/4528
ESLint recommends that a package that exports a shared configuration be prefixed with `eslint-config-` or simply named `eslint-config`.
This is only a recommendation.
Packages that export shared configurations can have arbitrary names.
Biome is now able to load any package.
> fix(migrate-eslint): load non-conventional shared config name

- CHANGELOG.md
- crates/biome_css_formatter/src/comments.rs
- crates/biome_css_formatter/tests/quick_test.rs
- crates/biome_css_formatter/tests/specs/css/properties/grid.css
- crates/biome_css_formatter/tests/specs/css/properties/grid.css.snap
closes: #4026 
I add a judge for `declaration_name` under `CSS_GENERIC_COMPONENT_VALUE_LIST`, it will deal the case the issue above:
```ts
#grid {
grid-template-columns:
1fr /* first comment */
auto /* second comment */
2fr /* third comment */  
}
```
I add test case.
> fix(formatter): don't move comments in grid-template

- CHANGELOG.md
- crates/biome_css_analyze/src/lint/nursery/no_unknown_pseudo_class.rs
- crates/biome_css_analyze/tests/specs/nursery/noUnknownPseudoClass/valid.css
- crates/biome_css_analyze/tests/specs/nursery/noUnknownPseudoClass/valid.css.snap
closes: #4533 
The case looks fine on `stylelint`(it has the lint rule that biome `noUnknownPseudoClass` rule from): https://stylelint.io/demo/#N4Igxg9gJgpiBcD4FoDuMBGBrAlgF2QGcwAnCAG3IwEMTk8ALAVwFsN4GIA3GEgAmAAdAHaC8kchBLw+JGFADcIvgF8Ry+CnTZ8RUhSq16zNvDwxCeAIxWB68RSky5i5SpAAaEADMc5GABy1CxwiDAAHsEADv4AdGCEhJ7gEMK+AOYIIELCfHyCIBHmwlCEBTIA2sp5+SCWAJ7+5DjCBJBpOOlEeNQltFAF1QC6Iu5e7RkAYlIs1HhZAFaEqcmwUUmIOXkFDU0teOW15HMWB57VO3iNMM2tyBOd3b1Q-YcFx+aWg8LuKkA
So i think biome need to pass the case:
```css
::-webkit-scrollbar-thumb:hover {
color: red;
}
```
Now it will get error like: https://biomejs.dev/playground/?lintRules=all&files.main.css=OgA6AC0AdwBlAGIAawBpAHQALQBzAGMAcgBvAGwAbABiAGEAcgAtAHQAaAB1AG0AYgA6AGgAbwB2AGUAcgAgAHsAfQAKADoAOgAtAHcAZQBiAGsAaQB0AC0AcwBjAHIAbwBsAGwAYgBhAHIALQB0AGgAdQBtA …
> fix(noUnknownPseudoClass): not error for pseudo class  after webkit scrollbar element

- CHANGELOG.md
- crates/biome_js_analyze/tests/specs/correctness/noUndeclaredVariables/validAmbientRead.d.ts
- crates/biome_js_analyze/tests/specs/correctness/noUndeclaredVariables/validAmbientRead.d.ts.snap
- crates/biome_js_analyze/tests/specs/correctness/noUndeclaredVariables/validAmbientRead.ts
- crates/biome_js_analyze/tests/specs/correctness/noUndeclaredVariables/validAmbientRead.ts.snap
- crates/biome_js_semantic/src/events.rs
Fix https://github.com/biomejs/biome/issues/4526
The semantic model now tracks if the traversed node is in an ambient context not.
The scope registers if it is in ambient context to properly restore the information once we leave a scope.
When we are in an ambient context we emit `AmbientRead` instead of `Read`.
This allows us to bind ambient read to type-only imports.
> fix(noUndeclaredVariables): bind read in ambient context to import type

- .changeset/new_top_level_suppression_for_the_analyzer.md
- Cargo.lock
- crates/biome_analyze/Cargo.toml
- crates/biome_analyze/src/diagnostics.rs
- crates/biome_analyze/src/lib.rs
- crates/biome_analyze/src/matcher.rs
- crates/biome_analyze/src/rule.rs
- crates/biome_analyze/src/suppression_action.rs
- crates/biome_cli/tests/cases/suppressions.rs
- crates/biome_cli/tests/snapshots/main_cases_suppressions/misplaced_top_level_suppression.snap
- crates/biome_cli/tests/snapshots/main_cases_suppressions/unused_suppression_after_top_level.snap
- crates/biome_css_analyze/src/lib.rs
- crates/biome_css_analyze/tests/suppression/suspicious/noDuplicateFontNames/noDuplicateFontNames.css.snap
- crates/biome_css_analyze/tests/suppression/suspicious/noEmptyBlock/noEmptyBlock.css.snap
- crates/biome_diagnostics_categories/src/categories.rs
- crates/biome_graphql_analyze/src/lib.rs
- crates/biome_graphql_analyze/tests/suppression/nursery/noDuplicatedFields/noDuplicatedFields.graphql.snap
- crates/biome_graphql_analyze/tests/suppression/nursery/useDeprecatedReason/useDeprecatedReason.graphql.snap
- crates/biome_js_analyze/src/lib.rs
- crates/biome_js_analyze/tests/suppression/a11y/useKeyWithClickEvents/invalid.jsx.snap
- crates/biome_js_analyze/tests/suppression/correctness/noUndeclaredVariables/noUndeclaredVariables.ts.snap
- crates/biome_js_analyze/tests/suppression/correctness/noUnusedVariables/simple.js.snap
- crates/biome_js_analyze/tests/suppression/suspicious/noArrayIndexKey/noArrayIndexKey.jsx.snap
- crates/biome_js_analyze/tests/suppression/suspicious/noAssignInExpressions/noAssignInExpressions.ts.snap
- crates/biome_js_analyze/tests/suppression/suspicious/noDoubleEquals/noDoubleEquals.js.snap
- crates/biome_js_analyze/tests/suppression/suspicious/noDoubleEquals/noDoubleEquals.jsx.snap
- crates/biome_js_analyze/tests/suppression/suspicious/noExplicitAny/noExplicitAny.ts.snap
- crates/biome_json_analyze/src/lib.rs
- crates/biome_suppression/src/lib.rs
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
Closes #4305 
As requested by @arendjr , this PR uses the `biome-ignore-all` for a top-level suppression.
I also took the liberty to provide a very good diagnostic in case the `biome-ignore-all`, and because of that I had to add more information returned by the function that parses the suppression comments.
Updated the snapshots, the tests and the changeset
> refactor: use `biome-ignore-all` for top level suppressions

- crates/biome_js_analyze/src/lint/a11y/no_aria_hidden_on_focusable.rs
- crates/biome_js_analyze/src/lint/a11y/use_aria_activedescendant_with_tabindex.rs
Align the code action message formatting of `useAriaActiveDescendantWithTabIndex` and `noAriaHiddenOnFocusable` with the other code actions by adding `<Emphasis></Emphasis>` tags.
No modifications to unit tests necessary.
> fix(biome_js_analyze): use consistent code action markup for noAria*/useAria*

- crates/biome_js_semantic/src/events.rs
- crates/biome_js_semantic/src/semantic_model/builder.rs
While I was testing https://github.com/biomejs/biome/pull/4579, I detected a bug introduced by https://github.com/biomejs/biome/pull/4546
As usual, we often forget to update the related methods when we push a new scope.
I manually tested the change.
Unfortunately, our test infra doesn't handle `.d.ts` files
> fix(js_semantic): scope for TsDeclarationModule

- crates/biome_js_semantic/src/events.rs
Small cleanup that reduces the size of `BindingInfo` by 1 byte.
CI must pass/
> refactor(js_semantic): reduce BindingInfo size

- CHANGELOG.md
- crates/biome_js_analyze/src/lint/correctness/use_exhaustive_dependencies.rs
- crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/issue4568.js
- crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/issue4568.js.snap
- crates/biome_js_semantic/src/semantic_model/import.rs
This fix attempts to fix #4568 such that the same issue won't pop up in other lint rules.
I suppose a better fix could be to not evaluate linter rules if the file has parsing errors. Would it be better to add a `JS_BOGUS_IMPORT` instead?
fixes #4568
Tested it manually against the sample in the issue.
> fix(analyze/js): fix bindings in bogus imports not being detected as imports

- CHANGELOG.md
- crates/biome_cli/tests/cases/overrides_formatter.rs
- crates/biome_cli/tests/snapshots/main_cases_overrides_formatter/allow_trailing_commas_on_well_known_files.snap
- crates/biome_json_syntax/src/file_source.rs
Fix https://github.com/biomejs/biome/issues/4391
> refactor(cli): don't consider files that don't end with the json extension as JSON files

- crates/biome_console/src/fmt.rs
As the title says: Provide `impl biome_console::fmt::Display for Box<T>` by delegating to `impl biome_console::fmt::Display for T`.
Needed for #4596 but valuable by itself.
> refactor(biome_console): add blanket implementation of `biome_console::fmt::Display` for `Box<_>`

- CHANGELOG.md
- crates/biome_js_analyze/tests/specs/correctness/noUnusedImports/valid-inner-imports.ts
- crates/biome_js_analyze/tests/specs/correctness/noUnusedImports/valid-inner-imports.ts.snap
- crates/biome_js_semantic/src/events.rs
Fix https://github.com/biomejs/biome/issues/3895
This PR changes how we bind ambient read to imported type.
Previously, we waited to get in the global scope to try binding an ambient read (read of a value in an ambient context) to an `import type`. However, external modules and namespaces can also import stuff.
I changed the code to support it in any scope.
I added a test
> fix(noUnusedImports): don't report used val imported as type in an external module

- CHANGELOG.md
- crates/biome_js_parser/src/syntax/js_parse_error.rs
- crates/biome_js_parser/src/syntax/typescript/statement.rs
- crates/biome_js_parser/tests/js_test_suite/error/ts_export_declare.ts
- crates/biome_js_parser/tests/js_test_suite/error/ts_export_declare.ts.snap
closes: #4562 
Now it will panic on:
```ts
declare@
```
so i replace `.expect()` with `.add_diagnostic()` at `parse_declare`.
I add test case for this.
> fix(js_parser): don't panic on declare@

- .github/renovate.json
This PR adds temporary hashbrown and grit packages in the ignore list of Renovate because their upgrade [break Biome](https://github.com/biomejs/biome/pull/4406).
Ignoring them allows us to update other crates more easily.
CI must pass.
> refactor(enovate): ignore hashbrown and grit

- crates/biome_analyze/CONTRIBUTING.md
Continue the improvements to the contribution docs started in #4542.
> docs(biome_js_analyze): improve biome_analyze/CONTRIBUTING.md

- Cargo.lock
- crates/biome_aria/Cargo.toml
- crates/biome_aria/src/lib.rs
- crates/biome_aria/src/roles.rs
- crates/biome_js_analyze/src/lint/a11y/no_aria_hidden_on_focusable.rs
- crates/biome_js_analyze/src/lint/a11y/no_interactive_element_to_noninteractive_role.rs
- crates/biome_js_analyze/src/lint/a11y/no_noninteractive_element_to_interactive_role.rs
- crates/biome_js_analyze/src/lint/a11y/no_noninteractive_tabindex.rs
- crates/biome_js_analyze/src/lint/a11y/no_redundant_roles.rs
- crates/biome_js_analyze/src/lint/a11y/use_aria_activedescendant_with_tabindex.rs
- crates/biome_js_analyze/src/lint/a11y/use_focusable_interactive.rs
- crates/biome_js_analyze/src/lint/nursery/no_static_element_interactions.rs
- crates/biome_js_analyze/src/lint/nursery/use_aria_props_supported_by_role.rs
- crates/biome_js_analyze/src/services/aria.rs
- crates/biome_js_analyze/tests/specs/a11y/noRedundantRoles/invalid.jsx.snap
- crates/biome_js_syntax/Cargo.toml
- crates/biome_js_syntax/src/jsx_ext.rs
- crates/biome_js_syntax/src/static_value.rs
This PR introduces an abstraction for HTML-like elements and attributes in `biome_aria`.
This allows us to use the same abstraction for HTML and JSX and avoid a dependency over `biome_rowan`/`biome_js_syntax`.
The abstraction is based on two traits (open to suggestion for naming):
- `biome_aria::Element`
- `biome_aria::Attribute`
These traits are implemented by some `biome_js_syntax` nodes (`AnyJsxElement` and `JsxAttribute`).
The trait methods returns `Option` that allows to return `None` upon buggy nodes.
This is not ideal, however I don't see a better alternative at the moment.
These traits simplify how we interact with the biome aria functions because we just need to pass regular AST nodes to them.
I plan to add a way of retrieving parent nodes or parent nodes with a role.
CI must …
> refactor(aria): add abstractions for attribute lookup

- crates/biome_js_analyze/src/lint/nursery/no_restricted_imports.rs
- crates/biome_js_analyze/tests/specs/nursery/noRestrictedImports/invalid.js
- crates/biome_js_analyze/tests/specs/nursery/noRestrictedImports/invalid.js.snap
- crates/biome_js_analyze/tests/specs/nursery/noRestrictedImports/invalid.options.json
- crates/biome_js_analyze/tests/specs/nursery/noRestrictedImports/invalid.ts
- crates/biome_js_analyze/tests/specs/nursery/noRestrictedImports/invalid.ts.snap
- crates/biome_js_analyze/tests/specs/nursery/noRestrictedImports/valid.js
- crates/biome_js_analyze/tests/specs/nursery/noRestrictedImports/valid.js.snap
- crates/biome_js_analyze/tests/specs/nursery/noRestrictedImports/valid.options.json
- crates/biome_js_analyze/tests/specs/nursery/noRestrictedImports/valid.ts
- crates/biome_js_analyze/tests/specs/nursery/noRestrictedImports/valid.ts.snap
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
- packages/@biomejs/biome/configuration_schema.json
Extend `noRestrictedImports` with the option to use `importNames` and `allowImportNames` to specify the set of (dis)allowed imports.
1. The [`no-restricted-imports` ESLint](https://eslint.org/docs/latest/rules/no-restricted-imports#importnames) provides the feature.
2. Personal need: I needed it to make sure that when using the `react-i18next` library, I'm always retrieving the `t` function from the `useTranslation` hook, instead of using `import { t } from 'i18next'`. 
```json
{
"options": {
"paths": {
"lodash": "Using lodash is not encouraged",
"underscore": "Using underscore is not encouraged",
"import-foo": {
"importNames": ["Bar"],
"message": "Please use Bar from /import-bar/baz/ instead."
},
"import-bar": {
"allowImportNames": ["Bar"],
"message": "Please use only Bar from …
```
> feat(noRestrictedImports): add import_names and allow_import_names settings

- CHANGELOG.md
- crates/biome_css_formatter/src/css/lists/selector_list.rs
- crates/biome_css_formatter/src/css/selectors/complex_selector.rs
- crates/biome_css_formatter/tests/quick_test.rs
- crates/biome_css_formatter/tests/specs/css/issue_3229.css.snap
- crates/biome_css_formatter/tests/specs/css/selectors/selector_lists.css
- crates/biome_css_formatter/tests/specs/css/selectors/selector_lists.css.snap
- crates/biome_css_formatter/tests/specs/prettier/css/comments/selectors.css.snap
closes: #4575 
I add special judge for the case like:
```css
/* 1some medium long comment */
.line1 selector,
/* 2some medium long comment */
.line1 selector,
/* 3some medium long comment */
div selector {
background: green;
}
```
if there was a selector, it contains comments before, it will don't be wrapped by the ident(So i add judge in this case to remove the ident for the selector).
I add test case.
> fix(css_formatter): don't wrap selector identation after css comments

- CHANGELOG.md
- crates/biome_js_analyze/src/lint/complexity/no_useless_fragments.rs
- crates/biome_js_analyze/tests/quick_test.rs
- crates/biome_js_analyze/tests/specs/complexity/noUselessFragments/issue_4553.jsx
- crates/biome_js_analyze/tests/specs/complexity/noUselessFragments/issue_4553.jsx.snap
closes: #4553 
I add judge logic for the fix case like:
```jsx
<Suspense fallback={<><span>Loading...</span></>}>
{children}
</Suspense>;
```
When the fragment child  is a `JSXElement` like `<span>Loading...</span>`  here, in the fix process, we will keep the JSXAttributeValue.
So it will fix as:
```jsx
<Suspense fallback={<span>Loading...</span>}>
{children}
</Suspense>;
```
The attribute `fallback`'s value is a `JsxExpressionAttributeValue` not a `JsxTagExpression`.
I add test case.
> fix(noUselessFragments): fix result has invalid syntax when under JSX attribute

- Cargo.lock
- Cargo.toml
- crates/biome_glob/Cargo.toml
- crates/biome_glob/src/lib.rs
- crates/biome_js_analyze/Cargo.toml
- crates/biome_js_analyze/src/assists/source/organize_imports.rs
- crates/biome_js_analyze/src/lint/correctness/no_undeclared_dependencies.rs
- crates/biome_js_analyze/src/utils.rs
- knope.toml
Move `RetsrictedGlob` from `biome_js_analyze` to a dedicated crate.
This allows us to use `RetsrictedGlob` outside `biome_js_analyze`. 
Also, I renamed `RetsrictedGlob` into `Glob`. Possible alternative names are `GlobPattern` and `Pattern`.
I added some documentation for the crate and put optional dependencies behind feature flags.
CI must pass.
> feat(biome_glob): add dedicated crate for globs

- .changeset/add_the_new_rule_notsignorehttps.md
- crates/biome_cli/src/execute/migrate/eslint_any_rule_to_biome.rs
- crates/biome_configuration/src/analyzer/linter/rules.rs
- crates/biome_diagnostics_categories/src/categories.rs
- crates/biome_js_analyze/src/lint/nursery.rs
- crates/biome_js_analyze/src/lint/nursery/no_ts_ignore.rs
- crates/biome_js_analyze/src/options.rs
- crates/biome_js_analyze/tests/specs/nursery/noTsIgnore/invalid.ts
- crates/biome_js_analyze/tests/specs/nursery/noTsIgnore/invalid.ts.snap
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
- packages/@biomejs/biome/configuration_schema.json
Follow up of https://github.com/biomejs/biome/pull/4619
> feat(linter): rule `noTsIgnore`

- Cargo.lock
- Cargo.toml
- crates/biome_service/Cargo.toml
- crates/biome_service/src/settings.rs
- crates/biome_service/src/workspace/server.rs
- packages/@biomejs/wasm-web/package.json
This PR is a proof-of-concept to show that we can use [papaya](https://github.com/ibraheemdev/papaya) instead of DashMap for workspace documents. It doesn't need immediate merging, although if all tests are green and the team is on board, I'd be happy to merge this as a stepping stone.
While papaya offers great read performance, the main reason why I want to make this change is because papaya is lock-free. Because of this, it cannot create dead locks. If we want to implement our own caching and file watching in the workspace, I would not want to run the risk of creating dead locks. They can be hard to catch, hard to debug, and generally drain contributor's energy. Let's try to avoid that :)
Because papaya is lock-free, it cannot offer a `get_mut()` method, meaning we cannot update values …
> refactor: use `papaya` instead of DashMap for workspace documents

- Cargo.lock
- Cargo.toml
- crates/biome_fs/Cargo.toml
- crates/biome_fs/src/interner.rs
Presumably `papaya` only offers "reasonable" performance for write-heavy workloads, although I can't imagine it faring any worse than a plain `RwLock`, so I just want to see how this works :)
Also 0.1.5 was released with the WASM fix.
> chore: use `papaya` in `PathInterner`

- crates/biome_service/src/diagnostics.rs
closes #4668  
I have removed the following unused variants from the `WorkspaceError` enum:  
- `ReportNotSerializable`  
- `DirtyWorkspace`  
- `CantReadDirectory`  
The motivation behind these changes is to eliminate unused code, thereby reducing bloat and improving maintainability.
> refactor: cleaned up workspaceError enum in biome_service/diagnostics.rs

- Cargo.lock
- Cargo.toml
- crates/biome_service/Cargo.toml
- crates/biome_service/src/diagnostics.rs
- crates/biome_service/src/file_handlers/mod.rs
- crates/biome_service/src/lib.rs
- crates/biome_service/src/matcher/mod.rs
- crates/biome_service/src/settings.rs
- crates/biome_service/src/workspace.rs
- crates/biome_service/src/workspace/server.rs
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
- xtask/rules_check/src/lib.rs
This PR drops the `slotmap` dependency in favor of `papaya`, and simplifies some of the locking inside the workspace settings.
The main tradeoff this makes is that we need to perform more cloning of the `Settings` struct, which is a rather large one. To mitigate the impact of this I changed `Matcher` such that is holds an `Arc` internally, making it cheap to clone. As part of this, I was also able to get rid of `Matcher`'s internal `RwLock` by utilizing `papaya` again.
Also checked our release build against the `unleash` repository again. These are performance numbers I'm seeing on that repo (I re-ran each a couple of times to make sure these numbers aren't heavy outliers):
Biome 1.9.4: `Checked 4511 files in 729ms.`
`next`: `Checked 4511 files in 744ms.`
This PR: …
> chore: drop `slotmap` and simplify locking

- crates/biome_cli/tests/commands/check.rs
- crates/biome_cli/tests/snapshots/main_cases_diagnostics/diagnostic_level.snap
- crates/biome_cli/tests/snapshots/main_cases_handle_astro_files/sorts_imports_check.snap
- crates/biome_cli/tests/snapshots/main_cases_handle_svelte_files/sorts_imports_check.snap
- crates/biome_cli/tests/snapshots/main_cases_handle_vue_files/sorts_imports_check.snap
- crates/biome_cli/tests/snapshots/main_cases_reporter_summary/reports_diagnostics_summary_check_command.snap
- crates/biome_cli/tests/snapshots/main_commands_check/applies_organize_imports_bug_4552.snap
- crates/biome_cli/tests/snapshots/main_commands_check/dont_applies_organize_imports_for_ignored_file.snap
- crates/biome_cli/tests/snapshots/main_commands_check/shows_organize_imports_diff_on_check.snap
- crates/biome_lsp/tests/server.rs
- crates/biome_service/src/file_handlers/mod.rs
Closes https://github.com/biomejs/biome/issues/4552
We aren't ready to move the organize import to be a simple assist action, so we need to turn it off completely. 
This PR fixes the false positive. 
> fix(analyzer): don't use organize imports implicitly

- crates/biome_cli/src/execute/migrate.rs
- crates/biome_cli/src/execute/mod.rs
- crates/biome_cli/src/execute/process_file/workspace_file.rs
- crates/biome_cli/src/execute/std_in.rs
- crates/biome_fs/src/path.rs
- crates/biome_lsp/src/handlers/text_document.rs
- crates/biome_lsp/src/server.rs
- crates/biome_service/src/lib.rs
- crates/biome_service/src/settings.rs
- crates/biome_service/src/workspace.rs
- crates/biome_service/src/workspace/scanner.rs
- crates/biome_service/src/workspace/server.rs
- crates/biome_service/tests/workspace.rs
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
By having both project scanning inside the workspace server, and explicit opening/closing of files through the workspace protocol, we run into a risk: What if a file was opened by the scanner, but for instance the LSP Proxy asks it to be closed? If we really close it, the analyzer wouldn't be able to extract information from it anymore.
With this PR, we protect against this scenario by tracking whether files have been opened by the scanner, and we keep them loaded in the server even when they're being closed through the workspace protocol.
I also re-added the ability to persist the node cache, but made it an option, so that the LSP Proxy can request a persistent node cache to speed up reparsing during editing, while we don't add overhead for any of the other open files in the workspace. …
> refactor: protect scanned files against closing by LSP

- CHANGELOG.md
- crates/biome_cli/src/execute/migrate/eslint_eslint.rs
- crates/biome_cli/src/execute/migrate/eslint_to_biome.rs
- crates/biome_cli/tests/commands/migrate_eslint.rs
- crates/biome_cli/tests/snapshots/main_commands_migrate_eslint/migrate_merge_with_overrides.snap
- crates/biome_deserialize/src/impls.rs
Fix https://github.com/biomejs/biome/issues/4740
I relaxed the type of `files` and `ignores` in flat ESlint configurations to accept `null` in the list.
Also, we now accept a simple string instead of an array.
This is rejected by ESlint, however, this simplification allows us to reuse `ShorthandVec`.
This avoids adding an extra type.
I modified the implementation of the deserialization of `Option<T>` to accept `null`.
I manually tested the fix and I added a related test.
> fix(migrate-eslint): allow null in file lists

- crates/biome_service/src/diagnostics.rs
- crates/biome_service/src/workspace/server.rs
- crates/biome_service/tests/workspace.rs
As the workspace server will become responsible for scanning projects, we also need to move the check for too large files into the server. Because there will be a disconnect between the initiation of the scanning and the pulling of diagnostics, we need to persist the `FileTooLarge` diagnostics. This PR implements a minimum version of this.
Later, I want to implement a `pull_diagnostics_multiple()` workspace method that can pull diagnostics for a scanned project as a whole. At that point, the persisted `FileTooLarge` will serve so we can return the right diagnostic at that point. Do you foresee any issues with this approach, @ematipico ?
> refactor: track too large files inside workspace server

- crates/biome_js_analyze/src/lint/nursery/no_restricted_imports.rs
Changed the version number from `v1.6.0` to `v2.0.0` to reflect the correct introduction version of the no-restricted-imports rule.
Issue mentioned in https://github.com/biomejs/biome/issues/4750
> docs(noRestrictedImports): update version notice

- Cargo.lock
- crates/biome_service/Cargo.toml
- crates/biome_service/src/workspace/server.rs
This is a small tweak to use `AppendOnlyVec` for `WorkspaceServer::file_sources`, instead of `RwLock<IndexSet>`.
The advantage is that with `AppendOnlyVec` we don't need to use a lock anymore, and we can still do fast lookup by index (probably a bit faster than a plain `IndexSet` even). The downside is that insertion needs to iterate over the entire vector, but then we don't expect many file sources to exist anyway.
It results in a modest performance improvement, bringing the performance of checking the entire `unleash` repository down from ~630ms to ~620ms, so about a 1.5% improvement.
> perf: use `AppendOnlyVec` for `file_sources`

- CHANGELOG.md
- crates/biome_js_analyze/src/lint/complexity/no_useless_fragments.rs
- crates/biome_js_analyze/tests/specs/complexity/noUselessFragments/issue_4208.jsx
- crates/biome_js_analyze/tests/specs/complexity/noUselessFragments/issue_4208.jsx.snap
Related issue: https://github.com/biomejs/biome/issues/4208
Fixes https://github.com/biomejs/biome/issues/4208
This PR addresses an issue where the parent of a fragment is not a `JsxTagExpression` in the case of`<A x-some-prop=<></>></>`. To resolve this, I added a handling case for `JsxAttributeInitializerClause` to ensure that the fragment is preserved.
Added a new test case in `crates/biome_js_analyze/tests/specs/complexity/noUselessFragments/issue_4208.jsx` to ensure the rule does not generate diagnostics for valid JSX attribute initializer clauses.
> fix(noUselessFragments): fix Infinite loop case

- CHANGELOG.md
- crates/biome_css_analyze/tests/specs/nursery/noDuplicateProperties/invalid.css
- crates/biome_css_analyze/tests/specs/nursery/noDuplicateProperties/invalid.css.snap
- crates/biome_css_analyze/tests/specs/nursery/noDuplicateProperties/valid.css
- crates/biome_css_analyze/tests/specs/nursery/noDuplicateProperties/valid.css.snap
- crates/biome_css_semantic/src/events.rs
fixed css semantic event so that `noDuplicateProperties` properly throws lint error when we use `@supports`.
close https://github.com/biomejs/biome/issues/4756
Please check snap shot test
> fix(css_semantic): semantic event for css supports at-rule

- Cargo.lock
- crates/biome_configuration/Cargo.toml
- crates/biome_configuration/src/html.rs
- crates/biome_configuration/src/lib.rs
- crates/biome_configuration/tests/invalid/top_level_extraneous_field.json.snap
- crates/biome_grit_formatter/src/generated.rs
- crates/biome_html_formatter/Cargo.toml
- crates/biome_html_formatter/src/context.rs
- crates/biome_service/src/file_handlers/html.rs
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
- packages/@biomejs/biome/configuration_schema.json
This sets up the end-user facing `HtmlConfiguration` for HTML. It also adds `attributePosition` to the formatter settings in some places it was missing.
This is necessary in order to test the HTML formatter with different combinations of formatter settings instead of just the defaults.
> feat(html): set up HTML configuration

- CHANGELOG.md
- crates/biome_js_formatter/src/jsx/tag/opening_element.rs
- crates/biome_js_formatter/tests/specs/jsx/bracket_same_line/bracket_same_line.jsx
- crates/biome_js_formatter/tests/specs/jsx/bracket_same_line/bracket_same_line.jsx.snap
closes #4719 
the bracketSameLine rule now works the same as prettier when a comment is placed before the last JSX attribute with configuration:
```json
"javascript": {
"formatter": {
"bracketSameLine": true
}
}
```
```diff
<Component
foo={fooValue}
// comment
- bar={barValue}
->
+ bar={barValue}>
some content
</Component>
```
added a test case and updated the snapshots.
> fix(formatter): refine the logic for identifying comments on the last attribute in JSX

- .changeset/remove_rome_binary.md
- packages/@biomejs/biome/bin/biome
Removes `ROME_BINARY`, an env variable that's been deprecated for a year
There is no other usage of `ROME_BINARY`
> refactor: remove `ROME_BINARY`

- CHANGELOG.md
- crates/biome_analyze/src/context.rs
- crates/biome_analyze/src/options.rs
- crates/biome_analyze/src/registry.rs
- crates/biome_analyze/src/signals.rs
- crates/biome_js_analyze/src/lint/nursery/use_sorted_classes.rs
- crates/biome_js_analyze/tests/specs/nursery/useSortedClasses/issue_4855.jsx
- crates/biome_js_analyze/tests/specs/nursery/useSortedClasses/issue_4855.jsx.snap
- crates/biome_js_analyze/tests/specs/nursery/useSortedClasses/issue_4855.options.json
- crates/biome_service/src/file_handlers/css.rs
- crates/biome_service/src/file_handlers/javascript.rs
- crates/biome_service/src/file_handlers/json.rs
- crates/biome_test_utils/src/lib.rs
- Adds a `preferred_jsx_quote` to the analyzer. It is used only inside the JavaScript analyzer to ensure that code fixes match the JSX quote style specified in the formatter’s configuration.
- Fixes https://github.com/biomejs/biome/issues/4855 by updating the `useSortedClasses` rule to use this new logic.
- I added a test case to useSortedClasses to check that code fixes follow the formatter’s configuration.
> fix(useSortedClasses): should suggest code fixes that match the JSX quote style of the formatter

- crates/biome_service/src/workspace/scanner.rs
- crates/biome_service/src/workspace/server.rs
- crates/biome_service/src/workspace/server.tests.rs
Makes sure that the scanner scans files in order, so that manifests are available when regular files are opened.
> fix(core): scan files in order

- crates/biome_css_parser/src/syntax/selector/pseudo_class/function_selector.rs
- crates/biome_css_parser/tests/css_test_suite/error/selector/pseudo_class/pseudo_class_function_selector/disabled/pseudo_class_function_selector_disabled.css
- crates/biome_css_parser/tests/css_test_suite/error/selector/pseudo_class/pseudo_class_function_selector/disabled/pseudo_class_function_selector_disabled.css.snap
Fixes the panic we see when running `pnpm check` in our own repo.
Add test cases.
> fix(css_parser): don't panic on unexpected EOF

- crates/biome_js_analyze/src/lint/correctness/use_exhaustive_dependencies.rs
- crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/issue4567.js
- crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/issue4567.js.snap
Adds a test case for #4567 . It appears the panic was already fixed, so I didn't have to do much for it. But I did notice an error was reported on the hook call, while the statement itself is not even complete in the given snippet. In practice, I think this means people may see the error appear while they're still writing the code, which seems not very user-friendly. So all I did was disable the error in this case.
Seeing how small this change is, I don't even think it warrants a CHANGELOG entry :sweat_smile: 
> fix(lint): don't report missing dependency on incomplete statement

- .changeset/better_control_over_linter_groups.md
- crates/biome_cli/src/execute/migrate/eslint_any_rule_to_biome.rs
- crates/biome_cli/src/execute/migrate/eslint_to_biome.rs
- crates/biome_cli/tests/cases/linter_groups_plain.rs
- crates/biome_cli/tests/cases/mod.rs
- crates/biome_cli/tests/snapshots/main_cases_linter_groups_plain/disable_all_rules_when_group_is_off.snap
- crates/biome_cli/tests/snapshots/main_cases_linter_groups_plain/enables_all_rules_when_group_is_error.snap
- crates/biome_cli/tests/snapshots/main_cases_linter_groups_plain/enables_all_rules_when_group_is_on_with_default_severity.snap
- crates/biome_configuration/src/analyzer/linter/rules.rs
- crates/biome_configuration/src/analyzer/mod.rs
- justfile
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
- packages/@biomejs/biome/configuration_schema.json
- xtask/codegen/src/generate_configuration.rs
- xtask/codegen/src/generate_migrate_eslint.rs
Part of https://github.com/biomejs/biome/issues/4662
It allows to assign to each group of the linter new options: 
- `"on"`: it enables all rules of the group, using the default severity of the rule
- `"off"`: it disable all rules
- `"info"`: it enables all rules of group, and all rules have the info severity
- `"warn"` it enables all rules of group, and all rules have the warn severity
- `"error"`: it enables all rules of group, and all rules have the error severity
I created a new type called `SeverityOrGroup<G>`, which is in charge of implementing all the functions that we already generate for each group.
I also created a new trait called `RuleGroupExt`: this allowed me to use functions like `G::default()` or `G::all_rules_as_filters()`, otherwise I would have to create an `impl …
> feat(linter): assign severity to groups

- GOVERNANCE.md
We're considering the idea of endorsing paid contracting of core contributors. This is a first proposal on how we may wish to do this.
Please consider that freelance contracts would be private contracts between the contributor and their client, and as such Biome cannot legally enforce the terms here. We can merely offer guidance and ask for abidance such that a contract can be endorsed by the project as well.
I realize that asking for 30% of a freelancer's contract amount is a large ask, so I'm especially curious what everyone's opinion is here. Some considerations:
- If we assume a freelancer pays 40% tax, the net amount paid by the freelancer is "only" 18%.
- I do believe asking for _some_ financial contribution from contributors benefiting from Biome is essential in preventing the …
> chore: paid contracting proposal

- .changeset/_fix_4875httpsgithubcombiomejsbiomeissues4875_where_the_jetbrains_ide_terminal_would_output_unclickable_relative_file_path_links_to_files_this_does_not_fix_paths_without_line_and_column_numbers_contributed_by_andrew_chen_wang.md
- CHANGELOG.md
- crates/biome_diagnostics/src/display.rs
Fixes #4874 
Jetbrains IDEs for relative file paths aren't clickable in diagnostics output. In webstorm, it requires prepending ` at ` (notice the whitespaces)
This does not fix the case where no line numbers and column numbers are displayed for relative paths. See test cases
The environment variable can be found here:
- comment: https://github.com/JetBrains/jediterm/issues/253#issuecomment-1280492436
- permalink: https://github.com/JetBrains/intellij-community/blob/5ca79d879617e9cc82f61590b8d157d6a4ad8746/plugins/terminal/src/org/jetbrains/plugins/terminal/runner/LocalOptionsConfigurer.java#L94
Test cases display:
- the environment variable
- a test where my relative path in my app was caught with a lint error but nothing was highlighted
- this PR only resolves relative file paths with …
> fix(biome_diagnostics): fix JetBrains relative file URLs should be clickable when given line and column numbers

- .changeset/fixanalyzer_suppression_comment_fails_with_inner_comments_in_functions.md
- crates/biome_analyze/src/lib.rs
- crates/biome_js_analyze/src/lib.rs
closes: #4519 
This is a little change, but it's hard for me to find and fix it.
Use the case from the issue as examples:
```ts
// biome-ignore lint/complexity/useArrowFunction: not work
const foo0 = function (bar: string) {
// biome-ignore lint/style/noParameterAssign: work
bar = "baz";
};
```
There are two suppression comments in the code:
```bash
// biome-ignore lint/complexity/useArrowFunction: not work
// biome-ignore lint/style/noParameterAssign: work
```
In the logic of the https://github.com/biomejs/biome/blob/main/crates/biome_analyze/src/lib.rs#L371 , the method `flush_matches` will choose the second suppression for the code: `function (bar: string)`, so it will not match the rule `lint/complexity/useArrowFunction` but match `lint/style/noParameterAssign`. So it will cause the …
> fix(analyzer): suppression comment fails with inner comments in functions

- .changeset/export_named_type_parser.md
- crates/biome_js_formatter/tests/specs/ts/module/export_clause.ts
- crates/biome_js_formatter/tests/specs/ts/module/export_clause.ts.snap
- crates/biome_js_parser/src/syntax/module.rs
- crates/biome_js_parser/tests/js_test_suite/ok/ts_export_named_from_specifier_with_type.ts
- crates/biome_js_parser/tests/js_test_suite/ok/ts_export_named_from_specifier_with_type.ts.snap
- crates/biome_js_parser/tests/spec_test.rs
closes: #4765
The following code: 
```ts
export { type default as CrsMeta } from './crs-meta.js'
```
it should be parsed without error.
I just add a simple judge when parser meet `T![default]`, and deal this to type alias, so it can be parsed successfully. 
i add test case.
> fix(parser): export_named_type should parse default as normal

- crates/biome_cli/tests/commands/lint.rs
- crates/biome_cli/tests/snapshots/main_commands_lint/linter_doesnt_crash_on_malformed_code_from_issue_4623.snap
- crates/biome_js_analyze/src/lint/suspicious/no_comment_text.rs
- crates/biome_rowan/src/cursor/element.rs
- crates/biome_rowan/src/cursor/node.rs
Fixes #4623 and resolves a TODO in `cursor/node.rs`.
The real fix is in `no_comment_text.rs`, where I replaced `ctx.query().range().start()` with `ctx.query().value_token().ok()?.text_range().start()`. The reason this works is that `ctx.query().range()` can return a range _with a higher starting offset_ than `ctx.query().value_token().ok()?.text_range()`, due to trimming in the former. I am not really happy with this fix, since it seems like a very easy mistake to make and there's no type safety to protect against this. It's also not really intuitive, so I'm open to better suggestions.
> fix(lint): don't crash on malformed JSX

- .changeset/add_the_new_rule_nofloatingpromises.md
- crates/biome_cli/src/execute/migrate/eslint_any_rule_to_biome.rs
- crates/biome_configuration/src/analyzer/linter/rules.rs
- crates/biome_diagnostics_categories/src/categories.rs
- crates/biome_js_analyze/src/lint/nursery.rs
- crates/biome_js_analyze/src/lint/nursery/no_floating_promises.rs
- crates/biome_js_analyze/src/options.rs
- crates/biome_js_analyze/tests/specs/nursery/noFloatingPromises/invalid.js
- crates/biome_js_analyze/tests/specs/nursery/noFloatingPromises/invalid.js.snap
- crates/biome_js_analyze/tests/specs/nursery/noFloatingPromises/invalid.ts
- crates/biome_js_analyze/tests/specs/nursery/noFloatingPromises/invalid.ts.snap
- crates/biome_js_analyze/tests/specs/nursery/noFloatingPromises/valid.js
- crates/biome_js_analyze/tests/specs/nursery/noFloatingPromises/valid.js.snap
- crates/biome_js_analyze/tests/specs/nursery/noFloatingPromises/valid.ts
- crates/biome_js_analyze/tests/specs/nursery/noFloatingPromises/valid.ts.snap
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
- packages/@biomejs/biome/configuration_schema.json
related: https://github.com/biomejs/biome/issues/3187
This pull request introduces the initial implementation of the no-floating-promises rule.
The rule reports Promise-valued statements that are not treated in one of the following ways:
- Calling .then() with two arguments
- Calling .catch() with one argument
- Awaiting the Promise
- Returning
- Using the void operator
> [!NOTE]
> ### Current Scope:
> - This PR currently covers simple async functions.
> - Currently, reassigning functions is not supported 
```
async function returnsPromise(): Promise<string> {
return 'value';
}
returnsPromise().then(() => {});
```
```
async function returnsPromise(): Promise<string> {
return 'value';
}
await returnsPromise();
void returnsPromise();
// Calling .then() with two arguments …
```
> feat(lint): implement `noFloatingPromises` rule for reguler `async` function

- crates/biome_js_analyze/src/lint/nursery/no_floating_promises.rs
- crates/biome_js_analyze/tests/specs/nursery/noFloatingPromises/invalid.ts
- crates/biome_js_analyze/tests/specs/nursery/noFloatingPromises/invalid.ts.snap
related: https://github.com/biomejs/biome/issues/3187 and https://github.com/biomejs/biome/issues/4956
This pull request introduces the support for assigned functions in `noFloatingPromises`
```
const returnsPromise = async (): Promise<string> => {
return 'value';
};
returnsPromise();
const returnsPromiseAssignedFunction = async function (): Promise<string> {
return 'value'
}
returnsPromiseAssignedFunction();
```
```
const returnsPromise = async (): Promise<string> => {
return 'value';
};
await returnsPromise();
void returnsPromise();
// Calling .then() with two arguments
returnsPromise().then(
() => {},
() => {}
);
```
> feat(lint): support assigned functions in `noFloatingPromises`

- crates/biome_dependency_graph/src/dependency_graph.rs
- crates/biome_dependency_graph/src/dependency_graph.tests.rs
- crates/biome_dependency_graph/src/resolver_cache.rs
- crates/biome_fs/src/fs.rs
- crates/biome_fs/src/fs/memory.rs
- crates/biome_fs/src/fs/os.rs
- crates/biome_package/src/node_js_package/package_json.rs
Fix #4941. We can now handle symlinks when resolving the dependency graph, which should allow us to handle many monorepo situations.
Also used `Utf8Path` a bit more internally, as I think I managed to work around some of the conversions I was struggling with.
Updated test case.
> fix(core): fix symlink handling

- crates/biome_cli/tests/commands/lint.rs
- crates/biome_cli/tests/snapshots/main_commands_lint/linter_doesnt_crash_on_malformed_code_from_issue_4723.snap
- crates/biome_css_syntax/src/generated/nodes.rs
- crates/biome_formatter/src/diagnostics.rs
- crates/biome_graphql_syntax/src/generated/nodes.rs
- crates/biome_grit_patterns/src/errors.rs
- crates/biome_grit_syntax/src/generated/nodes.rs
- crates/biome_html_syntax/src/generated/nodes.rs
- crates/biome_js_analyze/src/services/control_flow/nodes.rs
- crates/biome_js_analyze/src/services/control_flow/nodes/bogus.rs
- crates/biome_js_analyze/src/services/control_flow/visitor.rs
- crates/biome_js_syntax/src/generated/nodes.rs
- crates/biome_json_syntax/src/generated/nodes.rs
- crates/biome_markdown_syntax/src/generated/nodes.rs
- crates/biome_rowan/src/ast/mod.rs
- crates/biome_yaml_syntax/src/generated/nodes.rs
- xtask/codegen/src/generate_nodes.rs
Fixes #4723 by adding a `BogusVisitor` to our control flow graph builder. The original panic was caused by a broken assumption due to the presence of a bogus statement between the if statement and its else clause. I think the safer alternative is to just skip bogus branches from analysis.
To aid with this, codegen now generate an `Any*BogusNode` for every language as well.
> fix(core): don't build control flow graph inside bogus nodes

- .changeset/fix_1597_useexhaustivedependencies_now_consider_react_hooks_stable_within_parentheses_or_type_assertions.md
- crates/biome_js_analyze/src/react/hooks.rs
- crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/valid.ts
- crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/valid.ts.snap
Fixes #1597 (except more edge cases)
This pull request adds support of some different styles of hook calls that are considered as "stable", including:
- Parenthesized calls `(useRef())`
- Sequencial calls with a comma operator `(doSomething(), useRef())`
- Calls with a TS Non-null assertion `useRef()!`
- Calls with a TS `as` operator `useRef() as T`
- Calls with a TS `satisfies` operator `useRef() satisfies T`
Note this _doesn't_ cover all of edge cases.
Tests added.
> fix(lint): support some of wrapped hook calls in useExhaustiveDependencies

- .changeset/biome_logs_a_warning_in_case_a_folder_contains_biomejson_and_biomejsonc_and_it_will_use_biomejson_by_default.md
- crates/biome_cli/src/commands/mod.rs
- crates/biome_cli/tests/cases/config_path.rs
- crates/biome_cli/tests/commands/format.rs
- crates/biome_cli/tests/snapshots/main_cases_config_path/raises_a_warning_for_double_configuration_found.snap
- crates/biome_cli/tests/snapshots/main_cases_config_path/raises_an_error_for_no_configuration_file_found.snap
- crates/biome_cli/tests/snapshots/main_commands_format/invalid_config_file_path.snap
- crates/biome_configuration/src/diagnostics.rs
- crates/biome_configuration/src/lib.rs
- crates/biome_fs/src/fs.rs
- crates/biome_lsp/src/session.rs
- crates/biome_service/src/configuration.rs
Closes https://github.com/biomejs/biome/issues/4936
I also took the opportunity to refactor the methods that we use for auto search and loading user configuration:
- the auto search now works only for one single file, instead of accepting multiple files. This reduces the cognitive complexity, it doesn't raise diagnostic and we use a single loop,
- the logic we had in the auto search regarding "should_emit_error" was introduced only when searching for configuration files, however we raise an error only when the user provide `--config-path`, which **doesn't trigger an auto-search**.
- the loading of user configuration has been moved into its own function with its own logic, which must raise an error if we can't find a configuration file
- I refactored `load_editorconfig` and reduced its …
> fix(core): raise an error when invalid config extension is passed

- crates/biome_js_analyze/src/lint/nursery/no_floating_promises.rs
related: https://github.com/biomejs/biome/issues/4956
This PR refactors functions to return Option, aligning with the accepted coding practices in Biome as suggested [here](https://github.com/biomejs/biome/pull/4958#discussion_r1928521676)
> refactor(noFloatingPromises): update functions to return Option

- Cargo.toml
- crates/biome_analyze/src/syntax.rs
- crates/biome_formatter/src/lib.rs
- crates/biome_grit_patterns/src/pattern_compiler/compilation_context.rs
- crates/biome_yaml_parser/src/lexer/mod.rs
This PR enables `needless_lifetimes` clippy rule that is default in Rust v1.84.0.
> refactor: enable `needless_lifetimes` clippy rule

- crates/biome_migrate/src/analyzers/organize_imports.rs
- crates/biome_migrate/tests/specs/migrations/organizeImports/invalid.json.snap
> fix(migrate): fix a typo in organizeImports migration message

- crates/biome_html_formatter/src/html/lists/attribute_list.rs
- crates/biome_html_formatter/tests/specs/html/attributes/multiline/break.html
- crates/biome_html_formatter/tests/specs/html/attributes/multiline/break.html.snap
- crates/biome_html_formatter/tests/specs/html/attributes/multiline/no-break.html
- crates/biome_html_formatter/tests/specs/html/attributes/multiline/no-break.html.snap
- crates/biome_html_formatter/tests/specs/html/attributes/multiline/options.json
- crates/biome_service/src/file_handlers/html.rs
Close: https://github.com/biomejs/biome/issues/4828
Previous PR: https://github.com/biomejs/biome/pull/4972
Add break if elem has multi attributes (at multiline side).
Modified test case for element with single attribute.
> feat(format/html): apply line break with multiple attributes in multiline configuration

- .changeset/mark_useselfclosingelements_as_safe_and_improve_error_message.md
- crates/biome_js_analyze/src/lint/style/use_self_closing_elements.rs
- crates/biome_js_analyze/tests/specs/style/useSelfClosingElements/invalid.tsx.snap
- crates/biome_js_analyze/tests/specs/style/useSelfClosingElements/invalidCheckHtmlElementsFalse.tsx.snap
close https://github.com/biomejs/biome/issues/4966
> feat(lint): make useSelfClosingElements safe and improve error message

- .changeset/fix_nomissingvarfunction_false_positives_for_container_name.md
- crates/biome_css_analyze/src/lint/nursery/no_missing_var_function.rs
- crates/biome_css_analyze/tests/specs/nursery/noMissingVarFunction/valid.css
- crates/biome_css_analyze/tests/specs/nursery/noMissingVarFunction/valid.css.snap
closes #5007 
- add `container-name` to the ignored properties list
related: 
1. https://github.com/stylelint/stylelint/blob/32c9dded2b6d68ee5a435859d39b091b7f4b0a07/lib/rules/custom-property-no-missing-var-function/index.mjs#L26
2. https://developer.mozilla.org/en-US/docs/Web/CSS/container-name#formal_syntax
- added a test case
> fix(biome_css_analyze): false positive of container name in `noMissingVarFunction`

- crates/biome_html_formatter/src/html/auxiliary/opening_element.rs
- crates/biome_html_formatter/src/html/auxiliary/self_closing_element.rs
- crates/biome_html_formatter/src/html/lists/attribute_list.rs
- crates/biome_html_formatter/tests/specs/html/elements/bracket-same-line/element.html
- crates/biome_html_formatter/tests/specs/html/elements/bracket-same-line/element.html.snap
- crates/biome_html_formatter/tests/specs/html/elements/bracket-same-line/options.json
- crates/biome_html_formatter/tests/specs/html/elements/bracket-same-line/self-closing.html
- crates/biome_html_formatter/tests/specs/html/elements/bracket-same-line/self-closing.html.snap
This PR implements functionality for the `bracketSameLine` option, with a particular focus on matching prettier's emitted IR.
closes #4024
added tests
> feat(format/html): implement bracketSameLine

- crates/biome_html_formatter/src/context.rs
- crates/biome_html_formatter/src/html/auxiliary/element.rs
- crates/biome_html_formatter/tests/specs/html/attributes/break.html.snap
- crates/biome_html_formatter/tests/specs/html/attributes/multiline/break.html.snap
- crates/biome_html_formatter/tests/specs/html/attributes/multiline/no-break.html.snap
- crates/biome_html_formatter/tests/specs/html/attributes/no-break.html.snap
- crates/biome_html_formatter/tests/specs/html/attributes/self-closing.html.snap
- crates/biome_html_formatter/tests/specs/html/attributes/single-quotes.html.snap
- crates/biome_html_formatter/tests/specs/html/elements/bracket-same-line/element.html.snap
- crates/biome_html_formatter/tests/specs/html/elements/bracket-same-line/self-closing.html.snap
- crates/biome_html_formatter/tests/specs/html/elements/empty-extra-lines.html.snap
- crates/biome_html_formatter/tests/specs/html/elements/inline/tags-dont-hug-content-2.html.snap
- crates/biome_html_formatter/tests/specs/html/elements/inline/tags-dont-hug-content.html.snap
- crates/biome_html_formatter/tests/specs/html/elements/inline/tags-hug-content-longer-w-attr.html.snap
- crates/biome_html_formatter/tests/specs/html/elements/inline/tags-hug-content-w-attr.html.snap
- crates/biome_html_formatter/tests/specs/html/elements/inline/tags-hug-content.html.snap
- crates/biome_html_formatter/tests/specs/html/elements/pre-with-brackets.html.snap
- crates/biome_html_formatter/tests/specs/html/elements/pre-with-braille.html.snap
- crates/biome_html_formatter/tests/specs/html/elements/pre.html.snap
- crates/biome_html_formatter/tests/specs/html/elements/spacing/case0.html.snap
- crates/biome_html_formatter/tests/specs/html/elements/spacing/case1.html.snap
- crates/biome_html_formatter/tests/specs/html/elements/spacing/case2.html.snap
- crates/biome_html_formatter/tests/specs/html/elements/spacing/case3.html.snap
- crates/biome_html_formatter/tests/specs/html/elements/spacing/case4.html.snap
- crates/biome_html_formatter/tests/specs/html/example.html.snap
- crates/biome_html_formatter/tests/specs/html/long-content.html.snap
- crates/biome_html_formatter/tests/specs/html/many-children.html.snap
- crates/biome_html_formatter/tests/specs/html/self-closing.html.snap
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
- packages/@biomejs/biome/configuration_schema.json
This adds a `css` option for whitespace sensitivity to the HTML formattter. This option does what `strict` previously did, where it considers which elements are "inline" to determine whether or not to apply whitespace sensitivity rules. The `strict` option now considers *all* elements to be whitespace sensitive, matching prettier's behavior.
related: #4927
> feat(format/html): add `css` option for whitespace sensitivity

- crates/biome_html_formatter/src/html/lists/element_list.rs
- crates/biome_html_formatter/src/utils/metadata.rs
- crates/biome_html_formatter/tests/specs/html/long-inline-elements.html
- crates/biome_html_formatter/tests/specs/html/long-inline-elements.html.snap
This attempts to handle whitespace sensitivity cases where there's inline elements in a long chunk of text.
related: #4927
Added a new test.
> fix(format/html): enforce whitespace sensitivity for siblings in HtmlElementList

- biome.json
- crates/biome_cli/src/execute/process_file.rs
- crates/biome_cli/src/execute/process_file/format.rs
- crates/biome_cli/src/execute/process_file/lint.rs
- crates/biome_cli/src/execute/process_file/search.rs
- crates/biome_cli/src/execute/traverse.rs
- crates/biome_cli/tests/snapshots/main_commands_check/fs_error_dereferenced_symlink.snap
- crates/biome_cli/tests/snapshots/main_commands_check/fs_error_unknown.snap
- crates/biome_cli/tests/snapshots/main_commands_lint/fs_error_dereferenced_symlink.snap
- crates/biome_cli/tests/snapshots/main_commands_lint/fs_error_unknown.snap
- crates/biome_cli/tests/snapshots/main_commands_lint/include_files_in_subdir.snap
- crates/biome_cli/tests/snapshots/main_commands_lint/include_files_in_symlinked_subdir.snap
- crates/biome_css_analyze/src/registry.rs
- crates/biome_diagnostics/src/display.rs
- crates/biome_fs/src/fs.rs
- crates/biome_fs/src/fs/memory.rs
- crates/biome_fs/src/fs/os.rs
- crates/biome_js_analyze/src/registry.rs
- crates/biome_json_analyze/src/registry.rs
- crates/biome_service/src/configuration.rs
- crates/biome_syntax_codegen/src/generate_syntax_kinds.rs
- packages/@biomejs/js-api/tests/formatContent.test.ts
- packages/@biomejs/js-api/tests/lintContent.test.ts
- packages/tailwindcss-config-analyzer/src/generate-tailwind-preset.ts
- packages/tailwindcss-config-analyzer/src/introspect.ts
- packages/tailwindcss-config-analyzer/tsconfig.json
- xtask/codegen/src/generate_analyzer.rs
Closes https://github.com/biomejs/biome/issues/3946
Updated the snapshots. CI should stay green
> chore: print diagnostics using relative paths

- crates/biome_grit_parser/src/lexer/mod.rs
- crates/biome_grit_parser/src/parser/mod.rs
- crates/biome_grit_parser/src/parser/tests.rs
Fixes https://github.com/biomejs/biome/issues/5032 to prevent the parser from consuming infinite memory.
We previously only consumed new-lines in debug builds: https://github.com/biomejs/biome/pull/5033/files#diff-15e627641974e3cc1e6efc62bdc4b632ca41315fa8cc7b5bf3dd50c40df65d3eL183
This of course is very problematic when trying to use the parser in a released build.
Since this behavior only shows up in release builds, I don't have a simple way to run the tests unless we want to switch CI to use the `--release` profile for running tests.
> fix: repair explosive memory leak in GritQL parser

- crates/biome_grit_formatter/tests/specs/grit/marzano/react_hooks.grit
- crates/biome_grit_formatter/tests/specs/grit/marzano/react_hooks.grit.snap
- crates/biome_grit_formatter/tests/specs/grit/marzano/shadow_scope.grit
- crates/biome_grit_formatter/tests/specs/grit/marzano/shadow_scope.grit.snap
- crates/biome_grit_parser/src/lexer/mod.rs
- crates/biome_grit_parser/src/parser/patterns.rs
- crates/biome_grit_parser/tests/grit_test_suite/ok/ast_node.grit
- crates/biome_grit_parser/tests/grit_test_suite/ok/ast_node.grit.snap
- crates/biome_grit_parser/tests/grit_test_suite/ok/bubble_brace.grit
- crates/biome_grit_parser/tests/grit_test_suite/ok/bubble_brace.grit.snap
Ensure Biome can parse the full GritQL standard library:
- `function` needs to be usable as a name in JavaScript
- `bubble { ... }` is valid GritQL
Added spec tests
> fix(grit): patch more parser incompatibilities for complex patterns

- .changeset/violet-dingos-shake.md
- Cargo.lock
- crates/biome_service/src/workspace_types.rs
- crates/biome_wasm/Cargo.toml
- crates/biome_wasm/build.rs
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
- xtask/codegen/src/generate_bindings.rs
This is a quick and dirty hack to fix the type definition for this type when we generate the type definitions for the js api.
`serde_wasm_bindgen` indicates this is the correct type in this table here: https://github.com/RReverser/serde-wasm-bindgen?tab=readme-ov-file#supported-types
It builds and generates the correct code in `packages/@biomejs/wasm-web/biome_wasm.d.ts`
> fix(js-api): fix type definition for IFileFeaturesResult

- .changeset/dull-gorillas-juggle.md
- crates/biome_js_analyze/src/lint/correctness/use_jsx_key_in_iterable.rs
> fix(lint): add react domain to `useJsxKeyInIterable`

- crates/biome_cli/src/service/windows.rs
- crates/biome_cli/tests/commands/check.rs
- crates/biome_cli/tests/commands/format.rs
- crates/biome_cli/tests/commands/lint.rs
- justfile
This PR aims to solve the errors thrown by `just l` and `just _touch` on Windows systems. 
The linter succeeds in CI but not locally on my Windows machine. This is because it seems to not lint code with the `#[cfg(target_os = "windows")]` directive as the runner OS is Linux. In the future I suggest using a matrix runner in CI that runs the same linter workflow on both Windows and Unix so every OS is covered.
These were the fixes I had to implement on my local Windows machine, as recommend by the linter:
- Removed unnecessary explicit references (`&`)
- Added `#[cfg(not(windows))]` to Linux only variables, avoiding unused variable errors
- Wrote hexadecimal with equally sized groups of digits
Made the script call `powershell` explicitly, this allows the user to use either CMD, Powershell, …
> chore: fix windows specific script errors

- crates/biome_html_formatter/src/html/auxiliary/element.rs
- crates/biome_html_formatter/src/html/auxiliary/opening_element.rs
- crates/biome_html_formatter/tests/specs/html/content-breaks-when-attr-breaks.html
- crates/biome_html_formatter/tests/specs/html/content-breaks-when-attr-breaks.html.snap
- crates/biome_html_formatter/tests/specs/html/elements/bracket-same-line/element.html.snap
closes #5026
Added a snapshot test, and none of the other tests are affected.
> fix(format/html): make element children break if attributes break

- .github/actions/build-cli/action.yml
- .github/workflows/preview.yml
- .github/workflows/pull_request_js.yml
- .github/workflows/release.yml
This PR does the following:
- creates a new workflow called `preview.yml` which we can use to create **Preview releases**. Preview releases are the "new nightlies", where a preview release is only built upon a workflow dispatch and approval of a core contributors. While nightly releases are good, they use a lot of compute time in the CI and don't publish all of them.
- it moves the shared logic for building the binaries inside a composite job, so we don't repeat ourselves 
- preview releases and prod releases will have two separate workflows/files
This new preview workflow relies on the the [changeset snapshot release](https://github.com/changesets/changesets/blob/main/docs/snapshot-releases.md). They have their own naming convention, but I believe it's fine. 
Proof read. I will test it …
> ci: rebrand nightly releases as preview releases

- .changeset/lemon-flies-jam.md
- crates/biome_js_analyze/src/lint/suspicious/no_console.rs
- crates/biome_js_analyze/tests/spec_tests.rs
- crates/biome_js_analyze/tests/specs/suspicious/noConsole/issue_5053.js
- crates/biome_js_analyze/tests/specs/suspicious/noConsole/issue_5053.js.snap
> fix(linter): `noConsole` inside arrow function expressions

- crates/biome_js_formatter/src/comments.rs
- crates/biome_lsp/src/session.rs
- crates/biome_service/src/diagnostics.rs
Closes https://github.com/biomejs/biome/issues/3518
I tested locally and confirmed that new message is shown when the `.editorconfig` is incorrect
> fix(lsp): better error message when editorconfig is broken 

- crates/biome_css_formatter/src/context.rs
- crates/biome_formatter/src/format_element/document.rs
- crates/biome_formatter/src/lib.rs
- crates/biome_formatter/src/printer/printer_options/mod.rs
- crates/biome_graphql_formatter/src/context.rs
- crates/biome_graphql_formatter/src/graphql/value/object_value.rs
- crates/biome_grit_formatter/src/context.rs
- crates/biome_grit_formatter/src/grit/auxiliary/like.rs
- crates/biome_grit_formatter/src/grit/auxiliary/map.rs
- crates/biome_grit_formatter/src/grit/auxiliary/sequential.rs
- crates/biome_grit_formatter/src/grit/patterns/curly_pattern.rs
- crates/biome_grit_formatter/src/grit/patterns/pattern_any.rs
- crates/biome_grit_formatter/src/grit/patterns/pattern_or.rs
- crates/biome_grit_formatter/src/grit/patterns/pattern_or_else.rs
- crates/biome_grit_formatter/src/grit/predicates/predicate_and.rs
- crates/biome_grit_formatter/src/grit/predicates/predicate_any.rs
- crates/biome_grit_formatter/src/grit/predicates/predicate_curly.rs
- crates/biome_grit_formatter/src/grit/predicates/predicate_or.rs
- crates/biome_html_formatter/src/context.rs
- crates/biome_js_formatter/src/context.rs
- crates/biome_json_formatter/src/context.rs
- crates/biome_json_formatter/src/json/value/object_value.rs
Remove non-printing related options like `bracket_spacing` from `FormatOptions`
CI passes
> refactor(formatter): remove non-printing related options from `FormatOptions`

- .changeset/gold-buses-tap.md
- crates/biome_js_parser/src/syntax/typescript/ts_parse_error.rs
- crates/biome_js_parser/src/syntax/typescript/types.rs
- crates/biome_js_parser/tests/js_test_suite/error/import_type_error.ts
- crates/biome_js_parser/tests/js_test_suite/error/import_type_error.ts.snap
- crates/biome_js_parser/tests/spec_test.rs
closes: #4982 
The follwing code will throw a syntax error:
```ts
type T = import;
type U = typeof import;
```
I add test case for this.
> fix(parser): throw syntax error for import without arguments

- .github/workflows/pull_request.yml
- .gitignore
- e2e-tests/README.md
- e2e-tests/relative-path/biome.json
- e2e-tests/relative-path/src/file.js
- e2e-tests/relative-path/test.sh
- e2e-tests/test-all.sh
This PR adds end-to-end tests.
A test is a directory in the `e2e-tests` directory and consists of a shell script named `test.sh`.
All tests are executed thanks to `e2e-tests/test-all.sh`.
I added a workflow in the `pull_request` action.
CI must pass.
> test: add end-to-end tests

- crates/biome_configuration/src/analyzer/linter/mod.rs
- crates/biome_service/src/workspace_types.rs
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
- packages/@biomejs/biome/configuration_schema.json
- xtask/codegen/Cargo.toml
- xtask/codegen/src/generate_bindings.rs
This fixes the generated type for `domains` in the linter configuration. Now, that type gets emitted is `Record<RuleDomain, RuleDomainValue>`.
I've tested this on the website repo, and actually both an object and a `Map` work. I picked `Record` here since building `Map`s tends to be a little unergonomic.
> fix(js-api): fix the generated types for rule domains

- .changeset/hot-moons-kiss.md
- crates/biome_cli/tests/snapshots/main_commands_check/check_help.snap
- crates/biome_cli/tests/snapshots/main_commands_ci/ci_help.snap
- crates/biome_cli/tests/snapshots/main_commands_format/format_help.snap
- crates/biome_configuration/src/javascript/formatter.rs
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
- packages/@biomejs/biome/configuration_schema.json
This pull request renames the CLI flag `--javascript-attribute-position` to `--javascript-formatter-attribute-position` to keep naming consistency.
Snapshot updated, existing tests should pass.
> feat(cli)!: rename `--javascript-attribute-position` to `--javascript-formatter-attribute-position`

- .changeset/funny-beans-vanish.md
- crates/biome_cli/tests/snapshots/main_commands_check/check_help.snap
- crates/biome_cli/tests/snapshots/main_commands_ci/ci_help.snap
- crates/biome_cli/tests/snapshots/main_commands_format/format_help.snap
- crates/biome_configuration/src/javascript/formatter.rs
This pull request fixes a CLI flag `--bracket-spacing` is duplicated between the global configuration and the lang-specific override for JavaScript.
Snapshot changed, existing tests should pass.
> fix(cli): fix CLI flag of `bracketSpacing` option for lang-specific override

- crates/biome_glob/src/editorconfig.rs
- crates/biome_glob/src/lib.rs
This PR adds `biome_glob::editorconfig::EditorconfigGlob` that tries to match as close as possible the test suite for Editorconfig globs.
This is built on the `globset` crate.
The `convert_glob` function performs some adjustments in order to be compatible with the glob format of the `globset` crate.
The current implementation has some limitations:
- Nested alternates (choices) are not supported.
For example, `{a,b{a,b},d}` is not supported
- Empty choice such as `{a,b,}` is not supported (silently ignored)
- `a**b` is translated to `a*/**/b`.
Thus, this doesn't match `ab` or `axb`.
I plan to use this new implementation in a future PR.
This is required for progressing on #4611
I added all tests of the Editorconfig test suite.
I commented the tests that fail because of the limitations of …
> feat(biome_glob): add Editorconfig globs

- crates/biome_js_analyze/tests/specs/nursery/noAwaitInLoop/invalid.js.snap
Looks like two PRs were merged that influenced each other's snapshots.
CI should be green again.
> chore: fix snaphots

- .changeset/gentle-spies-drum.md
- .changeset/sour-coats-shake.md
- crates/biome_cli/tests/snapshots/main_commands_check/check_help.snap
- crates/biome_cli/tests/snapshots/main_commands_ci/ci_help.snap
- crates/biome_cli/tests/snapshots/main_commands_format/format_help.snap
- crates/biome_configuration/src/javascript/formatter.rs
Follow-up of #5068 
Split from #5082 
I renamed the CLI flag to keep consistency in formatter related flags.
CLI snapshots are updated to reflect the change.
> fix(cli): rename `--javascript-object-wrap` to `--javascript-formatter-object-wrap`

- crates/biome_formatter/src/comments/map.rs
- crates/biome_formatter/src/group_id.rs
- crates/biome_formatter/src/lib.rs
Resolved these warnings on `cargo check -p biome_cli --release`:
```
warning: unused variable: `token`
--> crates/biome_formatter/src/lib.rs:1939:48
|
1939 |     pub fn track_token<L: Language>(&mut self, token: &SyntaxToken<L>) {
|                                                ^^^^^ help: if this is intentional, prefix it with an underscore: `_token`
|
= note: `#[warn(unused_variables)]` on by default
warning: unused variable: `root`
--> crates/biome_formatter/src/lib.rs:1973:60
|
1973 |     pub fn assert_formatted_all_tokens<L: Language>(&self, root: &SyntaxNode<L>) {
|                                                            ^^^^ help: if this is intentional, prefix it with an underscore: `_root`
warning: method `all_parts` is never used
--> …
```
> chore: eliminate some warnings on release build

- .github/workflows/benchmark.yml
Benchmark CI is failing randomly, and it seems killed as Out-of-Memory (e.g. https://github.com/biomejs/biome/actions/runs/13453650349/job/37592835454).
`cargo codspeed build` invokes a `cargo build` command in it, so it can accept `CARGO_BUILD_JOBS` environment variable to limit how many jobs to be run in parallel.
I tried limiting the jobs in the different branch, and it seems mitigating the issue (at least it succeeded twice in this run: https://github.com/biomejs/biome/actions/runs/13451944211).
Let's try reducing the number of parallel jobs to see the issue to be resolved for now.
~Benchmark CI will run on this pull request, and all PRs after merged.~
All PRs including parser, formatter, or analyzer changes will run the Benchmark workflow, let's see it keeps failing or not after …
> ci: reduce max build jobs on cargo to mitigate OOM

- .changeset/cyan-beans-yawn.md
- crates/biome_js_formatter/src/utils/object_like.rs
- crates/biome_js_formatter/tests/specs/ts/object/objects.ts
- crates/biome_js_formatter/tests/specs/ts/object/objects.ts.snap
Closes #2406
Prettier seems not breaking properties of a type annotation in function parameters. This pull request adds an exception to formatting object-like nodes to be consistent with Prettier.
Snapshot tests added.
> fix(formatter): do not break properties of type annotation in function parameters

- .changeset/naming-conventions-regex-allow-char-escaping-at-start-of-regex-groups.md
- crates/biome_js_analyze/src/lint/style/use_filenaming_convention.rs
- crates/biome_js_analyze/src/lint/style/use_naming_convention.rs
- crates/biome_js_analyze/src/utils/restricted_regex.rs
Fixes https://github.com/biomejs/biome/issues/5173
The issue comes from the regex validator.
Only escapes sequence at the start of capturing regex group were ignored.
> fix(linter): allow escaping at the start of a regex group

- .changeset/remove-enum-member-case.md
- crates/biome_cli/src/execute/migrate/eslint_typescript.rs
- crates/biome_configuration/tests/invalid/naming_convention_incorrect_options.json.snap
- crates/biome_js_analyze/src/lint/style/use_naming_convention.rs
- crates/biome_js_analyze/tests/specs/style/useNamingConvention/malformedOptions.js.snap
- crates/biome_js_analyze/tests/specs/style/useNamingConvention/validEnumMemberCamelCase.options.json
- crates/biome_js_analyze/tests/specs/style/useNamingConvention/validEnumMemberConstantCase.options.json
- crates/biome_migrate/src/analyzers.rs
- crates/biome_migrate/src/analyzers/use_naming_convention_enum_member_case.rs
- crates/biome_migrate/tests/specs/migrations/useNamingConventionEnumMemberCase/invalid.json
- crates/biome_migrate/tests/specs/migrations/useNamingConventionEnumMemberCase/invalid.json.snap
- crates/biome_migrate/tests/specs/migrations/useNamingConventionEnumMemberCase/invalid_with_conventions.json
- crates/biome_migrate/tests/specs/migrations/useNamingConventionEnumMemberCase/invalid_with_conventions.json.snap
- crates/biome_migrate/tests/specs/migrations/useNamingConventionEnumMemberCase/invalid_with_empty_conventions.json
- crates/biome_migrate/tests/specs/migrations/useNamingConventionEnumMemberCase/invalid_with_empty_conventions.json.snap
- crates/biome_migrate/tests/specs/migrations/useNamingConventionEnumMemberCase/valid.json
- crates/biome_migrate/tests/specs/migrations/useNamingConventionEnumMemberCase/valid.json.snap
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
- packages/@biomejs/biome/configuration_schema.json
Remove the `enumMemberCase` option from the `useNamingConvention` lint rule.
I added a migration rule to convert `enumMemberCase` into `conventions`.
I added migration tests and updated `useNamingConvention` tests.
> refactor(useNamingConvention): remove `enumMemberCase` option

- crates/biome_analyze/src/diagnostics.rs
- crates/biome_analyze/src/lib.rs
- crates/biome_analyze/src/rule.rs
- crates/biome_analyze/src/suppressions.rs
- crates/biome_css_formatter/src/comments.rs
- crates/biome_diagnostics_categories/src/categories.rs
- crates/biome_diagnostics_categories/src/lib.rs
- crates/biome_graphql_formatter/src/comments.rs
- crates/biome_html_formatter/src/comments.rs
- crates/biome_js_analyze/tests/plugin/preferObjectSpreadSuppression.grit
- crates/biome_js_analyze/tests/plugin/preferObjectSpreadSuppression.grit.snap
- crates/biome_js_analyze/tests/plugin/preferObjectSpreadSuppression.js
- crates/biome_js_analyze/tests/plugin/preferObjectSpreadSuppressionAll.grit
- crates/biome_js_analyze/tests/plugin/preferObjectSpreadSuppressionAll.grit.snap
- crates/biome_js_analyze/tests/plugin/preferObjectSpreadSuppressionAll.js
- crates/biome_js_analyze/tests/spec_tests.rs
- crates/biome_js_formatter/src/comments.rs
- crates/biome_json_formatter/src/comments.rs
- crates/biome_plugin_loader/src/analyzer_grit_plugin.rs
- crates/biome_suppression/src/lib.rs
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
task: https://github.com/biomejs/biome/issues/4667
changes are split into 2 parts:
1. during the existing workflow for lint suppression, we need to add new fields to record suppression for plugins
2. during plugin evaluation, we need to handle each diagnosis, suppress it if matched
plugin suppression reuse most of the existing lint suppression workflow, but new fields are added to handle dynamic plugin names that users input.
file: crates/biome_suppression/src/lib.rs
each suppression comment is parse a single Suppression<'a>
here, a new 'subcategory' is added to the parse result
In the case for plugin, category will be 'plugin', and subcategory will be the custom plugin name that users input
```git
#[derive(Debug, PartialEq, Eq)]
pub struct Suppression<'a> {
// ...
-   pub categories: …
```
> feat: add plugin suppression

- crates/biome_analyze/src/diagnostics.rs
- crates/biome_analyze/src/lib.rs
- crates/biome_analyze/src/rule.rs
- crates/biome_analyze/src/suppressions.rs
- crates/biome_css_formatter/src/comments.rs
- crates/biome_diagnostics_categories/src/categories.rs
- crates/biome_graphql_formatter/src/comments.rs
- crates/biome_html_formatter/src/comments.rs
- crates/biome_js_analyze/tests/plugin/preferObjectSpreadSuppression.grit
- crates/biome_js_analyze/tests/plugin/preferObjectSpreadSuppression.grit.snap
- crates/biome_js_analyze/tests/plugin/preferObjectSpreadSuppression.js
- crates/biome_js_analyze/tests/plugin/preferObjectSpreadSuppressionAll.grit
- crates/biome_js_analyze/tests/plugin/preferObjectSpreadSuppressionAll.grit.snap
- crates/biome_js_analyze/tests/plugin/preferObjectSpreadSuppressionAll.js
- crates/biome_js_analyze/tests/spec_tests.rs
- crates/biome_js_formatter/src/comments.rs
- crates/biome_json_formatter/src/comments.rs
- crates/biome_plugin_loader/src/analyzer_grit_plugin.rs
- crates/biome_suppression/src/lib.rs
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
#5139 was merged to `next` branch, which is no longer available since the branch is already merged to `main`. Re-merging it to `main`.
cc @wanghaoPolar 
N/A
> chore: merge next to main

- .github/workflows/pull_request.yml
- .github/workflows/pull_request_js.yml
- .github/workflows/pull_request_node.yml
From https://github.com/biomejs/biome/pull/5190#issuecomment-2677793625
Testing Node.js API should be triggered on either Rust files or JS/TS files are changed. I added a new workflow `pull_request_node.yml` and moved the job.
Plus, I added `package.json` and `pnpm-lock.yaml` files to the trigger of `pull_request_js.yml` so any package updates will trigger the workflow.
Unfortunately this PR doesn't have any changes to trigger the workflow, but we can check in #5190 after merged this. At least existing CIs shouldn't be an error on the analysing phase.
> ci: move `test-node-api` job to a new `pull_request_node.yml` workflow

- crates/biome_js_analyze/tests/plugin/preferObjectSpreadSuppression.grit.snap
Follow-up of #5139, #5187 
Updating the snapshots added in #5139, which was outdated in `main` branch
Snapshot tests should pass.
> test(lint): update snapshots for #5139

- package.json
This pull request upgrades pnpm to v10 (latest).
I don't know why this is not yet achieved by Renovate.
Existing CIs for Node.js should pass.
> build: upgrade pnpm to v10

- crates/biome_js_analyze/tests/specs/nursery/useConsistentObjectDefinition/invalidExplicit.js.snap
- crates/biome_js_analyze/tests/specs/nursery/useConsistentObjectDefinition/invalidShorthand.js.snap
This PR updates the snapshots that were failing from a previous PR I recently merged
CI should pass
> test: update snapshots

- crates/biome_lsp/src/capabilities.rs
This PR fills in missing capabilities for workspace folder notifications in Biome LSP implementation.
In Zed we've reworked how language servers are initialized in https://github.com/zed-industries/zed/pull/24038 ; one of the consequences is that we no longer send out workspaceFolders in `InitializeParams`, instead opting to send out notifications when workspace folders are discovered. It works all fine and dandy with Biome (as it already supports that notification), except that we never actually send out the notification as Biome does not declare a capability for it.
The change from forelinked PR is going to land in Stable tomorrow. I've just learned about Biome breakage with new code today, but I'm sorry for the late notice regardless.
Biome language server built from this commit works …
> fix(lsp): fill in missing workspaceFolders capabilities

- crates/biome_analyze/src/rule.rs
- crates/biome_cli/tests/snapshots/main_commands_explain/explain_valid_rule.snap
This PR fixes a small bug in the explain command. Changeset not needed because this new version isn't released yet.
Snapshot updated
> fix: explain command for rule

- crates/biome_js_analyze/src/lint/nursery/no_floating_promises.rs
- crates/biome_js_analyze/tests/specs/nursery/noFloatingPromises/invalid.ts
- crates/biome_js_analyze/tests/specs/nursery/noFloatingPromises/invalid.ts.snap
- crates/biome_js_analyze/tests/specs/nursery/noFloatingPromises/valid.ts
- crates/biome_js_analyze/tests/specs/nursery/noFloatingPromises/valid.ts.snap
https://github.com/biomejs/biome/issues/4956
This pull request introduces the support for promise call in function argument for `noFloatingPromises`
```
type Props = {
a: string;
returnsPromise: () => Promise<void>;
};
async function testCallingReturnsPromise(props: Props) {
props.returnsPromise().then(() => {});
}
const testDestructuringAndCallingReturnsPromise = async ({
returnsPromise,
}: Props) => {
returnsPromise();
};
async function testPassingReturnsPromiseDirectly(
returnsPromise: () => Promise<void>
) {
returnsPromise();
}
async function testCallingReturnsPromiseFromObject(props: {
returnsPromise: () => Promise<void>;
}) {
props.returnsPromise();
}
async function testDestructuringAndCallingReturnsPromiseFromRest({ a, ...rest }: Props) {
rest.returnsPromise().then(() => …
```
> feat(lint): support promise in function argument for `noFloatingPromises`

- .changeset/funny-planes-care.md
- crates/biome_lsp/src/extension_settings.rs
- crates/biome_lsp/src/server.rs
- crates/biome_lsp/src/session.rs
As the first step of #5089, this pull request adds a new option `experimental.configurationPath` to the response of `workspace/configuration` request. It will affect when loading workspace configurations, preferred over the default `biome.json` in the workspace.
For the new option, I tested my modified build of biome-intellij with `workspace/configuration` support added. I could confirm that two projects work in parallel with different Biome configurations.
> feat(lsp): allow overriding the configuration path from LSP workspaces

- crates/biome_analyze/src/lib.rs
- crates/biome_grit_patterns/src/pattern_compiler/call_compiler.rs
- crates/biome_js_analyze/src/lint/a11y/use_alt_text.rs
- crates/biome_js_analyze/src/lint/a11y/use_anchor_content.rs
- crates/biome_js_analyze/src/lint/a11y/use_heading_content.rs
- crates/biome_js_analyze/src/lint/a11y/use_html_lang.rs
- crates/biome_js_analyze/src/lint/a11y/use_iframe_title.rs
- crates/biome_js_analyze/src/lint/a11y/use_valid_anchor.rs
- crates/biome_js_analyze/src/lint/correctness/use_exhaustive_dependencies.rs
- crates/biome_js_analyze/src/lint/nursery/no_constant_binary_expression.rs
- crates/biome_js_analyze/src/lint/nursery/no_static_element_interactions.rs
- crates/biome_js_analyze/src/lint/style/use_self_closing_elements.rs
- crates/biome_js_analyze/src/lint/suspicious/no_prototype_builtins.rs
- crates/biome_js_formatter/src/comments.rs
- crates/biome_js_formatter/src/js/expressions/call_arguments.rs
- crates/biome_js_formatter/src/utils/conditional.rs
- crates/biome_js_syntax/src/jsx_ext.rs
- crates/biome_service/src/file_handlers/mod.rs
- crates/biome_service/src/settings.rs
- crates/biome_string_case/src/lib.rs
- rust-toolchain.toml
- xtask/coverage/src/js/test262.rs
Part of #5196 
Rust 2024 is supported since Rust 1.85.0, so we need to upgrade the toolchain first.
> build: upgrade toolchain to Rust 1.85.0

- Cargo.toml
- crates/biome_cli/tests/commands/rage.rs
- crates/biome_formatter_test/src/diff_report.rs
- crates/biome_js_parser/src/lexer/mod.rs
- crates/biome_rowan/src/arc.rs
- crates/biome_rowan/src/green/node.rs
- crates/biome_rowan/src/green/node_cache.rs
- crates/biome_rowan/src/green/token.rs
- crates/biome_rowan/src/green/trivia.rs
- crates/biome_test_utils/src/lib.rs
- xtask/src/glue.rs
Part of #5196 
This pull request adds missing `unsafe` blocks inside `unsafe` functions, and `unsafe` keyword on `extern` blocks, which is required since Rust 2024.
> fix: add missing unsafe blocks and unsafe keyword on extern blocks

- Cargo.lock
- Cargo.toml
- crates/biome_analyze/src/categories.rs
- crates/biome_configuration/src/analyzer/mod.rs
- crates/biome_configuration/src/bool.rs
- crates/biome_configuration/src/lib.rs
- crates/biome_configuration/src/overrides.rs
- crates/biome_diagnostics/src/display/backtrace.rs
- crates/biome_diagnostics/src/serde.rs
- crates/biome_diagnostics_categories/build.rs
- crates/biome_fs/src/path.rs
- crates/biome_glob/src/editorconfig.rs
- crates/biome_glob/src/lib.rs
- crates/biome_grit_patterns/src/grit_built_in_functions.rs
- crates/biome_grit_patterns/src/grit_target_language.rs
- crates/biome_js_analyze/src/lint/correctness/no_undeclared_dependencies.rs
- crates/biome_js_analyze/src/lint/style/use_filenaming_convention.rs
- crates/biome_js_analyze/src/lint/style/use_naming_convention.rs
- crates/biome_js_analyze/src/react/hooks.rs
- crates/biome_js_analyze/src/utils/restricted_regex.rs
- crates/biome_service/src/workspace.rs
- crates/biome_service/src/workspace_types.rs
- crates/biome_text_size/src/schemars_impls.rs
- crates/biome_wasm/build.rs
- crates/tests_macros/src/lib.rs
- xtask/codegen/src/generate_bindings.rs
This is the first step of #5196, starting with an easy one :)
`gen` is now a reserved keyword since Rust 2024. All found usages were for schemars, which already supports Rust 2024 edition per https://github.com/GREsau/schemars/pull/378.
This pull request updates schemars to the latest, and removes all usages of `gen` identifiers from the project.
> fix: remove usages of gen reserved keyword

- .changeset/preserve-useless-escapes.md
- crates/biome_formatter/src/token/string.rs
- crates/biome_js_formatter/src/utils/string_utils.rs
- crates/biome_js_formatter/tests/specs/prettier/js/quote-props/objects.js.prettier-snap
- crates/biome_js_formatter/tests/specs/prettier/js/quotes/strings.js.prettier-snap
- crates/biome_js_formatter/tests/specs/prettier/js/strings/non-octal-eight-and-nine.js.prettier-snap
- crates/biome_json_formatter/src/format_string.rs
- crates/biome_json_formatter/tests/specs/json/object/string.json.snap
- crates/biome_json_formatter/tests/specs/prettier/json/json/pass1.json.prettier-snap
- crates/biome_json_formatter/tests/specs/prettier/json/json/pass1.json.snap
Part of https://github.com/biomejs/biome/issues/1090
This PR ensures that our formatter matches the behavior of Prettier 3.4+ by preserving useless escape sequences.
I updated the corresponding Prettier snapshots.
> refactor(formatter): preserve useless escapes

- Cargo.toml
- crates/biome_formatter/src/comments.rs
- crates/biome_grit_patterns/src/grit_target_node.rs
- crates/biome_js_analyze/src/lint/correctness/use_exhaustive_dependencies.rs
- crates/biome_js_analyze/src/react/hooks.rs
- crates/biome_js_semantic/src/semantic_model/closure.rs
- crates/biome_js_semantic/src/semantic_model/scope.rs
- crates/biome_js_syntax/src/expr_ext.rs
- crates/biome_rowan/src/cursor/element.rs
- crates/biome_rowan/src/cursor/node.rs
- crates/biome_rowan/src/cursor/token.rs
- crates/biome_rowan/src/syntax/element.rs
- crates/biome_rowan/src/syntax/node.rs
- crates/biome_rowan/src/syntax/token.rs
- crates/biome_rowan/src/syntax_node_text.rs
- xtask/codegen/src/generate_analyzer.rs
Part of #5196 
In Rust 2024 edition, we need to add `use<>` notation to control which lifetime is captured in RPIT's (return-position impl Trait). This pull request adds these notations based on the `impl_trait_overcaptures` lint rule, before upgrading to 2024.
ref: https://doc.rust-lang.org/edition-guide/rust-2024/rpit-lifetime-capture.html
> fix: add missing `use<>` to RPIT's

- Cargo.toml
- crates/biome_css_semantic/src/semantic_model/model.rs
- crates/biome_formatter/src/macros.rs
- crates/biome_js_analyze/src/lint/suspicious/no_misleading_character_class.rs
- crates/biome_wasm/Cargo.toml
- fuzz/Cargo.toml
- rustfmt.toml
- xtask/Cargo.toml
- xtask/bench/Cargo.toml
- xtask/codegen/Cargo.toml
- xtask/coverage/Cargo.toml
- xtask/libs_bench/Cargo.toml
- xtask/rules_check/Cargo.toml
> build: upgrade to Rust 2024 edition

- crates/biome_css_analyze/src/lint/nursery/no_useless_escape_in_string.rs
- crates/biome_css_analyze/tests/specs/nursery/noUselessEscapeInString/invalid.css
- crates/biome_css_analyze/tests/specs/nursery/noUselessEscapeInString/invalid.css.snap
- crates/biome_js_analyze/src/lint/nursery/no_useless_escape_in_string.rs
- crates/biome_js_analyze/tests/specs/nursery/noUselessEscapeInString/invalid.js
- crates/biome_js_analyze/tests/specs/nursery/noUselessEscapeInString/invalid.js.snap
I thought we renamed `text` to `text_with_trivia` and `text_trimmed` to `text`.
This is the case except for tokens.
This PR fixes the `noUselessEscapeInString` rule by using `text_trimmed` instead of `text`.
I added trivias in the tests.
> fix(noUselessEscapeInString): use text_trimmed instead of text

- crates/biome_js_analyze/src/lint/complexity/no_useless_catch.rs
- crates/biome_js_analyze/src/lint/correctness/no_nonoctal_decimal_escape.rs
- crates/biome_js_analyze/src/lint/nursery/no_floating_promises.rs
- crates/biome_js_analyze/src/lint/nursery/no_secrets.rs
- crates/biome_js_analyze/src/lint/nursery/no_template_curly_in_string.rs
- crates/biome_js_analyze/src/lint/nursery/no_useless_string_raw.rs
- crates/biome_js_analyze/src/lint/nursery/use_parse_int_radix.rs
- crates/biome_js_analyze/src/lint/style/no_shouty_constants.rs
- crates/biome_js_analyze/src/lint/style/no_unused_template_literal.rs
- crates/biome_js_analyze/src/lint/style/use_for_of.rs
- crates/biome_js_analyze/src/lint/suspicious/no_misleading_character_class.rs
- crates/biome_js_analyze/src/lint/suspicious/no_misplaced_assertion.rs
- crates/biome_js_analyze/src/lint/suspicious/no_suspicious_semicolon_in_jsx.rs
- crates/biome_js_analyze/src/lint/suspicious/no_then_property.rs
- crates/biome_js_analyze/tests/specs/style/noShoutyConstants/invalid.js.snap
- crates/biome_js_analyze/tests/specs/suspicious/noMisleadingCharacterClass/invalid.js.snap
This PR fixes several js lint rules that wrongly use `text` instead of `text_trimmed`.
CI must pass.
> fix(js/linter): use text_trimmed instead of text

- crates/biome_formatter/src/builders.rs
- crates/biome_formatter/src/macros.rs
Follow-up of #5224 
Per [tail expression temporary scope](https://doc.rust-lang.org/edition-guide/rust-2024/temporary-tail-expr-scope.html) change in Rust 2024, we can't use `unsafe` block in the `best_fitting!` macro anymore. I think hiding `BestFitting::from_arguments_checked` from documentation and using it from the macro directly is the better way to handle the problem.
rustc should be happy
> refactor: better handling for the lifetime extension issue

- xtask/src/lib.rs
Closes #5258 
I added checking the rustfmt version before running. Plus, I added a `OnceLock` to run `rustfmt --version` only once.
The codegen CI should pass.
> feat(xtask): check rustfmt version in codegen

- .github/workflows/pull_request.yml
Fixing `cargo-udeps` issue:
```
error: toolchain '1.85.0-x86_64-unknown-linux-gnu' is not installed
help: run `rustup toolchain install 1.85.0-x86_64-unknown-linux-gnu` to install it
```
See: https://github.com/biomejs/biome/actions/runs/13633509173/job/38106518433
CI should be green again.
> ci: fix `udeps` workflows

- .changeset/pretty-buttons-taste.md
- crates/biome_analyze/src/categories.rs
- crates/biome_analyze/src/rule.rs
- crates/biome_lsp/src/capabilities.rs
- crates/biome_lsp/src/handlers/analysis.rs
- crates/biome_lsp/src/server.tests.rs
Closes https://github.com/biomejs/biome/issues/5058
This PR contains two fixes:
- It changes the order of the code actions provided to the LSP client, and now the safe fix is at the first position. Check the screenshot later.
- It removes `source.fixAll.biome` from the fixed filters that are sent to the code actions method. The fix all filter is only opt-in, and it prevented from showing the suppressions code actions 
Updated the tests. Manually tested with Zed
> fix(lsp): order of code actions

- crates/biome_cli/src/commands/daemon.rs
- crates/biome_lsp/src/server.tests.rs
- crates/biome_service/src/workspace_watcher.rs
This should hopefully stabilise the watcher tests on macOS. I did find FSEvents on Mac to be _very_ unstable, to the point that tests would sometimes receive FS events for fixture preparation that happened even before the watcher was enabled. In the debugger I'm also still seeing weird effects... but at least when running `cargo tests`, it does appear stable. Fingers crossed...
CI should be green.
> chore: stabilise tests on macOS

- .changeset/chubby-cameras-argue.md
- crates/biome_cli/src/commands/daemon.rs
- crates/biome_cli/src/commands/mod.rs
- crates/biome_cli/src/lib.rs
- crates/biome_cli/src/service/unix.rs
- crates/biome_cli/src/service/windows.rs
- crates/biome_cli/tests/main.rs
- crates/biome_cli/tests/snapshots/main_commands_lsp_proxy/lsp_proxy_help.snap
- crates/biome_lsp/src/server.rs
- crates/biome_lsp/src/server.tests.rs
- crates/biome_lsp/src/session.rs
Part of #5089 
This pull request removes `--config-path` option from `biome lsp-proxy` and `biome start` commands.
Snapshots updated.
> feat(lsp)!: remove `--config-path` from lsp-proxy and daemon

- Cargo.lock
- Cargo.toml
- crates/biome_dependency_graph/Cargo.toml
- crates/biome_dependency_graph/src/resolver_cache.rs
Bumps `papaya` to `0.2`. One option that we used to set explicitly was removed, and performance should've improved further.
Tests should remain green.
> chore: bump papaya

- Cargo.lock
- crates/biome_cli/src/commands/daemon.rs
- crates/biome_cli/src/service/unix.rs
- crates/biome_dependency_graph/src/dependency_graph.rs
- crates/biome_lsp/src/handlers/text_document.rs
- crates/biome_lsp/src/server.rs
- crates/biome_lsp/src/server.tests.rs
- crates/biome_lsp/src/session.rs
- crates/biome_service/Cargo.toml
- crates/biome_service/src/lib.rs
- crates/biome_service/src/workspace.rs
- crates/biome_service/src/workspace/document.rs
- crates/biome_service/src/workspace/scanner.rs
- crates/biome_service/src/workspace/server.rs
- crates/biome_service/src/workspace/server.tests.rs
- crates/biome_service/src/workspace/watcher.rs
- crates/biome_service/src/workspace/watcher.tests.rs
- crates/biome_service/src/workspace_watcher.rs
This implements various improvements for making the watcher and the LSP play nicer together. Specifically:
* Made sure terminating the LSP proxy also terminates the daemon process (it hung on an pending channel loop).
* Made sure we always scan the project folder when registering it.
* Changed the channel mechanism for watcher updates to become "service data notifications". The LSP now also listens to this and updates diagnostics for all open documents when it receives a notification. This ensures that if you have multiple open documents, and make or break a cyclic dependency in one of them, they'll all update together.
Unfortunately it doesn't resolve my main issue with the LSP yet: Cyclic dependencies aren't detected until _after_ you've run the CLI with `--use-server` at least once. …
> feat(core): watcher + LSP improvements

- crates/biome_cli/src/commands/mod.rs
- crates/biome_lsp/src/server.rs
- crates/biome_lsp/src/server.tests.rs
- crates/biome_lsp/src/session.rs
- crates/biome_service/src/workspace.rs
- crates/biome_service/src/workspace.tests.rs
- crates/biome_service/src/workspace/server.rs
- crates/biome_service/src/workspace/server.tests.rs
- crates/biome_service/src/workspace/watcher.rs
Turns out the issue with the scanner in the LSP was just a footgun I ran into with Tokio: I was passing an `async` scan function to `tokio::spawn_blocking()`, which ended up doing... nothing, because nobody awaits the returned `Future`.
With that fixed, I immediately discovered that our LSP triggers 4 calls to the scanner because of some config updates it tries to process, so I implemented the functionality to not always rescan folders that are already being watched.
Tests are updated and should remain green. Manually tested too.
> fix(core): fix workspace scanner in LSP

- .changeset/dull-clocks-rescue.md
- crates/biome_js_analyze/src/lint/complexity/use_arrow_function.rs
- crates/biome_js_analyze/tests/specs/complexity/useArrowFunction/invalid.ts
- crates/biome_js_analyze/tests/specs/complexity/useArrowFunction/invalid.ts.snap
Closes #4967
In ECMAScript, the return value of an arrow expression that starts with `{` needs to be parenthesised to be a valid expression, even if the expression is not a `JsObjectExpression`. This pull request fixes the condition to parenthesise the expression or not.
Snapshot tests added.
> fix(lint): useArrowFunction should parenthesise the expr starting with `{`

- .changeset/add_new_option_javascriptjsxeverywhere.md
- crates/biome_cli/tests/snapshots/main_commands_check/check_help.snap
- crates/biome_cli/tests/snapshots/main_commands_ci/ci_help.snap
- crates/biome_configuration/src/javascript/mod.rs
- crates/biome_service/src/file_handlers/javascript.rs
- crates/biome_service/src/file_handlers/javascript.tests.rs
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
- packages/@biomejs/biome/configuration_schema.json
`.jsxEverywhere` should make an exception for `.ts` files to avoid conflicts with TS generics.
I've updated the original changeset.
Test added. Also manually tested.
> fix(parser): don't apply `jsxEverywhere` to `.ts` files

- .changeset/fancy-coins-cross.md
- crates/biome_js_analyze/src/lint/nursery/use_consistent_curly_braces.rs
- crates/biome_js_analyze/tests/specs/nursery/useConsistentCurlyBraces/valid.jsx
- crates/biome_js_analyze/tests/specs/nursery/useConsistentCurlyBraces/valid.jsx.snap
Fixes #4154
Update `useConsistentCurlyBraces` rule to ignore single spaces and newline characters in React components.
> fix(lint): allow single spaces in useConsistentCurlyBraces rule

- crates/biome_analyze/src/rule.rs
- crates/biome_configuration/src/analyzer/linter/mod.rs
- crates/biome_configuration/src/overrides.rs
- crates/biome_configuration/tests/invalid/domains.json
- crates/biome_service/src/settings.rs
- crates/biome_service/src/workspace_types.rs
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
- packages/@biomejs/biome/configuration_schema.json
`RuleDomain` and `RuleDomainValue` were missing in the generated `biome_wasm.d.ts` declaration file. The declaration file is generated from the JSON schema (from `schemars`), and it didn't support `additionalProperties` and `propertyNames`. I added their support to the build script to generate the missing types.
Plus, supported rule domains are now validated in editors that supports JSON schema (Draft 6 or later):
Once this is merged, the changes will be synced to `biomejs/website` repository. `tsc` on the website repository will be green after that.
> fix(wasm): add missing `RuleDomain` and `RuleDomainValue` types to the generated declaration

- Cargo.lock
- xtask/bench/Cargo.toml
- xtask/codegen/Cargo.toml
Update some dependencies to fix audited vulnerabilities:
```
❯ cargo audit
Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
Loaded 741 security advisories (from /Users/siketyan/.cargo/advisory-db)
Updating crates.io index
Scanning Cargo.lock for vulnerabilities (489 crate dependencies)
Crate:     ring
Version:   0.17.8
Title:     Some AES functions may panic when overflow checking is enabled.
Date:      2025-03-06
ID:        RUSTSEC-2025-0009
URL:       https://rustsec.org/advisories/RUSTSEC-2025-0009
Solution:  Upgrade to >=0.17.12
Dependency tree:
ring 0.17.8
├── rustls-webpki 0.102.8
│   └── rustls 0.23.23
│       └── ureq 3.0.8
│           ├── xtask_codegen 0.0.0
│           └── xtask_bench 0.0.0
└── rustls 0.23.23
Crate:     proc-macro-error
Version: …
```
> build(deps): update dependencies to fix cargo audit

- crates/biome_analyze/src/rule.rs
From https://github.com/biomejs/website/pull/1815#discussion_r1986060422
Removed deriving `Ord` and `PartialOrd`, added their impls to use alphabetical order.
I'll pull the synced changes to check the ordering is correct in biomejs/website#1815
> fix: use alphabetical order in Ord and PartialOrd impls on RuleDomain

- crates/biome_js_analyze/src/assist/source/organize_imports.rs
Import sorting is now its own action, so we need to copy the documentation we have in the website inside another page.
I removed the part of the CLI, which can't be applied anymore.
Proof read
> docs: copy docs of import sorting from website

- crates/biome_lsp/src/server.tests.rs
- crates/biome_lsp/src/session.rs
related: https://github.com/biomejs/biome/issues/5163 https://github.com/biomejs/biome/pull/5160
> fix: propagate plugin load error LSP

- crates/biome_cli/src/commands/daemon.rs
This also guarantees we don't wait for scanner jobs to finish, which could take a lot of time and/or consume a lot of memory otherwise.
> fix(core): force exit the daemon on shutdown

- crates/biome_cli/src/commands/mod.rs
- crates/biome_cli/src/execute/mod.rs
Adds the summary duration to the total amount of time. I'm not sure if this implementation is correct because, technically, there's some other code executed between scanning and traverse. Maybe we should start `Insta::now` way early and finish at the end of the traversal? 
Let me know what you think.
CI should pass
> fix: add scanning time to traverse time

- .changeset/cyan-beans-yawn.md
- crates/biome_js_formatter/src/utils/object_like.rs
- crates/biome_js_formatter/tests/specs/ts/object/objects.ts
- crates/biome_js_formatter/tests/specs/ts/object/objects.ts.snap
Closes #5342 
Follow-up of #5174 
The type annotation in the only function parameter should be in the `Hug` layout, and the object type should not create another group.
This is the follow-up fix of #5174, so I modified the changeset previously added.
Snapshot tests added.
> fix(formatter): hug the object type in the only function parameter

- crates/biome_diagnostics/src/display.rs
Make sure we check the `TERMINAL_EMULATOR` environment variable in addition to `TERM_PROGRAM`.
See: https://github.com/biomejs/biome/issues/5358#issuecomment-2726300551
I don't use IntelliJ myself, so it needs confirmation from someone who does, but based on the linked references, I'm pretty confident in this change :)
> fix(cli): check `TERMINAL_EMULATOR` variable

- crates/biome_analyze/src/lib.rs
- crates/biome_analyze/src/rule.rs
- crates/biome_css_analyze/tests/plugin/useLowercaseColors.grit.snap
- crates/biome_js_analyze/tests/plugin/preferObjectSpread.grit.snap
- crates/biome_js_analyze/tests/plugin/preferObjectSpreadSuppression.grit.snap
- crates/biome_plugin_loader/src/analyzer_grit_plugin.rs
- crates/biome_service/src/snapshots/biome_service__workspace__tests__plugins_are_loaded_and_used_during_analysis.snap
- crates/biome_service/src/snapshots/biome_service__workspace__tests__plugins_can_use_custom_severity.snap
- crates/biome_service/src/workspace.tests.rs
Adds the `severity` parameter to plugin function `register_diagnostic()`.
The default severity is now error.
Added test + updated snapshots.
> feat(core): allow plugins to control severity of diagnostics

- crates/biome_service/src/file_handlers/mod.rs
I tried the latest preview build on my private repository and observed slowdown from 3s to 24s. After profiling a run, I noticed that `ProjectLayout::get_node_manifest_for_path` is called for each rule, taking about 10 ms each.
Reading `package.json` was added for determining rule domains to apply automatically, but we don't need to read it for each rule. I changed `LintVisitor::new` to simply get the read manifest, and `AnalyzerVisitorBuilder::finish` to read the manifest only once.
I re-run Biome on the same repository after the changes, and it takes only 4s for entire run now.
Existing tests should pass. Plus, manually tested.
> perf: read package.json only once in a run

- packages/@biomejs/biome/README.ru.md
- packages/@biomejs/biome/README.uk.md
Added cross-links in the translations (apparently they got lost as two translations were released almost at the same time), as well as a translation for the "Gold Sponsors" section
> fix: fix of ru/uk readme translations

- crates/biome_cli/src/commands/mod.rs
- crates/biome_cli/src/commands/rage.rs
- crates/biome_configuration/src/lib.rs
- crates/biome_fs/src/fs.rs
- crates/biome_lsp/src/session.rs
- crates/biome_service/src/configuration.rs
This PR removes the detection of multiple configuration files.
While it is nice to have, it forces us to do multiple FS operations just to show a warning. Also, the current implementation was buggy while I tested it in a real-world project.
CI should pass
> chore: remove detection of multiple config files

- .changeset/thirty-deer-hope.md
- crates/biome_js_analyze/src/lint/style/use_export_type.rs
- crates/biome_js_analyze/tests/specs/style/useExportType/issue5382.ts
- crates/biome_js_analyze/tests/specs/style/useExportType/issue5382.ts.snap
Closes #5382 
Previously, useExportType only checked the type binding when the identifier has multiple bindings, so it detected the identifier as a false postivie. Checking `Binding::is_type_only` for every binding will fix the issue.
Snapshot tests added.
> fix(lint): handle const + type bindings in useExportType

- crates/biome_diagnostics/src/display.rs
This PR fixes two issues:
- it moves the `is_jetbrains` check further up, so the `at ...` is correctly printed regardless if the path is absolute or relative. This was a small regression of when we decided to pass relative paths, where stripped paths have a leading `/`, which creates a false positive in `Path::is_absolute`
- changes the `cfg` query to use `test` instead of `debug_assertions`, so we can see the result in the terminal when we run `cargo biome-cli-dev`
> [!IMPORTANT]
> The `at file.json` trick doesn't work for the new JetBrains emulator (beta)
I tested manually in VSCode and RustRover
> fix(diagnostics): correctly print emulator files

- crates/biome_js_analyze/src/lint/correctness/no_private_imports.rs
Slightly more nuanced docs for how private visibility is handled in `noPrivateImports`.
N/A
> chore: `noPrivateImports` doc tweak

- crates/biome_aria/src/roles.rs
- crates/biome_js_analyze/src/a11y.rs
- crates/biome_js_analyze/src/lib.rs
- crates/biome_js_analyze/src/lint/nursery/no_noninteractive_element_interactions.rs
- crates/biome_js_analyze/src/lint/nursery/no_static_element_interactions.rs
Several a11y lint rules currently define similar functions independently. 
This PR changes them to use a single consolidated implementation.
And  explicitly skip linting to custom components in `noStaticElementInteractions`.
> refactor(lint): a11y utils to reduce duplicate function definitions

- crates/biome_js_analyze/src/assist/source/use_sorted_attributes.rs
- crates/biome_js_analyze/tests/specs/source/useSortedAttributes/unsorted.jsx
- crates/biome_js_analyze/tests/specs/source/useSortedAttributes/unsorted.jsx.snap
The main goal of this PR is to change the sorting algorithm: we now use a naturl sort.
`useSortedAttributes` heavily use cloning.
I reduced the number of cloning and allocations. There is room for improvements, however this will require changing the code structure.
We now also check if the props are sorted before emitting a signal.
Also we now use unstable sort.
> refactor(assist/useSortedAttributes): natural sorting and avoid cloning

- Cargo.lock
- Cargo.toml
- crates/biome_js_analyze/Cargo.toml
- crates/biome_js_analyze/src/assist/source/use_sorted_keys.rs
- crates/biome_js_analyze/tests/specs/source/useSortedKeys/unsorted.js
- crates/biome_js_analyze/tests/specs/source/useSortedKeys/unsorted.js.snap
- crates/biome_json_analyze/Cargo.toml
- crates/biome_json_analyze/src/assist/source/use_sorted_keys.rs
Replace natord with our own implementation (the one used by the import sorter and other rules).
This allows removing our dependency over `natord`.
> refactor(assist/useSortedKeys): use our own natural order impl

- .github/workflows/preview.yml
It didn't build any wasm packages, but published to pkg.pr.new without any artifacts. I added a build-wasm job copied from the release.yml workflow.
N/A
> ci: build WASM packages before publishing them to pkg.pr.new

- crates/biome_glob/src/lib.rs
- crates/biome_js_analyze/src/assist/source/organize_imports/import_groups.rs
- crates/biome_js_analyze/tests/specs/source/organizeImports/custom-order-mixed-glob-groups.js
- crates/biome_js_analyze/tests/specs/source/organizeImports/custom-order-mixed-glob-groups.js.snap
- crates/biome_js_analyze/tests/specs/source/organizeImports/custom-order-mixed-glob-groups.options.json
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
- packages/@biomejs/biome/configuration_schema.json
This Pr adds the support for negated predefined groups and placing predefined groups in list.
This will simplify some configs such as https://github.com/biomejs/biome/issues/5435
I didn't change the documentation to avoid any confusion since the docs is diretcly published on `next.biomejs.dev`
> feat(assist/organizeImports): allow predefined groups in lists

- crates/biome_html_parser/src/syntax/mod.rs
- crates/biome_html_parser/src/syntax/parse_error.rs
- crates/biome_html_parser/tests/html_specs/error/template-langs/django/issue-5450.html
- crates/biome_html_parser/tests/html_specs/error/template-langs/django/issue-5450.html.snap
Closes #5450
Added a parser test.
> fix(parse/html): emit proper diagnostics when closing tag has extra literals

- crates/biome_configuration/src/analyzer/linter/rules.rs
- crates/biome_configuration/src/analyzer/mod.rs
- crates/biome_service/src/settings.tests.rs
- xtask/codegen/src/generate_configuration.rs
Fixed #5456 
Previously, merging a rule configuration into a rule group configuration was not supported.
Added a merge implementation as expanding the group and merge specific rules.
Test added.
> fix: allow overriding rule group by each rule

- .changeset/fancy-animals-kiss.md
- crates/biome_cli/src/execute/migrate.rs
- crates/biome_cli/src/execute/migrate/prettier.rs
- crates/biome_cli/tests/commands/migrate_prettier.rs
- crates/biome_cli/tests/snapshots/main_commands_format/line_width_parse_errors_overflow.snap
- crates/biome_cli/tests/snapshots/main_commands_migrate_prettier/prettier_migrate_override_with_bad_print_width.snap
- crates/biome_cli/tests/snapshots/main_commands_migrate_prettier/prettier_migrate_with_bad_top_level_print_width.snap
- crates/biome_formatter/src/lib.rs
Before:
```
$ yarn biome migrate prettier --verbose
migrate ━━━
✖ Migration has encountered an error: The line width should be between 1 and 320
```
After:
```
$ ../biome/target/debug/biome migrate prettier
migrate ━━━
✖ Migration has encountered an error: override element matching ["red/ac/ted.ts"]: The line width should be between 1 and 320, got 666
```
Snapshot tests showing the new errors added.
> fix(migrate): improve error messages when parsing Prettier configuration

- Cargo.lock
- crates/biome_analyze/src/lib.rs
- crates/biome_analyze/src/rule.rs
- crates/biome_plugin_loader/src/analyzer_grit_plugin.rs
- crates/biome_service/Cargo.toml
- crates/biome_service/src/snapshots/biome_service__workspace__tests__plugins_may_use_invalid_span.snap
- crates/biome_service/src/workspace.tests.rs
Plugins have to provide a `span` argument when reporting diagnostics. Naturally, they can mistakes when doing so.
Previously, incorrect spans would crash the process:
```
/home/arendjr/Projects/biome-plugin/src/routes/index.tsx internalError/panic  INTERNAL  ━━━━━━━━━━━━
✖ processing panicked: missing span
⚠ This diagnostic was derived from an internal Biome error. Potential bug, please report it if necessary.
```
With this PR, we gracefully handle such cases:
```
/src/routes/index.tsx plugin ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
✖ Don't use visible task pls
/src/routes/index.tsx plugin ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
ℹ Plugin qwik-plugin reported one or more diagnostics, but it didn't specify a valid span. …
```
> fix(plugins): handle invalid spans

- .github/workflows/pull_request_node.yml
Use the `*-dev` builds in the Node.js pull request check. The main difference is that release builds run `wasm-opt`, which is responsible for the majority of the time of these builds, but regular PRs of ours don't influence that process anyway, so it feels like a waste of time to run on every PR. It does mean that if `wasm-opt` breaks something, we'll discover it later, possibly when creating a prerelease.
I expect this saves more than 5 minutes of CI time per run.
> chore: use dev builds in Node.js pull request check

- rustfmt.toml
Biome switched to 2024 style edition in 9b2d5db56ebe3abc1306707 but did not set the style_edition in rustfmt.toml so if your editor runs rustfmt it now formats it with 2015 (the default) instead of 2024.
My editor runs `rustfmt` which defaults to 2015
This configures rustfmt.toml to be in line with the formatting xtask
```
rustfmt --config newline_style=Unix --config style_edition=2024
```
> chore: set 2024 as default Rustfmt style edition

- .changeset/olive-trains-buy.md
- crates/biome_js_analyze/src/lint/correctness/use_import_extensions.rs
- crates/biome_js_analyze/tests/specs/correctness/useImportExtensions/invalid.ts
- crates/biome_js_analyze/tests/specs/correctness/useImportExtensions/invalid.ts.snap
- crates/biome_js_analyze/tests/specs/correctness/useImportExtensions/invalidWithForcedJsExtensions.ts
- crates/biome_js_analyze/tests/specs/correctness/useImportExtensions/invalidWithForcedJsExtensions.ts.snap
- crates/biome_js_analyze/tests/specs/correctness/useImportExtensions/sub/component.svg.svelte.ts
- crates/biome_js_analyze/tests/specs/correctness/useImportExtensions/sub/component.svg.svelte.ts.snap
- crates/biome_js_analyze/tests/specs/correctness/useImportExtensions/sub/styles.css.ts
- crates/biome_js_analyze/tests/specs/correctness/useImportExtensions/sub/styles.css.ts.snap
- crates/biome_js_analyze/tests/specs/correctness/useImportExtensions/valid.js
- crates/biome_js_analyze/tests/specs/correctness/useImportExtensions/valid.js.snap
In JS ecosystem it is popular to have files with sub extensions/file steam.
[CSS modules](https://github.com/css-modules/css-modules) `styles.css.ts`
[Svelte](https://svelte.dev/docs/svelte/svelte-js-files) `rune.svelte.ts`
And more. Currently editors auto import without .ts extension so it is easy to miss that you are not using actual file extension.
This MR fixes it. 
I originally planned to only check specific extensions, however I decided against it:
- Rule would miss valid cases and for not much perf gain.
- Even `filename.ts.ts` is not [that rare](https://github.com/search?q=path%3A**%2F*.ts.ts&type=code).
- Some people might use naming convention which uses dots instead of dashes and so on.
Added snapshots
> feat(linter): make useImportExtensions check imports with sub extensions

- crates/biome_js_analyze/src/assist/source/organize_imports.rs
- crates/biome_js_analyze/tests/specs/source/organizeImports/suppressed-unsorted.js
- crates/biome_js_analyze/tests/specs/source/organizeImports/suppressed-unsorted.js.snap
- crates/biome_lsp/src/server.tests.rs
This PR adds the ability of suppressing organizeImports.
The suppression comment has to be placed on the first import/export of the file.
> fix(assist/organizeImports): allow suppression comments

- packages/@biomejs/js-api/README.md
Included how to use Biome configurations in the js-api package.
The README made absolutely no mention of how to use Biome configurations with the js-api package, which I guess normally wouldn't be a problem *if* it supported reading the biome.json file by default. Was wondering why it wasn't applying, and had to look through the source & abuse Intellisense to figure out that this was even possible in js-api.
https://discord.com/channels/1132231889290285117/1132231889911029825/1355987574786752683 -> me coping in the Discord server before I figured it out
N/A (documentation update)
> docs: include how to use configuration in the js-api README

- crates/biome_migrate/src/analyzers/includes.rs
- crates/biome_migrate/tests/specs/migrations/includes/invalid_globs.json.snap
Fix https://github.com/biomejs/biome/issues/5442
We now escape squared braces whe nconverting `include`/`ignore` into `includes`.
> refactor(migrate): escape squared braces

- crates/biome_service/src/lib.rs
Add some entries to the scanner's ignore entries, based on reports in Discord.
We'll have to hear from users on this one, I'm afraid.
> chore: add ignore entries to scanner

- packages/@biomejs/biome/README.md
Update our sponsors section.
I updated the width to 500px, as that's the size of the asset. I notice that both Gold and Silver have "medium-sized" images according to our OpenCollective, while Platinum has a "large" one. I guess they already had a large one, since it was already bigger than the silvers sponsors :)
N/A
> chore: add Platinum sponsor

- .changeset/lucky-boats-rush.md
- crates/biome_cli/src/diagnostics.rs
- crates/biome_cli/src/execute/mod.rs
- crates/biome_cli/src/execute/std_in.rs
- crates/biome_cli/src/lib.rs
- crates/biome_cli/tests/commands/format.rs
- crates/biome_cli/tests/snapshots/main_commands_format/format_stdin_errors_with_no_file_extension.snap
This PR fixes two bugs:
1. The stdin mode didn't check if `--stdin-file-path` contains an extension. The extension is required because it infers the document type; without it, Biome can't handle the file.
2. This is more of an internal bug, but I believe a user hit a particular use case. In stdin mode, the user needs to pass an arbitrary file so we can infer the extension. The thing is, if the user is running the Daemon, chances are that the Workspace already has a file with the same name. To avoid clashes, we use an internal, arbitrary file name. When using this arbitrary file name, we close it too at the end of the operation. This was affecting the JSON reporter too.
Added a new test for `1.`. CI should stay green
> fix(cli): emit error when no extension exist

- .changeset/gorgeous-cooks-pump.md
- crates/biome_js_analyze/src/lint/a11y/no_noninteractive_element_to_interactive_role.rs
- crates/biome_js_analyze/tests/specs/a11y/noNoninteractiveElementToInteractiveRole/valid.jsx
- crates/biome_js_analyze/tests/specs/a11y/noNoninteractiveElementToInteractiveRole/valid.jsx.snap
I elected for this simple fix because it's unclear what the more generalized heuristic would be here. In lieu of that, I've documented the precise reason for the exception.
fixes #5446
Added to the snapshot test.
> fix(lint/noNoninteractiveElementToInteractiveRole): fix mistakenly flagging `<li role="treeitem">`

- .changeset/use-regex-literals-escaping-bug.md
- crates/biome_js_analyze/src/lint/complexity/use_regex_literals.rs
- crates/biome_js_analyze/tests/specs/complexity/useRegexLiterals/invalid.js
- crates/biome_js_analyze/tests/specs/complexity/useRegexLiterals/invalid.js.snap
Fix https://github.com/biomejs/biome/issues/5487
I also took the opportunity of improving the implementation.
> fix(lint/useRegexLiterals): correctly handle escaped anti-slashes

- .changeset/no-paraemter-assign-unparenthesized-arrow-function.md
- crates/biome_js_analyze/src/lint/style/no_parameter_assign.rs
- crates/biome_js_analyze/tests/specs/style/noParameterAssign/invalid.jsonc
- crates/biome_js_analyze/tests/specs/style/noParameterAssign/invalid.jsonc.snap
Fix https://github.com/biomejs/biome/issues/5409
> fix(lint/noParameterAssign): handle unparenthesized arrow functions

- .changeset/no-type-only-import-attributes-ignore-commonjs-package.md
- crates/biome_js_analyze/src/syntax/correctness/no_type_only_import_attributes.rs
- crates/biome_js_analyze/tests/specs/correctness/noTypeOnlyImportAttributes/valid_cjs.ts
- crates/biome_js_analyze/tests/specs/correctness/noTypeOnlyImportAttributes/valid_cjs.ts.snap
Fix https://github.com/biomejs/biome/issues/5564
We now check the `type` field in `package.json`.
Also, I added a test to only check TypeScript files. 
I added a test
> fix(syntax/noTypeOnlyImportAttributes): ignore all commonjs files

- Cargo.lock
- crates/biome_js_analyze/src/lint/correctness/no_private_imports.rs
- crates/biome_js_analyze/src/lint/correctness/use_import_extensions.rs
- crates/biome_js_analyze/src/lint/nursery/no_import_cycles.rs
- crates/biome_js_analyze/src/lint/nursery/no_unresolved_imports.rs
- crates/biome_js_analyze/src/services/module_graph.rs
- crates/biome_js_type_info/src/inference.rs
- crates/biome_js_type_info/src/type_info.rs
- crates/biome_module_graph/Cargo.toml
- crates/biome_module_graph/src/js_module_visitor.rs
- crates/biome_module_graph/src/js_semantic_model.rs
- crates/biome_module_graph/src/jsdoc_comment.rs
- crates/biome_module_graph/src/lib.rs
- crates/biome_module_graph/src/module_graph.rs
- crates/biome_module_graph/src/module_graph.tests.rs
- crates/biome_module_graph/src/module_info.rs
- crates/biome_module_graph/src/snapshots/biome_module_graph__module_graph__tests__resolve_exports.snap
Fixes #5312.
This adds a light, and as of yet incomplete, version of the semantic model to the scanner. The goal isn't yet to do deep semantic analysis inside the scanned modules, but simply to resolve exported symbols when their declaration is in a different position than the export statement itself.
This makes sure that we can resolve both types and JSDoc comments more accurately through the module graph, and also resolves one of the limitations of `noPrivateImports` that we had in the beta.
JSDoc comments also have a dedicated type. The type definitions for type aliases has been refined as well.
Tests added and snapshots updated.
> feat(core): add light version of the semantic model to scanner

- crates/biome_js_analyze/src/assist/source/organize_imports.rs
- crates/biome_js_analyze/src/assist/source/organize_imports/import_key.rs
- crates/biome_js_analyze/src/assist/source/organize_imports/specifiers_attributes.rs
- crates/biome_js_analyze/tests/specs/source/organizeImports/mergeable_export.ts
- crates/biome_js_analyze/tests/specs/source/organizeImports/mergeable_export.ts.snap
- crates/biome_js_analyze/tests/specs/source/organizeImports/mergeable_imports.ts
- crates/biome_js_analyze/tests/specs/source/organizeImports/mergeable_imports.ts.snap
- crates/biome_js_analyze/tests/specs/source/organizeImports/mergeable_unsorted_imports.ts
- crates/biome_js_analyze/tests/specs/source/organizeImports/mergeable_unsorted_imports.ts.snap
- crates/biome_js_analyze/tests/specs/source/organizeImports/unsorted-same-source.ts.snap
This PR introduces the merge of imports and exports.
Here is an example:
```diff
- import type { T4, T2 } from "mod";
- import type { T3, T1 } from "mod";
+ import type { T1, T2, T3, T4 } from "mod";
- import { A, D } from "mod";
- import { B, C } from "mod";
+ import { A, B, C, D } from "mod";
```
We merge the following statements in order:
1. A default import and a namespace import are merged into a combined import
```diff
- import * as ns from "mod";
- import D from "mod";
+ import D, * as ns from "mod";
import { A, B } from "mod";
```
3. A default import and a named import are merged into a combined import
```diff
- import D from "mod";
- import { A, B } from "mod";
+ import D, { A, B } from "mod";
```
4. Two named imports/exports are merged into a single named import/export
```diff
- …
```
> feat(assist/organizeImports): merge imports and exports

- xtask/codegen/src/generate_syntax_kinds.rs
Some languages, such as YAML, do not, have any special keywords. The current implementation is unable to handle this, and instead will generate the `from_keyword` function:
```rust
let kw = match ident {
_ => return None,
};
Some(kw)
```
Which led to following errors
```rust
error: unreachable expression
--> crates/biome_yaml_syntax/src/generated/kind.rs:123:9
|
120 |           let kw = match ident {
|  __________________-
121 | |             _ => return None,
122 | |         };
| |_________- any code following this `match` expression is unreachable, as all arms diverge
123 |           Some(kw)
|           ^^^^^^^^ unreachable expression
|
= note: `-D unreachable-code` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(unreachable_code)]`
error: unused variable: `kw` …
```
> fix(xtask/codegen): handle languages with no keywords

- crates/biome_css_analyze/src/lint/a11y/use_generic_font_names.rs
- crates/biome_css_analyze/src/lint/correctness/no_invalid_direction_in_linear_gradient.rs
- crates/biome_css_analyze/src/lint/correctness/no_unknown_property.rs
- crates/biome_css_analyze/src/lint/correctness/no_unmatchable_anb_selector.rs
- crates/biome_css_analyze/src/lint/nursery/no_duplicate_properties.rs
- crates/biome_css_analyze/src/lint/nursery/no_missing_var_function.rs
- crates/biome_css_analyze/src/lint/nursery/no_unknown_pseudo_class.rs
- crates/biome_css_analyze/src/lint/nursery/no_unknown_pseudo_element.rs
- crates/biome_css_analyze/src/lint/suspicious/no_duplicate_at_import_rules.rs
- crates/biome_css_analyze/src/lint/suspicious/no_duplicate_font_names.rs
- crates/biome_css_analyze/src/lint/suspicious/no_duplicate_selectors_keyframe_block.rs
- crates/biome_css_analyze/src/lint/suspicious/no_shorthand_property_overrides.rs
- crates/biome_css_analyze/tests/specs/nursery/noUnknownPseudoClass/invalid.css.snap
- crates/biome_css_formatter/src/utils/component_value_list.rs
- crates/biome_js_analyze/src/lint/a11y/no_aria_hidden_on_focusable.rs
- crates/biome_js_analyze/src/lint/a11y/use_focusable_interactive.rs
- crates/biome_js_analyze/src/lint/complexity/no_useless_string_concat.rs
- crates/biome_js_analyze/src/lint/complexity/use_optional_chain.rs
- crates/biome_js_analyze/src/lint/correctness/no_flat_map_identity.rs
- crates/biome_js_analyze/src/lint/correctness/use_jsx_key_in_iterable.rs
- crates/biome_js_analyze/src/lint/nursery/no_process_env.rs
- crates/biome_js_analyze/src/lint/nursery/use_at_index.rs
- crates/biome_js_analyze/src/lint/style/no_yoda_expression.rs
- crates/biome_js_analyze/src/lint/style/use_number_namespace.rs
- crates/biome_js_analyze/src/lint/suspicious/no_duplicate_jsx_props.rs
- crates/biome_js_analyze/src/lint/suspicious/no_redeclare.rs
- crates/biome_rowan/src/ast/mod.rs
- crates/biome_rowan/src/text.rs
Took a stab at removing the use to `to_trimmed_string` from some rules, because that method **allocates** a string.
I created a small utility to avoid using `syntax().text_trimmed().into_text()`.
I managed to remove it from the CSS rules, and few of the JS rules, but there are other rules where I didn't check, and some other places where it's needed.
CI should stay green. One snapshot was updated because it was linting bogus nodes, but usually we don't force the handling of them, so it's fine not to handle that case.
> perf(lint): remove allocation of strings

- .changeset/fix-mjs-in-commonjs-package.md
- crates/biome_cli/tests/commands/lint.rs
- crates/biome_cli/tests/snapshots/main_commands_lint/should_lint_module_in_commonjs_package.snap
- crates/biome_service/src/workspace/server.rs
Fixes #5605.
We made the mistake of looking at the extension of the `DocumentFileSource`, whose extension doesn't necessarily match the real extension of the path it is derived from.
> fix(core): handle `.mjs` extension in CommonJS packages

- crates/biome_configuration/src/diagnostics.rs
- crates/biome_deserialize/src/lib.rs
- crates/biome_diagnostics/src/advice.rs
- crates/biome_diagnostics_macros/src/generate.rs
- crates/biome_diagnostics_macros/src/parse.rs
- crates/biome_fs/src/fs.rs
- crates/biome_service/src/configuration.rs
- crates/biome_service/src/settings.rs
Implements a small but important part for the upcoming monorepo support: non-root configuration files (those with a `root: false` field) are automatically skipped in the auto-search for finding a Biome configuration file.
If users explicitly provide a path to a non-root configuration file, we'll error with a diagnostic. In theory we could do an auto-search from the non-root file, but I'm not sure if it's desired, and if it is we can implement it later (it looks a bit tricky).
Tests added.
> feat(core): skip non-root configuration files

- .changeset/editorconfig-charclass-parsing.md
- Cargo.lock
- Cargo.toml
- crates/biome_cli/tests/cases/editorconfig.rs
- crates/biome_cli/tests/snapshots/main_cases_editorconfig/end_of_line_parse_error.snap
- crates/biome_cli/tests/snapshots/main_cases_editorconfig/indent_size_parse_error.snap
- crates/biome_cli/tests/snapshots/main_cases_editorconfig/non_closed_section.snap
- crates/biome_cli/tests/snapshots/main_cases_editorconfig/root_parse_error.snap
- crates/biome_configuration/Cargo.toml
- crates/biome_configuration/src/diagnostics.rs
- crates/biome_configuration/src/editorconfig.rs
- crates/biome_diagnostics/Cargo.toml
- crates/biome_diagnostics/src/adapters.rs
- crates/biome_diagnostics/src/lib.rs
- crates/biome_diagnostics/src/location.rs
- crates/biome_service/src/configuration.rs
Fix https://github.com/biomejs/biome/issues/5410
I finally decided to implement our own parser because the format used by EditorConfig is really simple.
> fix(editorconfig): parse char classes in globs

- crates/biome_analyze/src/lib.rs
- crates/biome_js_analyze/src/lint/complexity/use_arrow_function.rs
- crates/biome_js_analyze/src/suppressions.tests.rs
Closes https://github.com/biomejs/biome/issues/5562
The regression was introduced by https://github.com/biomejs/biome/pull/4714
The real issue wasn't how we suppressions were discovered, but by the fact that the diagnostic was emitting a text range that was spanning over multiple lines, and this was tripping the suppression engine.
Usually, text ranges emitted by our rules should be in one line, and that's what `text_range` is for. I implemented the function for the rule that was at fault, and now everything works again :) 
Added new tests. No changesets needed, since it's a fix of a fix, so the original changeset is still valid.
> fix(analyzer): use binary search to find diagnostics

- .changeset/plenty-foxes-give.md
- crates/biome_js_analyze/src/lint/suspicious/no_console.rs
- crates/biome_js_analyze/tests/specs/suspicious/noConsole/allowlist.js
- crates/biome_js_analyze/tests/specs/suspicious/noConsole/allowlist.js.snap
- crates/biome_js_analyze/tests/specs/suspicious/noConsole/invalid.js
- crates/biome_js_analyze/tests/specs/suspicious/noConsole/invalid.js.snap
- crates/biome_js_analyze/tests/specs/suspicious/noConsole/issue_5053.js.snap
- crates/biome_js_analyze/tests/specs/suspicious/noConsole/issue_5620.js
- crates/biome_js_analyze/tests/specs/suspicious/noConsole/issue_5620.js.snap
- crates/biome_js_analyze/tests/specs/suspicious/noConsole/valid.js
- crates/biome_js_analyze/tests/specs/suspicious/noConsole/valid.js.snap
Fixes #5620.
Handles all `console.xxx` member access cases, not only calls.
Changed text range in diagnostics (a) to bring in accordance with `eslint` (b) to reflect this change.
Tests are updated.
> fix(lint): `noConsole` rule now correctly handles indirect `console.log` calls and references

- crates/biome_deserialize_macros/src/deserializable_derive.rs
- crates/biome_js_analyze/src/assist/source/organize_imports/import_groups.rs
- crates/biome_js_analyze/src/assist/source/organize_imports/import_key.rs
- crates/biome_js_analyze/tests/specs/source/organizeImports/type-first-groups.options.json
- crates/biome_js_analyze/tests/specs/source/organizeImports/type-first-groups.ts
- crates/biome_js_analyze/tests/specs/source/organizeImports/type-first-groups.ts.snap
- crates/biome_js_analyze/tests/specs/source/organizeImports/type-last-groups.options.json
- crates/biome_js_analyze/tests/specs/source/organizeImports/type-last-groups.ts
- crates/biome_js_analyze/tests/specs/source/organizeImports/type-last-groups.ts.snap
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
- packages/@biomejs/biome/configuration_schema.json
Following user and maintainer feedbacks, this PR provides an alternative to the `typePlacement` option I introduced in https://github.com/biomejs/biome/pull/5582
Note that the PR doesn't remove `typePlacement`.
I left the removal to another PR.
Instead of introducing a new option to separate types, this PR introduces general import matchers.
This provides more flexibility to the users and improves extensibility to add more matching behaviors on imports/exports in the future if required.
For example the following config allows placing types first:
```json
{
"options": {
"groups": [
{ "type": true },
]
}
}
```
This one places types last:
```json
{
"options": {
"groups": [
{ "type": false },
]
}
}
```
Here is a more complex example:
```json
{
"options": {
"groups": [
{ "type": true, …
```
> feat(organizeImports): add import matchers

- Cargo.lock
- Cargo.toml
- crates/biome_js_analyze/src/lint/nursery/no_floating_promises.rs
- crates/biome_js_type_info/Cargo.toml
- crates/biome_js_type_info/src/lib.rs
- crates/biome_js_type_info/src/local_inference.rs
- crates/biome_js_type_info/src/resolver.rs
- crates/biome_js_type_info/src/type_info.rs
- crates/biome_js_type_info_macros/Cargo.toml
- crates/biome_js_type_info_macros/src/lib.rs
- crates/biome_js_type_info_macros/src/resolvable_derive.rs
- crates/biome_module_graph/src/js_module_info.rs
- crates/biome_module_graph/src/js_module_info/binding.rs
- crates/biome_module_graph/src/js_module_info/collector.rs
- crates/biome_module_graph/src/js_module_info/type_resolver.rs
- crates/biome_module_graph/src/module_graph.rs
- crates/biome_module_graph/src/snapshots/biome_module_graph__module_graph__tests__export_default_function_declaration.snap
- crates/biome_module_graph/src/snapshots/biome_module_graph__module_graph__tests__export_referenced_function.snap
- crates/biome_module_graph/src/snapshots/biome_module_graph__module_graph__tests__resolve_export_types.snap
- crates/biome_module_graph/src/snapshots/biome_module_graph__module_graph__tests__resolve_exports.snap
Another milestone towards implementation type inference: Indexed modules now have their types resolved before being added to the module graph.
Take the following code snippet:
```ts
class DeepThought {
/* class members */
}
export const superComputer = new DeepThought();
```
With this change, we can now successfully determine the type of `superComputer`, even though the `DeepThought` class is never being exported.
In order to accomplish this, I've introduced a `TypeResolver` trait and a `Resolvable` trait, with the latter also having a matching derive macro. The `TypeResolver` trait only has a single implementation for now, but I anticipate to be able to reuse the same trait when I implement full inference across modules.
Snapshots updated. I had already prepared a test for this …
> feat(core): implement "thin" type resolution

- Cargo.lock
- crates/biome_js_type_info/Cargo.toml
- crates/biome_js_type_info/src/type_info.rs
- crates/biome_js_type_info/src/type_info.tests.rs
Reduces another crate dependency, and allows us to add a message directly to the failing assertions.
Test added.
> chore: use test for type size verification

- .github/renovate.json
We don't want to update the engines (especially Node.js) to the latest. I added a package rule in renovate.json to disable updating dependencies in the `engines` section.
N/A
> chore: disable bumping engines on Renovate

- Cargo.lock
- Cargo.toml
- crates/biome_module_graph/src/resolver_cache.rs
`oxc_resolver` removed an API, and pushed the change as a minor by mistake.
To avoid possible issues in the future, I pinned the library. Another reason why I pinned is because the sync job of the website repository is failing, because cargo is pulling the latest version. 
Re: https://github.com/oxc-project/oxc-resolver/issues/453
CI should pass
> chore: update `oxc_resolver`

- xtask/bench/src/lib.rs
During benchmarking, we catch possible parse diagnostics, but we don't push the file name and the source, which means that diagnostics are basically useless 🤣 
From the CI:
```
parse ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
× expected `,` but instead found `zoom`
i Remove zoom
parse ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
× Unexpected value or character.
i Expected one of:
```
CI should pass should correct diagnostics
> ci(benchmarks): add code and file to diagnostics

- crates/biome_js_analyze/src/assist/source/organize_imports.rs
- crates/biome_js_analyze/src/assist/source/organize_imports/specifiers_attributes.rs
- crates/biome_js_analyze/tests/specs/source/organizeImports/issue-5710.js
- crates/biome_js_analyze/tests/specs/source/organizeImports/issue-5710.js.snap
Fixes #5710 
The `organizeImports` assist assumes the import is unsorted even if there are any bogus nodes. This causes an infinite loop when Biome apply code actions in multipass. Assuming the import is already sorted if any bogus nodes there so we no longer get stuck from the loop.
Added a snapshot test to ensure any diagnostics won't be emitted for the bogus code.
> fix(assist): skip sorting specifiers if it contains any bogus nodes

- crates/biome_configuration/src/analyzer/linter/rules.rs
- crates/biome_js_analyze/src/lint/nursery/use_consistent_object_definition.rs
- crates/biome_js_analyze/tests/specs/nursery/useConsistentObjectDefinition/invalidExplicit.js.snap
- crates/biome_js_analyze/tests/specs/nursery/useConsistentObjectDefinition/invalidShorthand.js.snap
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
- packages/@biomejs/biome/configuration_schema.json
Closes #5686 
`useConsistentObjectDefinition` now have a code action to auto-fix the object definition to shorthand or explicit syntax.
Test snapshots are updated.
> feat(lint): implement code action for useConsistentObjectDefinition

- crates/biome_js_analyze/tests/specs/nursery/noFloatingPromises/invalid.ts
- crates/biome_js_analyze/tests/specs/nursery/noFloatingPromises/invalid.ts.snap
- crates/biome_js_type_info/snapshots/infer_type_of_array_element.snap
- crates/biome_js_type_info/snapshots/infer_type_of_destructured_array_element.snap
- crates/biome_js_type_info/src/flattening.rs
- crates/biome_js_type_info/src/format_type_info.rs
- crates/biome_js_type_info/src/local_inference.rs
- crates/biome_js_type_info/src/resolver.rs
- crates/biome_js_type_info/src/type_info.rs
- crates/biome_js_type_info/tests/flattening.rs
- crates/biome_js_type_info/tests/snapshots/infer_flattened_type_of_destructured_array_element.snap
- crates/biome_js_type_info/tests/snapshots/infer_type_of_array.snap
- crates/biome_js_type_info/tests/snapshots/infer_type_of_array_element.snap
- crates/biome_js_type_info/tests/snapshots/infer_type_of_async_function.snap
- crates/biome_js_type_info/tests/snapshots/infer_type_of_destructured_array_element.snap
- crates/biome_js_type_info/tests/snapshots/infer_type_of_function_with_destructured_arguments.snap
- crates/biome_js_type_info/tests/snapshots/infer_type_of_promise_returning_function.snap
- crates/biome_js_type_info/tests/type_info.rs
- crates/biome_js_type_info/tests/utils/mod.rs
- crates/biome_module_graph/src/format_module_graph.rs
- crates/biome_module_graph/src/js_module_info/collector.rs
- crates/biome_module_graph/src/js_module_info/global_scope_resolver.rs
- crates/biome_module_graph/tests/snapshots/test_resolve_exports.snap
- crates/biome_module_graph/tests/spec_test.rs
My last PR left one regression in `noFloatingPromises`: The inability for our inference to track types across destructured properties. This is now resolved.
Test case updated, unit tests added.
> feat(core): implement type inference for destructuring

- crates/biome_js_type_info/src/format_type_info.rs
- crates/biome_js_type_info/src/lib.rs
- crates/biome_module_graph/src/format_module_graph.rs
- crates/biome_module_graph/src/js_module_info.rs
- crates/biome_module_graph/src/js_module_info/collector.rs
- crates/biome_module_graph/tests/snap/mod.rs
- crates/biome_module_graph/tests/snapshots/test_export_default_function_declaration.snap
- crates/biome_module_graph/tests/snapshots/test_export_referenced_function.snap
- crates/biome_module_graph/tests/snapshots/test_resolve_export_types.snap
- crates/biome_module_graph/tests/snapshots/test_resolve_exports.snap
It reduces the duplication of code between `biome_module_graph` and `biome_js_type_info`.
Adds formatting of `ObjectLiteral`
Updated snapshots
> chore: reduce duplication and add formating of object literals

- .github/workflows/beta.yml
- .github/workflows/preview.yml
- .github/workflows/release.yml
- .github/workflows/release_cli.yml
Fixes #5732.
Linux preview builds should work again.
> chore: update preview runners

- .changeset/use-regex-literals-5693.md
- crates/biome_js_analyze/src/lint/complexity/use_regex_literals.rs
- crates/biome_js_analyze/tests/specs/complexity/useRegexLiterals/invalid.js
- crates/biome_js_analyze/tests/specs/complexity/useRegexLiterals/invalid.js.snap
- crates/biome_js_analyze/tests/specs/complexity/useRegexLiterals/invalid.jsonc.snap
Fix https://github.com/biomejs/biome/issues/5693#issuecomment-2816096167
I took the opportunity of reviewing the entire process of escape/unescape.
I fixed many edge cases including:
- Don't unescape escaped characters in raw strings.
- Handle String literals split on several lines.
- Handle backspace escape (it is valid in strings and invalid in regexes)
I added new tests.
> fix(lint/useRegexLiterals): handle useless escapes

- crates/biome_cli/src/execute/migrate/eslint_any_rule_to_biome.rs
- crates/biome_configuration/src/analyzer/linter/rules.rs
- crates/biome_js_analyze/src/lint/nursery/use_explicit_type.rs
- crates/biome_js_analyze/tests/specs/nursery/useExplicitType/invalid.ts.snap
- crates/biome_js_analyze/tests/specs/nursery/useExplicitType/invalidArguments.ts
- crates/biome_js_analyze/tests/specs/nursery/useExplicitType/invalidArguments.ts.snap
- crates/biome_js_analyze/tests/specs/nursery/useExplicitType/invalidDeclarationStatements.ts.snap
- crates/biome_js_analyze/tests/specs/nursery/useExplicitType/namespace.ts.snap
- crates/biome_js_analyze/tests/specs/nursery/useExplicitType/valid.ts
- crates/biome_js_analyze/tests/specs/nursery/useExplicitType/valid.ts.snap
- crates/biome_js_analyze/tests/specs/nursery/useExplicitType/validInferrable.ts
- crates/biome_js_analyze/tests/specs/nursery/useExplicitType/validInferrable.ts.snap
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
- packages/@biomejs/biome/configuration_schema.json
Part of https://github.com/biomejs/biome/issues/2017
With this PR, now the function cover this rule: https://typescript-eslint.io/rules/explicit-module-boundary-types/#examples, in particular the arguments of the functions.
Since the rule is taking a different turn compared to the original design, I took the opportunity to revisit the messages and the advice. 
I will make a follow-up PR to revisit the documentation, because it talks about function return types.
Some cases that were valid, aren't valid anymore, so I removed them. I added
> feat(useExplicitType): cover function parameters

- crates/biome_js_analyze/tests/spec_tests.rs
Replaced the `TESTS_WITH_MODULE_GRAPH` constant with a registry visitor to check the rule is in the project domain and needs a module graph to test it. We don't need to manually enable it for a rule anymore.
> test(lint): auto enable module graph for rules in the project domain

- crates/biome_js_analyze/src/lint/nursery/no_process_global.rs
- crates/biome_js_analyze/tests/specs/nursery/noProcessGlobal/invalid.js.snap
- crates/biome_js_analyze/tests/specs/nursery/noProcessGlobal/invalid_with_import.js.snap
This PR fixes #5778 
Additionally, it fixes a typo in the name of the `create_porcess_import` function.
Automated tests pass
> fix(lint): use correct `node:process` import

- .changeset/major-apes-shout.md
- crates/biome_js_analyze/src/lint/nursery/use_sorted_classes.rs
- crates/biome_js_analyze/tests/specs/nursery/useSortedClasses/issue_4855.jsx.snap
- crates/biome_js_analyze/tests/specs/nursery/useSortedClasses/issue_5601.jsx
- crates/biome_js_analyze/tests/specs/nursery/useSortedClasses/issue_5601.jsx.snap
- This PR fixes This PR fixes https://github.com/biomejs/biome/issues/5601
- The linter now respects the preferred JSX quote style and safely converts conflicting inner quotes in class attributes, preventing syntax errors when sorting utility classes.
- Added snapshot test
> fix(lint): respect preferred JSX quote style and escape conflicting inner quotes in class attributes

- crates/biome_module_graph/src/jsdoc_comment.rs
Fixes #5785: JSDoc comments can't be empty or even have a negative length.
Tests added.
> fix(core): fix incorrect JSDoc detection

- crates/biome_js_analyze/tests/specs/nursery/noFloatingPromises/invalid.ts
- crates/biome_js_analyze/tests/specs/nursery/noFloatingPromises/invalid.ts.snap
- crates/biome_js_analyze/tests/specs/nursery/noFloatingPromises/promisedResult.ts
- crates/biome_js_analyze/tests/specs/nursery/noFloatingPromises/promisedResult.ts.snap
- crates/biome_js_analyze/tests/specs/nursery/noFloatingPromises/returnPromiseResult.ts
- crates/biome_js_analyze/tests/specs/nursery/noFloatingPromises/returnPromiseResult.ts.snap
- crates/biome_js_type_info/src/format_type_info.rs
- crates/biome_js_type_info/tests/snapshots/infer_type_of_function_with_destructured_arguments.snap
- crates/biome_module_graph/tests/snapshots/test_resolve_export_type_referencing_imported_type.snap
- crates/biome_module_graph/tests/snapshots/test_resolve_exports.snap
- crates/biome_module_graph/tests/spec_test.rs
Minor tweaks in how type member properties and methods are formatted.
Already included are some tests for the upcoming project-level resolution. By getting these in early, I hopefully avoid merge conflicts if other changes to type formatting are merged.
Snapshots updated.
> chore: type formatting tweaks

- .github/workflows/beta.yml
- .github/workflows/preview.yml
- .github/workflows/release.yml
- .github/workflows/release_cli.yml
Fixed `if` condition to test the runner is Windows, that was changed by adopting depot runner in #5734.
The preview workflow will be green in the next run.
> ci: fix binary path when building on Windows

- .github/workflows/beta.yml
- .github/workflows/beta_js_api.yml
- .github/workflows/preview.yml
- .github/workflows/release_cli.yml
- .github/workflows/release_js_api.yml
Fixed publish jobs to use GitHub hosted runner as npm provenance is not available on self-hosted runners, including depot.
See https://github.com/biomejs/biome/actions/runs/14727707221/job/41335419733 for error details
The release workflow will be green in the next run
> ci: use GitHub hosted runner for publish workflows

- Cargo.lock
- crates/biome_js_analyze/src/lint/correctness/no_private_imports.rs
- crates/biome_js_analyze/src/lint/correctness/use_import_extensions.rs
- crates/biome_js_analyze/src/lint/nursery/no_import_cycles.rs
- crates/biome_js_type_info/Cargo.toml
- crates/biome_js_type_info/src/flattening.rs
- crates/biome_js_type_info/src/format_type_info.rs
- crates/biome_js_type_info/src/globals.rs
- crates/biome_js_type_info/src/local_inference.rs
- crates/biome_js_type_info/src/resolver.rs
- crates/biome_js_type_info/src/type_info.rs
- crates/biome_js_type_info/tests/type_info.rs
- crates/biome_js_type_info/tests/utils.rs
- crates/biome_module_graph/src/format_module_graph.rs
- crates/biome_module_graph/src/js_module_info.rs
- crates/biome_module_graph/src/js_module_info/ad_hoc_scope_resolver.rs
- crates/biome_module_graph/src/js_module_info/binding.rs
- crates/biome_module_graph/src/js_module_info/collector.rs
- crates/biome_module_graph/src/js_module_info/scope.rs
- crates/biome_module_graph/src/js_module_info/visitor.rs
- crates/biome_module_graph/src/lib.rs
- crates/biome_module_graph/src/module_graph.rs
- crates/biome_module_graph/tests/snapshots/test_resolve_export_type_referencing_imported_type.snap
- crates/biome_module_graph/tests/snapshots/test_resolve_exports.snap
- crates/biome_module_graph/tests/spec_test.rs
I'm trying to avoid another huge PR, so I'm taking some smaller steps here :)
The main change in this PR is that `ResolvedTypeId` can now contain a `ModuleId` in addition to a `TypeId`. Such a `ModuleId` would only be used in combination with `TypeResolverLevel::Module`, but with a catch: The types stored in the module graph would not contain these module IDs, because it brings all kinds of complexity if a module needs to know its own ID. So the idea for now is that the `AdHocTypeResolver` will attach these module IDs at resolution time in order to keep track of which modules given types came from. I'm not yet sure it will be as easy as this, but that's the direction I'm going in.
Other changes are:
* `JsResolvedPath` and `JsImportSymbol` have been moved from `biome_module_graph` to …
> feat(core): add `ModuleId` to `ResolvedTypeId`

- crates/biome_js_type_info/src/flattening.rs
- crates/biome_js_type_info/src/format_type_info.rs
- crates/biome_js_type_info/src/globals.rs
- crates/biome_js_type_info/src/local_inference.rs
- crates/biome_js_type_info/src/resolver.rs
- crates/biome_js_type_info/src/type_info.rs
- crates/biome_js_type_info/tests/flattening.rs
- crates/biome_js_type_info/tests/resolver.rs
- crates/biome_js_type_info/tests/utils.rs
- crates/biome_js_type_info_macros/src/resolvable_derive.rs
- crates/biome_module_graph/src/format_module_graph.rs
- crates/biome_module_graph/src/js_module_info.rs
- crates/biome_module_graph/src/js_module_info/ad_hoc_scope_resolver.rs
- crates/biome_module_graph/src/js_module_info/binding.rs
- crates/biome_module_graph/src/js_module_info/collector.rs
- crates/biome_module_graph/tests/snapshots/test_export_default_function_declaration.snap
- crates/biome_module_graph/tests/snapshots/test_export_referenced_function.snap
- crates/biome_module_graph/tests/snapshots/test_resolve_export_type_referencing_imported_type.snap
- crates/biome_module_graph/tests/snapshots/test_resolve_export_types.snap
- crates/biome_module_graph/tests/snapshots/test_resolve_exports.snap
- crates/biome_module_graph/tests/snapshots/test_resolve_promise_export.snap
- crates/biome_module_graph/tests/snapshots/test_resolve_promise_from_imported_function_returning_imported_promise_type.snap
- crates/biome_module_graph/tests/spec_test.rs
Another fix in preparation for full project-level inference.
The last PR introduced the concept of "downgrading" project references into `TypeReference::Import`, but it missed a lot of cases still. This fix allows this downgrading to be performed during the resolution phase of the inference, so that it can traverse all references in the types. This required an upgrade of the derive macro as well.
I have also removed the `run_inference()`, `resolve_all()` and `flatten_all()` methods from the `TypeResolver` trait. While they were similar between implementations, there were already some deviations, and they were getting bigger in this PR. By convention, they're still similarly named across trait implementations, but it's no longer part of the trait.
Also included is a new implementation of …
> fix(core): fix downgrading of project references

- crates/biome_lsp/src/server.tests.rs
It's a bit of a shot in the dark, but given that the reason the `watcher_updates_module_graph_with_directories` test fails on Windows seems to be a timing issue, I'm adding some sleeps to see if it fixes the CI.
Windows CI should become green.
> chore: fix Windows CI

- Cargo.lock
- crates/biome_js_semantic/Cargo.toml
- crates/biome_js_semantic/src/format_semantic_model.rs
- crates/biome_js_semantic/src/lib.rs
- crates/biome_js_semantic/src/semantic_model/model.rs
- crates/biome_js_semantic/src/semantic_model/scope.rs
- crates/biome_service/src/file_handlers/astro.rs
- crates/biome_service/src/file_handlers/css.rs
- crates/biome_service/src/file_handlers/graphql.rs
- crates/biome_service/src/file_handlers/grit.rs
- crates/biome_service/src/file_handlers/html.rs
- crates/biome_service/src/file_handlers/javascript.rs
- crates/biome_service/src/file_handlers/json.rs
- crates/biome_service/src/file_handlers/mod.rs
- crates/biome_service/src/file_handlers/svelte.rs
- crates/biome_service/src/file_handlers/vue.rs
- crates/biome_service/src/snapshots/biome_service__workspace__tests__debug_semantic_model.snap
- crates/biome_service/src/workspace.rs
- crates/biome_service/src/workspace.tests.rs
- crates/biome_service/src/workspace/client.rs
- crates/biome_service/src/workspace/server.rs
- crates/biome_service/src/workspace_types.rs
- crates/biome_wasm/src/lib.rs
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
While working on `noShadow`, I found it kinda difficult to work with the semantic model because of the lack of a visual representation. This PR aims to resolve that by adding a debug printer for the semantic model.
I've added this printer to the quick test for the analyzer. I didn't make any explicit tests since it's just debug output and not functionality that end users will be engaging with.
> feat(workspace): add semantic model debug printer

- .changeset/tidy-llamas-glow.md
- crates/biome_js_analyze/src/lint/nursery/use_numeric_separators.rs
- crates/biome_js_analyze/tests/specs/nursery/useNumericSeparators/valid.js
- crates/biome_js_analyze/tests/specs/nursery/useNumericSeparators/valid.js.snap
Fixes https://github.com/biomejs/biome/issues/5826, which incorrectly flagged single-digit 0.
- Added a test for single-digit 0.
- Existing tests pass.
> fix(lint/useNumericSeparators): avoid false positive on single-digit 0

- crates/biome_module_graph/src/resolver_cache.rs
- crates/biome_service/src/workspace/scanner.rs
- crates/biome_service/src/workspace/server.rs
The scanner opens files in the worker threads powered by rayon, but collecting type info is run in the main thread after the traversal. It contains type inference, which is CPU-heavy operation. Plus, it can be moved to threads safely.
You can see only the main thread is busy while scanning in the following screenshot:
During investigation, I noticed that `ctx.workspace.update_module_graph()` is also called in the traversal. It tried to resolve the imported modules to update the graph, but it always fail due to a small bug in the resolver cache. Finally I removed duplicated calls of `ctx.workspace.update_module_graph()`, so now the graph is updated in the first call during the traversal. After this, all worker threads are used to collecting module graph and infering types:
Existing tests …
> perf(scanner): update type info in worker threads

- .changeset/five-schools-shave.md
- .changeset/good-jeans-invite.md
- crates/biome_cli/src/commands/mod.rs
- crates/biome_cli/src/commands/rage.rs
- crates/biome_cli/src/execute/mod.rs
- crates/biome_cli/src/execute/process_file/format.rs
- crates/biome_cli/src/execute/traverse.rs
- crates/biome_cli/src/reporter/mod.rs
- crates/biome_cli/src/reporter/terminal.rs
- crates/biome_cli/tests/cases/mod.rs
- crates/biome_cli/tests/cases/reporter_terminal.rs
- crates/biome_cli/tests/commands/lint.rs
- crates/biome_cli/tests/snapshots/main_cases_reporter_terminal/reports_diagnostics_check_command_verbose.snap
- crates/biome_cli/tests/snapshots/main_cases_reporter_terminal/reports_diagnostics_check_write_command_verbose.snap
- crates/biome_cli/tests/snapshots/main_cases_rules_via_dependencies/enables_next_rules_via_dependencies.snap
- crates/biome_cli/tests/snapshots/main_cases_rules_via_dependencies/enables_react_rules_via_dependencies.snap
- crates/biome_cli/tests/snapshots/main_cases_rules_via_dependencies/enables_test_globals_via_dependencies.snap
- crates/biome_cli/tests/snapshots/main_cases_vcs_ignored_files/ignore_vcs_ignored_file_via_cli.snap
- crates/biome_cli/tests/snapshots/main_commands_check/should_show_formatter_diagnostics_for_files_ignored_by_linter.snap
- crates/biome_cli/tests/snapshots/main_commands_format/should_format_files_in_folders_ignored_by_linter.snap
- crates/biome_cli/tests/snapshots/main_commands_lint/include_files_in_subdir.snap
- crates/biome_cli/tests/snapshots/main_commands_lint/include_files_in_symlinked_subdir.snap
- crates/biome_cli/tests/snapshots/main_commands_lint/should_report_when_schema_version_mismatch.snap
Closes https://github.com/biomejs/biome/issues/5817
Closes https://github.com/biomejs/biome/issues/5565
- Fixes a bug where the path of CLI diagnostics had a leading slash. This was caused by the fact that the `DiagnosticPrinter` receives file paths in the form of a string, and this caused the bug when doing `strip_prefix`. It's way easier and predictable to convert the file path into `Utf8PathBuf` and then strip the working directory
- The same was done for the "missing handler" diagnostic, which fixes other diagnostics that are usually printed via `--verbose`
- Always with `--verbose`, now the emitted paths are relative. Easier and safer to share
- Same for the configuration path when using `biome rage`
- The first time we load the configuration, we only print diagnostics **if there are …
> fix(core): printed directories

- crates/biome_module_graph/src/js_module_info/ad_hoc_scope_resolver.rs
- crates/biome_module_graph/tests/snapshots/test_resolve_promise_from_imported_function_returning_reexported_promise_type.snap
- crates/biome_module_graph/tests/spec_test.rs
Fix panics that occurred due to incorrect indexing in module/type vectors. At least one consistent method of triggering such panics was by using reexports, which is now fixed.
Test added. At the end of the test is still a failing assertion which I commented out, but at least the panics triggered by the test are resolved, so I'd like to merge this first.
> fix(core): fix incorrect module ID in reexport

- crates/biome_js_analyze/src/lint/correctness/use_jsx_key_in_iterable.rs
- crates/biome_service/src/workspace/scanner.rs
- crates/biome_service/tests/spec_test.rs
Seems that loading manifests inside `node_modules` results in some regressions, so we should be more careful about this.
Uncommented the test that checks for the manifest loading for now.
> fix(core): don't load manifests inside `node_modules` for now

- crates/biome_yaml_factory/src/generated/node_factory.rs
- crates/biome_yaml_factory/src/generated/syntax_factory.rs
- crates/biome_yaml_syntax/src/generated/kind.rs
- crates/biome_yaml_syntax/src/generated/macros.rs
- crates/biome_yaml_syntax/src/generated/nodes.rs
- crates/biome_yaml_syntax/src/generated/nodes_mut.rs
- xtask/codegen/src/yaml_kinds_src.rs
- xtask/codegen/yaml.ungram
YAML specification states that one node may have two properties: one anchor and one tag. However, the current implementation allows an arbitrary number of properties.
Everything should still remain green
> fix(yaml_parser): only allows maximum 2 properties per node

- .changeset/floppy-beers-shave.md
- crates/biome_analyze/src/rule.rs
- crates/biome_cli/src/execute/migrate/eslint_any_rule_to_biome.rs
- crates/biome_js_analyze/src/lint/complexity/no_excessive_nested_test_suites.rs
- crates/biome_js_analyze/src/lint/style/no_done_callback.rs
- crates/biome_js_analyze/src/lint/suspicious/no_duplicate_test_hooks.rs
- crates/biome_js_analyze/src/lint/suspicious/no_focused_tests.rs
- crates/biome_js_analyze/src/lint/suspicious/no_misplaced_assertion.rs
- crates/biome_js_analyze/src/lint/suspicious/no_skipped_tests.rs
Part of https://github.com/biomejs/biome/discussions/5862. Adds `@vitest/eslint-plugin` alongside `eslint-plugin-jest` as a rule source.
- Docs-only change
> docs: add @vitest/eslint-plugin as rule source

- crates/biome_js_analyze/src/lint/correctness/no_nonoctal_decimal_escape.rs
- crates/biome_js_analyze/src/lint/correctness/no_private_imports.rs
- crates/biome_js_analyze/src/lint/correctness/no_undeclared_dependencies.rs
- crates/biome_js_analyze/src/lint/correctness/no_undeclared_variables.rs
- crates/biome_js_analyze/src/lint/correctness/use_exhaustive_dependencies.rs
- crates/biome_js_analyze/src/lint/nursery/no_import_cycles.rs
- crates/biome_js_analyze/src/lint/nursery/no_restricted_types.rs
- crates/biome_js_analyze/src/lint/nursery/no_unresolved_imports.rs
- crates/biome_js_analyze/src/lint/nursery/use_sorted_classes.rs
- crates/biome_js_analyze/src/lint/nursery/use_sorted_classes/class_info.rs
- crates/biome_js_analyze/src/lint/nursery/use_sorted_classes/class_lexer.rs
- crates/biome_js_analyze/src/lint/nursery/use_sorted_classes/sort.rs
- crates/biome_js_analyze/src/lint/style/use_numeric_literals.rs
- crates/biome_js_analyze/src/lint/suspicious/no_duplicate_class_members.rs
- crates/biome_js_analyze/src/lint/suspicious/no_prototype_builtins.rs
- crates/biome_js_analyze/src/lint/suspicious/no_shadow_restricted_names.rs
- crates/biome_js_analyze/src/react/hooks.rs
Essentially follow up to https://github.com/biomejs/biome/pull/4211. I have limited understanding of memory in Rust so correct me if I am wrong:
- Replace usages of `String` with `Box<str>`, because its immutable, 24b vs 16b.
- Replace some usages of `to_string().into_boxed_str()` with `Box::from(str)` to avoid additional temporary allocation into heap.
- Replace some usages of `text_trimmed().to_string()` with `text_trimmed().into_text()` to prevent allocating new string when possible.
Existing tests should pass
> perf(js_analyze): use Box<str> in more places to reduce memory

- crates/biome_yaml_parser/src/lexer/mod.rs
- crates/biome_yaml_parser/src/lexer/tests.rs
- crates/biome_yaml_parser/src/token_source.rs
Allow the YAML lexer to lex plain token.
Added new tests for the lexer.
> feat(yaml_parser): lex plain token

- crates/biome_lsp/src/server.tests.rs
- crates/biome_service/src/workspace_watcher.rs
Fixed failing watcher tests on macOS, broken since f535ccfde5da7d64cec28612cb2a2fc1dd2ceb7d.
macOS CI should back to green.
Test Run: https://github.com/siketyan/biome/actions/runs/14854226578/job/41703612260
> fix(watcher): fix failing watcher tests on macOS

- crates/biome_cli/src/execute/migrate/node.rs
Loaded ESLint config may not be deserialized successfully, emitting diagnostics. It is hard to debug the diagnostics when the loaded config is large like #5900. In this pull request, the JSON configuration to be deserialized is now prettified, by adding the third argument to `JSON.stringify`.
> feat(cli): prettify ESLint config on loading for migration

- Cargo.lock
- crates/biome_yaml_parser/Cargo.toml
- crates/biome_yaml_parser/src/parser/block.rs
- crates/biome_yaml_parser/src/parser/document.rs
- crates/biome_yaml_parser/src/parser/flow.rs
- crates/biome_yaml_parser/src/parser/mod.rs
- crates/biome_yaml_parser/src/parser/parse_error.rs
- crates/biome_yaml_parser/tests/spec_test.rs
- crates/biome_yaml_parser/tests/spec_tests.rs
- crates/biome_yaml_parser/tests/yaml_test_suite/ok/flow/simple_plain.yaml
- crates/biome_yaml_parser/tests/yaml_test_suite/ok/flow/simple_plain.yaml.snap
Allows the parser to parse a document containing a single plain node
Added a new test document with contains a single plain node
> feat(yaml): parse plain node

- .changeset/heavy-heads-slide.md
- crates/biome_cli/src/execute/migrate/eslint_eslint.rs
- crates/biome_cli/src/execute/migrate/eslint_to_biome.rs
Fixes #5900 
Added support for nested `files` property in ESLint flat configurations, such as:
```jsonc
{
"files": [
["**/*.ts", "**/*.tsx"],
["**/*.js", "**/*.jsx"],
],
}
```
Note that the deserialized value is flattened.
Existing tests should pass. Manually tested that the reproduction in #5900 no longer emit diagnostics.
> fix(cli): support nested `files` property in ESLint flat config

- crates/biome_js_analyze/tests/quick_test.rs
- crates/biome_js_analyze/tests/specs/nursery/noFloatingPromises/panicBar.ts
- crates/biome_js_analyze/tests/specs/nursery/noFloatingPromises/panicBar.ts.snap
- crates/biome_js_analyze/tests/specs/nursery/noFloatingPromises/panicFoo.ts
- crates/biome_js_analyze/tests/specs/nursery/noFloatingPromises/panicFoo.ts.snap
- crates/biome_js_type_info/src/flattening.rs
- crates/biome_js_type_info/src/globals.rs
- crates/biome_js_type_info/src/helpers.rs
- crates/biome_js_type_info/src/lib.rs
- crates/biome_js_type_info/src/local_inference.rs
- crates/biome_js_type_info/src/resolver.rs
- crates/biome_js_type_info/src/type_info.rs
- crates/biome_js_type_info/tests/snapshots/infer_flattened_type_from_static_promise_function.snap
- crates/biome_js_type_info/tests/utils.rs
- crates/biome_module_graph/src/js_module_info.rs
- crates/biome_module_graph/src/js_module_info/collector.rs
- crates/biome_module_graph/src/js_module_info/scoped_resolver.rs
- crates/biome_module_graph/tests/snap/mod.rs
- crates/biome_module_graph/tests/snapshots/test_module_id_handling.snap
- crates/biome_module_graph/tests/snapshots/test_resolve_promise_from_imported_function_returning_imported_promise_type.snap
- crates/biome_module_graph/tests/snapshots/test_resolve_promise_from_imported_function_returning_reexported_promise_type.snap
- crates/biome_module_graph/tests/spec_test.rs
Since I introduced full type inference, there's been instances of panics because types would be looked up in the wrong module. I tracked it to an oversight with how we look up references: Whenever we retrieve a type from a resolver, we would get a `TypeData` reference. If that type contained nested `TypeReference` instances, we would attempt to look up those as well, but at that point we'd lost the information from which module the resolver had retrieved the initial `TypeData`.
I had already introduced the module IDs on `ResolvedTypeId`, so that such information can be tracked, but whenever we'd get a plain `&TypeData`, we'd lose track of it.
To fix this, I've introduced `ResolvedTypeData`, which can track the same information when dealing with `TypeData` references as well.
This did …
> fix(core): track resolver data

- crates/biome_module_graph/src/js_module_info/scoped_resolver.rs
- crates/biome_module_graph/tests/snapshots/test_resolve_promise_from_imported_function_returning_reexported_promise_type.snap
- crates/biome_module_graph/tests/spec_test.rs
Small fix so our type inference can follow named reexports. Blanket reexports are still not followed.
Test updated.
> fix(core): handle named reexports

- biome.json
- crates/biome_js_analyze/src/lib.rs
- crates/biome_js_analyze/src/lint/correctness/no_undeclared_dependencies.rs
- crates/biome_js_analyze/tests/spec_tests.rs
- crates/biome_js_analyze/tests/specs/correctness/noUndeclaredDependencies/invalid.js.snap
- crates/biome_js_analyze/tests/specs/correctness/noUndeclaredDependencies/invalid.test.js.snap
- crates/biome_module_graph/src/resolver_cache.rs
- crates/biome_module_graph/tests/spec_test.rs
- crates/biome_package/src/lib.rs
- crates/biome_package/src/node_js_package/mod.rs
- crates/biome_package/src/node_js_package/package_json.rs
- crates/biome_package/tests/tsconfig/valid/tsconfig.valid.baseUrl.json.snap
- crates/biome_package/tests/tsconfig/valid/tsconfig.valid.paths.json.snap
- crates/biome_project_layout/src/project_layout.rs
- crates/biome_service/src/file_handlers/mod.rs
- crates/biome_service/src/workspace/scanner.rs
- crates/biome_service/src/workspace/server.rs
- crates/biome_test_utils/src/lib.rs
Includes performance improvements **and one functional change**:
* Reverts #5910 due to a performance regression.
* Because parsing versions in `package.json` has proved problematic, they're now deserialised as `String` and only parsed into a semantic version on demand. I haven't noticed much performance impact of this, but at least it should solve issues with panics on incorrect semantic versions that plagued us before.
* Some tiny optimisations in our resolver cache.
* **Functional change:** `package.json` files inside `node_modules` are scanned again. I witnessed that indeed this used to cause a performance regression, but I've managed to mitigate this impact as you can see in https://github.com/biomejs/biome/commit/74266e62222f273c7f2c33647c14d15dca7d1115.
Performance is now back to …
> perf: faster manifest handling

- .github/renovate.json
Added a [regex manager](https://docs.renovatebot.com/modules/manager/regex/) for updating the toolchain version in `rust-toolchain.toml` automatically.
ref: https://github.com/renovatebot/renovate/issues/11488
ref: https://github.com/Turbo87/renovate-config/blob/3efd54b2e6eb9ad396970a61dfb52024d45052a8/rust/updateToolchain.json
I will check the dependency dashboard after merged this PR
> chore: update rust-toolchain.toml on Renovate

- .github/workflows/beta.yml
- .github/workflows/preview.yml
- .github/workflows/release.yml
- .github/workflows/release_cli.yml
Fixes #5896 
Changed release workflows to use the `rust:1.85.1-bullseye` image for building binaries for GNU/Linux. As glibc is dynamically linked by the version in the build environment, we need to use older Linux distribution on building to keep maximum compatibility.
Test Run: https://github.com/siketyan/biome/actions/runs/14888648016/job/41814926577
The next preview release should be green.
> ci: build GNU/Linux binaries in Docker

- Cargo.lock
- Cargo.toml
- crates/biome_fs/src/path.rs
- crates/biome_lsp/Cargo.toml
- crates/biome_lsp/src/capabilities.rs
- crates/biome_lsp/src/diagnostics.rs
- crates/biome_lsp/src/handlers/analysis.rs
- crates/biome_lsp/src/handlers/formatting.rs
- crates/biome_lsp/src/handlers/rename.rs
- crates/biome_lsp/src/handlers/text_document.rs
- crates/biome_lsp/src/requests/syntax_tree.rs
- crates/biome_lsp/src/server.rs
- crates/biome_lsp/src/server.tests.rs
- crates/biome_lsp/src/session.rs
- crates/biome_lsp/src/utils.rs
- crates/biome_lsp_converters/Cargo.toml
- crates/biome_lsp_converters/src/from_proto.rs
- crates/biome_lsp_converters/src/lib.rs
- crates/biome_lsp_converters/src/to_proto.rs
- crates/biome_service/src/file_handlers/javascript.rs
The crate `tower-lsp` isn't maintained anymore. The create https://github.com/tower-lsp-community/tower-lsp-server is a new community fork that is maintained.
- changed the code to confirm to the new crate
- the new create uses `Uri` instead of `Url` which behaves differently, so I updated the code accordingly
- `Uri` has some interior mutability, which triggers [`mutable_key_type`](https://rust-lang.github.io/rust-clippy/master/index.html#mutable_key_type), so I turned it off in the files where it was triggered
The CI should still pass
> refactor(lsp): use `tower-lsp-server`

- .changeset/rule-severity-overhaul.md
- crates/biome_analyze/CONTRIBUTING.md
Add more guidelines to choose a rule name and add guideline for choosing a severity level.
> docs(linter): add rule naming and severity choice guidelines

- crates/biome_js_type_info/src/flattening.rs
I've noticed it is easy to make mistakes that cause a stack overflow in flattening, given that the method calls itself recursively.
This PR reduces the recursiveness and adds a maximum depth guard.
> fix(core): add guard for flattening depth

- crates/biome_js_analyze/src/lint/nursery/use_iterable_callback_return.rs
- crates/biome_js_analyze/tests/specs/nursery/useIterableCallbackReturn/valid.js
- crates/biome_js_analyze/tests/specs/nursery/useIterableCallbackReturn/valid.js.snap
Fixes #5939 
Async and generator callbacks should be ignored as they always return a `Promise` or a `Generator` object respectively.
cc @mdevils 
Added snapshot tests.
> fix(lint): ignore async and generator callbacks in useIterableCallbackReturn

- Cargo.lock
- crates/biome_css_analyze/tests/spec_tests.rs
- crates/biome_graphql_analyze/tests/spec_tests.rs
- crates/biome_graphql_analyze/tests/specs/nursery/useNamedOperation/valid.graphql
- crates/biome_graphql_analyze/tests/specs/nursery/useNamedOperation/valid.graphql.snap
- crates/biome_graphql_analyze/tests/specs/nursery/useNamingConvention/valid.graphql
- crates/biome_graphql_analyze/tests/specs/nursery/useNamingConvention/valid.graphql.snap
- crates/biome_graphql_analyze/tests/specs/style/useDeprecatedReason/valid.graphql
- crates/biome_graphql_analyze/tests/specs/style/useDeprecatedReason/valid.graphql.snap
- crates/biome_js_analyze/tests/spec_tests.rs
- crates/biome_js_analyze/tests/suppression/source/useSortedAttributes/valid.jsx
- crates/biome_js_analyze/tests/suppression/source/useSortedAttributes/valid.jsx.snap
- crates/biome_js_transform/tests/spec_tests.rs
- crates/biome_json_analyze/tests/spec_tests.rs
- crates/biome_migrate/tests/spec_tests.rs
- crates/biome_test_utils/Cargo.toml
- crates/biome_test_utils/src/lib.rs
Follow up to https://github.com/biomejs/biome/pull/5883
- Add new `assert_diagnostics_expectation_comment` test helper which validates if diagnostics were genereted or not based on `should not generate diagnostics` / `should generate diagnostics` comments.
- It also checks that valid test files contain former comment.
- Update grapqhl snapshots with the right comment.  
Existing tests pass
> chore(tests): add test utils for asserting valid snapshots did not generate diagnostics

- crates/biome_yaml_factory/src/generated/node_factory.rs
- crates/biome_yaml_factory/src/generated/syntax_factory.rs
- crates/biome_yaml_syntax/src/generated/nodes.rs
- crates/biome_yaml_syntax/src/generated/nodes_mut.rs
- xtask/codegen/yaml.ungram
According to the [spec](https://yaml.org/spec/1.2.2/#rule-s-l+block-indented), an indented block node inside a block collection can be empty. Instead of modeling an empty node, this PR makes this node type optional wherever it's referred.
Also renamed to `AnyYamlBlockIndented` to match spec naming.
> fix(yaml): make indented block in mapping optional

- .changeset/warm-streets-think.md
- crates/biome_js_parser/src/syntax/expr.rs
- crates/biome_js_parser/tests/js_test_suite/ok/logical_expression_with_jsx.tsx
- crates/biome_js_parser/tests/js_test_suite/ok/logical_expression_with_jsx.tsx.snap
- crates/biome_parser/src/parse_lists.rs
closes: #5876 
The issue is caused by the case([playground link](https://biomejs.dev/playground/?lintRules=all&code=bABlAHQAIABiACAAPQAgADEAOwAKAAoAZgB1AG4AYwB0AGkAbwBuACAAQQAoACkAIAB7AAoAIAAgAGMAbwBuAHMAdAAgAGEAIAA9ACAAYgAgAD4AIAAwACAAJgAmACAAYgAgADwAIAAxAAoAIAAgAHIAZQB0AHUAcgBuACAAKAAKACAAIAAgACAAPABYAC4AWQA%2BAAoAIAAgACAAIAAgACAAIAB7AGEAfQAKACAAIAAgACAAPAAvAFgALgBZAD4ACgAgACAAKQAgACAACgB9AA%3D%3D)):
```jsx
let b = 1;
function  A() {
const a = b > 0 && b < 1
return (
<X.Y>
{a}
</X.Y>
)  
}
```
The  right logical expression `b < 1` will be parse as `TsInstantiationExpression`, and `< 1` and `return ( < X.Y>` will parse as `TsTypeArguments`. (For the users, they can add a semicon after `b < 1` to solve the problem), but we need to solve that case, so i add a special judge when parse …
> fix(parser): should parse Fragment syntax correct

- crates/biome_cli/src/execute/traverse.rs
- crates/biome_fs/src/fs.rs
- crates/biome_fs/src/fs/memory.rs
- crates/biome_fs/src/fs/os.rs
- crates/biome_service/src/workspace.rs
- crates/biome_service/src/workspace/scanner.rs
- crates/biome_service/src/workspace/server.rs
- crates/biome_service/tests/spec_test.rs
This changes the logic for what the scanner should scan: It now respects the top-level `files.includes` setting, with two exceptions:
* Supported files are always scanned, provided they are in directory that is not ignored.
* `node_modules` is always scanned when using `ScanKind::Project`.
The main advantage of this is that users gain the ability to configure the scanner, without exposing new configuration settings. There is some subtlety with use cases such as codegen however: Users usually want to exclude generated files, but some use cases we _should_ scan them. For these use cases, we should advise users to _include_ them in the top-level `files.includes`, and _exclude_ them using the tool-specific `includes` settings.
Everything should remain green. Also manually tested.
> fix(core): scanner tweak: mostly respect ignored dirs

- crates/biome_cli/tests/snapshots/main_cases_migrate_v2/should_successfully_migrate_ariakit.snap
- crates/biome_cli/tests/snapshots/main_cases_migrate_v2/should_successfully_migrate_knip.snap
- crates/biome_cli/tests/snapshots/main_cases_migrate_v2/should_successfully_migrate_sentry.snap
- crates/biome_json_syntax/src/object_ext.rs
- crates/biome_migrate/src/analyzers/organize_imports.rs
- crates/biome_migrate/src/analyzers/rule_mover.rs
- crates/biome_migrate/src/analyzers/style_rules.rs
- crates/biome_migrate/tests/specs/migrations/organizeImports/invalid.json.snap
- crates/biome_migrate/tests/specs/migrations/organizeImports/invalid2.json
- crates/biome_migrate/tests/specs/migrations/organizeImports/invalid2.json.snap
- crates/biome_rowan/src/syntax/token.rs
This PR improves our `organizeImports` migration by supporting overrides.
I added a new test.
> refactor(migrate): improve organizeImports migration

- crates/biome_js_analyze/src/lint/complexity/use_date_now.rs
- crates/biome_js_analyze/tests/specs/complexity/useDateNow/invalid.js.snap
Added a missing whitespace between `Date` and `object` words.
> fix(lint/useDateNow): add a missing space between words in diagnostic

- crates/biome_js_type_info/CONTRIBUTING.md
Adds a `CONTRIBUTING.md` to `biome_js_type_info` with a description of our type architecture.
It's an adaptation of part of the blog post I intend to publish today.
Proof read.
> docs: type architecture

- crates/biome_cli/tests/snapshots/main_cases_migrate_v2/should_migrate_aws_config.snap
- crates/biome_cli/tests/snapshots/main_cases_migrate_v2/should_successfully_migrate_knip.snap
- crates/biome_migrate/src/analyzers/rule_mover.rs
- crates/biome_migrate/tests/specs/migrations/ruleMover/duplicated.json
- crates/biome_migrate/tests/specs/migrations/ruleMover/duplicated.json.snap
- crates/biome_migrate/tests/specs/migrations/ruleMover/renaming.json
- crates/biome_migrate/tests/specs/migrations/ruleMover/renaming.json.snap
- crates/biome_migrate/tests/specs/migrations/ruleMover/transformed.json.snap
- crates/biome_migrate/tests/specs/migrations/ruleMover/transformed_with_level.json.snap
Improve the rule mover migration by handling already migrated rules and migration of several rules with the same name.
Basically, if the rule was already migrated, we just remove the old one.
This should solve an issue we have with a repository in the ecosystem-ci.
> refactor(migrate): handle already migrated rules

- crates/biome_cli/tests/snapshots/main_cases_migrate_v2/should_migrate_issue_5465.snap
- crates/biome_migrate/src/analyzers/rule_mover.rs
Currently, `useNamingConvention` is associated to two groups: `style` for the JS rule and `niursery` for the GraphQL rule.
This breaks the assumption that a rule is associated to a single group.
This leads the rule mover to unpromote `style/useNamingConvention` to `nursery/useNamingConvention`.
Unfortunately we can promote the GraphQL rule because the rule options are incompatible at the moment.
As a temporary fix of the rule mover, I added a hardcoded exception for `useNamingConvention`.
I updated the snapshots
> refactor(migrate): don't unpromote useNamingConvention

- .changeset/rotten-llamas-hang.md
- crates/biome_js_analyze/src/assist/source/organize_imports.rs
- crates/biome_js_analyze/src/assist/source/organize_imports/import_key.rs
- crates/biome_js_analyze/tests/specs/source/organizeImports/issue5985.js
- crates/biome_js_analyze/tests/specs/source/organizeImports/issue5985.js.snap
Fix https://github.com/biomejs/biome/issues/5985
I forget to handle the case of default and named imports merging.
I added a non regression test.
> fix(organizeImports): merge default and named imports

- .changeset/whole-clouds-lead.md
- crates/biome_cli/src/commands/mod.rs
- crates/biome_cli/src/commands/scan_kind.rs
- crates/biome_cli/src/execute/migrate.rs
- crates/biome_cli/src/execute/mod.rs
- crates/biome_cli/tests/commands/migrate.rs
- crates/biome_cli/tests/snap_test.rs
- crates/biome_cli/tests/snapshots/main_cases_config_path/set_config_path_to_directory.snap
- crates/biome_cli/tests/snapshots/main_cases_editorconfig/should_not_use_higher_editorconfig_when_find_biome_conf.snap
- crates/biome_cli/tests/snapshots/main_cases_migrate_v2/should_migrate_aws_config.snap
- crates/biome_cli/tests/snapshots/main_cases_migrate_v2/should_migrate_issue_5465.snap
- crates/biome_cli/tests/snapshots/main_cases_migrate_v2/should_successfully_migrate_ariakit.snap
- crates/biome_cli/tests/snapshots/main_cases_migrate_v2/should_successfully_migrate_knip.snap
- crates/biome_cli/tests/snapshots/main_cases_migrate_v2/should_successfully_migrate_sentry.snap
- crates/biome_cli/tests/snapshots/main_commands_format/custom_config_file_path.snap
- crates/biome_cli/tests/snapshots/main_commands_migrate/should_migrate_nested_files.snap
- crates/biome_cli/tests/snapshots/main_commands_migrate_eslint/migrate_eslintrcjson_exclude_inspired.snap
- crates/biome_cli/tests/snapshots/main_commands_migrate_eslint/migrate_eslintrcjson_fix.snap
- crates/biome_cli/tests/snapshots/main_commands_migrate_eslint/migrate_eslintrcjson_write.snap
- crates/biome_cli/tests/snapshots/main_commands_migrate_prettier/prettier_migrate_fix.snap
- crates/biome_cli/tests/snapshots/main_commands_migrate_prettier/prettier_migrate_write.snap
- crates/biome_cli/tests/snapshots/main_commands_migrate_prettier/prettier_migrate_write_biome_jsonc.snap
- crates/biome_cli/tests/snapshots/main_commands_migrate_prettier/prettier_migrate_write_packagejson.snap
- crates/biome_cli/tests/snapshots/main_commands_migrate_prettier/prettier_migrate_write_with_ignore_file.snap
- crates/biome_cli/tests/snapshots/main_commands_migrate_prettier/prettierjson_migrate_write.snap
- crates/biome_service/src/workspace.rs
- crates/biome_service/src/workspace/scanner.rs
- crates/biome_service/src/workspace/server.rs
Part of #2228 
This PR adds a new feature to the `migrate` command. With this PR, the command is now able to migrate nested configuration files. 
We take advantage of the light scanner to return the path to he configuration files. This will fix some repositories in the ecosystem CI, where they have nested `biome.json` inside their repositories, but the command fails because it sees old configuration files. 
This is also part of the monorepo support.
> feat(migrate): migrate nested configuration files

- .changeset/eleven-feet-heal.md
- crates/biome_lsp/src/handlers/formatting.rs
- crates/biome_lsp/src/server.tests.rs
Fixes #2260 
The LSP implementation of `textDocument/rangeFormatting` and `textDocument/onTypeFormatting` compares entire code of the source and the formatted snippet returned by `Workspace::format_range`. Return value of `format_range` only contains code within the range, so the compared diff deletes most of the code incorrectly.
This pull request fixes the behaviour by limiting the source to the formatted range specified in `Printed::range`, before comparing it.
Added a test to `server.tests.rs`.
> fix(lsp): compare only the formatted range on range formatting

- .changeset/chubby-dancers-design.md
- .changeset/twelve-streets-drop.md
- crates/biome_cli/src/cli_options.rs
- crates/biome_cli/src/execute/mod.rs
- crates/biome_cli/src/reporter/mod.rs
- crates/biome_cli/src/reporter/summary.rs
- crates/biome_cli/src/reporter/terminal.rs
- crates/biome_cli/tests/cases/reporter_summary.rs
- crates/biome_cli/tests/snapshots/main_cases_reporter_summary/reports_diagnostics_summary_check_verbose_command.snap
Closes https://github.com/biomejs/biome/issues/4052
The `summary` reporter now doesn't take `--max-diagnostics` into account. I ended up **not** adding a warning message because by default, Biome sets 20 as the default limit. This means there's a limit by default. 
I also fixed a bug where `summary` didn't report the processed/fixed files. 
> fix(reporter): summary with diagnostics

- .changeset/bright-teeth-like.md
- crates/biome_cli/tests/commands/lint.rs
- crates/biome_cli/tests/snapshots/main_commands_lint/lint_only_missing_group.snap
- crates/biome_configuration/src/analyzer/mod.rs
- crates/biome_migrate/src/analyzers/rule_mover.rs
This Pr adds the capability of passing only the rule name in `--only` and `--skip` CLI options.
Previously `--only=<rule-name>` was rejected.
You had to add the group name: `--only=<group-name>/<rule-name>`.
`--only=<rule-name>` is now accepted.
I took the opportunity of improving the validation.
We now reject using the `lint/` prefix for an assist action/group and the `assist/` prefix for a lint rule/group.
I updated the snapshots.
> feat(cli): support rule without group in `--only` and `--skip`

- crates/biome_service/src/workspace/scanner.rs
- crates/biome_service/src/workspace/server.rs
- crates/biome_service/src/workspace/watcher.rs
- crates/biome_service/src/workspace/watcher.tests.rs
- crates/biome_service/src/workspace_watcher.rs
This prevents a huge CPU spike we sometimes see when starting the LSP.
I do suspect a follow-up may be necessary trying to further optimise `session.update_all_diagnostics()` itself.
> fix(core): only trigger on ServiceDataNotification per scan

- crates/biome_analyze/src/lib.rs
- crates/biome_cli/tests/commands/check.rs
- crates/biome_cli/tests/snapshots/main_commands_check/check_plugin_suppressions.snap
- crates/biome_grit_patterns/src/grit_context.rs
- crates/biome_service/src/snapshots/biome_service__workspace__tests__plugins_can_use_custom_severity.snap
- crates/biome_service/src/workspace/server.rs
Fixes #6031: `biome check` calls the analyzer twice, once for formatting and once for linting. But it handed the linter plugins to both invocations, causing them to run twice. Worse, in the formatting invocation, the suppressions didn't work either.
Also fixes an issue that could cause certain Grit queries to report double diagnostics.
Test added.
> fix(analyzer): fix plugin diagnostic suppression + resolve double diagnostics

- .changeset/rotten-birds-greet.md
- crates/biome_js_analyze/src/lint/nursery/no_useless_escape_in_string.rs
- crates/biome_js_analyze/tests/specs/nursery/noUselessEscapeInString/invalid.js
- crates/biome_js_analyze/tests/specs/nursery/noUselessEscapeInString/invalid.js.snap
- crates/biome_js_analyze/tests/specs/nursery/noUselessEscapeInString/valid.js
- crates/biome_js_analyze/tests/specs/nursery/noUselessEscapeInString/valid.js.snap
Fixes https://github.com/biomejs/biome/issues/6039, which incorrectly flagged `\${` escape in template literals.
- Added a valid test case for `\${`, and an invalid case for `\$x`.
- Existing tests pass.
> fix(lint/noUselessEscapeInString): avoid false positive for `\${` escape in template literals

- crates/biome_resolver/src/lib.rs
This pull request fixes the failing test on Windows.
The culprit was a very niche case, where `node_modules` directory is at the root of the filesystem. In this case, `package_path` becomes `//node_modules/shared` after concated the paths as string. I don't know why, but `Utf8Path::new("//node_modules/shared") == Utf8Path::new("/node_modules/shared")` is `true` on Linux/macOS but Windows. Thus we couldn't resolve the path correctly from the cache in `ModuleGraphFsProxy` only on Windows.
Windows CI should back green.
> fix: resolve packages in /node_modules correctly on Windows

- crates/biome_lsp/src/session.rs
This pull request scopes the `workspace/configuration` LSP request to the `root_uri` (root of the workspace folder).
If we don't scope the request, VS Code will return the global configuration and ignore any potential workspace folder configuration overrides (`.vscode/settings.json`).
```
2025-05-17 10:09:57.397 [info] [Trace - 10:09:57 AM] Sending request 'initialize - (0)'.
2025-05-17 10:09:57.397 [info] Params: {
"processId": 23983,
"clientInfo": {
"name": "Visual Studio Code",
"version": "1.100.2"
},
"locale": "en",
"rootPath": null,
"rootUri": null,
...
```
```
2025-05-17 10:10:07.361 [info] [Trace - 10:10:07 AM] Received request 'workspace/configuration - (0)'.
2025-05-17 10:10:07.361 [info] Params: {
"items": [
{
"section": "biome"
}
]
}
```
```
2025-05-17 10:12:32.703 [info] …
```
> fix(lsp): scope `workspace/configuration` request to workspace folder

- .changeset/petite-rats-sniff.md
- crates/biome_js_analyze/src/lint/nursery/no_useless_escape_in_string.rs
- crates/biome_js_analyze/tests/specs/nursery/noUselessEscapeInString/invalid.js
- crates/biome_js_analyze/tests/specs/nursery/noUselessEscapeInString/invalid.js.snap
- crates/biome_js_analyze/tests/specs/nursery/noUselessEscapeInString/valid.js
- crates/biome_js_analyze/tests/specs/nursery/noUselessEscapeInString/valid.js.snap
Fixed https://github.com/biomejs/biome/pull/6042. The rule now reports useless escapes after skipping `\${` in template literals.
- Added more tests for template literals with `\${`.
- Existing tests pass.
> fix(lint/noUselessEscapeInString): flag useless escapes after skipping \${ in template literals

- .github/renovate.json
The `rust` dependency is incorrectly included in the `github-actions` group as the Rust container image is referred in release workflows. However, we want to update `rust` as well as `rust-toolchain.toml` and `Dockerfile`. Added `rust` to the exclusion list of `depName` in the `github-actions` group to ensure the dependency is grouped individually.
N/A
> chore(renovate): ignore rust in the github-actions group

- crates/biome_js_analyze/src/lint/nursery/no_floating_promises.rs
- crates/biome_js_analyze/tests/specs/nursery/noFloatingPromises/invalid.ts
- crates/biome_js_analyze/tests/specs/nursery/noFloatingPromises/invalid.ts.snap
- crates/biome_js_type_info/src/type_info.rs
Sometimes a statement resolves not just to `Promise`, but to `Promise | undefined`, or another union that includes a `Promise`. Such statements should be awaited too for proper handling, so `noFloatingPromises` will now trigger on those too.
> fix(linter): noFloatingPromises detects "maybe" Promises

- CONTRIBUTING.md
- crates/biome_analyze/CONTRIBUTING.md
This PR updates the release process and the TOC
> docs: update contribution guides

- crates/biome_fs/src/path.rs
- crates/biome_service/src/workspace/scanner.rs
- crates/biome_service/tests/fixtures/with_ignored_required_files/.gitignore
- crates/biome_service/tests/fixtures/with_ignored_required_files/biome.jsonc
- crates/biome_service/tests/fixtures/with_ignored_required_files/dist/package.json
- crates/biome_service/tests/fixtures/with_ignored_required_files/file.js
- crates/biome_service/tests/fixtures/with_ignored_required_files/package.json
- crates/biome_service/tests/spec_test.rs
Fixes #6089. Also fixes an issue in our own CI: https://github.com/biomejs/biome/actions/runs/15120815401/job/42502525360?pr=6090
Now that we respect users `files.includes` and ignore settings better, we should also be even more careful to always load relevant manifests and other required files, _even when those are excluded by the users settings_. To fix this, we check whether required files are part of an ignored directory, and only ignore them when this is the case. Whether the file itself is ignored in the configuration is then irrelevant in such cases.
Added another test.
> fix(core): don't ignore required files

- crates/biome_cli/tests/snapshots/main_commands_migrate/should_migrate_nested_files.snap
- crates/biome_service/src/settings.rs
- crates/biome_service/src/workspace/scanner.rs
Closes https://github.com/biomejs/biome/issues/5832
Closes https://github.com/biomejs/biome/issues/5898
We were processing files from the leaves to the root, which means that we were using the "longest" `.gitignore` as the root, causing all sorts of false positives. 
I manually tested it using the reproduction provided in #5832
> fix(core): process root ignore first

- crates/biome_js_analyze/src/lint/correctness/no_invalid_use_before_declaration.rs
- crates/biome_js_analyze/src/lint/correctness/no_unused_variables.rs
- crates/biome_js_analyze/src/lint/correctness/use_exhaustive_dependencies.rs
- crates/biome_js_analyze/src/lint/style/use_naming_convention.rs
- crates/biome_js_semantic/src/events.rs
- crates/biome_js_syntax/src/binding_ext.rs
- crates/biome_js_type_info/src/flattening.rs
- crates/biome_js_type_info/src/local_inference.rs
- crates/biome_js_type_info/src/type_info.rs
- crates/biome_module_graph/src/js_module_info/binding.rs
- crates/biome_module_graph/src/js_module_info/visitor.rs
- crates/biome_module_graph/tests/snapshots/test_export_const_type_declaration_with_namespace.snap
- crates/biome_module_graph/tests/spec_tests.rs
- packages/@biomejs/biome/configuration_schema.json
This adds some minor improvements on inference from `.d.ts` files:
* Recognise function declarations.
* Partially infer namespaces and external module declarations. Heavy emphasis on **partial** since the members aren't populated yet. However, I did add a test that shows the members _are_ being recognised and interpreted during semantic analysis, so we should be able to populate the members there. (Doing it during local inference would only make the computation more expensive.)
* Handle `export =` assignments.
Tests added.
> feat(core): improve inference on `.d.ts` files

- crates/biome_js_type_info/src/helpers.rs
- crates/biome_module_graph/src/js_module_info/collector.rs
- crates/biome_module_graph/tests/snapshots/test_export_const_type_declaration_with_namespace.snap
Another small step towards `.d.ts` inference: Making sure that namespaces and modules have their members populated. The semantic analysis would already discover them, so it was just a matter of looking them up in the right scope during the resolve step.
Test updated.
> feat(core): populate members of namespaces and modules

- crates/biome_js_analyze/src/lint/style/use_naming_convention.rs
Following some discussions on Discord, this PR improves the docs for the `conventions` option.
> docs(useNamingConvention): improve description of conventions

- crates/biome_js_analyze/src/lint/nursery/use_consistent_object_definition.rs
- packages/@biomejs/biome/configuration_schema.json
I left my reasoning [here](https://github.com/biomejs/biome/issues/4816#issuecomment-2870063333): 
> I wonder about default value for this rule. Right now rule uses "explicit" syntax, but given that:
> 
> * Eslint equivalent rule has default option set to always use shorthand.
> * Popular Eslint configs such as [Airbnb](https://github.com/search?q=repo%3Aairbnb%2Fjavascript+object-shorthand&type=code) and  [Antfu](https://github.com/search?q=repo%3Aantfu%2Feslint-config%20object-shorthand&type=code) also use shorthand by default.
> 
> Should default option be switched from "explicit" to "shorthand", because thats what most users would expect?
I consider this a fix, because even original changelog entry for this lint rule says, default should be shorthand. …
> fix(linter): change default syntax from explicit to shorthand for useConsistentObjectDefinition

- .changeset/light-things-relate.md
- crates/biome_css_analyze/src/assist/source/use_sorted_properties.rs
- crates/biome_css_analyze/tests/quick_test.rs
- crates/biome_css_analyze/tests/specs/source/useSortedProperties/invalid.css.snap
- crates/biome_css_analyze/tests/specs/source/useSortedProperties/valid.css
- crates/biome_css_analyze/tests/specs/source/useSortedProperties/valid.css.snap
closes: #6105 
Skip the unknown properties when [`useSortedProeprties`](https://next.biomejs.dev/assist/actions/use-sorted-properties/) check. 
I add test case under `crates/biome_css_analyzer` and add a quick_test file.
> fix(analyzer): useSortedProperties should skip unknown properties

- crates/biome_configuration/src/lib.rs
- crates/biome_lsp/src/extension_settings.rs
- crates/biome_lsp/src/session.rs
During the initialisation process of the workspace from LSP, the root directory of the project is overriden by the specified configuration path. I believe it's not intended when we use any custom configuration file, and replaced the logic to always use the current working directory even if the configuration path is provided.
Manually tested with VS Code.
> fix(lsp): custom configuration path should not override the working directory

- crates/biome_module_graph/src/module_graph.rs
- crates/biome_parser/src/lib.rs
- crates/biome_service/src/workspace/server.rs
- crates/biome_service/src/workspace/watcher.rs
- crates/biome_test_utils/src/lib.rs
Whenever we insert a file using `open_file_internal()`, we call `update_service_data()` afterwards. But `update_service_data()` called `update_module_graph()`, which was responsible for retrieving the document so we can process it there. This was wasteful, because `open_file_internal()` just inserted the document, and now we need to look it up again. So instead of doing these lookups, we can just pass the root for processing directly.
Also, I found that the watcher explicitly called `update_service_data()` even though this was also done through the call to `open_file_by_watcher()` right above it. So I think the watcher was doing some work twice there.
Tests should remain green.
> refactor: avoid unnecessary document retrieval

- Cargo.lock
- crates/biome_configuration/src/overrides.rs
- crates/biome_configuration/src/plugins.rs
- crates/biome_configuration/tests/invalid/overrides/incorrect_key.json.snap
- crates/biome_plugin_loader/Cargo.toml
- crates/biome_plugin_loader/src/diagnostics.rs
- crates/biome_plugin_loader/src/plugin_cache.rs
- crates/biome_service/src/settings.rs
- crates/biome_service/src/snapshots/biome_service__workspace__tests__diagnostics___project__a.ts.snap
- crates/biome_service/src/snapshots/biome_service__workspace__tests__diagnostics___project__lib__b.ts.snap
- crates/biome_service/src/workspace.tests.rs
- crates/biome_service/src/workspace/server.rs
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
- packages/@biomejs/biome/configuration_schema.json
Related: https://github.com/biomejs/biome/issues/5953
Allow add plugins that runs only in certain files.
```
{
"plugins": [
"./biome-rules/custom-card-rule.grit",
// ...
],
"overrides": [{
"includes": ["src/routes/**"],
"plugins": ["./biome-rules/no-components-in-routes.grit"]
}]
}
```
1. crates/biome_configuration/src/overrides.rs : add a new field `plugins` to overrides settings
2. crates/biome_service/src/settings.rs : 
- add method `as_all_plugins`, traverse settings to collect all plugins (including global plugins and all plugins in overrides)
- add method `as_plugins`, take `path` as parameter, this method return applicable plugins for the path. (including global plugins and matched plugins in overrides)
3. crates/biome_plugin_loader/src/plugin_cache.rs
- change method …
> feat: add plugins to override config

- .changeset/moody-cobras-win.md
- crates/biome_js_analyze/tests/specs/correctness/noUnusedImports/issue6144.ts
- crates/biome_js_analyze/tests/specs/correctness/noUnusedImports/issue6144.ts.snap
- crates/biome_js_semantic/src/events.rs
Fix https://github.com/biomejs/biome/issues/6144
This adds an exception to the semantic model to avoid binding a parameter type to a parameter.
I added several tests.
> fix(js-semantic): don't bind the parameter to its parameter

- crates/biome_html_formatter/src/comments.rs
- crates/biome_html_formatter/src/context.rs
This code never runs. It was probably the result of copying code from other formatters.
> chore(format/html): remove dead code around comment formatting

- crates/biome_service/src/workspace/scanner.rs
Looks like we had two definitions of the scanner's ignore list lying around :) Removed one.
Everything should remain green.
> fix(core): use single ignore list for scanner

- crates/biome_js_type_info/src/type_info/literal.rs
This is a very small change that basically check if the number has a numeric separator `_` before calling `replace` that allocates a string.
Also, I improved the prefix detection using a match.
No regression should be observed.
> refactor(js_type_info): avoid allocating a String upon number parsing

- crates/biome_service/src/projects.rs
- crates/biome_service/src/workspace/scanner.rs
- crates/biome_service/src/workspace/server.rs
We shouldn't be cloning the settings so much when doing ignore checks.
> perf: perform fewer clones for ignore checks

- crates/biome_js_type_info/src/flattening.rs
- crates/biome_js_type_info/src/format_type_info.rs
- crates/biome_js_type_info/src/type_info.rs
- crates/biome_module_graph/src/js_module_info/binding.rs
- crates/biome_module_graph/src/js_module_info/collector.rs
- crates/biome_module_graph/src/js_module_info/scope.rs
- crates/biome_module_graph/tests/snapshots/test_resolve_merged_namespace_with_type.snap
- crates/biome_module_graph/tests/snapshots/test_resolve_merged_types.snap
- crates/biome_module_graph/tests/snapshots/test_resolve_recursive_looking_country_info.snap
- crates/biome_module_graph/tests/spec_tests.rs
Improves the merging of namespaces with types and values in the same scope. Note that multiple namespaces of the same name are still not merged, but this is still an improvement over what we did, as the snapshots show.
Test added, snapshots updated.
> feat(core): improved namespace merging

- .changeset/four-needles-bow.md
- crates/biome_js_analyze/src/lint/correctness/use_hook_at_top_level.rs
- crates/biome_js_analyze/src/react/components.rs
- crates/biome_js_analyze/tests/specs/correctness/useHookAtTopLevel/invalidWrapped.js
- crates/biome_js_analyze/tests/specs/correctness/useHookAtTopLevel/invalidWrapped.js.snap
- crates/biome_js_analyze/tests/specs/correctness/useHookAtTopLevel/validNestedObjectProp.js
- crates/biome_js_analyze/tests/specs/correctness/useHookAtTopLevel/validNestedObjectProp.js.snap
Fixes for `useHookAtTopLevel` rule.
1. It didn't detect `memo/forwardRef` wrappers (#6110), example:
```js
const TestMemo = memo(
forwardRef((props, ref) => {
useEffect(() => {
const [test, setTest] = useState(1); // didn't complain about this hook call.
}, []);
return <div ref={ref}>test</div>;
})
);
```
2. It didn't handle property accessors when building "light version" of the control flow (#6093):
```js
function ReactComponent() {
const testObj = {
get print() {
return "hello" // considered this as a return from component
}
}
const callback = useCallback(() => {}, [])
return <></>
}
```
3. React Components detection mod received further improvements and tests.
Fixes #6110 and #6093.
Tests are included.
> fix: rule `useHookAtTopLevel` issues, improve react components detection

- CONTRIBUTING.md
`biome.lspBin` was deprecated in favor of `biome.lsp.bin`.
This PR fixes the contributing guide.
> docs(contributing): biome.lspBin to biome.lsp.bin

- crates/biome_js_analyze/src/lint/correctness/no_private_imports.rs
- crates/biome_js_type_info/src/helpers.rs
- crates/biome_js_type_info/src/type_info.rs
- crates/biome_module_graph/src/format_module_graph.rs
- crates/biome_module_graph/src/js_module_info.rs
- crates/biome_module_graph/src/js_module_info/binding.rs
- crates/biome_module_graph/src/js_module_info/collector.rs
- crates/biome_module_graph/src/js_module_info/scope.rs
- crates/biome_module_graph/src/js_module_info/scoped_resolver.rs
- crates/biome_module_graph/src/js_module_info/visitor.rs
- crates/biome_module_graph/src/module_graph.rs
- crates/biome_module_graph/tests/snap/mod.rs
- crates/biome_module_graph/tests/snapshots/test_export_const_type_declaration_with_namespace.snap
- crates/biome_module_graph/tests/snapshots/test_export_default_function_declaration.snap
- crates/biome_module_graph/tests/snapshots/test_export_referenced_function.snap
- crates/biome_module_graph/tests/snapshots/test_resolve_export_type_referencing_imported_type.snap
- crates/biome_module_graph/tests/snapshots/test_resolve_export_types.snap
- crates/biome_module_graph/tests/snapshots/test_resolve_exports.snap
- crates/biome_module_graph/tests/snapshots/test_resolve_merged_namespace_with_type.snap
- crates/biome_module_graph/tests/snapshots/test_resolve_merged_types.snap
- crates/biome_module_graph/tests/snapshots/test_resolve_promise_export.snap
- crates/biome_module_graph/tests/snapshots/test_resolve_promise_from_imported_function_returning_imported_promise_type.snap
- crates/biome_module_graph/tests/snapshots/test_resolve_promise_from_imported_function_returning_reexported_promise_type.snap
- crates/biome_module_graph/tests/snapshots/test_resolve_react_types.snap
- crates/biome_module_graph/tests/snapshots/test_resolve_recursive_looking_country_info.snap
- crates/biome_module_graph/tests/snapshots/test_resolve_recursive_looking_vfile.snap
- crates/biome_module_graph/tests/spec_tests.rs
This PR revises slightly how we track exported symbols. The reason is that the `export = someNamespace` syntax can be used not only to export the namespace itself, it also serves to define exports for all the members of `someNamespace`. This can be clearly witnessed in React exports, which effectively does something like this:
```ts
export = React;
declare namespace React {
function useCallback<T extends Function>(callback: T, deps: DependencyList): T;
// All the other functions.
}
```
In this example, `useCallback()` needs to be importable through `import { useCallback } from "react";` _as well as_ be usable like this:
```ts
import React from "react";
React.useCallback // <- Same symbol.
```
This required a bit of a refactoring, since at the point where we used to register the export as …
> feat(core): resolve React symbols

- crates/biome_cli/tests/commands/lint.rs
- crates/biome_cli/tests/snapshots/main_commands_lint/linter_can_resolve_imported_symbols.snap
- crates/biome_js_type_info/CONTRIBUTING.md
- crates/biome_js_type_info/src/resolver.rs
- crates/biome_js_type_info/src/type_info.rs
- crates/biome_js_type_info_macros/src/resolvable_derive.rs
- crates/biome_module_graph/src/js_module_info/scoped_resolver.rs
- crates/biome_module_graph/tests/snapshots/test_resolve_react_types.snap
Fixes an issue that could lead to panics if the scoped resolver imported a type from another module and then tried to resolve one of its type qualifiers from the scope of its own module.
Test added.
> fix(core): strip qualifiers in scoped resolver

- crates/biome_js_analyze/Cargo.toml
- crates/biome_js_analyze/src/lint/correctness/no_private_imports.rs
- crates/biome_js_analyze/tests/specs/correctness/noPrivateImports/default_package.js
- crates/biome_js_analyze/tests/specs/correctness/noPrivateImports/default_package.js.snap
- crates/biome_js_analyze/tests/specs/correctness/noPrivateImports/valid.js
- crates/biome_js_analyze/tests/specs/correctness/noPrivateImports/valid.js.snap
- crates/biome_resolver/src/lib.rs
Fixes #6214.
@minht11 I've made the decision to restrict `noPrivateImports` to relative imports only to prevent this. This means path aliases are excluded too, which to me feels right, because if you set up an alias for those paths, you probably _intent_ for their exports to be available everywhere, but let me know your thoughts on this!
Tests updated.
> fix(linter): exclude dependencies from `noPrivateImports`

- .changeset/grumpy-eels-create.md
- crates/biome_js_analyze/src/assist/source/organize_imports.rs
- crates/biome_js_analyze/tests/specs/source/organizeImports/issue6211.js
- crates/biome_js_analyze/tests/specs/source/organizeImports/issue6211.js.snap
- crates/biome_js_analyze/tests/specs/source/organizeImports/mergeable-with_header.js
- crates/biome_js_analyze/tests/specs/source/organizeImports/mergeable-with_header.js.snap
- crates/biome_js_analyze/tests/specs/source/organizeImports/mergeable-with_leading_newline.js
- crates/biome_js_analyze/tests/specs/source/organizeImports/mergeable-with_leading_newline.js.snap
- crates/biome_js_analyze/tests/specs/source/organizeImports/mergeable_export.ts.snap
- crates/biome_js_analyze/tests/specs/source/organizeImports/mergeable_imports.ts.snap
- crates/biome_js_analyze/tests/specs/source/organizeImports/mergeable_unsorted_imports.ts.snap
Fix https://github.com/biomejs/biome/issues/6211
The issue comes from merging the first import of the file with another one and moving the result after a third import.
This only arises when the first import has no leading trivia.
To fix the issue, we now keep the leading newline of the second import and remove it only if the merged import is placed at the start of the file and the previous first import had no leading newline.
I had to reverse the traversal order to merge imports in order to ensure that the merged of the first import with another import has the same slot index as the first import.
This is required to have proper trivia handling.
I added three tests and updated the snapshots.
> fix(organizeImports): emit correct code when merging imports

- .changeset/curvy-ducks-judge.md
- crates/biome_js_analyze/src/lint/style/no_parameter_assign.rs
- crates/biome_js_analyze/tests/specs/style/noParameterAssign/invalid.jsonc.snap
- crates/biome_js_analyze/tests/specs/style/noParameterAssign/invalidFixUnsafe.js.snap
- crates/biome_js_analyze/tests/specs/style/noParameterAssign/parameterMutationDenyInvalid.js
- crates/biome_js_analyze/tests/specs/style/noParameterAssign/parameterMutationDenyInvalid.js.snap
- crates/biome_js_analyze/tests/specs/style/noParameterAssign/parameterMutationDenyInvalid.options.json
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
- packages/@biomejs/biome/configuration_schema.json
Added a new `propertyAssignment` option to the `noParameterAssign` rule.
This option allows to configure whether property assignments on function parameters are permitted.
By default, `propertyAssignment` is set to `allow`.
Setting it to `deny` enforces stricter immutability by disallowing property mutations on function parameters.
closes #5205
> feat(biome_js_analyze): adds a new propertyAssignment option to the noParameterAssign rule.

- .changeset/muddy-mules-meander.md
- crates/biome_js_analyze/src/lint/nursery/no_misused_promises.rs
- crates/biome_js_analyze/src/services/typed.rs
- crates/biome_js_analyze/tests/quick_test.rs
- crates/biome_js_analyze/tests/specs/nursery/noMisusedPromises/checksConditionalsInvalid.ts
- crates/biome_js_analyze/tests/specs/nursery/noMisusedPromises/checksConditionalsInvalid.ts.snap
- crates/biome_js_analyze/tests/specs/nursery/noMisusedPromises/checksSpreadsInvalid.ts
- crates/biome_js_analyze/tests/specs/nursery/noMisusedPromises/checksSpreadsInvalid.ts.snap
- crates/biome_js_analyze/tests/specs/nursery/noMisusedPromises/checksVoidReturnInvalid.ts
- crates/biome_js_analyze/tests/specs/nursery/noMisusedPromises/checksVoidReturnInvalid.ts.snap
- crates/biome_js_analyze/tests/specs/nursery/noMisusedPromises/checksVoidReturnValid.ts
- crates/biome_js_analyze/tests/specs/nursery/noMisusedPromises/checksVoidReturnValid.ts.snap
- crates/biome_js_type_info/src/flattening.rs
- crates/biome_js_type_info/src/format_type_info.rs
- crates/biome_js_type_info/src/globals.rs
- crates/biome_js_type_info/src/local_inference.rs
- crates/biome_js_type_info/src/type_info.rs
- crates/biome_js_type_info/tests/snapshots/infer_flattened_type_from_direct_promise_instance.snap
- crates/biome_js_type_info/tests/snapshots/infer_resolved_type_from_direct_promise_instance.snap
- crates/biome_module_graph/src/js_module_info/collector.rs
- crates/biome_module_graph/src/js_module_info/module_resolver.rs
- crates/biome_module_graph/tests/snapshots/test_resolve_export_type_referencing_imported_type.snap
- crates/biome_module_graph/tests/snapshots/test_resolve_promise_from_imported_function_returning_imported_promise_type.snap
- crates/biome_module_graph/tests/snapshots/test_resolve_promise_from_imported_function_returning_reexported_promise_type.snap
This adds the detection of callbacks that return `Promise`s in places where conditional-returning or `void`-returning callback was expected. This gives us rough parity with ESLint's `typescript-eslint`.
Fixes #5541.
Tests added and snapshots updated.
> feat(linter): detect `Promise`-returning callbacks in `noMisusedPromises`

- crates/biome_parser/src/token_source.rs
- crates/biome_parser/src/tree_sink.rs
The current trivia attachment logic in TreeSink tries to attach a trivia as soon as when the current text position match the trivia's offset. This leads to problem when a trivia is attached as leading trivia to a token precedes it. For example, given this token set:
```
SEQUENCE_START@0:0
DASH@0:1
WHITESPACE@1:2
PLAIN_LITERAL@2:9
SEQUENCE_END@9:9
NEWLINE@9:10
EOF@10:10
```
which corresponds to 
```yaml
- literal
```
The TreeSink will attempt to attach `NEWLINE` token as `SEQUENCE_END`'s leading trivia, which in turns caused a whole host of problem with rowan.
This PR tries to fix this by adding a new condition to the trivia check, which checks for the end offset of the current token and the trivia to determine if this trivia is really this token's leading trivia
All tests should still be …
> fix(biome_parser): trivia placement for zero-width tokens

- crates/biome_js_type_info/src/globals.rs
- crates/biome_js_type_info/src/type_store.rs
Small performance improvement for type-aware rules, since we perform more regular lookups into the global resolver now.
In one of the Vercel repositories, this brings down the time for running `noMisusedPromises` from 16s to 15s. `noFloatingPromises` seems less affected and already took 15s.
> perf: use `TypeStore` in global resolver

- crates/biome_js_analyze/src/lint/correctness/no_private_imports.rs
- crates/biome_js_analyze/tests/specs/correctness/noPrivateImports/.gitignore
- crates/biome_js_analyze/tests/specs/correctness/noPrivateImports/node_modules/external-package/index.js
- crates/biome_js_analyze/tests/specs/correctness/noPrivateImports/node_modules/external-package/index.js.snap
- crates/biome_js_analyze/tests/specs/correctness/noPrivateImports/package.json
- crates/biome_js_analyze/tests/specs/correctness/noPrivateImports/valid.js
- crates/biome_js_analyze/tests/specs/correctness/noPrivateImports/valid.js.snap
Really fix #6214.
Added fixture data so the test case really resolves to a dependency. Double-checked that reverting the fix fails the test.
> fix(linter): don't flag imports from dependencies

- .changeset/beige-otters-divide.md
- crates/biome_js_analyze/src/lint/complexity/no_useless_escape_in_regex.rs
- crates/biome_js_analyze/tests/specs/complexity/noUselessEscapeInRegex/invalid.js.snap
- crates/biome_js_analyze/tests/specs/complexity/noUselessEscapeInRegex/valid.js
- crates/biome_js_analyze/tests/specs/complexity/noUselessEscapeInRegex/valid.js.snap
Fix https://github.com/biomejs/biome/issues/6331
> fix(lint/noUselessEscapeInRegex): don't report `\k` as useless

- .github/workflows/release.yml
- crates/biome_formatter_test/src/prettier/package.json
- package.json
- packages/@biomejs/cli-darwin-arm64/package.json
- packages/@biomejs/cli-darwin-x64/package.json
- packages/@biomejs/cli-linux-arm64-musl/package.json
- packages/@biomejs/cli-linux-arm64/package.json
- packages/@biomejs/cli-linux-x64-musl/package.json
- packages/@biomejs/cli-linux-x64/package.json
- packages/@biomejs/cli-win32-arm64/package.json
- packages/@biomejs/cli-win32-x64/package.json
- packages/@biomejs/js-api/package.json
- packages/@biomejs/wasm-bundler/package.json
- packages/@biomejs/wasm-nodejs/package.json
- packages/@biomejs/wasm-web/package.json
- merged the two jobs into one
- the publish command is done by `changeset publish` (tested it locally, and it works as expected)
- fixed the manual upload of the artefacts, where it was using `biome-` instead of `cli-`
Tested only the publish part. For uploading the artefacts, we should trigger a new release. It will need a new changeset
> ci: unify release and use changeset publish for tag creation

- .changeset/common-melons-see.md
- crates/biome_css_analyze/src/keywords.rs
- crates/biome_css_analyze/tests/specs/correctness/noUnknownPseudoClass/valid.css
- crates/biome_css_analyze/tests/specs/correctness/noUnknownPseudoClass/valid.css.snap
- crates/biome_css_analyze/tests/specs/correctness/noUnknownPseudoElement/valid.css
- crates/biome_css_analyze/tests/specs/correctness/noUnknownPseudoElement/valid.css.snap
Fixes #6360 
Added the following pseudo classes and elements:
- `:open`
- `::details-content`
- `::prefix`
- `::search-text`
- `::suffix`
ref: https://drafts.csswg.org/css-pseudo-4/
ref: https://drafts.csswg.org/selectors/
Updated snapshot tests.
> fix(lint): add missing known pseudo classes and elements

- .changeset/long-hairs-guess.md
- crates/biome_aria_metadata/build.rs
- crates/biome_aria_metadata/src/lib.rs
- crates/biome_js_analyze/tests/specs/a11y/useValidLang/valid.jsx
- crates/biome_js_analyze/tests/specs/a11y/useValidLang/valid.jsx.snap
Resolves #6341
Added `nb` and `nn` to the language list.
> fix(lint): valid norwegian language tags

- .changeset/shiny-groups-leave.md
- crates/biome_js_analyze/src/lint/correctness/use_exhaustive_dependencies.rs
- crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/checkHooksImportedFromReact.js.snap
- crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/customHook.js.snap
- crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/extraDependenciesInvalid.js.snap
- crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/ignoredDependencies.js.snap
- crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/issue1931.js.snap
- crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/issue6278.js
- crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/issue6278.js.snap
- crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/missingDependenciesInvalid.jsx.snap
- crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/preactHooks.js.snap
- crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/stableResultInvalid.js.snap
Fixes #6278 
The missing dependency was duplicated in the code fix if it is used multiple times in the hook. A single diagnostic of the rule is only for **one** dependency to add, so we should add only one instance of it.
I also improved the diagnostics slightly.
Snapshot updated.
> fix(lint): deduplicate missing dependencies in useExhaustiveDependencies

- packages/@biomejs/js-api/README.md
Fix the JavaScript API example. The `openProject()` method returns an `OpenProjectResult`: `{ projectKey: 2, scanKind: "none" }`. But the `formatContent()` and `lintContent()` methods only take the `projectKey` as a parameter.
```
/home/regseb/testcase/node_modules/@biomejs/js-api/dist/wasm.js:94
return new WasmError(e);
^
WasmError
at WasmError.fromError (/home/regseb/testcase/node_modules/@biomejs/js-api/dist/wasm.js:94:16)
at wrapError (/home/regseb/testcase/node_modules/@biomejs/js-api/dist/wasm.js:103:22)
at Biome.applyConfiguration (/home/regseb/testcase/node_modules/@biomejs/js-api/dist/index.js:50:40)
at file:///home/regseb/testcase/index.js:11:7 {
stackTrace: Error: Error: invalid type: JsValue(Object({"projectKey":2,"scanKind":"none"})), expected a nonzero usize
at …
```
> docs: fix JS API example

- .changeset/quick-nails-sniff.md
- crates/biome_js_analyze/src/utils.rs
- crates/biome_js_analyze/tests/specs/suspicious/noSelfCompare/issue6377.js
- crates/biome_js_analyze/tests/specs/suspicious/noSelfCompare/issue6377.js.snap
Fixes #6377 
Fixed that `biome_js_analyze::utils::is_node_equal` didn't compare two nodes when these have a common part at the start in a syntax node.
Added snapshot tests.
> fix(lint): false positive on noSelfCompare for additional arguments

- crates/biome_js_analyze/src/lib.rs
- crates/biome_js_type_info/src/type_store.rs
- crates/biome_module_graph/src/js_module_info/module_resolver.rs
- crates/biome_module_graph/tests/spec_tests.rs
A small optimisation to avoid unnecessary reallocations when running the inference on the module resolver.
Also made the `run_inference()` method itself private and run it directly upon construction. It is required to be called anyway, and may only be called once, so what better way to enforce that?
> perf: preallocate type store

- .changeset/chubby-carrots-divide.md
- crates/biome_js_analyze/src/lint/complexity/no_useless_fragments.rs
- crates/biome_js_analyze/tests/specs/complexity/noUselessFragments/issue_6391.jsx
- crates/biome_js_analyze/tests/specs/complexity/noUselessFragments/issue_6391.jsx.snap
Fixes #6391
React trims a "padding" whitespaces inside a element when it contains **at least one line break**; whitespaces without line breaks will never be trimmed and should be considered as a valid text node.
For example, the following code:
```jsx
<> </>
```
is equivalent to:
```jsx
<>{" "}</>
```
There is the same logic in `react/jsx-no-unnecessary-fragment`: https://github.com/jsx-eslint/eslint-plugin-react/blob/f2869fd6dc76ceb863c5e2aeea8bf4d392508775/lib/rules/jsx-no-useless-fragment.js#L116-L125
> fix(lint): noUselessFragments should ignore fragments with untrimmed whitespaces

- .github/workflows/release.yml
Related: https://github.com/biomejs/setup-biome/issues/268
The biomejs/setup-biome action expects the tag of release is named `@biomejs/biome@X.Y.Z` but got `@biomejs/biome@vX.Y.Z`. For v2.0.4, I updated the tag manually.
It will produce a correct tag in the next release
> ci: fix tag name on creating a release

- .changeset/modern-meals-end.md
- crates/biome_grit_patterns/src/grit_context.rs
- crates/biome_grit_patterns/src/grit_node_patterns.rs
- crates/biome_grit_patterns/tests/quick_test.rs
- crates/biome_grit_patterns/tests/specs/ts/import_patterns.grit
- crates/biome_grit_patterns/tests/specs/ts/import_patterns.snap
- crates/biome_grit_patterns/tests/specs/ts/import_patterns.ts
closes: #5801 
Align the biome grit patten behaviour with griftql.
i am not sure if my change is valid, but it seems the bug was caused by the pattern of grit in `biome_grit_patterns` don't match the import kind, so i add the judge for that case to align the behaviour with `gritql`
I add the case under `crates/biome_grit_patterns`.
> fix: gritql mismatch import pattern

- .changeset/conditional-clauses-check.md
- crates/biome_js_analyze/tests/specs/nursery/noFloatingPromises/01_invalid.ts
- crates/biome_js_analyze/tests/specs/nursery/noFloatingPromises/01_invalid.ts.snap
- crates/biome_js_analyze/tests/specs/nursery/noFloatingPromises/04_invalid.ts
- crates/biome_js_analyze/tests/specs/nursery/noFloatingPromises/04_invalid.ts.snap
- crates/biome_js_analyze/tests/specs/nursery/noFloatingPromises/invalid.ts
- crates/biome_js_analyze/tests/specs/nursery/noFloatingPromises/invalid.ts.snap
- crates/biome_js_type_info/src/local_inference.rs
Type inference is now able to handle ternary conditions in type aliases.
Note that we don't attempt to evaluate the condition itself. The resulting type
is simply a union of both conditional outcomes.
```ts
type MaybeResult<T> = T extends Function ? Promise<string> : undefined;
// We can now detect this function _might_ return a `Promise`:
function doStuff<T>(input: T): MaybeResult<T> { /* ... */ }
```
> fix(core): handle ternary in type alias

- .changeset/funky-functions-follow.md
- crates/biome_js_analyze/src/lint/nursery/use_exhaustive_switch_cases.rs
- crates/biome_js_analyze/tests/specs/nursery/noFloatingPromises/09_invalid.ts
- crates/biome_js_analyze/tests/specs/nursery/noFloatingPromises/09_invalid.ts.snap
- crates/biome_js_type_info/src/flattening/expressions.rs
- crates/biome_js_type_info/src/flattening/intersections.rs
- crates/biome_js_type_info/src/format_type_info.rs
- crates/biome_js_type_info/src/local_inference.rs
- crates/biome_js_type_info/src/type_info.rs
- crates/biome_js_type_info/tests/snapshots/infer_flattened_type_from_chained_invocation_of_promise_returning_function.snap
- crates/biome_js_type_info/tests/snapshots/infer_flattened_type_from_double_chained_invocation_of_promise_returning_function.snap
- crates/biome_js_type_info/tests/snapshots/infer_flattened_type_of_destructured_interface_field.snap
- crates/biome_js_type_info/tests/snapshots/infer_resolved_type_from_chained_invocation_of_promise_returning_function.snap
- crates/biome_js_type_info/tests/snapshots/infer_resolved_type_from_double_chained_invocation_of_promise_returning_function.snap
- crates/biome_js_type_info/tests/snapshots/infer_type_of_function_with_destructured_arguments.snap
- crates/biome_module_graph/tests/snapshots/test_export_referenced_function.snap
- crates/biome_module_graph/tests/snapshots/test_resolve_export_types.snap
- crates/biome_module_graph/tests/snapshots/test_resolve_exports.snap
- crates/biome_module_graph/tests/snapshots/test_resolve_promise_export.snap
- crates/biome_module_graph/tests/snapshots/test_resolve_recursive_looking_country_info.snap
- crates/biome_module_graph/tests/spec_tests.rs
Type inference can now infer the return types of functions and methods without
annotations.
```ts
const sneakyObject = {
doSomething() {
return Promise.resolve("This is a floating promise!");
},
};
// We can now detect that `doSomething()` returns a `Promise`.
sneakyObject.doSomething();
```
As part of this, we also explicitly track functions that return `void`.
Test added, snapshots updated.
> fix(core): infer method return types

- .changeset/plenty-bananas-throw.md
- crates/biome_cli/tests/snapshots/main_cases_overrides_max_file_size/overrides_files_max_size_too_large_limit_check.snap
- crates/biome_cli/tests/snapshots/main_cases_overrides_max_file_size/overrides_files_max_size_too_large_limit_format.snap
- crates/biome_cli/tests/snapshots/main_commands_check/file_too_large.snap
- crates/biome_cli/tests/snapshots/main_commands_check/file_too_large_cli_limit.snap
- crates/biome_cli/tests/snapshots/main_commands_check/file_too_large_config_limit.snap
- crates/biome_cli/tests/snapshots/main_commands_ci/file_too_large.snap
- crates/biome_cli/tests/snapshots/main_commands_ci/file_too_large_cli_limit.snap
- crates/biome_cli/tests/snapshots/main_commands_ci/file_too_large_config_limit.snap
- crates/biome_cli/tests/snapshots/main_commands_format/file_too_large.snap
- crates/biome_cli/tests/snapshots/main_commands_format/file_too_large_cli_limit.snap
- crates/biome_cli/tests/snapshots/main_commands_format/file_too_large_config_limit.snap
- crates/biome_cli/tests/snapshots/main_commands_lint/file_too_large.snap
- crates/biome_cli/tests/snapshots/main_commands_lint/file_too_large_cli_limit.snap
- crates/biome_cli/tests/snapshots/main_commands_lint/file_too_large_config_limit.snap
- crates/biome_service/src/diagnostics.rs
Fixes #6559 
When a file is larger than the limit, the CLI emits a diagnostic. The error message there was outdated, and referred the missing option `files.ignore` that was removed in 2.0.
> fix(cli): replace `files.ignore` with `files.includes` in the error message

- .changeset/busy-zebras-smash.md
- .changeset/hot-dragons-count.md
- crates/biome_lsp/src/capabilities.rs
- crates/biome_lsp/src/handlers/analysis.rs
- crates/biome_lsp/src/server.rs
- crates/biome_lsp/src/server.tests.rs
- crates/biome_lsp/src/session.rs
- crates/biome_service/src/projects.rs
This PR closes two bugs.
Closes https://github.com/biomejs/biome/issues/6287
To fix this bug, I had to apply the following changes:
- when loading the configuration, now we check if the configuration folder is empty. If it is empty, and the editor require the configuration, when we return early with `ConfigurationStatus::Missed`.
- the language server request `textDocument/codeAction` must be registered dynamically. We already do so with formatting requests too.
The second bug was related to how we compute the code actions to provide to the editors. I must admit that there was a lot of confusion on my part (and possibly others') in understanding the feature and correctly applying it to the code.
When the client requests `textDocument/codeAction`, we simply need to provide the code actions …
> fix(lsp): require config and code actions

- .changeset/large-showers-leave.md
- crates/biome_js_analyze/src/lint/correctness/no_unused_imports.rs
- crates/biome_js_analyze/tests/specs/correctness/noUnusedImports/issue_4677_jsdoc.js
- crates/biome_js_analyze/tests/specs/correctness/noUnusedImports/issue_4677_jsdoc.js.snap
https://github.com/biomejs/biome/pull/5698 fixed the majority of https://github.com/biomejs/biome/issues/4677.
An unhandled edge case is exported function.
```
// Some comment
export function exportedFunction {}
```
In this case, the comment belongs to `JsExport` instead of `AnyJsDeclaration`. This PR fixes the edge case.
> fix(biome_js_analyze): add JsExport to be walked by JsDocTypeCollectorVisitior

- crates/biome_js_analyze/src/lint/nursery/no_floating_promises.rs
Removes outdated disclaimer on `noFloatingPromises`.
N/A
> chore: remove disclaimer on `noFloatingPromises`

- .changeset/modern-turtles-exist.md
- crates/biome_js_analyze/src/lint/correctness/no_unused_imports.rs
- crates/biome_js_analyze/tests/specs/correctness/noUnusedImports/issue_4677_jsdoc.js
- crates/biome_js_analyze/tests/specs/correctness/noUnusedImports/issue_4677_jsdoc.js.snap
This PR fixed the edge case mentioned by @arendjr in https://github.com/biomejs/biome/pull/6565#pullrequestreview-2965088544.
The biome playground was very helpful in identifying the missing js syntax.
> fix(biome_js_analyze): fix JsDocTypeCollectorVisitior to also walk on JsStaticMemberAssignment

- crates/biome_js_analyze/src/lint/nursery/no_magic_numbers.rs
Currently website builds are failing as the doc comment of the `noMagicNumbers` rule has some code inside and it produces invalid MDX. This pull request resolves it by wrapping them with backquotes.
Deploy log: https://app.netlify.com/projects/biomejs/deploys/685eb8e91d147700080c8945
cc @vladimir-ivanov 
Website builds should back green.
> chore(lint): fix document of the `noMagicNumbers` rule that produces invalid MDX

- crates/biome_rowan/src/ast/mod.rs
From the rowan docs:
```
//! In rowan, syntax trees are transient objects. That means that we create
//! trees when we need them, and tear them down to save memory. In this
//! architecture, hanging on to a particular syntax node for a long time is
//! ill-advisable, as that keeps the whole tree resident.
//!
//! Instead, we provide a [`SyntaxNodePtr`] type, which stores information about
//! the _location_ of a particular syntax node in a tree. It's a small type
//! which can be cheaply stored, and which can be resolved to a real
//! [`SyntaxNode`] when necessary.
//!
//! We also provide an [`AstNode`] trait for typed AST wrapper APIs over rowan
//! nodes.
```
It would be nice to have this in `biome_rowan` too! This pr is basically a direct port with `text_range` swapped for …
> feat(core): port SyntaxNodePtr and AstPtr from rowan

- .changeset/targeted-tigers-tango.md
- crates/biome_cli/src/commands/mod.rs
- crates/biome_cli/src/commands/scan_kind.rs
- crates/biome_cli/src/execute/mod.rs
- crates/biome_cli/src/execute/traverse.rs
- crates/biome_cli/tests/cases/monorepo.rs
- crates/biome_cli/tests/snapshots/main_cases_monorepo/should_find_root_when_run_from_nested_dir.snap
- crates/biome_cli/tests/snapshots/main_cases_monorepo/should_find_settings_when_run_from_nested_dir.snap
- crates/biome_cli/tests/snapshots/main_cases_monorepo/should_find_settings_when_targeting_file_in_nested_dir.snap
- crates/biome_cli/tests/snapshots/main_cases_monorepo/should_find_settings_when_targeting_nested_dir.snap
- crates/biome_cli/tests/snapshots/main_cases_monorepo/should_find_settings_when_targeting_parent_of_nested_dir.snap
- crates/biome_cli/tests/snapshots/main_commands_check/check_help.snap
- crates/biome_service/src/configuration.rs
- crates/biome_service/src/diagnostics.rs
- crates/biome_service/src/workspace/scanner.rs
- crates/biome_service/src/workspace/server.rs
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
Implemented a more targeted version of the scanner, which ensures that if you provide file paths to handle on the CLI, the scanner will exclude directories that are not relevant to those paths.
Note that for many commands, such as `biome check` and `biome format`, the file paths to handle are implicitly set to the current working directory if you do not provide any path explicitly. The targeted scanner also works with such implicit paths, which means that if you run Biome from a subfolder, other folders that are part of the project are automatically exempted.
Use cases where you invoke Biome from the root of the project without providing a path, as well as those where project rules are enabled, are not expected to see performance benefits from this.
Fixed #6234.
Fixed #6483.
Fixed #6563. …
> feat(core): targeted file scanner

- .changeset/rebellious-roots-respect.md
- crates/biome_cli/tests/commands/lint.rs
- crates/biome_cli/tests/snapshots/main_commands_lint/should_apply_root_settings_with_stdin_file_path.snap
- crates/biome_cli/tests/snapshots/main_commands_lint/should_apply_root_settings_with_stdin_file_path_and_extended_broken_config.snap
- crates/biome_cli/tests/snapshots/main_commands_lint/should_apply_root_settings_with_stdin_file_path_and_extended_config.snap
- crates/biome_cli/tests/snapshots/main_commands_lint/should_apply_root_settings_with_stdin_file_path_and_extended_non_root_config.snap
- crates/biome_service/src/configuration.rs
If a configuration that did not contain an explicit `root` field extended another configuration that _did_ contain a `root` field, the `root` field was inherited. This is never what we want, and it tripped up configuration loading pretty badly, although it only manifested when checking a file from `stdin`.
Fixes #6616.
Added several test cases to show that `--stdin-file-path` works correctly in various use cases.
> fix(core): fix extending configs with root field

- .changeset/fix_capabilities_dynamic_registration.md
- crates/biome_lsp/src/server.rs
- crates/biome_lsp/src/session.rs
Some LSP capabilities were dynamically registered even if client does not support it, which does not comply with the LSP specification and not expected by clients, for example Neovim (reported in #4994).
> fix(lsp): add missing checks for capability dynamic registration support

- .changeset/old-rice-feel.md
- crates/biome_html_formatter/src/html/auxiliary/self_closing_element.rs
- crates/biome_html_formatter/tests/specs/html/attributes/self-closing.html.snap
- crates/biome_html_formatter/tests/specs/html/attributes/single-quotes.html.snap
- crates/biome_html_formatter/tests/specs/html/self-closing/never.html
- crates/biome_html_formatter/tests/specs/html/self-closing/never.html.snap
- crates/biome_html_syntax/src/element_ext.rs
Closes https://github.com/biomejs/biome/issues/6656
Added new tests
> fix(formatter): void elements with slash

- .changeset/clean-pumas-care.md
- crates/biome_html_formatter/src/html/auxiliary/element.rs
- crates/biome_html_formatter/tests/specs/html/embedded/strict-whitespace-sensitivity/options.json
- crates/biome_html_formatter/tests/specs/html/embedded/strict-whitespace-sensitivity/sensitive-style.html
- crates/biome_html_formatter/tests/specs/html/embedded/strict-whitespace-sensitivity/sensitive-style.html.snap
When this option is set to strict, it means _all_ tags are whitespace sensitive. This means that every element's children tries to "borrow" the parent element's opening tag `>` and closing tag. Normally, this would be "given" to the element list formatter to print, however for verbatim elements like embedded language tags, we avoid invoking the element list formatter entirely in favor of just printing it verbatim.
Now we never borrow these tokens if the element is a verbatim element.
fixes #6453
> fix(format/html): fix mangling of embedded language tags if `whitespaceSensitivity` is `strict`

- .changeset/loud-seals-fry.md
- crates/biome_cli/tests/commands/format.rs
- crates/biome_cli/tests/snapshots/main_commands_format/format_json_trailing_commas_all.snap
- crates/biome_cli/tests/snapshots/main_commands_format/format_json_trailing_commas_overrides_all.snap
- crates/biome_json_formatter/src/context.rs
- crates/biome_json_formatter/src/json/lists/array_element_list.rs
- crates/biome_json_formatter/src/json/lists/member_list.rs
- crates/biome_json_formatter/tests/language.rs
- crates/biome_json_formatter/tests/specs/json/trailing_comma_never/classic.json.snap
- crates/biome_json_formatter/tests/specs/prettier/json/json/array.json.snap
- crates/biome_json_formatter/tests/specs/prettier/json/json/json5.json.snap
- crates/biome_json_formatter/tests/specs/prettier/json/json5-as-json-with-trailing-commas/nested-quotes.json.snap
- crates/biome_json_formatter/tests/specs/prettier/json/range/cross-object-2.json.snap
- packages/@biomejs/biome/configuration_schema.json
Closes https://github.com/biomejs/biome/issues/6537
Now the formatter follows the `formatter.json.trailingCommas` option, even though it might emit an invalid JSON file.
Tests updated
> fix(formatter): trailing commas in json files

- crates/biome_cli/src/execute/process_file.rs
- crates/biome_cli/src/execute/process_file/check.rs
- crates/biome_cli/src/execute/std_in.rs
- crates/biome_cli/src/execute/traverse.rs
- crates/biome_formatter_test/src/spec.rs
- crates/biome_lsp/src/handlers/analysis.rs
- crates/biome_lsp/src/handlers/formatting.rs
- crates/biome_lsp/src/session.rs
- crates/biome_service/src/projects.rs
- crates/biome_service/src/workspace.rs
- crates/biome_service/src/workspace_types.rs
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
Fixed a regression from #6662 that broke the playground. cc @arendjr 
The `FileFeaturesResult` struct has changed in the PR, but it is also exposed to the WASM API and caused a type mismatch. I added a custom implementation of `serde::Serialize`, `serde::Deserialize`, and `schemars::JsonSchema` to keep it the same as before.
Manually tested with the playground
> fix(service): biome/file_features still should return a map instead of an array

- .changeset/bumpy-pots-share.md
- crates/biome_js_analyze/src/lint/complexity/use_date_now.rs
- crates/biome_js_analyze/tests/specs/complexity/useDateNow/invalid.js.snap
Previously, you would get an error like
```
Use Date.now() instead of new Date().getTime.
```
which wasn't technically correct. If you followed the error message literally, you'd end up with `Date.now()()` in your code.
Updated snapshot tests
> fix(lint/complexity/useDateNow): improve error message

- crates/biome_analyze/CONTRIBUTING.md
Follow-up of https://github.com/biomejs/biome/pull/5543
> docs: update analyzer contribution guide

- .changeset/whole-parks-grab.md
- crates/biome_js_analyze/src/assist/source/organize_imports.rs
- crates/biome_js_analyze/tests/specs/source/organizeImports/unsorted-alias.js
- crates/biome_js_analyze/tests/specs/source/organizeImports/unsorted-alias.js.snap
- crates/biome_rule_options/src/organize_imports/import_source.rs
Adds `$` to organize imports `:ALIAS:` group.
Frameworks like:
- [Sveltekit](https://svelte.dev/docs/kit/$lib) `import '$lib'`
- [Fresh](https://fresh.deno.dev/docs/concepts/routes) `import '$fresh/server.ts'`
use them as path alias.
Added new snapshot with all possible aliases
> feat(linter): add $ to organize imports :ALIAS: group

- .changeset/many-weeks-lose.md
- crates/biome_cli/tests/cases/overrides_formatter.rs
- crates/biome_cli/tests/snapshots/main_cases_overrides_formatter/overrides_javascript_formatting_options.snap
- crates/biome_cli/tests/snapshots/main_cases_overrides_formatter/overrides_json_formatting_options.snap
- crates/biome_service/src/settings.rs
Hello, first time contributor here! I opened an issue (#6638) because I noticed formatter overrides weren't being applied for all specified options. Looking through the code I found that `expand` option in JS formatter and `bracketSpacing` in JSON formatter weren't being overwritten when specified in `overrides`.
I followed existing code while fixing this. Although a better solution would be to somehow map over all possible options and apply them, but my Rust experience/knowledge is non-existent so I really don't know how would I do this.
I also wanted to write a test that verifies that override options are being applied, but that test wouldn't automatically cover any options that would be added in the future so it wouldn't catch missing options later on. And since my Rust knowledge is …
> fix(biome-service): override all formatter options with user configured overrides

- .changeset/ignored-iguanodons-ignite.md
- crates/biome_cli/tests/cases/vcs_ignored_files.rs
- crates/biome_cli/tests/snapshots/main_cases_vcs_ignored_files/use_root_gitignore_when_running_from_subdirectory.snap
- crates/biome_fs/src/path.rs
- crates/biome_service/src/workspace/scanner.rs
Fixed [#6646](https://github.com/biomejs/biome/issues/6646): `.gitignore` files are now picked up even when running Biome from a nested directory, or when the ignore file itself is ignored through `files.includes`.
> fix(core): .gitignore is discovered in more scenarios

- .changeset/mighty-tables-grab.md
- crates/biome_js_analyze/src/lint/complexity/no_useless_fragments.rs
- crates/biome_js_analyze/tests/specs/complexity/noUselessFragments/assigments.jsx
- crates/biome_js_analyze/tests/specs/complexity/noUselessFragments/assigments.jsx.snap
- crates/biome_js_analyze/tests/specs/complexity/noUselessFragments/componentFragment.jsx
- crates/biome_js_analyze/tests/specs/complexity/noUselessFragments/componentFragment.jsx.snap
- crates/biome_js_analyze/tests/specs/complexity/noUselessFragments/issue_3668.jsx
- crates/biome_js_analyze/tests/specs/complexity/noUselessFragments/issue_3668.jsx.snap
- crates/biome_js_analyze/tests/specs/complexity/noUselessFragments/issue_3926.jsx
- crates/biome_js_analyze/tests/specs/complexity/noUselessFragments/issue_3926.jsx.snap
- crates/biome_js_analyze/tests/specs/complexity/noUselessFragments/issue_4059.jsx
- crates/biome_js_analyze/tests/specs/complexity/noUselessFragments/issue_4059.jsx.snap
- crates/biome_js_analyze/tests/specs/complexity/noUselessFragments/issue_4639.jsx
- crates/biome_js_analyze/tests/specs/complexity/noUselessFragments/issue_4639.jsx.snap
- crates/biome_js_analyze/tests/specs/complexity/noUselessFragments/issue_6391.jsx
- crates/biome_js_analyze/tests/specs/complexity/noUselessFragments/issue_6391.jsx.snap
- crates/biome_js_analyze/tests/specs/complexity/noUselessFragments/issue_6508.jsx
- crates/biome_js_analyze/tests/specs/complexity/noUselessFragments/issue_6508.jsx.snap
- crates/biome_js_analyze/tests/specs/complexity/noUselessFragments/valid.jsx
- crates/biome_js_analyze/tests/specs/complexity/noUselessFragments/valid.jsx.snap
- crates/biome_js_analyze/tests/specs/complexity/noUselessFragments/withJsxElementInvalid.jsx
- crates/biome_js_analyze/tests/specs/complexity/noUselessFragments/withJsxElementInvalid.jsx.snap
- crates/biome_js_analyze/tests/specs/complexity/noUselessFragments/withJsxExpressionChildValid.jsx
- crates/biome_js_analyze/tests/specs/complexity/noUselessFragments/withJsxExpressionChildValid.jsx.snap
- crates/biome_js_analyze/tests/specs/complexity/noUselessFragments/withJsxTextInvalid.jsx
- crates/biome_js_analyze/tests/specs/complexity/noUselessFragments/withJsxTextInvalid.jsx.snap
Fixes #6688 
Fixed the `noUselessFragments` rule used different logic for shorthand fragments (`<></>`) and Fragment elements (`<Fragment></Fragment>`), causing some false positives only on the latter.
Updated snapshot tests.
> fix(lint/noUselessFragments): apply the same logic for shorthand fragments and Fragment elements

- .changeset/bare-beasts-bark.md
- crates/biome_grit_patterns/tests/specs/ts/bareImport.grit
- crates/biome_grit_patterns/tests/specs/ts/bareImport.snap
- crates/biome_grit_patterns/tests/specs/ts/bareImport.ts
- crates/biome_js_parser/src/syntax/module.rs
Fixed [#6573](https://github.com/biomejs/biome/issues/6573): Grit plugins can now match bare imports.
The following snippet:
```grit
`import $source`
```
will now match:
```ts
import "main.css";
```
Test added
> fix(grit): match bare imports

- .changeset/itchy-bananas-retire.md
- crates/biome_cli/src/commands/ci.rs
- crates/biome_cli/src/commands/mod.rs
- crates/biome_cli/src/diagnostics.rs
- crates/biome_cli/tests/snapshots/main_cases_suppressions/err_when_both_write_and_suppress_are_passed.snap
- crates/biome_cli/tests/snapshots/main_commands_check/fix_suggested_error.snap
- crates/biome_cli/tests/snapshots/main_commands_lint/fix_suggested_error.snap
- crates/biome_cli/tests/snapshots/main_commands_lint/should_error_if_changed_flag_and_staged_flag_are_active_at_the_same_time.snap
- crates/biome_cli/tests/snapshots/main_commands_lint/should_error_if_since_arg_is_used_without_changed.snap
- crates/biome_cli/tests/snapshots/main_commands_migrate/should_suggest_error_incompatible_arguments.snap
The error messages we provided previously in these cases resulted in some confusing error messages, particularly when `--since` was provided without `--changed`. This fixes that.
partially addresses #4225. I didn't link the issue in the changeset because the issue is primarily something different.
> fix(cli): improve error messages when given incompatible arguments

- .changeset/serious-mangos-relate.md
- crates/biome_js_analyze/tests/specs/suspicious/noFocusedTests/valid.js
- crates/biome_js_analyze/tests/specs/suspicious/noFocusedTests/valid.js.snap
- crates/biome_js_syntax/src/expr_ext.rs
fixes #6759
Updated snapshot tests.
> fix(noFocusedTests): fix `fit` false positive

- .changeset/early-pots-win.md
- .github/workflows/release.yml
Follow-up of #6776 
The `dist/` files were still missing in the package. I forgot to specify the target path in the `download-artifact` step.
Release again?
> ci: correct restore path of the artifact

- .changeset/flat-wolves-fall.md
- crates/biome_wasm/src/lib.rs
Fixed that the generated TypeScript type declares as `{ [K in FeatureKind]?: SupportKind }` but the actual value was `Map<FeatureKind, SupportKind>`. I enabled the `serialize_maps_as_objects` option in the serde_wasm_bindgen serializer.
Manually tested with the playground
> fix(wasm): serialize map as a plain object

- .changeset/seven-trains-lie.md
- crates/biome_cli/examples/text_reporter.rs
- crates/biome_cli/src/execute/mod.rs
- crates/biome_cli/src/reporter/github.rs
- crates/biome_cli/src/reporter/gitlab.rs
- crates/biome_cli/src/reporter/json.rs
- crates/biome_cli/src/reporter/junit.rs
- crates/biome_cli/src/reporter/mod.rs
- crates/biome_cli/src/reporter/summary.rs
- crates/biome_cli/src/reporter/terminal.rs
- crates/biome_cli/tests/snapshots/main_cases_reporter_summary/reports_diagnostics_summary_check_command.snap
- crates/biome_cli/tests/snapshots/main_cases_reporter_summary/reports_diagnostics_summary_check_verbose_command.snap
- crates/biome_cli/tests/snapshots/main_cases_reporter_summary/reports_diagnostics_summary_ci_command.snap
- crates/biome_cli/tests/snapshots/main_cases_reporter_summary/reports_diagnostics_summary_format_command.snap
- crates/biome_cli/tests/snapshots/main_cases_reporter_summary/reports_diagnostics_summary_lint_command.snap
- crates/biome_diagnostics/src/display.rs
This PR enhance the summary reporter:
- added list of files that have lint/assist violations
- all files have now an hyperlink, so users can open them
- the of errors/warnings/infos are printed only if they are greater than zero 
Updated snapshots, manually tested the links.
> feat(cli): enhanced summary reporter

- .changeset/sync-sinuses-stutter.md
- crates/biome_js_analyze/src/ast_utils.rs
- crates/biome_js_analyze/tests/specs/nursery/noFloatingPromises/invalidSyncCallbackInsideAsyncFn.ts
- crates/biome_js_analyze/tests/specs/nursery/noFloatingPromises/invalidSyncCallbackInsideAsyncFn.ts.snap
Fixed [#6796](https://github.com/biomejs/biome/issues/6796): `noFloatingPromises` will no longer suggest to add `await` keyword inside synchronous callbacks nested inside `async` functions.
> fix(core): correctly identify sync callbacks inside async functions

- .changeset/stupid-socks-visit.md
- crates/biome_service/src/workspace/server.rs
When both "Apply safe fixes on save" and "Sort imports on save" are enabled in the IntelliJ Biome plugin, the file occasionally becomes broken on save. After investigation, I realised that the Biome LSP returns incorrect text edits for the second code action request:
1. Editor sends a `textDocument/codeAction` request for `source.fixAll.biome`.
2. Biome LSP responses text edits to apply all safe fixes.
3. Editor applies the edits to the file and saves the file.
4. Editor sends a `textDocument/didChange` notification.
5. Biome LSP receives the notification and updates the opened document.
6. **The workspace watcher observes the file changes occurred in 3. and updates the opened document with the outdated content.**
7. Editor sends a `textDocument/codeAction` request for …
> fix(core): do not update the opened document when change observed by the watcher

- .changeset/iterable-items-infer.md
- .changeset/sync-sinuses-stutter.md
- .markdownlint.json
- crates/biome_js_analyze/tests/quick_test.rs
- crates/biome_js_analyze/tests/specs/nursery/noFloatingPromises/invalidSyncCallbackInsideAsyncFn.ts.snap
- crates/biome_js_analyze/tests/specs/nursery/noFloatingPromises/validSyncCallbackInsideAsyncFn.ts
- crates/biome_js_analyze/tests/specs/nursery/noFloatingPromises/validSyncCallbackInsideAsyncFn.ts.snap
- crates/biome_js_type_info/src/flattening/expressions.rs
- crates/biome_js_type_info/src/format_type_info.rs
- crates/biome_js_type_info/src/local_inference.rs
- crates/biome_js_type_info/src/type_info.rs
- crates/biome_module_graph/src/js_module_info/collector.rs
Fixed [#6796](https://github.com/biomejs/biome/issues/6796): Fixed a false positive that happened in `noFloatingPromises` when calling functions that were declared as part of `for ... of` syntax inside `async` functions.
Instead, the variables declared inside `for ... of` loops are now correctly inferred if the expression being iterated evaluates to an `Array` (support for other iterables will [follow later](https://github.com/biomejs/biome/issues/6810)).
**Invalid example**
```tsx
const txStatements: Array<(tx) => Promise<any>> = [];
db.transaction((tx: any) => {
for (const stmt of txStatements) {
// We correctly flag this resolves to a `Promise`:
stmt(tx)
}
});
```
**Valid example**
```tsx
async function valid(db) {
const txStatements: Array<(tx: any) => void> = [(tx) => …
```
> fix(core): infer for-of and for-in loop variables

- .changeset/cyclic-checks-charge.md
- Cargo.lock
- crates/biome_js_analyze/src/lint/nursery/no_import_cycles.rs
- crates/biome_module_graph/Cargo.toml
- crates/biome_module_graph/src/js_module_info.rs
- crates/biome_module_graph/src/js_module_info/collector.rs
- crates/biome_module_graph/tests/snapshots/test_export_const_type_declaration_with_namespace.snap
- crates/biome_module_graph/tests/snapshots/test_resolve_export_types.snap
- crates/biome_module_graph/tests/snapshots/test_resolve_exports.snap
- crates/biome_module_graph/tests/snapshots/test_resolve_merged_types.snap
- crates/biome_module_graph/tests/snapshots/test_resolve_multiple_reexports.snap
- crates/biome_module_graph/tests/snapshots/test_resolve_recursive_looking_country_info.snap
- crates/biome_module_graph/tests/snapshots/test_resolve_recursive_looking_vfile.snap
- crates/biome_module_graph/tests/spec_tests.rs
Improved the performance of `noImportCycles` by ~30%.
The majority of the savings are achieved by using an `IndexMap` instead of `BTreeMap` for storing the imports in the module info. These savings are likely to have some positive impact on type inference as well, although I expect the savings to be less pronounced there.
The rest of the savings were achieved by using an `FxHashSet` instead of a regular `HashSet` to track the paths that have been already been seen during cycle detection. Also, I'm storing the `resolved_path` in the set now, since it has an internal `Arc`, meaning we don't need another allocation for storing it, and we can call `.insert()` directly without needing to call `.contains()` first, since that was also just an attempt at avoiding the allocation.
Note that the …
> perf: optimise `noImportCycles`

- crates/biome_lsp/src/server.tests.rs
- crates/biome_service/src/workspace/scanner.rs
- crates/biome_service/src/workspace/server.rs
- crates/biome_service/src/workspace/watcher.rs
- crates/biome_service/src/workspace/watcher.tests.rs
- crates/biome_service/src/workspace_watcher.rs
This moves the logic for the scanner's `can_handle()` implementation into the workspace method `is_ignored_by_scanner()`, from where it can be reused by the Watcher. But because this logic depends on the `ScanKind`, we now keep track of the `ScanKind` inside the Watcher too, which should align the behaviours much better.
I'm also somewhat hopeful this can be a step towards solving #6838, although that will require an even tighter integration between the watcher and the rest of the scanner.
This may have a tiny overlap with #6839, so we should wait for that one to be merged first.
Everything should stay green, especially the tests introduced in #6839. Once #6839 is merged, I will also create a few variations to ensure differences in `ScanKind` are respected.
N/A
> refactor: make Watcher aware of `ScanKind`

- .changeset/tiny-this-trembles.md
- crates/biome_js_analyze/tests/specs/nursery/noFloatingPromises/18_invalid.js
- crates/biome_js_analyze/tests/specs/nursery/noFloatingPromises/18_invalid.js.snap
- crates/biome_js_analyze/tests/specs/nursery/noMisusedPromises/issue6777Valid.ts
- crates/biome_js_analyze/tests/specs/nursery/noMisusedPromises/issue6777Valid.ts.snap
- crates/biome_js_type_info/src/local_inference.rs
- crates/biome_module_graph/tests/snapshots/test_resolve_type_of_property_with_getter.snap.new
Fixed #6777: Fixed type inference handling of `this` to avoid infinite recursion.
Thanks to @sterliakov for the thorough investigation!
Test added.
> fix(core): fix type inference of `this`

- .changeset/damned-definitions-differ.md
- crates/biome_js_analyze/src/lint/correctness/use_import_extensions.rs
- crates/biome_js_analyze/tests/specs/correctness/useImportExtensions/sub/generated/index.d.ts
- crates/biome_js_analyze/tests/specs/correctness/useImportExtensions/sub/generated/index.d.ts.snap
- crates/biome_js_analyze/tests/specs/correctness/useImportExtensions/sub/generated/index.js
- crates/biome_js_analyze/tests/specs/correctness/useImportExtensions/sub/generated/index.js.snap
- crates/biome_js_analyze/tests/specs/correctness/useImportExtensions/valid.js
- crates/biome_js_analyze/tests/specs/correctness/useImportExtensions/valid.js.snap
Fixed [#6829](https://github.com/biomejs/biome/issues/6829): Fixed a false positive reported by `useImportExtensions` when importing a `.js` file that had a matching `.d.ts` file in the same folder.
Test added.
> fix(linter): fix false positive with `.d.ts` files in `useImportExtensions`

- .github/documentation-issue-labeler.yaml
Add French, Spanish, and Ukrainian to the documentation issue labeler and adjust the English matching regex accordingly
CI:
- Add French, Spanish, and Ukrainian labels to the documentation-issue-labeler config
- Update English label regex to exclude fr, es, and uk locales
> ci: add French, Spanish and Ukrainian to labeler

- .changeset/eleven-years-act.md
- crates/biome_cli/src/execute/migrate/eslint_any_rule_to_biome.rs
- crates/biome_js_analyze/src/lint/nursery/use_for_component.rs
Fix typo in [Solid.js ESLint rule](https://github.com/solidjs-community/eslint-plugin-solid) name from “perfer-for” to “prefer-for” and add a corresponding changeset
Bug Fixes:
- Correct rule key in migrate_eslint_any_rule from “solidjs/perfer-for” to “solidjs/prefer-for”
- Update lint rule declaration to reference “prefer-for” instead of misspelled “perfer-for”
Chores:
- Add changeset entry for the ESLint plugin fix
| Before | After |
|--------|--------|
| https://github.com/solidjs-community/eslint-plugin-solid/blob/main/packages/eslint-plugin-solid/docs/perfer-for.md | https://github.com/solidjs-community/eslint-plugin-solid/blob/main/packages/eslint-plugin-solid/docs/prefer-for.md | 
[eslint-plugin-solid](https://biomejs.dev/linter/javascript/sources/#eslint-plugin-solid)
> fix: typo `perfer-for` → `prefer-for`

- .changeset/crazy-moments-sniff.md
- crates/biome_js_analyze/src/lint/nursery/no_magic_numbers.rs
- crates/biome_js_analyze/tests/specs/nursery/noMagicNumbers/valid.tsx
- crates/biome_js_analyze/tests/specs/nursery/noMagicNumbers/valid.tsx.snap
Fixes #6910.
biome now ignores type casts and assertions when evaluating numbers for `noMagicNumbers` rule.
Updated `valid` snapshot test with constant definitions that are supposed to be correct.
Bugfix to a nursery rule - n/a.
> fix(biome_js_analyze): ignore `as const` and similar wrappers in `noMagicNumbers` rule

- .changeset/eleven-clouds-slide.md
- crates/biome_analyze/src/rule.rs
Correct the source URL path for the ESLint Vitest rule links
Bug Fixes:
- Fix typo in [ESLint Vitest plugin](https://github.com/vitest-dev/eslint-plugin-vitest) URL segment from "rule" to "rules"
Chores:
- Add a changeset entry for the URL fix
| Before | After |
|--------|--------|
| https://github.com/vitest-dev/eslint-plugin-vitest/blob/main/docs/rule/max-nested-describe.md | https://github.com/vitest-dev/eslint-plugin-vitest/blob/main/docs/rules/max-nested-describe.md | 
[@vitest/eslint-plugin](https://biomejs.dev/linter/javascript/sources/#vitesteslint-plugin)
> fix: typo `@vitest/eslint-plugin` source url

- .github/workflows/benchmark.yml
- crates/biome_deserialize/src/json.rs
- crates/biome_js_analyze/src/lint/correctness/no_private_imports.rs
- crates/biome_js_analyze/src/lint/nursery/no_unresolved_imports.rs
- crates/biome_js_analyze/src/lint/nursery/use_readonly_class_properties.rs
- crates/biome_js_syntax/src/unescape.rs
- crates/biome_js_type_info/src/flattening/conditionals.rs
- crates/biome_js_type_info/src/flattening/intersections.rs
- crates/biome_js_type_info/src/globals.rs
- crates/biome_js_type_info/src/local_inference.rs
- crates/biome_js_type_info/src/type_info.rs
- crates/biome_js_type_info/src/type_info/literal.rs
- crates/biome_js_type_info/tests/type_info.rs
- crates/biome_json_value/src/json_value.rs
- crates/biome_module_graph/src/format_module_graph.rs
- crates/biome_module_graph/src/js_module_info/collector.rs
- crates/biome_module_graph/src/js_module_info/module_resolver.rs
- crates/biome_module_graph/tests/snapshots/test_export_const_type_declaration_with_namespace.snap
- crates/biome_module_graph/tests/snapshots/test_resolve_exports.snap
- crates/biome_module_graph/tests/snapshots/test_resolve_merged_namespace_with_type.snap
- crates/biome_module_graph/tests/snapshots/test_resolve_recursive_looking_country_info.snap
- crates/biome_module_graph/tests/snapshots/test_resolve_recursive_looking_vfile.snap
- crates/biome_module_graph/tests/spec_tests.rs
- crates/biome_rowan/src/syntax_node_text.rs
- crates/biome_rowan/src/text.rs
- crates/biome_rowan/src/token_text.rs
- crates/biome_text_size/src/range.rs
Shrinks `Text` from 24 bytes to 16. Given that `Text` is getting used increasingly, including quite pervasively inside the module graph, I figured it might be a good candidate to squeeze a bit further.
Seems to give a ~1-3% improvement on the module graph benchmarks.
> perf: shrink `Text`

- .changeset/use_readonly_class_properties_add_async_await_method_check.md
- crates/biome_js_analyze/src/lint/nursery/use_readonly_class_properties.rs
- crates/biome_js_analyze/tests/specs/nursery/useReadonlyClassProperties/valid.ts
- crates/biome_js_analyze/tests/specs/nursery/useReadonlyClassProperties/valid.ts.snap
Fixed [#6919](https://github.com/biomejs/biome/issues/6919)
Fixed [#6920](https://github.com/biomejs/biome/issues/6920):
`useReadonlyClassProperties` now does checks for mutations in async class methods.
Example:
```typescript
class Counter3 {
private counter: number;
async count() {
this.counter = 1;
const counterString = `${this.counter++}`;
}
}
```
> feat(biome-js-analyze): expanded support for useReadonlyClassProperties to cover async class methods too

- .changeset/fast-bottles-guess.md
- crates/biome_diagnostics_categories/src/categories.rs
This fixes the documentation URL for `lint/correctness/noUnknownPseudoClass`, that was pointing to a 404 page.
I noticed there's also a `lint/correctness/noUnknownPseudoClassSelector` rule [here](https://github.com/biomejs/biome/blob/main/crates/biome_diagnostics_categories/src/categories.rs#L124), but hesitated to update that URL too, cause I'm not sure how to approach this. It seems like `noUnknownPseudoClassSelector` has been renamed to `noUnknownPseudoClass`, but before removing I want to make sure it's not there for backwards compatibility.
Let me know if I should either update that URL too, or remove the reference to `noUnknownPseudoClassSelector`.
> fix: update documentation URL for `noUnknownPseudoClass`

- .changeset/six-corners-lay.md
- Cargo.lock
- crates/biome_cli/src/execute/traverse.rs
- crates/biome_lsp/src/handlers/analysis.rs
- crates/biome_lsp/src/handlers/formatting.rs
- crates/biome_lsp/src/handlers/text_document.rs
- crates/biome_lsp/src/requests/syntax_tree.rs
- crates/biome_module_graph/Cargo.toml
- crates/biome_module_graph/src/js_module_info.rs
- crates/biome_module_graph/src/lib.rs
- crates/biome_service/Cargo.toml
- crates/biome_service/src/snapshots/biome_service__workspace__tests__debug_module_graph.snap
- crates/biome_service/src/workspace.rs
- crates/biome_service/src/workspace.tests.rs
- crates/biome_service/src/workspace/client.rs
- crates/biome_service/src/workspace/scanner.rs
- crates/biome_service/src/workspace/server.rs
- crates/biome_service/src/workspace_types.rs
- crates/biome_wasm/src/lib.rs
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
This PR exposes new functions to the WASM distribution. It also creates new functions that allow to update and pull the module graph.
The new functions will be very useful for the playground, because at the moment project rules don't work. With the new functions, we will be able to that (for the most part). We still need some functions for storing the manifests. 
Added new tests for the new functions. The CI should stay green
> feat(wasm): expose new functions

- .changeset/six-corners-lay.md
- Cargo.lock
- Cargo.toml
- crates/biome_service/Cargo.toml
- crates/biome_service/src/workspace/scanner.rs
- crates/biome_service/src/workspace_types.rs
- crates/biome_wasm/src/lib.rs
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
Exposes a workspace method `scan_project_folder` via the WASM API. This will enable use of type inference and project rules in the playground.
Manually tested with the playground locally.
N/A
> feat(wasm): expose Workspace::scan_project_folder

- .changeset/grumpy-crews-sneeze.md
- crates/biome_analyze/src/utils.rs
- crates/biome_migrate/tests/specs/migrations/ruleMover/issue6516.jsonc
- crates/biome_migrate/tests/specs/migrations/ruleMover/issue6516.jsonc.snap
Fixed the `fix_separators` utility function to move the trailing comments to the newly created separator token.
Added a snapshot test.
N/A
> fix(migrate): transfer comments to the separator

- .changeset/five-ghosts-wave.md
- crates/biome_js_analyze/tests/specs/nursery/noUnassignedVariables/valid.jsx
- crates/biome_js_analyze/tests/specs/nursery/noUnassignedVariables/valid.jsx.snap
- crates/biome_js_semantic/src/events.rs
Closes #6795
The `noUnassignedVariables` rule was incorrectly flagging variables used in JSX `ref` attributes as
unassigned. This occurred because JSX ref attributes were not being recognized as write references in the
semantic analyzer.
This PR fixes the issue by adding proper detection for JSX ref attribute usage, ensuring that variables
assigned to `ref` props are correctly tracked as write references.
Added test cases in `crates/biome_js_analyze/tests/specs/nursery/noUnassignedVariables/valid.jsx` to verify
that JSX ref attributes are correctly handled:
```jsx
export const Bug = () => {
let value;
return <div ref={value} />
}
```
The snapshot test confirms that no diagnostic is generated for this valid usage pattern.
[no-unassigned-variables](https://biomejs.dev/linter/rules/no-unassig …
> fix(lint/noUnassignedVariables): handle JSX ref attribute assignments

- .changeset/skating-scanner-skips.md
- crates/biome_cli/src/commands/mod.rs
- crates/biome_cli/tests/commands/lint.rs
- crates/biome_cli/tests/snapshots/main_commands_lint/linter_enables_project_domain_based_on_extended_config.snap
- crates/biome_formatter_test/src/spec.rs
- crates/biome_lsp/src/handlers/text_document.rs
- crates/biome_lsp/src/server.rs
- crates/biome_lsp/src/server.tests.rs
- crates/biome_lsp/src/session.rs
- crates/biome_service/src/configuration.rs
- crates/biome_service/src/workspace.rs
- crates/biome_service/src/workspace.tests.rs
- crates/biome_service/src/workspace/scanner.tests.rs
- crates/biome_service/src/workspace/server.rs
- crates/biome_service/src/workspace/server.tests.rs
- crates/biome_service/src/workspace/watcher.tests.rs
- crates/biome_service/tests/spec_tests.rs
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
- packages/@biomejs/js-api/src/wasm.ts
Fixed [#7062](https://github.com/biomejs/biome/issues/7062): Biome now correctly considers extended configs when determining the mode for the scanner.
The caller of `openProject()` already has a configuration, which has correctly applied extended configurations, so we use that instead of handling it inside the workspace. We already have `ScanKindComputer` to keep CLI and LSP implementations in sync.
Test added. Existing tests should remain green.
N/A
> fix(core): consider extended configs for scan kind

- .changeset/returned-raisins-reciprocate.md
- crates/biome_js_analyze/tests/specs/nursery/noFloatingPromises/issue6985Valid.ts
- crates/biome_js_analyze/tests/specs/nursery/noFloatingPromises/issue6985Valid.ts.snap
- crates/biome_js_type_info/src/local_inference.rs
- crates/biome_module_graph/tests/snapshots/test_resolve_type_of_this_in_class_wrong_scope.snap
- crates/biome_rowan/src/syntax/node.rs
Fixed [#6985](https://github.com/biomejs/biome/issues/6985): Inference of return types no longer mistakenly picks up return types of nested functions.
For all Biome devs: This PR introduces a nice utility that makes it easier to prune subtrees during node traversal: look for the `pruned_descendents()` method.
Test added.
N/A
> fix(core): return type inference no longer picks up nested returns

- .changeset/rotten-knives-brush.md
- crates/biome_js_analyze/src/lint/correctness/no_unused_private_class_members.rs
- crates/biome_js_analyze/tests/specs/correctness/noUnusedPrivateClassMembers/invalid.ts.snap
- crates/biome_js_analyze/tests/specs/correctness/noUnusedPrivateClassMembers/invalid_issue_7101.ts
- crates/biome_js_analyze/tests/specs/correctness/noUnusedPrivateClassMembers/invalid_issue_7101.ts.snap
- crates/biome_lsp/src/server.tests.rs
This PR fixes #7101
1. If a class member defined in a constructor argument is only used within the constructor, remove the `private` modifier and make it a plain method argument.
2. If it is not used within the constructor, prefix it with an underscore, as with `no_unused_function_parameter`.
Note:
Previously, unused class members defined as constructor arguments were completely removed from the constructor arguments. However, this changed the constructor signature and was inconsistent with the behavior of `no_unused_function_parameter`.
As a side effect of this bug fix, the constructor signature is no longer changed, which has caused some existing tests to produce different results. (check changed files)
New test file has been added.
> fix(lint/noUnusedPrivateClassMembers): handle class members declared in constructor parameters correctly

- .coderabbit.yaml
Alright CodeRabbit, let's see what you think of this.
YOLO
> chore: add CodeRabbit config

- .changeset/shaky-experts-sit.md
- crates/biome_js_analyze/src/lint/correctness/no_private_imports.rs
- crates/biome_js_analyze/src/lint/correctness/use_import_extensions.rs
- crates/biome_js_analyze/src/lint/nursery/no_import_cycles.rs
- crates/biome_js_analyze/src/lint/nursery/no_unresolved_imports.rs
- crates/biome_js_analyze/tests/specs/nursery/noImportCycles/ignoreTypes/a.ts
- crates/biome_js_analyze/tests/specs/nursery/noImportCycles/ignoreTypes/a.ts.snap
- crates/biome_js_analyze/tests/specs/nursery/noImportCycles/ignoreTypes/b.ts
- crates/biome_js_analyze/tests/specs/nursery/noImportCycles/ignoreTypes/b.ts.snap
- crates/biome_js_analyze/tests/specs/nursery/noImportCycles/ignoreTypes/c.ts
- crates/biome_js_analyze/tests/specs/nursery/noImportCycles/ignoreTypes/c.ts.snap
- crates/biome_js_analyze/tests/specs/nursery/noImportCycles/includeTypes.options.json
- crates/biome_js_analyze/tests/specs/nursery/noImportCycles/includeTypes.ts
- crates/biome_js_analyze/tests/specs/nursery/noImportCycles/includeTypes.ts.snap
- crates/biome_js_analyze/tests/specs/nursery/noImportCycles/types.ts
- crates/biome_js_analyze/tests/specs/nursery/noImportCycles/types.ts.snap
- crates/biome_module_graph/src/js_module_info.rs
- crates/biome_module_graph/src/js_module_info/collector.rs
- crates/biome_module_graph/src/js_module_info/module_resolver.rs
- crates/biome_module_graph/src/js_module_info/visitor.rs
- crates/biome_module_graph/src/lib.rs
- crates/biome_module_graph/tests/spec_tests.rs
- crates/biome_rule_options/src/no_import_cycles.rs
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
- packages/@biomejs/biome/configuration_schema.json
Fixes #6799 
Added a new option `ignoreTypes`, enabled by default, to ignore type-only imports in the `noImportCycle` rule.
Added snapshot tests.
Added the options section to the rule doc.
> feat(lint): add `ignoreTypes` option to the `noImportCycles` rule

- .github/workflows/release.yml
Replaced `env.GITHUB_SHA` with `github.sha`.
Pray for success in the next release :)
N/A
> ci: use `github.sha` for dispatch event on release

- packages/@biomejs/biome/CHANGELOG.md
Documentation:
- Update the useConsistentTypeDefinitions rule URL in the changelog to the correct path
| Before | After |
|--------|--------|
| https://biomejs.dev/rules/use-consistent-type-definitions | https://biomejs.dev/linter/rules/use-consistent-type-definitions |
> docs(changelog): fix wrong `useConsistentTypeDefinitions` URL

- crates/biome_css_parser/tests/spec_tests.rs
- crates/tests_macros/src/lib.rs
A minor DX improvement for generated snapshot tests. Previously, files with exactly the same name would comflict when compiled. For example, `ok/foo/test.css` and `ok/bar/test.css` would conflict because they both end up as `ok::test_css`.
This makes it so that these tests end up as `ok::foo::test_css` and `ok::bar::test_css` instead.
CI should stay green.
> refactor(test): make generated snapshot tests have module stucture that matches folder structure

- .coderabbit.yaml
Ignore generated files for Coderabbit
N/A
N/A
> chore(coderabbit): dont review generated files

- crates/biome_configuration/src/diagnostics.rs
Correct misspelled parameter name `messsage` to `message` in `with_verbose_advice` methods of diagnostic types
Chores:
- Fix typo in method signature and usage for CantLoadExtendFile.with_verbose_advice
- Fix typo in method signature and usage for CantResolve.with_verbose_advice
> chore: fix typos `messsage` → `message`

- crates/biome_css_analyze/src/keywords.rs
- crates/biome_css_analyze/tests/specs/source/useSortedProperties/invalid.css
- crates/biome_css_analyze/tests/specs/source/useSortedProperties/invalid.css.snap
- crates/biome_css_analyze/tests/specs/source/useSortedProperties/valid.css
- crates/biome_css_analyze/tests/specs/source/useSortedProperties/valid.css.snap
Fix typos in biome_css_analyze tests and CSS fixtures
Tests:
- Correct test function name typos from 'kown' to 'known' in several KNOWN_* properties order tests
- Change `sumsung` to `samsung`
- Fix typo in CSS test fixtures by replacing 'opactity' with 'opacity' in valid and invalid sortedProperties cases
```bash
cargo test
```
> chore: fix typos in biome css analyze crates

- .changeset/tired-results-knock.md
- crates/biome_js_analyze/src/lint/style/use_const.rs
- crates/biome_js_analyze/tests/specs/style/useConst/invalid.jsonc.snap
Implements https://github.com/biomejs/biome/issues/7174
[`useConst`](https://biomejs.dev/linter/rules/use-const/) no longer reports variables read before to be written.
Previously, `useConst` reported uninitialised variables that were read in an inner function before being written, as shown in the following example::
```js
let v;
function f() {
return v;
}
v = 0;
```
This can produce false positives in the case where `f` is called before `v` has be written as in the following code:
```js
let v;
function f() {
return v;
}
console.log(f()); // print `undefined`
v = 0;
```
Although this is an expected behavior of the original implementation, we consider it problematic since the rule fix is marked as safe.
To avoid false positives like this, the rule now ignores the previous examples. …
> feat(useConst): don't report uninit variables read befroe to be written

- .changeset/legal-mugs-care.md
- crates/biome_cli/tests/commands/format.rs
- crates/biome_cli/tests/snapshots/main_commands_format/can_format_graphphs_files.snap
- crates/biome_graphql_syntax/src/file_source.rs
We use `.graphqls` files for GraphQL definition files that contain only types ([SDL](https://www.apollographql.com/docs/kotlin/essentials/file-types#sdl-schemas-graphqls)), like this:
```graphql
scalar Time
scalar UUID
type Tenant {
id: UUID!
name: String!
isActive: Boolean!
createdAt: Time!
updatedAt: Time!
}
type DashboardUser {
name: String!
givenName: String
familyName: String
email: String!
createdAt: Time
}
type Query {
tenants: [Tenant!]!
dashboardUsers(tenantId: UUID): [DashboardUser!]!
}
```
We want `biome` to format those, and as we seen that [you already have tests](https://github.com/biomejs/biome/blob/main/crates/biome_graphql_formatter/tests/specs/graphql/definitions/object.graphql) that parse this format, the format we use in `.graphqls` types, we thought that it will be …
> feat(core): add support for  `.graphqls` files

- GOVERNANCE.md
- packages/@biomejs/biome/CHANGELOG.md
- packages/@biomejs/js-api/tests/lintContent.test.ts
- packages/@biomejs/js-api/tests/nodejs.test.ts
- xtask/codegen/css.ungram
- xtask/rules_check/src/lib.rs
Apply spelling corrections across the codebase
Chores:
- Fix misspelling of "diagnostics" in test descriptions
- Correct "organisation" to "organization" in governance documentation
- Fix typo in variable name from "supression_reason" to "suppression_reason" in rules_check
- Correct typo in CHANGELOG from "JsLogicalExpreesion" to "JsLogicalExpression"
> chore: fix various typos across codebase

- .changeset/slimy-zoos-search.md
- crates/biome_js_analyze/src/lint/complexity/use_index_of.rs
- crates/biome_js_analyze/tests/specs/complexity/useIndexOf/invalid.js.snap
Fixes #7233
The error message was incorrectly suggesting to prefer findIndex() over indexOf(), when it should suggest the opposite. Updated the diagnostic message to correctly recommend using indexOf()/lastIndexOf() over findIndex()/findLastIndex().
Fixed incorrect error message in the `useIndexOf` lint rule. The diagnostic was showing "Prefer Array#findIndex() over Array#indexOf()" when it should show "Prefer Array#indexOf() over Array#findIndex()". This was a simple variable swap in the diagnostic message template.
The fix swaps two variables in the diagnostic message string. The existing test snapshots will catch this change and verify the message is now correct. GitHub CI will validate the build and tests.
> fix: correct error message in useIndexOf rule

- packages/@biomejs/biome/README.fr.md
- packages/@biomejs/biome/README.hi.md
- packages/@biomejs/biome/README.ja.md
- packages/@biomejs/biome/README.kr.md
- packages/@biomejs/biome/README.md
- packages/@biomejs/biome/README.pt-BR.md
- packages/@biomejs/biome/README.ru.md
- packages/@biomejs/biome/README.uk.md
- packages/@biomejs/biome/README.zh-CN.md
- packages/@biomejs/biome/README.zh-TW.md
The sponsor image of Vercel is incorrect on npmjs. It falls back on the light image, while it should be the dark one. This PR fixes it
> chore: fix image sponsor

- crates/biome_cli/tests/snapshots/main_commands_check/check_json_files.snap
- crates/biome_cli/tests/snapshots/main_commands_lint/check_json_files.snap
- crates/biome_json_analyze/src/lint/suspicious/no_duplicate_object_keys.rs
- crates/biome_json_analyze/tests/specs/suspicious/noDuplicateObjectKeys/invalid.json.snap
Fixed a grammar mistake in an error message. The message was missing the word "is".
**Before (incorrect):**
> This where a duplicated key was declared again.
**After (correct):**
> This is where a duplicated key was declared again.
- Fixed the grammar in the error message
- Updated the test to match the corrected message
This makes the error message easier to read and understand for users.
Fixes #7307
> fix(noDuplicateObjectKeys): correct grammatical error in JSON diagnostic message

- .github/workflows/main.yml
- .github/workflows/preview.yml
- .github/workflows/pull_request.yml
- Cargo.lock
- Cargo.toml
- biome.json
- crates/biome_cli/Cargo.toml
- crates/biome_js_analyze/Cargo.toml
- crates/biome_js_runtime/Cargo.toml
- crates/biome_js_runtime/src/context.rs
- crates/biome_js_runtime/src/lib.rs
- crates/biome_js_runtime/src/module_loader.rs
- crates/biome_js_runtime/src/plugin_api.rs
- crates/biome_plugin_loader/Cargo.toml
- crates/biome_plugin_loader/src/analyzer_js_plugin.rs
- crates/biome_plugin_loader/src/diagnostics.rs
- crates/biome_plugin_loader/src/lib.rs
- crates/biome_plugin_loader/src/snapshots/evaluate_in_worker_threads.snap
- crates/biome_plugin_loader/src/thread_local.rs
- crates/biome_service/Cargo.toml
- crates/biome_service/src/workspace/server.rs
- package.json
- packages/@biomejs/plugin-api/LICENSE-APACHE
- packages/@biomejs/plugin-api/LICENSE-MIT
- packages/@biomejs/plugin-api/index.d.ts
- packages/@biomejs/plugin-api/index.js
- packages/@biomejs/plugin-api/package.json
- plugins/plugin.js
- pnpm-lock.yaml
Part of #2469
This pull request integrates the Boa engine to Biome for JS plugins. It runs the default exported function and pulls diagnostics from the plugin. JS APIs for Biome's AST/CST aren't implemented yet.
Support for JS plugins is gated behind the `js_plugin` feature and it will be enabled only in preview releases. Thus I think we can merge this to the main branch.
Added a simple test using multiple threads.
TODO
> feat: execute JS plugin in the Boa engine

- .changeset/use_readonly_class_properties_nested_assignment_fix.md
- crates/biome_js_analyze/tests/quick_test.rs
- crates/biome_js_analyze/tests/specs/style/useReadonlyClassProperties/valid.ts
- crates/biome_js_analyze/tests/specs/style/useReadonlyClassProperties/valid.ts.snap
Adds tests to confirm already fixed issues in pull request: https://github.com/biomejs/biome/pull/7015
Closes #7310
> fix(biome-js-analyze): add tests for useReadonlyClassProperties

- .changeset/clever-worlds-heal.md
- crates/biome_js_formatter/tests/specs/js/module/object/property_key.js
- crates/biome_js_formatter/tests/specs/js/module/object/property_key.js.snap
- crates/biome_unicode_table/src/lib.rs
These two characters have been added to the `ID_Continue` property in Unicode 15.1, but they're not supported in ECMAScript. To avoid an syntax error, Biome will omit these on checking if a character is in `ID_Continue`.
- U+30FB KATAKANA MIDDLE DOT `・`
- U+FF65 HALFWIDTH KATAKANA MIDDLE DOT `･`
Added a snapshot test.
N/A
> fix(formatter): patch ID_Continue to omit U+30FB and U+FF65 added in Unicode 15.1

- .changeset/forced-files-forget.md
- biome.json
- crates/biome_cli/tests/cases/included_files.rs
- crates/biome_cli/tests/snapshots/main_cases_included_files/does_not_handle_files_inside_force_ignored_folders.snap
- crates/biome_cli/tests/snapshots/main_cases_included_files/does_not_handle_included_files_if_overridden_by_forced_ignore.snap
- crates/biome_configuration/src/lib.rs
- crates/biome_configuration/tests/invalid/experimental_scanner_ignores.json
- crates/biome_configuration/tests/invalid/experimental_scanner_ignores.json.snap
- crates/biome_configuration/tests/invalid/files_extraneous_field.json.snap
- crates/biome_glob/src/lib.rs
- crates/biome_module_graph/src/js_module_info/diagnostics.rs
- crates/biome_service/src/projects.rs
- crates/biome_service/src/scanner/workspace_scanner_bridge.tests.rs
- crates/biome_service/src/settings.rs
- crates/biome_service/src/snapshots/module_diagnostic.snap
- crates/biome_service/src/workspace/server.rs
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
- packages/@biomejs/biome/configuration_schema.json
Deprecated the option `files.experimentalScannerIgnores` in favour of **force-ignore** syntax in `files.includes`.
`files.includes` supports ignoring files by prefixing globs with an exclamation mark (`!`). With this change, it also supports _force_-ignoring globs by prefixing them with a double exclamation mark (`!!`).
The effect of force-ignoring is that the scanner will not index files matching
the glob, even in project mode and those files are imported by other files.
Let's take the following configuration:
```json
{
"files": {
"includes": [
"**",
"!**/generated",
"!!**/dist",
"fixtures/example/dist/*.js"
]
},
"linter": {
"domains": {
"project": "all"
}
}
}
```
This configuration achieves the following:
- Because the [project domain](https://biomejs.dev/linter/domains/#project) is …
> feat(core): add force-ignore syntax to `files.includes`

- .changeset/big-keys-play.md
- crates/biome_js_analyze/src/lint/complexity/use_optional_chain.rs
- crates/biome_js_analyze/tests/specs/complexity/useOptionalChain/yoda_expressions_logicalAndCases3.js
- crates/biome_js_analyze/tests/specs/complexity/useOptionalChain/yoda_expressions_logicalAndCases3.js.snap
- crates/biome_js_analyze/tests/specs/complexity/useOptionalChain/yoda_expressions_logicalAndCases4.js
- crates/biome_js_analyze/tests/specs/complexity/useOptionalChain/yoda_expressions_logicalAndCases4.js.snap
- crates/biome_js_analyze/tests/specs/complexity/useOptionalChain/yoda_expressions_logicalAndCases5.js
- crates/biome_js_analyze/tests/specs/complexity/useOptionalChain/yoda_expressions_logicalAndCases5.js.snap
- crates/biome_js_analyze/tests/specs/complexity/useOptionalChain/yoda_expressions_logicalAndCases6.jsx
- crates/biome_js_analyze/tests/specs/complexity/useOptionalChain/yoda_expressions_logicalAndCases6.jsx.snap
- crates/biome_js_analyze/tests/specs/complexity/useOptionalChain/yoda_expressions_validCases.ts
- crates/biome_js_analyze/tests/specs/complexity/useOptionalChain/yoda_expressions_validCases.ts.snap
- crates/biome_js_syntax/src/expr_ext.rs
Closes #7381
Now the `useOptionalChain` rule recognizes optional chaining using Yoda expressions (e.g., `undefined !== foo && foo.bar`).
Added snap tests.
Using the shell script below, Yoda expressions versions of the existing tests were generated, and the snapshots of the Yoda versions were compared with the originals to confirm identical results.
```
#!/bin/bash
shopt -s nullglob
output_file_prefix="yoda_expressions"
for f in ${output_file_prefix}_*; do
case "$f" in
*.snap) continue ;;
esac
rm -f -- "$f"
done
for file in *.js *.ts *.jsx *.tsx; do
if [[ -f "$file" ]]; then
output_file="${output_file_prefix}_${file}"
swap_occurred=false
lines=()
while IFS= read -r line; do
trailing_semicolon=""
if [[ $line =~ \;$ ]]; then
trailing_semicolon=";"
line=${line%;}
fi
read -r -a words <<< …
```
> fix(useOptionalChain): support Yoda expressions

- crates/biome_analyze/src/options.rs
- crates/biome_js_type_info/src/conditionals.rs
- crates/biome_js_type_info/src/helpers.rs
- crates/biome_js_type_info/src/lib.rs
- crates/biome_js_type_info/src/type.rs
- crates/biome_js_type_info/tests/conditionals.rs
- crates/biome_js_type_info/tests/snapshots/test_reference_to_falsy_subset_of.snap
- crates/biome_module_graph/tests/spec_tests.rs
Hopefully fix #7324: Even though we're missing a complete reproduction, I noticed the partial reproductions we had both included a conditionals, so I double-checked the inference code related to those: I noticed an invalid `apply_module_id_to_reference()` happening in `derive_conditional_type()`, because the references coming from `flattened_union_variants()` already have correct module ID applied to them. `flattened_union_variants()` is also a very recent addition, so it could very well explain the regression.
Tests added. Unfortunately the tests **didn't** reproduce the original problem, so I can only hope it resolves the issue.
N/A
Note I didn't even add a changeset as I'm not sure the fix will solve the linked issue.
> fix(core): improve inference with conditionals

- .changeset/ancient-ancestors-ascent.md
- crates/biome_cli/src/execute/traverse.rs
- crates/biome_cli/tests/cases/included_files.rs
- crates/biome_cli/tests/commands/lint.rs
- crates/biome_cli/tests/snapshots/main_cases_included_files/does_not_handle_files_in_ignored_folder.snap
- crates/biome_service/src/projects.rs
- crates/biome_service/src/settings.rs
- crates/biome_service/src/workspace.rs
- crates/biome_service/src/workspace/server.rs
Fixed [#7268](https://github.com/biomejs/biome/issues/7268): Files that are explicitly passed as CLI arguments are now correctly ignored if they reside in an ignored folder.
**Warning:** This may have a slight but noticeable performance impact on traversal. We might be able to prevent this by pre-filtering the paths that are specified explicitly before traversal, but I wanted to fix the bug first.
Also fixes #7279.
Flawed test updated. Others should remain green.
> fix(cli): files in ignored folders are now correctly ignored

- .changeset/config.json
- .github/workflows/beta.yml
- .github/workflows/release.yml
- .github/workflows/release_cli.yml
`@biomejs/plugin-api` was introduced for providing type info for JS plugins, but not ready for publish. We have to skip publishing the package for now.
Wait for the next CI
N/A
> ci: ignore @biomejs/plugin-api on publish

- .changeset/little-heads-divide.md
- crates/biome_js_analyze/src/lint/correctness/no_unused_private_class_members.rs
- crates/biome_js_analyze/tests/specs/correctness/noUnusedPrivateClassMembers/invalid_dynamic_access.ts
- crates/biome_js_analyze/tests/specs/correctness/noUnusedPrivateClassMembers/invalid_dynamic_access.ts.snap
- crates/biome_js_analyze/tests/specs/correctness/noUnusedPrivateClassMembers/valid_dynamic_access.ts
- crates/biome_js_analyze/tests/specs/correctness/noUnusedPrivateClassMembers/valid_dynamic_access.ts.snap
Fixes https://github.com/biomejs/biome/issues/7323
The rule now considers as used all TS `private` members if a computed access on `this` is found.
I added two tests:
- A test that demonstrates that TS private members are no longer reported when a computed access on `this` is found.
- A test that demonstrates that unused `#member` are still reported even if a computed access on `this` is found.
I added a Caveat section describing the new behavior.
> fix(noUnusedPrivateClassMembers): ignore all TS `private` members if a `this[computed]` is found

- .changeset/wet-results-talk.md
- crates/biome_analyze/src/rule.rs
- crates/biome_cli/src/commands/lint.rs
- crates/biome_cli/src/commands/mod.rs
- crates/biome_cli/src/commands/scan_kind.rs
- crates/biome_cli/src/execute/mod.rs
- crates/biome_cli/tests/cases/linter_domains.rs
- crates/biome_cli/tests/snapshots/main_cases_linter_domains/should_disable_domain_via_cli.snap
- crates/biome_cli/tests/snapshots/main_cases_linter_domains/should_enable_domain_via_cli.snap
- crates/biome_cli/tests/snapshots/main_commands_lint/lint_help.snap
- crates/biome_cli/tests/snapshots/main_commands_lint/lint_only_rule_doesnt_exist.snap
- crates/biome_configuration/src/analyzer/mod.rs
- crates/biome_configuration/src/generated.rs
- crates/biome_configuration/src/generated/domain_selector.rs
- crates/biome_lsp/src/handlers/analysis.rs
- crates/biome_lsp/src/server.tests.rs
- crates/biome_service/src/configuration.rs
- crates/biome_service/src/file_handlers/css.rs
- crates/biome_service/src/file_handlers/graphql.rs
- crates/biome_service/src/file_handlers/javascript.rs
- crates/biome_service/src/file_handlers/json.rs
- crates/biome_service/src/file_handlers/mod.rs
- crates/biome_service/src/workspace.rs
- crates/biome_service/src/workspace.tests.rs
- crates/biome_service/src/workspace/server.rs
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
- xtask/codegen/src/generate_configuration.rs
Closes https://github.com/biomejs/biome/issues/6880
Now `--skip` and `--only` support domains too! They work the same as when you pass a group. However, we need to rely to some codegen because domains work across groups, so we need to codegen the filters generated by those domains.
Added new tests
Updated the relative CLI commands. Docs will be updated automatically upon release.
> feat(cli): --skip/--only with domains

- .changeset/rich-beds-clap.md
- crates/biome_configuration/src/lib.rs
- crates/biome_lsp/src/handlers/text_document.rs
- crates/biome_lsp/src/server.rs
- crates/biome_lsp/src/session.rs
Closes https://github.com/biomejs/biome/issues/7411
This PR makes the loading of configuration files "thread-aware". Unfortunately, the previous fix didn't work out as intended. In this PR, the loading of the configuration files uses a locking mechanism, so when two tasks arrive, the last one waits for the previous one, and uses the same value that was resolved by the first task. The loading operations are locked using the session ID, to avoid conflicts inside the same project.
Second, we enforce the scanning of the project when a `biome.json` file changes (precisely, when a watched file changes). The bug was caused by the fact that when the watcher is enabled, the project isn't re-indexed. This causes the project settings not to be updated. 
We now pass a `force` boolean up until when we …
> fix(lsp): project loading

- .github/workflows/autofix.yml
- CONTRIBUTING.md
- crates/biome_js_analyze/src/lint/nursery/no_useless_catch_binding.rs
- crates/biome_js_analyze/src/lint/nursery/use_consistent_arrow_return.rs
- crates/biome_js_analyze/src/lint/nursery/use_vue_multi_word_component_names.rs
- crates/biome_json_analyze/src/lint/suspicious/no_biome_first_exception.rs
- crates/biome_json_analyze/src/lint/suspicious/use_biome_ignore_folder.rs
- scripts/update-next-version.sh
We forgot to update this metadata for the past couple releases, so the website was showing incorect info.
Also, added a script to help automate it. It's AI generated, but I tested it and it works as expected.
Manually tested the new script. Went back in the changelog to figure out the right versions.
To test the automation, we currently have a new rule in the new release PR: #7413 So we'll know if it works then :crossed_fingers:
> chore: fix rule version metadata, add script to automate it

- .changeset/aliased-alleys-align.md
- crates/biome_resolver/src/lib.rs
- crates/biome_resolver/tests/fixtures/resolver_cases_6/package.json
- crates/biome_resolver/tests/spec_tests.rs
Fixed [#7242](https://github.com/biomejs/biome/issues/7242): Aliases specified in `package.json`'s `imports` section now support having multiple targets as part of an array.
Tests added.
N/A
> fix(core): support arrays as alias targets

- .changeset/infinite-indices-infer.md
- crates/biome_js_analyze/tests/specs/nursery/noFloatingPromises/03_invalid.ts
- crates/biome_js_analyze/tests/specs/nursery/noFloatingPromises/03_invalid.ts.snap
- crates/biome_js_analyze/tests/specs/nursery/noFloatingPromises/03b_invalid.ts
- crates/biome_js_analyze/tests/specs/nursery/noFloatingPromises/03b_invalid.ts.snap
- crates/biome_js_type_info/src/flattening/expressions.rs
- crates/biome_js_type_info/src/format_type_info.rs
- crates/biome_js_type_info/src/helpers.rs
- crates/biome_js_type_info/src/local_inference.rs
- crates/biome_js_type_info/src/resolver.rs
- crates/biome_js_type_info/src/type.rs
- crates/biome_js_type_info/src/type_data.rs
- crates/biome_module_graph/tests/snapshots/test_resolve_recursive_looking_country_info.snap
- crates/biome_module_graph/tests/snapshots/test_resolve_recursive_looking_vfile.snap
- crates/biome_module_graph/tests/spec_tests.rs
- crates/biome_resolver/tests/fixtures/resolver_cases_3/tsconfig.json
Fixed #7423: Type inference now recognises _index signatures_ and their accesses when they are being indexed as a string.
Replaces #6647, which was closed unintentionally.
```ts
type BagOfPromises = {
// This is an index signature definition. It declares that instances of type
// `BagOfPromises` can be indexed using arbitrary strings.
[property: string]: Promise<void>;
};
let bag: BagOfPromises = {};
// Because `bag.iAmAPromise` is equivalent to `bag["iAmAPromise"]`, this is
// considered an access to the string index, and a Promise is expected.
bag.iAmAPromise;
```
> feat(core): implement support for index signatures

- .coderabbit.yaml
Let's see if this works :)
cc @ematipico 
Watch the rabbit.
N/A
> chore: disable CodeRabbit review status

- .changeset/brave-camels-sin.md
- crates/biome_js_analyze/src/lint/correctness/use_exhaustive_dependencies.rs
- crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/issue6893.js
- crates/biome_js_analyze/tests/specs/correctness/useExhaustiveDependencies/issue6893.js.snap
Fixes #6893
The rule is used to find a first ancestor node that is a valid expression. However, some nodes including a shorthand object member doesn't have an expression inside. To catch these cases, I changed the logic to also find a reference identifier while searching the ancestors.
Added a snapshot test.
N/A
> fix(lint/useExhaustiveDependencies): correctly fix the dependency list from a shorthand object member

- .changeset/new-signs-tie.md
- crates/biome_js_analyze/src/react.rs
This updates the `is_global_react_import` function to include aliases for React. This is useful in cases where you are using the `reactClassic` jsxRuntime, but won't actually be importing from React, but a React-like library. The most prevalent (and only example I personally know of) would be the "@rbxts/react" package, which is used by hundreds of developers in the roblox-ts community.
See https://github.com/biomejs/biome/discussions/7487.
My pull request merely adds a hardcoded reference to "@rbxts/react". I do not foresee a significant amount of users otherwise ever having to modify this behavior to point to a separate package, so I believe what we have now will suffice.
> feat: add react library aliases

- Cargo.lock
- Cargo.toml
- crates/biome_js_analyze/src/assist/source/use_sorted_keys.rs
- crates/biome_ruledoc_utils/Cargo.toml
- crates/biome_ruledoc_utils/src/codeblock.rs
- crates/biome_ruledoc_utils/src/lib.rs
- crates/biome_test_utils/src/lib.rs
- xtask/rules_check/Cargo.toml
- xtask/rules_check/src/lib.rs
Creates a new crate `biome_ruledoc_utils`, and moved some of the code for parsing ruledoc code blocks there, as well as the logic for creating analyzer services evaluating the code blocks. This avoids a bunch of code duplication between codegen in the main repository and the website repository.
`just lint-rules` still works.
N/A
> chore: introduce ruledoc utils

- .changeset/crazy-steaks-mix.md
- .changeset/seven-beans-cough.md
- crates/biome_configuration/src/analyzer/linter/rules.rs
- crates/biome_configuration/src/generated/domain_selector.rs
- crates/biome_js_analyze/src/lint/correctness/no_children_prop.rs
- crates/biome_js_analyze/src/lint/correctness/no_react_prop_assignments.rs
- crates/biome_js_analyze/src/lint/security/no_dangerously_set_inner_html.rs
- crates/biome_js_analyze/src/lint/security/no_dangerously_set_inner_html_with_children.rs
- crates/biome_js_analyze/src/lint/style/use_component_export_only_modules.rs
- crates/biome_js_analyze/src/lint/suspicious/no_array_index_key.rs
- crates/biome_service/src/file_handlers/mod.rs
The following rules are now a part of the `react` domain. It will prevent the rules to be applied where it's not a React world.
- `lint/correctness/noChildrenProp`
- `lint/correctness/noReactPropAssignments`
- `lint/security/noDangerouslySetInnerHtml`
- `lint/security/noDangerouslySetInnerHtmlWithChildren`
- `lint/style/useComponentExportOnlyModules`
- `lint/suspicious/noArrayIndexKey`
Migration is unlikely needed as Biome will enable the `react` domain automatically when it detects React in the dependencies.
N/A
N/A
> feat(lint): move some rules to the `react` domain

- .changeset/gold-moments-move.md
- crates/biome_js_analyze/src/lint/performance/use_solid_for_component.rs
- crates/biome_js_analyze/tests/specs/performance/useSolidForComponent/invalid.tsx.snap
Fixes #7570
This PR corrects the diagnostic message for the `useSolidForComponent`  rule. The previous message was incorrect and did not properly highlight `<For />`  or include a working hyperlink to the documentation.
> fix: set correct string for diagnostic

- Cargo.lock
- crates/biome_formatter/src/lib.rs
- crates/biome_html_formatter/src/html/auxiliary/element.rs
- crates/biome_html_formatter/src/html/auxiliary/embedded_content.rs
- crates/biome_html_parser/tests/spec_tests.rs
- crates/biome_html_syntax/Cargo.toml
- crates/biome_html_syntax/src/attr_ext.rs
- crates/biome_html_syntax/src/element_ext.rs
- crates/biome_html_syntax/src/lib.rs
- crates/biome_html_syntax/src/script_type.rs
- crates/biome_json_formatter/src/lib.rs
- crates/biome_json_parser/src/lib.rs
- crates/biome_json_syntax/src/syntax_node.rs
- crates/biome_service/src/file_handlers/html.rs
- crates/biome_service/src/workspace.rs
- crates/biome_service/src/workspace/document.rs
- crates/biome_service/src/workspace/server.rs
- crates/biome_service/src/workspace/server.tests.rs
This adds the ability to format `<script type="importmap">` and `<script type="application/json>` tags in HTML files.
Contains minor refactoring to make it a little easier to add additional languages. Embedded nodes are now also collected in a single pass over the source tree, instead of one per embedded language.
Added a test. The rest should stay green.
@ematipico Does this require a changeset? I'm not sure to which extend the HTML formatting is stable yet...
> feat: implemented embedded JSON parsing

- .changeset/max-managers-mandate.md
- crates/biome_service/src/projects.rs
- crates/biome_service/src/settings.rs
- crates/biome_service/src/workspace/server.rs
Tiny optimisation to only query settings once when opening/indexing files. Previously, settings were queried in the `parse()` method, and separately for determining the max file size. For HTML files there was even a third query to pass settings to the embedded parsers, and similarly plain JavaScript files also had a third query to determine the `jsx_everywhere` setting. Now there's always only a single settings query.
This even fixes a tiny issue with max file size setting, which was previously always looked up in the root settings.
N/A
> perf: only query settings once

- .changeset/thin-cases-dig.md
- crates/biome_css_analyze/tests/specs/suspicious/noDuplicateProperties/invalid.css
- crates/biome_css_analyze/tests/specs/suspicious/noDuplicateProperties/invalid.css.snap
- crates/biome_css_analyze/tests/specs/suspicious/noDuplicateProperties/valid.css
- crates/biome_css_analyze/tests/specs/suspicious/noDuplicateProperties/valid.css.snap
- crates/biome_css_semantic/src/events.rs
- crates/biome_css_semantic/src/semantic_model/model.rs
Fixed https://github.com/biomejs/biome/issues/7470 and a false positive in `@starting-style` ([playground link](https://biomejs.dev/playground/?lineWidth=120&attributePosition=multiline&lintRules=noDuplicateProperties&analyzerFixMode=safeAndUnsafeFixes&code=WwBwAG8AcABvAHYAZQByAF0AOgBwAG8AcABvAHYAZQByAC0AbwBwAGUAbgAgAHsACgAgACAAbwBwAGEAYwBpAHQAeQA6ACAAMQA7AAoACgAgACAAQABzAHQAYQByAHQAaQBuAGcALQBzAHQAeQBsAGUAIAB7AAoAIAAgACAAIABvAHAAYQBjAGkAdAB5ADoAIAAwADsACgAgACAAfQAKAH0A&language=css)).
- Added more tests for `@container` and `@starting-style`.
- Existing tests pass.
> fix(noDuplicateProperties): false positives in `@container` and `@starting-style` at-rules

- crates/biome_analyze/src/rule.rs
- crates/biome_graphql_analyze/src/lint/style/use_graphql_naming_convention.rs
- `graphql-schema-linter` is it's own linter, not part of Eslint, so no `Eslint` prefix
- Correct `GraphQL-ESLint` documentation url
- Correct `GraphQL-ESLint` rule prefix is `@graphql-eslint/` not `graphql/`
> docs: fix correct graphql references

- .changeset/warm-insects-dress.md
- crates/biome_cli/tests/snapshots/main_commands_check/check_help.snap
- crates/biome_cli/tests/snapshots/main_commands_ci/ci_help.snap
- crates/biome_cli/tests/snapshots/main_commands_format/format_help.snap
- crates/biome_configuration/src/css.rs
- crates/biome_configuration/src/formatter.rs
- crates/biome_configuration/src/generated/domain_selector.rs
- crates/biome_configuration/src/graphql.rs
- crates/biome_configuration/src/html.rs
- crates/biome_configuration/src/javascript/formatter.rs
- crates/biome_configuration/src/json.rs
- crates/biome_configuration/src/overrides.rs
- crates/biome_formatter/src/lib.rs
- crates/biome_formatter/src/printer/mod.rs
- crates/biome_formatter_test/src/spec.rs
- crates/biome_grit_patterns/src/grit_target_language/css_target_language/generated_mappings.rs
- crates/biome_js_formatter/tests/specs/js/module/line-ending/auto/line_ending.js
- crates/biome_js_formatter/tests/specs/js/module/line-ending/auto/line_ending.js.snap
- crates/biome_js_formatter/tests/specs/js/module/line-ending/auto/options.json
- packages/@biomejs/backend-jsonrpc/src/workspace.ts
- packages/@biomejs/biome/configuration_schema.json
Related to https://github.com/biomejs/biome/discussions/7598, this implements suggestion 3, "auto" as a lineEnding format, without making it the default. Without this feature, it is very difficult to run Biome against cross-platform environments such as Electron apps, because `biome check` in CI will inevitably fail either macOS or Windows, there is no correct option other than completely disabling the formatter in CI, or using `.gitattributes` to force the repo to be checked out in LF
Unit tests
> feat: add 'auto' mode to lineEndings

- .changeset/big-pans-begin.md
- crates/biome_css_analyze/src/keywords.rs
- crates/biome_css_analyze/src/lint/correctness/no_unknown_pseudo_class.rs
- crates/biome_css_analyze/src/utils.rs
- crates/biome_css_analyze/tests/spec_tests.rs
- crates/biome_css_analyze/tests/specs/correctness/noUnknownPseudoClass/validGlobal.css
- crates/biome_css_analyze/tests/specs/correctness/noUnknownPseudoClass/validGlobal.css.snap
> fix(css_analyze): handle CSS Modules pseudo-class 'local' in NoUnknownPseudoClass rule (#6981)

- crates/biome_service/src/file_handlers/css.rs
My last [PR introduced](https://github.com/biomejs/biome/pull/5814) a regression. This PR fixes it 
The previous failing test `should_apply_fixes_to_embedded_languages` should pass
> fix: incorrect logic for CSS fix all
